### ISSUE TITLE
[XI] App failed to launch on device with Dyld Message: Library not loaded: @rpath/libmonosgen-2.0.dylib

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#3811] opened 2018-03-23 20:51 UTC
### Steps to Reproduce

1. Build and run monotouch-test on device with Debug and fast dev disabled. App runs successfully on device.
2. Build and run monotouch-test device with Debug and fastdev enabled.

### Expected Behavior
App should launch successfully
### Actual Behavior
App got installed but failed to launch. Device Log showed: 
Dyld Error Message:
Dyld Message: Library not loaded: @rpath/libmonosgen-2.0.dylib

Cleaning the solution fixed the launching issue.

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.4 (build 1033)
Installation UUID: 74c37335-5878-4fa7-8f71-09bc48b661c5
Runtime:
	Mono 5.8.0.129 (2017-10/835a98d8559) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000129

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.2.0.15 (Visual Studio Community)
Android SDK: /Users/gourikumari/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)

SDK Tools Version: 25.2.3
SDK Platform Tools Version: 25.0.1
SDK Build Tools Version: 25.0.1

Java SDK: /usr
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.2.0.20 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.10.0.43 (Visual Studio Community)
Hash: 3627e873
Branch: d15-7
Build date: 2018-03-21 22:33:57-0400

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704001033
Git revision: 053991068f3c88497d3e5cc52fe7fdf57c28b62f
Build date: 2018-02-28 05:02:28-05
Xamarin addins: cc3283953e0af0b8bfab1bdfdf847d9e403c4606
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Thu Jun 15 17:36:27 PDT 2017
    root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Gist Ide Information 1.1.0
Internet of Things (IoT) development (Preview) 7.1


```

### Build Logs

Build Log: https://gist.github.com/GouriKumari/3f288a9f1f4fef162edf6c820a4f2c89
~~Device Log~~ Crash Report: https://gist.github.com/GouriKumari/d379eaccd638e056547a43b677dd12ef

> VS bug [#591135](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/591135)

**Comment by mandel-macaque** [comment] 2018-03-26 16:47
I can confirm this with master, got and issue launching the app, version into: https://gist.github.com/mandel-macaque/997cea906e0f9dff0f34fe26cdef79ff

Will add more comments regarding 15-7 and 15-6

**Comment by mandel-macaque** [comment] 2018-03-27 23:29
Confirming this as a regression, the tests do work on d15-6.

**Comment by spouliot** [comment] 2018-03-28 21:16
I could not duplicate this with d15-7.

@GouriKumari please confirm the steps, I did
- Clean monotouchtest
- Start Debugging Item
app works on device
- Enable incremental builds checkbox in the project options
- Start Debugging Item
app still works on device

Also your link above was the crash report (good) but we're missing the device logs.

**Comment by GouriKumari** [comment] 2018-03-29 15:10
>>Also your link above was the crash report (good) but we're missing the device logs.
I mentioned it as Device Log, since I got from Xcode-> Window->Devices->View Device Logs.

**Comment by GouriKumari** [comment] 2018-03-29 16:53
>>@GouriKumari please confirm the steps, I did . 
Those are the steps that I  used to reproduce the issue. 

I rechecked it again and  I am unable to reproduce the issue with latest d15-7 build. Test is launching successfully on device with fastdev disabled and enabled. 

I think we should remove this from d15-7 milestone.

**Comment by DeveloperACE** [comment] 2018-04-09 05:32
Im getting a similar error:
```Launched application '_____' on '_____' with pid 10426
Application '_____' terminated.
dyld: Library not loaded: @rpath/libmonosgen-2.0.dylib
  Referenced from: /var/containers/Bundle/Application/37A64A51-F2A5-41EC-B3EC-7AEFD2B3E42A/_____.iOS.app/_____.iOS
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/37A64A51-F2A5-41EC-B3EC-7AEFD2B3E42A/_____.iOS.app/libmonosgen-2.0.dylib: required code signature missing for '/private/var/containers/Bundle/Application/37A64A51-F2A5-41EC-B3EC-7AEFD2B3E42A/_____.iOS.app/libmonosgen-2.0.dylib'
```


here's my Environment info:
```=== Visual Studio Community 2017 for Mac ===

Version 7.4.2 (build 12)
Installation UUID: ba213029-c0c0-4c24-a02d-cdbc18ebcdd3
Runtime:
	Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508010000

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Version: 2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.2.0.16 (Visual Studio Community)
Android SDK: /Users/ace/Library/Android/sdk
	Supported Android versions:
		5.0 (API level 21)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.2.1.28 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.9.1.24 (Visual Studio Community)
Hash: f62de472
Branch: xcode9.3
Build date: 2018-03-29 19:30:53-0400

=== Build Information ===

Release ID: 704020012
Git revision: 0d8e3f0a4d683771f17959739956fa09c7ba21e3
Build date: 2018-03-30 10:45:17-04
Xamarin addins: 958839ea56ab1e331caf7c92b6ad50fb9e6ee9d2
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.2
Darwin 17.3.0 Darwin Kernel Version 17.3.0
    Thu Nov  9 18:09:22 PST 2017
    root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

MvvmCross Template pack 2.0.1

```

the device I am testing on is an iPhone 8 running the latest public non-beta iOS. 


Hope this helps

**Comment by rolfbjarne** [comment] 2018-05-23 13:15
I'm closing this one, since it seems to be unreproducible.

Feel free to reopen if it happens again.

**Closed by rolfbjarne** 2018-05-23 13:15 UTC
Labels: bug, iOS, need-info, vs-sync

**Comment by mofdaddy** [comment] 2019-01-10 21:30
I am seeing this issue with Xamarin.iOS.MaterialComponents 72.2.0 from Nuget when installing app from either AppStore or TestFlight on some iOS9 and 10 devices.
When debugging it works fine.
When distributing test versions through HockeyApp it works fine.
AdHoc Distribution builds using the **same build configuration** as for the AppStore works fine!
However, builds downloaded from AppStore or TestFlight crashes.
How can this be??

**Crash log:**

{"bug_type":"109","os_version":"iPhone OS 10.2.1 (14D27)","build_version":"717","timestamp":"2019-01-09 11:12:26.64 +0100","is_beta":true,"app_name":"DBUFodbold_App_iOS","app_cohort":"2|date=1547028000000&sf=143458&tid=5c7ef3b0ad16abe7088e14ef3dbac44602ede17ee7c8f08ca6b462748e6cf545&ttype=i","bundleID":"dk.dbu.Fodbold","incident_id":"0D90F32D-C531-4E28-AF5C-A1E1E7B03069","name":"DBUFodbold_App_iOS","is_first_party":false,"app_version":"3.10.3","share_with_app_devs":true,"slice_uuid":"35fec473-b175-36ad-8209-1dd81bf2fb80","adam_id":521095398}
Incident Identifier: 0D90F32D-C531-4E28-AF5C-A1E1E7B03069
Beta Identifier:    A1784ECE-9789-4E51-803E-7303B842CD1C
Hardware Model:      iPhone5,2
Process:            DBUFodbold_App_iOS [494]
Path:                /private/var/containers/Bundle/Application/C5A1EEF4-B745-4EEB-B88A-EEAEC3F16292/DBUFodbold_App_iOS.app/DBUFodbold_App_iOS
Identifier:          dk.dbu.Fodbold
Version:            717 (3.10.3)
Beta:                YES
Code Type:          ARM (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:          dk.dbu.Fodbold [527]


Date/Time:          2019-01-09 11:12:26.5316 +0100
Launch Time:        2019-01-09 11:12:25.0000 +0100
OS Version:          iPhone OS 10.2.1 (14D27)
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Library not loaded: @rpath/MaterialComponents.framework/MaterialComponents | Referenced from: /var/containers/Bundle/Application/C5A1EEF4-B745-4EEB-B88A-EEAEC3F16292/DBUFodbold_App_iOS.app/DBUFodbold_App_iOS | Reason: image not found
Triggered by Thread:  0

Filtered syslog:
None found

Thread 0 Crashed:
0  dyld                          0x03a913e4 0x3a6f000 + 140260
1  dyld                          0x03a9104a 0x3a6f000 + 139338
2  dyld                          0x03a91084 0x3a6f000 + 139396
3  dyld                          0x03a72e72 0x3a6f000 + 15986
4  dyld                          0x03a75602 0x3a6f000 + 26114
5  dyld                          0x03a701d0 0x3a6f000 + 4560
6  dyld                          0x03a70040 0x3a6f000 + 4160

Thread 0 crashed with ARM Thread State (32-bit):
    r0: 0x00000000    r1: 0x00000000      r2: 0x00000000      r3: 0x03bd8e28
    r4: 0x000000bd    r5: 0x03bd8a28      r6: 0x00000000      r7: 0x03bd89f4
    r8: 0x00000000    r9: 0x000000bd    r10: 0x00000000    r11: 0x00000000
    ip: 0x00000209    sp: 0x03bd89b4      lr: 0x03a9104b      pc: 0x03a913e4
  cpsr: 0x40000010

Binary Images:
0xf000 - 0x33d2fff DBUFodbold_App_iOS armv7  <35fec473b17536ad82091dd81bf2fb80> /var/containers/Bundle/Application/C5A1EEF4-B745-4EEB-B88A-EEAEC3F16292/DBUFodbold_App_iOS.app/DBUFodbold_App_iOS
0x3a6f000 - 0x3a9afff dyld armv7s  <898b6b42ae3b3ffb8de9a96b7071f49d> /usr/lib/dyld

EOF
