### ISSUE TITLE
Can't build a Xamarin.Mac app with .net 6, it says  Could not find Xamarin.Mac in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current

### ISSUE THREAD

**Issue by psantosl** [xamarin/xamarin-macios#11005] opened 2021-03-26 21:33 UTC
### Steps to Reproduce

How to create an empty xamarin.macios app in .net 6 preview2:

Install dotnet SDK: https://download.visualstudio.microsoft.com/download/pr/5e10dc75-294e-49f4-972e-218ae86191a3/e46d3533c30c8a864252a334820263a9/dotnet-sdk-6.0.100-preview.2.21155.3-osx-x64.pkg
Install xamarin.macios for .net6: https://bosstoragemirror.blob.core.windows.net/wrench/main/98c8649d0c7d1e3c4c8d8d09e022befa853fb1e7/4541181/package/Microsoft.macOS.Bundle.11.1.100-ci.main.1245.pkg
enable the workload:
export MSBuildEnableWorkloadResolver=true

create a new macos app:
dotnet new macos

copy NuGet.config and global.json to your project folder from here: https://github.com/dotnet/net6-mobile-samples
Fix Xcode CLI tools:
xcode-select -p
sudo xcode-select --switch /Applications/Xcode.app

Add the following line to the csproj file
<RuntimeIdentifier>osx-x64</RuntimeIdentifier>

dotnet build

### Expected Behavior
It builds

### Actual Behavior
```
dotnet build -bl                                                                                                                                              
Microsoft (R) Build Engine version 16.10.0-preview-21126-01+6819f7ab0 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/local/share/dotnet/sdk/6.0.100-preview.2.21155.3/MSBuild.dll -bl -consoleloggerparameters:Summary -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/usr/local/share/dotnet/sdk/6.0.100-preview.2.21155.3/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/usr/local/share/dotnet/sdk/6.0.100-preview.2.21155.3/dotnet.dll -maxcpucount -restore -verbosity:m ./xamtest.csproj
  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/11.1.100-ci.main.1245/tools/msbuild/macOS/Xamarin.Shared.targets(891,3): error : Could not find Xamarin.Mac in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current. [/Users/pablo/wkspaces/xamtest/xamtest.csproj]
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/11.1.100-ci.main.1245/tools/msbuild/macOS/Xamarin.Shared.targets(891,3): error :          [/Users/pablo/wkspaces/xamtest/xamtest.csproj]

Build FAILED.

/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/11.1.100-ci.main.1245/tools/msbuild/macOS/Xamarin.Shared.targets(891,3): error : Could not find Xamarin.Mac in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current. [/Users/pablo/wkspaces/xamtest/xamtest.csproj]
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/11.1.100-ci.main.1245/tools/msbuild/macOS/Xamarin.Shared.targets(891,3): error :          [/Users/pablo/wkspaces/xamtest/xamtest.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.38

```
### Environment

```
```

### Build Logs
[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/6214447/msbuild.binlog.zip)

**Comment by filipnavara** [comment] 2021-03-27 06:50
Sounds like variation of https://github.com/xamarin/xamarin-macios/issues/10827

**Comment by mandel-macaque** [comment] 2021-04-01 13:40
@filipnavara  it is, thanks for taking a look, will close as a duplicate of #10827

**Closed by mandel-macaque** 2021-04-01 13:40 UTC
