### ISSUE TITLE
Mac Catalyst MAUI build Application Name appearing as Assembly Name - Causing Apple Rejection

### ISSUE THREAD

**Issue by PureWeen** [xamarin/xamarin-macios#21478] opened 2024-10-18 17:09 UTC
---
**Issue moved from dotnet/maui#25364**
- Please respond to @caliberdigitalllc.

---

_From @caliberdigitalllc on Friday, October 18, 2024 2:07:31 AM_

### Description

I am producing a Mac Catalyst build for release with the following command:

```
dotnet publish -f net9.0-maccatalyst -c Release \
    -p:ArchiveOnBuild=true \
    -p:CreatePackage=true \
    -p:EnableCodeSigning=true \
    -p:CodesignKey="Apple Distribution: AlzBetter LLC (8DVSMQ7G8N)" \
    -p:CodesignProvision="MacOS Distribution" \
    -p:CodesignEntitlements="Platforms/MacCatalyst/Entitlements.plist" \
    -p:EnablePackageSigning=true
```

I have these keys in info.plist:
```
<key>CFBundleName</key>
<string>AlzBetter Coach</string>
<key>CFBundleDisplayName</key>
<string>AlzBetter Coach</string>
```

I have this key in CSPROJ:
`<ApplicationTitle>AlzBetter Coach</ApplicationTitle>`

But when I deploy the build out to the app store, when installed, it installs as "AbMobileMaui" which is the assembly/project name. Apple is refusing to release the app because the app name doesn't match the actual app name (AlzBetter Coach) due to it installing as AbMobileMaui.

What setting/key am I missing here? The iOS build installs perfectly fine as the right app name.

This has been like this for several .net releases - I am just reporting it now.

### Steps to Reproduce

Create a mac catalyst app, build in release mode, release to testflight/app store.

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

**Comment by rolfbjarne** [comment] 2024-10-21 15:19
This is a duplicate of #20615.

As a workaround, I believe you can set the `_AppBundleName` property on the command line to the desired value:

```shell
$ dotnet publish ... /p:_AppBundleName="AlzBetter Coach"
```

Can you try that and see if it works for you?

**Comment by caliberdigitalllc** [comment] 2024-10-22 22:43
> This is a duplicate of #20615.
> 
> As a workaround, I believe you can set the `_AppBundleName` property on the command line to the desired value:
> 
> ```shell
> $ dotnet publish ... /p:_AppBundleName="AlzBetter Coach"
> ```
> 
> Can you try that and see if it works for you?

So I tried both "/p" and "-p" and both of them throw an error. "-p" says command not found and "/p" says no such directory.

tried:
```
dotnet publish -f net9.0-maccatalyst -c Release \
    -p:ArchiveOnBuild=true \
    -p:CreatePackage=true \
    -p:EnableCodeSigning=true \
    -p:CodesignKey="Apple Distribution: AlzBetter LLC (8DVSMQ7G8N)" \
    -p:CodesignProvision="MacOS Distribution" \
    -p:CodesignEntitlements="Platforms/MacCatalyst/Entitlements.plist" \
    -p:EnablePackageSigning=true
    /p:_AppBundleName="AlzBetter Coach"
```
and

```
dotnet publish -f net9.0-maccatalyst -c Release \
    -p:ArchiveOnBuild=true \
    -p:CreatePackage=true \
    -p:EnableCodeSigning=true \
    -p:CodesignKey="Apple Distribution: AlzBetter LLC (8DVSMQ7G8N)" \
    -p:CodesignProvision="MacOS Distribution" \
    -p:CodesignEntitlements="Platforms/MacCatalyst/Entitlements.plist" \
    -p:EnablePackageSigning=true
    -p:_AppBundleName="AlzBetter Coach"
```

**Comment by rolfbjarne** [comment] 2024-10-23 08:55
You're missing a backslash at the end of the previous argument:

```
	[...]
    -p:EnablePackageSigning=true \
    -p:_AppBundleName="AlzBetter Coach"
```

**Comment by caliberdigitalllc** [comment] 2024-10-23 11:29
> You're missing a backslash at the end of the previous argument:
> 
> ```
> 	[...]
>     -p:EnablePackageSigning=true \
>     -p:_AppBundleName="AlzBetter Coach"
> ```

I knew that, I was just testing you. :) Anyhow, that seems to break something at the end of the compile:

/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk.net9.0_18.0/18.0.9600-net9-rc2/tools/msbuild/iOS/Xamarin.Shared.targets(2839,3): error : 
      dsymutil exited with code 1:
      error: cannot parse the debug map for '/Users/mitch/Development/abmobile-maui/bin/Release/net9.0-maccatalyst/osx-x64/AlzBetter Coach.app/Contents/MacOS/AbMobileMaui': No such file or directory

If I leave that parameter off, it builds fine (with the wrong name obviously)

**Comment by rolfbjarne** [comment] 2024-10-23 19:02
OK, I can reproduce it, and I think I may have a workaround:

Edit your Info.plist (or create a new one if you don't have one), and then add this:

```xml
<key>CFBundleExecutable</key>
<string>AlzBetter Coach</string>
```

**Comment by caliberdigitalllc** [comment] 2024-10-23 20:48
I get the same error unfortunately. 

/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk.net9.0_18.0/18.0.9600-net9-rc2/tools/msbuild/iOS/Xamarin.Shared.targets(2839,3): error : 
      dsymutil exited with code 1:
      error: cannot parse the debug map for '/Users/mitch/Development/abmobile-maui/bin/Release/net9.0-maccatalyst/osx-x64/AbMobileMaui.app/Contents/MacOS/AlzBet
      ter Coach': No such file or directory

It seems to change the output file name and because it doesn't match the assembly name, it's failing. If I remove that extra key/string, it goes back to the old name and builds fully.

**Comment by rolfbjarne** [comment] 2024-10-24 17:04
Can you get an [MSBuild binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) from the failing build?

**Comment by caliberdigitalllc** [comment] 2024-10-24 17:05
> Can you get an [MSBuild binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) from the failing build?

yep, I'll grab that this evening for you.

**Comment by caliberdigitalllc** [comment] 2024-10-25 00:16
@rolfbjarne attached
[msbuild.binlog.gz](https://github.com/user-attachments/files/17514141/msbuild.binlog.gz)

**Comment by rolfbjarne** [comment] 2024-10-25 09:50
> @rolfbjarne attached [msbuild.binlog.gz](https://github.com/user-attachments/files/17514141/msbuild.binlog.gz)

It looks like you're not passing this to `dotnet publish` anymore:

    -p:_AppBundleName="AlzBetter Coach"

which you still need to do.

To recap, do all of the following:

1. Pass `-p:_AppBundleName="AlzBetter Coach"` to `dotnet publish`.
2. Add `CFBundleExecutable=AlzBetter Coach` in the Info.plist.
3. Pass `-bl:msbuild.binlog` to `dotnet publish` as well, and upload msbuild.binlog if it still doesn't work.

**Comment by caliberdigitalllc** [comment] 2024-10-26 14:06
> > @rolfbjarne attached [msbuild.binlog.gz](https://github.com/user-attachments/files/17514141/msbuild.binlog.gz)
> 
> It looks like you're not passing this to `dotnet publish` anymore:
> 
> ```
> -p:_AppBundleName="AlzBetter Coach"
> ```
> 
> which you still need to do.
> 
> To recap, do all of the following:
> 
> 1. Pass `-p:_AppBundleName="AlzBetter Coach"` to `dotnet publish`.
> 2. Add `CFBundleExecutable=AlzBetter Coach` in the Info.plist.
> 3. Pass `-bl:msbuild.binlog` to `dotnet publish` as well, and upload msbuild.binlog if it still doesn't work.

That  did the trick, thanks. At least we know the fix for it for a future .net release :)

**Comment by rolfbjarne** [comment] 2024-10-28 17:56
That's great that it works now!

I'll close this as a duplicate of https://github.com/xamarin/xamarin-macios/issues/20615.

Happy coding!

**Closed by rolfbjarne** 2024-10-28 17:56 UTC
Labels: need-attention
