### ISSUE TITLE
[XM] 'obj/***/copySceneKitAssets' folder consists '.app' file

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#5280] opened 2018-12-17 11:31 UTC
### Steps to Reproduce

1. Download a [sample](https://github.com/xamarin/mac-ios-samples/tree/master/SceneKitReel) 
2. Open and build it
3. Open `obj/Debug/copySceneKitAssets` folder

### Expected Behavior
There is no `.app` file 

### Actual Behavior
There is `.app` file 

### Environment

1. VSfM
https://gist.github.com/mykyta-bondarenko-gl/8964066270f49003a58af63630c1f6ea

### Build Logs

1. Build Output
https://gist.github.com/mykyta-bondarenko-gl/7948080a3357a482411a1ab782a74953

### Example Project 

[SceneKitReel](https://github.com/xamarin/mac-ios-samples/tree/master/SceneKitReel)

**Comment by mandel-macaque** [comment] 2018-12-17 23:14
I can confirm the issue, after a build I have the following:

iMac:SceneKitReel mandel$ ls SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/
models/    particles/ textures/
iMac:SceneKitReel mandel$ tree -f SceneKitReelMac/obj/Debug/copySceneKitAssets/ | grep .app
└── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app
    └── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets
        ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/models
        │   ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/models/bac.dae
        │   ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/models/firetruck.dae
        │   ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/models/globe.dae
        │   ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/models/ship.dae
        │   └── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/models/train_flat.dae
        ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/particles
        │   ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/particles/bokeh.scnp
        │   ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/particles/bubbles.scnp
        │   ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/particles/fire.scnp
        │   ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/particles/fire2.scnp
        │   ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/particles/plok.scnp
        │   ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/particles/plop.scnp
        │   ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/particles/reactor.scnp
        │   ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/particles/smoke.scnp
        │   └── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/particles/sparks.scnp
        └── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/textures
            ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/textures/bokeh.png
            ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/textures/envmap.jpg
            ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/textures/fire.png
            ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/textures/fire2.tiff
            ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/textures/fire3.png
            ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/textures/frontTruck.png
            ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/textures/plok.png
            ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/textures/sideTruck.png
            ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/textures/smoke.png
            ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/textures/spark.png
            ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/textures/train_wood.jpg
            ├── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/textures/tspark.png
            └── SceneKitReelMac/obj/Debug/copySceneKitAssets/SceneKitReelMac.app/assets.scnassets/textures/water2.png

I have the following [env](https://gist.github.com/mandel-macaque/105ba26d7de274eeb2139a229376b91d).

**Comment by spouliot** [comment] 2018-12-18 02:39
From @mandel-macaque post it looks like it's not the whole .app - but just the subset of the asset catalog which could just be for (temporary) editing purpose. @jstedfast or @VincentDondain could confirm that.

@mykyta-bondarenko-gl was there any other problem ? or did you just found it strange ? right now the `copy` prefix really makes me think it's genuine.

**Comment by jstedfast** [comment] 2018-12-18 12:50
I think this was a change @rolfbjarne recently made due to a new requirement by Apple's toolchain where it expects the directory it is dumping stuff into is the app bundle.

Anyway, this is safe to ignore.

**Comment by mandel-macaque** [comment] 2019-02-20 18:00
@mykyta-bondarenko-gl closing as per comment from @jstedfast

**Closed by mandel-macaque** 2019-02-20 18:00 UTC
Labels: macOS
