### ISSUE TITLE
NSUrlSessionHandler and CookieContainer don't play well together

### ISSUE THREAD

**Issue by MihaMarkic** [xamarin/xamarin-macios#9817] opened 2020-10-08 07:48 UTC
### Steps to Reproduce

1. Run the code below in an iOS project targeting min iOS 11 (no idea about others)

```
var handler = new NSUrlSessionHandler { CookieContainer = new CookieContainer() };
var client = new HttpClient(handler);
await client.GetStringAsync("https://www.globus.ch");
```

### Expected Behavior

No exceptions

### Actual Behavior

System.Net.CookieException: 'An error occurred when parsing the Cookie header for Uri 'https://www.globus.ch/'.'
Seems like the header `set-cookie: globus-session=[SESSIONID]; Path=/` is the culprit.
If I don't use a CookieContainer or I use a HttpClientHandler, then it works as expected.

### Environment

```
Microsoft Visual Studio Community 2019
Version 16.7.5
VisualStudio.16.Release/16.7.5+30523.141
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA212
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.7.532.28833
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2035807+72d099b977d3a85e65fa3b0614ca8cfc803fef02
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.7.532.28833
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.7.532.28833
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.7.532.28833
Azure Functions and Web Jobs Tools

Bundler & Minifier   2.8.396
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

C# Tools   3.7.0-6.20459.4+7ee7c540e3bf19765695b1331c946ddf986d1516
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CodeRush for Roslyn   20.1.8.0
DevExpress CodeRush for Roslyn package.

CodeRush for Roslyn Tool Windows   20.1.8.0
DevExpress CodeRush for Roslyn Tool Windows package.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

ConvertToDevExtremeCommand Extension   1.0
ConvertToDevExtremeCommand Visual Studio Extension Detailed Info

CreateLayoutWizard   1.0
Create layout wizard.

Devart Template Editor   1.0.11.0
Editor for T4 and Devart template files with syntax coloring and IntelliSense.

DevExpress Reporting Extension   1.0
A Visual Studio extension that invokes the Report Designer editor for report definition REPX files.

DevExpress Reporting Tools Extension   1.0
Extends Visual Studio with tools required for the Report Designer editor.

DevExpress.DeploymentTool   1.0
A useful tool for deploying DevExpress assemblies.

DevExpress.Win.LayoutAssistant Extension   1.0
DevExpress.Win.LayoutAssistant Visual Studio Extension Detailed Info

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub.VisualStudio   2.11.106.19330
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

ILSpy.AddIn   1.0
Integration of the ILSpy Decompiler into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30701.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.79+ge3567815aa.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.7.5 (112c7bc)
Support for debugging Mono processes with Visual Studio.

NCrunch   
Continuous Testing Tool for .NET
Copyright � 2010-2018 Remco Software Ltd

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62008.03130
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.20702.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.7.0-6.20459.4+7ee7c540e3bf19765695b1331c946ddf986d1516
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20361.3+3ef6f0b514198c0bfa6c2c09fefe41a740b024d5
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

WiX Toolset Visual Studio Extension   1.0.0.4
WiX Toolset Visual Studio Extension version 1.0.0.4
Copyright (c) .NET Foundation and contributors. All rights reserved.

Xamarin   16.7.000.452 (d16-7@033b1a7)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.7.0.495 (remotes/origin/d16-7@79c0c522c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.7.85 (1bcbbdf)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.0.2.0 (d16-7/025fde9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-7@1f3388a
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f


Xamarin.iOS and Xamarin.Mac SDK   14.0.0.0 (7ec3751a1)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Example Project (If Possible)

Add the code below to a new iOS project:
```

var handler = new NSUrlSessionHandler { CookieContainer = new CookieContainer() };
var client = new HttpClient(handler);
await client.GetStringAsync("https://www.globus.ch");
```

**Comment by chamons** [comment] 2020-10-08 18:41
I'm having trouble reproducing this.

```
		[Export ("application:didFinishLaunchingWithOptions:")]
		public bool FinishedLaunching (UIApplication application, NSDictionary launchOptions)
		{
			var handler = new NSUrlSessionHandler { CookieContainer = new CookieContainer () };
			var client = new HttpClient (handler);
			client.GetStringAsync ("https://www.globus.ch").ContinueWith (s => Console.WriteLine (s.Result));
			return true;
		}
```

Tried: iOS 14 sim, iOS 12.4 sim. iOS 10.3.2 device. and iOS 11.0.3 device.

Please attach a full sample project, so i can what configuration difference we're seeing.

**Comment by MihaMarkic** [comment] 2020-10-09 12:13
@chamons 
You're right, it's not happening anymore on said URL but it is still happening on an internal one which I can't share. I'll try to create a reliable repro and will let you know ASAP.

**Comment by mandel-macaque** [comment] 2020-10-12 20:24
@MihaMarkic might be that your internal url is not setting the cookie correctly or is not being parsed. Rather than trying to find a repo url, just show us the format of the set-cookie header, since we can easily create a small webapp that sets the cookie in the same manner. It very well can be that the webframework you are using is the culprit for example.

**Comment by MihaMarkic** [comment] 2020-10-12 20:47
@mandel-macaque I wish it was that easy. So far I tried to reproduce it but without success. Still trying to figure out the repro server.

**Comment by tj-devel709** [comment] 2020-11-20 20:43
Hi, since we haven't been able to reproduce and have not yet received more information, we will close this issue.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!

**Closed by tj-devel709** 2020-11-20 20:43 UTC
Labels: iOS, need-info
