### ISSUE TITLE
RealityKit unavailable

### ISSUE THREAD

**Issue by Jamesmc26** [xamarin/xamarin-macios#15112] opened 2022-05-24 20:16 UTC
Hi there, big fan of your works.
I am doing a project in Xamarin in which I need some realityKit Features - Currently exclusive to Swift.
In particular I need access to the ARView and the features this comes with.
I was wondering if you might be able to help and make this available within your library.

Thanks a lot,
Jim

**Comment by chamons** [comment] 2022-05-26 20:36
Thanks for the feedback.

This is a duplicate of https://github.com/xamarin/xamarin-macios/issues/6239.

RealityKit unfortunately is a swift-only framework, and thus very tricky to bind.

You may be able to work around this by creating a Swift library of your own exposing a simple API doing what you need, then marking it as objective-c and binding it as a normal objective-c library.

I am going to close this as a duplicate of the previous issue.

**Closed by chamons** 2022-05-26 20:36 UTC
