### ISSUE TITLE
Receive HE0042 Error when running iOS Xamarin.Forms app

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#15361] opened 2022-06-27 17:00 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Receive-HE0042-Error-when-running-iOS-Xa/10074509)._

---
I’m working on samples for the azure-mobile-apps library (https://github.com/azure/azure-mobile-apps).  The Xamarin.iOS app works fine in VS Mac 2022 Preview.  however, when starting the Xamarin.Forms.iOS version, I get the error:  HE0042: Could not launch the app ‘com.companyname.TodoApp.Forms’ on the device ‘iOS 15.5 (19F70) - iPhone SE (3rd generation)’: Application launch for 'com.companyname.TodoApp.Forms' did not return a valid pid nor a launch error.

The simulator is started; the app is deployed to the simulator, but the app is not started.  Starting the app manually on the simulator works just fine.

Build looks to work fine - just one warning: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the &quot;AutoGenerateBindingRedirects&quot; property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.

---
#### Rolf Kvinge [MSFT] on 6/17/2022, 00:59 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by rolfbjarne** [comment] 2022-06-28 08:05
This is probably a duplicate of https://github.com/xamarin/xamarin-macios/issues/14834, so closing as such.

**Closed by rolfbjarne** 2022-06-28 08:05 UTC
