### ISSUE TITLE
Unable to Install System.Threading.Overlapped

### ISSUE THREAD

**Issue by HobDev** [xamarin/xamarin-macios#3138] opened 2017-12-25 05:51 UTC
### Steps to Reproduce

1. Create new xamarin.forms project
2. Add Xamarin.Mac cocoa project
3. Install SerialPortStreamCore nuget to it.

### Expected Behavior
The nuget should be added successfully to the project

### Actual Behavior
The nuget adds itself successfully to netstandard shared project. But fails to add to Xamarin.Mac. I need this package for Serial port programming. 

### Environment
Visual Studio for Mac Community version 7.3.2(build 12)
Xamarin.Mac Version: 4.0.0.214 (Visual Studio Community)
Operating System: Mac OS X 10.13.2

```
=== Visual Studio Community 2017 for Mac ===

Version 7.3.2 (build 12)
Installation UUID: ff0b8bd1-b591-48e7-8748-666f21ab8827
Runtime:
	Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010007

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.3
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.0.3/Sdks
SDK Versions:
	2.0.3
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.iOS ===

Version: 11.6.1.2 (Visual Studio Community)
Hash: 6857dfcc
Branch: xcode9.2
Build date: 2017-12-04 21:20:41-0500

=== Xamarin.Android ===

Version: 8.1.0.25 (Visual Studio Community)
Android SDK: /Users/paramjit/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.0
SDK Build Tools Version: 27.0.1

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.3.2
Hash: 461f09a
Branch: 1.3-release
Build date: Tue, 03 Oct 2017 18:26:57 GMT
Client compatibility: 1

=== Xamarin.Mac ===

Version: 4.0.0.214 (Visual Studio Community)

=== Build Information ===

Release ID: 703020012
Git revision: 7d0c9d7ad46b125cf4b7bbf9532c0531b6433ce6
Build date: 2017-12-12 14:03:18-05
Xamarin addins: 6dddaa49fbecb2695fcdcd6b712eb269e288518c
Build lane: monodevelop-lion-d15-5

=== Operating System ===

Mac OS X 10.13.2
Darwin 17.3.0 Darwin Kernel Version 17.3.0
    Thu Nov  9 18:09:22 PST 2017
    root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

MFractor 3.03.00
Internet of Things (IoT) development (Preview) 7.1


```

### Build Logs

Package 'System.Threading.Overlapped.4.3.0 : Microsoft.NETCore.Platforms [1.1.0, ), System.Resources.ResourceManager [4.3.0, ), System.Runtime [4.3.0, ), System.Runtime.Handles [4.3.0, )' does not exist in project 'CallTech.MacOS'

Could not install package 'System.Threading.Overlapped 4.3.0'. You are trying to install this package into a project that targets 'Xamarin.Mac,Version=v2.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by VincentDondain** [comment] 2018-01-03 22:37
Hi, what is your Mac project's target framework?

I'm not sure *yet (I'm investigating)* what exactly in the `System.Threading.Overlapped` package is causing issues when installing on Xamarin.iOS or Xamarin.Mac Mobile but to work around the issue you can change the **Target Framework Version** to **4.6.2** *(Project Options > Build > General)*.

That will let you install `SerialPortStreamCore` (and `System.Threading.Overlapped` by extension).

**Comment by VincentDondain** [comment] 2018-01-04 17:42
Alright so I figured out exactly how `SerialPortStreamCore` and `System.Threading.Overlapped` are broken.

1. `System.Threading.Overlapped` is missing a `/lib/netstandard1.3` folder with the compatible dll. Therefore it makes sense it doesn't work with either Xamarin.iOS or Xamarin.Mac (Mobile) projects because it simply isn't compatible with netstandard 1.3 as is.

I sent an email to the owner of the package, you can do the same if you want, here it is:

```
You sent the following message via NuGet Gallery:

User VincentDondain <vidondai@microsoft.com> sends the following message to the owners of Package 'System.Threading.Overlapped'.

Hi,

There seem to be a problem with this package. It states that it supports netstandard1.3 but /lib doesn't include a netstandard1.3 folder (unlike /ref). Therefore the package cannot be properly installed on Xamarin.iOS/Xamarin.Mac projects (compatible with netstandard1.3).

See install logs: https://gist.github.com/VincentDondain/b02ea70a8dabeab3d5eb35b9b57d763e
Thanks,

Vincent.
```

2. `SerialPortStreamCore` not only has a broken `System.Threading.Overlapped` dependency but also a broken `Microsoft.Win32.Registry` dependency. The nuspec file requires version 4.3.0 but it is broken, `SerialPortStreamCore` should be using 4.4.0.

I also reported this to the owner of the package, see:

```
You sent the following message via NuGet Gallery:

User VincentDondain <vidondai@microsoft.com> sends the following message to the owners of Package 'SerialPortStreamCore'.

Hi,

There seem to be 2 problems with this package.

The nuspec has a dependency: <dependency id="Microsoft.Win32.Registry" version="[4.3.0, )" /> but it should be updated to 4.4.0 to work on Xamarin.iOS/Xamarin.Mac projects.

System.Threading.Overlapped is broken for netstandard1.3 projects (missing /lib/netstandard1.3 folder). I already asked to owners to update it. You will need to update SerialPortStreamCore accordingly after System.Threading.Overlapped is fixed.

See install logs: https://gist.github.com/VincentDondain/b7efa387558e706468e28e3ca21d65b8
Thanks,

Vincent.
```

Conclusion, there are no problem with Xamarin.Mac (or Xamarin.iOS), the package (SerialPortStreamCore) and its dependency (System.Threading.Overlapped) are simply broken therefore I'm closing this issue.

_Note: You can still use the workaround I mentioned. Hope it helps._

**Closed by VincentDondain** 2018-01-04 17:42 UTC
Labels: need-info

**Comment by weshaggard** [comment] 2018-01-04 18:15
For issues with these packages (System.Threading.Overloapped, Microsoft.Win32.Registry) it is probably better to file issues at http://github.com/dotnet/corefx. I will say though that these aren't broken packages exactly they just don't currently work on the Xamarian platform.

**Comment by VincentDondain** [comment] 2018-01-04 19:16
Yes, let me paste the clarification you gave me by email @weshaggard:

> It supports netstandard1.3 but the implementation doesn’t live under the lib folder because it is runtime specific so the implementation lives under “runtimes\win\lib\netstandard1.3” and “runtimes\unix\lib\netstandard1.3”.

I did manage to install `System.Threading.Overloapped` and `SerialPortStreamCore` successfully on a Xamarin.Mac Mobile project via Package Reference (not package.config which is currently the default mode in Visual Studio for Mac).

You can add the package via PackageReference by adding the following to your csproj (right click on the project > Tools > Edit file, we're working on making this step easier):

```
<ItemGroup>
    <PackageReference Include="System.Threading.Overlapped">
        <Version>4.3.0</Version>
    </PackageReference>
</ItemGroup>
```

Then the problem is that, when compiling, `/runtimes/win` and not `/runtimes/unix` will be used (I believe that's an issue of the package that would need a Mac specific package @weshaggard but that might not be it).

In order to use the right folder (and included dll) you need to add some extra properties to your csproj:

```
<RuntimeIdentifiers>unix;unix-x86;unix-x64</RuntimeIdentifiers>
<NuGetRuntimeIdentifier>unix</NuGetRuntimeIdentifier>
```

Let us know if it works this way, that would greatly help us.

**Comment by HobDev** [comment] 2018-01-06 12:42
@VincentDondain  Thank you, I manage to use System.Threading.Overlapped via package reference. Also added extra properties that you mentioned. But again the package Windows.Win32.Registry throwing this exception:
`System.IO.FileNotFoundException has been thrown
Could not load file or assembly 'Microsoft.Win32.Registry' or one of its dependencies.`

**Comment by HobDev** [comment] 2018-01-06 13:48
I open an issue in [the repo](https://github.com/jcurl/SerialPortStream/issues/45). The owner of the package says that the `Microsoft.Win32.Registry` is broken. As the package only says the minimum version is 4.3.0 but I can use 4.4.0

**Comment by HobDev** [comment] 2018-04-26 04:10
#https://github.com/jcurl/SerialPortStream/issues/45  any thoughts on this.
