### ISSUE TITLE
[Xcode10.2] XI unitests fail to build from bots with an error MTOUCH : error MT5106: Could not compile the file(s) 

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#5512] opened 2019-01-29 20:42 UTC
### Steps to Reproduce

1. Update System to Xamarin.iOS, Xamarin.iOS
Version: 12.4.0.15 (Visual Studio Community)
Hash: 8a579bbb and install Xcode10.2
2. Build monotouch-test, donlink test or mini test

### Expected Behavior
Tests Projects should build successfully
### Actual Behavior
Failed to build with an error,  MTOUCH : error MT5106: Could not compile the file(s) '/Users/xamarinqa/agent/_work/r1/a/xamarin-macios/tests/monotouch-test/obj/iPhone/Debug-unified/mtouch-cache/armv7/Xamarin.iOS.dll.s'. Please file a bug report at http://bugzilla.xamarin.com [/Users/xamarinqa/agent/_work/r1/a/xamarin-macios/tests/monotouch-test/monotouch-test.csproj]

### Environment

```
Xamarin.iOS
Version: 12.4.0.15 (Visual Studio Community)
Hash: 8a579bbb
```

### Build Logs
Build Log: http://xqa.blob.core.windows.net/gist/report-533d048480f24f6eb60d613792db0cf4.txt

### Example Project (If Possible)
monotouch-test project from xamarin-macios/tests

### Additional Info
This issue occurred only running from CI, I couldn't reproduce it locally.

**Comment by spouliot** [comment] 2019-01-29 21:37
That's because you use `-nolink` (Don't Link) on devices and you run into the 32bits native linker limit.

Are you using that same configuration locally ?

Was that same configuration working on XI 12.2 ?

**Comment by dalexsoto** [comment] 2019-01-30 04:06
I was able to reproduce this using `dont link` and targeting an iPhone 5 with iOS 10.3.3

```
Xamarin.iOS
Version: 12.4.0.0 (Visual Studio Enterprise)
Hash: b8b135fb
Branch: xcode10.2
Build date: 2019-01-29 21:38:11-0500
```

don't link build log 
https://gist.github.com/dalexsoto/5d550608322f7da3aaac05f307a24463#file-dont-link-log

That said I was able to run `monotouch-tests` without issues: https://gist.githubusercontent.com/dalexsoto/5d550608322f7da3aaac05f307a24463/raw/86ea94194ef021c3c7ccf10946f2faace0572989/monotouch-test.log

**Comment by spouliot** [comment] 2019-01-30 14:06
@dalexsoto the default monotouch-tests has the linker enabled, otherwise it would be larger than don't link (and even more likely to hit the limit)

**Comment by GouriKumari** [comment] 2019-01-30 14:45
That's because you use -nolink (Don't Link) on devices and you run into the 32bits native linker limit.

Are you using that same configuration locally ?
I was checking with linksdk locally. But I couldn't reproduce it locally with dontlink enabled. It is happening only from CI for me. 

Was that same configuration working on XI 12.2 ?
This is working with 12.2. I didn't see any build issues for 15.9 or 16.0.

**Comment by dalexsoto** [comment] 2019-02-01 02:13
@spouliot I can reproduce @GouriKumari findings, this does not happen if you try to build `dont link` for the iPhone 5 device using d15-9 + **Xcode101.app**.

BUT if you try to build `dont link` for the iPhone 5 using d15-9 + **Xcode102-beta1.app** you get the reported behavior as result (a bunch of `error GDC116A36: can not encode offset 'xxxxxx' in resulting scattered relocation.`).

**Comment by rolfbjarne** [comment] 2019-02-01 06:45
> BUT if you try to build `dont link` for the iPhone 5 using d15-9 + **Xcode102-beta1.app** you get the reported behavior as result (a bunch of `error GDC116A36: can not encode offset 'xxxxxx' in resulting scattered relocation.`).

This is probably a good thing: my guess is that Xcode10.1 silently created broken native code that would just crash randomly at runtime.

**Comment by spouliot** [comment] 2019-02-01 15:24
it’s the same, old issue - and there’s nothing we can do
there’s a code size limit where this situation happens - and it’s not hard to hit without the linker
every new release grows Xamarin.iOS.dll so we keep _eating_ the margin
and `clang` itself might produce larger/different code - again out of our control

**Comment by dalexsoto** [comment] 2019-02-19 14:58
Fixed in 
https://github.com/xamarin/xamarin-macios/commit/41cd8e748910af82a3246930b74ca9724665301b

**Closed by dalexsoto** 2019-02-19 14:58 UTC
Labels: bug, iOS
