### ISSUE TITLE
 condition `mono_domain_get () == mono_get_root_domain ()' not met error on building ios sample

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#4008] opened 2018-04-27 17:00 UTC
### Steps to Reproduce

1. Build https://github.com/xamarin/ios-samples/tree/master/ios8/MetalImageProcessing with Release|iPhone config from command line using msbuild.

### Expected Behavior
App should build successfully

### Actual Behavior
App failed to build with an error, Assertion at /Users/builder/data/lanes/5944/7e782c1e/source/xamarin-macios/external/mono/mono/metadata/gc.c:847, condition `mono_domain_get () == mono_get_root_domain ()' not met
This is the first time  such an issue is seen in bots. 

### Environment

```
Operating System: Mac OS X 10.13.4
Mono version: 5.10.1.57 (ea8a24b1bbf)  (2018-04-24 14:53:01 -04:00)
XA version: 8.3.0.18 (HEAD/1f8462ef1) 
XI version: 11.10.1.177 (d15-7: 7e782c1e) 
XM version: 4.4.1.176 (master: 7e782c1e)  (2018-04-25 15:27:14 -04:00)
XVS version: 
XS version: 7.5.0.1212 (c82e5cc)  (2018-04-19 16:57:22 -04:00)
```

### Build Logs

Build Log: http://xqa.blob.core.windows.net/gist/report-1f27cd1cc6244f9894172c3bbec5a287.txt

### Example Project (If Possible)
https://github.com/xamarin/ios-samples/tree/master/ios8/MetalImageProcessing

## Additional Info:
I couldn't reproduce the issue on the same bot with the same command line inputs
Manual Build Log : https://gist.github.com/GouriKumari/79ad5ce69ce6c9b995ef5f56d1736d53 .
Logging this to keep track of the issue.

**Comment by dalexsoto** [comment] 2018-06-03 03:35
@GouriKumari have you been able to reproduce this issue? Should we keep this open?

**Comment by dalexsoto** [comment] 2018-07-01 23:47
So I tried to repro this locally using `msbuild /t:build /p:Platform=iPhone /p:Configuration=Release ios8/MetalImageProcessing/MetalImageProcessing/MetalImageProcessing.csproj` and I was unable to do so, it builds fine here.

@GouriKumari I'll close the issue for now since it seems we are not able to repro. Please reopen if you find it otherwise.

**Closed by dalexsoto** 2018-07-01 23:47 UTC
Labels: bug, iOS, need-info
