### ISSUE TITLE
.NET 6 mac apps are not launching on first -t:Run attempt

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-macios#11094] opened 2021-04-02 20:39 UTC
### Steps to Reproduce

1. Install the latest bits from https://github.com/dotnet/net6-mobile-samples/tree/develop#net-600-mobile-samples
2. Clone/checkout the `develop` branch of `net6-mobile-samples`.
3. `dotnet build -t:Run HelloMacOS/HelloMacOS.csproj`
or
`dotnet build t:Run HelloMacCatalyst/HelloMacCatalyst.csproj`

First run attempt fails with:
```
       Run:
         open bin/Debug/net6.0-maccatalyst/maccatalyst-x64/HelloMacCatalyst.app
         The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10827 "kLSNoExecutableErr: The executable is missing" UserInfo={_LSLine=3665, _LSFunction=_LSOpenStuffCallLocal}
```

However, if I run the same `-t:Run` target again, the app launches without any issues. I can also open/start the app myself without any issues.

Binlog: 
[hellomaccat.binlog.zip](https://github.com/xamarin/xamarin-macios/files/6251176/hellomaccat.binlog.zip)

**Comment by wjk** [comment] 2021-04-19 16:22
I’m having this problem too. In my case, the `Contents/MacOS` directory does not appear after _any_ number of `-t:Run` calls. Furthermore, I had to edit the csproj from the template default to get this far, as ILLink choked until I made modifications. My csproj file is as follows:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-macos</TargetFramework>
    <OutputType>Exe</OutputType>

    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>osx-x64</RuntimeIdentifier>
  </PropertyGroup>
</Project>
```

--------

`dotnet --info` output:

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.3.21202.5
 Commit:    aee38a6dd4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.2
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-preview.3.21202.5/

Host (useful for support):
  Version: 6.0.0-preview.3.21201.4
  Commit:  236cb21e3c

.NET SDKs installed:
  5.0.202 [/usr/local/share/dotnet/sdk]
  6.0.100-preview.3.21202.5 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by wjk** [comment] 2021-04-19 16:31
Addendum: My problem only occurs when building in Debug configuration. `dotnet build -c Release` creates a complete application bundle.

**Comment by rolfbjarne** [comment] 2021-12-09 10:23
This seems to work fine now, the HelloMacOS sample runs once I've set the SupportedOSPlatformVersion attribute: https://gist.github.com/rolfbjarne/6fb01d5f8d9d1803aff2d91446fc1011.

Could you please confirm it also works for you?

**Comment by rolfbjarne** [comment] 2022-01-26 07:33
Closing since I can't reproduce.

**Closed by rolfbjarne** 2022-01-26 07:33 UTC
Labels: bug, need-info, dotnet
