### ISSUE TITLE
"Please file a bug in bugzilla.xamarin.com" error message needs to be updated.

### ISSUE THREAD

**Issue by migueldeicaza** [xamarin/xamarin-macios#4519] opened 2018-07-27 12:43 UTC
Various error messages produced by our tools direct our users to file bugs in bugzilla.xamarin.com, we should update that to point to xamarin/xamarin-macios/issues.

**Comment by spouliot** [comment] 2018-07-27 13:11
dupe of https://github.com/xamarin/xamarin-macios/issues/3647

but yes, it needs to be done, ideally at the right time to avoid merges conflicts across branches.

**Closed by spouliot** 2018-07-27 13:11 UTC
