### ISSUE TITLE
Could not AOT the assembly System.Core.dll

### ISSUE THREAD

**Issue by RetrotecEd** [xamarin/xamarin-macios#6700] opened 2019-08-01 16:27 UTC
Updated Visual Studio, Xamarin and XCode on the Mcc and on my development PC to the latest releases and now get the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not AOT the assembly '/Users/retrotec/Library/Caches/Xamarin/mtbs/builds/rCloudMobile.iOS.v2/217e149e259f93f3568f1a842e95dd1f/obj/iPhone/ReleaseDev/mtouch-cache/64/3-Build/System.Core.dll'	rCloudMobile.iOS.v2	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	804	

Could not AOT the assembly System.Core.dll

Related to:
https://github.com/xamarin/xamarin-macios/issues/3199
https://github.com/xamarin/xamarin-macios/issues/4995

Traced the problem down to this:

In Project Properties, iOS Build tab

Additional mtouch arguments
--linkskip=System.Core 

We tried the project in VS 2017 with a Mac that has not been updated and the project builds fine (Mono 5.18 and Xamarin iOS 12.4)

So something in the Mono 6.0.0.311 / Xamarin iOS 12.14.0.110 broke this. We are completely broken at this point. We put the --linkskip in there because the linker was stripping out too much and the iOS App would throw exceptions for objects not found.

Steps to Reproduce
1. Run project prior to updating the Mac and PC. Builds fine.
2. Update the PC and Mac to latest Visual Studio Releases.
3. App no longer compiles.

### Expected Behavior
App compiles like it did prior.

### Actual Behavior
AOT exception

### Environment

1. PC

Microsoft Visual Studio Professional 2019
Version 16.2.0
VisualStudio.16.Release/16.2.0+29123.88
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA131
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

Application Insights Tools for Visual Studio Package   9.1.00611.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.2.290.48383
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.2.290.48383
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.2.290.48383
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.4.0000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.2.290.48383
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.4.0000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.2.0-beta4-19359-03+15b43b33901c88f68ef43f8314b5a2457716780d
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.2.19178.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.9.1.7781
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.4.0000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.4.0000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.5
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.4.0000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20626.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.2.6 (4cfc7c3)
Support for debugging Mono processes with Visual Studio.

Multilingual App Toolkit   4.0
Multilingual App Toolkit helps you localize your Windows Store app by providing file management, pseudo and machine translation, translation editor, and build integration. http://aka.ms/matinstall

NuGet Package Manager   5.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.2.19178.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.2.19178.1
Conda support for Python projects.

Python - Django support   16.2.19178.1
Provides templates and integration for the Django web framework.

Python - IronPython support   16.2.19178.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.2.19178.1
Profiling support for Python projects.

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61906.28070
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.10627.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.2.0-beta4-19359-03+15b43b33901c88f68ef43f8314b5a2457716780d
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.2.0-beta.19321.1+a24d94ecf97d0d69d4fbe6b8b10cd1f97737fff4
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.2.0.90 (d16-2@ba267630e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.2.0.325 (remotes/origin/d16-2@f10cfbf83)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.117 (59a59e8)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.4.0.51 (d16-2/9fa7775)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-02@e6f5369c2d2
    Java.Interop: xamarin/java.interop/d16-2@d64ada5
    LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

Xamarin.iOS and Xamarin.Mac SDK   12.14.0.110 (a8bcecc)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

Mac:

=== Visual Studio Community 2019 for Mac ===

Version 8.2.1 (build 19)
Installation UUID: cdaf3f13-d337-4bd7-b6bf-27619086462c
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000311

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.311 (2019-02/494641b300c) (64-bit)
	Package version: 600000311

=== Xamarin Designer ===

Version: 16.2.0.375
Hash: 357d38ef4
Branch: remotes/origin/d16-2
Build date: 2019-07-26 14:44:54 UTC

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.12
	2.1.11
	2.1.8
	2.1.2
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.701/Sdks
SDK Versions:
	2.1.701
	2.1.700
	2.1.504
	2.1.302
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Not Installed

=== Microsoft Mobile OpenJDK ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.58
Hash: d03e3ea
Branch: remotes/origin/d16-2~1
Build date: 2019-07-16 17:37:14 UTC

=== Apple Developer Tools ===

Xcode 10.3 (14492.2)
Build 10G8

=== Xamarin.Mac ===

Version: 5.14.0.110 (Visual Studio Community)
Hash: a8bcecce
Branch: d16-2
Build date: 2019-06-28 07:31:43-0400

=== Xamarin.iOS ===

Version: 12.14.0.110 (Visual Studio Community)
Hash: a8bcecce
Branch: d16-2
Build date: 2019-06-28 07:31:42-0400

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 802010019
Git revision: c7aee29ba7d2a827dbfe4901e4ad7249ce7e5bc7
Build date: 2019-07-29 20:22:23+00
Build branch: release-8.2
Xamarin extensions: c990de17e8456ead7fce80aff9dab01df769b2fd

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Thu Jun 20 18:42:21 PDT 2019
    root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

### Build Logs

'/Users/retrotec/Library/Caches/Xamarin/mtbs/builds/rCloudMobile.iOS.v2/217e149e259f93f3568f1a842e95dd1f/obj/iPhone/ReleaseDev/mtouch-cache/64/3-Build/System.Core.dll'	rCloudMobile.iOS.v2	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	804	

Could not AOT the assembly System.Core.dll

### Example Project (If Possible)
Sample project attached.

**Comment by RetrotecEd** [comment] 2019-08-01 16:27
[IOSSystemCoreTest.zip](https://github.com/xamarin/xamarin-macios/files/3457724/IOSSystemCoreTest.zip)

**Comment by chamons** [comment] 2019-08-01 16:50
Issues reproduces when building for device release.

```
  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/response-file.rsp --linkskip=System.Core --linkskip=System.Runtime.Serialization 
    AOT Compilation exited with code 1, command:
    MONO_PATH=/Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/64/3-Build /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.110/bin/arm64-darwin-mono-sgen --debug --llvm -O=gsharedvt -O=-float32  --aot=mtriple=arm64-ios,data-outfile=/Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/arm64/System.Core.aotdata.arm64,static,asmonly,direct-icalls,full,nodebug,dwarfdebug,direct-pinvoke,msym-dir=/Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/64/3-Build/Msym,llvm-path=/Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.110/LLVM/bin/,outfile=/Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/arm64/System.Core.dll.s,llvm-outfile=/Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/arm64/System.Core.dll-llvm.o "/Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/64/3-Build/System.Core.dll"
    Mono Ahead of Time compiler - compiling assembly /Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/64/3-Build/System.Core.dll
    AOTID 5E612832-DAF7-9CE6-E73D-42E226C36152
    Can't find custom attr constructor image: /Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/64/3-Build/System.Core.dll mtoken: 0x0a000d24 due to: Could not resolve type with token 010000af from typeref (expected class 'System.Runtime.CompilerServices.PreserveDependencyAttribute' in assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e') assembly:mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e type:System.Runtime.CompilerServices.PreserveDependencyAttribute member:(null)
    Failed to load custom attributes from method System.Func`2<System.Linq.Expressions.Interpreter.LightLambda, System.Delegate> System.Linq.Expressions.Interpreter.LightLambda:MakeRunDelegateCtor (System.Type) due to Could not resolve type with token 010000af from typeref (expected class 'System.Runtime.CompilerServices.PreserveDependencyAttribute' in assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e') assembly:mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e type:System.Runtime.CompilerServices.PreserveDependencyAttribute member:(null)
    FullAOT cannot continue if there are loader errors.
    
    AOT Compilation exited with code 1, command:
    MONO_PATH=/Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/32/3-Build /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.110/bin/arm-darwin-mono-sgen --debug --llvm -O=gsharedvt -O=-float32  --aot=mtriple=armv7s-ios,data-outfile=/Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/armv7s/System.Core.aotdata.armv7s,static,asmonly,direct-icalls,full,nodebug,dwarfdebug,direct-pinvoke,msym-dir=/Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/32/3-Build/Msym,llvm-path=/Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.110/LLVM36/bin/,outfile=/Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/armv7s/System.Core.dll.s,llvm-outfile=/Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/armv7s/System.Core.dll-llvm.o "/Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/32/3-Build/System.Core.dll"
    Mono Ahead of Time compiler - compiling assembly /Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/32/3-Build/System.Core.dll
    AOTID 538C8815-4880-E4E7-B9F9-86C1A813BECE
    Can't find custom attr constructor image: /Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/32/3-Build/System.Core.dll mtoken: 0x0a000d24 due to: Could not resolve type with token 010000af from typeref (expected class 'System.Runtime.CompilerServices.PreserveDependencyAttribute' in assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e') assembly:mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e type:System.Runtime.CompilerServices.PreserveDependencyAttribute member:(null)
    Failed to load custom attributes from method System.Func`2<System.Linq.Expressions.Interpreter.LightLambda, System.Delegate> System.Linq.Expressions.Interpreter.LightLambda:MakeRunDelegateCtor (System.Type) due to Could not resolve type with token 010000af from typeref (expected class 'System.Runtime.CompilerServices.PreserveDependencyAttribute' in assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e') assembly:mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e type:System.Runtime.CompilerServices.PreserveDependencyAttribute member:(null)
    FullAOT cannot continue if there are loader errors.
    
    AOT Compilation exited with code 1, command:
    MONO_PATH=/Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/32/3-Build /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.110/bin/arm-darwin-mono-sgen --debug --llvm -O=gsharedvt -O=-float32  --aot=mtriple=armv7-ios,data-outfile=/Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/armv7/System.Core.aotdata.armv7,static,asmonly,direct-icalls,full,nodebug,dwarfdebug,direct-pinvoke,msym-dir=/Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/32/3-Build/Msym,llvm-path=/Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.110/LLVM36/bin/,outfile=/Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/armv7/System.Core.dll.s,llvm-outfile=/Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/armv7/System.Core.dll-llvm.o "/Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/32/3-Build/System.Core.dll"
    Mono Ahead of Time compiler - compiling assembly /Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/32/3-Build/System.Core.dll
    AOTID 6F40210F-FBE9-1843-0707-1E916932AF2A
    Can't find custom attr constructor image: /Users/donblas/Downloads/IOSSystemCoreTest/IOSSystemCoreTest/obj/iPhone/Release/mtouch-cache/32/3-Build/System.Core.dll mtoken: 0x0a000d24 due to: Could not resolve type with token 010000af from typeref (expected class 'System.Runtime.CompilerServices.PreserveDependencyAttribute' in assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e') assembly:mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e type:System.Runtime.CompilerServices.PreserveDependencyAttribute member:(null)
    Failed to load custom attributes from method System.Func`2<System.Linq.Expressions.Interpreter.LightLambda, System.Delegate> System.Linq.Expressions.Interpreter.LightLambda:MakeRunDelegateCtor (System.Type) due to Could not resolve type with token 010000af from typeref (expected class 'System.Runtime.CompilerServices.PreserveDependencyAttribute' in assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e') assembly:mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e type:System.Runtime.CompilerServices.PreserveDependencyAttribute member:(null)
    FullAOT cannot continue if there are loader errors.
```

**Comment by chamons** [comment] 2019-08-01 19:29
FYI @spouliot - Linker related?

**Comment by RetrotecEd** [comment] 2019-08-02 17:04
For what it is worth, we found this open issue: https://github.com/xamarin/xamarin-macios/issues/6346

And tried the workaround from @spouliot 

Inside your Main.cs file add the following line

[assembly: Preserve (typeof (Enumerable), AllMembers = true)]
between your using clauses and your namespace

but it either just hangs the compiler or in the previously attached project throws 15000+ errors which is why we had to linkskip it...

![VisualStudioError](https://user-images.githubusercontent.com/25186698/62386478-d936e800-b50c-11e9-9110-bf123adff3b2.png)

**Comment by jennablackwell** [comment] 2019-08-08 14:44
I am also having this issue :(

**Comment by jennablackwell** [comment] 2019-08-08 15:14
Apparently.... removing this line in iOS project build properties resolved it for me.  I never put it here myself, I think maybe it was the default when creating an iOS project before?

Remove from "Additional mtouch arguments"
--linkskip=System.Core

**Comment by spouliot** [comment] 2019-08-09 15:21
This is a bug in mono/linker, c.c. @marek-safar - I'll file it and cross-link the issues.

A new `internal PreserveDependencyAttribute` was added in Mono (inside `mscorlib.dll`) and `System.Core` uses it.

However it does not consider that assemblies that use this new attribute could be skipped (or not linked) and the processing does not mark the attribute inside `mscorlib.dll`.

So what happens is that `PreserveDependencyAttribute` is removed (because it's not marked) from `mscorlib.dll` but `System.Core` still reference the type.

That's invalid and the AOT compiler is not happy to have a set of broken assemblies and fail to produce a valid output, which we report as a `MT3001` error.

# Workaround

Since the attribute is `internal` you'll need to add an XML file to tell the linker to preserve it.

Add the following file to your project

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<linker>
    <assembly fullname="mscorlib">
        <type fullname="System.Runtime.CompilerServices.PreserveDependencyAttribute" />
    </assembly>
</linker>
```

and set it's build action to **LinkDescription**

**Comment by RetrotecEd** [comment] 2019-08-09 18:25
[IOSSystemCoreTest.zip](https://github.com/xamarin/xamarin-macios/files/3487597/IOSSystemCoreTest.zip)

Unfortunately the workaround didn't work or I didn't implement it correctly. 

When building the attached solution, after 20+ minutes (the solution is empty) it fails with 29k+ errors.

**Comment by spouliot** [comment] 2019-08-09 21:21
That sounds like a different issue. Just to confirm can you try a release build with only ARM64 to see if that works ? (which would mean your set up with the XML file is correct)

The most _common_ reason for thousands of errors is that the application size is too big for Apple's native linker (ld) to work on 32bits. Skipping the linker on `System.Core.dll` will produce something big, maybe big enough to hit that limitation. It's also one (of two) reason(s) that the build time is so slow. The other reason is that you're building for 3 architectures (not just armv7 and arm64).

If that's the case then let's try to figure out why you are disabling the linker on the whole System.Core.dll, instead of preserving whatever is needed (which is smaller, hopefully a lot smaller, than the assembly itself). Can you share a test case / subset of your app that shows that issue ? if so please open a separate issue for this and I'll do my best to help you.

**Comment by RetrotecEd** [comment] 2019-08-12 15:39
@spouliot Hi Sebastian, I can confirm it works with ARM64.

The reason we had to linkskip System.Core was in the early days of our Xamarin app (2016) we would get these hard to reproduce errors and crashes. We finally tracked it down to the linker stripping out too much from System.Core we assume cause the stripped out classes in question were being called by reflection somewhere. We wracked our brains trying to remember which classes they were and we tried a build without linkskipping but of course it failed on the ARM7 + ARM 7s builds. Unfortunately it has been three years since we ran into those errors so our memories aren't clear.

**Comment by spouliot** [comment] 2019-08-12 20:09
@RetrotecEd thanks, that confirm it's a different issue.

On my side I tried your test case and you're running into the issue. The 29k errors comes from the Apple's native linker (ld) because the produced binary gets larger than the 32bits limit (actually more like 24bits iirc).

> we tried a build without linkskipping but of course it failed on the ARM7 + ARM 7s builds

Failed at build time ? That should not happen - linking `System.Core` is the default and a well tested scenario.

Failed at runtime ? That's possible, even more when reflection is used - but that's generally easy to fix and workaround.

I strongly encourage you to drop that `--linkskip` for your development (will be faster) and final application size (will be smaller). The issue you had _might_ have been fixed but if not then please open issues for them and we'll fix them (and give you better workarounds that skipping the whole assembly).

**Comment by RetrotecEd** [comment] 2019-08-13 21:44
It failed at Build Time:

27> /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/iosdeveloper/Library/Caches/Xamarin/mtbs/builds/rCloudMobile.iOS.v2/84a393bf124dcb1aef1de409ff0921f2/obj/iPhone/ReleaseDev/response-file.rsp --linkskip=System.Runtime.Serialization --linkskip=BingMapsVerification --linkskip=SQLite-net --linkskip=Newtonsoft.Json --linkskip=AutoTest.iOS --linkskip=CommonCalcApp 
27>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(804,3): error MT3001: Could not AOT the assembly '/Users/iosdeveloper/Library/Caches/Xamarin/mtbs/builds/rCloudMobile.iOS.v2/84a393bf124dcb1aef1de409ff0921f2/obj/iPhone/ReleaseDev/mtouch-cache/3-Build/rCloudMobile.iOS.exe'

We were successful in building for Arm 64 but failed on Arm v7.

We are successful building in older version of Xamarin for all three platforms with the --linkskip System.Core in.

We are moving forward with a full regression test of our iOS app on ARM 64 without the linkskip and will post other bugs as we find them. But this is really hitting us hard.

**Comment by spouliot** [comment] 2019-08-14 02:40
@RetrotecEd thanks for confirming this works with ARM64 only.

Unless you use **Link All** (which is not the default) then the options `--linkskip=BingMapsVerification --linkskip=SQLite-net --linkskip=Newtonsoft.Json --linkskip=AutoTest.iOS --linkskip=CommonCalcApp` are no-op - i.e. they are already skipped because they are not SDK code (stuff we ship) but user code (stuff you provide).

`MT3001` only means the AOT compiler has not produced any output. There can be several reasons (assertions, crash, missing metadata...) but I can't see this from a partial build log.

Since this is not related to the current issue (and will make reading it difficult in the future if needed) please open another issue and attach
* the full build log (add `-v -v -v -v` to the **Additional touch arguments** to add verbosity);
* ideally a test case (like a subset of the application that has the build issue);
You can refer/link to this issue for context. Thanks!

**Comment by RetrotecEd** [comment] 2019-08-20 17:59
@spouliot 

Hi Sebastien,

We are proceeding as you instructed. We have removed the linkskip argument and are regression testing but I have to tell I am a bit nervous about it. We put it in there for a reason (our bad we didn't document it enough). 

As for the building Arm v7 and Arm v7s - we can't get a log. After 45 minutes of building we eventually just give up. Normally a build of our app with all three platforms takes 11 minutes.

**Comment by danielmeza** [comment] 2019-08-31 20:39
I Have this issue in Android with AOT enable and release mode. But with the System.Runtime.Loader.dll

**Comment by spouliot** [comment] 2019-11-28 19:51
Fix was merged.
32bits issue is different (too many warnings by the native linker) and already filed -> https://github.com/xamarin/xamarin-macios/issues/6787

**Closed by spouliot** 2019-11-28 19:51 UTC
Labels: bug, iOS
