### ISSUE TITLE
Binding project using xcframework can't be used in Xamarin.iOS app

### ISSUE THREAD

**Issue by leonluc-dev** [xamarin/xamarin-macios#10774] opened 2021-03-03 15:06 UTC
### Steps to Reproduce

1.  Create a Binding project with a xcframework as the native framework reference
2.  Build binding project and reference it in a Xamarin.iOS app.
3.  Build the Xamarin.iOS app

### Expected Behavior
The build process includes the native reference (or derived framework in case of xcframework) used in the referenced binding project.

### Actual Behavior
If a xcframework was used as a native reference in the binding project the expected derived framework isn't included in the Xamarin.iOS build process, which causes builds to fail with a MT5211 error. 

I've added an example project showcasing the issue below (using the Universal.xcframework that was supplied for xcframework testing).

### Environment

```
=== Visual Studio Professional 2019 for Mac ===

Version 8.9 (build 1651)
Installation UUID: 57691245-242a-4da8-98b8-14c6159c8d17
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000122

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.122 (2020-02/c621c35ffa0) (64-bit)
	Package version: 612000122

=== Roslyn (Language Service) ===

3.9.0-5.21112.8+f3ff04378c972d435826e6181de364b3c0db8d14

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.103/Sdks
SDK Versions:
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19

=== .NET Core 3.1 SDK ===

SDK: 3.1.406

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.14.2.5 (Visual Studio Professional)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:44-0500

=== Xamarin Designer ===

Version: 16.9.0.316
Hash: bd2705417
Branch: remotes/origin/d16-9
Build date: 2021-02-24 00:16:08 UTC

=== Xamarin.Android ===

Version: 11.2.0.0 (Visual Studio Professional)
Commit: xamarin-android/d16-9/f908d16
Android SDK: /Users/appdeveloper/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-9@1d382be
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.32.2@cfe06e0
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@ad80a42

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/appdeveloper/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/d16-9
Build date: 2021-02-18 03:14:56 UTC

=== Android Device Manager ===

Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/d16-9
Build date: 2021-02-18 03:15:18 UTC

=== Build Information ===

Release ID: 809001651
Git revision: c05b1dec4362b5956d47624a437e900ffdc9aa0a
Build date: 2021-02-25 11:27:51-05
Build branch: release-8.9
Xamarin extensions: c05b1dec4362b5956d47624a437e900ffdc9aa0a

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.2.0 Darwin Kernel Version 20.2.0
    Wed Dec  2 20:39:59 PST 2020
    root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
```

### Example Project (If Possible)

[BindingTest.zip](https://github.com/xamarin/xamarin-macios/files/6076743/BindingTest.zip)

**Comment by leonluc-dev** [comment] 2021-03-04 08:35
I've did some more testing and it seems that including the xcframework in the Xamarin.iOS app directly and not in the binding project it seems to works fine (the proper architecture in the xcframework gets picked for both simulator and device builds in the build process and the code called through the API binding works fine).

So this seems to be a issue related to the build process "importing" the xcframework from a reference project/dll/assembly, rather than a xcframework support issue as a whole.

So if you have access to the xcframework of the library you want to use you can include it in the Xamarin.iOS project directly as a temporary workaround until this issue is fixed. 
I've added an example showing the workaround:

[BindingTest-workaround.zip](https://github.com/xamarin/xamarin-macios/files/6081974/BindingTest-fixed.zip)

**Comment by spouliot** [comment] 2021-03-04 14:54
Thanks for the report. I'll have a look shortly...

> Note: The workaround only works on Visual Studio on Mac (Visual Studio 2019 on Windows still has a few bugs regarding xcframeworks)

Please file separate issues for them and specify they are only happening on Windows. Thanks!

**Comment by leonluc-dev** [comment] 2021-03-04 16:02
Thanks!

I've filed a seperate issue for the Windows exclusive issues here: #10784

**Comment by spouliot** [comment] 2021-03-04 20:35
> I've added an example project showcasing the issue below (using the Universal.xcframework that was supplied for xcframework testing).

@leonluc-dev just to be clear - the [original attached project](https://github.com/xamarin/xamarin-macios/files/6076743/BindingTest.zip) (in the main description) works without modification, right ?

* the main app has the native reference
* the binding project has no native reference

**Comment by leonluc-dev** [comment] 2021-03-04 20:57
@spouliot The BindingTest.zip in the original post is the one showing the issue (xcframework is in the binding project, app just has a reference to the binding). 

The Bindingtest-fixed.zip shows the temporary workaround (xcframework in app)

**Comment by spouliot** [comment] 2021-03-04 21:09
hmm, that's not what I downloaded...
but I could make the change (move native ref from app -> binding project) and see the build failure
investigating...

**Comment by spouliot** [comment] 2021-03-05 15:10
I'm hitting a localization issue (that I'll need to fix first, since it hides an issue) but I'm fairly sure the problem is (at least in part) because of the lack of

```
  <PropertyGroup>
    <NoBindingEmbedding>true</NoBindingEmbedding>
  </PropertyGroup>
```

inside your binding project, `.csproj` file.

In short, it's not really possible (at least it's a very bad idea [1]) to embed an .xcframework inside the assemblies. So we keep the native code in a "side car" with a manifest file that describe the arguments to be used. That is not new but, for compatibility, this was not the default for bindings. Now xcframework are new and makes this option even more important [2].


[1] is was already a bad idea for framework and even before, bitcode really made this a bad choice. The "cost" (in time) to extract the native code on each clean (not cached) build can be extremely large for some projects (larger than the rest of the build).

[2] it's even worse for .xcframework since assemblies are per-platforms (one for iOS, one for tvOS, one for watchOS, one for  macOS...) and this would embed the native code for all platforms into each platform specific assemblies.

**Comment by leonluc-dev** [comment] 2021-03-05 15:40
I see. 

So if I understand correctly, the 'workaround' mentioned earlier, NativeReference to xcframework in app and just the C# binding definition in the binding project (combined with the NoBindingEmbedding option), is the supposed way to go for xcframeworks or even framework based libraries in general?

**Comment by spouliot** [comment] 2021-03-05 16:10
> the 'workaround' mentioned earlier (NativeReference to xcframework in app

Not quite. The native reference should only be needed for the binding project(s) but, without `<NoBindingEmbedding>true</NoBindingEmbedding>`, the tooling cannot find the required manifest.

So
* Apps does not require native reference(s) that are already added in bindings projects
* Bindings to XCFrameworks requires the native reference(s)
* Bindings to XCFrameworks requires `<NoBindingEmbedding>true</NoBindingEmbedding>`

and

* The use of `<NoBindingEmbedding>true</NoBindingEmbedding>` is optional (for backward compatibility) for frameworks and (static `.a`) libraries binding projects. However build performance can suffer when the binaries are large (since it's costly to extract them after a clean operation).

**Comment by leonluc-dev** [comment] 2021-03-05 16:36
Alright. Thanks for the information!

After setting the NoBindingEmbedding in the csproj file it seems to work properly now. The binding project generates a DLL and a .resource folder containing the xcframework and manifest and the app seems to build properly now.

In other contexts (direct distribution of the binary files or NuGet for example), would making sure the .resource folder is in the same folder as the referenced dll be enough to make it work there as well?

**Comment by spouliot** [comment] 2021-03-05 16:50
Yes, the native bits are meant to be side-by-side (the "side car").

As for nuget it might be tricky since both nuget and xcframework are similar in design/goals but quite different in their implementation (nothing to do with `NoBindingEmbedding`). You find yourself with two _standard_ ways of splitting code into different platforms.

Ideally you would want a single copy of any `.xcframework` inside the nuget (since they can be very large). I'm no expert in nuget, there might be ways to achieve this that I won't know about. Using symlinks seems an easy way... but those might not work properly on Windows (which is something else I'm not an expert on).

**Comment by leonluc-dev** [comment] 2021-03-08 14:52
After some experimenting it seems that simply referencing the binding project dll and placing the .resources folder in the same folder as the dll works, but only on Mac. 
Windows based builds seemingly ignore any .resources folder in the same folder as the dll, leading to linker errors (possibly related to the same issue as reported in #10784?)

On Mac I am still working on getting this side-car setup to work in NuGet packages. Creating a NuGet package using the project pack command without a nuspec file only adds the dll to the package, so a custom nuget package needs to be made to add the .resources folder as well.

I've tried to add the .resources file to the `lib/xamarinios10` folder and the `content` folder in the package but neither option allows the Xamarin tooling to 'find' the .resources folder.
Looking in the [folder documentation for NuGet](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#from-a-convention-based-working-directory) it seems the content folder would be the best way to add the resources folder, since it allows arbitrary content. But I'm having a hard time figuring out how to get the Xamarin tooling to 'pick it up'.

**Comment by spouliot** [comment] 2021-03-09 21:30
@leonluc-dev thanks for your investigations. I'm not an expert on nuget so I'll open a different issue to see how this should be handled.

Also please add any Windows-specific information inside https://github.com/xamarin/xamarin-macios/issues/10784. I assumed the "side car" was working on Windows but I'm not fully sure anymore (it seems the cases I thought about actually did not use the feature).

I'll update the bindings documentation for "side car" and, once published, close this issue. Thanks!

**Comment by carlosmacmar** [comment] 2021-04-19 12:12
> > the 'workaround' mentioned earlier (NativeReference to xcframework in app
> 
> Not quite. The native reference should only be needed for the binding project(s) but, without `<NoBindingEmbedding>true</NoBindingEmbedding>`, the tooling cannot find the required manifest.
> 
> So
> 
> * Apps does not require native reference(s) that are already added in bindings projects
> * Bindings to XCFrameworks requires the native reference(s)
> * Bindings to XCFrameworks requires `<NoBindingEmbedding>true</NoBindingEmbedding>`
> 
> and
> 
> * The use of `<NoBindingEmbedding>true</NoBindingEmbedding>` is optional (for backward compatibility) for frameworks and (static `.a`) libraries binding projects. However build performance can suffer when the binaries are large (since it's costly to extract them after a clean operation).

Thanks, this was really helpful, but in my own case, something was still missing and, even though the binding project built without errors, I was getting errors when trying to use the binding project (added inside references) in an app.

After some investigation, I've found out that when the XCFramework was added to the project, VS added it to .csproj file like this:
```
<NativeReference Include="..\..\MyLibrary.xcframework">
  <Kind>Static</Kind>
  <SmartLink>False</SmartLink>
</NativeReference>
```

I then realised this shouldn't be like this, because a XCFramework is not a static library (.a file). I changed it to:
```
<NativeReference Include="..\..\MyLibrary.xcframework">
  <Kind>Framework</Kind>
  <SmartLink>False</SmartLink>
</NativeReference>
```

And now it's working correctly without errors 🔥 

I'll write a medium article about what I did and I'll add the link here as soon as I have it ready :)

**Comment by nguyenhuutinh** [comment] 2021-04-23 08:07
@carlosmacmar : how did you generate your metadata?

I tried but it says error

fatal error:
      module 'DemoSDK' not found
@import DemoSDK.DNSResolver;


Thanks

**Comment by Atamanam** [comment] 2021-10-20 23:53
@leonluc-dev  I have downloaded [BindingTest-fixed.zip](https://github.com/xamarin/xamarin-macios/files/6081974/BindingTest-fixed.zip) & also cannot figure out how this Apidefinition.cs links to the Native Reference [Universal] in the Binding Test App

namespace UniversalBinding
{
    [BaseType(typeof(NSObject))]
    interface FrameworkTest
    {
        [Export("func")]
        int Func();
    }
}

**Comment by joemather** [comment] 2021-11-30 16:36
How do we generate the metadata (`ApiDefinition.cs`) for an XCFramework?

Previously, we used sharpie, but sharpie seems incompatible with XCFrameworks.

I'm binding a framework with hundreds of APIs, so manually creating `ApiDefinition.cs` would be error prone.

@carlosmacmar - How did you generate it?

Thanks.

**Comment by 4brunu** [comment] 2021-11-30 18:00
@joemather You need point to the Framework inside the XCFramework.
Something like `TwilioVoice.xcframework/ios-arm64/TwilioVoice.framework`.
Here is an example
https://github.com/xamarin-bindings-for-twilio/TwilioVoiceXamarinIOS/blob/795bfc0d39dc70bd9cc064e77e9c5da50a64f6f0/src/bind.sh

**Comment by joemather** [comment] 2021-12-02 01:14
@4brunu - That works. Thank you!

For other devs trying to generate metadata, here's the command that worked for me:

```
sharpie bind -o Metadata/MyFramework  \
             -namespace=MyFramework   \
             -sdk iphoneos15.0        \
             -framework ./Frameworks/MyFramework.xcframework/ios-arm64/MyFramework.framework     \
             -c -I ./Frameworks/Depedency1.xcframework/ios-arm64/Depedency1.framework/Headers    \
                -I ./Frameworks/Depedency2.xcframework/ios-arm64/Depedency2.framework/Headers
```

Also, [this article](https://dgatto.com/posts/2020/10/xam-webrtc-binding-ios/) explains how to fix "file not found" errors when sharpie fails to resolve `#import` statements in the headers.

**Comment by nrudnyk** [comment] 2022-03-07 21:55
@leonluc-dev 
>On Mac I am still working on getting this side-car setup to work in NuGet packages. Creating a NuGet package using the project pack command without a nuspec file only adds the dll to the package, so a custom nuget package needs to be made to add the .resources folder as well.

have you been able to successfully setup NuGet Package? If so - could you please share some more info?

**Comment by leonluc-dev** [comment] 2022-03-08 14:33
@nrudnyk 
I did. It requires a bit of extra work. You can find how to do it in [this comment](https://github.com/xamarin/xamarin-macios/issues/10819#issuecomment-815059416). With tips to improve the nuget packaging found [here](https://github.com/xamarin/xamarin-macios/issues/10819#issuecomment-975227419) and [here](https://github.com/xamarin/xamarin-macios/issues/10819#issuecomment-975492088),

If you don't want to do all this manual configuration you can wait until .NET MAUI (along with .NET for iOS) releases later this year, which will support XCFrameworks in NuGet out of the box.

**Comment by nrudnyk** [comment] 2022-03-08 16:24
@quentinR0bert [Q2 of 2022](https://github.com/xamarin/xamarin-macios/issues/10819#issuecomment-1061818763)

**Comment by leonluc-dev** [comment] 2022-03-08 19:11
@nrudnyk 
Your nuspec file and nobindingembedded setting are fine. The issue is in your targets file.

In your targets file (which is "run" just before compiling starts, as indicated at the top) you first copy the bindings resources from the NuGet package to `$(TargetDir)\SciChart.iOS.Charting.resources\`. This is fine, but then the targets file tries to include the XCframework to the build process as a NativeReference from `$(TargetDir)\res\SciChart.xcframework`, a different folder.

You need to make sure the nativereference to the xcframework is included from the same folder you copy it to during the build process.

**Comment by nrudnyk** [comment] 2022-03-08 21:44
Thanks @leonluc-dev, I've updated .targets to the following:
```
    <Target Name="BeforeCompile">
        <ItemGroup>
            <BindingResources Include="$(MSBuildThisFileDirectory)..\content\res\**\*.*" />
        </ItemGroup>
        <Copy SourceFiles="@(BindingResources)" DestinationFolder="$(TargetDir)\res\%(RecursiveDir)" ContinueOnError="false" />
        <ItemGroup>
            <NativeReference Include="$(TargetDir)\res\SciChart.xcframework">
                <Kind>Framework</Kind>
                <SmartLink>False</SmartLink>
            </NativeReference>
        </ItemGroup>
    </Target>
```
and that does helped to fix the latter issue. Thanks a lot!

With that sorted out, I've faced another issue `MTOUCH: Error MT2101: Can't resolve the reference 'System.IntPtr`, locally while referencing bindings project by sample everything working fine, but when using Nuget Package is fails. That's whole another story.

Another important thing, that adding package is taking very long time, it is adding file by file for each platform and it takes like 10-15 minutes easily... have anyone faced similar issue? what do you thing about this @rolfbjarne ?

https://user-images.githubusercontent.com/20221382/157330423-452438e0-12f6-4cfd-96f8-268041975d62.mov

**Comment by vas1l3nk** [comment] 2022-03-09 09:53
@4brunu  Hello. How can I generate metadata via sharpie simultaneously for both `ios-arm64` and `ios-arm64_x86_64-simulator`.

**Comment by 4brunu** [comment] 2022-03-09 09:57
You can't do both at once, as far as I know.
But usually they are the same, so that shouldn't be an issue, in most cases.
So what I do is to generate the metadata via sharpie only for `ios-arm64`.

**Comment by vas1l3nk** [comment] 2022-03-09 10:29
Thanks a lot for this information!

**Comment by Atamanam** [comment] 2022-03-11 04:04
@leonluc-dev  Can you please help me with documentation on how to integrate xcframework with a Xamarin iOS project by creating a binding project.

**Comment by lassana** [comment] 2022-03-11 07:45
FYI: instead of ` <Target Name="BeforeCompile">` you should use something like `<Target Name="AddMyFrameworkWithUniqueName" BeforeTargets="BeforeCompile">`, see https://github.com/xamarin/xamarin-macios/issues/13603

**Comment by Atamanam** [comment] 2022-03-14 21:53
@leonluc-dev  Can you please help me with documentation on how to integrate xcframework with a Xamarin iOS project by creating a binding project.

**Comment by rolfbjarne** [comment] 2022-10-07 15:46
xcframeworks work in Xamarin.iOS projects now, so I don't think there's anything left to do here.

Also, in .NET, it's possible to run `dotnet pack` and we'll create a nupkg that will just work.

**Closed by rolfbjarne** 2022-10-07 15:46 UTC
Labels: iOS, documentation
