### ISSUE TITLE
[Bug] XF for Mac, have to clean before each build to see changes

### ISSUE THREAD

**Issue by JohnHDev** [xamarin/xamarin-macios#9014] opened 2020-07-02 18:06 UTC
### Description
Code changes aren't reflected when running the Mac app unless the current project is cleaned first

Instructions for creating an XF for Mac app: https://devblogs.microsoft.com/xamarin/preview-bringing-macos-to-xamarin-forms/

Forum conversation where Xamarin asked me to raise this issue here: https://forums.xamarin.com/discussion/183016/anyone-here-having-to-clean-before-every-build-for-mac-apps#latest

### Steps to Reproduce

1. Unzip the attached example and open the solution, restore packages etc
2. Set XF4Mac as startup project
3. Run it, see that the text is black
4. Change the label text colour to Red in MainPage.cs
5. Run it 

### Expected Behavior
Label text should be red

### Actual Behavior
Label text is still black

### Basic Information

- Version with issue: 4.5 +, 
- Last known good version: None
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

Clean the project before each build. Tedious, but it works

[XF4iOSAndroidMacDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/4865955/XF4iOSAndroidMacDemo.zip)

**Comment by chamons** [comment] 2020-07-06 21:50
I can reproduce this, but I am unsure if it a Xamarin.Forms bug or a Xamarin.Mac bug as of yet.

**Comment by chamons** [comment] 2020-07-06 22:01
Hmm, so the reason we're not seeing the change is that we are copying in the change to the bin/debug dir:
```
 Copying file from "/Users/donblas/Downloads/XF4iOSAndroidMacDemo/XF4iOSAndroidMacDemo/bin/Debug/netstandard2.0/XF4iOSAndroidMacDemo.dll" to "/Users/donblas/Downloads/XF4iOSAndroidMacDemo/XF4Mac/bin/Debug/XF4iOSAndroidMacDemo.dll".
 ```

but not re-running mmp to add to the package:
```
  Skipping target "_CompileToNative" because all output files are up-to-date with respect to the input files.
  Input files: /Users/donblas/Downloads/XF4iOSAndroidMacDemo/XF4Mac/bin/Debug/XF4Mac.exe
  Output files: bin/Debug/XF4Mac.app/Contents/MacOS/XF4Mac
```

**Comment by rolfbjarne** [comment] 2020-07-07 06:46
My guess would be that that file isn't listed in the Inputs, or that the Outputs' timestamp hasn't changed here:

https://github.com/xamarin/xamarin-macios/blob/edd8a2c8963063ca0ab3357e251944f4aa053fa8/msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets#L390-L391

**Comment by mattleibow** [comment] 2020-07-13 14:40
@rolfbjarne it seems to be exactly that. It appears that after an edit, only the final .exe reaches that target. Let me see where it drops off.

![image](https://user-images.githubusercontent.com/1096616/87317430-43327c80-c527-11ea-89af-9b35bace81dd.png)

**Comment by mattleibow** [comment] 2020-07-13 14:44
Not sure where `@(BundleDependentFiles)` comes from... It does not appear in any targets or props files...

**Comment by mattleibow** [comment] 2020-07-13 15:07
I think I have a fix for this:

![image](https://user-images.githubusercontent.com/1096616/87320562-5cd5c300-c52b-11ea-9bc2-8efd01024379.png)

**Closed** 2020-07-14 12:54 UTC
Labels: bug, macOS
