### ISSUE TITLE
OnDemandResources not working

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/xamarin-macios#8432] opened 2020-04-19 17:14 UTC
Since a few version of Xamarin.iOS (I don't know which one it was exaactly anymore), ODR do no longer work in Simulator (and if the Review Team from Apple test with a virtual device, it won't work for them as well... - this leads to random rejections of app submissions). I didn't change the code on my side at all, it works on TestFlight an Release versions and it won't work with older releaases (which once worked on the Simulator as well) no longer. 

The resource is uploaded with the app and should be loaded from apples ODR servers. 

The error message is the following: 
`Error Domain=NSCocoaErrorDomainCode=4994 "The requested application data doesn't exist." UserInfo={NSUnderlyingError=0x281990840 {Error Domain=_NSBundleResourceREquestErrorDomain Code=100 "No manifest found for bundle ID com.mycompany.myapp" UserInfo={NSLocalizedFailureReason=No manifest found for bundle ID com.mycompany.myapp}}}`

This issue is super annoying and should be fixed asap... The code to access the ODR is the following (which did work in the past also on the simulator and still works on TestFlight / Release): 

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Foundation;
using Microsoft.AppCenter.Crashes;
using MvvmCross;
using MyApp.Core.DependencyServices;
using MyApp.Core.Model.Data;
using MyApp.Core.Repositories;
using MyApp.iOS.DependencyServices;
using Xamarin.Forms;

[assembly: Dependency(typeof(FileDownloadService))]
namespace MyApp.iOS.DependencyServices
{
    public class FileDownloadService : NSObject, IFileDownloadService
    {
        public bool IsRunning { get; private set; }

        public event DownloadProgressChangedEventArgs DownloadProgressChanged;
        public event DownloadFinishedEventArgs DownloadFinished;

        public async Task<bool> StartDownloadAsync(string targetLocation, params string[] tags)
        {
            var repository = Mvx.IoCProvider.Resolve<IMapDatabaseRepository>();
            var maps = await repository.GetAllAsync();

            var request = new NSBundleResourceRequest(tags) { LoadingPriority = NSBundleResourceRequest.LoadingPriorityUrgent };
            request.Progress.AddObserver(this, "fractionCompleted", NSKeyValueObservingOptions.New | NSKeyValueObservingOptions.Initial, IntPtr.Zero);

            try
            {
                IsRunning = true;
                var result = await request.ConditionallyBeginAccessingResourcesAsync();

                if (!result)
                    await request.BeginAccessingResourcesAsync();

                await Task.Delay(TimeSpan.FromMilliseconds(500));
                CompleteDownloadSuccessful(request, maps.Where(map => tags.Contains(map.Tag)), targetLocation);
            }
            catch (NSErrorException ex)
            {
                IsRunning = false;
                DownloadFinished?.Invoke(this, false, ex.Error.Description);

                request.EndAccessingResources();
                request.Dispose();

                Crashes.TrackError(new Exception(ex.Error.DebugDescription));
                Crashes.TrackError(ex);
            }
            catch (Exception ex)
            {
                IsRunning = false;
                DownloadFinished?.Invoke(this, false, ex.Message);

                request.EndAccessingResources();
                request.Dispose();

                Crashes.TrackError(ex);
            }

            return true;
        }

        public override void ObserveValue(NSString keyPath, NSObject ofObject, NSDictionary change, IntPtr context)
        {
            try
            {
                var downloadProgress = ConvertNSObjectToSingle(change["new"]);
                DownloadProgressChanged?.Invoke(this, downloadProgress * 100f);
            }
            catch (NSErrorException ex)
            {
                var data = new Dictionary<string, string>();
                foreach (var c in change)
                    data.Add(c.Key.ToString(), c.Value.ToString());

                Crashes.TrackError(new Exception(ex.Error.DebugDescription), data);
                Crashes.TrackError(ex, data);
            }
            catch (Exception ex)
            {
                var data = new Dictionary<string, string>();
                foreach (var c in change)
                    data.Add(c.Key.ToString(), c.Value.ToString());

                Crashes.TrackError(ex, data);
            }
        }

        private void CompleteDownloadSuccessful(NSBundleResourceRequest request, IEnumerable<Map> relevantMaps, string targetLocation)
        {
            try
            {
                var tags = new List<string>();
                var completedMaps = new List<string>();

                foreach (var map in relevantMaps)
                {
                    var destFileName = Path.Combine(targetLocation, map.File + ".mbtiles");
                    if (File.Exists(destFileName))
                        File.Delete(destFileName);

                    var pathForResource = NSBundle.MainBundle.PathForResource(map.File, "mbtiles");
                    if (string.IsNullOrEmpty(pathForResource) || !File.Exists(pathForResource))
                        continue;

                    File.Copy(pathForResource, destFileName);
                    NSFileManager.SetSkipBackupAttribute(destFileName, true);

                    if (!tags.Contains(map.Tag))
                        tags.Add(map.Tag);

                    completedMaps.Add(map.File);
                }

                NSBundle.MainBundle.SetPreservationPriority(0, new NSSet<NSString>(tags.Select(t => new NSString(t)).ToArray()));
                request.EndAccessingResources();

                IsRunning = false;
                DownloadFinished?.Invoke(this, completedMaps.Any(), completedMaps.ToArray());
            }
            catch (NSErrorException ex)
            {
                Crashes.TrackError(new Exception(ex.Error.DebugDescription));
                Crashes.TrackError(ex);
                DownloadFinished?.Invoke(this, false, ex.Message);
            }
            catch (Exception ex)
            {
                Crashes.TrackError(ex);
                DownloadFinished?.Invoke(this, false, ex.Message);
            }
            finally
            {
                //Note: Is this necessary??
                request.Progress.RemoveObserver(this, "fractionCompleted", IntPtr.Zero);
                request.Dispose();
            }
        }

        private static float ConvertNSObjectToSingle(NSObject obj)
        {
            if (obj != null && obj is NSNumber number)
                return number.FloatValue;

            return 0;
        }
    }
}
```

There are also others with this problem, see: 

https://stackoverflow.com/questions/59884936/issue-with-using-on-demand-resource-through-xamarin-ios-on-ios-simulator

https://github.com/xamarin/xamarin-macios/issues/8026

**Comment by chamons** [comment] 2020-04-20 15:02
Thanks for the report. 

I believe this is a duplicate of https://github.com/xamarin/xamarin-macios/issues/8026

I'm going to escalate this with the appropriate team as well.

**Closed by chamons** 2020-04-20 15:02 UTC
