### ISSUE TITLE
Default `macos` project fails to build

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [xamarin/xamarin-macios#12046] opened 2021-06-30 00:10 UTC
### Steps to Reproduce

1. Download .NET 6 nightly SDK from https://github.com/dotnet/installer
2. Install macOS workload: `sudo dotnet workload install microsoft-macos-sdk-full`
3. Create new default `macos` project: `dotnet new macos -n mactest`
4. Build application: `cd mactest`, `dotnet build`

### Expected Behavior

The project builds.

### Actual Behavior

The project fails to build.

```
>dotnet build
Microsoft (R) Build Engine version 17.0.0-preview-21325-03+e9593e841 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  Detected signing identity:
          
    Bundle Id: com.companyname.mactest
    App Id: com.companyname.mactest
  mactest -> ~/src/scratch/mactest/bin/Debug/net6.0-macos/mactest.dll
/usr/local/share/dotnet/sdk/6.0.100-preview.7.21329.3/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(184,5): error NETSDK1102: Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app. [~/src/scratch/mactest/mactest.csproj]

Build FAILED.

/usr/local/share/dotnet/sdk/6.0.100-preview.7.21329.3/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(184,5): error NETSDK1102: Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app. [~/src/scratch/mactest/mactest.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.40
```

### Environment

macOS Big Sur 11.4 - i7

**Comment by AaronRobinsonMSFT** [comment] 2021-06-30 02:01
SDK also has a similar issue: https://github.com/dotnet/sdk/issues/18395

**Comment by agocke** [comment] 2021-06-30 18:17
Dug through the binlog -- I think the problem is that xamarin-macios sets PublishTrimmed based on project type, but doesn't set self-contained https://github.com/xamarin/xamarin-macios/blob/ebf6c13bd1e419c20112a4702c10876b21c0ba75/dotnet/targets/Xamarin.Shared.Sdk.targets#L244

This looks incorrect to me.

**Comment by rolfbjarne** [comment] 2021-06-30 19:57
The problem is that `RuntimeIdentifier` must be set. Add this to your csproj:

```xml
<RuntimeIdentifer>osx-x64</RuntimeIdentifier>
```

and it'll work.

We've recently fixed this to have a default `RuntimeIdentifier`, so this won't happen in preview 7.

**Comment by rolfbjarne** [comment] 2021-06-30 19:59
Closing this as a dup of #12000.

**Closed by rolfbjarne** 2021-06-30 19:59 UTC
