### ISSUE TITLE
warning MSB9004: ManifestResourceWithNoCulture item type is deprecated. Emit EmbeddedResource items instead, with metadata WithCulture='false', Type='Resx', and optional LogicalName.

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#4736] opened 2018-08-31 13:41 UTC
### Steps to Reproduce

1. Build an iOS 12 application (e.g. https://github.com/xamarin/ios-samples/tree/master/ios12/SoupChef) for device using Xcode 10

### Expected Behavior

Build without warnings.

### Actual Behavior

```
/Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(3288,5): warning MSB9004: ManifestResourceWithNoCulture item type is deprecated. Emit EmbeddedResource items instead, with metadata WithCulture='false', Type='Resx', and optional LogicalName.
```

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.6.1 (build 7)
Installation UUID: a8ba93d0-79b6-41af-a590-4edb9c2095b4
Runtime:
	Mono 5.12.0.305 (2018-02/e0e035e3b14) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000305

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.3
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 10.0 (14320.12.2)
Build 10L232m

=== Xamarin.Mac ===

Version: 4.99.3.658 (Visual Studio Community)
Hash: 1eefd4e3
Branch: 
Build date: 2018-08-21 15:01:53-0400

=== Xamarin.iOS ===

Version: 11.99.3.538 (Visual Studio Community)
Hash: 1eefd4e3
Branch: HEAD
Build date: 2018-08-21 15:01:52-0400

=== Xamarin.Android ===

Version: 8.3.0.19 (Visual Studio Community)
Android SDK: /Users/poupou/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.4   (API level 19)
		7.1   (API level 25)
		8.1   (API level 27)

SDK Tools Version: 24.0.2
SDK Platform Tools Version: 21.0.0
SDK Build Tools Version: 21.1.2

Java SDK: /usr
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706010007
Git revision: 7c9e755fe667840f2eed42b2e7910ec18ef51b82
Build date: 2018-08-24 02:25:33+00
Build branch: release-7.6-xcode10
Xamarin extensions: 1196f085605a84ce99f390a1aaee0bf257d31a50

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Internet of Things (IoT) development (Preview) 7.1

```

### Build Logs

```
...
Target "_GenerateCompileInputs" in file "/Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets":
  Using "Warning" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
  Task "Warning"
    /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(3288,5): warning MSB9004: ManifestResourceWithNoCulture item type is deprecated. Emit EmbeddedResource items instead, with metadata WithCulture='false', Type='Resx', and optional LogicalName.
  Done executing task "Warning".
  Task "Warning" skipped, due to false condition; ('@(ManifestNonResxWithNoCultureOnDisk)'!='' and '%(ManifestNonResxWithNoCultureOnDisk.EmittedForCompatibilityOnly)'=='') was evaluated as (''!='' and ''=='').
Done building target "_GenerateCompileInputs" in project "OrderSoupIntentBinding.csproj".
...
```

### Example Project (If Possible)

https://github.com/xamarin/ios-samples/tree/master/ios12/SoupChef

**Comment by rolfbjarne** [comment] 2018-09-11 15:04
This is a duplicate of #3876.

**Closed by rolfbjarne** 2018-09-11 15:04 UTC
Labels: duplicate, enhancement, iOS
