### ISSUE TITLE
[F#] Building iOS .NET 6 with LLVM hangs

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#14838] opened 2022-04-27 22:15 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/F-Building-iOS-NET-6-with-LLVM-hangs/10023966)._

---
\[severity:I’m unable to use this version\]  
Doing

```
dotnet restore Transmission-VSMac.slnf
cd Client/Client.Mobile
dotnet restore -r ios-arm64
dotnet build --no-restore -f net6.0-ios -ios-arm64 -c Release --self-contained
```

hangs on macOS 12.3.1

```  
Visual Studio Community 2022 for Mac Preview
Version 17.0 Preview (17.0 build 8567)
Installation UUID: 1f382393-40dc-4781-bd2a-2da097f24bc9

Runtime
.NET 6.0.3 (64-bit)
Architecture: X64

Xamarin Designer
Version: 17.1.5.85
Hash: bd4553834
Branch: remotes/origin/d17-0-vsmac
Build date: 2022-04-07 20:47:56 UTC

Roslyn (Language Service)
4.1.0-3.22075.3+592501cbb9c9394072a245c15b3458ff88155d85

NuGet
Version: 6.0.0.262

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.201/Sdks
SDK Versions:
	6.0.300-preview.22204.3
	6.0.201
	6.0.101
	5.0.407
	3.1.418
MSBuild SDKs: /usr/local/share/dotnet/sdk/6.0.300-preview.22204.3/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.3
	5.0.16
	3.1.24

Xamarin.Profiler
Version: 1.8.0.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Not Installed

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.10
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: Not Found

Android SDK Manager
Version: 17.2.0.31
Hash: d341462
Branch: remotes/origin/dev/mag/d17-2~1
Build date: 2022-04-07 20:48:01 UTC

Android Device Manager
Version: 0.0.0.1110
Hash: 6cb643c
Branch: remotes/origin/d17-2
Build date: 2022-04-07 20:48:01 UTC

Apple Developer Tools
Xcode 13.3 (20102)
Build 13E113

Xamarin.Mac
Version: 8.8.0.3 (Visual Studio Community)
Hash: eb7f8ed35
Branch: xcode13.3
Build date: 2022-03-30 03:16:09-0400

Xamarin.iOS
Version: 15.8.0.3 (Visual Studio Community)
Hash: eb7f8ed35
Branch: xcode13.3
Build date: 2022-03-30 03:16:09-0400

Build Information
Release ID: 1700008567
Git revision: 95e0843576bf05769cbede768cc99d36f75ac629
Build date: 2022-04-07 20:45:45+00
Build branch: release-17.0
Build lane: release-17.0

Operating System
Mac OS X 12.3.1
Darwin 21.4.0 Darwin Kernel Version 21.4.0
    Fri Mar 18 00:45:05 PDT 2022
    root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
  
```

---
#### XperiAndri on 4/26/2022, 09:39 AM: 

(private comment, text removed)
#### XperiAndri on 4/26/2022, 09:42 AM: 

(private comment, text removed)
#### XperiAndri on 4/26/2022, 09:43 AM: 

(private comment, text removed)
#### Feedback Bot on 4/26/2022, 08:59 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by xperiandri** [comment] 2022-04-27 22:37
@rolfbjarne can you access the files that I uploaded?

**Comment by rolfbjarne** [comment] 2022-04-28 07:46
Yes, I can access the project.

It builds fine for me, although it takes quite a while (almost 8 minutes on an iMac Pro).

How long did you wait before you cancelled the build?

If you add `/v:diag` to the build command, you'll get more progress, and you'll be able to see a bit better where the time is going:

> dotnet build --no-restore -f net6.0-ios -r ios-arm64 -c Release --self-contained /v:diag

Also open the Activity Monitor and see if there are any processes using a lot of CPU.

**Comment by xperiandri** [comment] 2022-04-28 07:49
Around 18 hours. However I did that on VMWare

**Comment by xperiandri** [comment] 2022-04-28 07:49
I was wonder why Acivity Monitor displays nothing

**Comment by xperiandri** [comment] 2022-04-28 07:50
What about trying to build that same from Visual Studio connected to Mac?

**Comment by rolfbjarne** [comment] 2022-04-28 07:53
> Around 18 hours. However I did that on VMWare

18 hours sounds like a bit too much...

> I was wonder why Acivity Monitor displays nothing

Yeah, that probably means something went wrong. If the build was still running, there should be some processes using a lot of CPU.

> What about trying to build that same from Visual Studio connected to Mac?

I wasn't able to access the log you attached from Visual Studio for Windows, could you try attaching it again (I had the same problem with the binlog as well)?

**Comment by xperiandri** [comment] 2022-04-28 10:52
[Transmission.Client.Mobile_Release_AnyCPU_Build_2022-04-28T12_13_13.9815949+03_00.binlog.zip](https://github.com/xamarin/xamarin-macios/files/8582030/Transmission.Client.Mobile_Release_AnyCPU_Build_2022-04-28T12_13_13.9815949%2B03_00.binlog.zip)

**Comment by rolfbjarne** [comment] 2022-04-28 13:10
@xperiandri you should be able to work around that issue by setting `EnableAssemblyILStripping=false` in the csproj:

```xml
<PropertyGroup>
    <EnableAssemblyILStripping>false</EnableAssemblyILStripping>
</PropertyGroup>
```

**Comment by xperiandri** [comment] 2022-04-28 13:11
For iOS only?

**Comment by rolfbjarne** [comment] 2022-04-28 13:15
yes (it's safe to set for all platforms, it'll just be ignored on platforms where there's no IL stripping)

**Comment by rolfbjarne** [comment] 2022-04-28 16:40
I can reproduce this, and I've filed https://github.com/xamarin/xamarin-macios/issues/14841 with the pertinent information.

**Comment by chamons** [comment] 2022-04-28 20:33
@rolfbjarne - Can we close this if 14841 covers this issue, or is there something I'm missing?

**Comment by chamons** [comment] 2022-04-28 20:48
This also looks to be originally from https://github.com/xamarin/xamarin-macios/issues/14813 as they filed that devcom issue to attach a private sample and it was "helpfully" moved back.

**Comment by rolfbjarne** [comment] 2022-04-29 06:31
@chamons there seems to be three different issues:

1. ILStrip fails on Windows (#14841).
2. AOT compilation hangs (this issue).
3. AOT compilation fails (#14813).

@xperiandri can you add diagnostic output to the build (by adding `/v:diag` to the command line) and attach the complete output somewhere. This should show us where the build process stops at least.

**Comment by xperiandri** [comment] 2022-04-29 08:08
Executed. Waiting for the result

**Comment by xperiandri** [comment] 2022-04-29 08:49
No CPU activity at all

**Comment by rolfbjarne** [comment] 2022-04-29 08:52
Can you execute that command (`clang++ -mios-version-m ...`) manually from a terminal and see if that works?

**Comment by xperiandri** [comment] 2022-04-29 09:02
Do you mean stopping the current build and executing that command?

**Comment by rolfbjarne** [comment] 2022-04-29 09:05
Yes

**Comment by xperiandri** [comment] 2022-04-29 10:40
@rolfbjarne I don't understand how to transform the output into a runnable command

**Comment by rolfbjarne** [comment] 2022-04-29 11:10
@xperiandri I've converted it into a script: https://gist.github.com/rolfbjarne/19ba773e02ea40d5cc494a3ff47837c9

1. Download the raw version, say to ~/Downloads/repro.sh: https://gist.githubusercontent.com/rolfbjarne/19ba773e02ea40d5cc494a3ff47837c9/raw/052bb283af96187478f437108509c62cab3868fb/repro.sh
2. Make it executable: `chmod +x ~/Downloads/repro.sh`
3. Execute it: `~/Downloads/repro.sh`

**Comment by xperiandri** [comment] 2022-04-29 11:39
I figured it out.
So something is still going on. But without noticeable activity in the process list.

It would be nice if you forward `xcrun` to a console so that a user can see what is going on.

**Comment by xperiandri** [comment] 2022-04-29 11:41
Is it possible to pre-LLVM dependencies without IL Stripping and pass LLVMed versions to the compiler?
That would be much better than waiting for LLVMing for ages.

**Comment by xperiandri** [comment] 2022-04-29 19:52
This is how it finished
```
"_p_398_plt_FSharp_Collections_Immutable_Microsoft_FSharp_Core_FSharpValueOption_1_b_REF_get_ValueNone_2_llvm", referenced from:
      _FSharp_Collections_Immutable_FSharp_Collections_Immutable_HashMap_vTryFind_a_REF_b_REF_a_REF_System_Collections_Immutable_ImmutableDictionary_2_a_REF_b_REF in FSharp.Collections.Immutable.dll.llvm.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by rolfbjarne** [comment] 2023-01-20 10:19
Sorry about the late response, this slipped through the cracks unfortunately.

> It would be nice if you forward `xcrun` to a console so that a user can see what is going on.

Unfortunately MSBuild captures the output and only shows it at the very end once execution has finished :/

> This is how it finished

Is that just a single error, or were there many more of them?

**Closed** 2023-01-27 11:01 UTC
Labels: need-info
