### ISSUE TITLE
macOS Ventura crash

### ISSUE THREAD

**Issue by ivanicin** [xamarin/xamarin-macios#16587] opened 2022-11-04 11:22 UTC
### Steps to Reproduce

I have submitted this before https://github.com/xamarin/xamarin-macios/issues/15396 , and it seems that the issue is happening on the release version of macOS Ventura. As stated it could be Apple's bug, but in that case it is yours to document it and submit it to them.

> I have received this crash report from AppCenter. It only happens for users on macOS 13.0 Ventura. It could be a macOS Ventura bug, but it feels like that some changes in this OS activate racing condition in Xamarin (this bug usually happens after hours of use of the app) and that it is a Xamarin bug. Technically it could be also app bug, but I think that the log would be different then and would point to at least some method in the app and I don't see how some sort of object disposal could directly call some list operation in the app.

### Expected Behavior
No Crash

### Actual Behavior
This is the crash log:

```
List`1+Enumerator[T].MoveNextRare ()
SIGTRAP: Collection was modified; enumeration operation may not execute.
List`1+Enumerator[T].MoveNextRare ()
List`1+Enumerator[T].MoveNext ()
NSObject+NSObject_Disposer.Drain (Foundation.NSObject ctx)
(wrapper managed-to-native) AppKit.NSApplication.NSApplicationMain(int,string[])
NSApplication.Main (System.String[] args)
MainClass.Main (System.String[] args)
```
### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.3.8 (build 5)
Installation UUID: d31d5e34-09ce-4611-b2d9-f8cc72f38a72

Runtime
.NET 6.0.5 (64-bit)
Architecture: X64

Roslyn (Language Service)
4.3.0-3.22312.2+52adfb8b2dc71ed4278debcf13960f2116868608

NuGet
Version: 6.2.2.1

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.402/Sdks
SDK Versions:
	6.0.402
	6.0.401
	6.0.400
	6.0.302
	6.0.301
	5.0.408
	5.0.407
	5.0.406
	5.0.405
	5.0.404
	5.0.403
	5.0.402
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.424
	3.1.423
	3.1.422
	3.1.421
	3.1.420
	3.1.419
	3.1.418
	3.1.417
	3.1.416
	3.1.415
	3.1.414
	3.1.413
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.701
	2.1.700
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.10
	6.0.9
	6.0.8
	6.0.7
	6.0.6
	5.0.17
	5.0.16
	5.0.15
	5.0.14
	5.0.13
	5.0.12
	5.0.11
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.30
	3.1.29
	3.1.28
	3.1.27
	3.1.26
	3.1.25
	3.1.24
	3.1.23
	3.1.22
	3.1.21
	3.1.20
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.0.0.0 (Visual Studio Community)
Commit: xamarin-android/d17-3/030cd63
Android SDK: /Users/ivanicin/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.2
SDK Build Tools Version: 33.0.0

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-3@7716ae53
SQLite: xamarin/sqlite/3.38.5@df4deab
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.3.0.23
Hash: 965bf40
Branch: remotes/origin/d17-3
Build date: 2022-10-13 22:07:48 UTC

Android Device Manager
Version: 0.0.0.1169
Hash: fafb1d5
Branch: fafb1d5
Build date: 2022-10-13 22:07:48 UTC

Xamarin Designer
Version: 17.3.0.208
Hash: 0de472ea0
Branch: remotes/origin/d17-3
Build date: 2022-10-13 22:07:43 UTC

Apple Developer Tools
Xcode 14.1 (21534.1)
Build 14B47b

Xamarin.Mac
Version: 8.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:54-0400

Xamarin.iOS
Version: 16.0.0.72 (Visual Studio Community)
Hash: 6756a1146
Branch: release/6.0.4xx-xcode14
Build date: 2022-09-21 08:51:06-0400

Build Information
Release ID: 1703080005
Git revision: 6a0d8af1de04f96af57762154da284796414cdd2
Build date: 2022-10-13 22:05:20+00
Build branch: release-17.3
Build lane: release-17.3

Operating System
Mac OS X 13.0.0
Darwin 22.1.0 Darwin Kernel Version 22.1.0
    Sun Oct  9 20:14:54 PDT 2022
    root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64


```

</details>

**Comment by rolfbjarne** [comment] 2022-11-07 17:33
@ivanicin are you using Mac Catalyst or macOS?

**Comment by ivanicin** [comment] 2022-11-07 17:37
> @ivanicin are you using Mac Catalyst or macOS?

macOS

**Comment by ivanicin** [comment] 2022-11-10 22:38
It seems that I've got the first 1 star review for this bug...

**Comment by ivanicin** [comment] 2022-11-10 22:40
It may be of some use to note that reports come from both Intel and Apple silicon Macs.

**Comment by rolfbjarne** [comment] 2022-11-15 16:36
Is this a .NET project or a legacy Xamarin.Mac project?

**Comment by rolfbjarne** [comment] 2022-11-24 06:11
I haven't been able to reproduce the issue, but I have a rather wild theory about what the problem is, and came up with a potential fix. However, since I'm not able to reproduce the issue, I have no idea if my theory is correct or not, so I can't verify the fix. But I have a package with the fix, and I wondered if you'd be willing and able to test this package to see if it solves the issue?

[xamarin.mac-9.0.0.25.pkg](https://download.visualstudio.microsoft.com/download/pr/c84a4855-de4e-441e-8cb0-ead07a0d8612/b8beb38bb2ddf207412d9e8cb6c169a9/xamarin.mac-9.0.0.25.pkg)

Just download, install and rebuild your app.

**Comment by ivanicin** [comment] 2022-11-24 14:19
@rolfbjarne how risky is this to cause unrelated problems?

I can't reproduce the issue directly, but I do get quite a bit of error reports so I can test it by deploying it to users, if there is no error in a week then it is safe to assume that it is fixed.

However deploying it to the production means also that it isn't something too risky either.

**Comment by rolfbjarne** [comment] 2022-11-25 14:40
@ivanicin this is the tentative fix:

https://github.com/xamarin/xamarin-macios/commit/5de48a433b5d038d735ced6b7a7292a7133499ff

There's some risk, because this is fairly important and low-level code, but on the other hand it's passed our own tests.

The package is also an update from your version (8.12.0.2 vs 9.0.0.25) - it includes support for Xcode 14.1, so there may be some risk here too (but then again it's very close to the package we'll soon ship to the stable channel for Xamarin.Mac with Xcode 14.1 support).

A different point is that the fix would have to be tested somehow and confirmed to work before we'll accept it.

My advice would be to treat it like any other Xamarin.Mac update: build & test locally as normal, and then release it.

**Comment by rolfbjarne** [comment] 2022-12-05 14:14
@ivanicin were you able to test the package?

**Comment by ivanicin** [comment] 2022-12-05 16:14
@rolfbjarne it looks promising that there are no crashes in two days, but it is far from certain. I need at least a week to be sure that this work as in that interval there should be much more than one crash. I think that there were two days without the crash before and that is also not on the version that was not freshly distributed and thus was more widely deployed.

**Comment by ivanicin** [comment] 2022-12-09 14:04
@rolfbjarne now it is few hours from the full week and there are no crashes yet. I think that it is reasonable to conclude that this can be treated as fixed. 

As there were no crashes on old versions either, it seems that most users that had this problem did update and don't have the problem.

Clearly as this is stochastic this isn't bullet-proof and there are sill some possibilities that the error may appear. As you probably finish the Xcode 14.1 release I think that it is reasonable to include it now, so I would suggest you to close the issue and if something new happens I'll report it again.

Also some other rare crashes without some descriptive error did disappear too, so this feels like a very good improvement based on the current data.

**Comment by rolfbjarne** [comment] 2022-12-12 10:43
@ivanicin great, thanks for confirming the fix! I'll get the fix merged and it'll eventually be released.

**Closed** 2022-12-12 16:41 UTC
Labels: bug
