### ISSUE TITLE
Request Authorization for User Notification in MacOS always false

### ISSUE THREAD

**Issue by Nii-co** [xamarin/xamarin-macios#9829] opened 2020-10-09 06:03 UTC
### Steps to Reproduce

1. Create a new Xamarin.Mac project
2. Add the following code into DidFinishLaunching:
```
var center = UNUserNotificationCenter.Current;
center.RequestAuthorization(UNAuthorizationOptions.Alert | UNAuthorizationOptions.Badge | UNAuthorizationOptions.Provisional, 
(grant, err) => {
    if (!grant)
    {
        System.Console.WriteLine("Access not Granted");
    }
    else
    {
        System.Console.WriteLine("Access Granted");
    }
});
```
3. Run the project

### Expected Behavior
A dialogue asking for permission pops up

### Actual Behavior
Nothing happens and RequestAuthorization just return false

### Environment

```
MacOS: 10.15.7
VS for Mac: 8.7.8
Xamarin.Mac: 6.20.2.2
```

### Example Project (If Possible)

**Is there any workaround to get the notification on MacOS work?**

**Comment by filipnavara** [comment] 2020-10-09 09:15
Is the application signed and does it have the necessary entitlements listed?

**Comment by chameleon67** [comment] 2020-10-09 12:14
@filipnavara 
What entitlements would you suggest for Local Notifications? Apple's documentation only suggests adding an Push Entitlement for Remote Notifications.

**Comment by chamons** [comment] 2020-10-09 15:21
This is a duplicate of https://github.com/xamarin/xamarin-macios/issues/9818

This answer applies here as well.
 
```
It turns out that on macOS some of the newest APIs are only available if you sign your app, else they will mysteriously fail.

These APIs are unfortunately not documented by Apple, and new XM projects by default do not sign in Debug (for build performance reasons).

If you enable code signing in debug your example works.
```

**Closed by chamons** 2020-10-09 15:21 UTC
