### ISSUE TITLE
[XI] ImageInverterExtn app displays a blank app on simulator 

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#3371] opened 2018-01-31 21:32 UTC
### Steps to Reproduce

 1. Download and open https://developer.xamarin.com/samples/monotouch/ios8/ImageInverter/ImageInverter.zip
2. Set iOS Deployment target to 11.0 or higher in both main and extension app
3. Set Extension App as startup project and rebuild the project
4. Deploy it in iOS simulator 
5. Open ImageInverter app in iOS simulator 
6. Enable ImageInverterExtn App in it

### Expected Behavior
ImageInverterExtn App should launch in iOS Simulator and Image should
be Inverted
 
### Actual Behavior
Blank screen is displayed when ImageInverterExtn loaded 
Screencast: https://www.screencast.com/t/BweketBj

### Environment

VSFM:  https://gist.github.com/parasAmbhore/a5207b50c330667ed6acd6393e3c5def
VS for windows: https://gist.github.com/parasAmbhore/e51d16f2541d49850a0a5277806cce00

### Build Logs

[VSFM_logs.zip](https://github.com/xamarin/xamarin-macios/files/1683392/VSFM_logs.zip)

### Regression: from d15-4
This issue was reported in VSTS  against VS for windows for d15-5, BUGID https://devdiv.visualstudio.com/DevDiv/_workitems/edit/510257. Since it is reproducible in both VSFMac and VS for Windows filing it against XI.

**Comment by dalexsoto** [comment] 2018-02-01 01:50
Hello @GouriKumari 

I am not able to reproduce the issue you are seeing the sample is crashing on me on the simulator, the funny thing is that nothing is printed on the logs, on device won't open at all either. That being said I went and downloaded the Apple sample this port is based on and it does not work either so if this is a line by line port it is likely the sample needs to be updated to match any new conditions in iOS or Xcode, marking this bug as Invalid since the native sample also does not work so it is very likely not to be out issue. I'll leave this open for now to discuss in our meeting to see what steps we take.

**Comment by spouliot** [comment] 2018-02-02 15:17
@dalexsoto since it was hinted as a regression from 15.4 can you try again with that version ?
If it does not work then please close this (since it's not a bug in the products) and open an issue in the sample repo (plus cross-links). Thanks!

**Comment by dalexsoto** [comment] 2018-02-02 20:10
I have tested the sample with d15-4 [0] and I see no difference with my previous testing results.

[0]:
```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.2.2 (build 11)
Installation UUID: 1899e9c0-871d-400c-9fdf-d07922303241
Runtime:
	Mono 5.4.1.6 (2017-06/1f4613aa1ac) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010006

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.3
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.0.3/Sdks
SDK Versions:
	2.0.3
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.5.6
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.1 (13532)
Build 9B55

=== Xamarin.iOS ===

Version: 11.3.0.47 (Visual Studio Enterprise)
Hash: 51128b8c
Branch: xcode9.1
Build date: 2017-10-31 22:42:13-0400

=== Xamarin.Android ===

Version: 8.0.2.1 (Visual Studio Enterprise)
Android SDK: /Users/alex/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3  (API level 15)
		4.1    (API level 16)
		4.2    (API level 17)
		4.3    (API level 18)
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)
		8.0    (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 27.0.0

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin.Mac ===

Version: 3.8.1.0 (Visual Studio Enterprise)

=== Xamarin Inspector ===

Version: 1.3.2
Hash: 461f09a
Branch: 1.3-release
Build date: Tue, 03 Oct 2017 18:26:57 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 702020011
Git revision: b604c37c5a4a2f0919b45ffbe2aaad9fe040af31
Build date: 2017-11-01 08:31:43-04
Xamarin addins: d57dc14cbd4eb166ee62bab585965ab78d3650bc
Build lane: monodevelop-lion-d15-4

=== Operating System ===

Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Thu Jan 11 22:59:40 PST 2018
    root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64
```

**Closed by dalexsoto** 2018-02-02 20:10 UTC
Labels: iOS, invalid
