### ISSUE TITLE
[Xcode13] NRE linking application that uses NUnitLite

### ISSUE THREAD

**Issue by viniciusjarina** [xamarin/xamarin-macios#12932] opened 2021-10-04 22:37 UTC
The problem seems related to the NUnitLite application

If you do File New > Unit Test App, and try to build you will hit the issue

### Steps to Reproduce

1.  Clone https://github.com/viniciusjarina/testapp
2.  msbuild testapp.sln /p:Platform=iPhone
3. NRE

### Expected Behavior

Application should be built

### Actual Behavior

NullReferenceException on _CompileToNative task

### Environment

```
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.10.10 (build 8)
Installation UUID: 35b4fff0-f3e8-48a7-b5d8-568a3d8ba4af
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000157

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.157 (2020-02/4150e65c9e3) (64-bit)
	Package version: 612000157

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.401/Sdks
SDK Versions:
	5.0.401
	3.1.413
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.10
	3.1.19

=== .NET Core 3.1 SDK ===

SDK: 3.1.413

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.3.0.4 (Visual Studio Enterprise)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/viniciusjarina/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/viniciusjarina/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-09-21 02:30:50 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-09-21 02:31:08 UTC

=== Apple Developer Tools ===

Xcode 13.0 (19234)
Build 13A233

=== Xamarin.Mac ===

Version: 7.14.0.27 (Visual Studio Enterprise)
Hash: 2566861a9
Branch: d16-10
Build date: 2021-07-27 02:34:12-0400

=== Xamarin.iOS ===

Version: 15.0.0.6 (Visual Studio Enterprise)
Hash: 2771277e0
Branch: xcode13-ios
Build date: 2021-09-23 10:36:08-0400

=== Build Information ===

Release ID: 810100008
Git revision: a3ff4b6e658e1f94623e1f3ed34ca94ed4fe78d8
Build date: 2021-09-23 19:50:51-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Mon Aug 30 06:12:21 PDT 2021
    root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
```

### Build Logs

https://gist.github.com/viniciusjarina/40f7f9034a67dfa696e63861b0374cc9

### Example Project (If Possible)

https://github.com/viniciusjarina/testapp

**Comment by rolfbjarne** [comment] 2021-10-05 05:35
Thanks for the report!

This is a duplicate of #12862.

**Closed by rolfbjarne** 2021-10-05 05:35 UTC
