### ISSUE TITLE
MT3001: Could not AOT the assembly 

### ISSUE THREAD

**Issue by sharmashiv** [xamarin/xamarin-macios#4016] opened 2018-05-01 12:43 UTC
Two cases in build(xamarin.ios):

1) When build option setting:

Linker behavior: Link All
In that case application crash with this error message
You MUST invoke LoadApplication () before calling base.FinishedLaunching ()

2) When build option setting:

Linker behavior: Link Framework SDKs Only
I'm getting the error:

MT3001: Could not AOT the assembly.

/Users/macmini01/Desktop/Per/RunningCode_Both/XXX_Mobile Sourcecode_2Apr2018/XXX/XXX.iOS/MTOUCH: Error MT3001: Could not AOT the assembly '/Users/macmini01/Desktop/Per/RunningCode_Both/XXX_Mobile Sourcecode_2Apr2018/XXX/XXX.iOS/obj/iPhone/Debug/mtouch-cache/64/Build/OsmSharp.UI.dll' (MT3001) (XXX.iOS)

**Comment by VincentDondain** [comment] 2018-05-01 14:25
Please include your full build logs, crash reports (if any), test case (to reproduce) and all your version information.

To get full build logs just set the log verbosity to diagnostic at the following locations:
- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.
Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:
- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
Then copy/paste the version information (you can use the "Copy Information" button).

**Comment by sharmashiv** [comment] 2018-05-02 05:51
[Build_Log.txt](https://github.com/xamarin/xamarin-macios/files/1966034/Build_Log.txt)
[Xamarin_IDE_Log.txt](https://github.com/xamarin/xamarin-macios/files/1966035/Xamarin_IDE_Log.txt)

**Comment by VincentDondain** [comment] 2018-05-02 14:35
Oh just realized this issue is a perfect duplicate of https://github.com/xamarin/xamarin-macios/issues/4012. Please let's keep everything in one issue (:

**Closed by VincentDondain** 2018-05-02 14:35 UTC
Labels: need-info

**Comment by dktechindia** [comment] 2019-07-04 02:18
I am getting this issue with Visual Studio Community 2019 (Version 16.1.5) and MacOS Catalina (Version 10.15 Beta (19A501i)

Any workaround for this?
