### ISSUE TITLE
Xamarin.iOS Binding for native SDK gets "ObjCRuntime\Trampolines.g.cs" class file broken

### ISSUE THREAD

**Issue by stvansolano** [xamarin/xamarin-macios#4086] opened 2018-05-12 04:06 UTC
I implemented a Xamarin.iOS binding library using Sharpie for a mobile SDK native available for iOS only.

I ran over most of the documentation about Sharpie but I'm facing this issue when building the project:

* After creating the binding and use it for a Xamarin.Forms (iOS only) it It gets a compiling issue for a generated class file. 
* I'm able to fix it manually by changing the misinterpreted type to a "var" and that's it.
* Unfortunately, my CI pipeline can't do that so it gets broken builds too.

Output file in VS for Mac
../[ProjectName.iOS]/obj/Debug/ios/ObjCRuntime/Trampolines.g.cs

![Trampolines.cs](https://pbs.twimg.com/media/DZd9BKJWsAEsoDW.jpg)
### Steps to Reproduce

1. Create a Xamarin binding project
2. Bring a .framework file
3. Use Sharpie for creating the Binding
4. Reference your new binding as part of a Xamarin iOS project (aka Xamarin.Forms flavored project)
5. Clean All and build the project

### Expected Behavior
Building the Xamarin Binding shouldn't bring up compiling issues on internal/generated tooling classes

### Actual Behavior
Local development build broken, CI/CD pipeline got broken too

### Environment
VS For Mac

```
Visual Studio Community 2017 for Mac
Version 7.5 (build 1254)
Installation UUID: e907c918-e368-4331-846d-fc7bd7838c7f
Runtime:
	Mono 5.10.1.47 (2017-12/8eb8f7d5e74) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

	Package version: 510010047

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Version: 2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.3 (14154)
Build 9E145

Xamarin.Mac
Version: 4.4.1.176 (Visual Studio Community)

Xamarin.iOS
Version: 11.10.1.177 (Visual Studio Community)
Hash: 7e782c1e
Branch: d15-7
Build date: 2018-04-25 15:27:13-0400

Xamarin.Android
Version: 8.3.0.19 (Visual Studio Community)
Android SDK: /Users/stvansolano/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Build Information
Release ID: 705001254
Git revision: 498923ea36d2c7fe440c4e4b8cfb75bd50bbd748
Build date: 2018-05-05 10:35:24-04
Xamarin addins: 219f1c4943b4693b837b4173dd10ea982a47c852
Build lane: monodevelop-lion-d15-7

Operating System
Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

Enabled user installed addins
EditorConfig 1.2
```

### No Example Project provided
* Action item: Contact for a Private project access or setup the binding or invitation or call to follow-up: stvansolano@gmail.com

**Comment by dalexsoto** [comment] 2018-05-12 05:26
Thank you for contacting us!

I can definitely recognize the Twilio namespace when I see it 😄. Looks like a `delegate` signature is not currently supported by our tooling  are you able to share the Objective-C (block) and C# delegate signature generated by sharpie for `TWSDataMutator`?

I bet it is something like this in C#

```csharp
delegate NSMutableDictionary<NSString, NSObject> TWSDataMutator (/* some other params here */);
```

If this is the case just remove the generic part from the return type in the signature:

```csharp
delegate NSMutableDictionary TWSDataMutator (/* some other params here */);
```

The above should get you going. That said please do share both signatures so I can be 100% certain this is a bug so I can fix it and have a model for a test case so this does not happen again.

Thanks!!

**Comment by stvansolano** [comment] 2018-05-17 05:38
Hello @dalexsoto, I'm still unsure since as I mentioned earlier I'm able to fix it manually by changing the method.

From

```
static internal class SDTWSDataMutator {
    static internal readonly DTWSDataMutator Handler = Invoke;
			
    [MonoPInvokeCallback (typeof (DTWSDataMutator))]
    static unsafe IntPtr Invoke (IntPtr block, IntPtr arg0) {
        var descriptor = (BlockLiteral *) block;
        var del = (global::TwilioSync.iOS.TWSDataMutator) (descriptor->Target);
        Foundation.NSMutableDictionary`2[Foundation.NSString,Foundation.NSObject] retval = del ( Runtime.GetNSObject<global::Foundation.NSMutableDictionary<NSString, NSObject>> (arg0));
        return retval != null ? retval.Handle : IntPtr.Zero;
    }
}
```

To

```
static internal class SDTWSDataMutator {
    static internal readonly DTWSDataMutator Handler = Invoke;
    
    [MonoPInvokeCallback (typeof (DTWSDataMutator))]
    static unsafe IntPtr Invoke (IntPtr block, IntPtr arg0) {
        var descriptor = (BlockLiteral *) block;
        var del = (global::TwilioSync.iOS.TWSDataMutator) (descriptor->Target);
        var retval = del ( Runtime.GetNSObject<global::Foundation.NSMutableDictionary<NSString, NSObject>> (arg0));
        return retval != null ? retval.Handle : IntPtr.Zero;
    }
}
```
So it gets fixed by using `var` for me.

```
var retval = del ( Runtime.GetNSObject<global::Foundation.NSMutableDictionary<NSString, NSObject>> (arg0));
```

Is that enough? In my case that's blocking my CD/CD pipeline as I get another way to avoid it (possibly placing in a separate project/assembly)

**Comment by dalexsoto** [comment] 2018-06-25 21:06
Sorry, looks like I missed your reply... please ping me again if for some reason I go stale for some days.

Could you somehow share with me your binding project? Maybe put it in on github/dropbox.

**Comment by therealjohn** [comment] 2018-07-24 15:15
We've not heard back with the requested information. If you can provide the binding project, please share a link and Reopen this issue. Thank you!

**Comment by stvansolano** [comment] 2018-07-25 05:16
Hello guys, for sure! What's your email address where I can attach the binding? @therealjohn @dalexsoto

**Comment by therealjohn** [comment] 2018-07-25 12:57
@stvansolano Please upload here: https://www.dropbox.com/request/EFj4tEpEWN0UaDev45X0

**Comment by stvansolano** [comment] 2018-07-30 16:55
Done @therealjohn let me know if you are able to reproduce it.

**Comment by rolfbjarne** [comment] 2018-09-07 11:16
@NateVVV could you provide a test project we can use to reproduce your issue? That would let us make sure you're not running into a different problem.

**Comment by rolfbjarne** [comment] 2018-09-07 13:26
@stvansolano I've tried the project you sent us, but I can't reproduce the problem (it seems to be a different binding project though, there's nothing related to `Twilio` in it for instance). Did you upload the right project?

**Comment by stvansolano** [comment] 2018-09-14 15:15
Hello @rolfbjarne sure let me check that and try uploading a new one.

**Comment by VincentDondain** [comment] 2018-10-15 15:53
Hi @stvansolano could you please upload a new test project so we can reproduce the issue? Otherwise we'll have to close this issue.

Thanks (:

**Comment by rolfbjarne** [comment] 2018-11-05 10:33
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!

**Closed by rolfbjarne** 2018-11-05 10:33 UTC
Labels: bug, iOS, need-info
