### ISSUE TITLE
AppDelegate OpenUrl and ContinueUserActivity methods not called when launching app from deep link

### ISSUE THREAD

**Issue by justintoth** [xamarin/xamarin-macios#6303] opened 2019-06-14 15:36 UTC
### Steps to Reproduce

1. In AppDelegate.cs, override all 3 of the OpenUrl methods as well as the ContinueUserActivity method.
2. Write some code in each of the overridden methods, e.g. "return true;", and set a breakpoint on each.
3. Run the app, minimize it, then tap on a deep link, e.g. from an event in the Calendar app.

### Expected Behavior

The Xamarin iOS app will launch and one of the overridden methods will be called.

### Actual Behavior

The Xamarin iOS app launches (so the deep link registration is working) but the overridden methods are not called. This has been reported by many developers here: [https://forums.xamarin.com/discussion/12306/openurl-not-being-called?](https://forums.xamarin.com/discussion/12306/openurl-not-being-called?)

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.0.9 (build 5)
Installation UUID: ea49f888-5c94-4697-b87f-7c6494e85e6b
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

=== NuGet ===

Version: 4.8.2.5835

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.4
	2.1.9
	2.1.8
	2.1.2
SDK: /usr/local/share/dotnet/sdk/2.2.203/Sdks
SDK Versions:
	2.2.203
	2.1.505
	2.1.504
	2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.9
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.2.3.0 (Visual Studio Community)
Android SDK: /android/sdk
	Supported Android versions:
		5.0 (API level 21)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2018-08-rc@5ac37ccd385
Java.Interop: xamarin/java.interop/d16-0@c987483
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
MXE: xamarin/mxe/xamarin@b9cbb535
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.26.0@325e91a
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/justintoth/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-05-28 18:18:20 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 12.8.0.2 (Visual Studio Community)
Hash: f2248ae6
Branch: d16-0
Build date: 2019-04-23 11:59:04-0400

=== Xamarin Designer ===

Version: 4.17.4.420
Hash: 0a2420845
Branch: remotes/origin/d16-0
Build date: 2019-05-23 23:40:02 UTC

=== Build Information ===

Release ID: 800090005
Git revision: 72a44477dd706608c2300a568f71e5769f89f7ef
Build date: 2019-05-29 15:19:54+00
Build branch: release-8.0
Xamarin extensions: 3e94aa3836143b8f5a5b9151b61a80e2fd278d62

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64


```

**Comment by dalexsoto** [comment] 2019-06-15 13:34
Hello, thank you for reaching us!

I am able to use `OpenUrl` just fine, I will describe what I did

1. Register my custom URL (`xamdeep`) inside the the `info.plist`

<img width="810" alt="register" src="https://user-images.githubusercontent.com/204671/59551897-74b8cd00-8f4e-11e9-87ed-0eaf93ed7f0f.png">

2. override `OpenUrl`inside my `AppDelegate.cs`

```csharp
public override bool OpenUrl (UIApplication app, NSUrl url, NSDictionary options)
{
	// Test url:
	// xamdeep://hello?name=alex
	var o = new UIApplicationOpenUrlOptions (options);
	var components = NSUrlComponents.FromUrl (url, false);
	Console.WriteLine ($"Source App: {o.SourceApplication}");
	Console.WriteLine ($"Hello: {components.QueryItems.FirstOrDefault ().Value}");
	return true;
}
```

3. Open an url using safari `xamdeep://hello?name=alex` and let iOS open our sample app

4. Results are printed in console

<img width="365" alt="console" src="https://user-images.githubusercontent.com/204671/59552045-112f9f00-8f50-11e9-9f93-d95dadee1991.png">

Here is the project I created:
[XamDeepLinkExample.zip](https://github.com/xamarin/xamarin-macios/files/3293129/XamDeepLinkExample.zip)

I also tested this on device and works as expected. I'll close this issue but feel free to reopen if needed.

Hope this helps.


I created a small video that shows the workflow I followed.

![openurl](https://user-images.githubusercontent.com/204671/59552017-ba29ca00-8f4f-11e9-812b-244d148b0a5e.gif)

**Closed** 2019-06-15 13:34 UTC
Labels: iOS, question

**Comment by justintoth** [comment] 2019-06-17 20:37
Thanks for the detailed test. It turns out the issue is with Firebase SDK integration... If you call Firebase.Core.App.Configure(); at any point, then the ContinueUserActivity method (which is what universal links leverage) is no longer called when tapping on deep links. 

Not sure if this is a Xamarin iOS bug or a Firebase bug, but because Google Analytics is going away soon on mobile and is being replaced by Firebase Analytics, this is potentially a major issue.

**Comment by RichardSV15** [comment] 2019-10-14 22:49
@justintoth is there a workout to have a any of these methods called?

**Comment by minhphoenix** [comment] 2019-10-22 18:01
@dalexsoto the application must not be in the background, or system tray. If it's in the background, OpenUrl works as intended.

**Comment by XamMobileDev** [comment] 2020-01-02 12:37
@dalexsoto with VS2019 for Mac we are facing the same issue with iOS(Android working fine). 
Can you run the above sample code in VS2019 for Mac once and confirm it.

**Comment by luisresende247** [comment] 2020-01-22 16:21
I've removed Firebase.Core.App.Configure(); and set FirebaseAppDelegateProxyEnabled to false on Info.plist.

App opens but nothing gets called. Any updates on this?

**Comment by YabinSong** [comment] 2020-04-17 18:10
I'm also getting same issue with VS 2019 for Mac. Specifically I'm using Siri custom intent, and choose to .ContinueInApp when handling the intent. The app is launched fine, but ContinueUserActivity is not called. Please provide a solution for this, thanks.

**Comment by omatrot** [comment] 2020-05-05 16:18
Same problem here.
OpenUrl is not called
FinishedLaunching & ContinueUserActivity are...

**Comment by YabinSong** [comment] 2020-05-05 16:22
I've found out for me it was because I was targeting iOS 13 and since iOS 13 the delegate methods are moved to SceneDelegate instead of inside AppDelegate. Hope it's helpful for some.

**Comment by fabian1122** [comment] 2020-07-09 17:27
@YabinSong Hello, sorry to bother you, but I cannot solve the problem, you can help me by sending or sending me the SceneDelegate file and the settings you used to test,
Thank you
