### ISSUE TITLE
Cannot find registrar.m

### ISSUE THREAD

**Issue by xamarinshukla** [xamarin/xamarin-macios#3201] opened 2018-01-11 19:51 UTC
### Steps to Reproduce

1. Existing Xamarin Forms project. Upgrade to latest Visual studio code. 
To Be honest there is not much in the repro path. This started to happen right after I upgraded to latest Xcode and Latest Xamarin update from stable channel. 
2. Archive for publishing/Debugging/running 

### Expected Behavior
Build/run the app without any issues. 
### Actual Behavior
Error in building. Please file a report at Xamarin bugzilaa
### Environment

```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.3.3 (build 5)
Installation UUID: 4f26ca11-7974-48a2-aaee-774541324b2e
Runtime:
	Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010007

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.3
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.3
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.1.3.0 (Visual Studio Enterprise)
Android SDK: /Users/a0718250/Library/Android/sdk
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 27.0.1

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.iOS ===

Version: 11.6.1.3 (Visual Studio Enterprise)
Hash: f70a1348
Branch: xcode9.2
Build date: 2017-12-18 14:47:16-0500

=== Xamarin.Mac ===

Version: 4.0.0.215 (Visual Studio Enterprise)

=== Xamarin Inspector ===

Version: 1.3.2
Hash: 461f09a
Branch: 1.3-release
Build date: Tue, 03 Oct 2017 18:26:57 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 703030005
Git revision: b1c2982e201e71ef758866c9ade05f253a8c6f47
Build date: 2017-12-21 11:04:40-05
Xamarin addins: f397ddfbacfb39e60c9cc8d9e410f73faf8c2cbc
Build lane: monodevelop-lion-d15-5

=== Operating System ===

Mac OS X 10.13.0
Darwin 17.0.0 Darwin Kernel Version 17.0.0
    Thu Aug 24 21:48:19 PDT 2017
    root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Android Signature Tool 2.1.2
NuGet Package Explorer 0.2
NuGet Package Management Extensions 0.12.2
Redth's Addins 1.0.9
Internet of Things (IoT) development (Preview) 7.1


```

**Comment by mandel-macaque** [comment] 2018-01-15 11:23
Could you please add the full build logs and a sample project to try to reproduce the issue? A gist or a text file attached would be good for the logs, the project can be attached also once it is cleaned and zipped.

(You can drag and drop, something I must recognised is not super intuitive)

**Comment by xamarinshukla** [comment] 2018-01-16 17:23
[build.log](https://github.com/xamarin/xamarin-macios/files/1636124/build.log)
[Spike.zip](https://github.com/xamarin/xamarin-macios/files/1636128/Spike.zip)

I removed the packages directory. This project is a simple project created on Visual Studio for Mac, Open->New->Forms project.

**Comment by dalexsoto** [comment] 2018-02-22 01:09
Hello @xamarinshukla I gave it a try and I can't reproduce the issue you are seeing, do you mind giving this another try but deleting the `bin/` and `obj/` folders manually? Also make sure you are using the latest stable versions of Xamarin.

Another thing, is this happening on a build bot? (invoking build via command line) Or is this happening from Visual Studio for Mac?

**Comment by rolfbjarne** [comment] 2018-02-22 06:14
This is the error:

> System.ComponentModel.Win32Exception (0x80004005): ApplicationName='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang', CommandLine='...'

this means the compiler (`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang`) couldn't be found, which probably means that Xcode is corrupted somehow. Try deleting and installing Xcode again to see if that helps.

**Comment by xamarinshukla** [comment] 2018-02-22 16:34
Is there a clean Xcode uninstall script? or it is just drag and drop to
trash?

**Comment by therealjohn** [comment] 2018-03-26 17:39
@xamarinshukla 

You can just drag and drop to the trash. Have you already tried this and had success?

**Comment by xamarinshukla** [comment] 2018-03-26 17:43
I gave up the machine. Bought a new one. Did not had time to fix it.

**Comment by therealjohn** [comment] 2018-03-26 19:33
Thanks for letting me know. I'll close the issue for now. If you run into this again, please Reopen and let us know.

**Closed by therealjohn** 2018-03-26 19:33 UTC
Labels: iOS, need-info
