### ISSUE TITLE
macOS/iOS can't build x86/x64 when NuGet has runtimes

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-macios#5265] opened 2018-12-12 15:54 UTC
### Steps to Reproduce

1. File | New Solution...
2. Mac | App | Cocoa App
3. Install SkiaSharp as a `<PackageReference>`
4. Build

### Expected Behavior

A successful build.

### Actual Behavior

> (_CompileToNative target) -> 
> MMP : error MM0009: Error while loading assemblies: /Users/matthew/.nuget/packages/skiasharp/1.68.0/runtimes/win-x86/native/libSkiaSharp.dll [/Users/matthew/Projects/SkiaSharpMacTest/SkiaSharpMacTest/SkiaSharpMacTest.csproj]

### Workaround

I noticed that if I switch from x86 to Any CPU, the issue goes away. For some reason, if building for x86 or x64, it decides to bull in the Windows binaries. Interestingly, there is an `osx` runtime asset that is totally ignored - even if I am building for Any CPU.

### Environment

```
=== Visual Studio Community 2019 Preview for Mac ===

Version 8.0 Preview (8.0 build 869)
Installation UUID: 3df57dfa-e4cc-43a1-9f16-046811852c10
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.0.0.0 ( / b40230c0)

	Package version: 516000221

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

=== NuGet ===

Version: 4.7.0.5148

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.6
	2.1.2
	2.1.1
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.500/Sdks
SDK Versions:
	2.1.500
	2.1.302
	2.1.301
	2.1.4
	2.0.2
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 8

=== Xamarin.Android ===

Version: 9.1.4.2 (Visual Studio Community)
Android SDK: /Users/matthew/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.1   (API level 16)
		4.3   (API level 18)
		4.4   (API level 19)
		5.0   (API level 21)
		5.1   (API level 22)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)
		8.0   (API level 26)
		8.1   (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.3

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/matthew/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
1.8.0-9
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.1
Hash: 99d7ff4
Branch: remotes/origin/d16-0-p2~1
Build date: 2018-12-03 21:56:10 UTC

=== Xamarin Designer ===

Version: 4.17.1.189
Hash: 0e3953bd9
Branch: remotes/origin/d16-0-p1
Build date: 2018-11-07 13:21:06 UTC

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.2.1.12 (Visual Studio Community)
Hash: 65ec520f
Branch: 
Build date: 2018-12-05 12:06:09-0500

=== Xamarin.iOS ===

Version: 12.2.1.12 (Visual Studio Community)
Hash: 65ec520f
Branch: d15-9
Build date: 2018-12-05 12:06:09-0500

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 800000869
Git revision: 3c7c96b41ce6b823bf58bb89bda695448ccc97f5
Build date: 2018-12-03 21:59:44+00
Build branch: release-8.0
Xamarin extensions: 87c82bbb37a91ff539738267c414f0d6db88392c

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

### Build Logs

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/2672501/msbuild.binlog.zip)

### Example Project (If Possible)

Broken: [SkiaSharpMacTest.zip](https://github.com/xamarin/xamarin-macios/files/2672506/SkiaSharpMacTest.zip)
Fixed: [SkiaSharpMacTest-fixed.zip](https://github.com/xamarin/xamarin-macios/files/2672512/SkiaSharpMacTest-fixed.zip)

**Comment by VincentDondain** [comment] 2018-12-12 18:37
I was able to reproduce that same MMP error with the broken project and the following [environment](https://gist.github.com/VincentDondain/b1397955bded1676ecaa842aee556f76).

**Comment by mrward** [comment] 2019-06-27 08:28
This looks like this bugzilla bug - https://xamarin.github.io/bugzilla-archives/57/57229/bug.html - which has not been fixed.

A workaround is to add some NuGet runtime identifiers to the SkiaSharpMacTest project:

```
<RuntimeIdentifiers>osx;osx-x86;osx-x64</RuntimeIdentifiers>
<NuGetRuntimeIdentifier>osx</NuGetRuntimeIdentifier>
```

**Comment by wickedw** [comment] 2019-08-14 12:50
@mrward @mattleibow thanks, do you happen to have a fix for a Xamarin.iOS build (using forms and SkiaSharp.Views.Forms (1.68.0)

Thanks.

**Comment by SamuelDebruyn** [comment] 2019-10-14 07:31
As the issue also occurs for Xamarin.iOS, maybe the title should be changed to reflect that?

**Comment by hudaIT** [comment] 2019-11-09 01:00
> This looks like this bugzilla bug - https://xamarin.github.io/bugzilla-archives/57/57229/bug.html - which has not been fixed.
> 
> A workaround is to add some NuGet runtime identifiers to the SkiaSharpMacTest project:
> 
> ```
> <RuntimeIdentifiers>osx;osx-x86;osx-x64</RuntimeIdentifiers>
> <NuGetRuntimeIdentifier>osx</NuGetRuntimeIdentifier>
> ```

A dummy question, but where do i have to add these two lines here?

> <RuntimeIdentifiers>osx;osx-x86;osx-x64</RuntimeIdentifiers>
> <NuGetRuntimeIdentifier>osx</NuGetRuntimeIdentifier>

in my App.Ios.scproj?

**Comment by mattleibow** [comment] 2019-11-09 16:13
Yes, in the .csproj inside the first `<PropertyGroup>` element:

**Comment by VincentDondain** [comment] 2019-11-11 16:04
Here's the mono issue: https://github.com/mono/mono/issues/15569 (superseding the bugzilla issue)

**Comment by stackunderflows** [comment] 2020-02-17 16:45
It's the year 2020 and this is still a problem. Any hope of this getting fixed?

**Comment by goiditdev** [comment] 2020-03-03 23:09
Is there a fix in the works that will let me use skiashark 1.68 with xamarin.ios? This issue seems to have been open a while now!

**Comment by chrisfoulds** [comment] 2020-06-05 18:49
This may be related to my issue 
https://github.com/mono/SkiaSharp/issues/1304
What do I need to add to a iOS project? , things above are for macos

**Comment by mhempel-unl** [comment] 2020-06-07 22:21
> This may be related to my issue
> [mono/SkiaSharp#1304](https://github.com/mono/SkiaSharp/issues/1304)
> What do I need to add to a iOS project? , things above are for macos

Not sure if this helps, but what worked for me was sort of indicated above: In Visual Studio, for my Xamarin.iOS project, the settings under Build -> Compiler -> Platform target was set t x86, which resulted in that skiasharp build issue.I changed that to Any CPU, did a clean and rebuild, and it worked!

**Comment by chrisfoulds** [comment] 2020-06-08 05:08
> > This may be related to my issue
> > [mono/SkiaSharp#1304](https://github.com/mono/SkiaSharp/issues/1304)
> > What do I need to add to a iOS project? , things above are for macos
> 
> Not sure if this helps, but what worked for me was sort of indicated above: In Visual Studio, for my Xamarin.iOS project, the settings under Build -> Compiler -> Platform target was set t x86, which resulted in that skiasharp build issue.I changed that to Any CPU, did a clean and rebuild, and it worked!

there is no option for that, it's x86_64 or nothing, well not nothing as it makes you pick one.
I found if I downgraded both mono and monoios it started working again.

**Comment by comfr3ak** [comment] 2020-06-13 13:42
> > This may be related to my issue
> > [mono/SkiaSharp#1304](https://github.com/mono/SkiaSharp/issues/1304)
> > What do I need to add to a iOS project? , things above are for macos
> 
> Not sure if this helps, but what worked for me was sort of indicated above: In Visual Studio, for my Xamarin.iOS project, the settings under Build -> Compiler -> Platform target was set t x86, which resulted in that skiasharp build issue.I changed that to Any CPU, did a clean and rebuild, and it worked!

For the record, this fixed the problem for me too. Was having exact same issue.

**Comment by chrisfoulds** [comment] 2020-06-13 18:04
@comfr3ak see attached screenshots
<img width="711" alt="Screenshot 2020-06-13 at 19 03 17" src="https://user-images.githubusercontent.com/16035209/84575903-bde16e00-ada8-11ea-851d-e0d6705d7009.png">
<img width="708" alt="Screenshot 2020-06-13 at 19 04 19" src="https://user-images.githubusercontent.com/16035209/84575905-c174f500-ada8-11ea-9e34-a6d0528f0045.png">

**Comment by chrisfoulds** [comment] 2020-06-17 16:01
Any body? , if I downgrade to Xamarin.iOS 13.16 it works, 13.18 & 13.20 fail

**Comment by mattleibow** [comment] 2020-06-17 16:33
I also found that I had to remove the `<PlatformTarget>` elements from the iOS project file. For some reason, if this exists - and it might be x86/x64 - then the compiler suddenly thinks it is building for Windows. iOS does not use it anyway, it is AOT'ed.

**Comment by chrisfoulds** [comment] 2020-06-17 17:04
I have no < PlatformTarget> elements in the ios project file.

**Comment by mattleibow** [comment] 2020-06-17 18:02
Try adding one wit AnyCPU as a value? I haven't seen this error recently, which means nothing...

**Comment by DeerSteak** [comment] 2020-08-17 15:00
Adding the PlatformTarget tag with AnyCPU as a value doesn't work.

It's fine on my machine, because it got the right framework. Automated builds are broken on AppCenter for my app because it insists on downloading the win-64 version. When I look at References in Visual Studio 2019 on my machine it doesn't show SkiaSharp, it shows the path to the DLL like this:

C:\Users\me\.nuget\packages\skiasharp\2.80.1\build\xamarinios1.0\libSkiaSharp.framework

Instead of the name of the reference like it does for every other package.

**Comment by mattleibow** [comment] 2020-10-14 15:48
Just started seeing this again on all the latest bits. 😢 

I might have to start adding warnings in my targets to catch this. Not sure what other issues  this will cause...

**Comment by chrisfoulds** [comment] 2020-10-14 15:57
Xamarin on iOS is just broke - I am actually buying a PC again just to get my work done, it's a total joke.

**Comment by spouliot** [comment] 2021-01-22 18:30
Seems to be a dupe of https://github.com/dotnet/msbuild/issues/6072
for which I opened an issue on msbuild repo https://github.com/dotnet/msbuild/issues/6072

**Closed by spouliot** 2021-01-22 18:30 UTC
Labels: bug, macOS, msbuild

**Comment by sdebruyn** [comment] 2021-01-22 19:03
@spouliot This issue from 2017 has become a dupe of an untriaged issue which you opened 32 minutes ago? How did that happen? Did we file it in the wrong place?

**Comment by mhempel-unl** [comment] 2021-01-22 19:10
I find this a little disrespectful to open a new issue and then close all other that look like the same. This issue has been around far longer.

----------------------------------------------------------

Michael Hempel, Ph.D.

Associate Director, Advanced Telecommunications Engineering Laboratory

Research Assistant Professor, Department of Electrical and Computer Engineering
College of Engineering, University of Nebraska–Lincoln
Office: STC 201, Scott Technology Center, 6825 Pine Street, Omaha, NE 68106
Mail: PKI 200, Peter Kiewit Institute, 1110 South 67th Street, Omaha, NE 68182
402-554-3521 | mhempel2@unl.edu | www.tel.unl.edu<http://www.tel.unl.edu>


________________________________

**Comment by chrisfoulds** [comment] 2021-01-22 19:33
Typical Microsoft bullshit, raise new ticket , close existing ones and then it doesn't look like it's been sitting on your backlog forever

**Comment by neminush** [comment] 2021-03-17 11:06
I ran into a similar problem with Visual Studio for Mac 8.9.2 (build 0) and early versions.

/Users/Neocriss/Documents/iLive.Mobile/ILive/ILive.iOS/MTOUCH: Error MT0009: Error while loading assemblies: /Users/Neocriss/.nuget/packages/harfbuzzsharp/2.6.1.7/runtimes/win-x86/native/libHarfBuzzSharp.dll. (MT0009) (ILive.iOS)

I added the following lines to the file 'ILive.iOS.csproj':
```
<RestoreProjectStyle>PackageReference</RestoreProjectStyle>
<RuntimeIdentifiers>osx;osx-x86;osx-x64</RuntimeIdentifiers>
```
then the problem disappeared.
