### ISSUE TITLE
VS MacOS build fails with: error MT0000: Unexpected error

### ISSUE THREAD

**Issue by dannyatftecu** [xamarin/xamarin-macios#4046] opened 2018-05-07 18:05 UTC
### Steps to Reproduce

1. Update to the latest VS Mac as of 5/7/2018 10AM PDT.
2. Build for iPhone [hardware]
3. Fail with "Unexpected error."
4. This build was working fine last week before I upgraded VS Mac.

### Expected Behavior

Build like iOS Simulator without error.

### Actual Behavior

Build error only for iOS device build.

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.5 (build 1254)
Installation UUID: 0cdcd297-61e0-41a3-80cc-ce8ccd7de743
Runtime:
	Mono 5.10.1.47 (2017-12/8eb8f7d5e74) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

	Package version: 510010047

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.3.0.19 (Visual Studio Community)
Android SDK: /Users/nikhilshinde/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		5.0 (API level 21)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.4.1.176 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.10.1.177 (Visual Studio Community)
Hash: 7e782c1e
Branch: d15-7
Build date: 2018-04-25 15:27:13-0400

=== Build Information ===

Release ID: 705001254
Git revision: 498923ea36d2c7fe440c4e4b8cfb75bd50bbd748
Build date: 2018-05-05 10:35:24-04
Xamarin addins: 219f1c4943b4693b837b4173dd10ea982a47c852
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1


```

### Build Logs

Main error:     MTOUCH : error MT0000: Unexpected error - Please file a bug report at http://bugzilla.xamarin.com
[error_build050618.log](https://github.com/xamarin/xamarin-macios/files/1980924/error_build050618.log)

**Comment by dannyatftecu** [comment] 2018-05-07 18:30
I tried to reproduce this error by rebuilding https://github.com/xamarin/ios-samples/tree/master/ios10/MonkeyNotify but it built fine for iPhone.  Sigh.

**Comment by spouliot** [comment] 2018-05-07 19:11
```
    MTOUCH : error MT0000: Unexpected error - Please file a bug report at http://bugzilla.xamarin.com
    System.InvalidOperationException: Sequence contains no matching element
      at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00012] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/external/corefx/src/System.Linq/src/System/Linq/First.cs:30 
      at Registrar.StaticRegistrar.GetBlockProxyAttributeMethod (Mono.Cecil.MethodDefinition method, System.Int32 parameter) [0x00020] in /Users/builder/data/lanes/5944/7e782c1e/source/xamarin-macios/tools/common/StaticRegistrar.cs:4121 
      at Registrar.StaticRegistrar.GetBlockWrapperCreator (Registrar.Registrar+ObjCMethod obj_method, System.Int32 parameter) [0x00011] in /Users/builder/data/lanes/5944/7e782c1e/source/xamarin-macios/tools/common/StaticRegistrar.cs:4065 
      at Registrar.StaticRegistrar.Specialize (Registrar.AutoIndentStringBuilder sb, Registrar.Registrar+ObjCMethod method, System.Collections.Generic.List`1[T] exceptions) [0x0216b] in /Users/builder/data/lanes/5944/7e782c1e/source/xamarin-macios/tools/common/StaticRegistrar.cs:3683 
      at Registrar.StaticRegistrar.Specialize (Registrar.AutoIndentStringBuilder sb) [0x00f1e] in /Users/builder/data/lanes/5944/7e782c1e/source/xamarin-macios/tools/common/StaticRegistrar.cs:2963 
```

@rolfbjarne I guess we're missing (at least) an error code for the condition above.

**Comment by rolfbjarne** [comment] 2018-05-08 05:44
@dannyatftecu would it be possible to get access to your project so that I can reproduce this myself?

**Comment by dannyatftecu** [comment] 2018-05-08 16:02
Unfortunately, it's not possible for me to share.

**Comment by dannyatftecu** [comment] 2018-05-08 16:48
Well, I'd have to delete all the exe, dll, .o, .s, .m, .arm64, pdb files that are specific to our project, along with "Xamarin.Sdk".  And rename contents (the project specific path names) of the various .txt files .  If that's still OK, then I can prepare the zip.

**Comment by spouliot** [comment] 2018-05-08 17:47
@dannyatftecu we can't be sure without trying but that _small_ subset is unlikely to include what's causing the error you're experiencing.

@rolfbjarne it might not be the _full_ fix but we should not report `MT0000` and that can be fixed independently. That will give newer `mtouch` versions a better error with the actual location of the code that trigger the condition. @dannyatftecu  could update and see what's reported.

**Comment by brendanzagaeski** [comment] 2018-05-08 20:25
Cross-referencing note for the Xamarin team

An error that matches this exception message and top line of the exception call stack was reported in: <https://developercommunity.visualstudio.com/content/problem/247814/blocking-xamarin-ios-build-breaks-with-unexpected.html>.

**Comment by rolfbjarne** [comment] 2018-05-09 13:17
@dannyatftecu can you try installing this package, rebuild, and paste the error here: https://bosstoragemirror.azureedge.net/wrench/macios-mac-issue-4046/dd/ddcc3d143731456eb856d57ce44afabfa1d19972/xamarin.ios-11.11.0.291.pkg?

The error message should now show which type is causing the problem, and if possible please share the corresponding assembly with us.

**Comment by dannyatftecu** [comment] 2018-05-09 16:49
Here's the updated error message: 

`MTOUCH : error MT4175: The type 'iAd.AdAction, Xamarin.iOS' does not contain a method named 'Create'. Please file a bug report at https://bugzilla.xamarin.com.
`

**Comment by dannyatftecu** [comment] 2018-05-09 16:58
[error_build20180509.log](https://github.com/xamarin/xamarin-macios/files/1988748/error_build20180509.log)

**Comment by dannyatftecu** [comment] 2018-05-09 17:21
Even with some files removed, it [mtouch-cache] still compressed to 34MB zip.  I've included the arm64 folders with some edits as well as the 3 .txt files [with edits of course].

[somefilesfrommtouch-cache20180509.zip](https://github.com/xamarin/xamarin-macios/files/1988811/somefilesfrommtouch-cache20180509.zip)

**Comment by rolfbjarne** [comment] 2018-05-10 13:04
@dannyatftecu that wasn't as helpful as I hoped 😒 

Can you try this build: https://bosstoragemirror.azureedge.net/wrench/macios-mac-issue-4046/fe/fe8af954e5bb46521bf87242c559dffea0a743c9/xamarin.ios-11.11.0.292.pkg? I changed the error to a warning, which should then result in more warnings with more information - please paste all warnings here.

This it might even make your project build, but since I don't quite understand what's happening yet, it's entirely possible more errors will show up later in the build process.

**Comment by rolfbjarne** [comment] 2018-05-10 15:32
@dannyatftecu another customer provided a project for this error, and I was able to track that down to having  `[BlockProxy (typeof (SomeType)]` in his code.

My guess is that you have something like this somewhere:

```csharp
public override void SomeFunction ([BlockProxy (typeof (AdAction))]` SomeType someArgument)
{
}
```

The fix is to remove the `[BlockProxy]` attribute, like this:

```csharp
public override void SomeFunction (SomeType someArgument)
{
}
```

**Comment by dannyatftecu** [comment] 2018-05-10 17:33
I can confirm that removing it made the build go through and the app runs OK.

**Comment by rolfbjarne** [comment] 2018-05-11 05:07
OK, I'm closing this as a duplicate of #4072 then. Thanks for confirming.

**Closed by rolfbjarne** 2018-05-11 05:07 UTC
Labels: bug, iOS, need-info
