### ISSUE TITLE
IOS Llvm never finishes

### ISSUE THREAD

**Issue by JanettHolst290490** [xamarin/xamarin-macios#6818] opened 2019-08-21 11:48 UTC
### Steps to Reproduce

1. Have a Xamarin.IOS project with a shared library (.NET Standard 2.0)
2. Set the IOS project as startup, run a release configuration with the following configuration:

Shared Library:
```
    <IntermediateOutputPath>obj\iPhone\Release</IntermediateOutputPath>
    <DebugType></DebugType>
    <Optimize>true</Optimize>
    <OutputPath>...</OutputPath>
    <DefineConstants>...</DefineConstants>
    <NoWarn></NoWarn>
    <NoStdLib>false</NoStdLib>
```

IOS project:
```
    <Optimize>true</Optimize>
    <OutputPath>...</OutputPath>
    <DefineConstants>...</DefineConstants>
    <WarningLevel>4</WarningLevel>
    <CodesignKey>iPhone Distribution</CodesignKey>
    <MtouchFloat32>true</MtouchFloat32>
    <CodesignEntitlements>Entitlements-prod.plist</CodesignEntitlements>
    <MtouchLink>SdkOnly</MtouchLink>
    <MtouchArch>ARMv7s, ARM64</MtouchArch>
    <MtouchHttpClientHandler>HttpClientHandler</MtouchHttpClientHandler>
    <MtouchVerbosity></MtouchVerbosity>
    <CodesignProvision>Automatic:AdHoc</CodesignProvision>
    <BuildIpa>true</BuildIpa>
    <MtouchUseLlvm>true</MtouchUseLlvm>
```

3. OR run the following in the command line:
```
msbuild AulaNative.iOS.csproj /p:Configuration="Release" /p:Platform="iPhone" /p:MTouchLink="SdkOnly" /p:BuildIpa=true /t:Clean,Build
```

### Expected Behavior
The build finishes successfully or finishes and tells me why it fails.  

### Actual Behavior
It never finishes (I tried waiting for 90 minutes)
In the console log it never gets past the "_CompileToNative" step.
```
...

_CompileAppManifest:
  Directory "bin/iPhone/Release/AulaNative.iOS.app.dSYM" doesn't exist. Skipping.
_ParseExtraMtouchArgs:
    NoSymbolStrip Output: False
    NoDSymUtil Output: false
_CompileToNative:
  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/[user]/workspace/mobile-app/application/[project]/iOS/obj/iPhone/Release/response-file.rsp 

```
However, if I run it with 
```
<MtouchUseLlvm>false</MtouchUseLlvm>
```
then it works fine.

### Environment

```
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.2.4 (build 17)
Installation UUID: 4c2dc437-7869-4392-9b24-f24a2c4f02e7
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000327

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.327 (2019-02/f8ea05bddcb) (64-bit)
	Package version: 600000327

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.2
	2.1.1
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.701/Sdks
SDK Versions:
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.302
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.4.1.0 (Visual Studio Enterprise)
Commit: xamarin-android/d16-2/ebd65c9
Android SDK: /Users/janettholst/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.1
SDK Build Tools Version: 29.0.1

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/janettholst/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
1.8.0-9
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.60
Hash: 686c817
Branch: remotes/origin/d16-2
Build date: 2019-08-07 15:49:58 UTC

=== Apple Developer Tools ===

Xcode 10.3 (14492.2)
Build 10G8

=== Xamarin.Mac ===

Version: 5.14.0.114 (Visual Studio Enterprise)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:06-0400

=== Xamarin.iOS ===

Version: 12.14.0.114 (Visual Studio Enterprise)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:05-0400

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Xamarin Designer ===

Version: 16.2.0.379
Hash: 3f0652957
Branch: remotes/origin/d16-2
Build date: 2019-08-01 17:32:50 UTC

=== Build Information ===

Release ID: 802040017
Git revision: 9b155edbf23e9fe8b477b3236a342164fabf5f6b
Build date: 2019-08-16 00:21:01+00
Build branch: release-8.2
Xamarin extensions: 9f2598b5f2371ba2903988c2cd87a9759d0255f2

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Thu Jun 20 18:42:21 PDT 2019
    root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64


```

### Build Logs
I'd rather not include the entire build log since it contains project details. I hope this is useful, this is the end of the file:
```
_CopyFilesMarkedCopyLocal:
  ...
_CopyAppConfigFile:
  ...
_DetectSigningIdentity:
  ...
_CopyResourcesToBundle:
  ...
_DetectDebugNetworkConfiguration:
    DebugIPAddresses: 
_CompileAppManifest:
  Directory "bin/iPhone/Release/AulaNative.iOS.app.dSYM" doesn't exist. Skipping.
_ParseExtraMtouchArgs:
    NoSymbolStrip Output: False
    NoDSymUtil Output: false
_CompileToNative:
  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/[user]/workspace/mobile-app/application/[projectname]/iOS/obj/iPhone/Release/response-file.rsp 
```

### Example Project (If Possible)
Unfortunately not possible since I do not own this project.

**Comment by rolfbjarne** [comment] 2019-08-21 11:52
> However, if I run it with false, then it works fine.

Do you mean if you set `/p:BuildIpa=false`?

Does it work if you build only for ARM64?

```xml
<MtouchArch>ARM64</MtouchArch>
```

**Comment by JanettHolst290490** [comment] 2019-08-21 12:05
Ups, it removed my xml tags. I meant that it works if I run it with
```
<MtouchUseLlvm>false</MtouchUseLlvm>
```
Let me try without ARMv7s

**Comment by JanettHolst290490** [comment] 2019-08-21 13:02
It seems to work if I set only ARM64.
I only need IPhone 5S and up, so I suppose I will just leave out ARM-v7s

**Comment by rolfbjarne** [comment] 2019-08-21 13:07
Since it works with only ARM64, this is most likely a variation/duplicate of #6787, so I'm closing this.

**Closed by rolfbjarne** 2019-08-21 13:07 UTC
Labels: bug, iOS, need-info

**Comment by EvoPulseGaming** [comment] 2019-11-17 08:29
What about 32 bit devices? I have an ipad mini I use for debugging.... The duplicate was also closed. why
