### ISSUE TITLE
Error when deploying Broker from Visual Studio 2019

### ISSUE THREAD

**Issue by kipters** [xamarin/xamarin-macios#10365] opened 2021-01-08 14:09 UTC
### Steps to Reproduce

1. Try to connect to a Mac from VS 2019

### Expected Behavior

- VS 2019 connects to the build host

### Actual Behavior

- VS 2019 does not connect and shows the error:

>An error occurred while trying to start the Broker...
>An error occurred while installing Broker 16.8.000.260

### Environment

```
Microsoft Visual Studio Enterprise 2019
Version 16.8.3
VisualStudio.16.Release/16.8.3+30804.86
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00433-90001-41734-AA462
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.8.554.20160
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.554.20160
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.554.20160
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.8.554.20160
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.8.20241.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.11.102.28613
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.20902.1 Commit Hash:b474efcb6f92db52a8f8e2e6a8cb9648476885cc
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.8.20241.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.8.20241.2
Conda support for Python projects.

Python - Django support   16.8.20241.2
Provides templates and integration for the Django web framework.

Python - IronPython support   16.8.20241.2
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.8.20241.2
Profiling support for Python projects.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62010.06180
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   16.0.30608.117
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Cross Platform Mobile Development (iOS)   16.0.30608.117
Visual C++ for Cross Platform Mobile Development (iOS)

Visual C++ for Linux Development   1.0.9.30608
Visual C++ for Linux Development

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.260 (d16-8@fd405a2)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.17 (d16-8/c0e2b8e)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: be2226b
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc


Xamarin.iOS and Xamarin.Mac SDK   14.6.0.15 (87a1b18d8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

```
=== Visual Studio Community 2019 for Mac ===

Version 8.8.4 (build 30)
Installation UUID: ab697fa3-73d3-483d-9e8a-92f832ac90ce
  GTK+ 2.24.23 (Raleigh theme)
  Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

  Package version: 612000113

=== Mono Framework MDK ===

Runtime:
  Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
  Package version: 612000113

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.101/Sdks
SDK Versions:
  5.0.101
  3.1.404
  3.1.402
  3.1.401
  3.1.302
  3.1.301
  3.1.300
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
  5.0.1
  3.1.10
  3.1.8
  3.1.7
  3.1.6
  3.1.5
  3.1.4
  2.1.23
  2.1.22
  2.1.21
  2.1.20
  2.1.19
  2.1.18

=== .NET Core 3.1 SDK ===

SDK: 3.1.404

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.2 (17535)
Build 12B45b

=== Xamarin.Mac ===

Version: 7.0.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:40-0500

=== Xamarin.iOS ===

Version: 14.6.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:41-0500

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Xamarin.Android ===

Version: 11.1.0.17 (Visual Studio Community)
Commit: xamarin-android/d16-8/c0e2b8e
Android SDK: /Users/fabio/Library/Developer/Xamarin/android-sdk-macosx
  Supported Android versions:
    8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.3

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/fabio/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:24 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:44 UTC

=== Build Information ===

Release ID: 808040030
Git revision: eaa21a8983aa5c4bcf6a665892478b4f3d413418
Build date: 2020-12-10 11:06:12-05
Build branch: release-8.8
Xamarin extensions: eaa21a8983aa5c4bcf6a665892478b4f3d413418

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Thu Oct 29 22:56:45 PDT 2020
    root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
```

### Build Logs

```
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Checking host configuration for connecting to 'Fabio’s MacBook Air'...
System.Net.Mqtt.Sdk.ClientPacketListener|Information|0|Client vs9400kipt - Dispatching Publish message to flow PublishReceiverFlow and topic xma/ping/vs9400kipt
Xamarin.Messaging.Client.PingHandler|Information|0|vs9400kipt received ping. Sending acknowledge...
System.Net.Mqtt.Sdk.MqttClientImpl|Information|0|Client vs9400kipt - An application message for topic xma/ping/vs9400kipt was received
System.Net.Mqtt.Sdk.ClientPacketListener|Information|0|Client vs9400kipt - Dispatching PublishAck message to flow PublishSenderFlow
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Checking SSH configuration...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Initializing environment...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Checking available disk space...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Checking Mono installation...
Xamarin.Messaging.Ssh.SshCommandRunner|Warning|0|Failed to execute 'which mono64': ExitStatus = 1
Xamarin.Messaging.Ssh.SshCommands|Information|0|A valid Mono installation has been found at '/Library/Frameworks/Mono.framework/Versions/Current/bin/mono64'
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Checking Xamarin iOS installation...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Checking host configuration for connecting to 'Fabio’s MacBook Air'...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Server State transition from ConfiguringState to ConfiguredState on Fabio’s MacBook Air (192.168.1.213)
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Host 'Fabio’s MacBook Air' is configured correctly
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Server State transition from ConfiguredState to ConnectingState on Fabio’s MacBook Air (192.168.1.213)
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Starting connection to 'Fabio’s MacBook Air'...
System.Net.Mqtt.Sdk.ClientPacketListener|Information|0|Client vs9400kipt - Dispatching Publish message to flow PublishReceiverFlow and topic vs9400kipt/response/xma/ping/Broker168000260
System.Net.Mqtt.Sdk.MqttClientImpl|Information|0|Client vs9400kipt - An application message for topic vs9400kipt/response/xma/ping/Broker168000260 was received
Xamarin.Messaging.Ssh.MessagingCommands|Information|0|Checking Broker 16.8.000.260 installation...
Xamarin.Messaging.Ssh.MessagingCommands|Warning|0|The target directory checksum for '/Users/kip/Library/Caches/Xamarin/XMA/Agents/Broker/16.8.000.260' couldn't be calculated
Xamarin.Messaging.Ssh.MessagingCommands|Information|0|Installing Broker 16.8.000.260...
Xamarin.Messaging.Ssh.MessagingCommands|Warning|0|The target directory checksum for '/Users/kip/Library/Caches/Xamarin/XMA/Agents/Broker/16.8.000.260' couldn't be calculated
Xamarin.Messaging.Ssh.MessagingCommands|Warning|0|The target directory checksum for '/Users/kip/Library/Caches/Xamarin/XMA/Agents/Broker/16.8.000.260' couldn't be calculated
Xamarin.Messaging.Ssh.MessagingService|Error|0|An error occurred while trying to start the Broker...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Starting connection to 'Fabio’s MacBook Air'...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Server State transition from ConnectingState to DisconnectingState on Fabio’s MacBook Air (192.168.1.213)
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Starting disconnection from Fabio’s MacBook Air...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Starting disconnection from Fabio’s MacBook Air...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Server State transition from DisconnectingState to DisconnectedState on Fabio’s MacBook Air (192.168.1.213)
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|The connection to 'Fabio’s MacBook Air' has been finished
Xamarin.Messaging.Integration.State.ServerStateContext|Error|0|An error occurred while trying to start the Broker...
Xamarin.Messaging.Ssh.Exceptions.AgentInstallationException: An error occurred while installing Broker 16.8.000.260 ---> Xamarin.Messaging.Exceptions.MessagingException: Integrity check failed between source and target content. Source path: c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\extensions\xamarin.visualstudio\Broker.zip, Target path: /Users/kip/Library/Caches/Xamarin/XMA/Agents/Broker/16.8.000.260
   at Xamarin.Messaging.Ssh.MessagingCommands.<InstallAsync>d__7.MoveNext() in C:\A\1\77\s\External\messaging\src\Xamarin.Messaging.Ssh\MessagingCommands.cs:line 72
   --- End of inner exception stack trace ---
   at Xamarin.Messaging.Ssh.MessagingCommands.<InstallAsync>d__7.MoveNext() in C:\A\1\77\s\External\messaging\src\Xamarin.Messaging.Ssh\MessagingCommands.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Ssh.MessagingService.<StartBrokerAsync>d__103.MoveNext() in C:\A\1\77\s\External\messaging\src\Xamarin.Messaging.Ssh\MessagingService.cs:line 802
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Ssh.MessagingService.<ConnectMqttAsync>d__95.MoveNext() in C:\A\1\77\s\External\messaging\src\Xamarin.Messaging.Ssh\MessagingService.cs:line 622
```

> VS bug [#1263902](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1263902)

**Comment by kipters** [comment] 2021-01-08 17:22
Small addendum: the same error occurs when connecting to two different MacBooks, one running macOS Big Sur and the other one on Catalina. Same error and behavior.
I'll try connecting from another Windows machine to see if it makes any difference.

**Comment by mauroa** [comment] 2021-02-26 13:36
Hi @kipters 
Could you please attach the entire VS log?
Also, what shell do you have configured on the Mac? We currently support a limited set of shells and we also have a known issue about Pair To Mac not supported with custom shell implementations like "oh my zsh".
This could cause errors when executing some SSH commands, causing the connection to fail. In this case it's failing when trying to deploy/run the Broker on the Mac, so that could be the case. We can confirm it by taking a look at the full log.
Thanks in advanced.

**Comment by kipters** [comment] 2021-02-26 17:00
Hi @mauroa
I'll try to get another full log later today and attach it here.
In the meantime, I usually use `fish` with oh-my-fish, but I'm not 100% sure I had already installed it on one of the two MacBooks I'd tried since I had wiped it up it just a couple hours before.
I'll also try to change the shell when I'm at it to get the log and update here.

**Comment by mauroa** [comment] 2021-02-26 18:09
Thanks @kipters.
Yes, please check what shell you are using on each Mac with failures and let me know. For the logs, please attach the logs when the connection fails so I can see the SSH errors in case it's because of the shell.

**Comment by kipters** [comment] 2021-02-26 19:08
Your suggestion was correct, it started working as soon as I switched to the default `zsh` on macOS, and it broke again when switching back to `fish`. I've attached the log for the one that failed.

[2021-02-26_20-00-45.9148.Ide.log](https://github.com/xamarin/xamarin-macios/files/6051854/2021-02-26_20-00-45.9148.Ide.log)

**Comment by mauroa** [comment] 2021-02-26 20:46
Good to know that was it. Currently the shells that we support are: "bash", "zsh", "ksh", "tcsh", "sh", "csh".
However we should be more clear on the logs and error messages about the real error, which is the incompatible shell. Right now the logs doesn't give any signal about what happened, and it's confusing.
We already have an opened ticket about supporting more shell versions and implementations, so that should cover this root cause. I'll also open an internal ticket to improve the diagnostic messages to be more clear when it fails because of this.
I'll close this issue since the workaround is to use one of the currently supported shells and the action items to support new ones are clear.
Thanks for your help.

**Closed by mauroa** 2021-02-26 20:46 UTC
Labels: external-xamarin-vs

**Comment by kipters** [comment] 2021-02-27 01:50
@mauroa Thank you!
