### ISSUE TITLE
iOS Use Safe Area Layout Guides not working in library project

### ISSUE THREAD

**Issue by lowleetak** [xamarin/xamarin-macios#3182] opened 2018-01-09 07:57 UTC
### Steps to Reproduce

1. Create a new solution
2. Create a new iOS library
3. Create a storyboard file in the newly created iOS library project
4. Create a UIViewController in the storyboard and assign label's constraints using safe area layout.
5. Set iOS app project to reference to the library project
6. Set the UIViewController as first screen
7. Run the application in iOS 10 and iOS 11 simulator

### Expected Behavior
App able to run on both iOS 10 and iOS 11 simulator. 

### Actual Behavior
App only able to run in iOS 11 but crash in iOS 10

### Environment

```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.3.2 (build 12)
Installation UUID: 16ccd9dd-7f71-4750-a921-690b9d774221
Runtime:
	Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010007

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/1.0.3/Sdks
SDK Version: 1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.iOS ===

Version: 11.6.1.2 (Visual Studio Enterprise)
Hash: 6857dfcc
Branch: xcode9.2
Build date: 2017-12-04 21:20:41-0500

=== Xamarin.Android ===

Version: 8.1.0.25 (Visual Studio Enterprise)
Android SDK: /Users/leetak/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.4   (API level 19)
		5.0   (API level 21)
		5.1   (API level 22)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 25.0.3

Java SDK: /usr
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.3.2
Hash: 461f09a
Branch: 1.3-release
Build date: Tue, 03 Oct 2017 18:26:57 GMT
Client compatibility: 1

=== Xamarin.Mac ===

Version: 4.0.0.214 (Visual Studio Enterprise)

=== Build Information ===

Release ID: 703020012
Git revision: 7d0c9d7ad46b125cf4b7bbf9532c0531b6433ce6
Build date: 2017-12-12 14:03:18-05
Xamarin addins: 6dddaa49fbecb2695fcdcd6b712eb269e288518c
Build lane: monodevelop-lion-d15-5

=== Operating System ===

Mac OS X 10.13.1
Darwin 17.2.0 Darwin Kernel Version 17.2.0
    Fri Sep 29 18:27:05 PDT 2017
    root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

WakaTime 3.0.0

```

**Comment by mandel-macaque** [comment] 2018-01-09 12:20
Hello,

In order to be able to reproduce the issue I created the following project/repo: 

https://github.com/mandel-macaque/xamarin-issue-3182

I have ran the above example in the following simulators:

* iPhone SE 10.0 - [Error](https://gist.github.com/mandel-macaque/35ef08705e6c4d71459f56c0607c6942)
* iPhone 7 10.0 - [Error](https://gist.github.com/mandel-macaque/fa5adf6511ee126ef4413e794634f23b)
* iPhone 7 10.3 - [Error] (https://gist.github.com/mandel-macaque/0a90c5056696b4f197aa3cc9e8146e6b)
* iPhone 8 iOS 11.2 - Success

Which indeed shows the issue does exist. Nevertheless I need to create a objc sample to ensure that the project or a similar one does work since, by the looks of it, the crash is not related to the xamarin code but an internal objc one.

**Comment by mandel-macaque** [comment] 2018-02-07 11:35
I am attaching an objc project that targets 10.0 that uses safe area layout and that, when executed in a iOS sim using 10.0 works, as well as, in a sim with 11.2:

![screen shot 2018-02-07 at 12 29 25](https://user-images.githubusercontent.com/2190086/35914327-2d4b21e0-0c03-11e8-89a9-dce7f3ec24d8.png)
[SimpleSafeAreaGuides.zip](https://github.com/xamarin/xamarin-macios/files/1702865/SimpleSafeAreaGuides.zip)

Will request information from the designer team to understand if we might be generating a possible issue in the storyboard file.

**Comment by alanmcgovern** [comment] 2018-02-07 12:31
The library project in this sample contains `Storyboard.storyboard`. This storyboard file is set to use the 'Project Deployment' ios version as it's deployment target.
<img width="1208" alt="screen shot 2018-02-07 at 12 29 42" src="https://user-images.githubusercontent.com/264396/35916543-a277e3be-0c02-11e8-8862-7b3fdcaf5f68.png">

The problem is that the library project cannot read the 'deployment target' value in the *executable* project where the Info.plist is, so it ends up defaulting to the latest iOS version when it is compiled. The only available solution is to ensure that every storyboard/xib contained in a project which is *not* the executable project has the correct minimum iOS value set in the `Deployment Target` setting.

**Comment by mandel-macaque** [comment] 2018-02-07 12:34
Closing issue after @alanmcgovern gave a way to fix the issue.

**Closed by mandel-macaque** 2018-02-07 12:34 UTC
Labels: iOS, need-info
