### ISSUE TITLE
Project template 'Single View App' should have zero errors but have "The type 'BigInteger' is required here and is unavailable."

### ISSUE THREAD

**Issue by AlonaBarabash** [xamarin/xamarin-macios#5078] opened 2018-11-02 12:47 UTC
### Steps to Reproduce

1. Select Template Category 'App' under 'iOS'
2. Select Template 'Single View App' under 'General'
3. Entering App Name as 'IOSSingleViewApp' and Organization Identifier as 'com.xamarin'
4. Select 'iPad'
5. Select 'iPhone'
6. Select iOS Target IOS101
7. Set the configuration to 'Debug|iPhoneSimulator'
8. Build > Build All

### Expected Behavior
Build successful
### Actual Behavior
Error message: Project templates should have zero errors Expected: <empty> But was: < " [Line]: 0 [Description]: The type 'BigInteger' is required here and is unavailable. You must add a reference to assembly 'System.Numerics, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. (FS1108) [File]: FSC [Project]: FSharpIOSSingleViewApp", " [Line]: 23 [Description]: The type 'UIUserInterfaceIdiom' does not support the operator '=' (FS0043) [File]: ViewController.fs [Project]: FSharpIOSSingleViewApp", " [Line]: 24 [Description]: The type 'UIInterfaceOrientation' does not support the operator '<>' (FS0043) [File]: ViewController.fs [Project]: FSharpIOSSingleViewApp", " [Line]: 6 [Description]: The type 'EntryPoint' is not defined. (FS0039) [File]: Main.fs [Project]: FSharpIOSSingleViewApp" > 
### Environment
System information
Bot name
XQA-XS-HighSierra-5
Operating System
Mac OS X 10.13.6
.NET Version
N/A
Java Version
N/A
Mono Version
N/A
Xamarin.Android Version
9.1.199.8
Xamarin.iOS Version
12.5.1.80
Xamarin.Mac Version
5.5.1.80
Visual Studio Version
7.8 Preview (7.8 build 1018)
Xamarin For Visual Studio
N/A

Video
[Screen Recording](http://xqa.blob.core.windows.net/video/macOsScreenRecord.mp4-4305724bde9c4b20ae5440a57dd29e2c.mp4)
Log files
[About information](http://xqa.blob.core.windows.net/gist/log-39c1d14758724608ac66cb9048ce6522.txt)
[Test log](http://xqa.blob.core.windows.net/gist/TestCreateBuildFSharpIOSSingleViewApp.txt.181024185032-98ab3b8b6add4ade85747942d4a72788.txt)
[SetConfigUserPrefs-b5b61cb587db4e99b6fbf9bb9c051d0a.txt](http://xqa.blob.core.windows.net/gist/SetConfigUserPrefs-b5b61cb587db4e99b6fbf9bb9c051d0a.txt)
[TestCreateBuildFSharpIOSSingleViewApp.Ide.log.181024185032-7443c137d7df4af489ab6a188d6cca54.txt](http://xqa.blob.core.windows.net/gist/TestCreateBuildFSharpIOSSingleViewApp.Ide.log.181024185032-7443c137d7df4af489ab6a188d6cca54.txt)
[MonoDevelopProperties.xml.181024185032-deba9edba7ce456eb8622a0849d8d358.txt](http://xqa.blob.core.windows.net/gist/MonoDevelopProperties.xml.181024185032-deba9edba7ce456eb8622a0849d8d358.txt)
[ActivityLogsXls](https://xqa.blob.core.windows.net/files/ActivityLog.xsl)

### Build Logs

[Build](http://xqa.blob.core.windows.net/gist/log-0724028846b3403f9d4b8ecfac6b4c6e.txt)

**Comment by spouliot** [comment] 2018-11-02 12:56
dupe of 
https://github.com/xamarin/xamarin-macios/issues/5070

**Closed by spouliot** 2018-11-02 12:56 UTC
