### ISSUE TITLE
A project with two shared projects crashes VS Mac

### ISSUE THREAD

**Issue by verybadcat** [xamarin/xamarin-macios#3219] opened 2018-01-13 16:39 UTC
### Steps to Reproduce

1.  Create a Xamarin.IOS project
2. Create two shared projects inside it. Add references to them.
3. Have a class in one shared project refer to a class in the other shared project

### Expected Behavior

You can edit, build, and run the solution.

### Actual Behavior

Xamarin.IOS frequently crashes, and if it doesn't crash, the references may fail to resolve at build time. In this particular example, I could add an ivar and have it build. But attempting to create an instance of that ivar crashed VS Mac, so I couldn't tell if that part would have built or not. In my real project, I can say that a lot of the references won't resolve at build time, and VS Mac crashes unpredictably.

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.3.3 (build 5)
Installation UUID: a4c66b52-bdb0-462b-b8a8-b29cac21f1e8
Runtime:
	Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010007

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.0
SDK: /usr/local/share/dotnet/sdk/2.0.0/Sdks
SDK Version: 2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.iOS ===

Version: 11.6.1.3 (Visual Studio Community)
Hash: f70a1348
Branch: xcode9.2
Build date: 2017-12-18 14:47:16-0500

=== Xamarin.Android ===

Version: 8.1.3.0 (Visual Studio Community)
Android SDK: /Users/william/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.2 (API level 17)
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 25.0.5
SDK Build Tools Version: 25.0.3

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.3.2
Hash: 461f09a
Branch: 1.3-release
Build date: Tue, 03 Oct 2017 18:26:57 GMT
Client compatibility: 1

=== Xamarin.Mac ===

Version: 4.0.0.215 (Visual Studio Community)

=== Build Information ===

Release ID: 703030005
Git revision: b1c2982e201e71ef758866c9ade05f253a8c6f47
Build date: 2017-12-21 11:04:40-05
Xamarin addins: f397ddfbacfb39e60c9cc8d9e410f73faf8c2cbc
Build lane: monodevelop-lion-d15-5

=== Operating System ===

Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Mon Nov 13 21:56:25 PST 2017
    root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

xUnit.NET 2 testing framework support 0.7.14
Internet of Things (IoT) development (Preview) 7.1


```

### Example Project (If Possible)

[SharedProjectTest.zip](https://github.com/xamarin/xamarin-macios/files/1628501/SharedProjectTest.zip)

In the particular solution, I was attempting to edit ClassB to add an ivar "public ClassA A {get;set;} and then type "A = new ClassA();" in the constructor, but this always crashes VS Mac.

> VS bug #552040

**Comment by mandel-macaque** [comment] 2018-01-15 11:15
Hello,

I have tested the attached project, and in my case, not only VS does crash, but it crashes when I'm trying to add the creation of the A instance with the followign trace:

https://gist.github.com/mandel-macaque/c1906309f5268b7527e8790258d6d3eb

Nevertheless, once I added the instance via an other editor everything work. Also, compiling via de command line results in a successful build:

https://gist.github.com/mandel-macaque/c90b75ed95969b64cb67f6713953a2d5

This means that we do have issues in VS for Mac but those are not present in xamarin.ios (which this issue was reported against). Tagging the issue to be a VS for mac for their team to pick up. 

Thanks for the report, once the VS team picks up this issue we will close it and will point to the VS for Mac issue tracking.

**Comment by mrward** [comment] 2018-05-08 15:08
I am unable to reproduce a crash using the latest stable Visual Studio for Mac 7.5.0.1254 (everything else from the stable channel). Also tried Visual Studio for Mac 7.4.0.1033.

My repro steps:

1. Open SharedProjectTest.
2. Open ClassB.
3. Type in: `public ClassA A { get; set; }`
4. In ClassB's constructor type in: `A = new ClassA ()`.
5. Build the solution.

If this can still be reproduced can the IDE log be attached? (Help - Open Log Directory)

**Closed** 2022-04-26 15:01 UTC
Labels: need-info, external-visual-studio-for-mac, high-priority
