### ISSUE TITLE
Linker does not remove unused assemblies if they are referenced in NSObject subclasses

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#15723] opened 2022-08-22 16:54 UTC
The linked does not correctly remove unused assemblies / methods when those calls are located in a NSObject subclass.
This increases the built .ipa unnecessarily.

### Steps to Reproduce

1. Download test project
2. Open terminal and navigate into the `test` folder
3. call `dotnet publish -c Release`
4. rename `/test/bin/Release/net6.0-ios/ios-arm64/publish/test.ipa` to a `zip` file and inspect

### Expected Behavior

The package does not contain System.Text.Json.dll & others
![Screenshot 2022-08-22 at 18 51 52](https://user-images.githubusercontent.com/2863198/185976188-f5ea8008-b3b1-4157-9450-df95783d982a.png)

### Actual Behavior

The package **does** not contain System.Text.Json.dll & others
![Screenshot 2022-08-22 at 18 51 59](https://user-images.githubusercontent.com/2863198/185976207-c143348b-69fe-45b8-95c4-e4d8d700b99e.png)

### Additional notes

The linker also correctly removes the assembly when the `UnusedClass` is commented out or when the `UnusedClass` does not extend `NSObject`.

### Environment
<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac Preview
Version 17.4 Preview (17.4 build 715)
Installation UUID: 67751e62-e762-44da-8eb3-677faa27413a

Runtime
.NET 6.0.5 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.4.0-1.22371.1+c07f2571612b471671c809b5b0db59b0c37aab57

NuGet
Version: 6.2.1.2

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/6.0.400/Sdks
SDK Version: 6.0.400
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.8
	6.0.0

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Version: 6.0.8

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin Designer
Version: 17.4.0.32
Hash: 439b92ed7b
Branch: remotes/origin/d17-4
Build date: 2022-08-04 16:29:17 UTC

Xamarin.Android
Not Installed

Microsoft Build of OpenJDK
Java SDK: Not Found

Eclipse Temurin JDK
Java SDK: Not Found

Android SDK Manager
Version: 17.4.0.24
Hash: b3b6672
Branch: remotes/origin/HEAD~1
Build date: 2022-08-04 16:29:21 UTC

Android Device Manager
Version: 0.0.0.1179
Hash: 0f220c0
Branch: main
Build date: 2022-08-04 16:29:21 UTC

Apple Developer Tools
Xcode 13.4.1 (20504)
Build 13F100

Xamarin.Mac
Version: 8.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:54-0400

Xamarin.iOS
Version: 15.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:55-0400

Build Information
Release ID: 1704000715
Git revision: 09071dadfc1b81e4f0e2c9505cd8a5ef0b41d312
Build date: 2022-08-04 16:26:39+00
Build branch: release-17.4
Build lane: release-17.4

Operating System
Mac OS X 12.5.1
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Wed Aug 10 14:28:35 PDT 2022
    root:xnu-8020.141.5~2/RELEASE_ARM64_T8101 arm64


```

</details>

### Example Project (If Possible)

[test.zip](https://github.com/xamarin/xamarin-macios/files/9396156/test.zip)

**Comment by rolfbjarne** [comment] 2022-08-23 16:27
This is expected behavior: we tell the linker to not remove any `NSObject` subclasses, because they might be used in a storyboard without any other reference from managed code (and if the linker removed such classes, the app wouldn't work correctly).

Admittedly it might be possible to scan storyboards to figure out which classes they need, and tell the linker to keep those, but this would likely be a rather big task to implement, and probably won't happen any time soon (also there might be other reasons to keep `NSObject` subclasses that I don't remember right now).

**Comment by rolfbjarne** [comment] 2022-08-23 16:27
Keeping open in case we decide to look into detecting any NSObject-subclass-usage from storyboards.

**Comment by rdavisau** [comment] 2023-02-18 23:41
Could it be possible to opt-out of the `NSObject`-subclass-ignoring behavior with some build parameters? I have an app that doesn't use storyboards (besides `LaunchScreen.storyboard`) and would be willing to see if anything else blows up.

**Comment by rolfbjarne** [comment] 2023-02-20 12:28
> Could it be possible to opt-out of the `NSObject`-subclass-ignoring behavior with some build parameters? I have an app that doesn't use storyboards (besides `LaunchScreen.storyboard`) and would be willing to see if anything else blows up.

There's no official way to do it, but there might be a _really_ hacky way to do it: rename your assembly to `Xamarin.Forms.Platform.iOS`: 

https://github.com/xamarin/xamarin-macios/blob/b462bfde99abdb49f64d962045d7c3b3ce9ec809/tools/linker/MarkNSObjects.cs#L146-L151

and we should skip preserving `NSObject` subclasses in that assembly.

Of course do this at your own risk (and it won't work if you're using Xamarin.Forms)... but I'm also curious about what you find out if you do it :)

**Comment by rdavisau** [comment] 2023-02-22 22:31
I enthusiastically tried this and got a build with a teeny tiny difference in my "Xamarin.Forms.Platform.iOS" assembly (and it worked fine). From that I remembered that what I'd really want is to have this behaviour applied to one of my dependencies (ReactiveUI, which has many 'Reactive' subclasses of UIKit pieces, many of which I don't use), not the core project.  Renaming that one will be a bit more involved I think :')

**Comment by rolfbjarne** [comment] 2023-02-23 13:40
> I enthusiastically tried this and got a build with a teeny tiny difference in my "Xamarin.Forms.Platform.iOS" assembly (and it worked fine). From that I remembered that what I'd really want is to have this behaviour applied to one of my dependencies (ReactiveUI, which has many 'Reactive' subclasses of UIKit pieces, many of which I don't use), not the core project. Renaming that one will be a bit more involved I think :')

It shouldn't be too hard to make this an opt-out behavior (at your own risk), but it might take some time until it reaches a stable release. Are you building a .NET app or a legacy Xamarin.iOS app?

**Comment by rolfbjarne** [comment] 2023-04-13 14:37
This has been implemented now (as an opt-in), and will be included in .NET 8.

It can be turned on by passing `--skip-marking-nsobjects-in-user-assemblies=true` to mtouch/mmp:

```xml
<PropertyGroup>
    <MtouchExtraArgs>--skip-marking-nsobjects-in-user-assemblies=true</MtouchExtraArgs>
</PropertyGroup>
```

**Closed** 2023-04-13 14:38 UTC
Labels: feature
