### ISSUE TITLE
NSUrlSession cannot be created in the background unless the application is signed.

### ISSUE THREAD

**Issue by velocitysystems** [xamarin/xamarin-macios#7101] opened 2019-09-25 15:42 UTC
### Steps to Reproduce

1. Implement a `NSUrlSessionDownloadDelegate` to handle downloading.
2. Use the `CreateDownloadTask` method on the `NSUrlSession` to create a download task from an `NSMutableUrlRequest`.
3. Dispatch the download.

Refer to attached sample project for a reproduction.

### Expected Behavior
The download should complete successfully.
Note: The code works successfully when compiled for iOS 12 using Xcode 10.x.

### Actual Behavior
```
Task <16D3EEF3-B557-434E-AE1C-73B76252023D>.<1> finished with error [-1] Error Domain=NSURLErrorDomain Code=-1 "unknown error"
UserInfo={NSErrorFailingURLStringKey=https://github.com/xamarin/xamarin-macios/raw/master/banner.png, 
NSErrorFailingURLKey=https://github.com/xamarin/xamarin-macios/raw/master/banner.png, 
_NSURLErrorRelatedURLSessionTaskErrorKey=(
    "BackgroundDownloadTask <16D3EEF3-B557-434E-AE1C-73B76252023D>.<1>"
), 
_NSURLErrorFailingURLSessionTaskErrorKey=BackgroundDownloadTask <16D3EEF3-B557-434E-AE1C-73B76252023D>.<1>, 
NSLocalizedDescription=unknown error}
```

### Environment
```
Microsoft Visual Studio Enterprise 2019
Version 16.3.0
VisualStudio.16.Release/16.3.0+29318.209
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA728
Microsoft Visual C++ 2019

Application Insights Tools for Visual Studio Package   9.1.00913.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.3.282.33872
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.3.282.33872
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.3.282.33872
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.3.282.33872
Azure Functions and Web Jobs Tools

C# Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20816.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.83+gbc8a4b23ec
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.3.7 (9d260c5)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61908.27190
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10821.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19455.1+0422ff293bb2cc722fe5021b85ef50378a9af823
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.3.0.274 (d16-3@06531f8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.3.0.230 (remotes/origin/d16-3-xcode11@bbe518670)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.565 (27e9746)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.0.0.43 (d16-3/8af1ca8)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-06@7af64d1ebe9
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333


Xamarin.iOS and Xamarin.Mac SDK   13.2.0.42 (5e8a208)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Build Logs
N/A

### Example Project (If Possible)
[NSUrlSessionTest.zip](https://github.com/xamarin/xamarin-macios/files/3657886/NSUrlSessionTest.zip)
- Run in iOS 13 simulator
- Tap "Download" to reproduce the failure.

**Comment by velocitysystems** [comment] 2019-09-26 13:23
Hi @rolfbjarne @spouliot, I see you were previously involved in NSUrlSession-related issues. We are currently trying to get to the bottom of this issue. Please note, the repro project builds and runs fine when compiled with the previous SDK/tooling/Xcode for iOS 12.

We would certainly appreciate any assistance with this as this is a breaking issue on iOS 13. Thanks!

**Comment by SSELLIOTTHOME** [comment] 2019-09-30 10:57
I can confirm this problem also occurs when HttpClient is configured to use NSURLSession. Bit of problem means we cannot upgrade to the latest XCode.

**Comment by chamons** [comment] 2019-09-30 15:11
@mandel-macaque has been looking into this already.

**Comment by mandel-macaque** [comment] 2019-10-01 17:07
@velocitysystems @SSELLIOTTHOME I have been closely looking at the issue and here is some information that will help:

1. The error posted in the issue is not the important one. The unknown error is received by the delegate when the tasks is trying to be resumed. 
2. A much more interesting error occurs before the task is executed. 'An error occurred on the xpc connection to setup the background session: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.nsurlsessiond was invalidated from this process."'
3. Nothing has been changed in Xamarin regarding the code. And there is no reason for it to be failing.

After some digging, I can explain that error 4099 means that th XPC communication with the download service daemon was rejected. The issue can be easily solved if you sign the application. I have confirmed this in two different ways:

1. Tested the application on a device iOS 13 (XR running iOS 13 17A5534f). The application is signed and we can communicate with the daemon. (this works both with the HttpClient reported by @SSELLIOTTHOME and with the code provided by @velocitysystems).
2. Modified the build so that the application that is deployed to the simulator is signed. 

In order to ensure that the application is signed and that is able to communicate with the daemon you can run following command:
```bash
codesign -d --entitlements - /Users/mandel/Downloads/NSUrlSessionTest/NSUrlSessionTest/bin/iPhoneSimulator/Debug/device-builds/iphone12.1-13.1/NSUrlSessionTest.app
```
If the application is not correctly signed, the daemon will not accept the connections. If that was the case, you will get a message from the above command similar to the following one:
```
codesign -d --entitlements - /Users/mandel/Downloads/NSUrlSessionTest/NSUrlSessionTest/bin/iPhoneSimulator/Debug/device-builds/iphone12.1-13.1/NSUrlSessionTest.app
/Users/mandel/Downloads/NSUrlSessionTest/NSUrlSessionTest/bin/iPhoneSimulator/Debug/device-builds/iphone12.1-13.1/NSUrlSessionTest.app: code object is not signed at all
```

@chamons We probably want to talked with the VSMac developers to get the signing of the apps that are deployed to the simulator to be the default behavior. 

@velocitysystems @SSELLIOTTHOME Would appreciate if you can confirm that signing the app does solve the issue.

**Comment by prmallic** [comment] 2019-10-01 17:40
Tried the approach suggested by @mandel-macaque . Signing in works on device and simulator

**Comment by SSELLIOTTHOME** [comment] 2019-10-01 17:42
@mandel-macaque  Thank you for the update, and I would like to confirm this solution but where would we run codesign, in Visual Studio on Windows, or on the mac, and per specific simulator?  - I need to pass this on to our iOS dev guy.

**Comment by mandel-macaque** [comment] 2019-10-01 17:47
@SSELLIOTTHOME it does not have to be for a specific simulator, you just have to ensure that code signing is performed by VS Mac or VS. Doing it on VS Mac is as simple as going to the signing options and Adding the Entitlements.plist when building for iPhoneSimulator (I cannot check atm on a Windows machine, but I suspect is very similar, will ask a colleague to take a look):

<img width="979" alt="Screen Shot 2019-10-01 at 1 45 20 PM" src="https://user-images.githubusercontent.com/2190086/65986385-c039ad00-e451-11e9-8358-ade7ea2acd41.png">

**Comment by dalexsoto** [comment] 2019-10-01 17:47
I think you can follow this guide to enable entitlements inside VS for Windows https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/provisioning/entitlements?tabs=windows

**Comment by chamons** [comment] 2019-10-01 17:52
@davidortinau - We should consider discussing with the IDE teams changing the default behavior for simulators, since apparently signing is now a thing.

**Comment by yavor87** [comment] 2019-10-01 19:08
@mandel-macaque , an error is created even when the`NSUrlSession` is being constructed from configuration by `NSUrlSession.FromConfiguration()`.
Error message:
> An error occurred on the xpc connection to setup the background session: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.nsurlsessiond was invalidated from this process." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.nsurlsessiond was invalidated from this process.}

Doing the same thing in ObjC in XCode 11 does not produce this error.

**Comment by velocitysystems** [comment] 2019-10-01 19:39
Thanks @mandel-macaque.
So just to confirm, nothing has changed in Xamarin.iOS but rather iOS 13/Xcode 11.x requires code-signing entitlements in the simulator for `NSUrlSession` to work correctly?

**Comment by mandel-macaque** [comment] 2019-10-01 21:59
@yavor87 yes, but that is because xcode11 does **always** the signing even on simulator which we do not do. So the signing has to be done in all cases. We tested this with swift as confirmed the hypothesis. 

@velocitysystems correct, nothing has changed in Xamarin.iOS at all, this is a change on Apples side regarding the restrictions to use the daemons on the simulators, your code should not have to change, but just signing has to be added.

**Comment by rolfbjarne** [comment] 2019-10-02 05:54
> @chamons @mandel-macaque @davidortinau - We should consider discussing with the IDE teams changing the default behavior for simulator to always sign.

I think we tried that in the past, and some things broke, but I don't remember exactly what happened. @jstedfast do you remember?

If we decide to always sign, it won't need input from the IDE teams, we do that in our own MSBuild tasks.

**Comment by chamons** [comment] 2019-10-02 12:33
Maybe we could detect "known bad" APIs and warn in mtouch? I know it's wack-a-mole but might be useful?

**Comment by velocitysystems** [comment] 2019-10-02 13:28
Thanks @mandel-macaque.
I think if XCode 11+ defaults to signing, then the IDEs should follow suit for consistency.
Any implications of this need to be discussed of course, but this maintains parity for developers which of course is the overall goal of Xamarin!

**Comment by rolfbjarne** [comment] 2019-10-02 14:04
> I think if XCode 11+ defaults to signing, then the IDEs should follow suit for consistency.

I agree, but iirc back when we tried, Xcode (not sure which version) didn't _always_ sign, and it took us a while to figure out the exact conditions.

Things might of course have changed since then, we'd have to investigate it again.

**Comment by mandel-macaque** [comment] 2019-10-02 18:46
@rolfbjarne I asked @dalexsoto and he mentioned not paid apple developer accounts was one of the reasons, but he could explain better

**Comment by mandel-macaque** [comment] 2019-10-04 14:57
@velocitysystems can we have confirmation of the fact that the issue as resolved via signing the app?

**Comment by mandel-macaque** [comment] 2019-10-14 18:45
by reading the issue added by @nCastle1 the workaround does work.

**Comment by velocitysystems** [comment] 2019-11-11 11:52
@mandel-macaque Thanks, all works fine now when signing the app.

**Comment by 1Cor125** [comment] 2021-03-21 13:26
I know this is closed now but the team had discussed trying to match Xcode's behavior of signing apps automatically when using a sim. This sort of thing creates friction for devs. Now if I build a little sample app in one of my package repos I need to sign the app to make sure everything works well in the sim. Is there a ticket somewhere to track this request? That way we don't have devs continuing to report this as a bug only to be told to sign their app to run it in the sim.

**Comment by velocitysystems** [comment] 2021-03-21 17:57
@1Cor125 Thanks for raising this, I am reopening this issue as it still requires attention.

**Comment by richardgroves** [comment] 2021-07-07 16:19
Another 4 months on and I stumble across this page when randomly Googling for why my app isn't working in the simulator in release build. Then reading down the thread realise I've been here before and upvoted things.

Can we get some indication of when this might get fixed? It'll be the tickets 2nd birthday in a couple of months.

**Closed** 2024-05-29 15:22 UTC
Labels: bug, iOS, regression
