### ISSUE TITLE
[XI] UI freezes while invoking `ARKit.ARSCNView.Session`

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#3377] opened 2018-02-01 14:36 UTC
### Steps to Reproduce

1. Download a ([project](https://github.com/mykyta-bondarenko-gl/private-samples/tree/audio-in-arkit/ios11/ARKitAudio))
2. Open:
 - `ARKitAudio/ViewController.cs` file and look at the line 184;
 - `ARKitAudio/Extensions/ARSCNViewExtensions.cs` file and look at the lines 71-72;
3. Uncomment any of these lines (any of these ways show working with `Session` property).
4. Run the project

### Expected Behavior
UI should be smooth.

### Actual Behavior
You can observe UI freezes.

### Environment

- Visual Studio for Mac 7.4 Preview (build 884)  
https://gist.github.com/mykyta-bondarenko-gl/b57c438f57032bd55ad6ef31415b08ce

### Frequency of Reproduction

Happens every time

### Example Project

[Link to the project](https://github.com/mykyta-bondarenko-gl/private-samples/tree/audio-in-arkit/ios11/ARKitAudio)

**Comment by spouliot** [comment] 2018-02-01 19:54
This sounds a lot like https://bugzilla.xamarin.com/show_bug.cgi?id=60393
and documentation should have been updated for it

**Comment by dalexsoto** [comment] 2018-02-01 21:58
Yes this is a dupe of Bug https://bugzilla.xamarin.com/show_bug.cgi?id=60393, if I change the code to an using all works as expected, so you need to either dispose the `CurrentFrame` manually or place it inside a using.

```csharp
var results = new List<FeatureHitTestResult>();

// TODO: temporary changes to show `Session` property freeze
//var features = (ARPointCloud)null;

using (var frame = view.Session.CurrentFrame) {
	var features = frame?.RawFeaturePoints;
	if (features != null)
	{
		var ray = view.HitTestRayFromScreenPos(point);
		if (ray.HasValue)
		{
		}
		else
		{
			return results;
		}
//... more here
```

**Closed by dalexsoto** 2018-02-01 21:58 UTC
Labels: duplicate, iOS

**Comment by spouliot** [comment] 2018-02-01 22:30
Just double checked that it's in our documentation
https://developer.xamarin.com/api/member/ARKit.ARSessionDelegate.DidUpdateFrame/p/ARKit.ARSession/ARKit.ARFrame/

**Comment by mykyta-bondarenko-gl** [comment] 2018-02-02 12:58
Thank you! Sorry that before I didn't check the Bugzilla (only github).
