### ISSUE TITLE
ServicePointManager.ServerCertificateValidationCallback stopped working

### ISSUE THREAD

**Issue by haavamoa** [xamarin/xamarin-macios#8176] opened 2020-03-23 22:04 UTC
Hello, I upgraded to the latest Visual Studio and got the latest Xamarin.iOS version today. After the update I saw a couple of my httpclient requests failing with SLL exception : `CertificateUnknown`. 

This is a known issue when I am hitting my servers, as they are self-signed.

The workaround I've used is to do a `ServicePointManager.ServerCertificateValidationCallback = (sender, certificate, chain, errors) => true;`.

After debugging a little bit, I've found out that the callback does not get called after I updated Xamarin.iOS. I've tested with a previous released app that is not compiled with my machine with the same code, and it works.

### Steps to Reproduce

1. Create a new Xamarin.Forms project
2. Use `HttpClient` to hit the following endpoint: `https://wrong.host.badssl.com/`
3. Observe the error
4. Add ``ServicePointManager.ServerCertificateValidationCallback = (sender, certificate, chain, errors) => true;`` before doing the server call
5. Observe the same error

### Expected Behavior
No exception when hitting `https://wrong.host.badssl.com/`.

### Actual Behavior
SSL Exception: `CertificateUnknown` when hitting the endpoint.

### Environment

Microsoft Visual Studio Enterprise 2019
Version 16.5.0
VisualStudio.16.Release/16.5.0+29911.84
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA147
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.5.236.49856
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.5.236.49856
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.5.236.49856
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.5.236.49856
Azure Functions and Web Jobs Tools

C# Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub.VisualStudio   2.10.8.8132
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JetBrains ReSharper Ultimate 2019.3.1   Build 193.0.20191219.91525
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2020 JetBrains, Inc.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30207.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.5.512 (7a72495)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ReviewsToolWindow Extension   1.0
ReviewsToolWindow Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62003.05170
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.20225.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.8.0.0 for F# 4.7   16.5.0-beta.20104.8+7c4de19faf36647c1ef700e655a52350840c6f03
Microsoft Visual F# Tools 10.8.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.5.000.521 (d16-5@b3ea41e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.5.0.470 (remotes/origin/d16-5@681de3fd6)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.5.49 (0904f41)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.2.0.100 (d16-5/988c811)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c0c5c78
    Java.Interop: xamarin/java.interop/d16-5@fc18c54
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b

Xamarin.iOS and Xamarin.Mac SDK   13.14.1.39 (30e8706)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by haavamoa** [comment] 2020-03-23 22:09
Note: I'm having issues proving that this is because of `Xamarin.iOS`, because I have to downgrade (uninstall my visual studio 2019). This means that I will lose a lot of setup and I don't want to go through that. I want to create this issue to see if there's anyone out there that might know what this problem might be. The only thing I know is that I am on the latest Visual Studio with a new Xamarin.iOS version, and that it works for my colleagues that are on the previous version of Visual Studio 2019.

**Comment by haavamoa** [comment] 2020-03-23 22:16
I am not that known in this project, but I see some changes to the callback here:
https://github.com/xamarin/xamarin-macios/commit/ccc9bbb448983c4717a14ac8d644ae103a649587#diff-7f619be41b43eaaed811ff8b330f769c

**Comment by haavamoa** [comment] 2020-03-24 07:31
I've made a reproducible Xamarin.Forms project : https://github.com/haavamoa/GithubIssues/tree/master/src/CertificateValidationError.Forms/CertificateValidationError.Forms

This is the code that runs when you click the "Hit endpoint" button in the app:
https://github.com/haavamoa/GithubIssues/blob/b98087f5cb3e49579835ccc72fa139533c2c451e/src/CertificateValidationError.Forms/CertificateValidationError.Forms/CertificateValidationError.Forms/MainPage.xaml.cs#L28

**Comment by haavamoa** [comment] 2020-03-24 11:31
I found a workaround for the problem. If I do it the same way as Android it will work:
https://github.com/haavamoa/GithubIssues/blob/b98087f5cb3e49579835ccc72fa139533c2c451e/src/CertificateValidationError.Forms/CertificateValidationError.Forms/CertificateValidationError.Forms/MainPage.xaml.cs#L38

**Comment by chamons** [comment] 2020-03-24 20:06
@mandel-macaque - Is this https://github.com/mono/mono/issues/17125 ?

**Comment by haavamoa** [comment] 2020-03-25 07:04
I like this solution, but I got very confused when it was working prior to updating visual studio.

**Comment by chamons** [comment] 2020-03-26 14:34
Updating Visual Studio updates the various included SDKs, such as Xamarin.iOS and Xamarin.Mac. Some of those updates include runtime changes, such as https://github.com/mono/mono/issues/17125 that impact you.

We try to minimize such changes in updates where possible.

I believe this is a duplicate of https://github.com/mono/mono/issues/17125 and given ^ I believe the issue can be closed as you have a work around until that fix is released.

**Closed by chamons** 2020-03-26 14:34 UTC

**Comment by haavamoa** [comment] 2020-03-27 10:35
This is correct, but I would also say that it was not clear to me that this has changed and that I can not expect it to work anymore. Is there any chance you could add a [Obsolete] flag to it to make sure people get notified about the change of the behavior?

**Comment by chamons** [comment] 2020-03-27 15:43
That is a reasonable request. I've filed https://github.com/mono/mono/issues/19346 to suggest it to that team.
