### ISSUE TITLE
NSAlertView on Mojave appears blank

### ISSUE THREAD

**Issue by lilleydnSub** [xamarin/xamarin-macios#4848] opened 2018-09-20 09:35 UTC
### Steps to Reproduce

1. Open Build and Run Sample Project (Code is in the MainWindowController)
2. Click on Button
3. NSAlert Should Appear

The code from MainWindowController
...
 ```
 public override void AwakeFromNib()
        {
            base.AwakeFromNib();

            NSButton aButton = new NSButton(new CoreGraphics.CGRect(20, 20, 100, 100));
            aButton.Activated += AButton_Activated;
            aButton.Title = "Press Me";
            this.Window.ContentView.AddSubview(aButton);
        }

        void AButton_Activated(object sender, EventArgs e)
        {
            NSAlert alert = new NSAlert();
            alert.AddButton("OK");
            alert.MessageText = "Message";
            alert.InformativeText = "Informative";
            alert.RunModal();
        }

```
..

### Expected Behaviour
NSAlert Should Appear showing Text and Button

<img width="761" alt="screenshot 2018-09-20 at 10 53 31" src="https://user-images.githubusercontent.com/12064448/45809693-1fa2a000-bcc9-11e8-8749-2726c9514224.png">

### Actual Behavior
NSAlert Frame only appears but the content is blank. Please note this is inconsistent as if you close the alert with escape or enter and press the button again it will show

<img width="1158" alt="screenshot 2018-09-20 at 10 53 10" src="https://user-images.githubusercontent.com/12064448/45809686-1addec00-bcc9-11e8-91f0-31f846819a39.png">

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.6.6 (build 17)
Installation UUID: 3f2abab7-67ae-4505-b2bf-7d93f8fd8513
Runtime:
	Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000301

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Not Installed

=== Apple Developer Tools ===

Xcode 10.0 (14320.24)
Build 10A254a

=== Xamarin.Mac ===

Version: 4.6.0.14 (Visual Studio Community)
Hash: 1a6e2786
Branch: 
Build date: 2018-08-28 00:12:06-0400

=== Xamarin.iOS ===

Version: 12.0.0.15 (Visual Studio Community)
Hash: 84552a46
Branch: xcode10
Build date: 2018-09-17 21:54:33-0400

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706060017
Git revision: 822323b5f6295b271d4c9bfaca4129f90ec41f38
Build date: 2018-09-18 20:19:40+00
Build branch: release-7.6-xcode10
Xamarin extensions: a83eb4b7ad9174ac2e705f2c4257ecd15688ba97

=== Operating System ===

Mac OS X 10.14.0
Darwin 18.0.0 Darwin Kernel Version 18.0.0
    Wed Aug 22 20:13:40 PDT 2018
    root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Internet of Things (IoT) development (Preview) 7.5.3

```

### Example Project (If Possible)

[TestNSAlert.zip](https://github.com/xamarin/xamarin-macios/files/2400663/TestNSAlert.zip)

**Comment by lilleydnSub** [comment] 2018-09-20 10:13
Also tested against Xcode 10 Preview Channel Which has the version Xamarin.Mac 4.99.3.741 which also showed the NSAlertView with empty frame

**Comment by rolfbjarne** [comment] 2018-09-20 10:35
This might be related to #4509.

**Comment by lilleydnSub** [comment] 2018-09-20 13:01
Created Swift Clone to ensure it was not Apple Problem. The swift version appears to work fine.

[AlertViewTest.zip](https://github.com/xamarin/xamarin-macios/files/2401362/AlertViewTest.zip)

**Comment by Rogister** [comment] 2018-09-21 09:02
I have this problem with my Xamarin.mac app.

**Comment by Rogister** [comment] 2018-09-21 09:03
Only on mojave, never had it on macos sierra or high sierra.

**Comment by Rogister** [comment] 2018-09-21 09:06
It's the same with Xcode 10 Preview, the problem is there !

**Comment by Rogister** [comment] 2018-09-21 13:48
Important note :

I have the same phenome with some view with PresentViewController. they appear empty then sometimes, they are normal, ...

**Comment by lilleydnSub** [comment] 2018-09-21 14:08
I have noticed this with anything modal, Presenting Windows Modally, Presenting Windows as Sheets Modally. My hunch is the more complex the Modal the more likely it is to be displayed. As the worst offender is the sample test I have produced.

**Comment by Rogister** [comment] 2018-09-21 14:10
Glad you saw the problem because I do not understand anything.

I have really weird problems since Mojave

**Comment by Rogister** [comment] 2018-09-21 14:26
I test the problems that I encounter and do, I realize that the problems come from the modal box problem.

Example:

I display an image and then hide this image and then I display an alertview.

If I do that, the image is not hiding. She remains visible while I told her before being hidden.

If I do not put the alertview, I do not have the problem. The image is well hidden.

**Comment by lilleydnSub** [comment] 2018-09-21 14:27
Ps also tried Window.ContentView.Superview.WantsLayer = true; with no such luck either

**Comment by Rogister** [comment] 2018-09-21 14:30
I tried this and my viewcontroller already has the layer checked in the Xib file.

I also put the line of code to try but it does not change anything.

Looks like there is something blocking after the display of the alertview and nothing else happens properly

**Comment by Rogister** [comment] 2018-09-21 18:49
Does anyone take care of this problem ?

**Comment by lemonmojo** [comment] 2018-09-24 09:57
Happy Mojave Day!

@lilleydnSub I found some info and posted it in https://github.com/xamarin/xamarin-macios/issues/4509#issuecomment-423727747.

**Comment by Rogister** [comment] 2018-09-24 10:03
Hi, 

I want to try this solution but when I put in my application, it highlights me DllImport, what should I do:

[DllImport ("/ System / Library / Frameworks / Cocoa.framework / Cocoa", EntryPoint = "NSApplicationLoad")]
         private static extern bool NSApplicationLoad ();

Alain

**Comment by lemonmojo** [comment] 2018-09-24 10:06
@Rogister You'll need to import `System.Runtime.InteropServices`. Add `using System.Runtime.InteropServices;` to your Program.cs file.

**Comment by Rogister** [comment] 2018-09-24 10:13
OK, thanks.

I just tried and it solves all the problems I had. (AlertView, Modal dialog and tableview)

Is there an explanation ?

Alain

**Comment by lemonmojo** [comment] 2018-09-24 10:32
@Rogister Well, from the info I was able to find I assume that macOS Mojave thinks that mono apps are not properly configured Cocoa apps and NSApplicationLoad fixes that. I don't know exactly what triggers this but as mentioned in the other thread, just calling mono_jit_init introduces the problem so the source of the issue must be somewhere in that method.

**Comment by Rogister** [comment] 2018-09-24 10:40
Chris would have to look at the problem because it's not very normal that we have to specify that.

Are you going to tell me, as long as it works ?

**Comment by Rogister** [comment] 2018-09-24 11:29
198/5000
I notice a last problem on Mojave with the toolbar.

I have buttons (image) that is no longer displayed correctly and I have the impression that the function SetTouchBar (null) no longer works.

**Comment by Rogister** [comment] 2018-09-24 11:42
The SetTouchBar (null) works fine!

But there is a problem. I display several buttons and now there is only
the first 5 that appears by putting me a big space between some buttons

**Comment by chamons** [comment] 2018-09-24 21:54
The cousin bug to this (#4509) appears fixed _for me_ on stable 10.14, please update, retest, and report back.

**Comment by Rogister** [comment] 2018-09-25 07:32
I try today without putting the lines of code that solves the problem and I still have the problem with MacOS Mojave Final

The problem is not solved without putting

  [DllImport ("/ System / Library / Frameworks / Cocoa.framework / Cocoa", EntryPoint = "NSApplicationLoad")]
         private static extern bool NSApplicationLoad ();

         static void Main (string [] args)
{
             NSApplicationLoad ();

  NSApplication.Init ();
NSApplication.Main (args);

         }

**Comment by DanWBR** [comment] 2018-09-28 18:52
I'm having this problem too. Tried the proposed solution (calling NSApplicationLoad) but it didn't work either. Using Xamarin.Mac on https://github.com/DanWBR/dwsim5 through https://github.com/picoe/Eto

**Comment by chamons** [comment] 2018-09-28 19:08
I believe this has the same root cause as:

radar://44763485 & mono/mono#10802

The mono team is investigating it now. The following things make the issue go away for _me_ at least:

- Using xcode9.4 instead of 10
- Using a project with storyboards instead of xibs
- Some cases are fixed by forcing the parent of your contentview to WantsLayer = true

And as a side note, NSApplicationLoad was a work around suggested by another user, not a solution at all.

**Comment by DanWBR** [comment] 2018-09-28 19:13
I'm having a new issue too, sometimes the controls inside a view vanish all of a sudden. I didn't have this issue before updating to Mojave (specifically, it was bug-free with High Sierra + XCode 10). Maybe it is related to the bug being discussed.

**Comment by chamons** [comment] 2018-09-28 19:16
There are a number of drawing corruptions various people are seeing after the mprotect call in mono startup, from the title bar disappearing, to strange resize behavior, to modal dialogs and controls not drawing.

I believe they all have the same root cause, and you can try the temporary work arounds I suggested to see if they hide it for now. A fix is in research.

**Comment by lemonmojo** [comment] 2018-09-28 19:56
@chamons Just wanted to note that in my testing just using a storyboard for the main menu and app delegate isn't enough to work around the issue. You'll also need to have your main window in the storyboard as well as the entry point of the app set to that window.

**Comment by chamons** [comment] 2018-10-05 15:31
Ok, the gears may feel like they are slowly turning on getting this fix out on an official channel, but considering the fact that the fix only landed _4 days ago_ things are moving along faster than it appears.

This is a "from the developer's machine" build for people to try:

https://xamarin.azureedge.net/uploads/y50ozav12uz/xamarin.mac-5.2.0.2-10.14.fix.pkg

I'll post an official build machine package later today, but I wanted to get something out as soon as I could.

Please test it (or the later package) and report back

**Comment by DanWBR** [comment] 2018-10-05 18:05
@chamons tested it here and all issues seem to be gone. Thank you all very much!

**Comment by dbdkmezz** [comment] 2018-10-08 08:30
This fixes the issue for me too. I work on two Xamarin.Mac applications, one of which was fixed by `NSApplicationLoad` and one wasn't. Messing around with `WantsLayer` didn't help that one either. But with this new build of Xamarin.Mac all appears well. Thanks @chamons

**Comment by Rogister** [comment] 2018-10-08 10:55
@chamons 

I installed the fix and everything seems to work properly. Thank you very much

I note that sometimes I still have empty boxes. It's almost impossible to reproduce. Sometimes (extremely rarely, the box is empty and if I do it again soon after, no problem).

**Comment by chamons** [comment] 2018-10-12 14:01
I'm happy to say that the build I posted a week ago appears to work for everyone so far, so I'm going to close this issue as fixed (in the next major version). It will come out in a future d15-9 release, but until then you can use the posted build from that branch.

If you run into additional issues _not_ fixed by this, please open a new issue.

**Closed by chamons** 2018-10-12 14:01 UTC
Labels: bug, macOS

**Comment by projectgoav** [comment] 2018-10-12 14:07
@chamons - When is the release likely to be?

**Comment by chamons** [comment] 2018-10-12 14:14
Unfortunately, I don't have any official dates I can point to.

This document describes the Visual Studio release cycle - https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2017-release-rhythm

We also have older d15-9 builds in the Alpha and Beta channel currently.

**Comment by lilleydnSub** [comment] 2018-10-23 09:15
Am I correct in believing that it still not fixed in Alpha and Beta channels ? 
Any closer to being released ?

**Comment by chamons** [comment] 2018-10-23 12:59
That is correct 😦  It is queued up for release. 

The latest d15-9 builds, which are publicly available, have the fix.

I can not comment on when it will go out currently, but yes closer...

**Comment by jeremywho** [comment] 2018-10-23 16:37
@chamons:

> The latest d15-9 builds, which are publicly available, have the fix.

Does this mean the 15-9 builds now available via ALPHA/BETA channels or are these found elsewhere?

**Comment by chamons** [comment] 2018-10-23 16:52
No, there is a separation. Let me explain:

- The release branch for our d15-9 release lives here: https://github.com/xamarin/xamarin-macios/commits/d15-9
- If you click the check marks \ red X's you can get package links to the bits produced by those lanes.
- At some point, QA validates those sufficiently and we push those bits out to a Alpha\Beta\Stable distribution channel

The fix is in d15-9, and the bits are available (The package I linked earlier was from here). Assuming no additional changes are needed, we'll be pushing those bits out at some point in the future when QA and release processing is complete. Until then, you can obtain them "early" as I noted.
