### ISSUE TITLE
MAUI apps fail during NuGet Restore

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#17490] opened 2023-02-09 11:42 UTC
### Steps to Reproduce

1. Create MAUI app from template in Visual Studio for macOS Preview with 7.0.200-preview.22628.1 SDK 

### Expected Behavior

The template works and builds.

### Actual Behavior

```
Getting restore information for project /Users/filipnavara/Projects/MauiApp/MauiApp/MauiApp.csproj
/usr/local/share/dotnet/sdk/7.0.200-preview.22628.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1226,3) : error MSB4019: The imported project "/usr/local/share/dotnet/sdk/7.0.200-preview.22628.1/Sdks/Microsoft.NET.Sdk/16.2.1024/targets/Xamarin.Shared.Sdk.MultiTarget.targets" was not found. Confirm that the expression in the Import declaration ";../16.2.1024/targets/Xamarin.Shared.Sdk.MultiTarget.targets;/usr/local/share/dotnet/packs/Microsoft.Maui.Sdk/6.0.552/Sdk/Microsoft.Maui.Sdk.After.targets;/usr/local/share/dotnet/packs/Microsoft.Maui.Sdk/6.0.552/Sdk/Microsoft.Maui.Core.Sdk.After.targets;/usr/local/share/dotnet/packs/Microsoft.Maui.Sdk/6.0.552/Sdk/Microsoft.Maui.Controls.Sdk.After.targets;/usr/local/share/dotnet/packs/Microsoft.Maui.Resizetizer.Sdk/7.0.59/Sdk/../targets/Microsoft.Maui.Resizetizer.targets" is correct, and that the file exists on disk.
Unable to create package spec for project. '/Users/filipnavara/Projects/MauiApp/MauiApp/MauiApp.csproj'
```

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac Preview
Version 17.5 Preview (17.5 build 1766)
Installation UUID: f793fc35-db4a-4668-98a6-01e4db7c0ca9

Runtime
.NET 7.0.1 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 12.3.2372; git-rev-head:754abbf6a3563f6267e5717ae832b4ac25b1f2fb; git-branch:release/7.0.1xx-xcode13.3

Roslyn (Language Service)
4.5.0-3.23056.2+97881342e427ff5cdcba8f12b12ff8e6f3564431

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.200-preview.22628.1/Sdks
SDK Versions:
	7.0.200-preview.22628.1
	7.0.101
	7.0.100
	6.0.405
	6.0.404
	6.0.403
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	6.0.405
	6.0.404
	6.0.106
	5.0.408
	3.1.426
	3.1.420

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.1
	7.0.0
	6.0.13
	6.0.12
	6.0.11

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.13
	6.0.12
	6.0.6
	5.0.17
	3.1.32
	3.1.26

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.2.0.0 (Visual Studio Community)
Commit: xamarin-android/d17-5/797e2e1
Android SDK: /Users/filipnavara/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.0  (API level 26)
		12.0 (API level 31)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.2
SDK Build Tools Version: 32.0.0 rc1

Build Information: 
Mono: 6dd9def
Java.Interop: xamarin/java.interop/main@149d70fe
SQLite: xamarin/sqlite/3.40.0@fdc1e34
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@9f02d77

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.5.0.33
Hash: f0c0c52
Branch: remotes/origin/d17-5~1
Build date: 1444-07-11 19:20:19 UTC

Android Device Manager
Version: 0.0.0.1245
Hash: 7f8a990
Branch: 7f8a990
Build date: 1444-07-11 19:20:19 UTC

Xamarin Designer
Version: 17.5.3.47
Hash: e8b5d371c3
Branch: remotes/origin/d17-5
Build date: 1444-07-11 19:20:14 UTC

Apple Developer Tools
Xcode: 14.2 21534
Build: 14C18

Xamarin.Mac
Version: 9.1.0.2 Visual Studio Community
Hash: 956a059ba
Branch: xcode14.2
Build date: 2022-12-15 06:15:43-0500

Xamarin.iOS
Version: 16.2.0.2 Visual Studio Community
Hash: 956a059ba
Branch: xcode14.2
Build date: 2022-12-15 06:15:44-0500

Build Information
Release ID: 1705001766
Git revision: 749808e99f0d0bf8a8eb45fe406840107ffb46b4
Build date: 2023-02-02 19:18:20+00
Build branch: release-17.5
Build lane: release-17.5

Operating System
Mac OS X 13.2.0
Darwin 22.3.0 Darwin Kernel Version 22.3.0
    Sun Dec  4 18:16:43 PST 2022
    root:xnu-8792.80.21.0.2~9/RELEASE_ARM64_T8103 arm64

Enabled user installed extensions
Project System Tools 0.12
```

</details>

### Notes

Possibly related to https://github.com/xamarin/xamarin-macios/issues/16400

**Comment by filipnavara** [comment] 2023-02-09 11:51
Same error happens with 7.0.101 SDK when forced through global.json. It works with 6.0.405 SDK (and correctly complains if some workloads are missing).

**Comment by rolfbjarne** [comment] 2023-02-09 14:17
This looks like a duplicate of #17400.

Does it work correctly (or fail with an error about missing workloads) if you build from the command line?

Also what's the TargetFrameworks in your csproj?

**Comment by filipnavara** [comment] 2023-02-09 15:02
> Does it work correctly (or fail with an error about missing workloads) if you build from the command line?

Fails the same way:
```
dotnet build MauiApp
MSBuild version 17.5.0-preview-22620-02+a6f6699d1 for .NET
  Determining projects to restore...
  Restored /Users/filipnavara/Projects/MauiApp/MauiApp/MauiApp.csproj (in 369 ms).
/usr/local/share/dotnet/sdk/7.0.200-preview.22628.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(287,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/Users/filipnavara/Projects/MauiApp/MauiApp/MauiApp.csproj::TargetFramework=net6.0-android]
/usr/local/share/dotnet/sdk/7.0.200-preview.22628.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1226,3): error MSB4019: The imported project "/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.1024/targets/Xamarin.Shared.Sdk.MultiTarget.targets" was not found. Confirm that the expression in the Import declaration ";/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.19/targets/Microsoft.iOS.Sdk.targets;/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.19/../16.2.1024/targets/Xamarin.Shared.Sdk.MultiTarget.targets;/usr/local/share/dotnet/packs/Microsoft.Maui.Sdk/6.0.552/Sdk/Microsoft.Maui.Sdk.After.targets;/usr/local/share/dotnet/packs/Microsoft.Maui.Sdk/6.0.552/Sdk/Microsoft.Maui.Core.Sdk.After.targets;/usr/local/share/dotnet/packs/Microsoft.Maui.Sdk/6.0.552/Sdk/Microsoft.Maui.Controls.Sdk.After.targets;/usr/local/share/dotnet/packs/Microsoft.Maui.Resizetizer.Sdk/7.0.59/Sdk/../targets/Microsoft.Maui.Resizetizer.targets" is correct, and that the file exists on disk. [/Users/filipnavara/Projects/MauiApp/MauiApp/MauiApp.csproj]
/usr/local/share/dotnet/sdk/7.0.200-preview.22628.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1226,3): error MSB4019: The imported project "/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/16.2.1024/targets/Xamarin.Shared.Sdk.MultiTarget.targets" was not found. Confirm that the expression in the Import declaration ";/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/16.2.19/targets/Microsoft.MacCatalyst.Sdk.targets;/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/16.2.19/../16.2.1024/targets/Xamarin.Shared.Sdk.MultiTarget.targets;/usr/local/share/dotnet/packs/Microsoft.Maui.Sdk/6.0.552/Sdk/Microsoft.Maui.Sdk.After.targets;/usr/local/share/dotnet/packs/Microsoft.Maui.Sdk/6.0.552/Sdk/Microsoft.Maui.Core.Sdk.After.targets;/usr/local/share/dotnet/packs/Microsoft.Maui.Sdk/6.0.552/Sdk/Microsoft.Maui.Controls.Sdk.After.targets;/usr/local/share/dotnet/packs/Microsoft.Maui.Resizetizer.Sdk/7.0.59/Sdk/../targets/Microsoft.Maui.Resizetizer.targets" is correct, and that the file exists on disk. [/Users/filipnavara/Projects/MauiApp/MauiApp/MauiApp.csproj]
```

> Also what's the TargetFrameworks in your csproj?

It's literally unmodified MAUI template:
```
		<TargetFrameworks>net6.0-android;net6.0-ios;net6.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) and '$(MSBuildRuntimeType)' == 'Full'">$(TargetFrameworks);net6.0-windows10.0.19041</TargetFrameworks>
```

**Comment by filipnavara** [comment] 2023-02-09 15:09
Actually, the `dotnet build` errors are mildly more helpful. If I install the `ios` and `maccatalyst` workloads from command line it builds. Visual Studio complains quite randomly about the missing workloads but the installation from its UI doesn't resolve the errors and doesn't install the right workloads; neither does `dotnet workload restore`.

**Comment by filipnavara** [comment] 2023-02-09 16:03
It is indeed duplicate of #16400 so I will close it. The annoying thing is that it happens on relatively fresh VS4Mac install. The install had all the components installed, then updated to newer SDKs through the built-in update UI. Then it fails a build on a MAUI template with no changes whatsoever.

**Closed** 2023-02-09 16:03 UTC
