### ISSUE TITLE
[Bug] "codesign" exited with code 1 iOS

### ISSUE THREAD

**Issue by Agredo** [xamarin/xamarin-macios#6813] opened 2019-08-18 21:59 UTC
Sometimes during deploying, VS2019 stops with error: "codesign" exited with code 1

### Steps to Reproduce

1. Deploy iOS.

### Basic Information
This Happens with the newest VS2019 and XF4.1 (Both not beta)

For more Information: https://stackoverflow.com/questions/48575062/xamarin-ios-error-msb6006-codesign-exited-with-code-1

The fix is very annoying: 

> Thing is, I am having this error regularily. 
> I am working with a local developer certificate created on my Mac using a free Apple Id, but without a paid Apple Developer Membership. I am using a Windows based devloper workstation and program in Visual Studio 2019 with Xamarin.Forms 4.0. To get local deployment working again, I need to visit the general settings on my iPhone and remove my trusted account from the list of developer apps under device management which basically not only removes the account but also the app from the device.
> Then I need to remove all occurances of the corresponding certificate on my Mac within the Keychain Utility and even the mobileprovision file on my harddrive located somewhere beneath my user directory.
> Now I have to Start XCode on my Mac, open the project, I am working on and have it automatically "repair" the signing certificate which basically creates a new one and registers it in the Keychain. The moment I run the app from XCode, I need to always allow keychain access and on my iPhone I can see the account appear in the general settings again which I have to manually trust... again.
> THEN I can open the corresponding project in my Visual Studio on my Windows Developer Workstation, rebuild and deploy the app and get no errors.
> Without being able to say why, it could happen even the next time I try to build and deploy the app, that this error happens again... this is very (!) inconvenient and I didn't find any real solution for it yet...
> 
Jul 3 at 20:32 
Mephisztoe (Stackoverflow)

**Comment by rolfbjarne** [comment] 2019-08-21 11:36
Thank you for your feedback!

For us to investigate this further, could you please provide your full build logs and all your version information.

To get full build logs just set the log verbosity to diagnostic at the following menu location: Tools > Options > Projects and Solutions > Build and Run

You also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

The easiest way to get exact version information: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

We look forward to hearing from you!

**Comment by Agredo** [comment] 2019-09-20 23:07
Hi sorry for the late reply. Searching this error Shows so many results… https://forums.xamarin.com/discussion/161711/how-to-solve-codesign-exited-with-code-1-finally

[Log.txt](https://github.com/xamarin/xamarin-macios/files/3638038/Log.txt)

**Comment by rolfbjarne** [comment] 2019-09-23 05:42
Could you also attach the complete build log? It's not saved in the logs directory, you'll have to open the build log tab in the IDE and copy the text.

**Comment by mackayn** [comment] 2019-10-01 13:28
Seeing this issue too.

I can work round it with the following steps

Get code1 error
Open iOS properties
Select Automatic for provisioning profile
Save csproj file
Select correct profile
Save csproj file
Deploys correctly.

Seen this bug come and go in Visual Studio since the dark days of 2015

**Comment by dhirensham** [comment] 2019-10-02 08:15
Same here, I typically get the codesign error after doing a full rebuild. It then goes away after switching from manual to automatic provisioning (or vice versa, depending on which was currently set). So it's not specific to one type of provisioning profile. It seems more related to the profile not being applied correctly during a rebuild, or being overwritten/lost during a later step, but then after changing the setting to trigger VS to re-apply the provisioning profile and doing a build, not rebuild, things then work because whatever was causing it to break during the rebuild step doesn't happen on a normal build.

**Comment by VividDigital** [comment] 2019-10-29 13:51
Getting this error and very annoying as the only way I can fix it is by doing a clean between every build. Any update on this? Doing a full build every time to test is no way to work. I've deleted the certs from keychain and re-added, full reboots etc. Nothing helps. Using the latest version of everything except windows which is Windows 7. Trying to deploy to a late 2018 iPad Pro

[Also see here same issue](https://developercommunity.visualstudio.com/content/problem/729766/codedesign-exited-with-code-1.html)

**Comment by rolfbjarne** [comment] 2019-10-29 15:13
For anybody who can reproduce this: please get a diagnostic build log from both a working and a failing build, and attach both build logs here.

To get diagnostic build logs set the log verbosity to diagnostic at the following menu location: Tools > Options > Projects and Solutions > Build and Run

You also want to add -v -v -v -v to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting Properties.

**Comment by rolfbjarne** [comment] 2019-10-30 07:28
@VividDigital thank you for the build logs!

A fix is in progress: #7332.

**Comment by VividDigital** [comment] 2019-10-30 13:14
Great. Thanks for the quick response.

**Comment by VividDigital** [comment] 2019-11-01 10:47
When can we expect the next update to be pushed out? This bug is really slowing down development

**Comment by VividDigital** [comment] 2019-11-06 19:16
Following up....

**Comment by Inrego** [comment] 2019-11-07 05:17
Also eagerly awaiting this to be fixed, as it's the biggest annoyance developing for iOS on Windows at the moment.. My build host is very slow, so whenever this happens I spend an hour trying to rebuild with different settings until it suddenly works again.

**Comment by mabdollahiasl** [comment] 2019-11-15 13:18
visual studio 2019 Version: 16.3.9
I have this problem too....

**Comment by feanorn777** [comment] 2019-11-22 18:10
VS 2019 16.3.10. The problem still persists

**Comment by VividDigital** [comment] 2019-12-10 16:15
This is supposed to be fixed in the new preview as seen here: https://developercommunity.visualstudio.com/content/problem/729766/codedesign-exited-with-code-1.html?childToView=842480#comment-842480

It is NOT fixed. How long is this going to take? This bug makes it pretty much impossible to work if your app is sizable at all.

**Comment by whitneyschmidt** [comment] 2019-12-17 21:37
@VividDigital I'm sorry that you're still encountering this issue.

There's a workaround in the forum post you linked:

We’ve detected this issue is easily reproducible when using copy always for any file, so if any of your files has the Copy to Output Directory property set to Always we recommend you to change it to Copy if newer. This is a workaround but also a recommendation since using copy always might have a negative impact on the build performance.

Please let us know if that works.

@emaf - Is there anything that I can link so users can track the progress of a fix?

**Comment by whitneyschmidt** [comment] 2019-12-17 21:47
@VividDigital - The best way to track the progress of the fix is by following the dev community thread: https://developercommunity.visualstudio.com/content/problem/729766/codedesign-exited-with-code-1.html?childToView=842480#comment-842480

Closing this GH issue as there is nothing actionable for the MaciOS team and it is tracked in DevOps.

**Closed by whitneyschmidt** 2019-12-17 21:47 UTC
Labels: bug, iOS, need-info

**Comment by saidalsaidi** [comment] 2020-01-08 19:29
is there any solution for this problem

**Comment by whitneyschmidt** [comment] 2020-01-09 18:25
@saidalsaidi There is a workaround posted in this comment: https://github.com/xamarin/xamarin-macios/issues/6813#issuecomment-566759937

You can track progress on a fix here: https://developercommunity.visualstudio.com/content/problem/729766/codedesign-exited-with-code-1.html?childToView=842480#comment-842480

It looks like it has been fixed and should be available in an upcoming release.

**Comment by cgladue** [comment] 2020-01-18 08:05
i was having this issue, downloaded VS 2019 v16.5 Preview 1 and that fixed the problem

**Comment by rezamohamed** [comment] 2020-04-01 06:55
I am on VS 16.5.2 and am seeing this issue now.

**Comment by rodvind** [comment] 2020-04-22 16:12
downloaded the latest vs and still see this issue

**Comment by zerokewl88** [comment] 2020-05-26 11:34
Also downloaded the RC 16.7 Preview 1.0, and it is itermittent - sometimes this error occurs, or not at all the first build / archive - but the constantly unable to build there afterwoulds, and looking for answers here again. Anyone have any stable luck ? I am building on a older mac mini, and was thinking if upgrading the device to a new 6 core i7 might help things - its painfully slow to build and then have to wait for this to never actually finish a complete build - where as 20 minutes ago on the previous build, it worked fine (still takes ages to compile though)

**Comment by Rothanan** [comment] 2020-07-20 15:58
Getting the same error for the 100th time, nothing I do will fix it. I hate the day I have to deal with Apple, unecessary and annoying as *****.

**Comment by pietrodicaprio** [comment] 2021-02-12 09:22
Any progress on this? I can't bundle my app because i MUST clear the solution for **every build** process and looks like the bundling executes it twice (or at least executes twice the stuff that triggers this error).

**Comment by rolfbjarne** [comment] 2021-02-12 10:09
@pietrodicaprio you're probably running into a different underlying issue than the one originally reported here (because this one has been fixed), so please file a new issue, and please get a diagnostic build log from both a working and a failing build (as described [here](https://github.com/xamarin/xamarin-macios/issues/6813#issuecomment-547471613)), and attach both build logs in the new issue.
