### ISSUE TITLE
Mac: wrong App Bundle icon if built under /tmp

### ISSUE THREAD

**Issue by johannes-schmitt** [xamarin/xamarin-macios#4400] opened 2018-07-05 13:08 UTC
### Steps to Reproduce
1. Use Visual Studio for Mac to create a new Cocoa App - **make sure its location is under /tmp directory** (e.g. /tmp/test)
2. Build the project
3. Use Finder to go to the produced app bundle
4. Check the app icon

### Expected Behavior
Finder shows the Xamarin default app Icon: ![expected](https://user-images.githubusercontent.com/9046926/42324686-19df4c5a-8064-11e8-923f-4e5a16782754.png)
### Actual Behavior
Finder shows MacOS default (fallback) app icon: ![actual](https://user-images.githubusercontent.com/9046926/42324688-1c45467a-8064-11e8-91ee-e0519c37940b.png)

### Environment
```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.5.3 (build 7)
Installation UUID: 7f2269fb-2856-4e48-807f-7ce4507a5f25
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Version: 2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Not Installed

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.4.1.193 (Visual Studio Enterprise)

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Xamarin.iOS ===

Version: 11.12.0.4 (Visual Studio Enterprise)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

=== Build Information ===

Release ID: 705030007
Git revision: 13cecd02aceddf29a1ed57b86f81c02994df1483
Build date: 2018-06-14 15:48:08-04
Xamarin addins: 7065de97cf22c9038fdc39dd627f2c30790fd8af
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.5
Darwin 17.6.0 Darwin Kernel Version 17.6.0
    Tue May  8 15:22:16 PDT 2018
    root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
```

**Comment by dalexsoto** [comment] 2018-07-06 00:59
I am able to reproduce this issue with the steps outlined above

**Comment by rolfbjarne** [comment] 2024-03-20 07:23
This is probably because /tmp is a symlink (to /private/tmp), and we apparently don't handle symlinks correctly.

See #20330 for some diagnostic information.

Closing as a duplicate of #20330, since that issue has more information.

**Closed by rolfbjarne** 2024-03-20 07:23 UTC
Labels: bug, macOS
