### ISSUE TITLE
Lower the 'Deployment Target' to see older simulators or check your Apple SDK path warning after update on Xcode 16

### ISSUE THREAD

**Issue by VladimirPlatun** [xamarin/xamarin-macios#21333] opened 2024-09-30 16:11 UTC
### Apple platform

iOS, macOS

### Framework version

Other

### Affected platform version

VS for mac 17.6.14(build 413)

### Description

I can't run my Xamarin Forms application on Mac in the simulator, writes: Lower the 'Deployment Target' to see older simulators or check your Apple SDK path warning after update. VS for mac has SDK version 16.0.
![image](https://github.com/user-attachments/assets/0fb1c6cb-c5cf-4b20-b66a-6a7cd94a6425)
![image](https://github.com/user-attachments/assets/dbdc7eb4-170d-4445-921b-938c9de473f6)
![image](https://github.com/user-attachments/assets/51df7e97-4671-493b-98cd-32f941abf3ee)

### Steps to Reproduce

I just updated the mac to support ios 18 in Xcode and all the emulators are gone. 

### Did you find any workaround?

I tried to create new applications, but they didn't work in Xamarin Forms, there were no emulators for ios devices. But using an application written in SwiftUI, the emulator started and worked.

**Comment by rolfbjarne** [comment] 2024-10-01 10:52
This is a duplicate of #21326.

**Closed by rolfbjarne** 2024-10-01 10:52 UTC
