### ISSUE TITLE
_CopyAppExtensionsToBundle calls ditto with Windows path

### ISSUE THREAD

**Issue by OlaOsttveit** [xamarin/xamarin-macios#11817] opened 2021-06-04 13:30 UTC
### Steps to Reproduce

1. Use Visual Studio 16.10
2. Create an iOS project with an app extension
2. Build the project on Windows with msbuild 

### Expected Behavior

_CopyAppExtensionsToBundle build step calls ditto with a relative mac server path to the app extension
This was the case with Visual Studio 16.9

### Actual Behavior

_CopyAppExtensionsToBundle build step calls ditto with an absolute Windows path to the app extension

### Environment

```
Microsoft Visual Studio Professional 2019
Version 16.10.0
VisualStudio.16.Release/16.10.0+31321.278
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA829
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.10.525.31942
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.10.525.31942
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.10.525.31942
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.10.525.31942
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.10.21111.19
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Dotfuscator Community Edition   6.3.0+8b29d6f4a2
PreEmptive Protection - Dotfuscator CE

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IncrediBuild Build Acceleration   1.5.0.13
IncrediBuild effectively reduces compilation and development times by up to 90%.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Linux Core Dump Debugging   1.0.9.31313
Enables debugging of Linux core dumps.

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.10
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40423.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.30310.1 Commit Hash:e550dd1b679956810ccace4368dbc7a64443213b
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   16.0.31130.00
Microsoft Office Developer Tools for Visual Studio

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.10.21111.19
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.10.21111.19
Conda support for Python projects.

Python - Django support   16.10.21111.19
Provides templates and integration for the Django web framework.

Python - Profiling support   16.10.21111.19
Profiling support for Python projects.

Python - VC Project Support   16.1.19129.1
Provides support for launching C++ projects with Python debugging enabled.

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62105.04180
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.30429.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   16.0.31306.167
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Cross Platform Mobile Development (iOS)   16.0.31213.239
Visual C++ for Cross Platform Mobile Development (iOS)

Visual C++ for Linux Development   1.0.9.31313
Visual C++ for Linux Development

Visual F# Tools   16.10.0-beta.21262.7+1b23bbeda88ea3cb9be9af777f4c99fa8663df81
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

Visual Studio Tools for Unity   4.10.2.0
Visual Studio Tools for Unity

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   16.10.000.228 (d16-10@1c8354c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.10.0.115 (remotes/origin/c750fbf1bde3c720d077f51640fe197c6dac7cbe@c750fbf1b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.3.0.1 (d16-10/22fc2b3)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: b4a3858
    Java.Interop: xamarin/java.interop/d16-10@f39db25
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0


Xamarin.iOS and Xamarin.Mac SDK   14.20.0.1 (fe0e2c518)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Build Logs

2021-06-04T09:43:37.0488217Z _CopyAppExtensionsToBundle:
2021-06-04T09:43:37.0489030Z   Creating directory "bin\iPhone\AppStore\<AppName>\PlugIns".
2021-06-04T09:43:37.1356226Z   Creating directory "bin/iPhone/AppStore/<AppName>/PlugIns".
2021-06-04T09:43:37.3084076Z   [xma]: build5f7d4deb3ae3329001286220b8930b4ed359b957a5fe1aa0d27718fdb56867bf10044TfsBu received ping. Sending acknowledge...
2021-06-04T09:43:37.4922142Z   /usr/bin/ditto D:/Source/<AppExtensionName>/bin/iPhone/AppStore/<AppExtensionName>.appex bin/iPhone/AppStore/<AppName>/PlugIns/<AppExtensionName>appex 
2021-06-04T09:43:37.4924554Z   ditto: Cannot get the real path for source 'D:/Source/<AppExtensionName>/bin/iPhone/AppStore/<AppExtensionName>.appex'
2021-06-04T09:43:37.4975420Z c:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(1251,3): error MSB6006: "ditto" exited with code 1. [D:\Source\<ProjectName>\<ProjectName>.csproj]
2021-06-04T09:43:37.4984664Z Done Building Project "D:\Source\<ProjectName>\<ProjectName>.csproj" (default targets) -- FAILED.
2021-06-04T09:43:37.4992891Z Done Building Project "D:\<SolutionName>.sln" (Build target(s)) -- FAILED.
2021-06-04T09:43:37.5021017Z 
2021-06-04T09:43:37.5022302Z Build FAILED.

Here is the build output for Visual Studio 16.9 which works fine:
2021-06-01T09:16:55.6038631Z _CopyAppExtensionsToBundle:
2021-06-01T09:16:55.6039091Z   Creating directory "bin\iPhone\AppStore\<AppName>\PlugIns".
2021-06-01T09:16:55.7116396Z   Creating directory "bin/iPhone/AppStore/<AppName>/PlugIns".
2021-06-01T09:16:55.9304396Z   /usr/bin/ditto -rsrc ../../<AppExtensionName>/d1b2095c864c4d0a049a6b3fd50c10faa89d01db8e3e5afc525ad734a9d84aab/bin/iPhone/AppStore/<AppExtensionName>.appex bin/iPhone/AppStore/<AppName>/PlugIns/<AppExtensionName>.appex 
2021-06-01T09:16:55.9402212Z   Directory "bin\iPhone\AppStore\<AppName>\PlugIns\<AppExtensionName>.appex\_CodeSignature" doesn't exist. Skipping.
2021-06-01T09:16:55.9404498Z   Directory "bin\iPhone\AppStore\<AppName>\..\<AppExtensionName>.appex.dSYM" doesn't exist. Skipping.

Here ditto is called with a relative mac path instead of the absolute Windows path.

### Example Project (If Possible)

> VS bug [#1339834](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1339834)

**Comment by spouliot** [comment] 2021-06-04 13:49
This looks like a duplicate of https://github.com/xamarin/xamarin-macios/issues/11786

The issue is not just about icons (that's just the most common case) but it affects how Windows tasks think they are executing on macOS vs Windows.

c.c. @emaf to confirm

**Comment by emaf** [comment] 2021-06-04 14:22
@spouliot it doesn't look like the same problem, it seems to be what we fixed here https://github.com/xamarin/xamarin-macios/commit/2df2665e4cb06e25d7e37ca9a47a1fd015201ed8#diff-1297479d99f283298da617f6ce6d7948680bcba0f9f011ba0f74616351e344d8R28.

@OlaOsttveit could you please try replacing `_GenerateAppBundleName;_GenerateAppExBundleName` by `_GenerateBundleName` in your `Xamarin.iOS.Common.After.targets` file (it's inside your VS installation folder, i.e. `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS`) just to confirm if that's the problem? Thanks!

**Comment by spouliot** [comment] 2021-06-04 14:47
@emaf thanks, was that backported to d16-10 ? 
also is there another open issue (if so I'll close this one after confirmation).

**Comment by emaf** [comment] 2021-06-04 14:59
@spouliot yes, it was already backported to d16-10, but it wasn't released on VS yet. I think this is the first external report for this problem, or at least I'm not aware of any other open issues related to this.

**Comment by OlaOsttveit** [comment] 2021-06-07 10:18
> 
> 
> @spouliot it doesn't look like the same problem, it seems to be what we fixed here [2df2665#diff-1297479d99f283298da617f6ce6d7948680bcba0f9f011ba0f74616351e344d8R28](https://github.com/xamarin/xamarin-macios/commit/2df2665e4cb06e25d7e37ca9a47a1fd015201ed8#diff-1297479d99f283298da617f6ce6d7948680bcba0f9f011ba0f74616351e344d8R28).
> 
> @OlaOsttveit could you please try replacing `_GenerateAppBundleName;_GenerateAppExBundleName` by `_GenerateBundleName` in your `Xamarin.iOS.Common.After.targets` file (it's inside your VS installation folder, i.e. `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS`) just to confirm if that's the problem? Thanks!

This fixed the _CopyAppExtensionsToBundle task, I had to do a manual clean of all bin and obj files first though.
But I'm getting a new error on the SymbolStrip task:

```
Task "SymbolStrip" (TaskId:563)
  Task Parameter:Executable=bin\iPhone\Ad-Hoc\<AppName>.app\PlugIns\<AppExtensionName>.appex\<AppExtensionName> (TaskId:563)
  Task Parameter:SessionId=e5361af486da597448c7a23de751d118b8012f62475d68605067ab991351dccc (TaskId:563)
  Task Parameter:IsFramework=False (TaskId:563)
  Task Parameter:SymbolFile=D:\Source\<AppName>\Source\<AppExtensionName>\obj\iPhone\Ad-Hoc\mtouch-symbols.list (TaskId:563)
  SymbolStrip: 2021-06-07T11:58:47.2821269+02:00 - Started (TaskId:563)
  SymbolStrip: 2021-06-07T11:58:47.2821269+02:00 - Initializing (TaskId:563)
  [xma]: Trying to get a Build Connection for Session 'e5361af486da597448c7a23de751d118b8012f62475d68605067ab991351dccc': Xamarin.Messaging.Build.Client.BuildConnection.e5361af486da597448c7a23de751d118b8012f62475d68605067ab991351dccc, Lifetime: Build (TaskId:563)
  SymbolStrip: 2021-06-07T11:58:47.2821269+02:00 - Initialized (TaskId:563)
  SymbolStrip: 2021-06-07T11:58:47.2831293+02:00 - There's no available inputs to copy to the Mac (TaskId:563)
  SymbolStrip: 2021-06-07T11:58:47.2831293+02:00 - Serializing intputs (TaskId:563)
  SymbolStrip: 2021-06-07T11:58:47.2881260+02:00 - Executing (TaskId:563)
  [xma]: Starting remote task execution for '<AppName>': Xamarin.MacDev.Tasks.SymbolStrip (TaskId:563)
  [xma]: Sending Request Xamarin.Messaging.Build.Contracts.ExecuteTaskMessage to topic xvs/build/execute-task/<AppName>/e5361af002fSymbolStrip (TaskId:563)
  [xma]: Received Response of Xamarin.Messaging.Build.Contracts.ExecuteTaskMessage to topic builde5361af486da597448c7a23de751d118b8012f62475d68605067ab991351dccc18284OlaOs/+/xvs/build/execute-task/<AppName>/e5361af002fSymbolStrip (TaskId:563)
  SymbolStrip: 2021-06-07T11:58:47.8331696+02:00 - Logging messages (TaskId:563)
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -i -s D:/Source/<ProjectName>/Source/<AppExtensionName>/obj/iPhone/Ad-Hoc/mtouch-symbols.list bin/iPhone/Ad-Hoc/<AppName>.app/PlugIns/<AppExtensionName>.appex/<AppExtensionName>  (TaskId:563)
  error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: can't open: D:/Source/<ProjectName>/Source/<AppExtensionName>/obj/iPhone/Ad-Hoc/mtouch-symbols.list (No such file or directory) (TaskId:563)
c:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(1311,3): error MSB6006: "strip" exited with code 1. [D\Source\<ProjectName>\Source\<AppName>\<AppName>.csproj]
  SymbolStrip: 2021-06-07T11:58:47.8391711+02:00 - Finished (TaskId:563)
Done executing task "SymbolStrip" -- FAILED. (TaskId:563)

```

Looks like the same kind of issue with Windows paths being passed to the mac.

**Comment by emaf** [comment] 2021-06-07 20:32
@OlaOsttveit oh, I'm sorry about that. I haven't seen that one before, could you try the following:
- Remove this line https://github.com/xamarin/xamarin-macios/blob/d16-10/msbuild/Xamarin.Shared/Xamarin.Shared.targets#L1395
- Add this right before that `PropertyGroup`, inside `_PrepareDebugSymbolGeneration`:
`<GetFullPath SessionId="$(BuildSessionId)" Condition="'$(IsMacEnabled)' == 'true'" RelativePath="$(_MtouchSymbolsList)">
			<Output TaskParameter="FullPath" PropertyName="_SymbolsListFullPath" />
		</GetFullPath>`

@spouliot it seems on this commit https://github.com/xamarin/xamarin-macios/commit/05e28c37132d44b17d27125176ec4e54aa36f6c1 we replaced the usage of the GetFullPath task by an inline method (from Windows that'll always return a Windows path), but I'm not sure why, could you please take a look at it? Thanks!

**Comment by spouliot** [comment] 2021-06-08 00:51
@emaf not quite sure, but likely a mix of not expecting a Windows path (because of the condition), the task code did the same (I now suspect it's overridden on Windows to do something else ?) and simplified code sharing between the iOS/Mac versions.

**Comment by OlaOsttveit** [comment] 2021-06-08 11:53
> 
> 
> @OlaOsttveit oh, I'm sorry about that. I haven't seen that one before, could you try the following:
> 
>     * Remove this line https://github.com/xamarin/xamarin-macios/blob/d16-10/msbuild/Xamarin.Shared/Xamarin.Shared.targets#L1395
> 
>     * Add this right before that `PropertyGroup`, inside `_PrepareDebugSymbolGeneration`:
>       `<GetFullPath SessionId="$(BuildSessionId)" Condition="'$(IsMacEnabled)' == 'true'" RelativePath="$(_MtouchSymbolsList)"> <Output TaskParameter="FullPath" PropertyName="_SymbolsListFullPath" /> </GetFullPath>`
> 

This worked, we have iOS builds completing now 👍

**Comment by emaf** [comment] 2021-06-08 12:46
@OlaOsttveit that's great!

@spouliot the problem is where things are executed, everything that happens on a target is executed locally, but tasks are executed remotely (if the SessionId prop is set), so they do the same but are executed in different contexts

**Closed** 2021-06-09 13:19 UTC
Labels: external-xamarin-vs, iOS, need-info

**Comment by OlaOsttveit** [comment] 2021-06-16 09:17
I upgraded to Visual Studio 16.10.2 and the _CopyAppExtensionsToBundle task works now.
But the SymbolStrip task is still failing with the Windows path issue - it seems that the SymbolStrip workaround has not been added like the _CopyAppExtensionsToBundle workaround.

Should I create a new bug for this SymbolStrip issue?
