### ISSUE TITLE
Error MT4109: Failed to compile the generated registrar code. (MT4109)

### ISSUE THREAD

**Issue by shouvik-halder** [xamarin/xamarin-macios#19089] opened 2023-09-21 19:36 UTC
### Steps to Reproduce

1.  Upgraded XCODE to version 15.
2. Upgraded Visual Studio to version 17.6.4
3. Rebuild the solution, I'm getting this issue

**Comment by shouvik-halder** [comment] 2023-09-21 19:39
Target _CompileToNative:
    /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/haldesh/Documents/DFSv2/Master/MobileApp/MG365Mobile/Spark.iOS/obj/iPhoneSimulator/Debug/response-file.rsp --optimize=experimental-xforms-product-type --registrar:static "--gcc_flags=-Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/haldesh/Documents/DFSv2/Master/MobileApp/MG365Mobile/Spark.iOS/obj/iPhoneSimulator/Debug/Entitlements.xcent" 
    Xamarin.iOS 16.4.0.6 (xcode14.3: 97731c92c) using framework: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.0.sdk
    
    
    
    
    After this the error is coming. Please help

**Comment by rpendleton** [comment] 2023-09-22 02:57
Someone from Microsoft might be able to confirm, but as far as I understand it, Xamarin.iOS isn't going to support Xcode 15. For Xcode 15 support, you'll need to update to .NET 8.

**Comment by pulmuone** [comment] 2023-09-22 05:57
same issue

**Comment by JoseAntonioRA** [comment] 2023-09-22 11:18
I have the same issue, is there a solution or will we have to wait?

**Comment by snechaev** [comment] 2023-09-22 16:03
> is there a solution or will we have to wait?

If you really need XCode 15. then you will have to wait until the Xamarin releases the version with XCode 15 support.
Or you can downgrade XCode to 14.3, which is supported by the current version of Xamarin.

**Comment by kpespisa** [comment] 2023-09-22 16:09
You can leave XCode 15 in place, and install XCode 14.3 as well until VS is updated. https://developer.apple.com/download/all/?q=xcode%2014

Launch XCode 14, download any simulators you need, and make sure it installs command line tools etc. 

I had one other issue where I saw "simctl returned exit code 72" when trying to debug. I had to go to Xcode menu > Preferences… > Locations tab > and select the XCode 14 Command Line Tools

**Comment by JoseAntonioRA** [comment] 2023-09-25 12:07
Once I downgraded xcode to version 14.3, and I try to start the application on an iPhone 12 with iOS 17, the application installs but it does not start, getting this same error: `simctl returned exit code 72`, the same thing happens to me when trying to install it on an iPhone 14 emulator with iOS 17, but however in iOS 16.3 it does allow me to open the application.

Would there be a solution for this right now?

**Comment by KRA2008** [comment] 2023-09-27 01:44
Note: Xcode 14 doesn't run on Sonoma (macOS 14.0). So don't upgrade your OS like I just did!

**Comment by KRA2008** [comment] 2023-09-28 00:35
> Note: Xcode 14 doesn't run on Sonoma (macOS 14.0). So don't upgrade your OS like I just did!

Actually, it turns out you can install Xcode 14 on Sonoma, but you won't be able to launch the app itself, however, the command line tools are still usable. So set the setting in Visual Studio to point at Xcode 14.

**Comment by dalexsoto** [comment] 2023-10-02 15:47
This is a partial duplicate of this https://github.com/xamarin/xamarin-macios/issues/18964 please try the versions listed in the first comment, this adds Xcode 15 support just not any bindings

**Closed by dalexsoto** 2023-10-02 15:47 UTC
Labels: question, iOS
