### ISSUE TITLE
Simulators gone again in Xcode 14.3

### ISSUE THREAD

**Issue by netzperfekt** [xamarin/xamarin-macios#17962] opened 2023-04-03 09:32 UTC
after updating to Xcode 14.3 - once again - all ios simulator entries have disappeared in vs mac. When will there be an update? 
Thanks!

**Comment by dalexsoto** [comment] 2023-04-03 12:45
Hello, this is a duplicate of https://github.com/xamarin/xamarin-macios/issues/17561 please downgrade to Xcode 14.2 for now.

**Closed by dalexsoto** 2023-04-03 12:45 UTC
Labels: iOS
