### ISSUE TITLE
[macOS] Cannot use PublishTrimmed=true

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#19142] opened 2023-10-09 16:42 UTC
### Steps to Reproduce

1. `dotnet new macos`
2. Add `<PublishTrimmed>true</PublishTrimmed>` to test.csproj
3. `dotnet publish`

### Expected Behavior

App builds and gets trimmed without errors

### Actual Behavior
`/usr/local/share/dotnet/sdk/8.0.100-rc.1.23463.5/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(212,5): error NETSDK1191: A runtime identifier for the property 'SelfContained' couldn't be inferred. Specify a rid explicitly. [/Users/me/GitHub/test/test.csproj]
`
### Environment
`macos                      13.3.8825-net8-rc1/8.0.100-rc.1      SDK 8.0.100-rc.1   
`

### Example Project (If Possible)

[test.zip](https://github.com/xamarin/xamarin-macios/files/12848451/test.zip)

### Comments
Until today, I was under the impression, that using  `TrimMode=full` did trim out every unused code from my application. However, I was surprised that my app did not throw any error when using System.Json.Text in .NET8 without source generators. I expected it to throw an [System.InvalidOperationException](https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-8/#disabling-reflection-defaults) as documented (and I also saw that exception in my .NET8 Android project).
As a side-note / additional question: I also added `PublishTrimmed=true` to my iOS app, built and uploaded it to TestFlight. It also does not throw the mentioned/expected System.InvalidOperationException. Does the `PublishTrimmed` property even have any effect in iOS/macOS projects?

**Comment by rolfbjarne** [comment] 2023-10-12 12:41
I can reproduce this, and a fix is in progress. Hopefully we'll be able to get it in the initial .NET 8 release.

Note that `PublishTrimmed=true` is redundant on macOS projects, because that's the default, so you can safely remove it.

> However, I was surprised that my app did not throw any error when using System.Json.Text in .NET8 without source generators. I expected it to throw an [System.InvalidOperationException](https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-8/#disabling-reflection-defaults) as documented (and I also saw that exception in my .NET8 Android project).

This is because we've changed the default for `JsonSerializerIsReflectionEnabledByDefault` to `true`, to avoid breaking people.

If you do this in your project:

```xml
<PropertyGroup>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
</PropertyGroup>
```

you should get the InvalidOperationException.

**Comment by tipa** [comment] 2023-10-12 12:54
Thanks. I always though that settings `TrimMode=full` would also set `PublishTrimmed=true` implicitly. Is this not the case? If not, what is the difference and does setting it to true explicitly result in any additional size reductions on both iOS & macOS?
On .NET Android, `PublishTrimmed` is set to true automatically in Release mode under certain conditions (and that causes `JsonSerializerIsReflectionEnabledByDefault` to be set to false.): https://github.com/xamarin/xamarin-android/blob/58a81eb148acb2d2f5d3df91629bba3a3129e773/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets#L71-L72

Can the same be done for iOS & macOS?

**Comment by rolfbjarne** [comment] 2023-10-12 13:07
We always set `JsonSerializerIsReflectionEnabledByDefault=true`:

https://github.com/xamarin/xamarin-macios/blob/1a05b370ef3905cc06c8c385fdaa2e920afd89e5/dotnet/targets/Xamarin.Shared.Sdk.props#L96C1-L97

> Also, does settings `JsonSerializerIsReflectionEnabledByDefault` to false result in any app size reduction?

No idea, my guess is that it could go either way, so testing it on your app is the only way to know for sure.

> Thanks. I always though that settings `TrimMode=full` would also set `PublishTrimmed=true` implicitly on iOS as well.

Note quite: we've hijacked the linker for our own purposes (in addition to what the linker usually does), and that means it's always executed (in fact we set `PublishTrimmed=true`, and if you try to tell us otherwise by setting `PublishTrimmed=false` yourself, you'll get a build error).

Then you can adjust exactly what's linked by setting the `TrimMode` property, or the old-style `MtouchLink` property (`TrimMode` takes precedence if you set both). You can even set `MtouchLink=None`, and the linker will still run, but not actually trim any assemblies (it'll only do what we hijacked it to do).

> does setting it to true explicitly result in any additional size reductions?

Setting `PublishTrimmed=true` doesn't change anything.

Setting `TrimMode=full` will change the output, and likely save some space.

**Closed** 2023-10-16 08:19 UTC
Labels: bug, regression
