### ISSUE TITLE
BeginInvokeOnMainThread does not work with method groups for some reason

### ISSUE THREAD

**Issue by jasonctoms** [xamarin/xamarin-macios#4389] opened 2018-07-04 11:39 UTC
### Steps to Reproduce
This can be easily reproduced in any size iOS project with any threaded code.

1.  Run a thread (on a TableView for example) and call `BeginInvokeOnMainThread(TableView.ReloadData);` within that thread.
2. Run the same code with `BeginInvokeOnMainThread(() => TableView.ReloadData());`

### Expected Behavior
Both methods should work properly since they SHOULD be the same thing.

### Actual Behavior
The first method (using a method group) experiences an exception caused by running UI code on a background thread.  The second method works as expected.

### Environment
```
Visual Studio Enterprise 2017 for Mac
Version 7.5.3 (build 7)
Installation UUID: 2d9ce4ab-2552-452a-8f0d-b2b42e543a97
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Version: 2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Xamarin.Android
Version: 8.3.3.2 (Visual Studio Enterprise)
Android SDK: /Users/jasontoms/Library/Android/sdk
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 28.0.0

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Apple Developer Tools
Xcode 9.4.1 (14161)
Build 9F2000

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 11.12.0.4 (Visual Studio Enterprise)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

Build Information
Release ID: 705030007
Git revision: 13cecd02aceddf29a1ed57b86f81c02994df1483
Build date: 2018-06-14 15:48:08-04
Xamarin addins: 7065de97cf22c9038fdc39dd627f2c30790fd8af
Build lane: monodevelop-lion-d15-7

Operating System
Mac OS X 10.13.5
Darwin 17.6.0 Darwin Kernel Version 17.6.0
    Tue May  8 15:22:16 PDT 2018
    root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

Enabled user installed addins
Internet of Things (IoT) development (Preview) 7.5

```

### Build Logs

None

### Example Project (If Possible)

Can use any iOS project.

**Comment by dalexsoto** [comment] 2018-07-06 00:51
Hello @jasonctoms, 

I have not been able to reproduce the issue you are describing above, I have attached the sample I created in order to test this, could you please give it a try and if possible accommodate the code to reproduce the behavior you are getting?

Thanks in advance!

[GHIssue4389.zip](https://github.com/xamarin/xamarin-macios/files/2168667/GHIssue4389.zip)

Code snippet from `ViewController.cs`:

```csharp
public async Task TaskAsync ()
{
	while (!cancelTokenSrc.Token.IsCancellationRequested) {
		if (!NSThread.IsMain) { // Making sure we are in a background thread
			BeginInvokeOnMainThread (ChangeColor);
			//BeginInvokeOnMainThread (() => ChangeColor ());
		}
		await Task.Delay (TimeSpan.FromSeconds (2), cancelTokenSrc.Token);
	}
}
```

**Comment by migueldeicaza** [comment] 2018-07-27 12:55
Closing due to lack of a response and a repro that shows that this works, it might be a different problem

**Closed by migueldeicaza** 2018-07-27 12:55 UTC
Labels: iOS, need-info
