### ISSUE TITLE
Getting "dyld: Library not loaded: @rpath/Mono.framework/Mono" while debug tvOS extension project.

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#3289] opened 2018-01-23 13:55 UTC
### Steps to reproduce:
1. Create a tvOS template project and add a TV Services Extension project.
2. Select tvOSextension project from menu and run it in debug mode.
3. Go To Simulator or device. Select the tvOSextension app from TopShelf and pull it down using apple tv remote for simulator and device.

## Actual Behaviour:  Getting error while debug tvOS extension app.
dyld: Library not loaded: @rpath/Mono.framework/Mono Referenced from: /Users/globallogic/Library/Developer/CoreSimulator/Devices/CF94002B-646E-491F-9795-E7C1A27ED9CA/data/Containers/Bundle/Application/1317D9B3-70C2-4E15-BD56-36FF3BC2AA4E/tvsingle.app/PlugIns/tvseriesextension.appex/tvseriesextension Reason: no suitable image found. Did find: /Users/globallogic/Library/Developer/CoreSimulator/Devices/CF94002B-646E-491F-9795-E7C1A27ED9CA/data/Containers/Bundle/Application/1317D9B3-70C2-4E15-BD56-36FF3BC2AA4E/tvsingle.app/PlugIns/tvseriesextension.appex/../../Frameworks/Mono.framework/Mono: required code signature missing for '/Users/globallogic/Library/Developer/CoreSimulator/Devices/CF94002B-646E-491F-9795-E7C1A27ED9CA/data/Containers/Bundle/Application/1317D9B3-70C2-4E15-BD56-36FF3BC2AA4E/tvsingle.app/PlugIns/tvseriesextension.appex/../../Frameworks/Mono.framework/Mono'

### Environment

```
Environment : 
Version 7.4 Preview (7.4 build 884)
Mono 5.8.0.108 (2017-10/9aa78573ee2) (64-bit)
Xamarin.Android Version: 8.2.0.6
Xamarin.Mac Version: 4.2.0.8
Xamarin.iOS Version: 11.8.0.8

Build Info : https://gist.github.com/GLjackyvaswani/8216002eb5de09aaad35810df4f3bc70
```
### Build Logs

Screencast : https://www.screencast.com/t/PKZyksc2MQ
Build Output : 
https://gist.github.com/mohakbarokar/9db05d6df5b704266fe5ae4aa3b640c6
Bug is reported as a regression in d15-6,

**Comment by VincentDondain** [comment] 2018-01-23 18:24
I could confirm that with the above steps to reproduce, we cannot hit a breakpoint set on `get { return TVTopShelfContentStyle.Sectioned; }` (TVService templates) while we can with XI 11.6.1.3 (d15.5 stable).

I got the same error Gouri mentioned, this is indeed a regression.

**Comment by spouliot** [comment] 2018-01-23 18:48
> required code signature missing for ...

@jstedfast can you have a look ? it might be related to the recent code signing changes

c.c. @rolfbjarne in case it's related to code sharing

**Comment by rolfbjarne** [comment] 2018-01-23 22:56
From the build log:

```
Target "_CodesignFrameworks" skipped, due to false condition; ('$(_CanOutputAppBundle)' == 'true' And '$(_CodeSigningKey)' != '' And '@(_Frameworks)' != '') was evaluated as ('True' == 'true' And '' != '' And 'bin/iPhoneSimulator/Debug/device-builds/appletv6.2-11.2/tvsingle.app/Frameworks/Mono.framework/Mono' != '').
```

this looks like something for @jstedfast

**Comment by rolfbjarne** [comment] 2018-01-29 09:57
The fix was merged (https://github.com/xamarin/xamarin-macios/commit/d86b0822a46fa383e7f599f8bc302b78c06aeef6), could you verify the fix with a wrench package? Then we might look into getting the fix into d15-6 somehow.

**Comment by rolfbjarne** [comment] 2018-01-29 09:57
@GouriKumari ^ forgot to mention you

**Comment by GouriKumari** [comment] 2018-01-29 17:45
@rolfbjarne : I checked it with XI d15-6 11.8.0.8 and  could reproduce the issue. ## Logs:

Verified with Xamarin.iOS master: 11.9.0.100 and breakpoint  for tvOS extension does hit. 
I observed a few discrepancies while launching tvOS extension app:
1)  I could launch the extension project when the break point is still hit and I can step in and out
2) Another case, break point is hit and I can step in and out but I need to use the  apple tv remote to launch the extension. 
I see similar behaviour with stable as well. 
## Screencast: https://www.screencast.com/t/AqNRJbPsq
Test Env: https://gist.github.com/GouriKumari/d490c26e2671acb0d782476bc38658c0

**Comment by rolfbjarne** [comment] 2018-01-30 09:41
@jstedfast could you please create the PR to backport this to d15-6?

**Comment by jstedfast** [comment] 2018-01-30 13:48
Back-ported to 15.6: https://github.com/xamarin/xamarin-macios/pull/3354

**Comment by rolfbjarne** [comment] 2018-01-31 14:10
@GouriKumari can you double-check that the bug occurs on device as well? I can reproduce in the simulator, but not on device, and it would affect how serious the bug is.

**Comment by GouriKumari** [comment] 2018-02-01 17:18
I couldn't reproduce this issue on device. Breakpoint in extension project gets hit as expected. Tested with current beta which failed for tvOS simulator.

## Screencast: https://screencast.com/t/h4rsIARzlz
## Test Env: https://gist.github.com/GouriKumari/8cc9d0cd53c32689d4a1ec5b6bc67a46

**Comment by rolfbjarne** [comment] 2018-02-05 18:05
Workaround: add `--mono:static` to the additional mtouch arguments in _all_ projects' iOS Build options.

**Comment by mohakbarokar** [comment] 2018-02-12 11:23
This issue is tested on Build : https://wrench.internalx.com/Wrench/ViewLane.aspx?lane_id=5920&host_id=392&revision_id=927710

& the breakpoint is hitting for TvServiceExtension.

Screencast Link: http://www.screencast.com/t/diqDm05DB6s

Observation: Breakpoint again points to same line number even after the execution is continued

We can mark the Bug as Resolved Fixed.

**Closed** 2018-03-27 17:26 UTC
Labels: bug, iOS
