### ISSUE TITLE
Not possible to solve CA1416 warnings on net8.0-ios

### ISSUE THREAD

**Issue by JeroenBer** [xamarin/xamarin-macios#20314] opened 2024-03-15 16:15 UTC
After moving from Xamarin we have a lot of CA1416 warnings. For Android we managed to solve them but for iOS it seems impossible.
Maybe also related to https://github.com/dotnet/maui/issues/15032

### Steps to Reproduce

1. Open very simple repro project https://github.com/JeroenBer/iOSLibWarnings
2. Compile
3. We get a warning:

warning CA1416: This call site is reachable on: 'iOS' 12.4 and later, 'maccatalyst' 13.0 and later. 'UITraitCollection.CurrentTraitCollection' is only supported on: 'ios' 13.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)

### Expected Behavior
 We don't expect a warning since it's guarded by

```
OperatingSystem.IsIOSVersionAtLeast(13, 0)
```

### Actual Behavior
We get an incorrect warning

### Environment

net8.0-ios

**Comment by rolfbjarne** [comment] 2024-03-18 08:45
This is a duplicate of https://github.com/dotnet/roslyn-analyzers/issues/7239.

If you're not building for Mac Catalyst, adding this attribute to your source code (anywhere outside a namespace) will silence the warning:

```cs
[assembly:System.Runtime.Versioning.UnsupportedOSPlatform("maccatalyst")]
```

**Closed by rolfbjarne** 2024-03-18 08:45 UTC

**Comment by bzd3y** [comment] 2024-03-21 17:58
@rolfbjarne This workaround doesn't seem to work for me, at least maybe for code that is in a shared project. When I put that line in MauiProgram.cs, outside of the namespace, it did silence warnings for code actually in the project. But warnings for code in the shared projects that project references was not silenced.

Adding `[UnsupportedOSPlatform("maccatalyst")]` or something like `[SupportedOSPlatform("maccatalyst13.1")]` directly to the class/method does silence the warning for that class/method.

So maybe there is another issue with the analyzer or analyzers in general? It doesn't seem to be picking up the assembly attributes in the files within the shared project.

**Comment by rolfbjarne** [comment] 2024-03-22 07:55
> So maybe there is another issue with the analyzer or analyzers in general? It doesn't seem to be picking up the assembly attributes in the files within the shared project.

Please file a new issue and attach a test project, and we'll have a look.

**Comment by bzd3y** [comment] 2024-04-03 14:51
> Please file a new issue and attach a test project, and we'll have a look.

Okay, would I file that issue here or a different project?

**Comment by rolfbjarne** [comment] 2024-04-05 15:36
> > Please file a new issue and attach a test project, and we'll have a look.
> 
> Okay, would I file that issue here or a different project?

You can file it here, we'll move it if it's better located elsewhere.

**Comment by bzd3y** [comment] 2024-04-21 13:34
@rolfbjarne FYI, I just tried the workaround you recommended again and this time it does seem to work. I'm not sure what was going on the first. Maybe the analyzers weren't getting to run or something.

Thanks again. This is much cleaner than what I had been doing.
