### ISSUE TITLE
The same Header exists in HttpContentHeaders and HttpResponseHeaders in a request

### ISSUE THREAD

**Issue by zhenlei520** [xamarin/xamarin-macios#17491] opened 2023-02-09 12:46 UTC
### Description

I don't know if this is a bug, but I think it's not normal. I accidentally discovered that HttpContentHeaders and HttpResponseHeaders contain the same information when using vs2022 to develop ios clients using xamarin.

![2b78a335105e4d4a7721de762fecd53](https://user-images.githubusercontent.com/9740886/217809760-a3e79259-4e91-48bd-a688-82d3a8521480.png)
![0fd6ea30df6f5b57eb8c3db8753e046](https://user-images.githubusercontent.com/9740886/217809769-cbe608b7-f1d9-4ccc-bc33-e62be6eec97f.png)

This problem has not always existed. It appeared after updating the preview version of vs2022 and the corresponding ios-related SDK. There was no such problem before.

### Steps to Reproduce

Create a .NET Maui APP.
Create a iOS Binding project

1. Install `Aliyun.OSS.SDK.NetCore` package version to `2.13.0`
2. Refer to [this demo](`https://github.com/aliyun/aliyun-oss-csharp-sdk/blob/master/samples/Samples/PutObjectSample.cs?spm=a2c4g.11186623.0.0.2992cb3672Qfqr&file=PutObjectSample.cs# L109`) Write a method for uploading pictures and execute it on the ios side

If you feel that the second step is troublesome, you can also try to build an API service by yourself. The response status code of the API is 200, and the returned response header contains `x-oss-hash-crc64ecma` and other headers to try. We have not done this kind of test for the time being. Not sure if this will work

Version with bug

IDE Version: 

Microsoft Visual Studio Enterprise 2022
Version 17.5.0 Preview 6.0
VisualStudio.17.Preview/17.5.0-pre.6.0+33402.96
Microsoft .NET Framework
Version 4.8.09032
Xamarin   17.5.0.172 (d17-5@2a1a1bf)
Xamarin Designer 17.5.3.46 (remotes/origin/d17-5@e4dd80b2bb)
Xamarin.Android SDK   13.2.0.0 (d17-5/797e2e1)
Xamarin.Android Reference Assemblies 
VisualStudio.Mac   1.0
Mac Extension for Visual Studio

SDK Version: 7.0.200-preview.22628.1

Last version that worked well

Unknown/Other

Affected platforms
iOS

Affected platform versions

iOS 15.7.1 .NET 7

Did you find any workaround?

Versions prior to Microsoft Visual Studio Enterprise 2022 preview4 do not have such issues，But in my opinion it should be related to the corresponding xamarin version, not directly related to the Visual Studio Enterprise version

Relevant log output
No response

**Comment by rolfbjarne** [comment] 2023-02-09 14:18
This looks like a duplicate of #17331.

**Comment by zhenlei520** [comment] 2023-02-10 01:19
Yes, it seems that they are the same problem. I checked the code related to the Header, and it seems that there is no problem with the judgment, but the result is actually inconsistent with the code. Can you explain this to me? thank you very much

https://github.com/xamarin/xamarin-macios/blob/main/src/System.Net.Http/CFNetworkHandler.cs#L396

**Comment by rolfbjarne** [comment] 2023-02-10 06:32
I don't think you're using that code, you're using this code:

https://github.com/xamarin/xamarin-macios/blob/8f6eb025423bcdaf77b04be60885e92269e07148/src/Foundation/NSUrlSessionHandler.cs#L875-L876

**Comment by zhenlei520** [comment] 2023-02-10 10:22
Yes, you are correct, thanks again for helping me out with this doubt.

**Comment by rolfbjarne** [comment] 2023-02-10 21:57
OK, I'll close this as a duplicate of #17331 then.

**Closed by rolfbjarne** 2023-02-10 21:57 UTC
