### ISSUE TITLE
[bugs] Xamarin.iOS when build with iphone debug / release mode raise 550 warning from Xamarin.Shared.Targets

### ISSUE THREAD

**Issue by sunkerGit** [xamarin/xamarin-macios#14166] opened 2022-02-16 12:54 UTC
Build the app using Xamarin.iOS project and set the device to iPhone / generic device. the build is shown a warning from Xamarin.Shared.Targets (550 warnings) when we are pointing to iPhone / generic device (debug/release mode) but not happened when we are pointed to emulator (12 warnings and no any issue with Xamarin.Shared.Targets)

### Steps to Reproduce

1. Set as the start-up project to Xamarin.iOS
2. Set mode to debug/release
3. Set the target device to iPhone / generic
4. Rebuild All the application

### Expected Behavior
When Rebuild All - it should no 550 warning was raised from Xamarin.Shared.Targets

### Actual Behavior
when rebuilding all - it should no warning from Xamarin.Shared.Targets (550 warnings)
### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.19 (build 2)
Installation UUID: 6fa2d55f-edd0-44bb-9145-0b78313531e7
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000162

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.162 (2020-02/2ca650f1f62) (64-bit)
	Package version: 612000162

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/sdk/5.0.405/Sdks
SDK Versions:
	5.0.405
	5.0.402
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.416
	3.1.414
	3.1.413
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.701
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.14
	5.0.11
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.22
	3.1.20
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12

=== .NET Core 3.1 SDK ===

SDK: 3.1.416

=== .NET 5.0 SDK ===

SDK: 5.0.405

=== Xamarin Designer ===

Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 02:44:16 UTC

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 13.2.1 (19586)
Build 13C100

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 15.6.0.3 (Visual Studio Community)
Hash: caa899d24
Branch: d17-1
Build date: 2022-01-16 21:16:56-0500

=== Xamarin.Android ===

Version: 12.0.0.3 (Visual Studio Community)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Users/kok.sang/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

=== Eclipse Temurin JDK ===

Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:52 UTC

=== Build Information ===

Release ID: 810190002
Git revision: 632b6ca654e2733a685bfc9c6a0686e0a317092b
Build date: 2022-02-09 13:38:14-05
Build branch: release-8.10

=== Operating System ===

Mac OS X 11.6.2
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Wed Nov 10 22:23:07 PST 2021
    root:xnu-7195.141.14~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Android Signature Tool 2.2.0


```

### Example Project (If Possible)
When Build with Device = EMULATOR, Warning show = 12

![image](https://user-images.githubusercontent.com/3633650/154414241-7ee36b4c-87ec-4ca7-8446-a31b0857dfff.png)

When Build With Device = Iphone, Warning show = 550, Xamarin.Shared.Targets
![image](https://user-images.githubusercontent.com/3633650/154414589-6f96e62f-a9d7-4bb5-80a7-c311dbd1d7a2.png)

**Comment by chamons** [comment] 2022-03-29 18:40
Thanks for the report and apologies for the delay in response.

This issue is a duplicate of https://github.com/xamarin/xamarin-macios/issues/13652 

I will close duplicate, please follow that issue for updates.

As noted there:

> The warning is harmless, it happens when we call dsymutil to create debug info (.dSYM directory) for the framework in question, and it's dsymutil telling us that it can't find some of the symbol information. The only problem that can occur with this warning is that crash reports that contain stack frames from the framework won't be fully symbolicated.

**Closed by chamons** 2022-03-29 18:40 UTC
