### ISSUE TITLE
System.IndexOutOfRangeException thrown when using UIApplication.SharedApplication.Windows[0].SafeAreaInsets.Top and deploying to iOS 13

### ISSUE THREAD

**Issue by walterthelapcat** [xamarin/xamarin-macios#7110] opened 2019-09-26 05:25 UTC
Apologies if I'm not doing this right, this is my first issue report.

I am building the sample Xamarin.iOS application from Microsoft Learn, located [here](https://docs.microsoft.com/en-us/learn/modules/introduction-to-xamarin-ios/8-exercise-add-ui-and-behavior-to-a-tip-calculator-app). There appear to be an issue with one of the lines of code in the example. It works when I deploy to an iOS 12.2 simulator, but throws an error when deploying to iOS 13.

### Steps to Reproduce

1. Build the project from Microsoft Learn ([source code here](https://github.com/MicrosoftDocs/mslearn-xamarin-ios-intro/tree/master/src/exercise2/final)).
2. Deploy to iOS 13 simulator

### Expected Behavior
App deploys without any issues.

### Actual Behavior
System.IndexOutOrRangeException (Index was outside the bounds of the array) is thrown on this line: 

`var topPadding = UIApplication.SharedApplication.Windows[0].SafeAreaInsets.Top;`

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.3 (build 1805)
Installation UUID: b4290957-8e74-43b1-a5ad-71fc691ca9fe
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000198

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.198 (2019-06/fe64a4765e6) (64-bit)
	Package version: 604000198

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Version: 3.0.100
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.1.13

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 10.0.0.43 (Visual Studio Community)
Commit: xamarin-android/d16-3/8af1ca8
Android SDK: /Users/treyudy/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-06@7af64d1ebe9
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/treyudy/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:42:44 UTC

=== Android Device Manager ===

Version: 1.2.0.115
Hash: 724ea69
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:43:06 UTC

=== Apple Developer Tools ===

Xcode 11.0 (14936)
Build 11A420a

=== Xamarin.Mac ===

Version: 6.2.0.42 (Visual Studio Community)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

=== Xamarin.iOS ===

Version: 13.2.0.42 (Visual Studio Community)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

=== Xamarin Designer ===

Version: 16.3.0.230
Hash: bbe518670
Branch: remotes/origin/d16-3-xcode11
Build date: 2019-09-17 18:39:30 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803001805
Git revision: df50511ccb08d4d84a53939f1d7fc0b40cbb0ee1
Build date: 2019-09-20 16:10:55+00
Build branch: release-8.3
Xamarin extensions: da8d448cd65f2cc87c5e6dc7e2c2ca7b96d20c72

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64


```

### Build Logs

[build_log.txt](https://github.com/xamarin/xamarin-macios/files/3656026/build_log.txt)

### Example Project (If Possible)

[Xamarin.iOS Microsoft Tutorial code](https://docs.microsoft.com/en-us/learn/modules/introduction-to-xamarin-ios/8-exercise-add-ui-and-behavior-to-a-tip-calculator-app)

**Comment by chamons** [comment] 2019-09-26 16:43
Thanks for the report!

I've passed it on to @patridge for consideration, who's logged it in their system.

Since the bug isn't in the SDK, I'm going to close this issue. Please feel free to reach out if you have any questions.

**Closed by chamons** 2019-09-26 16:43 UTC

**Comment by patridge** [comment] 2019-09-26 18:54
Just to bring my results back to this public front, I am unable to reproduce this issue at all with the 13.0 iOS simulators. I have tested it on the **iPhone 8 iOS 13.0** and **iPhone 11 iOS 13.0** simulator variants.

@walterthelapcat Do you have any more details on what simulator you were running or anything special you had set up in your simulator before encountering the error?

**Comment by walterthelapcat** [comment] 2019-09-26 23:17
@patridge The setup I was using was the out of the box iOS 13 iPhone 11 simulator. Nothing special or custom about it.

Screenshot of error: 
<img width="1680" alt="Screen Shot 2019-09-26 at 4 10 51 PM" src="https://user-images.githubusercontent.com/11891017/65730910-6cf1e400-e078-11e9-8358-1e1c5f127d02.png">

Screenshot of same code running on iOS 12.2 iPhone X simulator:
<img width="1680" alt="Screen Shot 2019-09-26 at 4 14 58 PM" src="https://user-images.githubusercontent.com/11891017/65731043-f0abd080-e078-11e9-8d55-eaef7b47e721.png">

**Comment by patridge** [comment] 2019-09-29 22:03
Thank you so much for following up with this. I really appreciate the help, and I'm hoping we can get the issue resolved.

Since I can't seem to reproduce this issue, I'd really like to learn a little more about the state of things when that error happens. Is there any chance you could add another line right before that `var topPadding` one to see if it blows up the same way? (In other words, move the current line 23 to line 24, and make this line execute first.)

```cs
var keyWindowTest = UIApplication.SharedApplication.KeyWindow.SafeAreaInserts.Top;
```

The `Windows[0]` isn't as elegant as it could be, but I can't figure out why it wouldn't also work. This `KeyWindow` version shouldn't work either if there isn't a single window in the `Windows` array, but it will rule out one possible issue. If the new line works and it gets past it to blow up back on the `Windows[0]` line, I might have to file a bug with the Xamarin.iOS project itself. If it doesn't work, I have more to learn about how Xamarin.iOS and/or iOS is getting the current windows.

**Comment by patridge** [comment] 2019-09-29 22:07
@walterthelapcat Actually, it's looking like `KeyWindow` might be deprecated. So, I'm not even sure if it's available still.
https://developer.apple.com/documentation/uikit/uiapplication#1656986

**Comment by bash862** [comment] 2019-10-09 10:28
if can help i solved this error with removing the option "Supports multiple windows" in the file "info.plist"
![image](https://user-images.githubusercontent.com/51796195/66473806-ebdb1980-ea87-11e9-8a64-7e5d23c75092.png)

**Comment by patridge** [comment] 2019-10-09 14:47
@bash862 Thank you for sharing that. I haven't even played with that setting yet, but clearly I need to. I'll see if I can find a better solution for when that checkbox _is_ checked.

**Comment by patridge** [comment] 2019-10-09 16:35
Thanks again, @bash862. I can confirm that enabling that checkbox will cause the error @walterthelapcat was seeing. I was trying to reproduce it using the completed exercise from the Microsoft Learn module they were mentioning, which was created before that plist value was available/set.

**Comment by patridge** [comment] 2019-10-09 18:14
In the latest Forms templates [on VS Mac, at least] they no longer leave the **Supports multiple windows** box checked. So, it shouldn't affect folks following along with the Introduction to Xamarin.iOS module on Microsoft Learn.

**Comment by JulesMoorhouse** [comment] 2020-09-02 07:58
@patridge I'm still getting this issue, but for Visual Studio for Mac.

It's following the same tutorial, shown in the screenshot above
https://docs.microsoft.com/en-us/learn/modules/introduction-to-xamarin-ios/8-exercise-add-ui-and-behavior-to-a-tip-calculator-app

![image](https://user-images.githubusercontent.com/361024/91954255-7b6d6480-ecf9-11ea-8fd2-4b9874e1c880.png)

Here's my app delegate...

![image](https://user-images.githubusercontent.com/361024/91954410-aeaff380-ecf9-11ea-98a1-b20da8a7a6db.png)

I've unchecked the **Supports multiple windows** option.

![image](https://user-images.githubusercontent.com/361024/91954906-5a594380-ecfa-11ea-8416-7f49a0f67bc1.png)

I've just installed the latest version VS-M last and Xcode on a new machine last week.

Can you please advise further ?

**Comment by micheleissa** [comment] 2021-02-21 21:58
This is still not working on iOS 14 and up......
