### ISSUE TITLE
Crash when using CreateDelegate and OpenTK Color4

### ISSUE THREAD

**Issue by swoolcock** [xamarin/xamarin-macios#5427] opened 2019-01-17 12:29 UTC
Xamarin.iOS apps can hard crash when using `CreateDelegate` and certain generic method signatures.  I have only been able to reproduce this using the `Color4` struct from our OpenTK fork (renamed to osuTK to avoid namespace conflicts with the OpenTK provided in Xamarin.iOS).

Crashes seem to occur when the method signature has at least two generic arguments and ends in a floating point type. The return type does not seem to make a difference.

Signatures that crash:
* `(TValue, TValue, double)`
* `(TValue, TValue, float)`
* `(double, double, double, double, TValue, TValue, double)`

Signatures that work:
* `(TValue)`
* `(TValue, double)`
* `(TValue, TValue)`
* `(TValue, TValue, int)`
* `(TValue, TValue, long)`
* `(double, TValue)`
* `(double, TValue, TValue)`
* `(double, double, double, double, TValue, TValue)`

Workaround PR: https://github.com/ppy/osu-framework/pull/2088

Context: https://github.com/ppy/osu-framework/blob/master/osu.Framework/MathUtils/Interpolation.cs

`Color4`: https://github.com/ppy/osuTK/blob/netstandard/src/osuTK/Graphics/Color4.cs

### Steps to Reproduce

1. Use reflection and `CreateDelegate` to get a reference to a static method using particular generic parameters
2. Call the reflected delegate through an intermediary generic class, specifically for the `Color4` struct

See `AppDelegate.cs` in the provided test project for a full example.

### Expected Behavior

The reflected method is successfully called.

### Actual Behavior

A crash in native code:
`error: * Assertion: should not be reached at ../../../../../mono/mini/mini-arm64-gsharedvt.c:119`

### Environment

```
Visual Studio Community 2017 for Mac (Preview)
Version 7.8 Preview (7.8 build 1471)
Installation UUID: 43aef541-5456-472a-a6a9-d639caaf3ce9
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.2.1.12 ( / 65ec520f)

	Package version: 516000221

Mono Framework MDK
Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

NuGet
Version: 4.8.0.5385

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.0
	2.1.2
	2.1.1
	2.1.0
	2.0.6
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.2.101/Sdks
SDK Versions:
	2.2.101
	2.1.302
	2.1.301
	2.1.300
	2.1.104
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 9.1.4.2 (Visual Studio Community)
Android SDK: /Users/samah/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 25.1.2
SDK Platform Tools Version: 24.0.0
SDK Build Tools Version: 23.0.2

Microsoft Mobile OpenJDK
Java SDK: /Users/samah/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
1.8.0-9
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 7.8.1.0
Hash: 06ceaea1

Apple Developer Tools
Xcode 10.1 (14460.46)
Build 10B61

Xamarin.Mac
Version: 5.2.1.12 (Visual Studio Community)
Hash: 65ec520f
Branch: 
Build date: 2018-12-05 12:06:09-0500

Xamarin.iOS
Version: 12.2.1.12 (Visual Studio Community)
Hash: 65ec520f
Branch: d15-9
Build date: 2018-12-05 12:06:09-0500

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 708001471
Git revision: 088a080b35e6b334bf6b67256bb93ebfc1ec0903
Build date: 2018-12-17 18:14:14+00
Build branch: release-7.8-p1
Xamarin extensions: 6cffe6d190fbe788ac62840d29f6d0ff6956052d

Operating System
Mac OS X 10.14.0
Darwin 18.0.0 Darwin Kernel Version 18.0.0
    Wed Aug 22 20:13:40 PDT 2018
    root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
```

### Build Logs

https://gist.github.com/swoolcock/e43726f8202ca0e1f79f9ca72ab2f51e

### Example Project (If Possible)

[CrashTest.zip](https://github.com/xamarin/xamarin-macios/files/2768582/CrashTest.zip)

https://github.com/swoolcock/xamarin-color4-crash

**Comment by spouliot** [comment] 2019-01-17 15:18
I get the same crash with stable (12.2.1.12 / d15-9) but it works fine with master, so the fix is already present in the newer mono (2018-08 vs 2018-04)

Closing as already fixed. You might want to update to 16.0 preview #2 (available soon) or take a build directly from our bots if the issue is blocking you.

**Closed by spouliot** 2019-01-17 15:18 UTC
Labels: bug, iOS

**Comment by swoolcock** [comment] 2019-01-18 05:00
Tested with 12.7.0.74, crash is fixed.  Thanks.  ;)

**Comment by spouliot** [comment] 2019-01-18 14:35
@swoolcock thanks for confirming it!
