### ISSUE TITLE
Some shipped assemblies in mobile profile are not properly strong-named

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#6459] opened 2019-06-28 17:17 UTC
_From @garuma on Tue, 25 Jun 2019 13:54:15 GMT_

Versions:
- Xamarin.iOS 12.14.0.87 (72c4a8ab9045f809eda72bf8416043bceb036629)
- mono 2019-02

The following assemblies (at least) that are shipped as part of Xamarin.iOS are not properly strong-named but instead have been left with the delay-signed flag on which trips a sign check on the Visual Studio side:

- system.drawing.common.dll
- system.net.http.dll
- system.numerics.dll

Invoking `sn -v` on them yields:

```
Assembly ./lib/mono/Xamarin.iOS/System.Numerics.dll is delay-signed but not strongnamed
```

_Copied from original issue mono/mono#15398_

**Comment by chamons** [comment] 2019-06-28 17:17
_From @marek-safar on Wed, 26 Jun 2019 09:12:58 GMT_

@akoeplinger thoughts on this?

/cc @steveisok

**Comment by chamons** [comment] 2019-06-28 17:17
_From @akoeplinger on Fri, 28 Jun 2019 10:18:44 GMT_

I checked the assemblies on the Mono side and they are correctly strong named and not delay-signed.

What seems to happen is that Xamarin.iOS is re-signing the assemblies with their own key here: https://github.com/xamarin/xamarin-macios/blob/d16-2/builds/Makefile#L676-L678

This makes the assemblies delay-signed. What I don't understand is why only the three files are tripping up the sign check in VS since _all_ of the BCL assemblies are processed this way and have been for the last couple releases as far as I can see.

Note: this is no longer an issue for Mono in d16-3 since the BCL assemblies are consumed as-is from Mono. The Xamarin.iOS.dll however is still delay-signed.

**Comment by chamons** [comment] 2019-06-28 17:21
cc @rolfbjarne

**Comment by rolfbjarne** [comment] 2019-06-28 17:33
@chamons apparently this is not an issue in master/d16-3, so is it enough of an issue for us to spend time on it for d16-2?

**Comment by chamons** [comment] 2019-06-28 17:34
That is an open question, I'm getting the answers now. Assume not unless you hear otherwise.

**Comment by chamons** [comment] 2019-07-26 19:48
This did not make the d16-2 bar, and since it's fixed in d16-3 it is being closed.

**Comment by chkn** [comment] 2019-08-07 16:16
Looks like this was not fixed in 16.3? https://devdiv.visualstudio.com/DevDiv/_workitems/edit/959536

**Comment by chkn** [comment] 2019-08-12 18:49
In addition to the assemblies mentioned in the original description, I'm seeing new bugs with the following assemblies listed:

- system.componentmodel.composition.dll
- system.data.dll
- system.transactions.dll
- system.web.services.dll

**Comment by marek-safar** [comment] 2019-08-12 18:53
@akoeplinger could you confirm the changes were made on Mono side?

/cc @steveisok

**Comment by spouliot** [comment] 2019-08-13 18:29
@chkn can you please clarify if this happens (or not) with d16-3 after the mono 2019-06 bump (i.e. preview 2) ?

If that's only with `d16-2` then can you build from an `xcode11` (open branch) package to confirm a fix ? no PR yet, asking first :)

**Comment by chkn** [comment] 2019-09-11 10:46
> @chkn can you please clarify if this happens (or not) with d16-3 after the mono 2019-06 bump (i.e. preview 2) ?

It appears the issue is fixed for BCL assemblies after that bump, but not for `Xamarin.Mac.dll` nor `Xamarin.iOS.dll`, which still report as delay-signed but not strongnamed ([build PR](https://github.com/xamarin/designer/pull/2280))

> If that's only with d16-2 then can you build from an xcode11 (open branch) package to confirm a fix ? no PR yet, asking first :)

As mentioned in email, the Xcode 11 build did not have the fix, but happy to try again once that's merged into d16-3 (or wherever).

**Comment by chamons** [comment] 2019-09-17 21:39
@chkn - Try the latest d16-3, which has Xcode 11 merged in, and report back.

**Comment by chkn** [comment] 2019-10-23 15:23
Just pulled the latest from our d16-4 release branch, and things look greatly improved. The following assemblies are the only ones still reporting delay-signed but not strongnamed:

- Xamarin.Mac.dll
- Xamarin.iOS.dll
- Xamarin.TVOS.dll

However this seems to be fine for our purposes at the moment.

**Comment by chamons** [comment] 2019-10-23 15:35
@chkn - Can we close this or do we still need it open?

**Comment by chkn** [comment] 2019-10-24 21:28
I think we can close this. Will reopen if need be.

**Closed by chkn** 2019-10-24 21:28 UTC
Labels: bug, iOS, macOS
