### ISSUE TITLE
NSColorPanel make crash with macOS 11 (BigSur)

### ISSUE THREAD

**Issue by simeon052** [xamarin/xamarin-macios#9484] opened 2020-08-25 06:27 UTC
When I opened NSColorPanel, application was dead with BigSure.

Sample code is there.
https://github.com/simeon052/colorpanal

Crash is happed on color store .
I added demo movie on my sample project.
https://github.com/simeon052/colorpanal/blob/master/Screen Recording 2020-08-25 at 0.05.28.mov

Sample works well with 10.15.
This issue only occurs when /Users/<username>/Library/Colors/NSColorPanelSwatches.plist doesn’t exist.
If file is there already, sample code works well. 

### Steps to Reproduce
Delete /Users/<username>/Library/Colors/NSColorPanelSwatches.plist at first.

1. Build sample app
2. Push button
3. Store color as attached movie.

https://github.com/simeon052/colorpanal/blob/master/Screen Recording 2020-08-25 at 0.05.28.mov

### Expected Behavior
Can store color

### Actual Behavior
Crash

### Environment
Xamarin.Mac 6.20.2.2

**Comment by whitneyschmidt** [comment] 2020-09-01 20:45
@simeon052 Thank you for your feedback!

I was able to reproduce the issue you reported in Objective-C with no Xamarin code involved. Here's the sample project I created: [colorpanel.zip](https://github.com/xamarin/xamarin-macios/files/5158739/colorpanel.zip)

The best path forward would be to file a radar directly with Apple: https://developer.apple.com/bug-reporting/

The crash after deleting /Users//Library/Colors/NSColorPanelSwatches.plist and following the instructions you provided produced the following output:

2020-09-01 16:26:09.027729-0400 colorpanel[1908:73021] Metal API Validation Enabled
Assertion failed: (backingScaleFactor > 0.f), function drawnFocusRingBitmapForTime, file /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-2006.102/AppKit.subproj/NSAutomaticFocusRing.m, line 306.
Assertion failed: (backingScaleFactor > 0.f), function drawnFocusRingBitmapForTime, file /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-2006.102/AppKit.subproj/NSAutomaticFocusRing.m, line 306.
(lldb)

Closing since this is an Apple issue and unrelated to Xamarin.

**Closed by whitneyschmidt** 2020-09-01 20:45 UTC
