### ISSUE TITLE
Error "Could not AOT the assembly" again with vs2019

### ISSUE THREAD

**Issue by TomQv** [xamarin/xamarin-macios#5914] opened 2019-04-17 18:50 UTC
this was already fixed with the last vs2018, but now #4012 is back with vs2019mac

**Comment by chamons** [comment] 2019-04-18 16:44
@TomQv I'm sorry you've run into an issue with ahead of time compilation.

However, despite the fact that they have the same error message, the underlying cause might be very different. Any number of failures in the compiler might trigger it.

Could you please attach a full build log, and at minimum the binaries being compiled. A full project is preferable, but sometimes difficult to create.

**Comment by TomQv** [comment] 2019-04-18 16:49
I can't provide binaries or project, because its a very big project.
Can only say, that everything was fine with the latest Xamarin.IOS from VS2017.
After upgrading to VS2019, without changing anything on the project or sources, this error occurs.

How do I create a full build log ?

**Comment by chamons** [comment] 2019-04-18 16:52
https://docs.microsoft.com/en-us/xamarin/cross-platform/troubleshooting/questions/version-logs#verbose-build-output-logs

Without at least the assembly being AOT'ed and its dependencies, it may be difficult to fix.

**Comment by TomQv** [comment] 2019-04-19 07:42
Thanks Chris for taking care of the issue.
Attached is the full debug-build output and that specific osmsharp.dll, which could not AOT. 

[could_not_aot_osmsharp.zip](https://github.com/xamarin/xamarin-macios/files/3097377/could_not_aot_osmsharp.zip)

**Comment by rolfbjarne** [comment] 2019-04-22 12:45
This looks like a duplicate of https://github.com/mono/mono/issues/14066:

> * Assertion at /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mono/mini/decompose.c:1469, condition `cfg->cbb == first_bb' not met (TaskId:483)

That issue also contains an idea for how to work around this issue in your codebase.

**Closed by rolfbjarne** 2019-04-22 12:45 UTC
Labels: bug, iOS, need-info

**Comment by TomQv** [comment] 2019-04-22 13:15
Thx, workaround is fine for me.

**Comment by joemather** [comment] 2019-05-03 20:33
Thank you @TomQv and @rolfbjarne.  Just upgraded to vs2019mac and ran into this issue.  Removing nested enums from generic classes fixed the problem.

**Comment by TomQv** [comment] 2019-05-03 20:46
My workaround was just to remove most of the code in that specific dll, because I don't need it anyway.
I'm still wondering, what "nested enums in generic classes" is.
Something like this is causing the error?
```
public class Foo<T>
{
    public enum Bar
    {
        A = 1,
        B = 2
    }
}
```
So change to this would also be a workaround?
```
public enum Bar
{
     A = 1,
     B = 2
}
public class Foo<T>
{
    
}
```

**Comment by joemather** [comment] 2019-05-03 21:06
@TomQv - Yes, that was the error scenario and the workaround.  Thanks again for shining some light on this issue!

**Comment by dktechindia** [comment] 2019-07-07 16:56
None of the above workaround worked for me. I have just upgraded to Catalina and issue starts.  Any workaround?

**Comment by chamons** [comment] 2019-07-08 16:02
@dktechindia Please file a new issue if you are having trouble, so we don't confuse history.
