### ISSUE TITLE
How to add a Notification Service Extension to a .NET6 iOS app

### ISSUE THREAD

**Issue by petro2050** [xamarin/xamarin-macios#17126] opened 2022-12-26 12:55 UTC
Can you please recommend how to add a Notification Service Extension project to a .NET6 iOS app? I haven't found a suitable template when I ran `dotnet new --list`.

```
iOS Application                               ios                         [C#]        iOS/Mobile                                               
iOS Binding Library                           iosbinding                  [C#]        iOS/Mobile                                               
iOS Class Library                             ioslib                      [C#]        iOS/Mobile                                               
iOS Controller                                ios-controller              [C#]        iOS/Mobile                                               
iOS Storyboard                                ios-storyboard              [C#]        iOS/Mobile                                               
iOS Tabbed Application                        ios-tabbed                  [C#]        iOS/Mobile                                               
iOS View                                      ios-view                    [C#]        iOS/Mobile                                               
iOS View Controller                           ios-viewcontroller          [C#]        iOS/Mobile   
```

**Comment by VladislavAntonyuk** [comment] 2023-01-01 22:14
You can use this guide: https://vladislavantonyuk.github.io/articles/Extend-.NET-MAUI-application-with-iOS-Extensions

or install templates: https://www.nuget.org/packages/VladislavAntonyuk.DotNetTemplates

**Comment by rolfbjarne** [comment] 2023-01-10 13:51
Closing, since this is a duplicate of #16127.

From a quick look @VladislavAntonyuk's guide seems like it should work as a workaround.

**Closed by rolfbjarne** 2023-01-10 13:51 UTC
