### ISSUE TITLE
Build fail after upgrading to Xcode 15

### ISSUE THREAD

**Issue by siddhant-maurya** [xamarin/xamarin-macios#19100] opened 2023-09-26 06:10 UTC
### Steps to Reproduce

1. Update Xcode to version 15
2. Update Mac VS to version 17.6.4
3. Update Mac OS to 13.6

### Expected Behavior
Xamarin forms iOS project should build.

### Actual Behavior
Build is Failing in Debug mode with error- Error MT4109: Failed to compile the generated registrar code.
In release mode building successfully

### Build Logs
 Compilation failed with code 1, command:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Wno-receiver-forward-class -Wno-objc-missing-super-calls -Wno-unguarded-availability-new -stdlib=libc++ -gdwarf-2 -std=c++14 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/16.4.0.6/SDKs/MonoTouch.iphonesimulator.sdk/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.0.sdk -Qunused-arguments -fobjc-legacy-dispatch -fobjc-abi-version=2 -mios-simulator-version-min=8.0 -arch x86_64 -c -o /Users/anishmacmini/Documents/GitHub/Landmark-Mobile/LandMarkHealth.Widget/obj/iPhoneSimulator/Debug/mtouch-cache/x86_64/registrar.o -x objective-c++ -D DEBUG /Users/anishmacmini/Documents/GitHub/Landmark-Mobile/LandMarkHealth.Widget/obj/iPhoneSimulator/Debug/mtouch-cache/registrar.m
    In file included from /Users/anishmacmini/Documents/GitHub/Landmark-Mobile/LandMarkHealth.Widget/obj/iPhoneSimulator/Debug/mtouch-cache/registrar.m:3:
    /Users/anishmacmini/Documents/GitHub/Landmark-Mobile/LandMarkHealth.Widget/obj/iPhoneSimulator/Debug/mtouch-cache/registrar.h:28:9: fatal error: 'NewsstandKit/NewsstandKit.h' file not found
    #import <NewsstandKit/NewsstandKit.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    MTOUCH : error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
Done building target "_CompileToNative" in project "LandMarkHealth.iOS.csproj" -- FAILED.

Done building project "LandMarkHealth.iOS.csproj" -- FAILED.

Build FAILED.

**Comment by dalexsoto** [comment] 2023-09-26 12:51
This is a duplicate of https://github.com/xamarin/xamarin-macios/issues/18964 please use the instructions on the first post to workaround this issue.

**Closed by dalexsoto** 2023-09-26 12:51 UTC
Labels: bug, iOS

**Comment by ziminny** [comment] 2023-09-28 00:39
I downloaded Symptom today and it was very slow, using the iOS 16.4 version solved it for me, look at this post I hope it helps.

https://medium.com/p/a320e47a81ca

**Comment by ziminny** [comment] 2023-09-28 00:40
I downloaded Symptom today and it was very slow, using the iOS 16.4 version solved it for me, look at this post I hope it helps.

https://medium.com/@ziminny/macos-sonoma-xcode-15-ios-17-bug-in-ios-version-emulator-and-preview-a320e47a81ca
