### ISSUE TITLE
MTLDevice.GetAllDevices incorrectly annotated on macOS

### ISSUE THREAD

**Issue by hamarb123** [xamarin/xamarin-macios#13540] opened 2021-12-13 08:37 UTC
### Steps to Reproduce

1. Make macOS project
2. Put line of code `MTLDevice.GetAllDevices()`

### Expected Behavior
No warning - see https://developer.apple.com/documentation/metal/1433367-mtlcopyalldevices - it supports macOS 10.11+ (it also says catalyst 13.0+, not 15.0+).

### Actual Behavior
<img width="788" alt="Screen Shot 2021-12-13 at 7 35 38 pm" src="https://user-images.githubusercontent.com/25316035/145778640-102e0ba3-76a6-488f-b390-10718f529b4c.png">

I believe this was caused by https://github.com/xamarin/xamarin-macios/commit/67e1ca5459b91e1c669b20edd9f0230c714b47af.

### Environment

```
Visual Studio Community 2022 for Mac Preview
Version 17.0 Preview (17.0 build 4729)
Installation UUID: a716094e-6740-4470-8c68-e1f80f14c356
	GTK+ 2.24.23

Mono Framework MDK
Runtime:
	Mono 6.12.0 (2020-02/5ce143a1a88) (64-bit)
	Package version: 612000158

Roslyn (Language Service)
4.1.0-1.21511.14+c09d760509f00afadf0fa9b6ee7d0c53b70943ca

NuGet
Version: 6.0.0.262

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.100/Sdks
SDK Versions:
	6.0.100
	5.0.403
	3.1.415
	3.0.103
	2.2.207
	2.1.818
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.0
	5.0.12
	3.1.21
	3.0.3
	2.2.8
	2.1.30

Xamarin.Profiler
Version: 1.7.0.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
A valid Xcode installation was not found at the configured location: '/Library/Developer/CommandLineTools'

Xamarin.Mac
Version: 8.2.0.1 (Visual Studio Community)
Hash: 8fd9e6289
Branch: xcode13.1
Build date: 2021-10-26 10:13:55-0400

Xamarin.iOS
Version: 15.2.0.1 (Visual Studio Community)
Hash: 8fd9e6289
Branch: xcode13.1
Build date: 2021-10-26 10:13:56-0400

Xamarin Designer
Version: 17.1.0.43
Hash: 1841a0e79
Branch: remotes/origin/main
Build date: 2021-11-04 15:16:29 UTC

Xamarin.Android
Version: 12.1.99.56 (Visual Studio Community)
Commit: xamarin-android/main/43243b4
Android SDK: /Users/Hamish/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0  (API level 23)
		12.0 (API level 31)
		11.0 (API level 30)
		9.0  (API level 28)

SDK Command-line Tools Version: 5.0
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/main@79744f61
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.36.0@a575761
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@a5194e9

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.1.0.14
Hash: 9c65d8a
Branch: remotes/origin/backport-pr-548-to-main~1
Build date: 2021-11-04 15:16:32 UTC

Android Device Manager
Version: 17.1.0.13
Hash: 1de1208
Branch: remotes/origin/anchimna/missingLibCmdtoolsFix~1
Build date: 2021-11-04 15:16:32 UTC

Build Information
Release ID: 1700004729
Git revision: 39b9401f81b4c2246a15990f370e17e42f6d74d0
Build date: 2021-11-04 11:15:22-04
Build branch: release-17.0

Operating System
Mac OS X 11.6.1
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Tue Oct 12 18:33:42 PDT 2021
    root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64
```

**Comment by rachelkang** [comment] 2021-12-13 17:39
Hi, @hamarb123 - thanks for the feedback.

Is your project running on .NET 6? If so, it looks like this issue may be a duplicate of https://github.com/xamarin/xamarin-macios/issues/10170. 
If not, please attach your project or a sample project reproducing the issue so that we can investigate further.

**Comment by rachelkang** [comment] 2021-12-14 14:32
Thanks for checking! I'll be closing this issue since it's a duplicate, but please feel free to track #10170 to remain updated on this issue.

**Closed by rachelkang** 2021-12-14 14:32 UTC
Labels: bug, need-info
