### ISSUE TITLE
Suddenly the source code stopped compiling into the release build

### ISSUE THREAD

**Issue by alex-dubatov** [xamarin/xamarin-macios#19371] opened 2023-10-29 14:43 UTC
Suddenly the source code stopped compile release build's.
Even those source code commits that were compiled before.
There may have been some kind of software update.

Now the compilation of the release build ends with errors such as:

> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.0.sdk/usr/include/simd/matrix.h(25,25): Error G3127DA5A: use of undeclared identifier 'vzip1q_f32'; did you mean 'vzipq_f32'? (G3127DA5A) (FF.Mobile.iOS)
> 
> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.0.sdk/usr/include/simd/matrix.h(17,17): Error G6D89C99D: no viable conversion from 'float32x4x2_t' to 'simd_float4' (vector of 4 'float' values) (G6D89C99D) (FF.Mobile.iOS)

Changing used XCode to version 14.3.1 propagate another error:

> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(3,3): Error: strip exited with code 72:
> xcrun: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find strip 2> /dev/null' failed with exit code 16384: (null) (errno=Invalid argument)
> xcrun: error: unable to find utility "strip", not a developer tool or in PATH (FF.Mobile.iOS)

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.6.6 (build 408)
Installation UUID: 4fe82bc7-1447-4218-bbf1-498b1d80b0b7

Runtime
.NET 7.0.3 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.310/Sdks
SDK Versions:
	7.0.310
	7.0.307
	7.0.306
	7.0.304
	7.0.203
	7.0.202
	7.0.201
	7.0.200
	7.0.102
	7.0.101
	7.0.100
	6.0.416
	6.0.413
	6.0.412
	6.0.410
	6.0.408
	6.0.407
	6.0.406
	6.0.405
	6.0.404
	6.0.403
	6.0.402
	6.0.401
	6.0.400
	6.0.302
	6.0.301
	6.0.300
	6.0.203
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	6.0.416
	6.0.413
	6.0.412
	6.0.410
	6.0.408
	6.0.407
	6.0.406
	6.0.405
	6.0.404
	6.0.403
	6.0.402
	6.0.401
	6.0.400
	6.0.302
	6.0.301
	6.0.300
	6.0.203
	5.0.408
	5.0.406
	3.1.426
	3.1.425
	3.1.424
	3.1.423
	3.1.422
	3.1.421
	3.1.420
	3.1.419
	3.1.417

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.13
	7.0.10
	7.0.9
	7.0.7
	7.0.5
	7.0.4
	7.0.3
	7.0.2
	7.0.1
	7.0.0
	6.0.24
	6.0.21
	6.0.20
	6.0.18
	6.0.16
	6.0.15
	6.0.14
	6.0.13
	6.0.12
	6.0.11
	6.0.10
	6.0.9
	6.0.8
	6.0.7
	6.0.6
	6.0.5

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.24
	6.0.21
	6.0.20
	6.0.18
	6.0.16
	6.0.15
	6.0.14
	6.0.13
	6.0.12
	6.0.11
	6.0.10
	6.0.9
	6.0.8
	6.0.7
	6.0.6
	6.0.5
	5.0.17
	5.0.15
	3.1.32
	3.1.31
	3.1.30
	3.1.29
	3.1.28
	3.1.27
	3.1.26
	3.1.25
	3.1.23

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode: 15.0.1 22266
Build: 15A507

Xamarin.Mac
Version: 9.3.0.18 Visual Studio Community
Hash: 9d266025e
Branch: xcode14.3
Build date: 2023-09-06 19:52:26-0400

Xamarin.iOS
Version: 16.4.0.18 Visual Studio Community
Hash: 9d266025e
Branch: xcode14.3
Build date: 2023-09-06 19:52:27-0400

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2023-10-23 17:41:00 UTC

Xamarin.Android
Version: 13.2.2.0 (Visual Studio Community)
Commit: xamarin-android/d17-5/45b0e14
Android SDK: Not found

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2023-10-23 17:41:04 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2023-10-23 17:41:04 UTC

Build Information
Release ID: 1706060408
Git revision: 3912eca6712af97335aa3a782abaa75ff86ec74a
Build date: 2023-10-23 17:39:03+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 13.6.0
Darwin 22.6.0 Darwin Kernel Version 22.6.0
    Fri Sep 15 13:41:30 PDT 2023
    root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T8103 arm64

Enabled user installed extensions
Project System Tools 0.13


```

</details>

### Build Logs

[FF.Mobile.iOS_Release_iPhone_Build_2023-10-29T14_03_52.4166050Z.msbuild.log](https://github.com/xamarin/xamarin-macios/files/13198305/FF.Mobile.iOS_Release_iPhone_Build_2023-10-29T14_03_52.4166050Z.msbuild.log)

**Comment by Jones-Abramoff** [comment] 2023-10-29 18:10
I have exactly the same problem

**Comment by Jones-Abramoff** [comment] 2023-11-01 07:14
I couldn't wait for the fix so I renamed Xcode.app to Xcode1501.app, downloaded XCode 14.3.1, and followed the instructions at https://stackoverflow.com/questions/76958016/is-there-a-way-to-run-xcode-14-on-macos-sonoma.

**Comment by yaliashkevich** [comment] 2023-11-01 11:20
> I have no problems building it on local workstation (Intel) xcode15/macOS 13.5
that is not true actually, if you try to make release build with linking it fails.
Looks like here is a workaround
https://github.com/xamarin/xamarin-macios/issues/19228

**Comment by yaliashkevich** [comment] 2023-11-01 15:13
And it looks to be fixed in xcode 15.1, works well on beta without applying workaround above.

**Comment by rolfbjarne** [comment] 2023-11-02 13:02
> Error G3127DA5A: use of undeclared identifier 'vzip1q_f32'; did you mean 'vzipq_f32'?

This happens because Xcode 15 has broken header files when it comes to compiling for armv7.

See https://github.com/xamarin/xamarin-macios/issues/19257#issuecomment-1770437569 for more info.

The fix/workaround is to remove `ARMV7` from the `MtouchArch` property in your project file.

Closing as a duplicate of #19257.

**Closed by rolfbjarne** 2023-11-02 13:02 UTC

**Comment by alex-dubatov** [comment] 2023-11-03 10:38
@rolfbjarne For ARMV7s also build failed. So I just set only ARM64 and then build succeeded.

**Comment by Vlasenkoip** [comment] 2023-11-17 16:59
It turns out that neither Mac nor xcode can be updated to support xamarin applications?
This is very sad.
Last time I downloaded version 14.2 separately from the latest one only for xamarin, now neither it nor 14.3.1 allows you to build iOS applications..
