### ISSUE TITLE
Can't AOT-compile 32-bit iOS apps on Catalina

### ISSUE THREAD

**Issue by dktechindia** [xamarin/xamarin-macios#6566] opened 2019-07-11 23:27 UTC
### Steps to Reproduce

1. Create any Xamarin.Forms project with VS 2019 community and connect to mac with OS Catalina
2. Set the Build to release and iPhone as device
3. Rebuild the project and could not AOT error comes out

### Expected Behavior
Project should build successfully and ipa file should be generated
### Actual Behavior
throws build error for AOT
### Environment

```
Microsoft Visual Studio Community 2019
Version 16.1.6
VisualStudio.16.Release/16.1.6+29102.190
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA114
Microsoft Visual C++ 2019

Application Insights Tools for Visual Studio Package   9.1.00429.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.1.429.50124
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2012   16.1.429.50124
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2019   16.1.429.50124
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.1.429.50124
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.1.429.50124
Azure Functions and Web Jobs Tools

C# Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.77 (master@24013d5)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub.VisualStudio   2.9.1.7781
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

GitLab Extension for Visual Studio   1.0.189
A Visual Studio Extension that brings the GitLab Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20419.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.1.1 (2473f22)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.10424.1 Commit Hash:c3ce0ae0b29c0b3a755ffc12f8a685fe7ddd3600
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61904.23160
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

TypeScript Tools   16.0.10506.2004
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.28917
Visual C++ for Linux Development

Visual F# Tools 10.4 for F# 4.6   16.1.0-beta.19253.3+42526fe359672a05fd562dc16a91a43d0fe047a7
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.1.0.545 (d16-1@db7c858e8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.1.0.418 (remotes/origin/d16-1@5b958bb10)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.2.112 (4db4af4)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.3.0.23 (HEAD/d0b48056f)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2018-08@3a07bd426d3
    Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
    LibZipSharp: grendello/LibZipSharp/d16-1@44de300
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26


Xamarin.iOS and Xamarin.Mac SDK   12.10.0.157 (6bd9475)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Build Logs

[BuildLogs.txt](https://github.com/xamarin/xamarin-macios/files/3384329/BuildLogs.txt)

### Example Project (If Possible)

> VS bug [#948442](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/948442)

**Comment by chamons** [comment] 2019-07-16 16:58
Sections of the log:

```
2>"C:\Projects\Personal\myApp.iOS\myAppiOS.iOS.csproj" (Rebuild;BuiltProjectOutputGroup;BuiltProjectOutputGroupDependencies;DebugSymbolsProjectOutputGroup;DebugSymbolsProjectOutputGroupDependencies;DocumentationProjectOutputGroup;DocumentationProjectOutputGroupDependencies;SatelliteDllsProjectOutputGroup;SatelliteDllsProjectOutputGroupDependencies;SGenFilesOutputGroup;SGenFilesOutputGroupDependencies target) (1) ->
2>(_CompileToNative target) -> 
2>  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(797,3): error MT3001: Could not AOT the assembly '/Users/kumardh/Library/Caches/Xamarin/mtbs/builds/myAppiOS.iOS/20120f7877426a870f29973b0b01cf4e/obj/iPhone/Release/mtouch-cache/32/3-Build/myApp.iOS.exe'
```
```
2>  MONO_PATH=/Users/kumardh/Library/Caches/Xamarin/mtbs/builds/myAppiOS.iOS/20120f7877426a870f29973b0b01cf4e/obj/iPhone/Release/mtouch-cache/32/3-Build /Library/Frameworks/Xamarin.iOS.framework/Versions/12.10.0.157/bin/arm-darwin-mono-sgen --debug -O=gsharedvt -O=-float32  --aot=mtriple=armv7s-ios,data-outfile=/Users/kumardh/Library/Caches/Xamarin/mtbs/builds/myAppiOS.iOS/20120f7877426a870f29973b0b01cf4e/obj/iPhone/Release/mtouch-cache/armv7s/Newtonsoft.Json.aotdata.armv7s,static,asmonly,direct-icalls,full,nodebug,dwarfdebug,msym-dir=/Users/kumardh/Library/Caches/Xamarin/mtbs/builds/myAppiOS.iOS/20120f7877426a870f29973b0b01cf4e/obj/iPhone/Release/mtouch-cache/32/3-Build/Msym,outfile=/Users/kumardh/Library/Caches/Xamarin/mtbs/builds/myAppiOS.iOS/20120f7877426a870f29973b0b01cf4e/obj/iPhone/Release/mtouch-cache/armv7s/Newtonsoft.Json.dll.s "/Users/kumardh/Library/Caches/Xamarin/mtbs/builds/myAppiOS.iOS/20120f7877426a870f29973b0b01cf4e/obj/iPhone/Release/mtouch-cache/32/3-Build/Newtonsoft.Json.dll" (TaskId:294)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(797,3): error MT3001: Could not AOT the assembly '/Users/kumardh/Library/Caches/Xamarin/mtbs/builds/myAppiOS.iOS/20120f7877426a870f29973b0b01cf4e/obj/iPhone/Release/mtouch-cache/32/3-Build/myApp.iOS.exe'
```

**Comment by rolfbjarne** [comment] 2019-07-22 07:43
This is because the 32-bit AOT compiler is a 32-bit executable, which won't work on Catalina.

This will be fixed in d16-3.

**Closed** 2019-07-22 07:45 UTC
Labels: external-xamarin-vs

**Comment by se** [comment] 2019-08-08 18:09
@rolfbjarne, Is there any way to get this update early? I kinda stuck, and don't want to go back to Mojave.

**Comment by chamons** [comment] 2019-08-08 18:36
If you want to try a d16-3 build, you can follow the instructions here:

https://github.com/xamarin/xamarin-macios/wiki#downloading-a-build

Currently that's:

https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/d16-3/53979af5a8a786980cb0962eae09549e57d020db/28/package/xamarin.ios-12.16.1.12.pkg

Or you could try the preview channel, that may have a new enough build as well.

**Comment by se** [comment] 2019-08-09 10:08
I'm already using preview channel @chamons. But it didn't work either. I'll try these options also and put the result here...

**Comment by se** [comment] 2019-08-09 10:39
> If you want to try a d16-3 build, you can follow the instructions here:
> 
> [xamarin/xamarin-macios/wiki#downloading-a-build](https://github.com/xamarin/xamarin-macios/wiki#downloading-a-build)
> 
> Currently that's:
> 
> [bosstoragemirror.blob.core.windows.net/wrench/jenkins/d16-3/53979af5a8a786980cb0962eae09549e57d020db/28/package/xamarin.ios-12.16.1.12.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/d16-3/53979af5a8a786980cb0962eae09549e57d020db/28/package/xamarin.ios-12.16.1.12.pkg)
> 
> Or you could try the preview channel, that may have a new enough build as well.

This is old one. I installed it but still same (and even worse).

My version is;

```
Xamarin.iOS
Version: 12.99.2.40 (Visual Studio Community)
Hash: d883febf
Branch: xcode11
Build date: 2019-08-06 08:33:40-0400
```

The version that you sent;

```
Xamarin.iOS
Version: 12.16.1.12 (Visual Studio Community)
Hash: 53979af5
Branch: d16-3
Build date: 2019-08-05 11:05:36-0400
```

**Comment by chamons** [comment] 2019-08-09 16:09
If you compare the branches, one is xcode11 and one is d16-3. The numbers don't line up because of that. 

xcode11 should work for sure, @se please open an issue with full steps to reproduce, bug log, and example project.

**Comment by kryslt** [comment] 2020-02-18 14:15
For me it was wrong "Linker Behavior" setting (iOS properties => iOS Build) that had to be set to "Link Framework SDKs Only".
