### ISSUE TITLE
[iOS] Path too long for MAUI device connected deploys using Sentry.Maui

### ISSUE THREAD

**Issue by espenrl** [xamarin/xamarin-macios#18259] opened 2023-05-10 21:31 UTC
NOTE: This is a compound issue by Sentry NuGet having files in a deep folder structure and MAUI SDK tooling generating longer paths than needed.

### Steps to Reproduce

Setup MAUI .NET 7 service release 6 with Sentry and deploy from Visual Studio to a usb connected IPhone.

https://www.nuget.org/packages/Sentry.Maui

### Expected Behavior

Deployment to go an without error.

### Actual Behavior

Fails with MSB3021	The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

### Environment

- MAUI .NET 7 SR6
- Sentry 3.31.0

### Build Logs

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3021	Unable to copy file `"C:\Users\xxxx\.nuget\packages\sentry.bindings.cocoa\3.31.0\lib\net6.0-ios16.1\Sentry.Bindings.Cocoa.resources\Sentry.xcframework\ios-arm64_x86_64-simulator\dSYMs\Sentry-iPhoneSimulator.dSYM\Contents\Resources\DWARF\Sentry"` to `"C:\Users\xxxx\AppData\Local\Temp\Xamarin\HotRestart\Signing\Naturoppdrag.app\out\Payload\Naturoppdrag.app\Naturoppdrag.content\Sentry.Bindings.Cocoa.resources\Sentry.xcframework\ios-arm64_x86_64-simulator\dSYMs\Sentry-iPhoneSimulator.dSYM\Contents\Resources\DWARF\Sentry"`. The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.	Naturoppdrag	C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\16.4.7054\tools\msbuild\iOS\Xamarin.iOS.HotRestart.targets	273

**Comment by espenrl** [comment] 2023-05-10 21:32
It's reported to Sentry at https://github.com/getsentry/sentry/issues/48904

**Comment by espenrl** [comment] 2023-05-10 21:35
I chose to report it as a MAUI SDK issue as the base path 'C:\Users\xxxx\AppData\Local\Temp\Xamarin\HotRestart\Signing\Naturoppdrag.app\out\Payload\Naturoppdrag.app\Naturoppdrag.content' is 126 characters long. Looking at the path it could be shorter.

**Comment by espenrl** [comment] 2023-05-10 21:39
Would love to know if there is any workaround for this issue that would make the path shorter.

**Comment by mattjohnsonpint** [comment] 2023-05-10 23:39
See https://github.com/getsentry/sentry-dotnet/issues/2363#issuecomment-1542887668

@rolfbjarne - I think this issue can be closed here - other than to make sure your .NET 8 changes can deal with long-ish paths.

**Comment by rolfbjarne** [comment] 2023-05-11 05:41
Ok, I'll close this then.

Our own code can handle long paths just fine, the problem is that Visual Studio doesn't enable long paths in its application manifest, so that might have to be added manually.

**Closed by rolfbjarne** 2023-05-11 05:41 UTC

**Comment by mattjohnsonpint** [comment] 2023-05-21 20:40
On further testing, it's not about our Hot Restart workaround, but is indeed about long file paths.  Enabling [long file paths at the OS level](https://learn.microsoft.com/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later) then restarting Visual Studio does seem to work.

I'd also like to find a way to exclude simulator files from the hot restart build, as they shouldn't be needed.  They're in the same xcframework, so they are getting included.  Any thoughts on that?

**Comment by mattjohnsonpint** [comment] 2023-05-22 03:51
I found a way...

```xml
  <Target Name="_SentryRemoveSimulatorResourcesForHotRestartBuilds" AfterTargets="_CopyLocalBindingResources" Condition="'$(IsHotRestartBuild)' == 'true'">
    <ItemGroup>
      <ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)" Condition="$([System.String]::new('%(Identity)').Contains('Sentry.xcframework\ios-arm64_x86_64-simulator'))" />
    </ItemGroup>
  </Target>
```

That at least keeps the files that are hitting max path from being included, and we don't need simulator files in Hot Restart mode anyway.
