### ISSUE TITLE
LinkMode does not work on iOS

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-macios#15382] opened 2022-06-30 17:31 UTC
### Steps to Reproduce

1.  File | New | iOS/Maui
2. Add `<LinkMode>None</LinkMode>` to the csproj
3. Deploy to device
4. Links...

### Expected Behavior
No links.

### Actual Behavior
Links.

![image](https://user-images.githubusercontent.com/1096616/176740953-7ae9e47d-246e-4aeb-a7f4-08336fa4087a.png)

**Comment by dalexsoto** [comment] 2022-06-30 22:48
If this is a duplicate of https://github.com/xamarin/xamarin-macios/issues/12796 is it worth keeping it open?

**Closed** 2022-07-01 15:40 UTC
Labels: bug, iOS

**Comment by BretJohnson** [comment] 2022-08-17 18:26
What exactly is the bug here?
For iOS the setting (today) is MtouchLink, not LinkMode. LinkMode is just for macOS. If you set `MtouchLink` to none that should turn off linking.

**Comment by mattleibow** [comment] 2022-08-17 20:57
We should try be consistent. I think I was reading docs and tried the normal way, but it is special.
