### ISSUE TITLE
Xamarin iOS crashes in debug randomly with error described.

### ISSUE THREAD

**Issue by RazvanEmilR** [xamarin/xamarin-macios#5267] opened 2018-12-12 21:02 UTC
### Steps to Reproduce

1. Start debugging app.
2. Step forward through breaking points

### Expected Behavior
After last break point, visual studio waits for further action with the app still running in debug mode.
If running the app on device disconnected from computer it will not crash.

### Actual Behavior
App crashes at random times with the error below.
App on device also crashes when running disconnected from computer.

**Note: App runs fine in simulator without crashing.
App ran fine in debug before, no code changes made to the respective pages.**

Thread started: <Thread Pool> #11
Thread started:  #12
2018-12-12 11:33:40.016 MyApp.iOS[1201:234792] Token received: <c888863b cb362ba8 3028fa09 ea6171ce e88231e3 f1d5f6a3 071e47aa 1b2511e3>
Thread started: <Thread Pool> #13
Thread started: <Thread Pool> #14
Thread started: <Thread Pool> #15
Thread started: <Thread Pool> #16
2018-12-12 11:33:42.934 MyApp.iOS[1201:234792] <!DOCTYPE html>
<html>
    <head>
        <title>The resource cannot be found.</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         
@media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

    <body bgcolor="white">

            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>The resource cannot be found.</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable. &nbsp;Please review the following URL and make sure that it is spelled correctly.
            <br><br>

            <b> Requested URL: </b>/push/installations/e99787d6-f94e-4ddf-888d-9b4e8e680bdd<br><br>

            <hr width=100% size=1 color=silver>

            <b>Version I
nformation:</b>&nbsp;Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3163.0

            </font>

    </body>
</html>

The app has been terminated.
Failed to Stop app:  An error occured on client IDB412377 while executing a reply for topic xvs/idb/4.12.3.77/stop-app
The app has been terminated.

### Environment

```
Microsoft Visual Studio Professional 2017  (2)
Version 15.9.4
VisualStudio.15.Release/15.9.4+28307.222
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Professional

Visual C++ 2017   00370-10200-41157-AA904
Microsoft Visual C++ 2017

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

Application Insights Tools for Visual Studio Package   8.14.11009.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60913.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.5001.7
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   15.9.02046.0
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.5001.7
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   15.9.18254.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

DPack   3.11.9
DPack for Visual Studio
Copyright © 2004-2018 USysWare, Inc.
For more information, visit http://www.usysware.com/dpack/ or contact us at support@usysware.com

JavaScript support via JavaScript Parser extension by Oleksandr Boiko

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.6.1.6227
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IncrediBuild Build Acceleration   1.5.0.3
IncrediBuild effectively reduces compilation and development times by up to 90%.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft Azure HDInsight Azure Node   2.3.5001.7
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.5001.7
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.4
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.5001.7
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10730.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Mono Debugging for Visual Studio   4.13.12-pre (9bc9548)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.4.21001.1 Commit Hash:8dd15923800d931b153ab9e4de74e42a74eba5e6
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2017 ENU   15.0.28224.00
Microsoft Office Developer Tools for Visual Studio 2017 ENU

PowerShell Pro Tools for Visual Studio   1.0
A set of tools for developing and debugging PowerShell scripts and modules in Visual Studio.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   15.9.18254.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   15.9.18254.1
Provides templates and integration for the Django web framework.

Python - IronPython support   15.9.18254.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   15.9.18254.1
Profiling support for Python projects.

R Tools for Visual Studio   1.3.40517.1016
Provides project system, R Interactive window, plotting, and more for the R programming language.

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SmartPaster2013   1.0
Paste clipboard into comments or string builder

SQL Server Data Tools   15.1.61810.11040
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.9.20918.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   15.0.28107.00
Visual C++ for Cross Platform Mobile Development (Android)

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Apache Cordova   15.123.7408.1
Visual Studio Tools for Apache Cordova

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Unity   3.9.0.3
Visual Studio Tools for Unity

Visual Studio Tools for Universal Windows Apps   15.0.28307.208
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   4.12.3.77 (d15-9@e3f40b477)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.13 (45a16efd4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.4.2 (HEAD/8255f42fc)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.2.1.12 (65ec520)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Example Project (If Possible)

> VS bug [#750057](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/750057)

**Comment by RazvanEmilR** [comment] 2018-12-12 21:41
Any fix to this or idea about what I should do because I am stuck I cannot continue developing app and the error does not tell me anything immediately useful about what could be wrong so i can solve it...

**Comment by spouliot** [comment] 2018-12-13 13:32
@RazvanEmilR the error is not clear but 

> The app has been terminated. Failed to Stop app: An error occured on client IDB412377 while executing a reply for topic xvs/idb/4.12.3.77/stop-app The app has been terminated.

strongly hints it's related to XVS and the bug has been assigned to this team for investigation.

In the meantime I suggest you try to debug directly from the Mac (using Visual Studio for Mac) since that error should not happen locally.

**Comment by RazvanEmilR** [comment] 2018-12-13 21:20
@spouliot  Thanks so much for the tip, and for forwarding the bug. I was really stuck doing my work. Will try using Visual Studio for Mac.

**Comment by RazvanEmilR** [comment] 2018-12-14 17:15
@spouliot Im getting same error when I run the project on my Macbook as well. I just don't understand if its from my code or its a bug in Visual Studio. What I know is that im at the third version of the app and I never modified the code on the page on which the error appears when its just quits with the error message above, and it worked fine until now. What resource is missing? Any other ideas?

**Comment by VincentDondain** [comment] 2018-12-14 17:54
Hi @RazvanEmilR, 

Could you please [Gist](https://gist.github.com) us your full verbose logs (build + application output + any crash you get) when running on the Mac and also on Windows (again, since I don't think your logs are complete)?

The error Sebastien referenced https://github.com/xamarin/xamarin-macios/issues/5267#issuecomment-446969200 IDB412377 should definitely not happen with VSMac, it's Windows specific.

In addition if you can provide a small test project so we can try to reproduce locally that would be helpful (:

**Comment by RazvanEmilR** [comment] 2018-12-14 18:32
@VincentDondain I understand. I just got this idea now about what could be the problem. I am not sure if it is so, but it sounds plausible to me.

**Comment by American-Ledger** [comment] 2018-12-22 21:42
I have this, and I think two instances of the app are being created - a few seconds apart, and then one is terminating.

**Comment by mandel-macaque** [comment] 2019-02-20 17:34
@RazvanEmilR I'm closing the issue since there has not been any updates for a long time. Please feel free to open the issue if you consider this wrong.

**Closed by mandel-macaque** 2019-02-20 17:34 UTC
Labels: external-xamarin-vs, iOS
