### ISSUE TITLE
Optimize Pngs

### ISSUE THREAD

**Issue by yaliashkevich** [xamarin/xamarin-macios#20106] opened 2024-02-14 10:49 UTC
I've been migrating from classic xamarin to dotnet ios recently and noticed that _**pngcrushing**_ of images under /Resources is not happening anymore. 

Looks like it (**_OptimizePngImages** target) is turned off for sdk style project. Is it any way to enable it?

https://github.com/xamarin/xamarin-macios/blob/dc90060cfa1c106dc6b8cc2811da9d71e0480207/msbuild/Xamarin.Shared/Xamarin.iOS.Common.targets#L33-L50

**Comment by rolfbjarne** [comment] 2024-02-14 18:44
This looks like an oversight; I'll have to investigate a bit.

In the meantime, something like this in your csproj might do it:

```xml
<PropertyGroup>
    <BuildDependsOn>
        $(BuildDependsOn);
		_OptimizePngImages
	</BuildDependsOn>
</BuildDependsOn>
```

**Comment by rolfbjarne** [comment] 2024-02-16 16:32
I've filed #20129 to look into this + a couple of other targets we're missing in .NET, so I'm closing this as a duplicate of that issue.

Thanks for your report! Please let us know if you run into any problems with the workaround.

**Closed by rolfbjarne** 2024-02-16 16:32 UTC
