### ISSUE TITLE
AVAudioPcmBuffer crashes with Xamarin iOS 13.20

### ISSUE THREAD

**Issue by ghost** [xamarin/xamarin-macios#8882] opened 2020-06-17 22:39 UTC
### Steps to Reproduce

1. Attempt to initialize an AVAudioPcmBuffer (parameters do not matter- I've tried many combinations)

`AVAudioPcmBuffer buffer = new AVAudioPcmBuffer(new AVAudioFormat(AVAudioCommonFormat.PCMFloat32, 44100.0, 2, false), (uint)100);`

### Expected Behavior
Buffer gets initialized and can be used, like it can be in <= 13.18

### Actual Behavior
App crashes and terminates, upon running this line of code

### Environment

```
Microsoft Visual Studio Community 2019 Preview
Version 16.7.0 Preview 2.0
VisualStudio.16.Preview/16.7.0-pre.2.0+30128.36
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Azure App Service Tools v3.0.0   16.7.276.48084
Azure App Service Tools v3.0.0

C# Tools   3.7.0-2.20270.4+205504dfd0f686370cffae5df068024c8a2b427f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   16.7.2 (c19c9c3)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.7.0-2.20270.4+205504dfd0f686370cffae5df068024c8a2b427f
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20230.7+082844d9aaa5d2893680b05a1fe0b77ee18719dd
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.7.000.200 (master@c631c2f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.7.0.340 (remotes/origin/d16-7@f61b59c2e)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.6.61 (87c64b8)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.3.99.259 (d16-7/feabf52)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 075c3f0
    Java.Interop: xamarin/java.interop/d16-7@d6024f1
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@23c4fe0


Xamarin.iOS and Xamarin.Mac SDK   13.20.0.22 (c2a220d84)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Build Logs

Project builds fine

**Comment by chamons** [comment] 2020-06-18 16:04
I can confirm this crashes on sim:
```
			var format = new AVAudioFormat (AVAudioCommonFormat.PCMFloat32, 44100.0, 2, true);
			AVAudioPcmBuffer buffer = new AVAudioPcmBuffer (format, (uint)100);
```
and this passes on sim
```
    AVAudioFormat * format = [[AVAudioFormat alloc] initWithCommonFormat:AVAudioPCMFormatFloat32 sampleRate:44100.0 channels:2 interleaved:YES];
    AVAudioPCMBuffer * buffer = [[AVAudioPCMBuffer alloc] initWithPCMFormat:format frameCapacity:100];
```

Doing some digging.

**Comment by chamons** [comment] 2020-06-19 15:13
We've isolated this to part of a PR
```
-               public bool Equals (NSObject obj) => Equals ((object) obj);
+               public bool Equals (NSObject obj)
+               {
+                       if (obj == null)
+                               return false;
+                       // we'll ask the overridden Equals (if available) if one of the instances is not a direct binding
+                       return (IsDirectBinding && obj.IsDirectBinding) ? IsEqual (obj) : Equals ((object) obj);
+               }
```
From https://github.com/xamarin/xamarin-macios/pull/8091 

Looking at a fix.

Thanks for the report and early testing by the way!

**Comment by chamons** [comment] 2020-06-19 16:25
This fix will make it into d16-7, but not in time for next preview.

**Comment by DamianMehers** [comment] 2020-06-20 13:33
I'm getting a similar thing calling 

```c#
          var format = node.GetBusOutputFormat(0);
          _playAudioEngine.Connect(node, _playAudioEngine.MainMixerNode, format);
```

If I pass `null` for format it also crashes.  Both iOS and WatchOS.

There is infinite recursion in AVAudioFormat: Equals calls "==" which calls Equals which calls "==" ... ad infinitum

I'm assuming it is the same issue, but let me know if I should open a separate one,

<img width="575" alt="Screenshot 2020-06-20 at 15 32 06" src="https://user-images.githubusercontent.com/1457446/85203069-5036c400-b30b-11ea-8cc8-6c437e1791fc.png">

**Comment by DamianMehers** [comment] 2020-06-20 14:04
@tolrtd @chamons 

I hit the same issue, and have worked around it by defining my own `AVAudioFormat`:

``` c#
public class MyAudioFormat : AVAudioFormat {
    public override bool Equals(object obj) {
      return System.Runtime.CompilerServices.RuntimeHelpers.Equals(this, obj);
    }
    public override int GetHashCode() {
      return System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(this);
    }

    public MyAudioFormat(AVAudioFormat other) : base(other.Settings) {
    }
  }
```

Then whenever I passed an AVAudioFormat I wrap it in my own:

```c#
_converter = new AVAudioConverter(new MyAudioFormat(sourceFormat), new MyAudioFormat(toFormat));
_tempPcmBuffer = new AVAudioPcmBuffer(new MyAudioFormat(sourceFormat), PlaybackFrameSize);
```

By setting a breakpoint in [AVAudioFormat.Equals](https://github.com/chamons/xamarin-macios/blob/master/src/AVFoundation/AVAudioFormat.cs) I was able to see where I'd missed wrapping it with my one.

**Comment by chamons** [comment] 2020-06-21 19:28
That seems like a reasonable enough work around until we get this out in the newest preview (other than downgrading to stable).

**Comment by DamianMehers** [comment] 2020-06-22 06:14
> That seems like a reasonable enough work around until we get this out in the newest preview (other than downgrading to stable).

I wish I could go back to stable, but I'm blocked by [a different issue](https://github.com/xamarin/xamarin-macios/issues/8288) in stable.

**Comment by rolfbjarne** [comment] 2022-09-28 14:12
Closing, since this has been fixed (and released) for a while.

**Closed by rolfbjarne** 2022-09-28 14:12 UTC
Labels: iOS
