### ISSUE TITLE
[XI]System tests failure on 32 bit device with Release and llvm enabled

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#3369] opened 2018-01-31 20:18 UTC
### Steps to Reproduce

1. Build and Execute System tests on 32 bit device with Release config and llvm enabled

### Expected Behavior
Tests should pass successfully
### Actual Behavior
Most of Blocking CollectionTests fails with NRE and Enumerator_Current in SortedDictionary Test crash which causes System test not to finish successfully. These issues occur only when llvm is enabled.
### Environment

Xamarin.iOS
Version: 11.8.0.18 (Visual Studio Community)
Hash: 4c56cbbf
Branch: d15-6

Device:
iPad2 9.3.5

### Build Logs
d15-6
Build Log: https://gist.github.com/GouriKumari/47d7ce839435d533ae945ee4f37c832c
Test Log: https://gist.github.com/GouriKumari/c5fe08cc05b6f82a6676ce99b3bf3632
Crash Log: https://gist.github.com/GouriKumari/e6081c2d9a489d34ebee2cf0798e3e3d

##Regression Status: yes
d15-5
Build Log: https://gist.github.com/GouriKumari/136b936d2f53124d9f4d135e2fcaa843
Test Log: https://gist.github.com/GouriKumari/5ed78511de5281b0b14fd47f15a78ac2
All tests passed

**Comment by dalexsoto** [comment] 2018-01-31 21:17
I can also reproduce this in an iPhone 5

Crash log: https://gist.github.com/dalexsoto/9a70da64017ede7e534c514d5f75a57e#file-crash-log
Console log: https://gist.github.com/dalexsoto/9a70da64017ede7e534c514d5f75a57e#file-console-log

This does seem like a dupe of https://github.com/xamarin/xamarin-macios/issues/3241

/cc @spouliot @vargaz

**Comment by rolfbjarne** [comment] 2018-02-01 12:34
This test succeeds if I apply the fix for #3241 locally, so I'm closing as a dup of that one.

**Closed by rolfbjarne** 2018-02-01 12:34 UTC
Labels: bug, iOS
