### ISSUE TITLE
Linking on Xamarin IOS apparently removes some EF Core 2.0 features

### ISSUE THREAD

**Issue by Kortdag** [xamarin/xamarin-macios#3441] opened 2018-02-09 10:27 UTC
### Steps to Reproduce
Run on a real device. Haven´t testet on emulator.
Fix Info.plist certificates to you own 

1. Run sample project with Linker behavior "Link SDK frameworks Only". And deploy 
2. Run sample project with Linker behavior "Dont link"
3. var test = context.Blogs.Include(x => x.Posts).ToList(); in app delegate fails i scenario 1) with [Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions] but works without linking

[LinkEFSample.zip](https://github.com/xamarin/xamarin-macios/files/1710588/LinkEFSample.zip)

**Comment by mandel-macaque** [comment] 2018-02-09 11:58
Hello,

I tried to test the supplied application but it does not build since the platform of the EF dependency lib does not match with the Xamarin.iOS runtime:

![screen shot 2018-02-09 at 12 55 32](https://user-images.githubusercontent.com/2190086/36026749-bf77cdf2-0d98-11e8-81c6-bd3b4cd2e913.png)

Can you please fix the project and resubmit. Nevertheless, it is important to note that it might be the case that the linker is removing code that it believes is not used. You can configure the linker to NOT remove certain classes/methods/properties as indicated in the [docs](https://developer.xamarin.com/guides/cross-platform/advanced/custom_linking/)

But if you can provide a compiling test app I will take a look to pinpoint the issue and if needed provide you with a config xml for your case.

**Comment by Kortdag** [comment] 2018-02-09 13:08
Hi

Huh, it builds finde on my machine. On my machine the error just shows up since to get migrations to work I seems to have to target both cnetstandard and coreapp like so in the proj file
<TargetFramework>netstandard2.0</TargetFramework>

    


Anyway I changes it back to only netstandard2.0 which makes the VS error not showing up.
It compiles fine on my machine and the issue remains to be there.

Hope it helps

**Comment by spouliot** [comment] 2018-02-09 15:02
might be a duplicate of https://github.com/xamarin/xamarin-macios/issues/3394

**Comment by Kortdag** [comment] 2018-02-09 15:18
Looks like the same issue.
Still not a reliable workaround as mentioned since one never know when other things break.
But I guess the conclusion is that the only place to fix this in a robust way is if its done in the Core EF framework??

**Comment by spouliot** [comment] 2018-02-13 21:01
> But I guess the conclusion is that the only place to fix this in a robust way is if its done in the Core EF framework??

@Kortdag Yes, they are the only people who knows what's used thru reflection (to preserve them) and that list can differ across versions (which we would not be able to deal with).

If the previous workaround is not complete enough then please update your test case, re-open the issue and we'll have a look.

**Closed by spouliot** 2018-02-13 21:01 UTC
Labels: need-info

**Comment by Kortdag** [comment] 2018-09-19 13:42
This one on EF core 
https://github.com/aspnet/EntityFrameworkCore/issues/10963#issuecomment-370475286
