### ISSUE TITLE
Runtime "AX Exchange error" warnings with alpha build

### ISSUE THREAD

**Issue by taori** [xamarin/xamarin-macios#5394] opened 2019-01-14 10:42 UTC
@emaf provided me with an alpha build to try resolve a debug issue i've been having. Debugging works now, but my debug output window is being swarmed with these log messages and he told me to forward this issue here.

# output window

```
2019-01-11 14:22:03.484 STMiOS[1957:2733846] AX Exchange error: Error Domain=Accessibility Code=0 "Remote service does not respond to _accessibilityMachPort" UserInfo={NSLocalizedDescription=Remote service does not respond to _accessibilityMachPort}
2019-01-11 14:22:03.484 STMiOS[1957:2733846] AX Exchange error: Error Domain=Accessibility Code=0 "Remote service does not respond to _accessibilityMachPort" UserInfo={NSLocalizedDescription=Remote service does not respond to _accessibilityMachPort}
2019-01-11 14:22:03.484 STMiOS[1957:2733846] AX Exchange error: Error Domain=Accessibility Code=0 "Remote service does not respond to _accessibilityMachPort" UserInfo={NSLocalizedDescription=Remote service does not respond to _accessibilityMachPort}
2019-01-11 14:22:03.485 STMiOS[1957:2733846] AX Exchange error: Error Domain=Accessibility Code=0 "Remote service does not respond to _accessibilityMachPort" UserInfo={NSLocalizedDescription=Remote service does not respond to _accessibilityMachPort}
2019-01-11 14:22:03.485 STMiOS[1957:2733846] AX Exchange error: Error Domain=Accessibility Code=0 "Remote service does not respond to _accessibilityMachPort" UserInfo={NSLocalizedDescription=Remote service does not respond to _accessibilityMachPort}
2019-01-11 14:22:03.485 
STMiOS[1957:2733846] AX Exchange error: Error Domain=Accessibility Code=0 "Remote service does not respond to _accessibilityMachPort" UserInfo={NSLocalizedDescription=Remote service does not respond to _accessibilityMachPort}
2019-01-11 14:22:03.586 STMiOS[1957:2733846] AX Exchange error: Error Domain=Accessibility Code=0 "Remote service does not respond to _accessibilityMachPort" UserInfo={NSLocalizedDescription=Remote service does not respond to _accessibilityMachPort}
STMiOS[1957:2733846] AX Exchange error: Error Domain=Accessibility Code=0 "Remote service does not respond to _accessibilityMachPort" UserInfo={NSLocalizedDescription=Remote service does not respond to _accessibilityMachPort}
2019-01-11 14:22:03.586 STMiOS[1957:2733846] AX Exchange error: Error Domain=Accessibility Code=0 "Remote service does not respond to _accessibilityMachPort" UserInfo={NSLocalizedDescription=Remote service does not respond to _accessibilityMachPort}
2019-01-11 14:22:03.586 STMiOS[1957:2733846] AX Exchange error: Error Domain=Accessibility Code=0 "Remote service does not respond to _accessibilityMachPort" UserInfo={NSLocalizedDescription=Remote service does not respond to _accessibilityMachPort}
2019-01-11 14:22:03.586 STMiOS[1957:2733846] AX Exchange error: Error Domain=Accessibility Code=0 "Remote service does not respond to _accessibilityMachPort" UserInfo={NSLocalizedDescription=Remote service does not respond to _accessibilityMachPort}
2019-01-11 14:22:03.587 STMiOS[1957:2733846] AX Exchange error: Error Domain=Accessibility Code=0 "Remote service does not respond to _accessibilityMachPort" UserInfo={NSLocalizedDescription=Remote service does not respond to _accessibilityMachPort}
2019-01-11 14:22:03.587 
2019-01-11 14:22:03.694 STMiOS[1957:2733846] AX Exchange error: Error Domain=Accessibility Code=0 "Remote service does not respond to _accessibilityMachPort" UserInfo={NSLocalizedDescription=Remote service does not respond to _accessibilityMachPort}
[0:] 22:03.722 INF 15 Request end Api/v1/TopLevelProject/GetById/12 275,365ms - success (93 bytes)2019-01-11 14:22:03.694 STMiOS[1957:2733846] AX Exchange error: Error Domain=Accessibility Code=0 "Remote service does not respond to _accessibilityMachPort" UserInfo={NSLocalizedDescription=Remote service does not respond to _accessibilityMachPort}
2019-01-11 14:22:03.694 STMiOS[1957:2733846] AX Exchange error: Error Domain=Accessibility Code=0 "Remote service does not respond to _accessibilityMachPort" UserInfo={NSLocalizedDescription=Remote service does not respond to _accessibilityMachPort}
2019-01-11 14:22:03.694 STMiOS[1957:2733846] AX Exchange error: Error Domain=Accessibility Code=0 "Remote service does not respond to _accessibilityMachPort" UserInfo={NSLocalizedDescription=Remote service does not respond to _accessibilityMachPort}
2019-01-11 14:22:03.694 STMiOS[1957:2733846] AX Exchange error: Error Domain=Accessibility Code=0 "Remote service does not respond to _accessibilityMachPort" UserInfo={NSLocalizedDescription=Remote service does not respond to _accessibilityMachPort}
2019-01-11 14:22:03.695
```

# environment info 

```
Microsoft Visual Studio Enterprise 2017 
Version 15.9.5
VisualStudio.15.Release/15.9.5+28307.280
Microsoft .NET Framework
Version 4.7.03062

Installierte Version: Enterprise

Allgemeine Azure-Tools   1.10
Bietet allgemeine Dienste für die Verwendung durch Azure Mobile Services und Microsoft Azure-Tools.

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60913.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

Azure Functions und Webauftragstools   15.9.02046.0
Azure Functions und Webauftragstools

C#-Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C#-Komponenten, die in der IDE verwendet werden. Je nach Projekttyp und Einstellungen kann eine andere Compilerversion verwendet werden.

Erweiterung zum Debuggen von Momentaufnahmen   1.0
Detaillierte Informationen zur Visual Studio-Erweiterung zum Debuggen von Momentaufnahmen

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

JavaScript-Sprachdienst   2.0
JavaScript-Sprachdienst

JetBrains ReSharper Ultimate 2018.2.3   Build 182.0.20180912.70621
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

Microsoft Azure-Tools   2.9
Microsoft Azure-Tools für Microsoft Visual Studio 2017 – v2.9.10730.2

Microsoft Continuous Delivery Tools für Visual Studio   0.4
Die Konfiguration von Azure DevOps-Pipelines von der Visual Studio-IDE aus wird vereinfacht.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio-Tools für Container   1.1
Jetzt können Sie Ihre ASP.NET Core-Anwendung in der Zielumgebung entwickeln, ausführen und überprüfen. Drücken Sie F5, um die Anwendung direkt in einem Container mit Debugfunktionen auszuführen, oder STRG+F5 zum Bearbeiten und Aktualisieren Ihrer Anwendung, ohne den Container erneut erstellen zu müssen.

Mono Debugging for Visual Studio   4.13.12-pre (9bc9548)
Support for debugging Mono processes with Visual Studio.

NuGet-Paket-Manager   4.6.0
NuGet-Paket-Manager in Visual Studio. Weitere Informationen zu NuGet finden Sie unter "http://docs.nuget.org/".

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage-Erweiterung   1.0
Detaillierte Informationen zur ResourcePackage-Erweiterung von Visual Studio

ResourcePackage-Erweiterung   1.0
Detaillierte Informationen zur ResourcePackage-Erweiterung von Visual Studio

ResXManager   1.33.1745.0
Manage localization of all ResX-Based resources in one place. Shows all resources of a solution and let's you edit the strings and their localizations in a well-arranged data grid.

SQL Server Data Tools   15.1.61901.03220
Microsoft SQL Server Data Tools

TypeScript-Tools   15.9.20918.2001
TypeScript-Tools für Microsoft Visual Studio

Visual Basic-Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic-Komponenten, die in der IDE verwendet werden. Je nach Projekttyp und Einstellungen kann eine andere Version des Compilers verwendet werden.

Visual F# Tools 10.2 für F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 für F# 4.5

Visual Studio-Tools für Container   1.0
Visual Studio-Tools für Container

Visual Studio Code-Debugadapter-Hostpaket   1.0
Interopebene zum Hosten der Visual Studio Code-Adapter in Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSColorOutput   2.6.3
Color output for build and debug windows - http://mike-ward.net/vscoloroutput

Xamarin   4.12.3.82 (merge@153c0369d)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.13 (45a16efd4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.5.0 (HEAD/4b951a3e7)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.2.1.12 (65ec520)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

# logs

[logs_2019-01-14.zip](https://github.com/xamarin/xamarin-macios/files/2754783/logs_2019-01-14.zip)

**Comment by spouliot** [comment] 2019-01-14 14:01
That message comes directly from iOS (not Xamarin) and is triggered by the use of some API (i.e. it's not something I see locally) either directly (by your application) or some 3rd party code.

A bit of googling shows this happened to both [Xcode](https://stackoverflow.com/a/28592706/220643) and [Xamarin](https://stackoverflow.com/a/47628401/220643) developers. The later seems to point to Calabash as a 3rd party that can cause this to happen.

If it's not the case then we'll need a test case to investigate what could be causing those extraneous warnings to be printed.

**Comment by spouliot** [comment] 2019-01-14 14:32
Definitively try removing (disabling) calabash to see if it's the cause of the warnings.

It might be temporary - but I think it's more likely the warning is printed only on some (maybe recent) version of iOS (and your calabash library might be older).

**Comment by mandel-macaque** [comment] 2019-02-27 11:36
Closing the issue since we have had no movement for over a month. Please reopen if you feel appropiate.

**Closed by mandel-macaque** 2019-02-27 11:36 UTC
Labels: iOS, need-info, support

**Comment by hauteur** [comment] 2019-03-26 11:57
I have seen this happen as well, but it is intermittent.  When it is happening, however, commenting out `Calabash.Start()` for UI Test makes it stop.

**Comment by AnoopN01** [comment] 2020-03-05 18:04
I am seeing this error when my app is having no connectivity ( airplane mode)
