### ISSUE TITLE
Error: strip exited with code 139 (Release Mode)

### ISSUE THREAD

**Issue by gwise-vision** [xamarin/xamarin-macios#21327] opened 2024-09-29 13:10 UTC
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

VS2022 For Mac 17.6.14(Build 413), NET 8.0.4, iOS 18.0.8303, Xcode 16

### Description

When compiling as a release on Mac VS2022, an error occurs as shown below.
If you do not check [Strip native debugging symbols] in the Build options, the error does not occur. I want to apply this option.

/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_18.0/18.0.8303/tools/msbuild/iOS/Xamarin.Shared.targets(3,3): Error: strip exited with code 139
         (ExpiryDateScanner.iOS)

### Steps to Reproduce

When compiling as a release on Mac VS2022, an error occurs as shown below.
If you do not check [Strip native debugging symbols] in the Build options, the error does not occur. I want to apply this option.

/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_18.0/18.0.8303/tools/msbuild/iOS/Xamarin.Shared.targets(3,3): Error: strip exited with code 139
         (ExpiryDateScanner.iOS)

**Comment by corne-ac** [comment] 2024-09-29 18:54
Getting this same one when trying to debug my MAUI Application. I followed the latest guide on how to update to xcode 16 support, and am now getting this. I cann ot for the life of me figure out what is causing it. So hopefully this issue can be escalated.

I am using jetbrains rider, here is what gets printed:

Tool xcrun execution started with arguments: dsymutil -num-threads 4 -o bin/Debug/net8.0-ios/ios-arm64/MyApp.MAUI.app.dSYM /Users/{myuser}/RiderProjects/MyAppMobile/MyApp.MAUI/bin/Debug/net8.0-ios/ios-arm64/MyApp.MAUI.app/P4Flow.MAUI
        
Target _NativeStripFiles:
Tool xcrun execution started with arguments: strip -i -s /Users/{myuser}/RiderProjects/MyAppMobile/MyApp.MAUI/obj/Debug/net8.0-ios/ios-arm64/mtouch-symbols.list /Users/{MyUser}/RiderProjects/MyAppMobile/MyApp.MAUI/bin/Debug/net8.0-ios/ios-arm64/MyApp.MAUI.app/MyApp.MAUI
        
Tool xcrun execution finished (exit code = 139).
        
1>Xamarin.Shared.targets(2848,3): Error  : strip exited with code 139

The code part: (inside Xamarin.Shared.targets)


		<SymbolStrip
			SessionId="$(BuildSessionId)"
			Condition="'$(IsMacEnabled)' == 'true'"
			Executable="$(_AppContainerDir)%(_NativeStripItems.Identity)"
			Kind="%(_NativeStripItems.Kind)"
			MaxDegreeOfParallelism="$(SymbolStripMaxDegreeOfParallelism)"
			SymbolFile="%(_NativeStripItems.SymbolFile)"
		/>

**Comment by alisariaslan** [comment] 2024-09-29 22:46
I'm currently using VS Code Archive/Publish Extention for my publishes. You can try publish extension in VS Code if you wanna publish your project.

**Comment by gwise-vision** [comment] 2024-09-30 04:42
> I'm currently using VS Code Archive/Publish Extention for my publishes. You can try publish extension in VS Code if you wanna publish your project. I'm doing my debug sessions with VS for Mac.

The same error 139 occurs in vs code.
This error occurs when applying Strip native debugging symbols in Xcode 16.

![image](https://github.com/user-attachments/assets/5c48c425-8b29-4519-980c-54e6da74bbcc)

**Comment by pulmuone** [comment] 2024-09-30 06:23
vs-code same error (Xcode 16)

  Tool xcrun execution finished (exit code = 139).
          
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_18.0/18.0.8303/tools/msbuild/iOS/Xamarin.Shared.targets(2848,3): error : strip exited with code 139 [/Users/gwise/Projects/ExpiryDateScanner/ExpiryDateScanner/ExpiryDateScanner.iOS/ExpiryDateScanner.iOS.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_18.0/18.0.8303/tools/msbuild/iOS/Xamarin.Shared.targets(2848,3): error :          [/Users/gwise/Projects/ExpiryDateScanner/ExpiryDateScanner/ExpiryDateScanner.iOS/ExpiryDateScanner.iOS.csproj]

**Comment by rolfbjarne** [comment] 2024-09-30 06:24
This is a duplicate of #19157.

**Closed by rolfbjarne** 2024-09-30 06:24 UTC

**Comment by EricNgo1972** [comment] 2025-01-16 20:45
I had the same problem when I tried to release a MAUI app on Rider with XCode 16.1. It was strange because the app compiled fine in debug mode, and a HelloWorld app was released without any issues.

However, the problem was resolved after upgrading XCode to 16.2

**Comment by danbridgellc** [comment] 2025-01-28 19:02
Same here, had the same problem and upgraded to XCode 16.2 resolved the issue! Thank you @EricNgo1972!!
