### ISSUE TITLE
Archiving iOS app fails in Visual Studio 16.7 Preview 5: "Process cannot be executed on XMA server"

### ISSUE THREAD

**Issue by tekr** [xamarin/xamarin-macios#9200] opened 2020-07-27 07:51 UTC
### Steps to Reproduce

1. Build iOS project (Release mode) in Xamarin Forms app solution
2. Attempt to archive build (Right-click on iOS project in Solution Explorer -> Archive...)
3. 

### Expected Behavior

Archive of Release build is created.

### Actual Behavior

Archiving fails. The Xamarin output window says:

Archiving App Bundle 'Test'...
The underlying client has been disconnected by the remote host
The underlying client has been disconnected by the remote host
An error occurred while registering a handler for 'ClientStatusMessage' messages, so all the content sent to the topic 'xma/client-status' will not be handled in this active connection
An error occurred while registering a handler for 'PingMessage' messages, so all the content sent to the topic 'xma/ping/{ClientId}' will not be handled in this active connection
Cannot create an IOS archive 'Test.iOS'. Process cannot be executed on XMA server.
Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new

### Environment

Mac host: Catalina 10.15.6 on Mac mini 2018

```
Microsoft Visual Studio Professional 2019 Preview
Version 16.7.0 Preview 5.0
VisualStudio.16.Preview/16.7.0-pre.5.0+30317.65
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA156
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.7.527.4847
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2035807+72d099b977d3a85e65fa3b0614ca8cfc803fef02
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.7.527.4847
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.7.527.4847
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.4.6000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.7.527.4847
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.4.6000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.7.0-5.20366.7+a303c0d8a4ab6af557afb6e4a7a5bc09bbcebae5
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper Ultimate 2020.1.4   Build 201.0.20200702.125931
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2020 JetBrains, Inc.

Microsoft Azure HDInsight Azure Node   2.4.6000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.4.6000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.4.6000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30701.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.79+ge3567815aa.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.7.5 (112c7bc)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62007.09200
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.20702.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.7.0-5.20366.7+a303c0d8a4ab6af557afb6e4a7a5bc09bbcebae5
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.30317
Visual C++ for Linux Development

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20361.3+3ef6f0b514198c0bfa6c2c09fefe41a740b024d5
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.7.000.439 (d16-7@f5cc903)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.7.0.495 (remotes/origin/d16-7@79c0c522c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.7.85 (1bcbbdf)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.0.0.3 (d16-7/aca845b)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-7@1f3388a
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f


Xamarin.iOS and Xamarin.Mac SDK   13.20.1.44 (28cab0985)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Build Logs

Build log:

https://gist.github.com/tekr/7bb188f1ea834e733062e9c0c2d202ae

### Example Project (If Possible)

> VS bug [#1162758](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1162758)

**Comment by mauroa** [comment] 2020-08-11 21:24
Hi,
It would be great to analyze the build process that runs when the archiving is generated, so we can see what is causing your issues. To produce that build and get the logs, please follow the next steps:

1. Install the [Project System Tools](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools) extension
2. In Visual Studio, choose the View > Other Windows > Build Logging menu item.
3. Click on the "play" button.
4. Reproduce the issue
5. Select all entries in the build logging tool window
6. Right-click them, Save Logs
7. Attach the resulting zip file to this issue.

Finally, please try to report VS related issues directly on the following VS Feedback link: https://developercommunity.visualstudio.com/idea/746832/visual-studio-feedback.html

Thanks for your help.

**Comment by mauroa** [comment] 2020-09-28 12:29
Closing this since we had no reply with the requested information from a long time. Thanks

**Closed by mauroa** 2020-09-28 12:29 UTC
Labels: external-xamarin-vs
