### ISSUE TITLE
[mono 2019-06][Tests] [xUnit] Mono BCL tests group 4 fail on iOS 64 and tvOS

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#6331] opened 2019-06-17 11:12 UTC
Running the tests results in the following [failures](https://gist.github.com/mandel-macaque/00578c27c44b930be324821ce1cf1adf).

**Comment by marek-safar** [comment] 2019-06-17 12:57
This is most likely duplicate of https://github.com/mono/mono/issues/14877

**Comment by akoeplinger** [comment] 2019-07-02 19:28
Closing as duplicate of #14877.

**Closed by akoeplinger** 2019-07-02 19:28 UTC
