### ISSUE TITLE
CMMotionManager throws exception on StartAccelerometerUpdates

### ISSUE THREAD

**Issue by razmojazz** [xamarin/xamarin-macios#3522] opened 2018-02-18 07:17 UTC
### Steps to Reproduce

The code below throws the exception
Object of type 'System.Func '3[CoreMotion.CMAccelerometerData, Foundation.NSError, System.Object]' cannot be converted to type 'CoreMotion.CMAccelerometerHandler'

Code (slightly modified from the example on the Xamarin website).

            motionManager = new CMMotionManager();
             Samples = new List<Accel3DPoint>();

            motionManager.StartAccelerometerUpdates(NSOperationQueue.CurrentQueue, (data, error) =>
             {
                 var point = new Accel3DPoint(data.Acceleration.X, data.Acceleration.Y, data.Acceleration.Z);
                 Samples.Add(point);
             });

### Expected Behavior

No exception - points are added to List called Samples

### Actual Behavior
Exception is thrown
Object of type 'System.Func '3[CoreMotion.CMAccelerometerData, Foundation.NSError, System.Object]' cannot be converted to type 'CoreMotion.CMAccelerometerHandler'

### Environment
iOS Live Player version 1.5.174 (674) through TestFlight
VS2017 Pro on Windows 10

**Comment by dalexsoto** [comment] 2018-02-20 03:37
Hello @razmojazz

Sample: [GHIssue3522.zip](https://github.com/xamarin/xamarin-macios/files/1738822/GHIssue3522.zip)

I followed your instructions and created a sample project that tries to reproduce your issue. I am **not** getting any issues with the provided sample code. 

Please download this sample and try yourself. If you are able to reproduce the issue with the given sample please include your full build logs, crash reports (if any) and all your **version information**.

To get full build logs just set the log verbosity to diagnostic at the following locations:
- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.
Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact **version information**:
- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
Then copy/paste the version information (you can use the "Copy Information" button).

**Comment by razmojazz** [comment] 2018-02-22 17:39
Hi!

I tried to run your code, but it doesn't work on Live player on my iPhone 6 (It showed a warning once and nothing happens when I click "Start Accelerometer"). 

I was not sure if it was a Mac problem or a Live Player problem, but it seems to be the latter. Should I just repost in the Live Player forum?

**Comment by rolfbjarne** [comment] 2022-09-22 19:47
Closing since Live Run no longer exists.

**Closed by rolfbjarne** 2022-09-22 19:47 UTC
Labels: bug, iOS, external-live-run
