### ISSUE TITLE
Failed to codesign .... replacing existing signature

### ISSUE THREAD

**Issue by Kanat9494** [xamarin/xamarin-macios#21849] opened 2024-12-23 06:58 UTC
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

VS 2022

### Description

I had an old mac, and I used it to create 1 application in .net maui, and successfully tested it and uploaded it to the App Store. After a while, I bought a new mac, exported all my certificates there, but I couldn't run my application there, which was created on the old mac. All I can do is connect via Visual Studio Windows and build an ipa file to publish to the App Store. But I need to run the app on a new mac to test. I've been trying to fix this for months

      
              

Build failed with 2 error(s) in 1.6s

### Steps to Reproduce

create new app net maui, test and run on ios devise, publish to app store, than try to run this app on new mac)

### Did you find any workaround?

Unfortunately, I did not find it.

### Relevant logs

I get the following error:
[{
	"resource": "/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_18.0/18.0.8303/tools/msbuild/iOS/Xamarin.Shared.targets",
	"owner": "maui",
	"severity": 8,
	"message": "/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_18.0/18.0.8303/tools/msbuild/iOS/Xamarin.Shared.targets(2335,3): error :",
	"source": "maui",
	"startLineNumber": 2335,
	"startColumn": 3,
	"endLineNumber": 2335,
	"endColumn": 3
}]
PAMobile net8.0-ios failed with 2 error(s) (1.4s) → PAMobile/bin/Debug/net8.0-ios/iossimulator-arm64/PAMobile.dll
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_18.0/18.0.8303/tools/msbuild/iOS/Xamarin.Shared.targets(2335,3): error : 
      /usr/bin/codesign exited with code 1:
      /Users/aidarjolboldiev/Desktop/maui/PAMobile/PAMobile/bin/Debug/net8.0-ios/iossimulator-arm64/PAMobil
      e.app: replacing existing signature
      /Users/aidarjolboldiev/Desktop/maui/PAMobile/PAMobile/bin/Debug/net8.0-ios/iossimulator-arm64/PAMobil
      e.app: resource fork, Finder information, or similar detritus not allowed
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_18.0/18.0.8303/tools/msbuild/iOS/Xamarin.Shared.targets(2335,3): error : 
      Failed to codesign '/Users/aidarjolboldiev/Desktop/maui/PAMobile/PAMobile/bin/Debug/net8.0-ios/iossim
      ulator-arm64/PAMobile.app': /Users/aidarjolboldiev/Desktop/maui/PAMobile/PAMobile/bin/Debug/net8.0-io
      s/iossimulator-arm64/PAMobile.app: replacing existing signature
      /Users/aidarjolboldiev/Desktop/maui/PAMobile/PAMobile/bin/Debug/net8.0-ios/iossimulator-arm64/PAMobil
      e.app: resource fork, Finder information, or similar detritus not allowed

**Comment by rolfbjarne** [comment] 2024-12-30 07:37
This is a duplicate of https://github.com/xamarin/xamarin-macios/issues/5202.

The fix is to remove the extra file attributes from the files in question, although it might not be entirely trivial to figure out where all the files come from, since the error message from Apple's codesign tool doesn't say which files are causing this.

However, a good beginning would be to remove the extra file attributes from all the files in the solution/project directory, by executing this from a terminal:

```shell
xattr -s -c -r /path/to/solution
```

**Closed by rolfbjarne** 2024-12-30 07:37 UTC
