### ISSUE TITLE
UITextView.TypingAttributes  always return null, even after set

### ISSUE THREAD

**Issue by unamed000** [xamarin/xamarin-macios#12709] opened 2021-09-13 08:18 UTC
### Steps to Reproduce

1. Create a UITextView
2. Set TypingAttributes for that UITextView
3. After that line, get the TypingAttributes immediately.

### Expected Behavior
TypingAttributes should return newly set value

### Actual Behavior
TypingAttributes always return null

### Code example
```     
                var typingAttributes = new NSMutableDictionary();

                typingAttributes[UIStringAttributeKey.UnderlineStyle] = isUnderlined ? (NSNumber)1 : (NSNumber)0;
                typingAttributes[UIStringAttributeKey.Font] = newFont;

                Control.TypingAttributes = typingAttributes;

                var hereComesTheNull = Control.TypingAttributes;
```

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.7 (build 17)
Installation UUID: 26ad19d0-0dc7-4785-a4c3-5c8fd4209b57
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.400/Sdks
SDK Versions:
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11

=== .NET Core 3.1 SDK ===

SDK: 3.1.412

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.5.1 (18212)
Build 12E507

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.20.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:01-0400

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Xamarin.Android ===

Version: 11.3.0.4 (Visual Studio Community)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/huyvu/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.0
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/huyvu/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.12
Hash: e240b8c
Branch: remotes/origin/d16-10
Build date: 2021-08-03 17:48:52 UTC

=== Android Device Manager ===

Version: 16.10.0.14
Hash: e340248
Branch: remotes/origin/d16-10
Build date: 2021-08-03 17:49:10 UTC

=== Build Information ===

Release ID: 810070017
Git revision: 503b9b053dff2e7f136e96b362a629c199f78a42
Build date: 2021-08-05 12:48:29-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Wed Jun 23 00:26:31 PDT 2021
    root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64


```

**Comment by chamons** [comment] 2021-09-14 16:24
I gave this a shot both in C# and Objc, and I can't reproduce the behavior.

What callback did you use for the included code? ViewDidLoad?

Please attach a sample project showing the behavior in question.

**Comment by unamed000** [comment] 2021-09-15 12:30
Hi @chamons 

Not sure why you won't be able to reproduce it. It's very easy to reproduce on my side. (Objective C and swift will work of course)
Here is the proof
![image](https://user-images.githubusercontent.com/10647722/133433379-86fb073b-2028-4907-aa13-4f8a5c786e10.png)

For the project, you just need to create a completely blank xamarin ios project, then put this ViewController as your RootViewController, then attach the debugger
```
using System;
using System.Drawing;
using UIKit;
using Foundation;

namespace IOSApp1
{
    [Register("ViewController")]
    public partial class ViewController : UIViewController
    {
        private UITextView _uiTextView;

        public ViewController() : base()
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            // Perform any additional setup after loading the view, typically from a nib.

            _uiTextView = new UITextView(View.Bounds);

            View.AddSubview(_uiTextView);

            var typingAttributes = new NSMutableDictionary();

            typingAttributes[UIStringAttributeKey.UnderlineStyle] = (NSNumber)1;
            typingAttributes[UIStringAttributeKey.Font] = UIFont.SystemFontOfSize(20);

            _uiTextView.TypingAttributes = typingAttributes;

            var hereComesTheNull = _uiTextView.TypingAttributes;
        }
    }
}
```

**Comment by chamons** [comment] 2021-09-15 15:45
I'm now able to reproduce your issue, and have gotten to the bottom of it.

You are getting null because of this precondition:

https://github.com/xamarin/xamarin-macios/blob/main/src/uikit.cs#L13665

```
			// this avoids a crash (see unit tests) and behave like UITextField does (return null)
			[PreSnippet ("if (SelectedRange.Length == 0) return null;", Optimizable = true)]
```

Adding 
```
            TextView.SelectedRange = new NSRange(0, 1);
```
to your sample returns non-null. 

I'm going to look into if we can safely remove the PreSnippet now, given how Xcode 12+ react.

**Comment by chamons** [comment] 2021-09-15 17:01
After discussion with the team, we're planning on keeping this quirk. The behavior is very old 5+ years, and chance of breaking customers is higher than the benefit.

If the work around is unacceptable, let me know and I'll get you a manual binding without the check.

**Comment by huyvuskedulo** [comment] 2021-09-15 17:52
Hi @chamons , thanks for the reply, but the workaround definitely does not work for our case and i doubt it will ever work for any cases when using the typingAttributes like this...

The reason we need it because we need to know when we can toggle off the Bold text style on cursor when we enable it. And when the user is typing, the SelectedLength will always be 0. So another binding will be helpful ....

**Comment by chamons** [comment] 2021-09-15 18:31
Give this a shot @huyvuskedulo 

```csharp
    public static class NSTextViewMonkeyPatch
    {
        [System.Runtime.InteropServices.DllImport("/usr/lib/libobjc.dylib", EntryPoint = "objc_msgSend")]
        extern static IntPtr IntPtr_objc_msgSend(IntPtr receiver, IntPtr selector);

        public static NSDictionary GetTypingAttributes (this UITextView view)
        {
            return ObjCRuntime.Runtime.GetNSObject<NSDictionary>(IntPtr_objc_msgSend(view.Handle, ObjCRuntime.Selector.GetHandle("typingAttributes")));
        }
    }
```

```csharp
            var hereComesTheNull = TextView.GetTypingAttributes();
```

**Comment by unamed000** [comment] 2021-09-16 05:19
Thanks @chamons , this seems to work perfectly for me.

**Comment by tipa** [comment] 2021-09-22 10:21
I just stumbled over this myself today (while implementing a bold toggle with the same reasoning as @huyvuskedulo) and spent like an hour googling and searching for the bug in my code.
I also verified that in Swift the `typingattributes` are actually returned and non-null, even when the `selectedrange` has a length of 0. I am also confused about the comment in the bindings referring to UIText**Field**, while this is about UIText**View**.

@chamons I would appreciate if you could reconsider changing the behavior since it's an apparent difference from the native behavior. If the fear of breaking old code is too high, please at least consider adding an additional property to the bindings similar to the workaround (which is working fine) and/or add a comment to the property so that other users find about this weird quirk quicker than I did.

**Comment by chamons** [comment] 2021-09-22 14:18
Reopening for consideration of an additional property + deprecating existing one.

**Comment by tipa** [comment] 2023-04-18 11:11
Have there been any considerations in the meantime? I would assume adding a new property and deprecating the old one shouldn't be too much of a problem, or is it?

**Comment by tipa** [comment] 2024-02-11 16:42
I am still using the workaround posted above. Is there any change this will be resolved in the future @rolfbjarne?

**Comment by rolfbjarne** [comment] 2024-02-12 10:34
> I am still using the workaround posted above. Is there any change this will be resolved in the future @rolfbjarne?

Fix in progress: https://github.com/xamarin/xamarin-macios/pull/20089

**Closed** 2024-02-13 07:28 UTC
Labels: bug, iOS
