### ISSUE TITLE
Invalid ToolChain iOS Publish 

### ISSUE THREAD

**Issue by AhmedAdelGadElkareeem** [xamarin/xamarin-macios#7400] opened 2019-11-11 08:32 UTC
### Steps to Reproduce
I want to publish my app to Apple Store using these versions :
- Visual studio Mac Version 8.3.7 ( build 1 )
- Xcode version Version 11.2 (11B52)
- Xamarin iOS Version: 13.6.0.12
but apple store reply on me by " Invalid ToolChain "

### Environment

```
```

**Comment by DamianMehers** [comment] 2019-11-11 13:57
This looks to be a duplicate of https://github.com/xamarin/xamarin-macios/issues/7349

The workaround that worked for me is to download the XCode GM, change your Visual Studio settings to point to this XCode, and rebuild and resubmit using the XCode GM: per this comment https://github.com/xamarin/xamarin-macios/issues/7349#issuecomment-550098042

**Comment by chamons** [comment] 2019-11-11 16:31
I believe @DamianMehers is correct, and this is a duplicate of #7349 

Please update, and open a new issue with more information if necessary.

**Closed by chamons** 2019-11-11 16:31 UTC

**Comment by AhmedAdelGadElkareeem** [comment] 2019-11-13 11:48
my issue already solved after install Xcode 11.2.1
