### ISSUE TITLE
Debugging not Possible on Apple Watch 5

### ISSUE THREAD

**Issue by SprengerS** [xamarin/xamarin-macios#9634] opened 2020-09-15 06:40 UTC
VS Mac Debugger not getting with a Debug App with Apple Watch 5 Device. The paired iPhone is connected via USB and the Debugger tries to connect via WiFi on port 10001. 

### Steps to Reproduce

1. Create a WatchApp with Armv7+Arm64 Architecture.
2. Add `--interpreter=all` as additional Monotouch Arguments
3. Deploy Debug Target to  iPhone and start Debugging

### Expected Behavior
1. App will be started on Apple Watch
2. Debugger will be connected 
### Actual Behaviour
1. Debugger tries to connect but connection will not be established because of `System.IO.IOException: DWP Handshake failed
### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.7.5 (build 19)
Installation UUID: 15e61cf8-1958-4c13-8382-8b037596ad0e
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

=== Roslyn (Language Service) ===

3.7.0-6.20412.3+d3c3a44a4e7ad31cc75c59be0d3df4a19ff33878

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.401/Sdks
SDK Versions:
	3.1.401
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.2.100
	2.1.701
	2.1.700
	2.1.505
	2.1.302
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.7
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.2.0
	2.1.21
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.2
	2.1.1
	2.0.5
	2.0.0

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.7 (16142)
Build 11E801a

=== Xamarin.Mac ===

Version: 6.20.2.2 (Visual Studio Community)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:44:59-0400

=== Xamarin.iOS ===

Version: 13.20.2.2 (Visual Studio Community)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:45:00-0400

=== Xamarin Designer ===

Version: 16.7.0.495
Hash: 03d50a221
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-08-28 13:12:52 UTC

=== Xamarin.Android ===

Version: 11.0.2.0 (Visual Studio Community)
Commit: xamarin-android/d16-7/025fde9
Android SDK: /Users/sprenger_m/Library/Android/sdk
	Supported Android versions:
		8.0 (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.1
SDK Build Tools Version: 30.0.0 rc1

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/sprenger_m/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-08-19 22:18:28 UTC

=== Android Device Manager ===

Version: 16.7.0.24
Hash: bb090a3
Branch: remotes/origin/d16-7
Build date: 2020-08-19 22:18:52 UTC

=== Build Information ===

Release ID: 807050019
Git revision: f2504848d2fad8637d40072e76f2d493f380241e
Build date: 2020-09-03 04:12:46-04
Build branch: release-8.7
Xamarin extensions: f2504848d2fad8637d40072e76f2d493f380241e

=== Operating System ===

Mac OS X 10.15.6
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Thu Jun 18 20:49:00 PDT 2020
    root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

MSBuild Editor 2.4.0

```

### Build Logs

[Build Log](https://gist.github.com/SprengerS/9c56d5af0b928975e06ea4cb187e011c)

[IDE Log](https://gist.github.com/SprengerS/0352371dd45f6b3004ef113daa2c24a4)

**Comment by rolfbjarne** [comment] 2020-09-15 10:47
This could be a duplicate of #8810.

In any case I can reproduce.

**Comment by chamons** [comment] 2021-11-15 14:50
Closing as duplicate of https://github.com/xamarin/xamarin-macios/issues/8810

**Closed by chamons** 2021-11-15 14:50 UTC
Labels: bug, iOS
