### ISSUE TITLE
iOS Class Library Cannot Access Packages From Referenced NETStandard Library

### ISSUE THREAD

**Issue by kspearrin** [xamarin/xamarin-macios#6451] opened 2019-06-27 16:10 UTC
### Steps to Reproduce

1. Using Xamarin.Forms project with iOS.
2. Create an additional netstandard2 class library. Install Json.NET to this library.
3. Create an additional iOS class library.
4. Reference iOS class library from iOS app.
5. Reference netstandard2 class library from XF app, iOS App, iOS Class library.

### Expected Behavior

Able to access JSON.NET namespaces from all projects.

### Actual Behavior

Cannot access Json.NET from iOS class library. Namespace not found.

Adding a reference to netstandard to iOS class library allows you to then access Json.NET namespaces there too.

```
    <PackageReference Include="NETStandard.Library">
      <Version>2.0.3</Version>
    </PackageReference>
```

### Environment

```
Microsoft Visual Studio Enterprise 2019
Version 16.1.4
VisualStudio.16.Release/16.1.4+29020.237
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Enterprise

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

Application Insights Tools for Visual Studio Package   9.1.00429.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.1.429.50124
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.1.429.50124
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.1.429.50124
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.9000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.1.429.50124
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.9000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.77 (master@24013d5)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

Microsoft Azure HDInsight Azure Node   2.3.9000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.9000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.5
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.9000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20419.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.1.1 (2473f22)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Open Command Line   2.1.218
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61904.23160
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.10506.2004
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.1.0-beta.19253.3+42526fe359672a05fd562dc16a91a43d0fe047a7
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.1.0.545 (d16-1@db7c858e8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.1.0.418 (remotes/origin/d16-1@5b958bb10)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.2.112 (4db4af4)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.3.0.23 (HEAD/d0b48056f)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2018-08@3a07bd426d3
    Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
    LibZipSharp: grendello/LibZipSharp/d16-1@44de300
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26


Xamarin.iOS and Xamarin.Mac SDK   12.10.0.157 (6bd9475)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Build Logs

```
1>------ Rebuild All started: Project: Core, Configuration: Debug Any CPU ------
1>Core -> C:\Users\me\Desktop\App5\App5\Core\bin\Debug\netstandard2.0\Core.dll
2>------ Rebuild All started: Project: App5, Configuration: Debug Any CPU ------
2>App5 -> C:\Users\me\Desktop\App5\App5\App5\bin\Debug\netstandard2.0\App5.dll
3>------ Rebuild All started: Project: iOS.Core, Configuration: Debug Any CPU ------
3>  Executing SayHello Task to establish a connection to a Mac Server. 
**REDACTED**
3>  Executing SayHello Task to establish a connection to a Mac Server. 
**REDACTED**
3>C:\Users\me\Desktop\App5\App5\iOS.Core\iOS.Core\Class1.cs(1,7,1,17): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
3>C:\Users\me\Desktop\App5\App5\iOS.Core\iOS.Core\Class1.cs(19,14,19,26): error CS0246: The type or namespace name 'JsonPropertyAttribute' could not be found (are you missing a using directive or an assembly reference?)
3>C:\Users\me\Desktop\App5\App5\iOS.Core\iOS.Core\Class1.cs(19,14,19,26): error CS0246: The type or namespace name 'JsonProperty' could not be found (are you missing a using directive or an assembly reference?)
4>------ Rebuild All started: Project: App5.iOS, Configuration: Debug iPhone ------
4>  Executing SayHello Task to establish a connection to a Mac Server. 
**REDACTED**
4>  Executing SayHello Task to establish a connection to a Mac Server. 
**REDACTED**
4>CSC : error CS0006: Metadata file 'C:\Users\me\Desktop\App5\App5\iOS.Core\iOS.Core\bin\Debug\iOS.Core.dll' could not be found
========== Rebuild All: 2 succeeded, 2 failed, 0 skipped ==========

```

### Example Project (If Possible)

See attached zip.

[App5.zip](https://github.com/xamarin/xamarin-macios/files/3335667/App5.zip)

Try to build iOS.Core project.

**Comment by spouliot** [comment] 2019-07-04 19:39
It's a compiler error (well before it reach the SDK) and it seems genuine to me - there's no reference in `iOS.Core` to the `Newtonsoft.Json` assembly, so the compiler does not load it and report it can't find the types.

It sounds like you're expecting a nugget package reference to be available to everything inside the solution ?

**Comment by kspearrin** [comment] 2019-07-04 22:51
`Json.NET NuGet Library <= Core Project <= iOS.Core Project <= App5.iOS Project`

I would expect to be able to access `Newtonsoft.Json` from any project in that chain. The fix/workaround wasn't to add a reference to Json.NET nuget package. Adding a reference to `NETStandard.Library` in `iOS.Core` allowed me to then reference `Newtonsoft.Json` in `App5.iOS`.

**Comment by rolfbjarne** [comment] 2019-07-05 09:22
This sounds like a duplicate of https://github.com/xamarin/xamarin-macios/issues/3949 (in particular see https://github.com/xamarin/xamarin-macios/issues/3949#issuecomment-420306411)

**Comment by kspearrin** [comment] 2019-07-05 15:26
Yes, that does seem like the same issue.

**Comment by spouliot** [comment] 2019-07-05 17:52
Alright, closing as duplicate - so all discussions are kept in a single place

**Closed by spouliot** 2019-07-05 17:52 UTC
Labels: iOS, need-info
