### ISSUE TITLE
[Bug] Error MT5216: Native Linking failed forlibOneSignal.iOS.Binding.dll.dylib

### ISSUE THREAD

**Issue by hartez** [xamarin/xamarin-macios#5012] opened 2018-10-19 04:18 UTC
_From @MarcusOy on October 12, 2018 13:16_

### Description
/Users/Marcus/Projects/xxx/_git/xxx/xxx/xxx.iOS/clang: Error: linker command failed with exit code 1 (use -v to see invocation) (xxx.iOS)

/Users/Marcus/Projects/xxx/_git/xxx/ElectionsClient/xxx.iOS/MTOUCH: Error MT5216: Native linking failed for '/Users/Marcus/Projects/xxx/_git/xxx/OneSignalNotificationServiceExtension/obj/iPhone/Debug/device-builds/iphone7.2-10.0.1/mtouch-cache/arm64/libOneSignal.iOS.Binding.dll.dylib'. Please file a bug report at http://bugzilla.xamarin.com (MT5216) (xxx.iOS)

So I'm trying to use a library called OneSignal for push notifications, however it is giving me the issue listed above. This only happens when compiling for IOS and for a physical device. I'm sure the library works fine in the Simulator, however, that is not for certain since the Simulator cannot receive push notifications. I do have a developer account with Apple, if that helps, with all necessary application extensions turned on (App Groups, Push Notifications, Remote Notifications, etc).
### Steps to Reproduce

1.  Create a new Forms project (Shared I believe)
2. Import NuGet packages: Com.OneSignal and Com.OneSignal.Abstrations
3. Compile for physical device

### Expected Behavior

App compiles, starts debugging on iPhone.

### Actual Behavior

See stack traces above

### Basic Information

- IDE: Visual Studio for Mac
- Platform Target Frameworks: IOS only issue
  - iOS:  Tried 8.0, 10.0, 12.0
- Nuget Packages: https://imgur.com/a/Ktqhka0
```
<packages>
  <package id="Acr.Support" version="2.1.0" targetFramework="xamarinios10" />
  <package id="Acr.UserDialogs" version="7.0.1" targetFramework="xamarinios10" />
  <package id="BTProgressHUD" version="1.2.0.6" targetFramework="xamarinios10" />
  <package id="Com.OneSignal" version="3.2.1" targetFramework="xamarinios10" />
  <package id="Microcharts" version="0.7.1" targetFramework="xamarinios10" />
  <package id="Microcharts.Forms" version="0.7.1" targetFramework="xamarinios10" />
  <package id="Microsoft.CSharp" version="4.5.0" targetFramework="xamarinios10" />
  <package id="Microsoft.NETCore.Platforms" version="2.1.1" targetFramework="xamarinios10" />
  <package id="Microsoft.Win32.Primitives" version="4.3.0" targetFramework="xamarinios10" />
  <package id="NETStandard.Library" version="2.0.3" targetFramework="xamarinios10" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="xamarinios10" />
  <package id="OxyPlot.Core" version="1.0.0" targetFramework="xamarinios10" />
  <package id="OxyPlot.Xamarin.Forms" version="1.0.0" targetFramework="xamarinios10" />
  <package id="OxyPlot.Xamarin.iOS" version="1.0.0" targetFramework="xamarinios10" />
  <package id="SkiaSharp" version="1.60.3" targetFramework="xamarinios10" />
  <package id="SkiaSharp.Views" version="1.60.3" targetFramework="xamarinios10" />
  <package id="SkiaSharp.Views.Forms" version="1.60.3" targetFramework="xamarinios10" />
  <package id="Splat" version="5.0.2" targetFramework="xamarinios10" />
  <package id="System.AppContext" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Collections" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.ComponentModel.TypeConverter" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Console" version="4.3.1" targetFramework="xamarinios10" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Diagnostics.Tracing" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Globalization" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Globalization.Calendars" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.IO" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.IO.Compression.ZipFile" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.IO.FileSystem" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Linq" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Net.Http" version="4.3.4" targetFramework="xamarinios10" />
  <package id="System.Net.Primitives" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Net.Sockets" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.ObjectModel" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Reflection" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Reflection.Extensions" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Reflection.Primitives" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Runtime" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Runtime.Handles" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Runtime.Serialization.Formatters" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Runtime.Serialization.Primitives" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.1" targetFramework="xamarinios10" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.2" targetFramework="xamarinios10" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Text.RegularExpressions" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Threading" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Threading.Timer" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.ValueTuple" version="4.5.0" targetFramework="xamarinios10" />
  <package id="System.Xml.ReaderWriter" version="4.3.1" targetFramework="xamarinios10" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="xamarinios10" />
  <package id="System.Xml.XmlDocument" version="4.3.0" targetFramework="xamarinios10" />
  <package id="Xamarin.Forms" version="3.2.0.871581" targetFramework="xamarinios10" />
</packages>
```
- Affected Devices: iPhone, NOT Simulator

_Copied from original issue: xamarin/Xamarin.Forms#4071_

**Comment by MarcusOy** [comment] 2018-10-19 13:39
I forgot about this Github issue, but I did get a bandaid resolution:

Switch configurations from Debug|iPhone to Release|iPhone. The OneSignal library has something wrong within it that causes a debug configuration to fail (according to the wiki), so testing on a physical device must be done on a release configuration. Simulator works in any circumstance.

**Comment by spouliot** [comment] 2018-10-19 19:46
@MarcusOy the fact that it works, in some configuration, generally means the native library is either mis-compiled or the binding project does not include the right arguments. Both are not issue in the Xamarin.iOS SDK.

I'd still like to confirm the issue, can you share a link to the wiki document you mentioned ? https://github.com/OneSignal/OneSignal-Xamarin-SDK does not seem to have any wiki page. 

Also a self-contained test case would help. I never used this library and just adding nugets to a project won't include the code in the application (it will be removed as unused) so I might not hit your issue. Thanks!

**Comment by MarcusOy** [comment] 2018-10-29 02:44
@spouliot This is the wiki page for OneSignal: https://documentation.onesignal.com/docs/xamarin-sdk-setup

I believe that there is a mishap with the library, nothing of the issue seems to be caused from the actual project or Xamarin.IOS.

**Comment by rolfbjarne** [comment] 2018-11-05 10:53
I was able to reproduce this problem, and this is the native linker's error:

```
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_UIActivityIndicatorView", referenced from:
          objc-class-ref in OneSignal.a(OneSignalWebView.o)
[...]
    ld: symbol(s) not found for architecture arm64
    clang : error : linker command failed with exit code 1 (use -v to see invocation)
```

The problem is that the `Com.OneSignal` bindings don't say they need the `UIKit` framework:

    Extracted third-party binding 'OneSignal.a' from '/Users/rolf/Projects/TestApp/packages/Com.OneSignal.3.2.1/lib/Xamarin.iOS10/OneSignal.iOS.Binding.dll' to '/Users/rolf/Projects/TestApp/NSExt/obj/iPhone/Debug/mtouch-cache/OneSignal.a'
        ForceLoad: True
        Frameworks: SystemConfiguration UserNotifications
        IsCxx: False
        LinkerFlags: 
        LinkTarget: 0
        NeedsGccExceptionHandling: False
        SmartLink: False
        WeakFrameworks: 

An additional condition is that `Incremental builds` must be enabled for this problem to surface (which is why it works for your release build: incremental builds is by default enabled for debug builds and disabled for release builds) - this is because when incremental builds is enabled, we compile each assembly to its own dynamic library, and we only link with the frameworks we known that each dynamic library needs. In this case, the OneSignal.iOS.Bindings.dll assembly doesn't state that it needs `UIKit`, so it ends up with linker errors. When incremental builds is disabled, we create one executable for all the assemblies, and we detect that other assemblies need `UIKit`, so the dependency is fulfilled.

This means there are a couple of ways to fix this:

* Disable incremental builds in the iOS Build options, since the Com.OneSignal bindings don't support it.
* Ask Com.OneSignal to fix their bindings.

I'm closing this, since it's not a bug in Xamarin.iOS.

**Closed by rolfbjarne** 2018-11-05 10:53 UTC
Labels: iOS, need-info, support

**Comment by tiagocrizanto** [comment] 2018-11-29 14:20
Look the architecture you're build your project. I get this error when build my application with ARMv7s + ARM64. Change to build only for ARM64 solved my problem with onesignal.
