### ISSUE TITLE
[iOS] Recurring app crashes on launch in Debug mode

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#9779] opened 2020-10-05 11:08 UTC
# Steps to Reproduce
It's not as easily to reproduce as I wish it would be, but for me this happens when running the app (successfully), then making a code-change and try to run it again. The app is deployed, the launch screen shows for a very short time, then the app closes down. The same happens when trying to launch the app by clicking on the app icon with no VS involved. This happens for both physical device and simulator.
Completely rebuilding the app from scratch resolves the issue, meaning that it will launch again once. But after a code change and rebuild, the same issue occurs again.

Sometimes it also works for a longer period of time, then the next day it's broken again. But I've seen this problem for way too often and long for at least a few months now.
I sometimes work on VS for Mac and sometimes on VS on Windows (being paired to that Mac) if that has any relevance.

### Expected Behavior
I can change code, rebuild the app and it will keep launching

### Actual Behavior
After a code change, the app often does not launch. There are no error logs in the VS output window.
In the macOS console app, I can find crash reports of the device, indicating there is some Bindings library (that I imported via NuGet - in this case `MBProgressHUD`) missing:

```
Process:               MyApp.iOS [15378]
Path:                  /Users/USER/Library/Developer/CoreSimulator/Devices/ADFCD4E0-9E95-414D-9866-005C466B7983/data/Containers/Bundle/Application/CD537F6B-D74A-4034-89F4-6A3E06E30041/MyApp.iOS.app/MyApp.iOS
Identifier:            MyApp.iOS
Version:               2.5.3 (1.8.17)
Code Type:             X86-64 (Native)
Parent Process:        launchd_sim [12204]
Responsible:           SimulatorTrampoline [1997]
User ID:               501

Date/Time:             2020-10-05 09:02:06.056 +0200
OS Version:            Mac OS X 10.16 (20A5384c)
Report Version:        12
Bridge OS Version:     5.0 (18P50390a)
Anonymous UUID:        36B15FBB-7C89-1F79-7157-70A767AB38EC


Time Awake Since Boot: 55000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_SHARED_CACHE_DIR=/Users/timopartl/Library/Developer/CoreSimulator/Caches/dyld/20A5384c/com.apple.CoreSimulator.SimRuntime.iOS-14-0.18A372
DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
DYLD_FALLBACK_FRAMEWORK_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks
DYLD_FALLBACK_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib

Dyld Error Message:
  dyld: Using shared cache: C8C7DC6C-A9ED-363C-950F-5C4929FD07E8
Library not loaded: @rpath/MBProgressHUD.framework/MBProgressHUD
  Referenced from: /Users/USER/Library/Developer/CoreSimulator/Devices/ADFCD4E0-9E95-414D-9866-005C466B7983/data/Containers/Bundle/Application/CD537F6B-D74A-4034-89F4-6A3E06E30041/MyApp.iOS.app/MyApp.iOS
  Reason: image not found
```

I then tried to remove all references of that library in my code, but then another library (that was also imported via NuGet) was not found so it's not specific to that one binding

### Environment
```
=== Visual Studio Community 2019 for Mac ===

Version 8.7.8 (build 4)
Installation UUID: 0c7af5e5-7087-40ae-a5e1-2958b1da596f
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

=== Roslyn (Language Service) ===

3.7.0-6.20427.1+18ede13943b0bfae1b44ef078b2f3923159bcd32

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.402/Sdks
SDK-Versionen:
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.503
	2.1.302
MSBuild-SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core-Runtime ===

Laufzeit: /usr/local/share/dotnet/dotnet
Laufzeitversionen:
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.7
	2.1.2

=== Xamarin.Profiler ===

Version: 1.6.15.68
Speicherort: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.0.1 (17220)
Build 12A7300

=== Xamarin.Android ===

Nicht installiert

=== Microsoft OpenJDK for Mobile ===

Java SDK: Nicht gefunden

Android Designer EPL-Code ist hier verfügbar:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-09-16 05:12:24 UTC

=== Android Device Manager ===

Version: 16.7.0.24
Hash: bb090a3
Branch: remotes/origin/d16-7
Build date: 2020-09-16 05:12:46 UTC

=== Xamarin Designer ===

Version: 16.7.0.495
Hash: 03d50a221
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-08-28 13:12:52 UTC

=== Xamarin.Mac ===

Version: 6.20.2.2 (Visual Studio Community)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:44:59-0400

=== Xamarin.iOS ===

Version: 14.0.0.0 (Visual Studio Community)
Hash: 7ec3751a1
Branch: xcode12
Build date: 2020-09-16 11:33:15-0400

=== Build Information ===

Release ID: 807080004
Git revision: 9ea7bef96d65cdc3f4288014a799026ccb1993bc
Build date: 2020-09-16 17:22:54-04
Build branch: release-8.7
Xamarin extensions: 9ea7bef96d65cdc3f4288014a799026ccb1993bc

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.1.0 Darwin Kernel Version 20.1.0
    Thu Sep 24 20:22:06 PDT 2020
    root:xnu-7195.40.89.100.3~1/RELEASE_X86_64 x86_64
```

**Comment by rolfbjarne** [comment] 2020-10-05 12:45
This may have been fixed in our next major release. Would it be possible for you to try a preview package ([xamarin.ios-14.4.0.12.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/d16-8/0c7bba361d1a6d5388f1028704180ae650d219e3/36/package/notarized/xamarin.ios-14.4.0.12.pkg)) to see if it works for you? It'll probably be easier to test this package while working on VS for Mac, since otherwise VS for Windows will say you have the wrong version installed.

**Comment by tipa** [comment] 2020-10-05 15:46
Thanks - looks pretty good so far with the preview package you provided.
Finally no more crashes - what a relief!! I lost so much time with rebuilding the whole app after every change... :D

**Comment by rolfbjarne** [comment] 2020-10-06 06:55
That's great! I'm closing this then, but feel free to reopen if it shows up again.

**Closed by rolfbjarne** 2020-10-06 06:55 UTC
Labels: bug, iOS

**Comment by tipa** [comment] 2020-10-08 17:21
@rolfbjarne not sure if that issue is related, but since I am using the package you provided I occasionally get this error - rebuilding the app completely usually fixes it again:
```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.Common.targets(451,3): error MSB4018: Unerwarteter Fehler bei der DetectSdkLocations-Aufgabe.
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.Common.targets(451,3): error MSB4018: System.MissingMethodException: Method not found: string Xamarin.Localization.MSBuild.MSBStrings.get_E0083()
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.Common.targets(451,3): error MSB4018:   at Xamarin.Mac.Tasks.DetectSdkLocationsTaskBase.Execute () [0x0000b] in <d017cb344f634ca38ded1ddbdf8b14c4>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.Common.targets(451,3): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:575 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.Common.targets(451,3): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002a9] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:818 
```

**Comment by rolfbjarne** [comment] 2020-10-09 07:35
@tipa thanks for the report, I think I know what's going on. This comes from having a different version of Xamarin.Mac and Xamarin.iOS installed (which we support, but sometimes we have bugs that we need to fix). I've filed https://github.com/xamarin/xamarin-macios/issues/9830 for it.

**Comment by tipa** [comment] 2020-10-14 18:14
@rolfbjarne I am experiencing another issue with the 14.4.0.12 package. Very often Visual Studio does not rebuild the app once I make a change to the source code - it just re-launches the app in the simulator. I have to manually rebuild the app completely, which is very time-consuming

**Comment by rolfbjarne** [comment] 2020-10-14 18:16
@tipa that's unfortunate 😒 would it be possible for you to enable diagnostic build logs, and get the resulting build log when the app doesn't rebuild?

**Comment by tipa** [comment] 2020-10-15 19:47
It seems like no build is triggered so no text is appended in the "Build output" window...
It just deploys the app to the simulator.

**Comment by rolfbjarne** [comment] 2020-10-16 06:19
@tipa Yes, that sounds like your problem. I would suggest commenting on that bug or create your own (that way the VS team knows the issue is affecting more people, and will prioritize the problem accordingly).
