### ISSUE TITLE
[Bug] [iOS] Tap GestureRecognizers not working in iOS 13.4

### ISSUE THREAD

**Issue by RobDaytona** [xamarin/xamarin-macios#8547] opened 2020-05-02 06:21 UTC
xamarin/Xamarin.Forms#7922 # Description

The game we are developing, was yesterday for the first time simulated on IOS and also deployed to an iPhone. In both simulations and the actual device, there are areas in the game with the TapGesture Recogniser / Tap Event is broken on IOS. Everything happy in Android as its always been.

All the code is the shared project.

The bug happens in areas where a TapGesture has been added to a BoxView, however this is how we handle all tap events in the game, and there are many areas in the game where this works just fine, which will make tracking down this bug harder....

I am sure that this bug is related to : [Bug] [iOS] GestureRecognizers not working in iOS 13.4 xamarin/Xamarin.Forms#10162 

Which apparently has been fixed, however possibly there is somewhere else in your source code that needs to be fixed in a similar manner that was missed? - if possible can you guys take a look again? see if there is any spot you missed?

Our project is huge, and its going to take me a while and a lot of effort to try to create a one page project with steps to reproduce, (something I am working on as we speak), so please be patient on that, I will get you steps to reproduce as soon as I possibly can. I have posted the bug, here so we can get the ball rolling on this one, its a critical critical issue, not being able to handle tap events!

### Steps to Reproduce

Working furiously to get you a mini project to look at.

- IDE: VS Mac 8.5.4 (build 12)
-  iOS 13.4
(Everything mono, etc.. was setup on the mac yesterday, and paired with the PC (which was also upgraded to the latest everything, pair and simulation on pc worked fine)
The build and deploy to the iPhone was done on the Mac directly.

**Comment by samhouts** [comment] 2020-05-07 21:44
@thisismyself Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by dalexsoto** [comment] 2020-05-07 21:48
@thisismyself also make sure that you have the latest stable Xamarin.iOS as of today (Xamarin.iOS 13.16.0.13) and that you **do not have Xamarin.iOS 13.16.0.11** in any of your two machines.

**Comment by thisismyself** [comment] 2020-05-14 16:20
@samhouts @dalexsoto I cannot reproduce the issue anymore. We guess the installation of Xamarin.iOS 13.16.0.13 package update failed on the failing Mac and we didn't notice this. Thank you for help.

**Comment by whitneyschmidt** [comment] 2020-05-27 21:29
Closing as this issue as it is no longer repro. 

@thisismyself @RobDaytona thank you for sharing this issue with us, if you begin encountering it again feel free to reopen this issue.

**Closed by whitneyschmidt** 2020-05-27 21:29 UTC
Labels: need-info

**Comment by RobDaytona** [comment] 2020-06-23 13:53
@thisismyself @whitneyschmidt @samhouts @dalexsoto thank you all for subsequent posts to my work around, glad its been fixed!!!
