### ISSUE TITLE
System.IO.IOException (sharing violation) when building iOS project

### ISSUE THREAD

**Issue by DaRosenberg** [xamarin/xamarin-macios#3594] opened 2018-02-26 00:31 UTC
### Steps to Reproduce

1. Clean solution
2. Build iOS project
3. Debug
4. Stop
5. Debug again
6. Build fails

### Expected Behavior

Build should work more than one time.

### Actual Behavior

On every build, except the very first build after doing a clean, the following error is printed in the build output window:

```
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(777,3): error : Unexpected error - Please file a bug report at http://bugzilla.xamarin.com
1>  System.IO.IOException: Sharing violation on path /Users/danielstolt/Library/Caches/Xamarin/mtbs/builds/IDeliverable.Retrospect.Xamarin.iOS/769cc7daf40cafe28c0e7d1a7ea4d934/obj/iPhoneSimulator/DebugSampleData/mtouch-cache/PreBuild/System.Net.Http.Formatting.dll
1>    at System.IO.File.SetLastWriteTime (System.String path, System.DateTime lastWriteTime) [0x0002b] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/File.cs:488 
1>    at System.IO.File.SetLastWriteTimeUtc (System.String path, System.DateTime lastWriteTimeUtc) [0x00000] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/File.cs:493 
1>    at System.IO.FileSystemInfo.set_LastWriteTimeUtc (System.DateTime value) [0x00016] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/io/filesysteminfo.cs:312 
1>    at System.IO.FileSystemInfo.set_LastWriteTime (System.DateTime value) [0x00000] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/io/filesysteminfo.cs:275 
1>    at Xamarin.Bundler.Driver.Touch (System.Collections.Generic.IEnumerable`1[T] filenames, System.Nullable`1[T] timestamp) [0x0002c] in /Users/builder/data/lanes/5665/db807ec9/source/xamarin-macios/tools/mtouch/mtouch.cs:806 
1>    at Xamarin.Bundler.Driver.Touch (System.String[] filenames) [0x00001] in /Users/builder/data/lanes/5665/db807ec9/source/xamarin-macios/tools/mtouch/mtouch.cs:811 
1>    at Xamarin.Bundler.Target.ManagedLink () [0x00b3b] in /Users/builder/data/lanes/5665/db807ec9/source/xamarin-macios/tools/mtouch/Target.cs:710 
1>    at Xamarin.Bundler.Target.ProcessAssemblies () [0x000bb] in /Users/builder/data/lanes/5665/db807ec9/source/xamarin-macios/tools/mtouch/Target.cs:800 
1>    at Xamarin.Bundler.Application.ProcessAssemblies () [0x0002f] in /Users/builder/data/lanes/5665/db807ec9/source/xamarin-macios/tools/mtouch/Application.cs:1407 
1>    at Xamarin.Bundler.Application.BuildManaged () [0x00001] in /Users/builder/data/lanes/5665/db807ec9/source/xamarin-macios/tools/mtouch/Application.cs:831 
1>    at Xamarin.Bundler.Application+<>c.<BuildAll>b__134_1 (Xamarin.Bundler.Application v) [0x00000] in /Users/builder/data/lanes/5665/db807ec9/source/xamarin-macios/tools/mtouch/Application.cs:779 
1>    at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x00024] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
1>    at Xamarin.Bundler.Application.BuildAll () [0x00050] in /Users/builder/data/lanes/5665/db807ec9/source/xamarin-macios/tools/mtouch/Application.cs:779 
1>    at Xamarin.Bundler.Driver.Main2 (System.String[] args) [0x00481] in /Users/builder/data/lanes/5665/db807ec9/source/xamarin-macios/tools/mtouch/mtouch.cs:1403 
1>    at Xamarin.Bundler.Driver.Main (System.String[] args) [0x00015] in /Users/builder/data/lanes/5665/db807ec9/source/xamarin-macios/tools/mtouch/mtouch.cs:928 
========== Build: 0 succeeded, 1 failed, 17 up-to-date, 0 skipped ==========
```

Cleaning the solution again allows one build to succeed - after that, the next one will fail again with the same error message.

### Environment Windows

```
Microsoft Visual Studio Professional 2017 
Version 15.5.7
VisualStudio.15.Release/15.5.7+27130.2036
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Professional

Microsoft Visual Studio Tools for Applications 2017   00369-60000-00001-AA734
Microsoft Visual Studio Tools for Applications 2017

Visual Basic 2017   00369-60000-00001-AA734
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA734
Microsoft Visual C# 2017

Visual F# 4.1   00369-60000-00001-AA734
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.10.01106.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.31129.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.51007.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.31106.0
Azure App Service Tools v3.0.0

CodeRush for Roslyn   17.2.6.0
DevExpress CodeRush for Roslyn package.

CodeRush for Roslyn Tool Windows   17.2.6.0
DevExpress CodeRush for Roslyn Tool Windows package.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

EditorConfig Language Service   1.17.237
Language service for .editorconfig files.

EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

File Icons   2.7
Adds icons for files that are not recognized by Solution Explorer

File Nesting   2.6.67
Automatically nest files based on file name and enables developers to nest and unnest any file manually

GitHub.VisualStudio   2.4.2.1331
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Service Fabric Tools for Visual Studio   2.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51120.3

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.8.4-pre (3fe64e3)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.4.11025.7
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   2.1.179
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

SQL Server Data Tools   15.1.61710.120
Microsoft SQL Server Data Tools

SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 14.0.800.98

Syntax Highlighting Pack   2.8.133
Adds syntax highlighting and snippet support for a wide variety of programming languages such as Clojure, Go, Jade, Lua, Swift, Ruby and many more...

TypeScript Tools   15.5.11025.1
TypeScript Tools for Microsoft Visual Studio

WebJobs Tools v1.0.0   15.0.40108.0
WebJobs Tools v1.0.0

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.27130.2036
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.8.0.760 (fc93f3f5b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.8.188 (c5813fa34)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.1.5.0 (HEAD/75f8c6838)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.6.1.4 (db807ec)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Environment Mac

```
=== Visual Studio Professional 2017 for Mac ===

Version 7.3.3 (build 23)
Installation UUID: 18b1cf61-9d12-4056-852a-6a64a98fb8d6
Runtime:
	Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010007

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.0.0.216 (Visual Studio Professional)

=== Xamarin.Android ===

Version: 8.1.5.0 (Visual Studio Professional)
Android SDK: /Users/danielstolt/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)

SDK Tools Version: 25.1.2
SDK Platform Tools Version: 24.0.0
SDK Build Tools Version: 23.0.2

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin.iOS ===

Version: 11.6.1.4 (Visual Studio Professional)
Hash: db807ec9
Branch: xcode9.2
Build date: 2018-01-10 16:45:48-0500

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 703030023
Git revision: e02ab111d8181ffe766c2258141282c88188ebb6
Build date: 2018-02-20 08:06:38-05
Xamarin addins: 5ce2b6790676a4542aa0d69d07f6a716e17d4e65
Build lane: monodevelop-lion-d15-5

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1

```

### Build Logs

https://gist.github.com/DaRosenberg/5bfb4d06520e2f7bba72e5a347dd847d

**Comment by rolfbjarne** [comment] 2018-02-26 06:23
This is a duplicate of https://bugzilla.xamarin.com/show_bug.cgi?id=60149.

It has already been fixed (e4d9895365bb0ed93733642b1e3eb7b640e0ffb8) and the fix included in the next stable release which will be out in a couple of weeks (it's in the Beta channel right now if you want to try it).

**Closed by rolfbjarne** 2018-02-26 06:23 UTC

**Comment by DaRosenberg** [comment] 2018-02-26 14:43
Thanks @rolfbjarne - do I need to run a preview of VS on Windows too, or can I update only VS for Mac on the Beta channel and keep using the stable Windows version?

**Comment by rolfbjarne** [comment] 2018-02-26 16:01
@DaRosenberg I recommend using the same version on both Mac and Windows, otherwise you can run into strange problems.
