### ISSUE TITLE
iOS CFNetworkHandler crash app if the app is put to background.

### ISSUE THREAD

**Issue by jonathanantoine** [xamarin/xamarin-macios#5337] opened 2019-01-03 11:47 UTC
iOS CFNetworkHandler crash app if the app is put to background while a request is ongoing.

### Steps to Reproduce
Uses the repro sample : [CFNetworkHandlerCrash.zip](https://github.com/xamarin/xamarin-macios/files/2723593/CFNetworkHandlerCrash.zip)

1. Launch the app.
2. Wait for this log to be displayed 'Batch X created'.
3. Wait 1 second.
4. Put the app in background ( press the home button for example).
5. Wait 10 seconds and put the app back to foreground.
6. Notice the exception is throwned.

(I sometimes have to do it several times for the bug to happen).

### Actual Behavior

A NullReferenceException is throwned and the app crash with this stacktrace :

```  at System.Net.Http.CFNetworkHandler.HandleHasBytesAvailableEvent (System.Object sender, CoreFoundation.CFStream+StreamEventArgs e) [0x0002f] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/System.Net.Http/CFNetworkHandler.cs:361 
  at CoreFoundation.CFStream.OnHasBytesAvailableEvent (CoreFoundation.CFStream+StreamEventArgs args) [0x0000a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/CoreFoundation/CFStream.cs:415 
  at CoreFoundation.CFStream.OnCallback (CoreFoundation.CFStreamEventType type) [0x00045] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/CoreFoundation/CFStream.cs:465 
  at CoreFoundation.CFStream.OnCallback (System.IntPtr s, System.nint type, System.IntPtr info) [0x00013] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/CoreFoundation/CFStream.cs:451 
  at (wrapper native-to-managed) CoreFoundation.CFStream.OnCallback(intptr,System.nint,intptr)
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/UIKit/UIApplication.cs:63 
  at ReproTaskPoolNotWorking.Application.Main (System.String[] args) [0x00001] in /Users/jonathanantoine/Projects/ReproTaskPoolNotWorking/ReproTaskPoolNotWorking/Main.cs:12 
--- End of stack trace from previous location where exception was thrown ---
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.12/src/Xamarin.iOS/UIKit/UIApplication.cs:63 
  at ReproTaskPoolNotWorking.Application.Main (System.String[] args) [0x00001] in /Users/xxx/Projects/ReproTaskPoolNotWorking/ReproTaskPoolNotWorking/Main.cs:12 
```

### Environment

```
Release ID: 707020021
Git revision: f1fea53df9eb0bb5890a9563c0d7ea7b03922144
Build date: 2018-12-14 18:37:35+00
Build branch: release-7.7
Xamarin extensions: 9c5cea335e6a9ce4ccfde31c4aa06c25a3576085

=== Operating System ===

Mac OS X 10.14.1
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Fri Oct  5 19:41:49 PDT 2018
    root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

LiveXAML 1.3.31
NuGet Package Management Extensions 0.13


```

### Build Logs

None
### Example Project (If Possible)

[CFNetworkHandlerCrash.zip](https://github.com/xamarin/xamarin-macios/files/2723593/CFNetworkHandlerCrash.zip)

**Comment by spouliot** [comment] 2019-01-03 13:59
more complete stack trace
```
System.NullReferenceException: Object reference not set to an instance of an object
  at System.Net.Http.CFContentStream.ReadStreamData () [0x00018] in /Users/poupou/git/master/xamarin-macios/external/mono/mcs/class/System.Net.Http/CFContentStream.cs:110
  at System.Net.Http.CFNetworkHandler.HandleHasBytesAvailableEvent (System.Object sender, CoreFoundation.CFStream+StreamEventArgs e) [0x0002f] in /Users/poupou/git/master/xamarin-macios/external/mono/mcs/class/System.Net.Http/CFNetworkHandler.cs:278
  at CoreFoundation.CFStream.OnHasBytesAvailableEvent (CoreFoundation.CFStream+StreamEventArgs args) [0x0000a] in /Users/poupou/git/master/xamarin-macios/src/CoreFoundation/CFStream.cs:415
  at CoreFoundation.CFStream.OnCallback (CoreFoundation.CFStreamEventType type) [0x00045] in /Users/poupou/git/master/xamarin-macios/src/CoreFoundation/CFStream.cs:465
  at CoreFoundation.CFStream.OnCallback (System.IntPtr s, System.nint type, System.IntPtr info) [0x00013] in /Users/poupou/git/master/xamarin-macios/src/CoreFoundation/CFStream.cs:451
  at at (wrapper native-to-managed) CoreFoundation.CFStream.OnCallback(intptr,System.nint,intptr)
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/poupou/git/master/xamarin-macios/src/UIKit/UIApplication.cs:79
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Users/poupou/git/master/xamarin-macios/src/UIKit/UIApplication.cs:63
  at ReproTaskPoolNotWorking.Application.Main (System.String[] args) [0x00001] in /Users/poupou/Downloads/ReproTaskPoolNotWorking-3/ReproTaskPoolNotWorking/Main.cs:12
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/poupou/git/master/xamarin-macios/src/UIKit/UIApplication.cs:79
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Users/poupou/git/master/xamarin-macios/src/UIKit/UIApplication.cs:63
  at ReproTaskPoolNotWorking.Application.Main (System.String[] args) [0x00001] in /Users/poupou/Downloads/ReproTaskPoolNotWorking-3/ReproTaskPoolNotWorking/Main.cs:12
```

**Comment by spouliot** [comment] 2019-01-03 14:03
There are two more issues pending backport/fix for CFNetworkHandler
* https://github.com/mono/mono/pull/12153
* https://github.com/xamarin/xamarin-macios/issues/5289

I'll look into this one once the above are merged into master.

**Comment by spouliot** [comment] 2019-01-08 20:13
The first fix (from above) was merged
and the second one is now PR'ed https://github.com/mono/mono/pull/12321

**Comment by spouliot** [comment] 2019-12-06 22:16
Both were merged and a lot of other changes also happened since then...
I'm not able to reproduce this anymore using the sample.
If this still happens please re-open an issue and link back to this one along with additional informations. Thanks!

**Closed by spouliot** 2019-12-06 22:16 UTC
Labels: bug, iOS, macOS
