### ISSUE TITLE
[Feature Request] Side by Side SDK Support

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#6106] opened 2019-05-22 19:33 UTC
Over time we've had a number of requests for "side by side" support in the IDE.

Example: https://developercommunity.visualstudio.com/content/problem/314863/xamarinios-on-the-should-support-sxs-installations.html

There are a number of open questions on what that would entail:

- Do we have a global Current pointer (like we do now) or somehow projects know which version to use
- Would we need some xcode-select style tool to manipulate it
- How does this interact with msbuild and assembly resolution, etc.

This issue is a meta issue to track interest. Creating this issue does not imply that this is being worked on actively or will happen in the future.

**Comment by spouliot** [comment] 2019-05-22 20:00
_Edited copy/paste from my bits on a similar issue (December 5th, 2018)_ https://dev.azure.com/devdiv/DevDiv/_workitems/edit/712815

The biggest impact of SxS support for XI (and XM) is not in the SDK themselves. IOW the SDK can already exists side-by-side (it's been the case since we moved out of `/Developer/` circa our unified/64bits support).

The main reasons it does not work (as expected) are:

**mono / msbuild**

On the mac we have a single system mono that points back to the (XI/XM) SDK targets. It can't point to many (just one) - unless we have separate mono as well. That could be a good thing anyway, since each version of the SDK is tested against a specific mono - but it's another pandora box with its share of surprises.

My understanding is that moving to SDK projects might help (and that should be on the roadmap soon but it might not be enough). Maybe .NET 5 will help/force us...

**UI vs disk space**

We can allow side-by-side installations (not removing old versions when installing new ones) but this will fill the disk space very quickly (limited SSD).

There needs to be a way, in both IDE, to manage/remove SDK versions and, ideally, something that won't conflict between VS(Win) and VS4Mac.

**Xcode**

You can have several Xcode installed side-by-side - but some stuff is updated globally (e.g. device support, command line tools...). That should not be a huge problem, just a limit to how old we can support SxS installs.

This will however cause scripting issues (like having more than a single mono) since build script that "shells out" might not be using the Xcode they were intended to run from. E.g. the "default/system" Xcode might not have the tool/option a build script needs, causing errors that won't be reproducible on another computer.

**Comment by jeromelaban** [comment] 2019-05-23 12:11
Thanks @spouliot for the details. If it were this easy to do, it would have already be done ;)

It's mostly a matter of making the switch between versions easier (as it can already be done with CI). For instance, a short term adjustment would be to cache the installers that VS pulls when switching between a VS4Win Preview and stable.

**Comment by chamons** [comment] 2020-03-27 19:29
I suspect this may be solved with the [.NET 5](https://github.com/xamarin/xamarin-macios/issues/7528) work, but am not 100% certain.

**Comment by rolfbjarne** [comment] 2020-03-30 07:26
> I suspect this may be solved with the [.NET 5](https://github.com/xamarin/xamarin-macios/issues/7528) work, but am not 100% certain.

Yes, it will be solved with .NET 5.

> * Do we have a global Current pointer (like we do now) or somehow projects know which version to use

Projects will be able to specify the exact version to use, there will be no global/system version (however, there will be a default version depending on which .NET version is installed).

> We can allow side-by-side installations (not removing old versions when installing new ones) but this will fill the disk space very quickly (limited SSD).

The .NET 5 way seems to be to fill up your disk, nothing seems to be uninstalled ever.

**Comment by MichaelRumpler** [comment] 2020-03-30 07:46
> The .NET 5 way seems to be to fill up your disk, nothing seems to be uninstalled ever.

That's not an option of course.

It won't be easy to decide, when an old version can be removed. Especially when multiple Windows machines with different VS versions are paired to the same Mac.
You could remember when which version was used and then delete those which have not been used in e.g. a month (with a setting for the elapsed time).

**Comment by rolfbjarne** [comment] 2020-03-30 07:50
> > The .NET 5 way seems to be to fill up your disk, nothing seems to be uninstalled ever.
> 
> That's not an option of course.
> 
> It won't be easy to decide, when an old version can be removed. Especially when multiple Windows machines with different VS versions are paired to the same Mac.
> You could remember when which version was used and then delete those which have not been used in e.g. a month (with a setting for the elapsed time).

My point here really is that this is not a problem for us (the Xamarin.iOS team) to solve, it's a problem that should be solved generally for all of .NET 5 (afaik work is in progress on it).

**Comment by whitneyschmidt** [comment] 2020-07-22 18:06
_Edited Copy/Paste from a related issue (June 17, 2020)_
https://developercommunity.visualstudio.com/content/problem/1117465/why-downgrade-xamarin-ios-sdk.html

**Feedback**:
When selecting an bit older project  there VS wants to install the older SDK … changing back to the newer Project will cost a lot of time to reinstall that SDK again. why is it removed?? this cost me so much time!

“The Xamarin.iOS SDK version ‘13.20.1.18’ that is installed on the Mac is not compatible with this version of Visual Studio. Would you like us to install Xamarin.iOS ‘13.18.2.1’ for you? This will overwrite any other existing Xamarin.iOS installation on your Mac.”

**Comment by MichaelRumpler** [comment] 2021-08-06 07:54
After you skipped .NET5 last year, how are the chances that we get this in November 2021?

I just got asked in [this ticket](https://developercommunity.visualstudio.com/t/Mac-build-host-disconnects-after-a-few-s/1399299) to test in a preview version and ran into this issue again.

**Comment by rolfbjarne** [comment] 2022-09-27 07:07
This is solved in .NET.

**Closed by rolfbjarne** 2022-09-27 07:07 UTC
Labels: enhancement, macOS, iOS
