### ISSUE TITLE
iOS simulators are not showing up.

### ISSUE THREAD

**Issue by KKS91** [xamarin/xamarin-macios#18047] opened 2023-04-13 09:14 UTC
Hello,
I've upgraded my VS2020 to the latest version and now Xcode is not showing up.

I've following installed.
Visual Studio Community 2022 for Mac
Version 17.5.3 (build 15)
Xamarin.iOS
Version: 16.2.0.5 Visual Studio Community
Hash: 7738c90c9
Branch: xcode14.2
Build date: 2023-01-25 15:56:15-0500

Installed XCode Version 14.3 (14E222b) 

I've also tried with downgrading Xcode command line option to 14.2 but result didn't change.

Thanks!
Kundan

**Comment by rolfbjarne** [comment] 2023-04-13 15:06
This is a duplicate of https://github.com/xamarin/xamarin-macios/issues/17561, please read that issue for workarounds (downgrade to Xcode 14.2) or using newer packages.

**Closed by rolfbjarne** 2023-04-13 15:06 UTC
