### ISSUE TITLE
Xamarin app build failed with Xcode 12

### ISSUE THREAD

**Issue by vsafonkin** [xamarin/xamarin-macios#9960] opened 2020-10-26 13:37 UTC
Hello, I have an issue with Xcode 12 that used through symlink. I'm using `/Applications/Xcode.app` symlink to point real Xcode files. App build is successful if the symlink points to Xcode 11.7, but failed if the symlink points to Xcode 12
### Steps to Reproduce

1. Store Xcode 12 in any directory
2. Create symlink Xcode.app in `/Applications` directory that points to Xcode 12
3. Run build

### Expected Behavior
Build is successful

### Actual Behavior
Build is failed

### Environment

Xamarin-iOS 13.20 or 14.00
macOS-10.15
Azure DevOps CI environment: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md

### Build Logs

[8_Build Xamarin.iOS solution UsingUITest.sln.txt](https://github.com/xamarin/xamarin-macios/files/5439036/8_Build.Xamarin.iOS.solution.UsingUITest.sln.txt)

**Comment by rolfbjarne** [comment] 2020-10-26 13:48
Yes, we've run into the same problem when using Xcode through a symlink.

Unfortunately, the only solution we've found is to not use Xcode through a symlink.

As far as we can tell, this is not a bug in Xamarin.iOS/Xamarin.Mac, so I'm closing this.

**Closed by rolfbjarne** 2020-10-26 13:48 UTC

**Comment by jeromelaban** [comment] 2020-10-29 13:02
The fix for this issue is overriding the default configuration set by xcode-select, which breaks Xamarin.UITest (for which there's no support for iOS 14, yet).

https://github.com/microsoft/appcenter/issues/1992
