### ISSUE TITLE
[tvOS, Xcode10]NWPathTest.HasIPV6PropertyTest failure in monotouch-tests

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#4808] opened 2018-09-13 16:43 UTC
### Steps to Reproduce

1. Install XI 11.99.3.608 (xcode10: 2c8f8828) 
2. Execute monotouch-test on tvOS device

### Expected Behavior
All tests should pass.
### Actual Behavior
[FAIL] NWPathTest.HasIPV6PropertyTest :   By default the interface does not support IPV6
### Environment
```
Bot Name: XQA-XI-Sierra-tvOS-1
Mono version: 5.12.0.307 (c5b8988d22e)  (2018-08-27 20:12:54 -04:00)
XA version: 9.0.0.20 (HEAD/86d33f45b) 
XI version: 11.99.3.608 (xcode10: 2c8f8828) 
XM version: 4.99.3.728 (2c8f8828)  (2018-09-12 13:56:21 -04:00)
XVS version: 
XS version: 7.6.1.9 (982e8c4)  (2018-09-06 17:34:08 -04:00)
[Device] Name: XQA-AppleTV-3, Identifier: c38e2c74bad7b1d5ec5a0f95289b4c0d5e90e85d
```

### Build Logs

Test Logs: http://xqa.blob.core.windows.net/gist/monotouch-test-tvos11-20-17c38e2c74bad7b1d5ec5a0f95289b4c0d5e90e85d11-20-17-9a671f4f1ef64ddf82d7dc15f83348ca.zip
Build Log: https://gist.github.com/GouriKumari/d620f1abdecfd1f45029d55f186ad14c

### Example Project (If Possible)

xamarin-macios/tests/monotouch-test/monotouc-test-tvOS

**Comment by spouliot** [comment] 2018-09-13 18:14
new test, depends on the environment
dupe of https://github.com/xamarin/maccore/issues/1030
should be fixed with https://github.com/xamarin/xamarin-macios/pull/4805

**Closed by spouliot** 2018-09-13 18:14 UTC
