### ISSUE TITLE
imessage icon archiving - missing icons

### ISSUE THREAD

**Issue by balinabbb** [xamarin/xamarin-macios#4840] opened 2018-09-19 12:37 UTC
### Steps to Reproduce

1. create a new app and a corresponding iMessage extension
2. set all iMessage app icons in the asset catalog
3. archive for publishing
4. validate archive with xcode / try to upload

All the icon files are there in the project under Assets.xassets. They are also referenced in content.json.

### Expected Behavior

All the icon png files should be in the extension appex, also listed in the Info.plist and successful validation.

### Actual Behavior

The icon files 
 - `iMessage App Icon27x20@2x.png`
 - `iMessage App Icon27x20@3x.png`
 - `iMessage App Icon32x24@2x.png`
 - `iMessage App Icon32x24@3x.png`

are not present after archiving, also the Info.plist does not contain them.
```
  - Icon files (iOS 5)
    - Primary Icon
      - Icon files
        - Item 0 : iMessage App Icon60x45
        - Item 1 : iMessage App Icon67x50
        - Item 2 : iMessage App Icon74x55
<<< should be there but missing
        - Item 3 : iMessage App Icon27x20
        - Item 4 : iMessage App Icon32x24
>>>
```
The other 6 files are ok.
Xcode validation results in an error stating that these four files above are missing.

### Further Details / Workaround / Solution suggestion
Copy the missing 4 files directly in the *.xarchive/Products/Applications/*.app/Plugins/*.appex/
and also edit the Info.plist file at the location.

I am 100% that #3955 is related.

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.6.3 (build 1)
Installation UUID: c50a0e4a-372e-4281-aafb-96cdcaa708f6
Runtime:
	Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000301

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.6.0.14 (Visual Studio Community)
Hash: 1a6e2786
Branch: 
Build date: 2018-08-28 00:12:06-0400

=== Xamarin.iOS ===

Version: 11.14.0.14 (Visual Studio Community)
Hash: 1a6e2786
Branch: HEAD
Build date: 2018-08-28 00:12:06-0400

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Community)
Android SDK: /Users/bb/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Java SDK: /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706030001
Git revision: 18a828b090fb6d2cfb0b3576cd6d7eb764f29753
Build date: 2018-08-30 15:12:59+00
Build branch: release-7.6
Xamarin extensions: f4aee57d7b72fa4be6b6d585ac90d614f20fa426

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

**Comment by rolfbjarne** [comment] 2018-09-19 17:09
Thanks for the report.

You're correct, this is in fact a duplicate of #3955.

**Closed by rolfbjarne** 2018-09-19 17:09 UTC
