### ISSUE TITLE
xamarin.ios wifi connect error:internal error

### ISSUE THREAD

**Issue by CherryBu** [xamarin/xamarin-macios#19419] opened 2023-11-10 05:18 UTC
I use Visual studio,use xamarin.ios platform, using ssidname and password to connect specific wifi, I also allow location permission,please check the following code:

```cs
public Task<int> ChangeToWifi(string ssid, string pwd)
        {
            TaskCompletionSource<int> taskCompletionSource = new TaskCompletionSource<int>();

          
                NEHotspotConfiguration hotspotConfiguration = new NEHotspotConfiguration(ssid, pwd, false);
                hotspotConfiguration.JoinOnce = true;
                NEHotspotConfigurationManager.SharedManager.ApplyConfiguration(hotspotConfiguration, (NSError error) =>
                {
                    if (error != null)
                    {
                        if (error?.LocalizedDescription == "already associated.")
                        {
                            taskCompletionSource.SetResult(1);
                            UpdateSelectedWIfiModel(ssid);
                            LogHelper.LogDebug("wifi switch: already associated,connected");
                            Console.WriteLine("========Connected333333333");
                        }
                        else
                        {
                            taskCompletionSource.SetResult(0);
                            UpdateSelectedWIfiModel(ssid);
                            LogHelper.LogDebug("wifi switch: no connected or not approve");
                            Console.WriteLine("========No Connected");
                        }
                    }
                    else
                    {
                        taskCompletionSource.SetResult(1);
                        UpdateSelectedWIfiModel(ssid);
                        LogHelper.LogDebug("wifi switch: connected");
                        Console.WriteLine("==========Connected11111111");
                    }
                });           
            }
            return taskCompletionSource.Task;
        }
```

### Expected Behavior
NEHotspotConfigurationManager working normally in iOS 14,

IOS 16 or 14.4.2,return 0, and  **internal error will appear**,

In this case, I only restart the device， It can be solved temporarily, but it will appear again after a while

### Actual Behavior
But It works well on other os version, for example 14, I use ssidname and password , can connect wifi and return 1 result
### Environment
 I use visual studio tool, and xamarin.ios platform

**Comment by rolfbjarne** [comment] 2023-11-10 09:07
Please print out the full contents of the error like this and paste it here:

```cs
Console.WriteLine (error);
```

also we'll likely need a complete test project in order to reproduce this.

**Comment by CherryBu** [comment] 2023-11-13 01:27
@rolfbjarne sorry for the late reply

I use 14.4.2 and 16 version, it always returns **Console.WriteLine ("internal error.");**， but I it works fine on other version , like 14.6 ot other.

**Comment by CherryBu** [comment] 2023-11-13 02:03
@rolfbjarne Please take a look the following sample:

` public interface IGetWifiSSIDService
    {     
        Task<int> ChangeToWifi(string ssid, string pwd);
       
    }`

Custom render:

` public class GetWifiSSIDService : IGetWifiSSIDService
    {
        public GetWifiSSIDService()
        {

        }

        public Task<int> ChangeToWifi(string ssid, string pwd)
        {
            TaskCompletionSource<int> taskCompletionSource = new TaskCompletionSource<int>();

            if (UIDevice.CurrentDevice.CheckSystemVersion(14, 0))
            {
                //NEHotspotConfigurationManager.SharedManager.GetConfiguredSsids((listWifi) =>
                //{
                //    if (listWifi != null)
                //    {
                //        foreach (string ssid_selected in listWifi)
                //        {

                //            if (ssid_selected == ssid)
                //            {
                //                NEHotspotConfigurationManager.SharedManager.RemoveConfiguration(ssid);
                //            }
                //        }
                //    }
                //});
                NEHotspotConfiguration hotspotConfiguration = new NEHotspotConfiguration(ssid, pwd, false);
                hotspotConfiguration.JoinOnce = true;
                NEHotspotConfigurationManager.SharedManager.ApplyConfiguration(hotspotConfiguration, (NSError error) =>
                {
                    if (error != null)
                    {
                        if (error?.LocalizedDescription == "already associated.")
                        {
                            taskCompletionSource.SetResult(1);
                            Console.WriteLine("======== already Connected");
                        }
                        else
                        {
                            taskCompletionSource.SetResult(0);
                            Console.WriteLine("========No Connected:" + error.ToString());

                        }
                    }
                    else
                    {
                        taskCompletionSource.SetResult(1);
                        Console.WriteLine("==========Connected");
                    }
                });
            }
            return taskCompletionSource.Task;
        }
    }`

Connect wifi by ssidname and password:
` async void btn1_Clicked(System.Object sender, System.EventArgs e)
        {
            string ssidname = "test";
            string password = "password";

            IGetWifiSSIDService service = DependencyService.Get<IGetWifiSSIDService>();
            int result = await service.ChangeToWifi(ssidname, password);

        }`

**Comment by rolfbjarne** [comment] 2023-11-13 10:54
Do you get the same problem with all wifi networks, or just one in particular?

**Comment by CherryBu** [comment] 2023-11-14 01:07
@rolfbjarne 
I tried to connect to different wifi, and the results were the same, both returning internal errors. I tried restarting the device and then connecting to wifi, and it was able to connect to wifi normally. But the problem may reoccur later. So restarting the device does not solve the underlying problem

**Comment by CherryBu** [comment] 2023-11-14 05:29
@rolfbjarne 
I can reproduce this issue.
Step 1: Settings-Internet-Turn off the network
Step 2: At this time, the code connects to a network, but the network is closed by me at this time
Step 3: NEHotspotConfigurationManager.SharedManager.ApplyConfiguration has no return value and keeps trying to connect without stopping.
Step 4: Close the app and restart it. At this time, connect to an available network, but it always fails to connect, always Internal error

**Comment by rolfbjarne** [comment] 2023-11-14 07:06
Can you zip up and attach your test project so that I can be sure to test the exact same code you're using?

**Comment by CherryBu** [comment] 2023-11-14 07:18
@rolfbjarne 
[WIFISwitch.zip](https://github.com/xamarin/xamarin-macios/files/13345656/WIFISwitch.zip)

Upload sample zip

**Comment by rolfbjarne** [comment] 2023-11-14 08:58
I can reproduce, and the problem is that you need the "Hotspot Configuration" entitlement in your project.

References:

* https://learn.microsoft.com/en-us/dotnet/maui/ios/entitlements?tabs=vs#hotspot-configuration
* https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_hotspotconfiguration?language=objc

Remember that you'll also need to create a provisioning profile that includes the entitlement as well.

Closing since this is not an issue with Xamarin.iOS.

**Closed by rolfbjarne** 2023-11-14 08:58 UTC
Labels: need-attention

**Comment by CherryBu** [comment] 2023-11-15 03:03
@rolfbjarne 
Yes, I already add "Hotspot Configuration" entitlement, Otherwise, I won’t be able to use it normally on other devices.
 
I can reproduce this issue.
Step 1: Settings-Internet-Turn off the network
Step 2: At this time, the code connects to a network, but the network is closed by me at this time
Step 3: NEHotspotConfigurationManager.SharedManager.ApplyConfiguration has no return value and keeps trying to connect without stopping.
Step 4: Close the app and restart it. At this time, connect to an available network, but it always fails to connect, always Internal error

**I test on iphone,  Ipad seem don't have this problem**

       ```
 <key>com.apple.developer.networking.HotspotConfiguration</key>
	<true/>
	<key>com.apple.developer.networking.wifi-info</key>
	<true/>
```

**Comment by rolfbjarne** [comment] 2023-11-15 10:54
Can you update your test project with your exact configuration (including entitlements) that work on some devices and doesn't on others?

**Comment by CherryBu** [comment] 2023-11-17 07:14
@rolfbjarne 
Sorry for  the late reply, and sorry for not uploading the correct and complete code.
[WIFISwitch.zip](https://github.com/xamarin/xamarin-macios/files/13388519/WIFISwitch.zip)

I use 14.4.2 and 16 version, it always returns Console.WriteLine ("internal error.");， but I it works fine on other version , like 14.6 ot other.

In this case, I only restart the device， It can be solved temporarily, but it will appear again after a while

I was able to reproduce this problem two days ago, but today I am not reproducing this problem.

**Comment by rolfbjarne** [comment] 2023-12-04 09:25
I can't reproduce any problems anymore.

The fact that this is intermittent, and that rebooting the device fixes the problem, makes me believe it's an issue in iOS.

My recommendation would be to create a test project in Xcode, and then submit an issue and/or forum question to Apple about it.
