### ISSUE TITLE
Native linking error - IOS application only in release mode

### ISSUE THREAD

**Issue by pradc** [xamarin/xamarin-macios#13195] opened 2021-10-31 06:39 UTC
### Steps to Reproduce

1. We are creating creating ios mobile app using Xamarin forms version 4.5 with Visual studio 19. 
2.  We have integrated native ios sdk's in our application. Our application builds clean in debug mode but we get folloiwng errors in release mode. 
3. Can this be the reason for our application crashing intermittently during runs. 
4. During build we get following errors, Is our application crashing because of following build errors. **Please help to resolve this.** 

Native linking failed, undefined symbol:_CMSampleBufferGetImageBuffer
please verify that all the necessary frameworks have been referenced and native libraries are properly linked in (MT5210)
Native linking failed, undefined symbol:_CMSampleBufferGetImageBuffer,
please verify that all the necessary frameworks have been referenced and native libraries are properly linked in (MT5210)
Native linking failed,undefined symbol: _CMSampleBufferGetPresentationTimeStamp,
please verify that all the necessary frameworks have been referenced and native libraries are properly linked in (MT5210)
Native linking failed, undefined symbol: _CMSampleBufferInvalidate
please verify that all the necessary frameworks have been referenced and native libraries are properly linked in (MT5210)
Native linking failed, undefined symbol: _CMTimeMake
please verify that all the necessary frameworks have been referenced and native libraries are properly linked in (MT5210)
Native linking failed, undefined symbol::CMVideoFormatDescriptionGetPresentationDimensions
please verify that all the necessary frameworks have been referenced and native libraries are properly linked in (MT5210)
Native linking failed, undefined Objective-C class : ALAssetsLibrary. The symbol 'OBJC_CLASS$_ALAssetsLibrary' could not be found in any of the libraries or frameworks linked with your application
Native linking failed, undefined symbol: _kCMTimeZero.

### Expected Behavior
No build errors during debug and release mode and no intermittent crash during run
### Actual Behavior
Build errors in release mode, no build errors in debug mode and crashing at run time intermittently during the flow of application. 
### Environment

```
```

**Comment by chamons** [comment] 2021-11-01 15:14
Thank you for your feedback!

For us to investigate this further, could you please provide your full build logs, build settings, and ideally a test case (to reproduce).

Looking at the error you posted, I see `OBJC_CLASS$_ALAssetsLibrary` which makes me wonder if your build settings are correct. Do you happen to be building for 32-bit? Is the native library you are linking against 32-bit for some reason?

A sample project would be very useful to get to the bottom of this. 

We look forward to hearing from you!

**Comment by rachelkang** [comment] 2021-12-20 18:13
We will be closing this issue as it has been over 30 days since we have not received the requested information. If you are still experiencing this issue, please provide all the requested information and then click the Reopen Issue button. Thank you!

**Closed by rachelkang** 2021-12-20 18:13 UTC
Labels: need-info
