### ISSUE TITLE
NSTextTab throwing null exception when passed null options

### ISSUE THREAD

**Issue by RicheyMB** [xamarin/xamarin-macios#11972] opened 2021-06-17 11:25 UTC
Documentation states that the options parameter for a NSTextTab constructor can be null but it has stared throwing an error.

https://docs.microsoft.com/en-us/dotnet/api/uikit.nstexttab.-ctor?view=xamarin-ios-sdk-12#UIKit_NSTextTab__ctor_UIKit_UITextAlignment_System_nfloat_Foundation_NSDictionary_

### Steps to Reproduce

NSTextTab t = new NSTextTab(UITextAlignment.Left, 0, null);

### Expected Behavior

t to become a NSTextTab object

### Actual Behavior

AgrumentNullException thrown

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.9.10 (build 4)
Installation UUID: 13cc5e72-07e9-4b9a-90bc-9d0feedd869c
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000125

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.125 (2020-02/8c552e98bd6) (64-bit)
	Package version: 612000125

=== Xamarin Designer ===

Version: 16.9.0.324
Hash: b1e216c75
Branch: remotes/origin/d16-9
Build date: 2021-04-16 00:02:50 UTC

=== Roslyn (Language Service) ===

3.9.0-6.21152.10+c10f884b30737542ddd84ca889a4aad9281ce210

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.203/Sdks
SDK Versions:
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.402
	3.1.401
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.8
	3.1.7
	2.1.23
	2.1.22
	2.1.21

=== .NET Core 3.1 SDK ===

SDK: 3.1.409

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.5 (18205)
Build 12E262

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.16.0.5 (Visual Studio Community)
Hash: ab40b131d
Branch: xcode12.5
Build date: 2021-04-22 08:56:42-0400

=== Xamarin.Android ===

Not Installed

=== Microsoft OpenJDK for Mobile ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/dev/bretjohn/readme-tweak~3
Build date: 2021-05-13 17:03:56 UTC

=== Android Device Manager ===

Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/dev/jmt/d16-9bump~1
Build date: 2021-05-13 17:04:12 UTC

=== Build Information ===

Release ID: 809100004
Git revision: 30612572b7defb0273729cb6b5ea5adc8bd9a147
Build date: 2021-05-13 13:06:24-04
Build branch: release-8.9
Xamarin extensions: 30612572b7defb0273729cb6b5ea5adc8bd9a147

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.5.0 Darwin Kernel Version 20.5.0
    Sat May  8 05:10:33 PDT 2021
    root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64


```

**Comment by rolfbjarne** [comment] 2021-06-17 12:21
Looks like we changed this here:

https://github.com/xamarin/xamarin-macios/commit/d7684319cd3c5c5d5ab7b7a40816d2b04e0221d5#diff-97d65d3ebcf51cbd79386a15db035a4a338cc9bf0fdcb2cd653d6b015ecd1770R533

to match Apple's API.

In recent years Apple has added nullability information to their API, so now we know how their API is supposed to be used, and we're updating our own bindings to match what Apple is saying (previously we had to guess, and in many cases we guessed wrong).

Is there any particular reason you need to pass `null` for this API? Does it work / behave differently in that case?

**Comment by RicheyMB** [comment] 2021-06-17 13:24
Thanks. I don't have a need to pass null, an empty NSDictionary has fixed the I was seeing but thought I would ask the question as the docs say null is allowed.

Any tips on staying ahead of changes like this, was there a breaking change notification?

**Comment by mandel-macaque** [comment] 2021-08-09 15:42
@RicheyMB nullability is not a API breaking change perse, since it will be a runtime issue. If you set enable nullability checks in your project, the compiler will throw an error when you pass a null value to a not nullable parameter: https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references#nullable-contexts

This will ensure that you catch the changes at compile time and not at runtime. Close the issue since it is not a bug :)

**Closed by mandel-macaque** 2021-08-09 15:42 UTC
Labels: need-info
