### ISSUE TITLE
High CPU load on Mac when VS (for Windows) is connected.

### ISSUE THREAD

**Issue by MrThiis** [xamarin/xamarin-macios#8453] opened 2020-04-24 14:26 UTC
### High CPU load on Mac when Visual Studio (for Windows) is connected
- This started happening after updating VS from v16.5.2 to v16.5.4.
- Process consuming CPU resources: mono-sgen64

### Steps to Reproduce
1. Open a Xamarin Android & iOS solution in Visual Studio for Windows.
2. Connect (in VS) to your build-Mac
3. Observe the CPU load on the build-Mac: It increases to a pretty high level right after connecting, and remains there until you disconnect.

### Environment
Visual Studio: 
- Microsoft Visual Studio Community 2019 Version 16.5.4 + 3011.22
- Microsoft .NET Framework Version 4.8.03752

Mac:
- OS: Catalina v10.15.4
- DevTools: Xcode v11.4.1 (16137)

### Possibly Related Issues
- https://github.com/mono/mono/issues/11939
   _-> initially about another issue, but drifted towards the described issue the past few days._
- https://developercommunity.visualstudio.com/content/problem/982546/100-cpu-load.html
   _-> concerns VS for Mac, but describes pretty much the same behaviour - also after a recent VS update_

> VS bug [#1109887](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1109887), VS bug [#1110529](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1110529), VS bug [#1111788](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1111788), VS bug [#1112446](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1112446)

**Comment by MrThiis** [comment] 2020-04-30 10:20
First of all, thank you guys for taking a look at this issue!
What I don't understand: Why has this issue been closed without further information? Was it posted in the wrong forum? If so, where should it be posted, or can it be moved?
@chamons: Why the label "external-visual-studio-for-mac"...? This is about VS for Windows **connecting** to a Mac.

**Comment by chamons** [comment] 2020-05-01 14:14
@MrThiis - Sorry for the confusion. Here's what happened:

- This github repo is only for Xamarin.iOS and Mac _SDK_ issues and work, the open source binding and tooling components. 
- [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) is the primary place for Visual Studio / Visual Studio for Mac issues.
- We have "special" tags which create "internal" bugs for other teams at microsoft, such as 
external-visual-studio-for-mac
- You can see them (but not open them) here:
![image](https://user-images.githubusercontent.com/6392201/80811498-a305c200-8b8b-11ea-9621-21a2cc325da9.png)
- When I triaged this issue, I accidentally fat-fingered the wrong IDE. Apologies. 
- I fixed it on the internal bug side, but it didn't replicate in a visible way here.
- However, due to that, there were two sets of bugs open, and when one was closed it "synced" here. 
- Internal bug 1109887 is still active, I'll reopen this now to sync up with that state.

**Comment by InnerScript** [comment] 2020-05-25 18:07
Any update on this bug, and what version it will be released in?

**Comment by 0x0041764C** [comment] 2020-05-26 06:54
I am also waiting for a fix.
FYI: It is also under investigation here:
https://developercommunity.visualstudio.com/content/problem/1015210/mono-sgen64-causes-100-cpu-when-connecting-to-buil.html

**Comment by mauroa** [comment] 2020-06-08 15:55
Closing as fixed for the latest VS 16.7 Preview, according to a Feedback Item with the same root cause: https://developercommunity.visualstudio.com/content/problem/1015210/mono-sgen64-causes-100-cpu-when-connecting-to-buil.html
Please feel free to re-open it if you still experience any issue from this version.
You can install the preview from here: https://visualstudio.microsoft.com/vs/preview/
Thanks

**Closed** 2020-06-08 16:12 UTC
Labels: external-visual-studio-for-mac
