### ISSUE TITLE
warning MSB4130: The condition XXX may have been evaluated incorrectly in an earlier version of MSBuild.

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-macios#12499] opened 2021-08-20 14:32 UTC
### Steps to Reproduce

1. Create a maui app (probs ios is fine too)
2. Build
3. Observe an error:

5>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.0.100-rc.1.512\tools\msbuild\iOS\Xamarin.Shared.targets(203,41): warning MSB4130: The condition "'$(IsMacEnabled)' == 'true' And '$(IsAppExtension)' == 'true' Or '$(_PlatformName)' == 'macOS'" may have been evaluated incorrectly in an earlier version of MSBuild. Please verify that the order of the AND and OR clauses is written as intended. To avoid this warning, add parentheses to make the evaluation order explicit.

### Expected Behavior

No warning.

### Actual Behavior

Warning.

### Environment

```
```

**Comment by spouliot** [comment] 2021-08-23 15:30
I have not yet noticed it myself but

```
msbuild/Xamarin.Shared/Xamarin.Shared.targets:		<Delete SessionId="$(BuildSessionId)" Condition="'$(IsMacEnabled)' == 'true' And '$(IsAppExtension)' == 'true' Or '$(_PlatformName)' == 'macOS'" Files="$(DeviceSpecificOutputPath)dsym.items" />
```

there might be others, complex conditions that needs the same

**Comment by spouliot** [comment] 2021-08-23 21:06
@mattleibow can you tell me which version of net6 you're using to see those warnings
the current bump we're using on `main` does not show them and I suspect there's more than one
thanks!

**Comment by mattleibow** [comment] 2021-08-24 22:25
@spouliot it was `6.0.100-rc.1.21418.8`

**Comment by mattleibow** [comment] 2021-08-24 22:41
I updated the iOS sdk to rc.1.516 and I see the warning went away. I think it was probably fixed at some point.

We are a week or two behind as we got to wait for a bunch of things to sync up.

I'll close this issue for now.

**Comment by mattleibow** [comment] 2021-08-24 22:57
Heh. Just saw it again with a dotnet clean in a new ios app. dotnet 6.0.100-rc.1.21418.8 and ios 15.0.100-rc.1.516

**Comment by ShammyLevva** [comment] 2021-12-09 09:45
I encountered this too. It's reasonably obvious that 
`<Delete SessionId="$(BuildSessionId)" Condition="'$(IsMacEnabled)' == 'true' And '$(IsAppExtension)' == 'true' Or '$(_PlatformName)' == 'macOS'" Files="$(DeviceSpecificOutputPath)dsym.items" />`

is ambiguous. It should either be 
`<Delete SessionId="$(BuildSessionId)" Condition="'$(IsMacEnabled)' == 'true' And ('$(IsAppExtension)' == 'true' Or '$(_PlatformName)' == 'macOS')" Files="$(DeviceSpecificOutputPath)dsym.items" />`

or
`<Delete SessionId="$(BuildSessionId)" Condition="('$(IsMacEnabled)' == 'true' And '$(IsAppExtension)' == 'true') Or '$(_PlatformName)' == 'macOS'" Files="$(DeviceSpecificOutputPath)dsym.items" />`

Whichever was intended the fix is to determine the intent and add the brackets to make it clear what is required and avoid the warning.

NB. This always happens for me on doing a clean process.

**Comment by stephanpalmer** [comment] 2022-01-06 14:12
I encountered this too, with the following version:
- Visual Studio for Mac 8.10.16
- Xamarin.iOS 15.2.0.17
- Xcode 13.1

**Comment by chamons** [comment] 2022-01-10 15:39
This should be fixed in https://github.com/xamarin/xamarin-macios/pull/13112#pullrequestreview-789934291 and released in a future build.

**Closed by chamons** 2022-01-10 15:39 UTC
Labels: msbuild, dotnet, dotnet-pri0
