### ISSUE TITLE
I'm having an timeout issue, specifically a WebException.

### ISSUE THREAD

**Issue by mhughey-vent** [xamarin/xamarin-macios#6043] opened 2019-05-03 17:58 UTC
### Description

So the issue is I'm running into a WebException (specifically a timeout).

I have been able to narrow it down to the HTTP Client implementation settings in iOS.

- When it is set to **Managed** I don't get the error

- When I set it to **NSUrlSession (iOS 7+)** a timeout exception is being generated after a request has been running longer than 1 minute. 

We also tested our json request, using Insomnia, and it took about 5 mins as well, but no exception is generated.

I do not have access to the middle tier, just the server logs that get updated.

I know about the HttpClient.Timeout property which we have set for large amount of time, are there any other configuration variables for setting the timeout when needing TLS 1.2?

What am I missing?

Mac OS 
- XCode 8.3.3

Visual Studio 2015 for Windows 
- Xamarin 4.6.3.4  
- Xamarin.IOS 10.12.3.3

:: Extra Info That May Be Helpful ::
It looks as though **NSUrlSession (iOS 7+)** setting forces the native HTTP Client to be used (which has a hard-coded timeout of 60 seconds)

**Comment by spouliot** [comment] 2019-05-11 01:38
This issue was also posted on xamarin-macios
Closing as duplicate of https://github.com/xamarin/xamarin-macios/issues/5992

We're still waiting for additional information. Right now we suspect this was fixed (last December) and that the version of XI (10.12) is much older (about 2 years) to have the fix.

**Closed by spouliot** 2019-05-11 01:38 UTC
