### ISSUE TITLE
CarPlay parking app crashed when launching from CarPlay simulator

### ISSUE THREAD

**Issue by KevinHu-au** [xamarin/xamarin-macios#9749] opened 2020-10-01 06:02 UTC
We have applied CarPlay entitlement and want to extend our Xamarin.iOS app (by Xamarin.Forms) for CarPlay. When open the CarPlay simulator, the app is showing on the screen of CarPlay, but crashed when launching from CarPlay.

The Info.plist configure:
```
	<key>UIApplicationSceneManifest</key>
	<dict>
		<key>UISceneConfigurations</key>
		<dict>
			<key>CPTemplateApplicationSceneSessionRoleApplication</key>
			<array>
				<dict>
					<key>UISceneClassName</key>
					<string>CPTemplateApplicationScene</string>
					<key>UISceneConfigurationName</key>
					<string>ParkingPlus-Car</string>
					<key>UISceneDelegateClassName</key>
					<string>ParkingPlus.AppSceneDelegateImp</string>
				</dict>
			</array>
		</dict>
	</dict>
```
"ParkingPlus" is the app bundle name!

The class AppSceneDelegateImp (under the root folder of the iOS project 
```
    public class AppSceneDelegateImp : UIResponder, ICPTemplateApplicationSceneDelegate
    {
        private CPInterfaceController _interfaceController;

        public async void DidConnect(CPTemplateApplicationScene templateApplicationScene, CPInterfaceController interfaceController)
        {
            _interfaceController = interfaceController;
           .....
        }

        public void DidDisconnect(CPTemplateApplicationScene templateApplicationScene, CPInterfaceController interfaceController)
        {
            _interfaceController.Dispose();
            _interfaceController = null;
        }
```

### Steps to Reproduce

1.  Launch the app
2. Open the CarPlay Simulator from I/O => External Displays => CarPlay
3. Tap the app icon on CarPlay simulator

### Expected Behavior
Run the app on CarPlay

### Actual Behavior
Got a crash with exception with message "Application does not implement CarPlay template application lifecycye methods in its scene delegate."

Aslo there is an error message in the VS for mac Application output window "[SceneConfiguration] Info.plist configuration "(no name)" for CPTemplateApplicationSceneSessionRoleApplication contained UISceneDelegateClassName key, but could not load class with name "ParkingPlus.AppSceneDelegateImp""

By reading Apple document, it seems like I can return the Scene configuration by overriding AppDelegate.GetConfiguration

```
        public override UISceneConfiguration GetConfiguration(UIApplication application, UISceneSession connectingSceneSession, UISceneConnectionOptions options)
        {
            return new UISceneConfiguration("ParkingPlus-Car", UIWindowSceneSessionRole.ExternalDisplay);
        }
```

As the UIWindowsSceneSessionRole enum does not have the value for "CarTemplateApplication", I choosed ExternalDisplay.

Then I got one more error message in Application Output window 
"[Assert] BUG IN CLIENT OF UIKIT: Attempting to define a mismatched UISceneSessionRole! This will be an assert in future UIKit releases! Assigning a UISceneConfiguration with role "UIWindowSceneSessionRoleExternalDisplay" for a UISceneSession with role "CPTemplateApplicationSceneSessionRoleApplication"."

**Can I please be advised if I did anything wrong or if this is an issue from Xamarin.iOS?

Any comments or advises is really appreciated!**

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.7.8 (build 4)
Installation UUID: 5e5c8a39-22a3-4267-b751-d32060012277
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

=== Roslyn (Language Service) ===

3.7.0-6.20427.1+18ede13943b0bfae1b44ef078b2f3923159bcd32

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.402/Sdks
SDK Versions:
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	2.2.207
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	2.2.8
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.0.1 (17220)
Build 12A7300

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.0.0.0 (Visual Studio Community)
Hash: 7ec3751a1
Branch: xcode12
Build date: 2020-09-16 11:33:15-0400

=== Xamarin Designer ===

Version: 16.7.0.495
Hash: 03d50a221
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-08-28 13:12:52 UTC

=== Xamarin.Android ===

Version: 11.0.2.0 (Visual Studio Community)
Commit: xamarin-android/d16-7/025fde9
Android SDK: /Users/kevinhu/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/kevinhu/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-09-16 05:12:24 UTC

=== Android Device Manager ===

Version: 16.7.0.24
Hash: bb090a3
Branch: remotes/origin/d16-7
Build date: 2020-09-16 05:12:46 UTC

=== Build Information ===

Release ID: 807080004
Git revision: 9ea7bef96d65cdc3f4288014a799026ccb1993bc
Build date: 2020-09-16 17:22:54-04
Build branch: release-8.7
Xamarin extensions: 9ea7bef96d65cdc3f4288014a799026ccb1993bc

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Mon Aug 31 22:12:52 PDT 2020
    root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64


```

**Comment by KevinHu-au** [comment] 2020-10-01 21:20
@chamons , Thank you for your reply. The "ParkingPlus" in the Info.plist is the bundle name. I did try a few cases: with and without namespace; with and without bundle name. 

And for the Delegate implementation class, I have tried to just inherit from the Delegate class as below 
`
public class AppSceneDelegateImp : CPTemplateApplicationSceneDelegate
{
...
}
`


Can you please advise if it is possible to develop the CarPlay apps (or extension) by Xamarin.iOS? If not, is there any possible to use iOS native + the existing Xamarin.iOS mobile code to implement the feature? 

Your help is highly appreciated. I have to give the answer to my manager ASAP as we need feedback the ETA to our client.

Thanks.

**Comment by KevinHu-au** [comment] 2020-10-02 06:55
@chamons, I override the AppDelegate.GetConfiguration and when tapping the app icon on CarPlay, the method will be called. But when I inspected the connectingSceneSession, I found there are some exceptions inside the variable members.
"CPTemplateApplicationSceneSessionRoleApplication has no associated enum value on this platform".

As I mentioned in the description, Xamarin.iOS only has UIWindowSceneSessionRole enum which doesn't have value for CPTemplateApplicationSceneSessionRoleApplication.  Probably Xamarin.iOS should have an enum like UISceneSessionRole to have the values for UIWindowScene and UIScene for CarPlay.

<img width="1020" alt="Screen Shot 2020-10-02 at 4 46 05 pm" src="https://user-images.githubusercontent.com/8989917/94895803-73a70880-04cf-11eb-967c-e258651d3d9b.png">

**Comment by chamons** [comment] 2020-10-02 21:00
@KevinHu-au - Carplay is an area where Xamarin.iOS technically has known support (we believe we have most/all of the APIs bound) but doesn't any testing/known major use. It also isn't an area that's likely to have major investment in the short term, so things will continue to be at that level for the foreseeable future.

I believe we do have the APIs you referenced, here for example: https://github.com/xamarin/xamarin-macios/blob/main/src/carplay.cs#L1139

The issue is still need-info as we don't have a sample / enough information to proceed.

**Comment by KevinHu-au** [comment] 2020-10-03 12:07
@chamons. I believe Xamarin.iOS does have almost all CarPlay APIs available. After two days try and play, the issue I got is quite straightforward. It was happening when I was trying to launch the app from CarPlay simulator, the below method in AppDelegate is called with the declared SceneSessionConfiguration (from Info.plist).
```
        public override UISceneConfiguration GetConfiguration(
            UIApplication application,
            UISceneSession connectingSceneSession,
            UISceneConnectionOptions options)
        {
        }
```

Because the SceneConfiguration in Info.plist has the role type of CPTemplateApplicationSceneSessionRoleApplication, but the Role property of UISceneSession (connectingSceneSession) is an enum type UIWindowSceneSessionRole. This enum only have two values (Application & ExternalDisplay) which was introduced since iOS 13. 

When checking the Apple iOS CarPlay document, the UISceneSession.Role has a new value member "carTemplateApplication" for CarPlay scene session. Please have a look the screenshot. [https://developer.apple.com/documentation/uikit/uiscenesession/role](url)

<img width="1007" alt="Screen Shot 2020-10-03 at 9 55 39 pm" src="https://user-images.githubusercontent.com/8989917/94991093-0032f300-05c4-11eb-837c-753ed5b3b53d.png">

Please let me know if you need any more specific information.

Is there any other way I can implement the CarPlay part feature by Xcode/swift while keeping the mobile app on Xamarin.Forms/Xamarin.iOS?

Thanks.

**Comment by KevinHu-au** [comment] 2020-10-06 22:25
@chamons . Hi Chris, Any comments or suggests for me to continue or do you need any further information for this issue? Thanks.

**Comment by chamons** [comment] 2020-10-07 18:55
So we do have carTemplateApplication bound, it's just in a slightly different location than the other two:

https://github.com/xamarin/xamarin-macios/blob/main/src/carplay.cs#L1139

which you can see is the name if you swap the docs to Objective-C:

https://developer.apple.com/documentation/uikit/uiscenesessionrole?language=objc

However, that means APIs that need to use it such as UISceneConfiguration.Create can't take it without fixing on our end.

I'll get that fixed up.

Until then, you can try this monkey patch:

```
        [DllImport ("/usr/lib/libobjc.dylib", EntryPoint = "objc_msgSend")]
        public extern static IntPtr IntPtr_objc_msgSend_IntPtr_IntPtr (IntPtr receiver, IntPtr selector, IntPtr arg1, IntPtr arg2);

        public static UISceneConfiguration Create (string? name, NSString sessionRole)
        {
            global::UIKit.UIApplication.EnsureUIThread ();
            var nsname = NSString.CreateNative (name);

            UISceneConfiguration ret;
            ret = Runtime.GetNSObject<UISceneConfiguration> (IntPtr_objc_msgSend_IntPtr_IntPtr (Class.GetHandle("UISceneConfiguration"), Selector.GetHandle ("configurationWithName:sessionRole:"), nsname, sessionRole.Handle));
            NSString.ReleaseNative (nsname);

            return ret!;
        }

        [Export("application:configurationForConnectingSceneSession:options:")]
        public UISceneConfiguration GetConfiguration(UIApplication application, UISceneSession connectingSceneSession, UISceneConnectionOptions options)
        {
            return Create ("Default Configuration", CarPlay.CPTemplateApplicationScene.SessionRoleApplication);
        }
```

You may need to bump your c# version to 8 to get that to compile due to nullability bits.

**Comment by KevinHu-au** [comment] 2020-10-07 22:30
@chamons , really appreciate your help and recommendation. I will give it a try. Hopefully it will work for me.

**Comment by KevinHu-au** [comment] 2020-10-08 06:43
@chamons, your patch works fine with some of additional changes.  Just put my final working solution here in case someone has the same issue to fix.

1. The AppDelegate to create the scene configuration for two cases (CarPlay and phone)
```

        [DllImport("/usr/lib/libobjc.dylib", EntryPoint = "objc_msgSend")]
        public extern static IntPtr IntPtr_objc_msgSend_IntPtr_IntPtr(IntPtr receiver, IntPtr selector, IntPtr arg1, IntPtr arg2);

        public static UISceneConfiguration Create(string? name, NSString sessionRole)
        {
            global::UIKit.UIApplication.EnsureUIThread();
            var nsname = NSString.CreateNative(name);

            UISceneConfiguration sceneConfig;
            sceneConfig = Runtime.GetNSObject<UISceneConfiguration>(IntPtr_objc_msgSend_IntPtr_IntPtr(Class.GetHandle("UISceneConfiguration"), Selector.GetHandle("configurationWithName:sessionRole:"), nsname, sessionRole.Handle));
            NSString.ReleaseNative(nsname);
            //Because only the CarPlay scene will be here to create a scene configuration
            //We need manually assign the CarPlay scene delegate here!
            sceneConfig.DelegateType = typeof(AppCarSceneDelegateImp);
            return sceneConfig!;
        }

        [Export("application:configurationForConnectingSceneSession:options:")]
        public UISceneConfiguration GetConfiguration(UIApplication application, UISceneSession connectingSceneSession, UISceneConnectionOptions options)
        {
            UIWindowSceneSessionRole sessionRole;
            bool isCarPlaySceneSession = false;
            try
            {
                //When the connecting scene is a CarPlay scene, an expected exception will be thrown
                //Under this moment from Xamarin.iOS.
                sessionRole = connectingSceneSession.Role;
            }
            catch (NotSupportedException ex)
            {
                if (!string.IsNullOrEmpty(ex.Message) &&
                    ex.Message.Contains("CPTemplateApplicationSceneSessionRoleApplication"))
                {
                    isCarPlaySceneSession = true;
                }
            }

            if (isCarPlaySceneSession && UIDevice.CurrentDevice.CheckSystemVersion(14,0))
            {
                return Create("Car", CarPlay.CPTemplateApplicationScene.SessionRoleApplication);
            }
            else
            {
                //If it is phone scene, we need the regular UIWindow scene
                UISceneConfiguration phoneScene = new UISceneConfiguration("Phone", UIWindowSceneSessionRole.Application);
                //And assign the scene delegate here.
                phoneScene.DelegateType = typeof(AppWindowSceneDelegateImp);
                return phoneScene;
            }
        }
```
2. Create a UIWindowScene delegate to handle the regular mobile scene window
```
    public class AppWindowSceneDelegateImp : UISceneDelegate
    {
        public override void WillConnect(UIScene scene, UISceneSession session, UISceneConnectionOptions connectionOptions)
        {
            var windowScene = scene as UIWindowScene;
            if (windowScene != null)
            {
                //Assign the Xamarin.iOS app window to this scene 
                UIApplication.SharedApplication.KeyWindow.WindowScene = windowScene;
                UIApplication.SharedApplication.KeyWindow.MakeKeyAndVisible();
            }
        }
    }
```

**Comment by parkmagic** [comment] 2020-10-13 19:45
Hi,

I have followed the above "monkey patch" and ran the app on the simulator on mac using an iOS 14 device from visual studio.
The app goes into the above methods and continues to work - I enable the carplay on xcode by going to i/o then external displays then carplay but this doesn't trigger the app to change its configuration role to carplay, the carplay emulator shows but no app or breakpoint is fired off in the code.
Do I need to test on a real carplay device?

Thanks in advance for the above - this is fantastic if it works.

**Comment by KevinHu-au** [comment] 2020-10-15 21:55
@parkmagic , you need have the entitlement from Apple and include in you provision profile.

**Comment by Suplanus** [comment] 2020-11-19 20:23
@chamons was asking for the Xamarin Carplay example. I wrote a [blog post](https://maui-blog.com/carplay/) and created the [demo app](https://github.com/Suplanus/Xamarin.Demo.Carplay).
I will try to implement the scene stuff.

PRs are very welcome 💖

**Comment by Suplanus** [comment] 2020-11-25 13:01
I done my best... but I think something is missing.
The Create is `GetConfiguration()` is never called. Someone an idea?

[Here](https://github.com/Suplanus/Xamarin.Demo.Carplay/tree/dev ) you can find my tries.

**Comment by spouliot** [comment] 2021-01-18 20:35
Closing as the original issue was fixed long ago.

@Suplanus please use https://docs.microsoft.com/en-us/answers/topics/dotnet-ios.html if you have related questions. thanks!

**Closed** 2021-01-18 21:06 UTC
Labels: iOS, need-info
