### ISSUE TITLE
.Net7-iOS app is larger than a Xamarin.iOS app.

### ISSUE THREAD

**Issue by joduss** [xamarin/xamarin-macios#17798] opened 2023-03-15 08:20 UTC
### Steps to Reproduce

1. Create 2 projects, one Xamarin.iOS, one .Net 7-iOS
2. Archive the apps for publishing

### Expected Behavior
Both apps should have similar size

### Actual Behavior
The .Net7-iOS app is about 2 time larger (10MB vs 5MB)

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.5.1 (build 23)
Installation UUID: 966a4136-5806-49ca-99b1-5bf66242c74b

Runtime
.NET 7.0.1 (64-bit)
Architecture: X64
Microsoft.macOS.Sdk 12.3.2372; git-rev-head:754abbf6a3563f6267e5717ae832b4ac25b1f2fb; git-branch:release/7.0.1xx-xcode13.3

Roslyn (Language Service)
4.5.0-3.23056.2+97881342e427ff5cdcba8f12b12ff8e6f3564431

NuGet
Version: 6.4.0.117

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/7.0.201/Sdks
SDK Versions:
	7.0.201
	7.0.200
	7.0.103
	7.0.102
	7.0.101
	7.0.100
	6.0.406
	6.0.405
	6.0.404
	6.0.403
	6.0.402
	6.0.401
	6.0.400
	6.0.302
	6.0.301
	6.0.300
	6.0.200
	5.0.408
	5.0.407
	5.0.406
	5.0.405
	3.1.426
	3.1.425
	3.1.424
	3.1.423
	3.1.422
	3.1.421
	3.1.420
	3.1.419
	3.1.418
	3.1.417
	3.1.416
	2.1.818
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.3
	7.0.2
	7.0.1
	7.0.0
	6.0.14
	6.0.13
	6.0.12
	6.0.11
	6.0.10
	6.0.9
	6.0.8
	6.0.7
	6.0.6
	6.0.5
	6.0.2
	6.0.0-preview.5.21301.5
	5.0.17
	5.0.16
	5.0.15
	5.0.14
	5.0.13
	5.0.12
	5.0.11
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.32
	3.1.31
	3.1.30
	3.1.29
	3.1.28
	3.1.27
	3.1.26
	3.1.25
	3.1.24
	3.1.23
	3.1.22
	3.1.21
	3.1.20
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	2.1.30
	2.1.23
	2.1.22

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Not Installed

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.5.0.33
Hash: f0c0c52
Branch: remotes/origin/d17-5~2
Build date: 2023-03-02 06:08:31 UTC

Android Device Manager
Version: 0.0.0.1245
Hash: 7f8a990
Branch: 7f8a990
Build date: 2023-03-02 06:08:31 UTC

Apple Developer Tools
Xcode: 14.2 21534
Build: 14C18

Xamarin.Mac
Version: 9.1.0.5 Visual Studio Community
Hash: 7738c90c9
Branch: xcode14.2
Build date: 2023-01-25 15:56:14-0500

Xamarin.iOS
Version: 16.2.0.5 Visual Studio Community
Hash: 7738c90c9
Branch: xcode14.2
Build date: 2023-01-25 15:56:15-0500

Xamarin Designer
Version: 17.5.3.47
Hash: e8b5d371c3
Branch: remotes/origin/d17-5
Build date: 2023-03-02 06:08:27 UTC

Build Information
Release ID: 1705010023
Git revision: 4ea4e8aba0157d7f608399614482546551c0ee08
Build date: 2023-03-02 06:06:42+00
Build branch: release-17.5
Build lane: release-17.5

Operating System
Mac OS X 13.2.0
Darwin 22.3.0 Darwin Kernel Version 22.3.0
    Thu Jan  5 20:53:49 PST 2023
    root:xnu-8792.81.2~2/RELEASE_X86_64 x86_64
```

</details>

### Build Logs

When/if required

### Example Project (If Possible)

[Example Projects.zip](https://github.com/xamarin/xamarin-macios/files/10977329/Example.Projects.zip)

**Comment by tipa** [comment] 2023-03-15 20:56
Duplicate of https://github.com/xamarin/xamarin-macios/issues/10249 I think

**Comment by rolfbjarne** [comment] 2023-03-16 12:24
Here's a comparison between the two apps, this looks very much like the Hello World numbers from #10249.

---

# Application Comparer

* App A: `/Users/rolf/Downloads/Example.Projects/Xamarin/JitProject/bin/iPhone/Release/JitProject.app`
* App B: `/Users/rolf/Downloads/Example.Projects/Net7/JitProject/bin/Release/net7.0-ios/ios-arm64/JitProject.app`

| Files | Size A | Size B | diff | % |
|:----|----:|----:|----:|----:|
| _CodeSignature/CodeResources | 6,457 | 6,351 | -106 | -1.6% |)
| AppIcon60x60@2x.png | 2,632 | 1,076 | -1,556 | -59.1% |)
| AppIcon76x76@2x~ipad.png | 3,125 | 1,270 | -1,855 | -59.4% |)
| archived-expanded-entitlements.xcent | 181 | 181 | 0 | 0.0% |)
| Assets.car | 75,096 | 45,464 | -29,632 | -39.5% |)
| embedded.mobileprovision | 18,604 | 18,604 | 0 | 0.0% |)
| icudt.dat | 0 | 1,824,544 | 1,824,544 | - |)
| Info.plist | 1,708 | 1,336 | -372 | -21.8% |)
| JitProject | 3,779,248 | 6,706,112 | 2,926,864 | 77.4% |)
| JitProject.aotdata.arm64 | 1,264 | 1,728 | 464 | 36.7% |)
| JitProject.exe -> JitProject.dll | 6,144 | 6,656 | 512 | 8.3% |)
| LaunchScreen.nib | 0 | 3,059 | 3,059 | - |)
| LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib | 1,835 | 0 | -1,835 | -100.0% |)
| LaunchScreen.storyboardc/222-view-223.nib | 0 | 1,848 | 1,848 | - |)
| LaunchScreen.storyboardc/Info.plist | 258 | 237 | -21 | -8.1% |)
| LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib | 896 | 0 | -896 | -100.0% |)
| LaunchScreen.storyboardc/UIViewController-222.nib | 0 | 882 | 882 | - |)
| Main.storyboardc/BYZ-38-t0r-view-8bC-Xf-vdC.nib | 1,835 | 0 | -1,835 | -100.0% |)
| Main.storyboardc/Info.plist | 258 | 0 | -258 | -100.0% |)
| Main.storyboardc/UIViewController-BYZ-38-t0r.nib | 916 | 0 | -916 | -100.0% |)
| mscorlib.aotdata.arm64 -> System.Private.CoreLib.aotdata.arm64 | 297,712 | 599,032 | 301,320 | 101.2% |)
| mscorlib.dll -> System.Private.CoreLib.dll | 407,552 | 668,672 | 261,120 | 64.1% |)
| PkgInfo | 8 | 8 | 0 | 0.0% |)
| runtimeconfig.bin | 0 | 983 | 983 | - |)
| System.aotdata.arm64 | 752 | 0 | -752 | -100.0% |)
| System.dll | 4,608 | 0 | -4,608 | -100.0% |)
| System.Runtime.aotdata.arm64 | 0 | 808 | 808 | - |)
| System.Runtime.dll | 0 | 5,120 | 5,120 | - |)
| Xamarin.iOS.aotdata.arm64 -> Microsoft.iOS.aotdata.arm64 | 46,720 | 74,096 | 27,376 | 58.6% |)
| Xamarin.iOS.dll -> Microsoft.iOS.dll | 58,368 | 167,424 | 109,056 | 186.8% |)
| | | | | |
| STATISTICS | 0 | 0 | 0 | - |)
| Native | 4,125,696 | 7,381,776 | 3,256,080 | 78.9% |)
|     Executable | 3,779,248 | 6,706,112 | 2,926,864 | 77.4% |)
|     AOT data | 346,448 | 675,664 | 329,216 | 95.0% |)
| Managed *.dll/exe | 476,672 | 847,872 | 371,200 | 77.9% |)
| | | | | |
| TOTAL | 4,716,177 | 10,135,491 | 5,419,314 | 114.9% |)

Generated by [appcompare](https://github.com/spouliot/appcompare)

**Comment by rolfbjarne** [comment] 2023-03-16 12:30
Here's a report with the interpreter completely disabled (removing the `MtouchInterpreter` property):

---

# Application Comparer

* App A: `/Users/rolf/Downloads/Example.Projects/Xamarin/JitProject/bin/iPhone/Release/JitProject.app`
* App B: `/Users/rolf/Downloads/Example.Projects/Net7/JitProject/bin/Release/net7.0-ios/ios-arm64/JitProject.app`

| Files | Size A | Size B | diff | % |
|:----|----:|----:|----:|----:|
| _CodeSignature/CodeResources | 6,457 | 6,351 | -106 | -1.6% |)
| AppIcon60x60@2x.png | 2,632 | 1,076 | -1,556 | -59.1% |)
| AppIcon76x76@2x~ipad.png | 3,125 | 1,270 | -1,855 | -59.4% |)
| archived-expanded-entitlements.xcent | 181 | 181 | 0 | 0.0% |)
| Assets.car | 75,096 | 45,464 | -29,632 | -39.5% |)
| embedded.mobileprovision | 18,604 | 18,604 | 0 | 0.0% |)
| icudt.dat | 0 | 1,824,544 | 1,824,544 | - |)
| Info.plist | 1,708 | 1,336 | -372 | -21.8% |)
| JitProject | 3,779,248 | 6,323,072 | 2,543,824 | 67.3% |)
| JitProject.aotdata.arm64 | 1,264 | 1,440 | 176 | 13.9% |)
| JitProject.exe -> JitProject.dll | 6,144 | 7,168 | 1,024 | 16.7% |)
| LaunchScreen.nib | 0 | 3,059 | 3,059 | - |)
| LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib | 1,835 | 0 | -1,835 | -100.0% |)
| LaunchScreen.storyboardc/222-view-223.nib | 0 | 1,848 | 1,848 | - |)
| LaunchScreen.storyboardc/Info.plist | 258 | 237 | -21 | -8.1% |)
| LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib | 896 | 0 | -896 | -100.0% |)
| LaunchScreen.storyboardc/UIViewController-222.nib | 0 | 882 | 882 | - |)
| Main.storyboardc/BYZ-38-t0r-view-8bC-Xf-vdC.nib | 1,835 | 0 | -1,835 | -100.0% |)
| Main.storyboardc/Info.plist | 258 | 0 | -258 | -100.0% |)
| Main.storyboardc/UIViewController-BYZ-38-t0r.nib | 916 | 0 | -916 | -100.0% |)
| mscorlib.aotdata.arm64 -> System.Private.CoreLib.aotdata.arm64 | 297,712 | 496,280 | 198,568 | 66.7% |)
| mscorlib.dll -> System.Private.CoreLib.dll | 407,552 | 373,760 | -33,792 | -8.3% |)
| PkgInfo | 8 | 8 | 0 | 0.0% |)
| runtimeconfig.bin | 0 | 983 | 983 | - |)
| System.aotdata.arm64 | 752 | 0 | -752 | -100.0% |)
| System.dll | 4,608 | 0 | -4,608 | -100.0% |)
| System.Runtime.aotdata.arm64 | 0 | 808 | 808 | - |)
| System.Runtime.dll | 0 | 5,120 | 5,120 | - |)
| Xamarin.iOS.aotdata.arm64 -> Microsoft.iOS.aotdata.arm64 | 46,720 | 38,200 | -8,520 | -18.2% |)
| Xamarin.iOS.dll -> Microsoft.iOS.dll | 58,368 | 57,344 | -1,024 | -1.8% |)
| | | | | |
| STATISTICS | 0 | 0 | 0 | - |)
| Native | 4,125,696 | 6,859,800 | 2,734,104 | 66.3% |)
|     Executable | 3,779,248 | 6,323,072 | 2,543,824 | 67.3% |)
|     AOT data | 346,448 | 536,728 | 190,280 | 54.9% |)
| Managed *.dll/exe | 476,672 | 443,392 | -33,280 | -7.0% |)
| | | | | |
| TOTAL | 4,716,177 | 9,209,035 | 4,492,858 | 95.3% |)

Generated by [appcompare](https://github.com/spouliot/appcompare)

**Comment by rolfbjarne** [comment] 2023-03-16 12:31
And with the interpreter fully enabled (`<UseInterpreter>true</UseInterpreter>`):

---

# Application Comparer

* App A: `/Users/rolf/Downloads/Example.Projects/Xamarin/JitProject/bin/iPhone/Release/JitProject.app`
* App B: `/Users/rolf/Downloads/Example.Projects/Net7/JitProject/bin/Release/net7.0-ios/ios-arm64/JitProject.app`

| Files | Size A | Size B | diff | % |
|:----|----:|----:|----:|----:|
| _CodeSignature/CodeResources | 6,457 | 5,635 | -822 | -12.7% |)
| AppIcon60x60@2x.png | 2,632 | 1,076 | -1,556 | -59.1% |)
| AppIcon76x76@2x~ipad.png | 3,125 | 1,270 | -1,855 | -59.4% |)
| archived-expanded-entitlements.xcent | 181 | 181 | 0 | 0.0% |)
| Assets.car | 75,096 | 45,464 | -29,632 | -39.5% |)
| embedded.mobileprovision | 18,604 | 18,604 | 0 | 0.0% |)
| icudt.dat | 0 | 1,824,544 | 1,824,544 | - |)
| Info.plist | 1,708 | 1,336 | -372 | -21.8% |)
| JitProject | 3,779,248 | 3,971,152 | 191,904 | 5.1% |)
| JitProject.aotdata.arm64 | 1,264 | 0 | -1,264 | -100.0% |)
| JitProject.exe -> JitProject.dll | 6,144 | 6,656 | 512 | 8.3% |)
| LaunchScreen.nib | 0 | 3,059 | 3,059 | - |)
| LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib | 1,835 | 0 | -1,835 | -100.0% |)
| LaunchScreen.storyboardc/222-view-223.nib | 0 | 1,848 | 1,848 | - |)
| LaunchScreen.storyboardc/Info.plist | 258 | 237 | -21 | -8.1% |)
| LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib | 896 | 0 | -896 | -100.0% |)
| LaunchScreen.storyboardc/UIViewController-222.nib | 0 | 882 | 882 | - |)
| Main.storyboardc/BYZ-38-t0r-view-8bC-Xf-vdC.nib | 1,835 | 0 | -1,835 | -100.0% |)
| Main.storyboardc/Info.plist | 258 | 0 | -258 | -100.0% |)
| Main.storyboardc/UIViewController-BYZ-38-t0r.nib | 916 | 0 | -916 | -100.0% |)
| mscorlib.aotdata.arm64 -> System.Private.CoreLib.aotdata.arm64 | 297,712 | 34,888 | -262,824 | -88.3% |)
| mscorlib.dll -> System.Private.CoreLib.dll | 407,552 | 668,672 | 261,120 | 64.1% |)
| PkgInfo | 8 | 8 | 0 | 0.0% |)
| runtimeconfig.bin | 0 | 983 | 983 | - |)
| System.aotdata.arm64 | 752 | 0 | -752 | -100.0% |)
| System.dll | 4,608 | 0 | -4,608 | -100.0% |)
| System.Runtime.dll | 0 | 5,120 | 5,120 | - |)
| Xamarin.iOS.aotdata.arm64 | 46,720 | 0 | -46,720 | -100.0% |)
| Xamarin.iOS.dll -> Microsoft.iOS.dll | 58,368 | 167,424 | 109,056 | 186.8% |)
| | | | | |
| STATISTICS | 0 | 0 | 0 | - |)
| Native | 4,125,696 | 4,006,040 | -119,656 | -2.9% |)
|     Executable | 3,779,248 | 3,971,152 | 191,904 | 5.1% |)
|     AOT data | 346,448 | 34,888 | -311,560 | -89.9% |)
| Managed *.dll/exe | 476,672 | 847,872 | 371,200 | 77.9% |)
| | | | | |
| TOTAL | 4,716,177 | 6,759,039 | 2,042,862 | 43.3% |)

Generated by [appcompare](https://github.com/spouliot/appcompare)

**Closed** 2023-03-16 12:36 UTC
