### ISSUE TITLE
System.Text.Json.JsonSerializer' threw an exception. ---> System.MissingMethodException

### ISSUE THREAD

**Issue by eltra-ch** [xamarin/xamarin-macios#10839] opened 2021-03-11 05:28 UTC
just updated to visual studio 16.9.1, Visual Studio for Mac 8.9 (build 1651). Latest Xamarin Forms 5.0.0.2012 etc.

by calling Serialize using System.Text.Json.Serializer of simple class (UserIdentity) below:

I get following exception:

System.TypeInitializationException: The type initializer for 'System.Text.Json.JsonSerializer' threw an exception. ---> System.MissingMethodException: Method not found: int System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<byte>)
  at System.Text.Json.JsonEncodedText.EncodeHelper (System.ReadOnlySpan`1[T] utf8Value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00000] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
  at System.Text.Json.JsonEncodedText.TranscodeAndEncode (System.ReadOnlySpan`1[T] value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00033] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
  at System.Text.Json.JsonEncodedText.Encode (System.ReadOnlySpan`1[T] value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00014] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
  at System.Text.Json.JsonEncodedText.Encode (System.String value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00014] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
  at System.Text.Json.JsonSerializer..cctor () [0x00042] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
   --- End of inner exception stack trace ---

This was working fine in previous releases!

[DataContract]
    public class UserIdentity
    {
        /// <summary>
        /// UserIdentity
        /// </summary>
        public UserIdentity()
        {
            Header = DefaultHeader;
        }

        #region Properties

        /// <summary>
        /// DefaultHeader
        /// </summary>
        public static string DefaultHeader = "ABA0";

        /// <summary>
        /// Header
        /// </summary>
        [DataMember]
        public string Header { get; set; }

        /// <summary>
        /// Login
        /// </summary>
        [DataMember]
        [Required]
        [EmailAddress]
        public string Login { get; set; }

        /// <summary>
        /// Name
        /// </summary>
        [DataMember]
        public string Name { get; set; }

        /// <summary>
        /// Password
        /// </summary>
        [DataMember]
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        /// <summary>
        /// User role
        /// </summary>
        [DataMember]
        public string Role { get; set; }

        /// <summary>
        /// Is valid
        /// </summary>
        [IgnoreDataMember]
        [JsonIgnore]
        public bool IsValid
        {
            get
            {
                return !string.IsNullOrEmpty(Login) && !string.IsNullOrEmpty(Password);
            }
        }

        #endregion
    }

**Comment by filipnavara** [comment] 2021-03-11 08:02
The underlying issue: https://github.com/mono/mono/issues/20805
Workaround is presented there.

**Comment by eltra-ch** [comment] 2021-03-11 08:32
Workaround doesn't work in my case. I applied 1:1 the references, but now I cannot use the "ReadOnlySpan" and "Span" classes. I don't know if this playes any role, but the those classes are used over .net standard 2.0 library.

**Comment by filipnavara** [comment] 2021-03-11 08:53
We also use .NET Standard 2.0 libraries. In the Xamarin main project we use the overrides for System.Buffers/System.Memory to convince NuGet that the dependency is satisfied without overwriting the actual files coming from the Mono/Xamarin framework.

**Comment by spouliot** [comment] 2021-03-11 15:50
Dupe of https://github.com/xamarin/xamarin-macios/issues/10548

**Closed by spouliot** 2021-03-11 15:50 UTC
