### ISSUE TITLE
Allow overriding resulting app bundle path

### ISSUE THREAD

**Issue by Therzok** [xamarin/xamarin-macios#7892] opened 2020-02-14 09:51 UTC
### Steps to Reproduce

1. Build a Xamarin.Mac app
2. Observe there is no way to configure just the resulting app bundle output directory

### Expected Behavior
https://github.com/xamarin/xamarin-macios/blob/3f84883ebfad4a876821eabfdef49b8dfae52104/msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets#L482-L488

`AppBundleDir` should be overrideable. Something like `<AppBundleDir Condition=" '$(AppBundleDir)' == '' ">`.

### Actual Behavior
No way to configure this behaviour except overriding `_GenerateBundleName` which may break.

### Version
6.18.0.1

**Comment by chamons** [comment] 2020-02-19 15:54
Try setting:
```
    <AssemblyName>FooBuzz</AssemblyName>
```
That works for me in a sample project @Therzok

**Comment by Therzok** [comment] 2020-02-19 17:22
What we're looking for is not to have the resulting app bundle in `<OutputPath>` but some other configurable directory, and leave whatever dlls were built in there, but just relocate the prefix of the app bundle.

**Comment by chamons** [comment] 2020-02-24 19:00
Discussions on internal slack with Iain suggest this is an internal issue, and not a bug in macios.

Closing for now. Please reopen with details if needed.

**Closed by chamons** 2020-02-24 19:00 UTC
Labels: macOS, need-info
