### ISSUE TITLE
Failed to Deploy iOS App to Actual iPhone.

### ISSUE THREAD

**Issue by dzeping96** [xamarin/xamarin-macios#17958] opened 2023-03-31 07:42 UTC
After update to XCode 14.3, when I try to Debug with my actual iPhone device, receive following error.
![image](https://user-images.githubusercontent.com/23049317/229053731-3e528556-f867-44e5-ad2b-513044e86508.png)

But the file did exist in XCode folder.
<img width="1234" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/23049317/229060573-641d8a2b-6ce3-421f-bc39-f0ed87569e77.png">
<img width="1235" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/23049317/229060596-78516348-54a2-4da9-9500-dde704545257.png">

### Steps to Reproduce
No need to do anything, simply deploy will reproduce.

### Expected Behavior
Deploy and able to deploy and debug on actual iPhone device.

### Actual Behavior
Receive error.

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.5.3 (build 15)
Installation UUID: fc4bf42a-5087-4781-b863-5580659f715a

Runtime
.NET 7.0.1 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 12.3.2372; git-rev-head:754abbf6a3563f6267e5717ae832b4ac25b1f2fb; git-branch:release/7.0.1xx-xcode13.3

Roslyn (Language Service)
4.5.0-3.23056.2+97881342e427ff5cdcba8f12b12ff8e6f3564431

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.202/Sdks
SDK Versions:
	7.0.202
	7.0.101
	6.0.407
	6.0.404
	6.0.401
	6.0.400
	6.0.301
	6.0.300
	6.0.203
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	6.0.407
	6.0.404
	6.0.401
	6.0.400
	6.0.301
	6.0.300
	6.0.106
	6.0.105
	6.0.104
	5.0.408
	5.0.407
	3.1.426
	3.1.423
	3.1.422
	3.1.420
	3.1.419
	3.1.418

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.4
	7.0.1
	6.0.15
	6.0.12
	6.0.9
	6.0.8
	6.0.6
	6.0.5

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.15
	6.0.12
	6.0.9
	6.0.8
	6.0.6
	6.0.5
	6.0.4
	5.0.17
	5.0.16
	3.1.32
	3.1.29
	3.1.28
	3.1.26
	3.1.25
	3.1.24

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.2.0.6 (Visual Studio Community)
Commit: xamarin-android/d17-5/a200af1
Android SDK: /Users/aft/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		11.0 (API level 30)
		10.0 (API level 29)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.3
SDK Build Tools Version: 33.0.0

Build Information: 
Mono: 6dd9def
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@9f02d77

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.5.0.33
Hash: f0c0c52
Branch: remotes/origin/d17-5~2
Build date: 2023-03-23 18:30:27 UTC

Android Device Manager
Version: 0.0.0.1245
Hash: 7f8a990
Branch: 7f8a990
Build date: 2023-03-23 18:30:27 UTC

Xamarin Designer
Version: 17.5.3.47
Hash: e8b5d371c3
Branch: remotes/origin/d17-5
Build date: 2023-03-23 18:30:22 UTC

Apple Developer Tools
Xcode: 14.3 21812
Build: 14E222b

Xamarin.Mac
Not Installed

Xamarin.iOS
Version: 16.2.0.6 Visual Studio Community
Hash: 8dbac9331
Branch: xcode14.2
Build date: 2023-02-08 15:12:08-0500

Build Information
Release ID: 1705030015
Git revision: c7ec3826dd11045a53fa7f2c08ddbd6bd475c05b
Build date: 2023-03-23 18:28:33+00
Build branch: release-17.5
Build lane: release-17.5

Operating System
Mac OS X 13.3.0
Darwin 22.4.0 Darwin Kernel Version 22.4.0
    Mon Mar  6 21:00:41 PST 2023
    root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64
```

```
XCode 14.3 (14E222b)
```

</details>

### Build Logs

/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch -sdkroot "/Applications/Xcode.app/Contents/Developer" --installdev "/Users/aft/Documents/ZPShareFolder/zptest/zptest/zptest.iOS/bin/iPhone/Debug/zptest.iOS.app" --device ios "--devname=Ong's iPhone (2)" --install-progress
Using Xcode 14.3 found in /Applications/Xcode.app/Contents/Developer
Xamarin.Hosting: Xamarin.Hosting
Xamarin.Hosting:     Version: 75a03ccbfc (refs/heads/xcode14)
Xamarin.Hosting:     Xcode: /Applications/Xcode.app
Xamarin.Hosting:     Xcode Version: 14.3
Xamarin.Hosting:     Verbosity: 10
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/DVTFoundation
Xamarin.Hosting: Loaded /Library/Developer/PrivateFrameworks/CoreSimulator.framework/CoreSimulator
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTDeviceFoundation.framework/DVTDeviceFoundation
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DTDeviceKitBase.framework/DTDeviceKitBase
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTKit.framework/DVTKit
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DTDeviceKit.framework/DTDeviceKit
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DTXConnectionServices.framework/DTXConnectionServices
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTSourceControl.framework/DVTSourceControl
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTServices.framework/DVTServices
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTPortal.framework/DVTPortal
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTDocumentation.framework/DVTDocumentation
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTAnalyticsClient.framework/DVTAnalyticsClient
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/XCServices.framework/XCServices
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTAppStoreConnect.framework/DVTAppStoreConnect
error HE0004: Could not load the framework 'ContentDeliveryServices' (path: /Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/ContentDeliveryServices): 
dlopen(/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/ContentDeliveryServices, 0x0001): Library not loaded: @rpath/ContentDelivery.framework/Versions/A/ContentDelivery
  Referenced from: <77B7BF95-A673-3DD7-875F-6393D0092351> /Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/Frameworks/ITunesConnectFoundation.framework/Versions/A/ITunesConnectFoundation
  Reason: tried: '/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/Frameworks/ITunesConnectFoundation.framework/Versions/A/../../../../Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Library/Frameworks/Xamarin.iOS.framework/Versions/16.2.0.6/lib/mlaunch/mlaunch.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/Frameworks/AppStoreService.framework/Versions/A/../../../../Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Library/Frameworks/Xamarin.iOS.framework/Versions/16.2.0.6/lib/mlaunch/mlaunch.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Library/Frameworks/Xamarin.iOS.framework/Versions/16.2.0.6/lib/mlaunch/mlaunch.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/../ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Library/Frameworks/Xamarin.iOS.framework/Versions/16.2.0.6/lib/mlaunch/mlaunch.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/../ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/System/Library/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file, not in dyld cache)
        
  at Xamarin.Hosting.Services.LoadFramework (System.String framework, System.Boolean warnIfMissing) [0x00089] in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/Services.cs:269 
  at Xamarin.Hosting.Services.LoadFrameworks () [0x002e6] in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/Services.cs:147 
  at Xamarin.Hosting.Services.Initialize (System.String xcode_location, System.Boolean enable_xcode_plugins) [0x000d8] in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/Services.cs:91 
  at Xamarin.Launcher.DevController.Initialize () [0x00001] in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/controller-device.cs:35 
  at Xamarin.Launcher.DevController.InstallApplicationAsync (System.String device_name, System.String device_type, System.String app_path) [0x00342] in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/controller-device.cs:112 
  at Xamarin.Utils.NSRunLoopExtensions.RunUntilTaskCompletion[T] (Foundation.NSRunLoop this, System.Threading.Tasks.Task`1[TResult] task) [0x00082] in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Utils/Extensions.cs:35 
  at Xamarin.Launcher.Driver.Main2 (System.String[] args) [0x00ba3] in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:435 
  at Xamarin.Launcher.Driver.Main (System.String[] args) [0x0006d] in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:123 

Application could not be uploaded to the device.

**Comment by happysoftware-es** [comment] 2023-03-31 20:40
Same problem. 
Reproduced by trying to deploy on iOS Version 16.4 and 16.3.1.
Environment: MacBook Air M1, XCode 14.3 and Command Line Tools XCode 14.3.

**Comment by dalexsoto** [comment] 2023-03-31 21:04
Hello, this is a known issue with Xcode 14.3, the solution is to use Xcode 14.2 for now, you can find instructions on how to get it here https://github.com/xamarin/xamarin-macios/issues/17561.

Closing as a duplicate of https://github.com/xamarin/xamarin-macios/issues/17561

**Closed by dalexsoto** 2023-03-31 21:04 UTC
