### ISSUE TITLE
Call to a method from the static library throws System.EntryPointNotFoundException, but runs fine in Xcode

### ISSUE THREAD

**Issue by lexboss93** [xamarin/xamarin-macios#12515] opened 2021-08-23 15:37 UTC
### Steps to Reproduce

1.  Clone the provided repository (see Example Project section)
2.  Run Visual Studio project from **vs_proj** folder (I've used iOS 14.5 simulator)
3.  See it crashes with System.EntryPointNotFoundException on a call to a **curl_easy_init**

```
public partial class ViewController : UIViewController
{
    [DllImport("__Internal", CharSet = CharSet.Auto, SetLastError = true, CallingConvention = CallingConvention.Cdecl)]
    static extern int ossl_store_init_once(); // from libopenssl.a

    [DllImport("__Internal", CharSet = CharSet.Auto, SetLastError = true, CallingConvention = CallingConvention.Cdecl)]
    static extern IntPtr curl_easy_init(); // from libcurl.a

    public ViewController(IntPtr handle) : base(handle)
    {
    }

    public override void ViewDidLoad()
    {
        base.ViewDidLoad();

        Console.WriteLine(ossl_store_init_once()); // prints 1 in console

        var ptr = curl_easy_init(); // throws EntryPointNotFoundException curl_easy_init assembly:<unknown assembly> type:<unknown type> member:(null)
    }
}
```

4. The same static libraries are used in the provided Xcode project (see **xcode_proj** folder). It's not crashing and functional.

### Expected Behavior
App not throwing System.EntryPointNotFoundException

### Actual Behavior
The System.EntryPointNotFoundException is thrown (even if compilation is passed without errors with Link All enabled)

### Environment

https://gist.github.com/lexboss93/f9b964dd0d58bf3915dcdad266afb7fd

### Build Logs

https://gist.github.com/lexboss93/046397e229c7fc88fa50d7d572d25009

### Example Project

https://github.com/lexboss93/xamarin_entry_point_not_found_issue_reproduce

**Comment by spouliot** [comment] 2021-08-23 19:19
I can reproduce the issue. 

The `libcurl` symbols are local (lowercase `t`) and not external (uppercase `T`). 

```
Sebastiens-MacBook-Pro:xamarin_entry_point_not_found_issue_reproduce poupou$ nm vs_proj/vs_test/bin/iPhoneSimulator/Debug/device-builds/ipod\ touch\ \(7th\ generation\)-15.0/vs_test.app/vs_test | grep curl_easy_init
00000001003d9cff t _curl_easy_init
Sebastiens-MacBook-Pro:xamarin_entry_point_not_found_issue_reproduce poupou$ nm vs_proj/vs_test/bin/iPhoneSimulator/Debug/device-builds/ipod\ touch\ \(7th\ generation\)-15.0/vs_test.app/vs_test | grep ossl_store_init_once
0000000100511c32 T _ossl_store_init_once
```

The dynamic lookup that is used (default for p/invoke and JIT) cannot look it up.

It's (of course) the same for Xcode but since it's not a lookup, but for ObjC it's just a call inside the same binary (no lookup), then it works fine.

```
Sebastiens-iMac:xamarin_entry_point_not_found_issue_reproduce poupou$ nm /Users/poupou/Library/Developer/Xcode/DerivedData/xcode_test-dmllwmfrkodxfebidpnaazqlffyn/Build/Products/Debug-iphonesimulator/xcode_test.app/xcode_test | grep curl_easy_init
0000000100133949 t _curl_easy_init
Sebastiens-iMac:xamarin_entry_point_not_found_issue_reproduce poupou$ nm /Users/poupou/Library/Developer/Xcode/DerivedData/xcode_test-dmllwmfrkodxfebidpnaazqlffyn/Build/Products/Debug-iphonesimulator/xcode_test.app/xcode_test | grep ossl_store_init_once
0000000100105ffe T _ossl_store_init_once
```

The solution would be to re-build `libcurl.a` to ensure it's symbols are externally visible.

**Comment by spouliot** [comment] 2021-08-23 19:21
What flags did you use to build the `libcurl.a` ?

**Comment by lexboss93** [comment] 2021-08-23 19:37
> What flags did you use to build the `libcurl.a` ?

Thanks for the reply, @spouliot. Yes, I've noticed the `t` and `T` differences too, but thought that if it works in Xcode, then should in Xamarin. Now I got it that there is a difference.

Libs in example project are built from the script of my colleague - [kartaris/curl-ios](https://github.com/kartaris/curl-ios)
`./build-ios.sh 7.78.0`
And I've also tested it with this one - [jasonacox/Build-OpenSSL-cURL](https://github.com/jasonacox/Build-OpenSSL-cURL)
`./build.sh -e`
They both should be _clone & compile_ ready.

**Comment by lexboss93** [comment] 2021-08-24 06:54
@spouliot but if we look to `nm`'s output on a static libraries both methods are with `T` (uppercase). The `_curl_easy_init` becomes with `t` (lowercase) only inside compiled app's binary. Does it matter?
```
iMac:xamarin_native_ref_issue_reproduce user$ nm libopenssl.a | grep ossl_store_init_once
....
threads_win.o: no symbols
0000000000000000 T _ossl_store_init_once
                 U _ossl_store_init_once


iMac:xamarin_native_ref_issue_reproduce user$ nm libcurl.a | grep curl_easy_init
...
                 U _curl_easy_init
...
0000000000000123 T _curl_easy_init
```

With `...` I hid the `some.o: no symbols` lines.

**Comment by rachelkang** [comment] 2021-12-20 18:16
We will be closing this issue as it has been over 30 days since we have heard back from you. If you are still experiencing this issue after rebuilding with a new define, as described in the previous comment, please provide all the requested information and then click the Reopen Issue button. Thank you!

**Closed by rachelkang** 2021-12-20 18:16 UTC
Labels: iOS, need-info, support
