### ISSUE TITLE
Bug, Xamarin WatchOS does not work, is Xamarin Watch Still supported ?

### ISSUE THREAD

**Issue by JeroenBer** [xamarin/xamarin-macios#16588] opened 2022-11-04 12:08 UTC
### Steps to Reproduce

1. Running the latest stable version of VS2022 on Mac (not M1 but X86)
2. Executing exactly the steps to build a Xamarin watch application as described here: https://learn.microsoft.com/en-us/xamarin/ios/watchos/get-started/installation?tabs=windows 
3. The hosting iOS app works fine in the simulator
4. I set the Startup Project to the watch app
5. Run
6. I immediately get the error "Execution failed." The simulator does not start

On an old VS2019 Mac machine the simulator does start however there I get a message in the app simulator:
This app needs to be updated by the developer to work on this version of watchOS

I read about a lot of problem with Xamarin WatchOS, is this still supported ? I tried on different machines the simple Hello World app and it fail everywhere with different problems.

Also on Nuget package restore I get these errors:
Project XXX is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0). Project XXX supports: xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0).

### Expected Behavior
The Watch simulator should start and then start the Watch App

### Actual Behavior
It does not start

### Environment

- Visual Studio Professional 2022 for Mac Version 17.3.8 (build 5)
- Architecture: X64
- Xamarin.iOS Version: 16.0.0.72  release/6.0.4xx-xcode14
- Xcode 14.0.1 (21336)

**Comment by rolfbjarne** [comment] 2023-01-18 07:38
This is likely a duplicate of #16142, so I'm closing this, since that bug has been fixed, so latest version of Xamarin.iOS should work fine.

If you disagree and believe this to be a different issue, please attach a [binary build log](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) and we'll reopen and have a look.

**Closed by rolfbjarne** 2023-01-18 07:38 UTC
