### ISSUE TITLE
can't archive app or build it on real device

### ISSUE THREAD

**Issue by michalec** [xamarin/xamarin-macios#4199] opened 2018-06-08 10:15 UTC
### Steps to Reproduce

1. can't build debug app on real iPhone (tried on iPhone 5c and 8)
2. can't create archive (release:generic device)

### Expected Behavior
debug on iphone or create ipa file

### Actual Behavior
crashes: Error MT0000: Unexpected error - Please file a bug report at http://bugzilla.xamarin.com (MT0000)

### Environment

Visual Studio Community 2017 for Mac
Version 7.5.2 (build 40)
Installation UUID: febd2638-a346-4d16-9bf0-cbdd7d2fc574
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.3
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.3
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.4 (14160)
Build 9F1027a

Xamarin.Mac
Version: 4.4.1.193 (Visual Studio Community)

Xamarin.Android
Version: 8.3.3.2 (Visual Studio Community)
Android SDK: /Users/minom/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.3 (API level 18)
		4.4 (API level 19)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.1

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin.iOS
Version: 11.12.0.4 (Visual Studio Community)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Build Information
Release ID: 705020040
Git revision: cfe2fc0566bc4db990242959de40505a13f58352
Build date: 2018-05-30 11:24:18-04
Xamarin addins: 3ac7413ef51a88e06367313c27aec8f7292752a6
Build lane: monodevelop-lion-d15-7

Operating System
Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Fri Apr 13 19:32:32 PDT 2018
    root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

Enabled user installed addins
Internet of Things (IoT) development (Preview) 7.5

```
```

### Build Logs

[full_build_log.txt](https://github.com/xamarin/xamarin-macios/files/2083946/full_build_log.txt)

**Comment by dalexsoto** [comment] 2018-06-08 16:52
There are some interesting bits in your build log

```
Unable to compile method '(wrapper native-to-managed) void SkiaSharp.SKManagedPixelSerializer:EncodeInternal (intptr,intptr)' due to: 'Invalid IL code in (wrapper native-to-managed) SkiaSharp.SKManagedPixelSerializer:EncodeInternal (intptr,intptr): IL_0054: ret       
    
     assembly:<unknown assembly> type:<unknown type> member:(null) signature:<none>'.
    Mono Ahead of Time compiler - compiling assembly /Users/minom/develop/xamarin-forms/UAE777v2/iOS/obj/iPhone/Debug/device-builds/iphone5.4-10.3.3/mtouch-cache/Build/SkiaSharp.dll
    AOTID 8A68759C-DD2E-71E6-4401-6B843770FFCF
    Code: 305548(70%) Info: 3947(0%) Ex Info: 92186(21%) Unwind Info: 13673(3%) Class Info: 3595(0%) PLT: 682(0%) GOT Info: 10174(2%) Offsets: 4056(0%) GOT: 6728
    Compiled: 635/636 (99%), No GOT slots: 0 (0%), Direct calls: 193 (36%)
    Output file: '/Users/minom/develop/xamarin-forms/UAE777v2/iOS/obj/iPhone/Debug/device-builds/iphone5.4-10.3.3/mtouch-cache/armv7/SkiaSharp.dll.s'.
    Linking symbol: '_mono_aot_module_SkiaSharp_info'.
    JIT time: 121 ms, Generation time: 121 ms, Assembly+Link time: 0 ms.
```

Looks like there is something wrong with the SkiaSharp library.

**Comment by dalexsoto** [comment] 2018-06-08 16:55
@michalec I think the issue is within the SkiaSharp library, would you be able to provide us with a test case for this?

**Comment by mandel-macaque** [comment] 2018-07-10 17:35
@michalec We have not received the needed info, I'll close the issue, please feel free to reopen it if you want us to continue looking into it.

**Closed by mandel-macaque** 2018-07-10 17:35 UTC
Labels: iOS, need-info
