### ISSUE TITLE
[XI]Mini test "GShared" failed with master build

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#5257] opened 2018-12-11 18:31 UTC
### Steps to Reproduce

1. Install Xamarin.iOS master, 12.5.1.316
2. Execute mini test on iOS or tvOS device

### Expected Behavior
All tests should pass

### Actual Behavior
[FAIL] JitTests.GShared :   Expected: 0

### Environment
Mono version: 5.18.0.219 (f919fb58c4e)  (2018-12-04 12:36:55 -05:00)
XA version: 9.1.199.37 (HEAD/1158d33f) 
XI version: 12.5.1.316 (master): 4cdb87e5) 
XM version: 5.5.1.316 (master: 4cdb87e5)  (2018-12-10 14:22:31 -05:00)
XVS version: 
XS version: 7.8.0.1370 (2c9a1dd)  (2018-12-10 12:42:19 -05:00)
[Device] Name: XQAiPadPro3, Identifier: 17b66b8a60251f7c83b15482e5cf0da7469d98b3

### Build Logs

Build Log + Installation Log:
https://gist.github.com/GouriKumari/8f7296e1e4fc071f59a524acaf1f4c24

Test Log: https://gist.github.com/GouriKumari/75201b02752469b5ba7fedaa810a6ab9

### Example Project (If Possible)

xamarin-macios/tests/mini/

**Comment by VincentDondain** [comment] 2018-12-11 19:59
Mmh I cannot reproduce the issue locally. I tried installing XI 12.5.1.316 (master): 4cdb87e like you did. I ran the mini tests for debug|iphone on a XS locally and they all passed.

Is this issue random? Can you reproduce locally or only on the bots?

**Comment by GouriKumari** [comment] 2018-12-12 15:46
I could reproduce it locally with latest master build, e509cc98c

Test Log: https://gist.github.com/GouriKumari/4e2dc79c393bd84c0942737c0a2b3a8e 
Build Log: https://gist.github.com/GouriKumari/ecc15b6cc2b33ad18c3d9826694f0a89

Test Env: https://gist.github.com/GouriKumari/d09ccf83397665d6041afe2bab77d11f

**Comment by spouliot** [comment] 2019-01-09 21:18
I can duplicate this with master (device build).

@VincentDondain is that failing on device tests ?

c.c. @vargaz

**Comment by VincentDondain** [comment] 2019-01-11 20:50
@spouliot yes latest device tests for master are also showing that issue -> https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2317870

There are a bunch of `[FAIL] JitTests.GShared : Expected: 0`.

**Comment by rolfbjarne** [comment] 2019-02-12 06:14
This is a duplicate of https://github.com/mono/mono/issues/12831.

**Closed by rolfbjarne** 2019-02-12 06:14 UTC
Labels: bug, iOS
