### ISSUE TITLE
MacOS FinderExtension plugin not getting copied to .app after build after upgrade to VS 8.8.4 (Xamarin Mac 7.0.0.15)

### ISSUE THREAD

**Issue by deepgoyal25** [xamarin/xamarin-macios#10332] opened 2020-12-29 22:21 UTC
### Steps to Reproduce

1. Create a MacOS cocoa app solution with a project
2. Create a new project which is an extension for Finder Sync (say MacFinderExtension)
3. Build the solution

### Expected Behavior
The .app generated after the build should have Contents/PlugIns/MacFinderExtension.appex

### Actual Behavior
The .app generated after the build do not have Contents/PlugIns/MacFinderExtension.appex

### Environment
```
1.
=== Visual Studio Professional 2019 for Mac ===

Version 8.8.4 (build 30)
Installation UUID: cb37e9ad-3ca9-4735-ba43-aad221c731d7
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.101/Sdks
SDK Versions:
	5.0.101
	5.0.100
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	2.2.110
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.1
	5.0.0
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	2.2.8
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19

=== .NET Core 3.1 SDK ===

SDK: 3.1.404

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.3 (17715)
Build 12C33

=== Xamarin.Mac ===

Version: 7.0.0.15 (Visual Studio Professional)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:40-0500

=== Xamarin.iOS ===

Xamarin.iOS not installed.
Can't find mtouch or the Version file at /Library/Frameworks/Xamarin.iOS.framework/Versions/Current.

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Xamarin.Android ===

Not Installed

=== Microsoft OpenJDK for Mobile ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:24 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:44 UTC

=== Build Information ===

Release ID: 808040030
Git revision: eaa21a8983aa5c4bcf6a665892478b4f3d413418
Build date: 2020-12-10 11:06:12-05
Build branch: release-8.8
Xamarin extensions: eaa21a8983aa5c4bcf6a665892478b4f3d413418

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.2.0 Darwin Kernel Version 20.2.0
    Wed Dec  2 20:39:59 PST 2020
    root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

SortAndRemoveOnSave 1.3
```

### Example Project (If Possible)
https://docs.microsoft.com/en-us/samples/xamarin/mac-samples/extensionsamples/

**Comment by deepgoyal25** [comment] 2020-12-29 22:32
Before upgrading, the Finder extension plugin was getting copied correctly when I had ```Xamarin.Mac - 7.0.0.15``` and ```Mono - 6.12.0.113```. In the build, I found that the build for app extension was getting triggered by the Main project which has a reference added to app extension
```
Project "<workspace>/MacClient/MacClient.csproj" (8) is building "<workspace>/MacFinderExtension/MacFinderExtension.csproj" (9) on node 1 (default targets).
```
And when the build for getting completed for MacClient (main project), I was able to see the target ```_CopyAppExtensionsToBundle``` was getting executed which was copying the .appex to .app
```
_CopyAppExtensionsToBundle:
Creating directory "bin/x64/Release/MyApp.app/Contents/PlugIns".
/usr/bin/ditto -rsrc "/Users/workdrivemac/work_place/Drive_Client/AWSWorkDriveClient/fuse-clients/managed-mono/MacFinderExtension/bin/Release/MyApp Finder Extension.appex" "bin/x64/Release/MyApp.app/Contents/PlugIns/MyApp Finder Extension.appex"

```

However, after the upgrade, I am noticing that the build for app extension is getting triggered by the solution instead of the main project which has reference to it
```
Project "<workspace>/MySolution.sln" (1) is building "<workspace>/MacFinderExtension/MacFinderExtension.csproj" (9) on node 1 (default targets).
```
Additionally, the build order is not consistent now as well and MacClient and MacFinderExtension are getting built in undetermined order

**Comment by spouliot** [comment] 2021-01-11 16:12
> Version: 7.0.0.15 (Visual Studio Community)

Closing as dupe of #10324 since that XM version is known not to include the `PlugIns` directory inside the `.app`

**Closed by spouliot** 2021-01-11 16:12 UTC
Labels: external-xsdk
