### ISSUE TITLE
Build fails for iOS/tvOS/watchOS Submission samples/templates project when profile and certificates are not set to "Automatic" in iOS project properties 

### ISSUE THREAD

**Issue by parasAmbhore** [xamarin/xamarin-macios#3595] opened 2018-02-26 09:53 UTC
### Steps to Reproduce

1. Create new iOS Single view app
2. Set configuration as Release and target as Device
3. Update build versions in info.plist also, set Bundle identifier as “ com.xamarin360.iTravel”
4. Update signing profiles to Distribution Peter Beaman and profile as “iTravel appstore”  in iOS project properties
5. Set app icons in Assest catalog  
6. Build the solution 
7. Right click on project and click on Archive on publishing 
8. After it succeeds, click on sign and distribute , click on App Store
9. Select proper provisioning profiles and create Archive 

### Expected Behaviour

Archive should be created successfully and .ipa should be uploaded successfully via App loaded 

### Actual Behaviour

 Getting build error : "
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(3,3): Error: No iOS signing identities match the specified provisioning profile 'iTravelAppStore'. (iOSSubmitAppSingle) " 

### Environment

https://gist.github.com/GLjackyvaswani/ee0b98d359ba37682120a5b4e5cbc092

## We have tested this with D15-6 P6 build with XCODE 9.3 beta and there issue is not reproducible 

https://gist.github.com/GLjackyvaswani/400c9cdda81f930526e47d49ee4b528a  : D15-6 Preview 6 info
https://screencast.com/t/RP33IG5H7kH5  : Provisioning working as expected 

Test suite : https://xqa-testrail.eastus.cloudapp.azure.com/index.php?/plans/view/54354
[Archive.zip](https://github.com/xamarin/xamarin-macios/files/1757955/Archive.zip)
[iOSSubmitAppSingle.zip](https://github.com/xamarin/xamarin-macios/files/1757956/iOSSubmitAppSingle.zip)

Issue is reproducible for TvOS ODRS and watchkit submission sample too 

Link : https://github.com/olegoid/SubmissionSamples/tree/master/ODRsTVOS
https://github.com/olegoid/SubmissionSamples/tree/master/WatchOS

**Comment by mandel-macaque** [comment] 2018-03-05 16:54
Hi,

I have tested the sample using my own signing certificate set to Manual and I have had no problems in building it with the following [env](https://gist.github.com/mandel-macaque/3de6bb5e7e021ff19e761c591628e585). Can you please provide logs of the machines where the build fails? It might be an issue with the configuration of those machines. 

![screen shot 2018-03-05 at 17 52 18](https://user-images.githubusercontent.com/2190086/36988021-05db3e24-209e-11e8-8b71-3d4b793b0ddf.png)

**Comment by GouriKumari** [comment] 2018-03-05 19:31
This issue is reproducible only with d15-5 VSFMac build. With d15-6 VSFMac,  (also mentioned in bug description), I could  select specific provisioning profile and submit the  .ipa.  Since it is an IDE issue and is no longer reproducible with d15-6, I think we can close the issue and can re-open this message if the issue  reproduces again.

**Comment by dalexsoto** [comment] 2018-04-09 01:50
Closing as @GouriKumari suggested here https://github.com/xamarin/xamarin-macios/issues/3595#issuecomment-370535618, If you are still experiencing this issue please re-open the bug report. Thanks!

**Closed by dalexsoto** 2018-04-09 01:50 UTC
Labels: need-info
