### ISSUE TITLE
xcode 12 watchos is not getting any events 

### ISSUE THREAD

**Issue by jigneshbodarya** [xamarin/xamarin-macios#9767] opened 2020-10-02 06:03 UTC
### Steps to Reproduce

1. Install Xcode 12.1
2. Start watch test app
3. Add any button and bind it with action
4. Run and tap on it

### Expected Behavior
Not receiveing event in action
### Actual Behavior
Must receive action
### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.7.8 (build 4)
Installation UUID: d3772a20-92dc-416a-a4d1-de349ba646e7
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

=== Roslyn (Language Service) ===

3.7.0-6.20427.1+18ede13943b0bfae1b44ef078b2f3923159bcd32

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.402/Sdks
SDK Versions:
	3.1.402
	3.1.301
	3.1.101
	3.0.101
	3.0.100
	2.2.401
	2.1.701
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.8
	3.1.5
	3.1.1
	3.0.1
	3.0.0
	2.2.6
	2.1.22
	2.1.19
	2.1.15
	2.1.14
	2.1.13
	2.1.12

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.0.2.0 (Visual Studio Community)
Commit: xamarin-android/d16-7/025fde9
Android SDK: /Users/jignesh/Documents/SDK
	Supported Android versions:
		6.0 (API level 23)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.6
SDK Build Tools Version: 29.0.3

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/jignesh/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-09-16 05:12:24 UTC

=== Android Device Manager ===

Version: 16.7.0.24
Hash: bb090a3
Branch: remotes/origin/d16-7
Build date: 2020-09-16 05:12:46 UTC

=== Xamarin Designer ===

Version: 16.7.0.495
Hash: 03d50a221
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-08-28 13:12:52 UTC

=== Apple Developer Tools ===

Xcode 12.0.1 (17220)
Build 12A7300

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.0.0.0 (Visual Studio Community)
Hash: 7ec3751a1
Branch: xcode12
Build date: 2020-09-16 11:33:15-0400

=== Build Information ===

Release ID: 807080004
Git revision: 9ea7bef96d65cdc3f4288014a799026ccb1993bc
Build date: 2020-09-16 17:22:54-04
Build branch: release-8.7
Xamarin extensions: 9ea7bef96d65cdc3f4288014a799026ccb1993bc

=== Operating System ===

Mac OS X 10.15.5
Darwin 19.5.0 Darwin Kernel Version 19.5.0
    Tue May 26 20:41:44 PDT 2020
    root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64


```

### Build Logs

https://gist.github.com/jigneshbodarya/93d6d501b6bbdfbd587c71448c8446fd
### Example Project (If Possible)

[Test.zip](https://github.com/xamarin/xamarin-macios/files/5316211/Test.zip)

**Comment by chamons** [comment] 2020-10-02 16:40
I believe this is a duplicate of:

https://github.com/xamarin/xamarin-macios/issues/8810
and
https://github.com/xamarin/xamarin-macios/issues/9634

You didn't list the watch version - please let me know what version of watch you are using.

**Comment by jigneshbodarya** [comment] 2020-10-03 09:49
Apple watch Series 6 - 40mm

**Comment by chamons** [comment] 2020-10-07 16:25
Debugging on device is currently broke, I would suggest using the simulator for this use case for now.

**Comment by rolfbjarne** [comment] 2022-10-06 11:20
Closing as duplicate of #8810.

**Closed by rolfbjarne** 2022-10-06 11:20 UTC
Labels: iOS
