### ISSUE TITLE
[xcode10] `Master-Detail Forms` app looks differently on a device and a simulator

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#4578] opened 2018-08-06 13:22 UTC
### Steps to Reproduce

1. Open VSfM
2. Create a `Master-Detail Forms App` app
3. Build it
4. Run it on Simulator 12.0 (it looks properly on a device)

### Expected Behavior
It looks like this (device):
<img src="https://user-images.githubusercontent.com/32954580/43718764-44b859e6-9994-11e8-8451-1c3569f41195.png" width="200" />

### Actual Behavior
It looks like this (simulator):
<img src="https://user-images.githubusercontent.com/32954580/43718406-3ccbb9e0-9993-11e8-9823-45ecf4fcba4a.png" width="200" />

### Environment

1. VSfM
https://gist.github.com/mykyta-bondarenko-gl/676d301238157d52224d8d293070e665

### Example Project
[MasterDetailTest.zip](https://github.com/xamarin/xamarin-macios/files/2262647/MasterDetailTest.zip)

**Comment by VincentDondain** [comment] 2018-08-07 03:15
This should be a duplicate of https://github.com/xamarin/xamarin-macios/issues/4532. On iPhone X it shows those 2 black bars and the Forms Master Detail app presents the same _wrong_ behavior as the other apps I tested.

**Closed by VincentDondain** 2018-08-07 03:15 UTC
