### ISSUE TITLE
Make Apple SDKs trimming safe

### ISSUE THREAD

**Issue by marek-safar** [xamarin/xamarin-macios#10709] opened 2021-02-23 20:47 UTC
As part of the .NET6 effort we are making the .NET Runtime [trimming safe](https://github.com/dotnet/designs/blob/main/accepted/2020/linking-libraries.md#trimming-compatibility) allow developers to annotate their libraries to be also trimming safe. As Apple SDK is one of the primary workloads which will always use linker and cares about the size it's important to resolve any linker warnings which the developers would experience when enabling linker analyzers.

The work to enable the linker analyzer is not yet simple and the effort to change that is tracked at https://github.com/dotnet/sdk/issues/15962

**Comment by rolfbjarne** [comment] 2021-02-24 06:54
This is a duplicate of #10405.

**Closed by rolfbjarne** 2021-02-24 06:54 UTC
