### ISSUE TITLE
[XCode 11 | X.iOS 12.99.3.5] Xamarin crash when attempting to run on Simulator

### ISSUE THREAD

**Issue by projectgoav** [xamarin/xamarin-macios#6838] opened 2019-08-23 07:11 UTC
### Steps to Reproduce

1. Start a new Xamarin.iOS project
1. Select a simulator target
2. Start debugging

### Expected Behavior
SImulator will get focus and app will start debugging. 

### Actual Behavior

Xamarin tool crash. 

~~My code-sign certificate expired the other day but I don't think this affects simulator builds.~~
Regenerated signed key and new provision profiles and issue still occurs. 

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.2.4 (build 45)
Installation UUID: 606023c4-9ab9-444e-b3e0-86e229e9ae04
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000327

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.327 (2019-02/f8ea05bddcb) (64-bit)
	Package version: 600000327

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.1.1
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.701/Sdks
SDK Versions:
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.0 (14921.5)
Build 11M392q

=== Xamarin.Mac ===

Version: 5.99.3.5 (Visual Studio Community)
Hash: dd394471
Branch: xcode11
Build date: 2019-08-21 07:29:09-0400

=== Xamarin.iOS ===

Version: 12.99.3.5 (Visual Studio Community)
Hash: dd394471
Branch: xcode11
Build date: 2019-08-21 07:29:08-0400

=== Xamarin Designer ===

Version: 16.2.0.414
Hash: a1c119d5f
Branch: remotes/origin/d16-2-xcode11
Build date: 2019-08-20 22:38:28 UTC

=== Xamarin.Android ===

Version: 9.4.1.0 (Visual Studio Community)
Commit: xamarin-android/d16-2/ebd65c9
Android SDK: /Users/ewan/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/ewan/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.60
Hash: 686c817
Branch: remotes/origin/d16-2
Build date: 2019-08-20 15:19:18 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 802040045
Git revision: 7da3e8d5e4b3bf8f0d4cf83f92d60c82094502b2
Build date: 2019-08-21 17:33:58+00
Build branch: release-8.2-xcode11
Xamarin extensions: 12c306582cf9fe4ef451e9b27422c416d11c6491

=== Operating System ===

Mac OS X 10.15.0
Darwin 19.0.0 Darwin Kernel Version 19.0.0
    Fri Aug  9 21:59:46 PDT 2019
    root:xnu-6153.0.139.161.2~2/RELEASE_X86_64 x86_64
```

### Example Project (If Possible)

Apple Crash report output
[XamarinCrashOnSimulatorStart.txt](https://github.com/xamarin/xamarin-macios/files/3533211/XamarinCrashOnSimulatorStart.txt)

**Comment by projectgoav** [comment] 2019-08-23 08:11
As with my previous experience with my issue #6740, I'll do a complete re-install of Visual Studio and XCode to check my machine is not foobarred.

This was previously working before the most recent XCode 11 Preview channel update I installed this morning.

**Comment by projectgoav** [comment] 2019-08-23 08:18
Re-installed `Xamarin.iOS.12.99.2.40` and the issue has been fixed

**Comment by rolfbjarne** [comment] 2019-08-23 12:42
This is a duplicate of #6841.

**Closed by rolfbjarne** 2019-08-23 12:42 UTC
