### ISSUE TITLE
ListView OnItemSelected Tap Gesture iOS not working in 16.5.2

### ISSUE THREAD

**Issue by adha-admin** [xamarin/xamarin-macios#8266] opened 2020-04-01 21:35 UTC
Installed latest version of VS2019 on PC - 16.5.2
Installed latest version of XCode on Mac - 11.4

This was to address the Broker issue
https://github.com/xamarin/xamarin-macios/issues/7882

Have a listview which when you tap, you get the details.
This used to work fine until this release.
I use all the bulk standard code that comes with a template tabview

Running in the Android Simulator works fine. 
Running in the iOS Simulator does NOT work
Running on an iPhone does NOT work.

**Comment by chamons** [comment] 2020-04-01 21:37
I believe this is a duplicate of:

xamarin/Xamarin.Forms#10162
#8255 

Thanks for the report. A fix is in work. See https://github.com/xamarin/Xamarin.Forms/issues/10162#issuecomment-607500960 for details.

**Closed by chamons** 2020-04-01 21:37 UTC
