### ISSUE TITLE
Failed to compile the generated registrar code.

### ISSUE THREAD

**Issue by uwantfries** [xamarin/xamarin-macios#4342] opened 2018-06-26 14:35 UTC
### Steps to Reproduce

1. Select iOS project & then try to build it (this has been working OK in the past - not tried it for 3 months or so)

### Expected Behavior
App compiles and runs

### Actual Behavior
Build crashes with 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to compile the generated registrar code. Please file a bug report at http://bugzilla.xamarin.com	XApp.iOS	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	791	

### Environment

VS2017 on PC
Microsoft Visual Studio Enterprise 2017 
Version 15.7.3
VisualStudio.15.Release/15.7.3+27703.2026
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Enterprise

Application Insights Tools for Visual Studio Package   8.12.10405.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40522.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40424.0
Azure App Service Tools v3.0.0

C# Tools   2.8.3-beta6-62923-07. Commit Hash: 7aafab561e449da50712e16c9e81742b8e7a2969
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CleanCommand Extension   1.0
CleanCommand Visual Studio Extension Detailed Info

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.19-rc (a4ffc1b)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10420.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2017 ENU   15.0.27612.00
Microsoft Office Developer Tools for Visual Studio 2017 ENU

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.8.3-beta6-62923-07. Commit Hash: 7aafab561e449da50712e16c9e81742b8e7a2969
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 2527e6829ecdc8281ee60d83be8cfd0fa720a648.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.27703.2026
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   4.10.10.1 (f1760154c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.1 (f3257e429)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.3.2 (HEAD/dffc59120)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.12.0.4 (64fece5)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

=====================
=== Visual Studio Community 2017 for Mac ===

Version 7.5.3 (build 7)
Installation UUID: b089baa8-67cf-45df-b42c-45cca25c0e92
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Version: 2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.4.1.193 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.12.0.4 (Visual Studio Community)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

=== Xamarin.Android ===

Version: 8.3.3.2 (Visual Studio Community)
Android SDK: /Users/admin/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705030007
Git revision: 13cecd02aceddf29a1ed57b86f81c02994df1483
Build date: 2018-06-14 15:48:08-04
Xamarin addins: 7065de97cf22c9038fdc39dd627f2c30790fd8af
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.5
Darwin 17.6.0 Darwin Kernel Version 17.6.0
    Tue May  8 15:22:16 PDT 2018
    root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

### Build Logs
[buildOutput.zip](https://github.com/xamarin/xamarin-macios/files/2137572/buildOutput.zip)

**Comment by therealjohn** [comment] 2018-06-26 14:51
There are a bunch of errors with the registrar and PDFTron in the logs. 
```
2>  In file included from /Users/admin/Library/Caches/Xamarin/mtbs/builds/XApp.iOS/9adb7912fb774f13b3df2e668e700aff/obj/iPhone/Debug/mtouch-cache/registrar.m:3: (TaskId:608)
2>  /Users/admin/Library/Caches/Xamarin/mtbs/builds/XApp.iOS/9adb7912fb774f13b3df2e668e700aff/obj/iPhone/Debug/mtouch-cache/registrar.h:1177:70: error: unknown type name 'pdftronprivate' (TaskId:608)
2>  @interface pdftron_PDF_Controls_AnnotationToolbarDelegate : NSObject<pdftronprivate.AnnotationToolbarDelegate> { (TaskId:608)
2>                                                                       ^  (TaskId:608)
2>  /Users/admin/Library/Caches/Xamarin/mtbs/builds/XApp.iOS/9adb7912fb774f13b3df2e668e700aff/obj/iPhone/Debug/mtouch-cache/registrar.h:1177:84: error: expected '>' (TaskId:608)
2>  @interface pdftron_PDF_Controls_AnnotationToolbarDelegate : NSObject<pdftronprivate.AnnotationToolbarDelegate> { (TaskId:608)
2>                                                                                     ^  (TaskId:608)
2>  /Users/admin/Library/Caches/Xamarin/mtbs/builds/XApp.iOS/9adb7912fb774f13b3df2e668e700aff/obj/iPhone/Debug/mtouch-cache/registrar.h:1177:84: error: cannot use dot operator on a type (TaskId:608)
2>  /Users/admin/Library/Caches/Xamarin/mtbs/builds/XApp.iOS/9adb7912fb774f13b3df2e668e700aff/obj/iPhone/Debug/mtouch-cache/registrar.h:1192:61: error: unknown type name 'pdftronprivate' (TaskId:608)
2>  @interface pdftron_PDF_Tools_ToolManagerDelegate : NSObject<pdftronprivate.ToolManagerDelegate> { (TaskId:608)
2>                                                              ^  (TaskId:608)
```
@rolfbjarne Can you take a look at this?

**Comment by rolfbjarne** [comment] 2018-06-26 15:51
This is a duplicate of #4094. See the last comment there for the solution (https://github.com/xamarin/xamarin-macios/issues/4094#issuecomment-390636740)

**Closed by rolfbjarne** 2018-06-26 15:51 UTC
Labels: iOS
