### ISSUE TITLE
[XCode 10 Preview] New Tabbed App crashes on start

### ISSUE THREAD

**Issue by prashantvc** [xamarin/xamarin-macios#4670] opened 2018-08-21 16:14 UTC
### Steps to Reproduce

1. Create a new Tabbed App project
2. Start debugging

### Expected Behavior
The app should install on device/simulator and start debugging

### Actual Behavior
The deployed app crashes with exception `NSInvalidArgumentException Reason: -[UIImage _selectedTabBarItemImageWithTintColor:metrics:style:forScreenScale:]: unrecognized selector sent to instance 0x600001462530`

### Environment
https://gist.github.com/prashantvc/3507ae951d5624e25e43d642038035ce#file-versioninformation

### Crash Logs
https://gist.github.com/prashantvc/3507ae951d5624e25e43d642038035ce

**Comment by VincentDondain** [comment] 2018-08-21 17:53
Closing, dupe of https://github.com/xamarin/xamarin-macios/issues/4577. Please install latest XI: 
https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode10/347f472b033073e732b05b33a7e6fe93b37a3d49/145/package/xamarin.ios-11.99.3.243.pkg

**Closed by VincentDondain** 2018-08-21 17:53 UTC
