### ISSUE TITLE
Apps have a black splash screen on latest simulators

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-macios#18777] opened 2023-08-21 14:04 UTC
### Steps to Reproduce

1. File | New | iOS / Maui app
2. Deploy to iOS **16.4** (I am using Xcode 14.3.1)
3. Observe a black splash screen
4. Deploy to iOS 15 (or even 16.0)
5. Observe splash screen

I tested with Xcode to iOS 16.4 and I see a splash screen

### Expected Behavior
Splash screens

### Actual Behavior
Black splash on the latest iOS 16.4

### Environment

<details>
<summary>Version information</summary>

```
Xcode 14.3.1
macOS 13.5
.NET SDK 8 Preview 7 (and the related public workloads)
```

</details>

### Example Project (If Possible)

https://github.com/xamarin/xamarin-macios/assets/1096616/0300b380-b166-4cde-8c96-424ccefbadff

https://github.com/dotnet/maui/assets/27841167/cb29d4b8-f2e3-4612-b472-a54aa04fac90

**Comment by rolfbjarne** [comment] 2023-08-22 15:26
After a lot of debugging I saw this:

> Resource validation error: Cannot validate resource. Bundle is not codesigned: file:///Users/rolf/Library/Developer/CoreSimulator/Devices/9B99FC8C-690B-4D6F-B223-F9E1ABC07362/data/Containers/Bundle/Application/ED2ED47F-3A85-42AA-94ED-43D3B2F084A6/ios.app/MauiSplash.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib

And remembered that I've already debugged this.

The answer is that iOS 16.4+ apparently requires apps to be signed to load the launch screen (which is why this works fine on device - all apps are signed on device).

Closing as duplicate of https://github.com/xamarin/xamarin-macios/issues/18469.

**Closed by rolfbjarne** 2023-08-22 15:26 UTC

**Comment by ithiredguns** [comment] 2023-08-31 16:33
@jfversluis  
Please check out the issue and sample project I have posted ... Could be that it's because of the pdf files I am using for my splash screen ? 

 https://github.com/xamarin/xamarin-macios/issues/18469#issuecomment-1701380891

**Comment by FreakyAli** [comment] 2023-09-06 10:57
@rolfbjarne @jfversluis The suggested workaround does not solve the issue but it forces you to have a dev certificate even when you run on a simulator, Is there something for this that actually works...

**Comment by argentini** [comment] 2023-09-10 22:43
FYI, this also happens in the latest preview of .NET 8 (preview 7).

**Comment by FreakyAli** [comment] 2023-09-10 23:38
The suggested change does nothing on .net 7 and .net 8 even when you add it, it's not like the splash screen starts appearing...

**Comment by SamiAlan** [comment] 2023-11-24 08:42
I'm having an issue where once I debug on a physical device, I can see the splash screen but a black screen appears after that. I tried changing all .svg images to .png and also removed the icons all together with no success.

Running Visual Studio 17.8.1 on Windows
iPhone 17.1.1
.NET 8

**Comment by rolfbjarne** [comment] 2023-11-27 08:21
> I'm having an issue where once I debug on a physical device, I can see the splash screen but a black screen appears after that. I tried changing all .svg images to .png and also removed the icons all together with no success.
> 
> Running Visual Studio 17.8.1 on Windows iPhone 17.1.1 .NET 8

If you have a problem with the splash screen on device, it's a different problem than this one, so please file a new issue and we'll diagnose the problem there.

**Comment by SamiAlan** [comment] 2023-11-27 09:56
> > I'm having an issue where once I debug on a physical device, I can see the splash screen but a black screen appears after that. I tried changing all .svg images to .png and also removed the icons all together with no success.
> > Running Visual Studio 17.8.1 on Windows iPhone 17.1.1 .NET 8
> 
> If you have a problem with the splash screen on device, it's a different problem than this one, so please file a new issue and we'll diagnose the problem there.

I can perfectly see the splash screen and it lasts the usual time it takes for the MAUI app to load but when the app loads and is ready to open the main page, it shows a black screen. I can even see the dialog that asks for the permission to show push notifications but the app itself is just a black screen.

**Comment by KerryXEX** [comment] 2023-12-19 15:21
I finally got the SplashScreen to work on actual device (still not on latest simulator with iOS17,2).
My issue was a very odd false description on the original MS instructions for the "BaseSize" parameter.

The correct BaseSize params are 
BaseSize="[Height],[Width]"  (not the other way round).

I always had width,height as described which then resulted in a black launchscreen.

**Comment by 007vel** [comment] 2024-03-27 06:53
Still, the black screen showing in iOS app launch, any solution?
MAUI .net8

**Comment by SJaschinski** [comment] 2024-05-30 15:35
In my case the issue was solved by scaling my SVG splash screen for iOS to a much smaller base size. When I provided no base size at all the screen stayed black. Providing a base size with the same dimensions as the SVG view box (in my case 1563 x 1882) the screen stayed black. Decreasing the base size to one tenth only on iOS did the job:
`      
        
        <MauiSplashScreen Condition="'$(TargetFramework)'=='net8.0-android'"
                          Include="Resources\Splash\splash.svg"
                          Color="#FFFFFF" />
        
        <MauiSplashScreen Condition="'$(TargetFramework)'=='net8.0-ios'"
                          Include="Resources\Splash\splash.svg"
                          Color="#FFFFFF"
                          BaseSize="156,188" />
`
This solution worked for me on MAUI .NET 8.0.20.

**Comment by chinni-nag** [comment] 2024-10-14 11:50
@SJaschinski Hi, Same code have added but no use , showing same black it self. 
Any other thing need to add any where

**Comment by SJaschinski** [comment] 2024-10-23 08:59
@chinni-nag no more code needed in my case. Have you played with decreasing the base size? In my case it took a lot of try and error until I found the correct base size ratio (one tenth).

**Comment by JayMansel** [comment] 2024-12-10 17:08
Can confirm that reduce the base size to a tenth fixed the issue for me. (Originally 1536:2008 down to 154:201 with some rounding).

**Comment by a-pagano** [comment] 2025-03-07 09:02
> I finally got the SplashScreen to work on actual device (still not on latest simulator with iOS17,2). My issue was a very odd false description on the original MS instructions for the "BaseSize" parameter for iOS. It is correct for Android.
> 
> The correct BaseSize params for IOS are BaseSize="[Height],[Width]" (not the other way round).
> 
> I always had width,height as described which then resulted in a black launchscreen.

This fixed it for us. Reducing the base size made the splash screen display but the scaling was way off with a png. Inverting the Width and Height on ios allowed to display the splash screen with the correct scaling:

```xml
  <MauiSplashScreen Condition="'$(TargetFramework)'=='net9.0-ios'" Include="Resources\Splash\splash.png" Color="#FFFFFF" BaseSize="1334,750"/>
        <MauiSplashScreen Condition="'$(TargetFramework)'=='net9.0-android'" Include="Resources\Splash\splash.png" Color="#FFFFFF" BaseSize="750,1334"/>
```
