### ISSUE TITLE
[Xcode 12] AdditionalAppExtensions entitlements path resolution add space and newline characters causing codesign to fail

### ISSUE THREAD

**Issue by motoko89** [xamarin/xamarin-macios#9458] opened 2020-08-23 18:36 UTC
### Steps to Reproduce

Use this in iOS `csproj`:

    <ItemGroup>
        <AdditionalAppExtensions Include="Widget">
            <Name>WidgetExtension</Name>
           <BuildOutput Condition="'$(Platform)' == 'iPhone' And '$(Configuration)'!='Release'">Build/Products/Debug-iphoneos</BuildOutput>
           <BuildOutput Condition="'$(Platform)' == 'iPhoneSimulator' And '$(Configuration)'!='Release'">Build/Products/Debug-iphonesimulator</BuildOutput>
           <BuildOutput Condition="'$(Platform)' == 'iPhone' And '$(Configuration)'=='Release'">Build/Products/Release-iphoneos</BuildOutput>
           <BuildOutput Condition="'$(Platform)' == 'iPhoneSimulator' And '$(Configuration)'=='Release'">Build/Products/Release-iphonesimulator</BuildOutput>
        </AdditionalAppExtensions>
     </ItemGroup>

Copy entitlement file to the expected location

### Expected Behavior

Build succeeds

### Actual Behavior

Codesign failed because entitlement file can't be read

### Environment
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.7.2 (build 9)
Installation UUID: a1719866-2a3f-41c8-8331-056ac163fbf5
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000090

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.90 (2020-02/d3daacdaa80) (64-bit)
	Package version: 612000090

=== Roslyn (Language Service) ===

3.7.0-6.20371.12+917b9dfae12e3b6cb266a3c062fb20a1e9d5fb06

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.401/Sdks
SDK Versions:
	3.1.401
	3.1.302
	3.1.100
	3.0.103
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.7
	3.1.6
	3.1.0
	3.0.3
	2.1.21
	2.1.20

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.0 (17210.1)
Build 12A8189h

=== Xamarin.Mac ===

Version: 6.99.0.179 (Visual Studio Enterprise)
Hash: 8abd3ebbc
Branch: xcode12
Build date: 2020-08-12 21:56:10-0400

=== Xamarin.iOS ===

Version: 13.99.0.219 (Visual Studio Enterprise)
Hash: a19b0f2c7
Branch: xcode12
Build date: 2020-08-22 15:38:41-0700

=== Xamarin Designer ===

Version: 16.7.0.492
Hash: f5afe667d
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-07-10 18:42:54 UTC

=== Xamarin.Android ===

Version: 11.0.0.3 (Visual Studio Enterprise)
Commit: xamarin-android/d16-7/aca845b
Android SDK: /Users/admin/Library/Android/sdk
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/admin/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/dev/jmt/d16-7readconfig~2
Build date: 2020-07-23 22:38:02 UTC

=== Android Device Manager ===

Version: 16.7.0.18
Hash: 4b44bc1
Branch: remotes/origin/d16-7
Build date: 2020-07-23 22:38:26 UTC

=== Build Information ===

Release ID: 807020009
Git revision: 76b8ecb8cde5f8fc9347bd87919c303832633e50
Build date: 2020-08-13 09:10:10-04
Build branch: merge
Xamarin extensions: 76b8ecb8cde5f8fc9347bd87919c303832633e50

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.0.0 Darwin Kernel Version 20.0.0
    Fri Aug 14 00:25:13 PDT 2020
    root:xnu-7195.40.44.151.1~4/RELEASE_X86_64 x86_64

```
```

### Build Logs

You can see from the build logs that the argument gets broken into 3 lines instead of 1 line:

    Task "Codesign"
    Tool /usr/bin/codesign execution started with arguments: -v --force --timestamp=none --sign "Apple Development: Dev Name (XXX3456789)" --entitlements [Project path]
              /Widget/WidgetExtension.entitlements
             --timestamp=none [app path]/bin/iPhone/Debug/device-builds/iphone10.1-14.0/App.iOS.app/PlugIns/WidgetExtension.appex

Because of this codesign uses the wrong path for entitlement file and can't read it

**Comment by chamons** [comment] 2020-08-24 20:17
I can confirm this using my one-off sample https://github.com/chamons/xamarin-ios-swift-extension

**Comment by chamons** [comment] 2020-08-24 20:33
It appears changing the msbuild to have:
```
<Entitlements Condition="Exists('$(_ExtensionEntitlementPath)')">$(_ExtensionEntitlementPath)</Entitlements>
```
seems to fix it for me locally.

**Comment by chamons** [comment] 2020-08-25 14:43
Should be fixed in latest xcode12 build and a future preview.

Thanks for testing and the detailed bug report!

**Closed by chamons** 2020-08-25 14:43 UTC
Labels: bug, iOS

**Comment by motoko89** [comment] 2020-08-25 17:26
Thanks a lot @chamons , do you know how long it will take before this is available on XCode 12 Preview update channel?

**Comment by chamons** [comment] 2020-08-25 17:31
We were going to do a preview later this week that would include it, but Apple _just_ released a new beta so the soonest we could turn around would be next week.

If you want to try a build from our lane directly, the instructions [are here](https://github.com/xamarin/xamarin-macios/wiki#downloading-a-build) and this is [the lane](https://github.com/xamarin/xamarin-macios/commits/xcode12). It'll likely be at least a few more hours before it finishing building.

**Comment by wojciech-kulik** [comment] 2020-10-05 21:12
@chamons in my case when I'm building my project, it does not take entitlements at all:
```
Target _CodesignAppExtensions:
    Tool /usr/bin/codesign execution started with arguments: -v --force --timestamp=none --sign "Apple Development: XXXX" --timestamp=none [path]/My.iOS.app/PlugIns/MyWidgetExtension.appex
```

CSProj:
```
<AdditionalAppExtensions Include="$(MSBuildProjectDirectory)/../../NativeWidget">
      <Name>MyWidgetExtension</Name>
      <BuildOutput Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhone' ">DerivedData/Project/Build/Products/Debug-iphoneos</BuildOutput>
      <BuildOutput Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhoneSimulator' ">DerivedData/Project/Build/Products/Debug-iphonesimulator</BuildOutput>
      <BuildOutput Condition=" '$(Configuration)|$(Platform)' == 'Release|iPhone' ">DerivedData/Project/Build/Products/Release-iphoneos</BuildOutput>
      <BuildOutput Condition=" '$(Configuration)|$(Platform)' == 'Release|iPhoneSimulator' ">DerivedData/Project/Build/Products/Release-iphonesimulator</BuildOutput>
    </AdditionalAppExtensions>
```

I have `MyWidgetExtension.entitlements` file both in `NativeWidget` directory and `NativeWidget/MyWidget`

Environment:
```Visual Studio Community 2019 for Mac
Version 8.7.8 (build 4)
Installation UUID: 09dfa363-97dc-490c-94e7-b735d8bc4959
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

Mono Framework MDK
Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

Roslyn (Language Service)
3.7.0-6.20427.1+18ede13943b0bfae1b44ef078b2f3923159bcd32

NuGet
Version: 5.7.0.6702

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/3.1.402/Sdks
SDK Versions:
	3.1.402
	3.1.200
	3.1.102
	3.1.101
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.8
	3.1.2
	3.1.1
	2.1.22
	2.1.16
	2.1.15

Xamarin.Profiler
Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 11.0.2.0 (Visual Studio Community)
Commit: xamarin-android/d16-7/025fde9
Android SDK: /Users/wkulik/Library/Android/sdk
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.3

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

Microsoft OpenJDK for Mobile
Java SDK: /Users/wkulik/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-09-16 05:12:24 UTC

Android Device Manager
Version: 16.7.0.24
Hash: bb090a3
Branch: remotes/origin/d16-7
Build date: 2020-09-16 05:12:46 UTC

Xamarin Designer
Version: 16.7.0.495
Hash: 03d50a221
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-08-28 13:12:52 UTC

Apple Developer Tools
Xcode 12.0.1 (17220)
Build 12A7300

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 14.0.0.0 (Visual Studio Community)
Hash: 7ec3751a1
Branch: xcode12
Build date: 2020-09-16 11:33:15-0400

Build Information
Release ID: 807080004
Git revision: 9ea7bef96d65cdc3f4288014a799026ccb1993bc
Build date: 2020-09-16 17:22:54-04
Build branch: release-8.7
Xamarin extensions: 9ea7bef96d65cdc3f4288014a799026ccb1993bc

Operating System
Mac OS X 10.15.6
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Thu Jun 18 20:49:00 PDT 2020
    root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
```

Any idea how to make it work?

**Comment by mobilinked** [comment] 2020-10-21 06:40
@wojciech-kulik, thank you for sharing. 

I have tried your method to test the widget and intent on the iPad, and the codesign command works well. But I have a problem to release the app to the app store, what's the step I have tried: 
- Build for App Store 
- Run the codesign commands to codesign the entitlements into the widget extension in the app bundle in the bin/Appstore folder 
- Then click the archive menu to archive 
- Upload to the app store and test via TestFlight. But now the "entitlements" does not work (no way to share a file via App Group)

Would you please help to share your experience on this issue?

**Comment by wojciech-kulik** [comment] 2020-10-21 10:35
@mobilinked I also experienced this issue. However, I've found the root cause and fixed it here: https://github.com/xamarin/xamarin-macios/pull/9846

You can apply this fix locally, just find the file from PR and change it on your computer :). You have to put entitlements in the same folder that you pointed in csproj. You can check if it works by browsing into `appex` file or just by looking at build logs (`codesign` command should have `--entitlements` parameter)

**Comment by mobilinked** [comment] 2020-10-22 04:24
@wojciech-kulik, thanks much. All works now. 

It was really a very tough time to add a widget with intent and needs to call WidgetKitCenter functions.
