### ISSUE TITLE
Tooling should reference github issues not bugzilla

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#3823] opened 2018-03-28 14:11 UTC
There are a number of places in our code where we reference filing bugzilla bugs:

https://github.com/xamarin/xamarin-macios/blob/master/tools/mmp/driver.cs#L850

Those need to be scrubbed and point to github issues.

**Comment by spouliot** [comment] 2018-04-02 20:23
dupe of #3647

**Closed by spouliot** 2018-04-02 20:23 UTC
Labels: enhancement, iOS, macOS
