### ISSUE TITLE
Odd/changed linker behaviour in Xamarion.iOS 12.14

### ISSUE THREAD

**Issue by beeradmoore** [xamarin/xamarin-macios#6711] opened 2019-08-05 07:49 UTC
### Steps to Reproduce

1. Create a new Xamarin.iOS app.
2. Add a linker.xml file with the contents of, 
```
<?xml version="1.0" encoding="UTF-8"?>
<linker>
	<assembly fullname="Xamarin.iOS">
		<namespace fullname="AVFoundation" />
	</assembly>
</linker>
```
3. Set the build action of the file to LinkDescription. (side note: In my main project I was using the linker.xml as content, and using additional mtouch arguments of `--xml=${ProjectDir}/linker.xml` but the result is the same when using LinkDescription)
4. Build for release on an iPhone device.

### Expected Behavior
Build completes. (as it did on Xamarin.iOS 12.10)

### Actual Behavior
2 errors.
```
/Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.110/src/Xamarin.iOS/AVFoundation/AVAudioMixInputParameters.g.cs(125): error MT4104: The registrar cannot marshal the return value of type `MediaToolbox.MTAudioProcessingTap` in the method `AVFoundation.AVAudioMixInputParameters.get_AudioTapProcessor()`.
/Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.110/src/Xamarin.iOS/AVFoundation/AVMutableAudioMixInputParameters.g.cs(123): error MT4104: The registrar cannot marshal the return value of type `MediaToolbox.MTAudioProcessingTap` in the method `AVFoundation.AVMutableAudioMixInputParameters.get_AudioTapProcessor()`.
```
### Environment

```
Visual Studio Community 2019 for Mac
Version 8.2.1 (build 19)
Installation UUID: 847e2f18-c83c-4fec-b1f7-d8892f7fe125
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000311

Mono Framework MDK
Runtime:
	Mono 6.0.0.311 (2019-02/494641b300c) (64-bit)
	Package version: 600000311

NuGet
Version: 5.1.0.6013

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.4
	2.1.10
	2.1.9
	2.1.8
	2.1.7
	2.1.6
	2.1.2
SDK: /usr/local/share/dotnet/sdk/2.2.203/Sdks
SDK Versions:
	2.2.203
	2.1.505
	2.1.504
	2.1.503
	2.1.500
	2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

Xamarin.Profiler
Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 9.4.0.51 (Visual Studio Community)
Commit: xamarin-android/d16-2/9fa7775
Android SDK: /Users/bradmoore/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.1
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

Microsoft Mobile OpenJDK
Java SDK: /Users/bradmoore/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 1.2.0.58
Hash: d03e3ea
Branch: remotes/origin/d16-2~1
Build date: 2019-07-16 17:37:14 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Apple Developer Tools
Xcode 10.3 (14492.2)
Build 10G8

Xamarin.Mac
Version: 5.14.0.110 (Visual Studio Community)
Hash: a8bcecce
Branch: d16-2
Build date: 2019-06-28 07:31:43-0400

Xamarin.iOS
Version: 12.14.0.110 (Visual Studio Community)
Hash: a8bcecce
Branch: d16-2
Build date: 2019-06-28 07:31:42-0400

Xamarin Designer
Version: 16.2.0.375
Hash: 357d38ef4
Branch: remotes/origin/d16-2
Build date: 2019-07-26 14:44:54 UTC

Build Information
Release ID: 802010019
Git revision: c7aee29ba7d2a827dbfe4901e4ad7249ce7e5bc7
Build date: 2019-07-29 20:22:23+00
Build branch: release-8.2
Xamarin extensions: c990de17e8456ead7fce80aff9dab01df769b2fd

Operating System
Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Thu Jun 20 18:42:21 PDT 2019
    root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

Enabled user installed extensions
MonoGame Extension 3.7.1.189
MFractor 3.8.9
```

### Build Logs

https://gist.github.com/beeradmoore/f3a9862e7eb7fb6466e005301cd00297

### Example Project (If Possible)

[LinkerTest.zip](https://github.com/xamarin/xamarin-macios/files/3466419/LinkerTest.zip)

**Comment by Physikbuddha** [comment] 2019-08-05 18:13
I can confirm that something related to the linker has changed in Xamarin.iOS 12.14.
I haven't created a separate bug report (yet), but since Xamarin 12.14 I can't compile my app using the LLVM compiler anymore.

The build process appears to be stuck. However the Mac is getting really warm and the system information tool shows lld (LLVM linker) eating up all of the Mac's CPU time. After ~1.5 hours, the build finally fails with about 70,000 errors, all of them something like "Failed to link class ...". It's probably listing the whole .NET framework.

Luckily I was able to downgrade VS and Xamarin.iOS back to 12.10, but I have to update eventually. 
I'm not on my workstation right now, so please excuse the vague description. Might post a detailed bug report in the next few days.

**Comment by beeradmoore** [comment] 2019-08-05 23:47
This issue is still replicatable with the Xamarin.iOS 12.14.0.114 update from today.

```
Visual Studio Community 2019 for Mac
Version 8.2.2 (build 21)
Installation UUID: c6eb5dbe-6cdb-491c-8f61-f84648dd09f7
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000319

Mono Framework MDK
Runtime:
	Mono 6.0.0.319 (2019-02/52203786470) (64-bit)
	Package version: 600000319

NuGet
Version: 5.1.0.6013

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.4
	2.1.10
	2.1.9
	2.1.8
	2.1.7
	2.1.6
	2.1.2
SDK: /usr/local/share/dotnet/sdk/2.2.203/Sdks
SDK Versions:
	2.2.203
	2.1.505
	2.1.504
	2.1.503
	2.1.500
	2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

Xamarin.Profiler
Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 9.4.1.0 (Visual Studio Community)
Commit: xamarin-android/d16-2/ebd65c9
Android SDK: /Users/someuser/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.1
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

Microsoft Mobile OpenJDK
Java SDK: /Users/someuser/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 1.2.0.58
Hash: d03e3ea
Branch: remotes/origin/d16-2~1
Build date: 2019-07-30 21:29:36 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Xamarin Designer
Version: 16.2.0.379
Hash: 3f0652957
Branch: remotes/origin/d16-2
Build date: 2019-08-01 17:32:50 UTC

Apple Developer Tools
Xcode 10.3 (14492.2)
Build 10G8

Xamarin.Mac
Version: 5.14.0.114 (Visual Studio Community)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:06-0400

Xamarin.iOS
Version: 12.14.0.114 (Visual Studio Community)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:05-0400

Build Information
Release ID: 802020021
Git revision: d2ffd09000c5d24a206b715b63d409e8e965689a
Build date: 2019-08-02 00:25:49+00
Build branch: release-8.2
Xamarin extensions: 4cc9cbbe68baaeb6bc654f36e057b1bd124f3f65

Operating System
Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Thu Jun 20 18:42:21 PDT 2019
    root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

Enabled user installed extensions
MonoGame Extension 3.7.1.189
MFractor 3.8.9
```

**Comment by chamons** [comment] 2019-08-07 16:54
I can confirm this on stable. 

You can work around this by adding this to your xml
```
        <namespace fullname="MediaToolbox" />
```

**Comment by chamons** [comment] 2019-08-07 16:55
cc @spouliot - Maybe a lead on the linker changes you were talking about? Or just unrelated?

**Comment by spouliot** [comment] 2019-08-07 17:49
It seems the static registrar does not see `MTAudioProcessingTap` as being a `INativeObject` anymore... that might be due to change in the (mono) linker code wrt interfaces removal.

**Comment by spouliot** [comment] 2019-08-07 18:44
@beeradmoore thanks for your test case :-)

Under some circumstances the linker can now remove/optimize away `INativeObject` from `MTAudioProcessingTap` - which makes the static registrar unable to generated the required glue code for the properties (mentioned in the error message).

While the behaviour itself is fine (for the linker) it's something that, for **Link SDK frameworks** should be handled automatically and will be fixed in an upcoming release. Until then the workaround from @chamons (or simply preserving the `MTAudioProcessingTap` type) can be used  to achieve the same result.

**Comment by beeradmoore** [comment] 2019-08-08 01:38
That workaround worked for me. Thanks!
I'll try reproduce the issue as to why I have to add AVFoundation to my linker at all and file it under a different issue and see if there is another issue that could be resolved.

**Comment by spouliot** [comment] 2019-08-08 02:09
@beeradmoore In general when reflection is not used (directly or indirectly) then **Link SDK** should not require the use of XML files (or similar tricks) to produce a working application.  So it would be nice (and really appreciated) if you can give us a test case for the original issue :)

**Closed** 2019-08-08 21:19 UTC
Labels: bug, iOS
