### ISSUE TITLE
Using SocketsHttpHandler and NSUrlSessionHandler in the same net8.0-ios project causes incorrect 401 runtime errors for NTLM authorized HTTP requests

### ISSUE THREAD

**Issue by JeroenBer** [xamarin/xamarin-macios#20311] opened 2024-03-15 15:17 UTC
We ported our Xamarin iOS application to .NET 8 (net8.0-ios). We use SocketsHttpHandler and NSUrlSessionHandler in the same project. We use SocketsHttpHandler for NTLM requests and NSUrlSessionHandler for other requests. 

Ntlm SocketsHttpHandler can do HTTP requests with NTLM authorization. But if you also use NSUrlSessionHandler and once you hit a 401 in NSUrlSessionHandler it seems this has the nasty side effect that NTLM authorization in SocketsHttpHandler is broken.

### Steps to Reproduce

1. Do a NTLM authorized HTTP Requests with SocketsHttpHandler (Succes)
2. Do a NSUrlSessionHandler request which returns a 401
3. Do the same request as in step 1 and now it will also start failing with a 401. This is not correct, it should still work.

### Expected Behavior
SocketHttpHandler requests should not be influenced by NSUrlSessionHandler requests

### Actual Behavior
401 on NSUrlSessionHandler causes NTLM to fail on SocketHttpHandler

### Environment

Environment is Microsoft.iOS.Sdk/17.2.8022

### Example Project (If Possible)

1. Clone project https://github.com/JeroenBer/TestHttpClientHandlers
2. Run "HttpMessageHandlerTests.iOS" project in Debug mode
3. Click on button "NTLM Test"
4. This will run the code in NtlmTest.cs

You can see this code unexpectedly fails now:

```
    public static async Task<string> RunTest()
    {
        await SocketsHttpRequest();
        await SocketsHttpRequest();
        await SocketsHttpRequest();

        // force a 401 request with NSUrlSessionHandler
        await NsUrlSessionHandler401Request();
        
        // This http request now unexpectedly fails!!!
        await SocketsHttpRequest();
        return "OK";
    }
```

**Comment by rolfbjarne** [comment] 2024-03-18 10:07
I can reproduce.

This seems to be an issue in `SocketsHttpHandler`; nothing `NSUrlSessionHandler` does should affect how `SocketsHttpHandler` works, so I'm moving to dotnet/runtime (where the implementation of `SocketsHttpHandler` lives).

**Comment by rolfbjarne** [comment] 2024-03-18 10:08
This issue was moved to dotnet/runtime#99892

**Closed by rolfbjarne** 2024-03-18 10:08 UTC
