### ISSUE TITLE
[Bug] Don't Link causes iOS apps to crash on iPad OS & iOS 13.1 devices

### ISSUE THREAD

**Issue by amirvenus** [xamarin/xamarin-macios#7402] opened 2019-10-11 01:21 UTC
### Description

Using Don't Link option causes the app to crash immediately upon startup on iPad OS  and iOS 13.1.

### Steps to Reproduce

1.  Open Visual Studio for Mac, Create a new XF project 
2. Change the iOS build settings and set to Don't Link
3. Run the app

### Expected Behavior

It shouldn't crash!

### Actual Behavior

It crashes upon app start up.

### Basic Information

- Version with issue: 4.2.0.848062
- Last known good version: N/A
- IDE: Visual Studio for Mac 8.3.3 (build 8)
- Platform Target Frameworks: 
  - iOS:  iPad OS  and iOS 13.1

**Comment by chamons** [comment] 2019-11-12 19:37
I just tried to reproduce this with:

- A new Xamarin.Forms Empty project
- Built on release or debug
- With Linker Behavior: Don't Link
- Against Xcode 11.2
- Run on iOS 13.1.3 iPhone

And was unable to reproduce. Someone please attach a project and detailed steps to reproduce.

**Comment by vecalion** [comment] 2019-12-12 11:25
I'm getting the same crash. A little more info. This is something related to Hot Reload. 
- When I tap on the installed app on the phone it runs without any problems. It crashes only when I try to debug the app from VS.
- With Disable XAML Hot Reload, the app doesn't crash.

**Comment by chamons** [comment] 2019-12-12 17:24
@vecalion - This bug is at the point it can be closed due to lack of info. Can you please attach a project showing the problem?

**Comment by vecalion** [comment] 2019-12-12 17:36
@chamons here we go:
[testapp.zip](https://github.com/xamarin/xamarin-macios/files/3957070/testapp.zip)

As it was mentioned before - just a blank project (master-details in this case). What's important - Linker settings for the iOS project should be set to Don't Link AND Hot Reload should be turned on (Preferences -> Projects -> Xamarin Hot Reload)

**Comment by chamons** [comment] 2019-12-23 22:48
This was the piece I was missing. Reproducible on my end.

```As it was mentioned before - just a blank project (master-details in this case). What's important - Linker settings for the iOS project should be set to Don't Link AND Hot Reload should be turned on (Preferences -> Projects -> Xamarin Hot Reload)```

**Comment by chamons** [comment] 2019-12-23 23:11
Apologies in the delay in response.

This is a duplicate of https://github.com/xamarin/xamarin-macios/issues/7173#issuecomment-541900770 . Updating to the current preview channel fixes this.

**Closed by chamons** 2019-12-23 23:11 UTC
Labels: bug, iOS
