### ISSUE TITLE
MTOUCH : error MT2001: Could not link assemblies. Reason: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by doudouLin** [xamarin/xamarin-macios#3210] opened 2018-01-12 12:52 UTC
### Steps to Reproduce

1. update mac mini operating system to High Sierra version 10.13.2
2. update xCode to 9
3. update all packages in xamarin iOS project
4. can not compile anymore, alway got the error: could not link assemblies....

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.3.3 (build 5)
Runtime:
	Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010007

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Laufzeit: /usr/local/share/dotnet/dotnet
Laufzeitversionen:
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK-Versionen:
	2.1.4
	2.0.0
MSBuild-SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.0
Speicherort: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.1.3.0 (Visual Studio Community)
Android SDK: /Users/hongjuanlin/Library/Developer/Xamarin/android-sdk-macosx
	Unterstützte Android-Versionen:
		4.4    (API-Ebene 19)
		4.4.87 (API-Ebene 20)
		5.0    (API-Ebene 21)
		5.1    (API-Ebene 22)
		6.0    (API-Ebene 23)
		7.0    (API-Ebene 24)
		7.1    (API-Ebene 25)
		8.0    (API-Ebene 26)

Version der SDK-Tools: 26.1.1
Version der SDK-Plattformtools: 26.0.2
Version der SDK-Buildtools: 26.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL-Code ist hier verfügbar:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.3.2
Hash: 461f09a
Branch: 1.3-release
Build date: Tue, 03 Oct 2017 18:26:57 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.iOS ===

Version: 11.6.1.3 (Visual Studio Community)
Hash: f70a1348
Branch: xcode9.2
Build date: 2017-12-18 14:47:16-0500

=== Xamarin.Mac ===

Version: 4.0.0.215 (Visual Studio Community)

=== Build Information ===

Release ID: 703030005
Git revision: b1c2982e201e71ef758866c9ade05f253a8c6f47
Build date: 2017-12-21 11:04:40-05
Xamarin addins: f397ddfbacfb39e60c9cc8d9e410f73faf8c2cbc
Build lane: monodevelop-lion-d15-5

=== Operating System ===

Mac OS X 10.13.2
Darwin 17.3.0 Darwin Kernel Version 17.3.0
    Thu Nov  9 18:09:22 PST 2017
    root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1
```

### Build Logs

```
    MTOUCH : error MT2001: Could not link assemblies. Reason: Object reference not set to an instance of an object
    --- inner exception
    System.NullReferenceException: Object reference not set to an instance of an object
      at Mono.Linker.TypeReferenceExtensions+<GetMethods>d__4.MoveNext () [0x00047] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/external/linker/linker/Mono.Linker/TypeReferenceExtensions.cs:169 
      at Mono.Linker.Steps.TypeMapStep.TryMatchMethod (Mono.Cecil.TypeReference type, Mono.Cecil.MethodDefinition method) [0x0002d] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/external/linker/linker/Mono.Linker.Steps/TypeMapStep.cs:170 
      at Mono.Linker.Steps.TypeMapStep+<GetBaseMethodsInInterfaceHierarchy>d__12.MoveNext () [0x0006c] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/external/linker/linker/Mono.Linker.Steps/TypeMapStep.cs:159 
      at Mono.Linker.Steps.TypeMapStep.MapVirtualInterfaceMethod (Mono.Cecil.MethodDefinition method) [0x00020] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/external/linker/linker/Mono.Linker.Steps/TypeMapStep.cs:111 
      at Mono.Linker.Steps.TypeMapStep.MapVirtualMethod (Mono.Cecil.MethodDefinition method) [0x00009] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/external/linker/linker/Mono.Linker.Steps/TypeMapStep.cs:97 
      at Mono.Linker.Steps.TypeMapStep.MapVirtualMethods (Mono.Cecil.TypeDefinition type) [0x00037] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/external/linker/linker/Mono.Linker.Steps/TypeMapStep.cs:87 
      at Mono.Linker.Steps.TypeMapStep.MapType (Mono.Cecil.TypeDefinition type) [0x00001] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/external/linker/linker/Mono.Linker.Steps/TypeMapStep.cs:45 
      at MonoTouch.Tuner.MonoTouchTypeMapStep.MapType (Mono.Cecil.TypeDefinition type) [0x00001] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/tools/linker/MonoTouch.Tuner/MonoTouchTypeMap.cs:45 
      at Mono.Linker.Steps.TypeMapStep.ProcessAssembly (Mono.Cecil.AssemblyDefinition assembly) [0x0001d] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/external/linker/linker/Mono.Linker.Steps/TypeMapStep.cs:40 
      at Mono.Linker.Steps.BaseStep.Process (Mono.Linker.LinkContext context) [0x0002e] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/external/linker/linker/Mono.Linker.Steps/BaseStep.cs:55 
      at Mono.Linker.Pipeline.Process (Mono.Linker.LinkContext context) [0x0001e] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/external/linker/linker/Mono.Linker/Pipeline.cs:127 
      at MonoTouch.Tuner.Linker.Process (MonoTouch.Tuner.LinkerOptions options, MonoTouch.Tuner.MonoTouchLinkContext& context, System.Collections.Generic.List`1[Mono.Cecil.AssemblyDefinition]& assemblies) [0x000e0] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/tools/mtouch/Tuning.cs:82 
    ---
      at MonoTouch.Tuner.Linker.Process (MonoTouch.Tuner.LinkerOptions options, MonoTouch.Tuner.MonoTouchLinkContext& context, System.Collections.Generic.List`1[Mono.Cecil.AssemblyDefinition]& assemblies) [0x003ad] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/tools/mtouch/Tuning.cs:124 
      at Xamarin.Bundler.Target.LinkAssemblies (System.Collections.Generic.List`1[Mono.Cecil.AssemblyDefinition]& assemblies, System.String output_dir, System.Collections.Generic.IEnumerable`1[T] sharedCodeTargets) [0x0029f] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/tools/mtouch/Target.cs:491 
      at Xamarin.Bundler.Target.ManagedLink () [0x005c5] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/tools/mtouch/Target.cs:614 
      at Xamarin.Bundler.Target.ProcessAssemblies () [0x000bb] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/tools/mtouch/Target.cs:800 
      at Xamarin.Bundler.Application.ProcessAssemblies () [0x0002f] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/tools/mtouch/Application.cs:1407 
      at Xamarin.Bundler.Application.BuildManaged () [0x00001] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/tools/mtouch/Application.cs:831 
      at Xamarin.Bundler.Application+<>c.<BuildAll>b__134_1 (Xamarin.Bundler.Application v) [0x00000] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/tools/mtouch/Application.cs:779 
      at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x00024] in <4fdc5ed61a074cafb49fa42deb20d521>:0 
      at Xamarin.Bundler.Application.BuildAll () [0x00050] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/tools/mtouch/Application.cs:779 
      at Xamarin.Bundler.Driver.Main2 (System.String[] args) [0x00481] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/tools/mtouch/mtouch.cs:1403 
      at Xamarin.Bundler.Driver.Main (System.String[] args) [0x00015] in /Users/builder/data/lanes/5665/f70a1348/source/xamarin-macios/tools/mtouch/mtouch.cs:928 
    The command exited with code 1.
    Output Property: _CompiledArchitectures=ARM64
  Done executing task "MTouch" -- FAILED.
Done building target "_CompileToNative" in project "JumpinMobile.iOS.csproj" -- FAILED.

Done building project "JumpinMobile.iOS.csproj" -- FAILED.

Project Evaluation Performance Summary:
       92 ms  /Users/hongjuanlin/Projects/JumpinApp/JumpinMobile.Core/JumpinMobile.Core.csproj   2 calls
       96 ms  /Users/hongjuanlin/Projects/JumpinApp/JumpinMobile/JumpinMobile.csproj   2 calls

Project Performance Summary:
       21 ms  /Users/hongjuanlin/Projects/JumpinApp/JumpinMobile.Core/JumpinMobile.Core.csproj   4 calls
       35 ms  /Users/hongjuanlin/Projects/JumpinApp/JumpinMobile/JumpinMobile.csproj   4 calls
    11597 ms  /Users/hongjuanlin/Projects/JumpinApp/iOS/JumpinMobile.iOS.csproj   1 calls

Target Performance Summary:
        * ms  GetCopyToOutputDirectoryItems              1 calls
        0 ms  ResGen                                     1 calls
        0 ms  PrepareForRun                              1 calls
        0 ms  AfterResGen                                1 calls
        0 ms  PrepareResources                           1 calls
        0 ms  _CopySourceItemsToOutputDirectory          1 calls
        0 ms  SetWin32ManifestProperties                 1 calls
        0 ms  _CompileSceneKitAssets                     1 calls
        0 ms  BeforeCompile                              1 calls
        0 ms  XamlG                                      1 calls
        0 ms  _CompileTextureAtlases                     1 calls
        0 ms  PrepareProjectReferences                   1 calls
        0 ms  _CompileColladaAssets                      1 calls
        0 ms  BeforeResolveReferences                    1 calls
        0 ms  _XamarinBuildDownloadMasterTarget          1 calls
        0 ms  ResolveNativeReferences                    1 calls
        0 ms  PrepareResourceNames                       1 calls
        0 ms  AfterCompile                               1 calls
        0 ms  _OptimizeLocalizationFiles                 1 calls
        0 ms  BeforeResGen                               1 calls
        0 ms  _OptimizePngImages                         1 calls
        0 ms  _CompileInterfaceDefinitions               1 calls
        0 ms  _CompileImageAssets                        1 calls
        0 ms  _XamarinBuildDownload                      1 calls
        0 ms  ResolveReferences                          1 calls
        0 ms  _XamarinBuildAddDownloadedItems            1 calls
        0 ms  AfterBuild                                 1 calls
        0 ms  CreateCustomManifestResourceNames          1 calls
        0 ms  Compile                                    1 calls
        0 ms  BeforeBuild                                1 calls
        0 ms  CreateSatelliteAssemblies                  1 calls
        0 ms  CoreBuild                                  1 calls
        0 ms  GenerateManifests                          1 calls
        0 ms  BclBuildSetRunningFullBuild                1 calls
        0 ms  AfterResolveReferences                     1 calls
        0 ms  GetTargetFrameworkProperties               2 calls
        0 ms  _OptimizePropertyLists                     1 calls
        0 ms  _RoslynPublicSignHack                      1 calls
        0 ms  _SplitAppExtensionReferencesByExistent     1 calls
        0 ms  GetFrameworkPaths                          1 calls
        0 ms  _PrepareResourceRules                      1 calls
        0 ms  ExpandSDKReferences                        1 calls
        0 ms  ResolveSDKReferences                       1 calls
        0 ms  _CoreCompileSceneKitAssets                 1 calls
        0 ms  _SplitWatchAppReferencesByExistent         1 calls
        0 ms  _SetTargetFrameworkMonikerAttribute        1 calls
        0 ms  _CoreOptimizeLocalizationFiles             1 calls
        0 ms  _CoreCompileColladaAssets                  1 calls
        0 ms  BuildOnlySettings                          1 calls
        0 ms  _CoreCompileTextureAtlases                 1 calls
        0 ms  _GetCompileToNativeInputs                  1 calls
        0 ms  _ResolveAppExtensionReferences             1 calls
        0 ms  BclBuildGetTargetPath                      1 calls
        0 ms  _CoreXamlG                                 1 calls
        0 ms  _ReadCoreCompileInterfaceDefinitions       1 calls
        0 ms  GetInstalledSDKLocations                   1 calls
        0 ms  _ReadCoreCompileTextureAtlases             1 calls
        0 ms  GetTargetPath                              2 calls
        0 ms  _ReadCoreCompileSceneKitAssets             1 calls
        0 ms  _CheckForCompileOutputs                    1 calls
        0 ms  _SeparateWatchAppReferences                1 calls
        0 ms  _BeforeCompileTextureAtlases               3 calls
        0 ms  _BeforeCoreCompileSceneKitAssets           3 calls
        0 ms  _GenerateBundleName                        1 calls
        0 ms  _SeparateAppExtensionReferences            1 calls
        0 ms  _PreXamlG                                  1 calls
        0 ms  BclBuildAddProjectReferenceProperties      1 calls
        0 ms  _GenerateCompileInputs                     1 calls
        0 ms  _ResolveWatchAppReferences                 1 calls
        0 ms  _ParseExtraMtouchArgs                      1 calls
        0 ms  GenerateBindingRedirectsUpdateAppConfig    1 calls
        0 ms  _ReadCompileImageAssets                    1 calls
        0 ms  _SetEmbeddedWin32ManifestProperties        1 calls
        0 ms  _FirebaseInstanceIDItems                   1 calls
        0 ms  _FirebaseAnalyticsItems                    1 calls
        0 ms  GetNativeManifest                          2 calls
        0 ms  _ValidateXFTasks                           1 calls
        0 ms  _DetectDebugNetworkConfiguration           1 calls
        1 ms  CoreResGen                                 1 calls
        1 ms  _CreateAssetPackManifest                   1 calls
        1 ms  _CleanUploaded                             1 calls
        1 ms  GenerateTargetFrameworkMonikerAttribute    1 calls
        1 ms  _BeforeCoreCompileInterfaceDefinitions     1 calls
        1 ms  _CollectXamlFiles                          1 calls
        1 ms  _CollectColladaAssets                      1 calls
        1 ms  _CollectPropertyLists                      1 calls
        1 ms  _AfterCoreOptimizePropertyLists            1 calls
        1 ms  _CopyOutOfDateSourceItemsToOutputDirectoryAlways   1 calls
        1 ms  SplitResourcesByCulture                    1 calls
        1 ms  _FirebaseCloudMessagingItems               1 calls
        1 ms  _CopyAppConfigFile                         1 calls
        1 ms  _CheckForInvalidConfigurationAndPlatform   1 calls
        1 ms  _CollectLocalizationFiles                  1 calls
        1 ms  _FirebaseCoreItemsFolder                   1 calls
        1 ms  _BeforeCoreCompileImageAssets              1 calls
        1 ms  PrepareForBuild                            1 calls
        1 ms  _ComputeTargetArchitectures                1 calls
        2 ms  _GetNativeExecutableName                   1 calls
        2 ms  AssignProjectConfiguration                 1 calls
        2 ms  _CollectPngImages                          1 calls
        2 ms  _XamarinBuildDownloadCore                  1 calls
        2 ms  CopyFilesToOutputDirectory                 1 calls
        2 ms  GetReferenceAssemblyPaths                  1 calls
        2 ms  GenerateBindingRedirects                   1 calls
        2 ms  _SplitProjectReferencesByFileExistence     3 calls
        2 ms  _CompileEntitlements                       1 calls
        2 ms  GetTargetPathWithTargetPlatformMoniker     3 calls
        3 ms  BclBuildValidateNugetPackageReferences     2 calls
        3 ms  _DetectAppManifest                         1 calls
        3 ms  _CollectBundleResources                    1 calls
        5 ms  _DetectSdkLocations                        1 calls
        6 ms  _AfterCoreOptimizePngImages                1 calls
        6 ms  _CompileAppManifest                        1 calls
        9 ms  _ComputeBundleResourceOutputPaths          1 calls
       10 ms  AssignTargetPaths                          3 calls
       15 ms  _DetectSigningIdentity                     1 calls
       17 ms  _GenerateSatelliteAssemblyInputs           1 calls
       21 ms  _GenerateCompileDependencyCache            1 calls
       32 ms  _CopyResourcesToBundle                     1 calls
       40 ms  IncrementalClean                           1 calls
       46 ms  ImplicitlyExpandDesignTimeFacades          1 calls
       65 ms  _XamariniOSBuildResourceRestore            1 calls
       82 ms  FindReferenceAssembliesForReferences       1 calls
      106 ms  _CleanGetCurrentAndPriorFileWrites         1 calls
      118 ms  _CoreOptimizePropertyLists                 1 calls
      135 ms  ResolveProjectReferences                   1 calls
      135 ms  _GetProjectReferenceTargetFrameworkProperties   4 calls
      156 ms  _CoreCompileImageAssets                    1 calls
      219 ms  _UnpackLibraryResources                    1 calls
      265 ms  XamlC                                      1 calls
      307 ms  ResolveAssemblyReferences                  1 calls
      504 ms  _CopyFilesMarkedCopyLocal                  1 calls
     1502 ms  CoreCompile                                1 calls
     1662 ms  _CoreOptimizePngImages                     1 calls
     2332 ms  _CoreCompileInterfaceDefinitions           1 calls
     3713 ms  _CompileToNative                           1 calls
        (* = timing was not recorded because of reentrancy)

Task Performance Summary:
        * ms  MSBuild                                    5 calls
        0 ms  GetFrameworkPath                           1 calls
        0 ms  AssignCulture                              1 calls
        0 ms  GetTasksAbi                                1 calls
        0 ms  ReadLinesFromFile                          1 calls
        0 ms  ParseExtraMtouchArgs                       1 calls
        0 ms  GetReferenceAssemblyPaths                  1 calls
        0 ms  FindAppConfigFile                          1 calls
        0 ms  DetectDebugNetworkConfiguration            1 calls
        0 ms  FixedCreateCSharpManifestResourceName      1 calls
        0 ms  CreateAssetPackManifest                    1 calls
        0 ms  Touch                                      1 calls
        1 ms  RemoveDir                                  2 calls
        1 ms  ParseDeviceSpecificBuildInformation        1 calls
        1 ms  MakeDir                                    2 calls
        1 ms  ResolveNonMSBuildProjectOutput             1 calls
        1 ms  Delete                                     5 calls
        1 ms  AssignProjectConfiguration                 1 calls
        1 ms  GenerateBindingRedirects                   1 calls
        1 ms  GetNativeExecutableName                    1 calls
        2 ms  XamarinDownloadArchives                    1 calls
        2 ms  CompileEntitlements                        1 calls
        2 ms  ValidatePackageReferences                  2 calls
        3 ms  FindItemWithLogicalName                    1 calls
        3 ms  WriteItemsToFile                           3 calls
        4 ms  CollectBundleResources                     2 calls
        4 ms  Message                                    4 calls
        5 ms  AssignTargetPath                          15 calls
        5 ms  DetectSdkLocations                         1 calls
        5 ms  CompileAppManifest                         1 calls
        6 ms  CreateItem                                18 calls
        7 ms  ConvertToAbsolutePath                      1 calls
        8 ms  Hash                                       1 calls
        9 ms  ComputeBundleResourceOutputPaths           1 calls
       12 ms  WriteLinesToFile                           2 calls
       15 ms  DetectSigningIdentity                      1 calls
       28 ms  SmartCopy                                  1 calls
       35 ms  RemoveDuplicates                           2 calls
       65 ms  XamarinBuildiOSResourceRestore             1 calls
       68 ms  FindUnderPath                              5 calls
      118 ms  OptimizePropertyList                       1 calls
      153 ms  ACTool                                     1 calls
      219 ms  UnpackLibraryResources                     1 calls
      265 ms  XamlCTask                                  1 calls
      305 ms  ResolveAssemblyReference                   1 calls
      505 ms  Copy                                       5 calls
     1500 ms  Csc                                        1 calls
     1661 ms  OptimizeImage                              1 calls
     2330 ms  IBTool                                     1 calls
     3708 ms  MTouch                                     1 calls
        (* = timing was not recorded because of reentrancy)

Build FAILED.
```

**Comment by spouliot** [comment] 2018-01-12 18:55
The steps to reproduce are not complete enough. This happens for something specific to your project so we need more details, ideally a small test case that reproduce the issue (that can be attached here).

**Comment by doudouLin** [comment] 2018-01-15 09:47
@spouliot hi Spouliot, thank you very much for your reply. I haven't create test case and upload to github before, need a bit time to check how to do it. will come back as soon as i figure it out.

Best regards
Lin

**Comment by spouliot** [comment] 2018-01-15 14:05
In most case you can create a zip file from your project (do a clean first so it will be a lot smaller) and drag it into a comment text box of this issue.

**Comment by spouliot** [comment] 2018-01-15 17:14
Your stack trace looks quite similar to the one from issue #3215 
It's quite possible you are running into a similar case where you have a reference to a BCL assembly from the desktop .net (and not from XI SDK or net standard).

**Comment by doudouLin** [comment] 2018-01-15 17:59
my company doesn't allow me to upload code to internet. I am not able to do that:(

**Comment by doudouLin** [comment] 2018-01-15 18:02
sorry, i am new to Xamarin, could you please indicte me that where can i check and change this BCL reference? you mean Microsoft.Bcl.Build package?

**Comment by doudouLin** [comment] 2018-01-15 18:05
can I write you email to discuss this? is it ok for you?

**Comment by doudouLin** [comment] 2018-01-17 08:53
![image](https://user-images.githubusercontent.com/19983434/35033568-79791caa-fb6b-11e7-97b7-2798df17328c.png)

@spouliot hi Sebastien, I attached a photo for my reference in xamarin.iOS project, by BCL assembly, do you mean the references here?

cheers
Lin

**Comment by spouliot** [comment] 2018-01-17 13:54
They are references, but they are not *all* the references (it's recursive). One of them (not something we ship) is likely referencing a *desktop* (not mobile) version of a .net assembly. The mobile version does not include everything (e.g. `System.Configuration`) so the tool will fail when it encounters such references (since it's missing and cannot be bundled into the app).

**Comment by doudouLin** [comment] 2018-01-17 14:13
Is there a way to check which one is referencing the desktop version of a .net assembly? and change it to the proper assembly?

I have seen that you adapted the linker code, added null check. Could that be helpful for my problem?

**Comment by KSchau** [comment] 2018-01-19 17:34
I am having the same problem - unable to link assemblies. Any news on when this fix will be deployed so I can try to see what assemblies are causing me trouble?

**Comment by spouliot** [comment] 2018-01-24 04:21
The mono bump part of https://github.com/xamarin/xamarin-macios/pull/3282 fixed this issue. It will be part of our preview 4 (for 15.6).

**Closed by spouliot** 2018-01-24 04:21 UTC
Labels: iOS, need-info

**Comment by ChetanLimitless** [comment] 2018-01-24 12:05
The same issue am facing,I am using "realm" I have separately created .net standard library for realm where an initialising the object for realm.Now a adding this lib. to my iOS project and add the reference of the lib.After importing that lib whenever  I create object of that lib ever I get the compile time error.
 May I know any easy and clean way to remove this error.

**Comment by wiltwitt** [comment] 2018-02-05 14:49
I have same issue.  I am using PCL.  It works fine on iPhone emulator on Mac but not on physical device.

**Comment by Nixon-Joseph** [comment] 2018-02-08 20:19
I see that this issue has been resolved, how do I get the version where it is fixed?/How long until a stable version with the fix comes out? On a deadline with the app, and need to make sure I can build and deploy ios.

Thanks!
