### ISSUE TITLE
Failed to load AOT module

### ISSUE THREAD

**Issue by sledderGIT** [xamarin/xamarin-macios#18995] opened 2023-09-11 15:13 UTC
Debugging the .NET 6 iOS app on my iPhone 12 getting Failed to load AOT module 'IdentityModel.OidcClient' (or sometimes with another random library in the project) while running in aot-only mode because a dependency cannot be found or it is out of date.` It appears absolutely randomly. May disappear after couple of rebuilds. Sometimes it happens in the main application. But more often it happens in my notification content extension.

### Steps to Reproduce

1.  Build an iOS app with notification content extension
2. Launch it on iPhone
3.  Failed to load AOT module 'IdentityModel.OidcClient' while running in aot-only mode because a dependency cannot be found or it is out of date.

### Expected Behavior

Should work

### Actual Behavior

Crashes with  Failed to load AOT module 'Acr.UserDialogs' while running in aot-only mode because a dependency cannot be found or it is out of date.

### Environment

Visual Studio Community 2022 for Mac
Version 17.6.3 (build 421)
Installation UUID: 0a97187a-cef5-499f-a10e-c53d754a8b90

Runtime
.NET 7.0.3 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.307/Sdks
SDK Versions:
	7.0.307
	7.0.306
	7.0.304
	7.0.302
	7.0.203
	7.0.202
	7.0.200
	7.0.102
	7.0.101
	7.0.100-rc.1.22431.12
	6.0.413
	6.0.412
	6.0.410
	6.0.408
	6.0.407
	6.0.406
	6.0.405
	6.0.404
	6.0.402
	6.0.401
	6.0.400
	6.0.400-preview.22330.6
	6.0.302
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	3.1.426
	3.1.424
	3.1.423
	3.1.422
	3.1.421

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.10
	7.0.9
	7.0.8
	7.0.7
	7.0.5
	7.0.4
	7.0.3
	7.0.2
	7.0.1
	7.0.0-rc.1.22426.10
	6.0.21
	6.0.20
	6.0.18
	6.0.16
	6.0.15
	6.0.14
	6.0.13
	6.0.12
	6.0.10
	6.0.9
	6.0.8
	6.0.7
	6.0.6

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	3.1.32
	3.1.30
	3.1.29
	3.1.28
	3.1.27

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.2.1.2 (Visual Studio Community)
Commit: xamarin-android/d17-5/a8a26c7
Android SDK: /Users/alexeyshavrukov/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0  (API level 23)
		12.0 (API level 31)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 34.0.1
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: d9a6e87
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2023-08-02 19:06:47 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2023-08-02 19:06:47 UTC

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2023-08-02 19:06:42 UTC

Apple Developer Tools
Xcode: 14.3.1 21815
Build: 14E300c

Xamarin.Mac
Version: 9.3.0.6 Visual Studio Community
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:35-0400

Xamarin.iOS
Version: 16.4.0.6 Visual Studio Community
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:36-0400

Build Information
Release ID: 1706030421
Git revision: c90350679f1b9295edc584519320b13d06489853
Build date: 2023-08-02 19:05:00+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 13.1.0
Darwin 22.2.0 Darwin Kernel Version 22.2.0
    Fri Nov 11 02:03:51 PST 2022
    root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64

Enabled user installed extensions
Project System Tools 0.13

**Comment by rolfbjarne** [comment] 2023-09-11 15:32
I believe you're running into #17708, which will be fixed in .NET 8, and hopefully also in .NET 7 in a few weeks.

In the meantime, the workaround is to clean your project and then try again.

Closing as a duplicate of #17708.

**Closed by rolfbjarne** 2023-09-11 15:32 UTC
