### ISSUE TITLE
Do we have a plan for Swift library and xcframework binding?

### ISSUE THREAD

**Issue by tuyen-vuduc** [xamarin/xamarin-macios#15306] opened 2022-06-21 01:02 UTC
1) XCFramework
Apple shifted to use **XCFramework** for iOS/MacOS projects' dependencies. Right now, Xamarin.iOS doesn't support it natively yet. We could work around by adding XCFramework directly to the main app project, but it doesn't sound neutral.
 
 An approach: Create a binding target might work somehow.

2) Swift library
A lot of Swift libraries even major ones like Stripe, MapBox aren't fully ObjectiveC compatible any more. It'll be really a bearer to keep Xamariners to stay and/or to get new people to join in.

### Steps to Reproduce

1. Create a binding library for a Swift library e.g. MapBox SDK for iOS
2. Check out the output

### Expected Behavior
- C# APIs must be generated Swift APIs
- XCframework could be embedded inside binding DLL

### Actual Behavior
- No C# APIs generated for Swift APIs
- XCframework couldn't be embedded inside binding DLL

### Environment
<details>
<summary>Visual Studio Community 2022 for Mac Preview
Version 17.3 Preview (17.3 build 1028)</summary>

```
Visual Studio Community 2022 for Mac Preview
Version 17.3 Preview (17.3 build 1028)
Installation UUID: 44f53ab2-fc44-4b03-ac7c-0fda76fd8c07

Runtime
.NET 6.0.4 (64-bit)
Architecture: X64

Roslyn (Language Service)
4.3.0-2.22307.14+b91fc5b06135deb5bd72c105a1b96ce278ad6beb

NuGet
Version: 6.0.0.262

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.301/Sdks
SDK Versions:
	6.0.301
	6.0.300
	3.1.420
	3.1.419
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.6
	6.0.4
	3.1.26
	3.1.25

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 12.3.99.95 (Visual Studio Community)
Commit: xamarin-android/main/5432886
Android SDK: /Users/tuyen/Library/Android/sdk
	Supported Android versions:
		12.1 (API level 32)
		12.0 (API level 31)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)

SDK Command-line Tools Version: 5.0
SDK Platform Tools Version: 33.0.1
SDK Build Tools Version: 33.0.0 rc3

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/main@1f27ab55
SQLite: xamarin/sqlite/3.38.5@df4deab
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@fc3c2ac

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.2.0.47
Hash: d6dd135
Branch: remotes/origin/dev/tondat/main-menues~3
Build date: 2022-06-09 16:25:59 UTC

Android Device Manager
Version: 0.0.0.1127
Hash: 4bb4d48
Branch: remotes/origin/dev/tondat/main-1536295~1
Build date: 2022-06-09 16:25:59 UTC

Apple Developer Tools
Xcode 13.4.1 (20504)
Build 13F100

Xamarin.Mac
Version: 8.10.0.5 (Visual Studio Community)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:06-0400

Xamarin.iOS
Version: 15.10.0.5 (Visual Studio Community)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:07-0400

Xamarin Designer
Version: 17.3.0.110
Hash: 01d90a6c4
Branch: remotes/origin/d17-3
Build date: 2022-06-09 16:25:54 UTC

Build Information
Release ID: 1703001028
Git revision: 5307590023c3e31269ce51cdf27757b8d35833d6
Build date: 2022-06-09 16:23:58+00
Build branch: release-17.3
Build lane: release-17.3

Operating System
Mac OS X 12.4.0
Darwin 21.5.0 Darwin Kernel Version 21.5.0
    Tue Apr 26 21:08:22 PDT 2022
    root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64
```

</details>

### Build Logs
N/A

### Example Project (If Possible)

https://github.com/NAXAM/stripe-ios-binding/tree/v22.5.0
https://github.com/NAXAM/mapbox-ios-binding/tree/v10.5.0

**Comment by dalexsoto** [comment] 2022-06-30 23:20
Hello!

As for point `1.` we do support XCFrameworks in our .NET offerings you can find an example about it here https://github.com/xamarin/xamarin-macios/tree/main/tests/bindings-xcframework-test

For point `2.` we have various options on how to address this
* [Binding Tools for Swift](https://github.com/xamarin/binding-tools-for-swift): Which is the one that aims to do what you describe, point it to a library and give you a C# assembly. This is still work in progress.
* The other option is via a bridging header file and that approach is being described here: https://docs.microsoft.com/en-us/xamarin/ios/platform/binding-swift/walkthrough
* And last but not least it is a new way that we are exploring to support in our .NET 6 offerings and Swift Widgets, the idea is in early stages but can be found here https://github.com/xamarin/xamarin-macios/issues/15315
 
Since both already have their own set of solutions and/or issues I will be closing this one since I think it is a dupe of tea different features. Feel free to reopen/comment if you'd like.

Thanks!

**Closed by dalexsoto** 2022-06-30 23:20 UTC
Labels: support

**Comment by tuyen-vuduc** [comment] 2022-07-02 01:20
@dalexsoto Thanks a lot for the info. I will check them out.
