### ISSUE TITLE
WatchOS apps keep crashing when running on hardware

### ISSUE THREAD

**Issue by adityal** [xamarin/xamarin-macios#8254] opened 2020-04-01 10:40 UTC
### Steps to Reproduce
I have been running on Xamarin.iOS version 13.2 for quite some time and have a pretty basic Apple Watch app which was working very smoothly until I did an update to the latest Xamarin.iOS 13.14 version. Suddenly my watch app, and as a matter of fact all sample watch apps, keep crashing on start. In simulator everything's working as expected. Does anyone else experience something similar?

Incident Identifier: E4013810-5F6E-49DE-951C-BF2797F02103
CrashReporter Key:   a447a51e564cd74bdba62740762212d7fd47e190
Hardware Model:      Watch5,1
Process:             WatchAppWatchOSExtension [343]
Path:                /private/var/containers/Bundle/Application/0255693E-2070-4054-873B-7E4E553DAD6A/WatchApp.WatchOSApp.app/PlugIns/WatchAppWatchOSExtension.appex/WatchAppWatchOSExtension
Identifier:          com.kastle.testlibraryiosapp.watchkitapp.watchkitextension
Version:             1.9 (1.9)
Code Type:           ARM (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.kastle.testlibraryiosapp.watchkitapp.watchkitextension [445]

Date/Time:           2020-03-26 14:27:57.9161 +0530
Launch Time:         2020-03-26 14:27:57.0000 +0530
OS Version:          Watch OS 6.1.3 (17S811)
Release Type:        User
Baseband Version:    n/a
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Application Specific Information:
abort() called

Thread 0 name:  tid_407  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x1e384c70 __pthread_kill + 8
1   libsystem_pthread.dylib       	0x1e401980 pthread_kill + 220
2   libsystem_c.dylib             	0x1e2d86f4 abort + 100
3   WatchAppWatchOSExtension      	0x04c118e4 print_callback(char const*, int) + 6625508 (runtime.m:1218)
4   WatchAppWatchOSExtension      	0x04c00af8 monoeg_g_logv_nofree + 6556408 (goutput.c:150)
5   WatchAppWatchOSExtension      	0x04c00b48 monoeg_g_log + 6556488 (goutput.c:165)
6   WatchAppWatchOSExtension      	0x04bf305c mono_threads_transition_do_blocking + 6500444 (mono-threads-state-machine.c:725)
7   WatchAppWatchOSExtension      	0x04bf0a58 mono_threads_enter_gc_safe_region_unbalanced_with_info + 6490712 (mono-threads-coop.c:324)
8   WatchAppWatchOSExtension      	0x04b5ba84 mono_gc_pthread_create + 5880452 (sgen-mono.c:2432)
9   WatchAppWatchOSExtension      	0x04bf1eb4 mono_thread_platform_create_thread + 6495924 (mono-threads-posix.c:101)
10  WatchAppWatchOSExtension      	0x04b7f2ec create_thread + 6025964 (threads.c:1384)
11  WatchAppWatchOSExtension      	0x04b7ed8c mono_thread_create_internal + 6024588 (threads.c:530)
12  WatchAppWatchOSExtension      	0x04ad54a8 mono_gc_init_finalizer_thread + 5330088 (gc.c:1002)
13  WatchAppWatchOSExtension      	0x04c18924 -[XamarinGCSupport init] + 6654244 (monotouch-main.m:199)
14  WatchAppWatchOSExtension      	0x04c18cfc xamarin_main + 6655228 (monotouch-main.m:462)
15  WatchAppWatchOSExtension      	0x045cd7cc xamarin_watchextension_main + 55244 (main.m:55)
16  libdyld.dylib                 	0x1e204a78 start + 4

Thread 1:
0   libsystem_pthread.dylib       	0x1e408824 start_wqthread + 0

Thread 2 name:  SGen worker
Thread 2:
0   libsystem_kernel.dylib        	0x1e384a40 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x1e404130 _pthread_cond_wait + 668
2   WatchAppWatchOSExtension      	0x04bde09c thread_func + 6414492 (mono-os-mutex.h:178)
3   libsystem_pthread.dylib       	0x1e400930 _pthread_start + 156
4   libsystem_pthread.dylib       	0x1e408838 thread_start + 8

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000014d78790   x5: 0x0000000000000003   x6: 0x0000000000000000   x7: 0x00000000fffffffb
    x8: 0x00000000074dd3c0   x9: 0x00000000a97ffa9c  x10: 0x00000000000de930  x11: 0x0000000000179f41
   x12: 0x0000000000003fff  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x000000001d015c47
   x16: 0x0000000000000148  x17: 0x000000001e6e8ba8  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000000000407  x21: 0x00000000158ed040  x22: 0x0000000004d27000  x23: 0x0000000004d318e8
   x24: 0x0000000014d786d0  x25: 0x000000004c034a38  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x00000000072c6ac0   lr: 0x000000001e401980
    sp: 0x00000000072c6aa0   pc: 0x000000001e384c70 cpsr: 0x40000000
   esr: 0x56000080  Address size fault

### Expected Behavior
The watchOS app should launch successfully.

### Actual Behavior
The WatchOS app crashing on every launch.

### Environment
Visual Studio Community 2019 for Mac
Version 8.5 (build 3183)
Installation UUID: 10146add-b8ff-4640-bd8e-26b6a353e7e5
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.14.1.39 (d16-5 / 30e8706b4)

	Package version: 608000123

Mono Framework MDK
Runtime:
	Mono 6.8.0.123 (2019-10/1d0d939dc30) (64-bit)
	Package version: 608000123

Roslyn (Language Service)
3.5.0-beta4-20125-04+1baa0b3063238ed752ad1f0368b1df6b6901373e

NuGet
Version: 5.4.0.6315

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/3.1.200/Sdks
SDK Versions:
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	3.0.100-preview8-013656
	2.1.701
	2.1.700
	2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	3.0.0-preview8-28405-07
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.2

Xamarin.Profiler
Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 11.3.1 (15715)
Build 11C505

Xamarin.Mac
Version: 6.14.1.39 (Visual Studio Community)
Hash: 30e8706b4
Branch: d16-5
Build date: 2020-02-20 16:41:47-0500

Xamarin.iOS
Version: 13.14.1.39 (Visual Studio Community)
Hash: 30e8706b4
Branch: d16-5
Build date: 2020-02-20 16:41:48-0500

Xamarin Designer
Version: 16.5.0.471
Hash: 35aa4889d
Branch: remotes/origin/d16-5
Build date: 2020-02-25 00:52:08 UTC

Xamarin.Android
Version: 10.2.0.100 (Visual Studio Community)
Commit: xamarin-android/d16-5/988c811
Android SDK: /Users/aditya.aggarwal/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: c0c5c78
Java.Interop: xamarin/java.interop/d16-5@fc18c54
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b

Microsoft Mobile OpenJDK
Java SDK: /Users/aditya.aggarwal/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.5.0.39
Hash: 6fb4c79
Branch: remotes/origin/d16-5
Build date: 2020-02-20 23:25:56 UTC

Android Device Manager
Version: 16.5.0.71
Hash: 49194e8
Branch: remotes/origin/d16-5
Build date: 2020-02-20 23:26:18 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 805003183
Git revision: 60e06e010baa677204535600661dda3fb4677c2f
Build date: 2020-03-20 06:18:03-04
Build branch: release-8.5
Xamarin extensions: 60e06e010baa677204535600661dda3fb4677c2f

Operating System
Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

**Comment by rolfbjarne** [comment] 2020-04-01 11:03
This is a duplicate of #8232.

**Closed by rolfbjarne** 2020-04-01 11:03 UTC
