### ISSUE TITLE
using file from Native-Reference result in error

### ISSUE THREAD

**Issue by hieronymusanthonius** [xamarin/xamarin-macios#10640] opened 2021-02-14 17:35 UTC
### Steps to Reproduce

1.  Build OSPRAY lib
2.  Create MacOS sample project with Xamarin/Visual Studio
3.  Add Native references to the libs

### Expected Behavior
to able to consume the native libraries

### Actual Behavior

error MM0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
### Environment
MacOs Big Sur 11.1, Xamarin,

```
=== Visual Studio Community 2019 for Mac ===

Version 8.8.8 (build 12)
Installation UUID: ace95834-8fa4-4f93-9828-76edf31091ef
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.103/Sdks
SDK Versions:
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.200
	3.1.102
	3.1.100
	3.0.100
	2.1.809
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.503
	2.1.302
MSBuild SDKs: /Applications/Visual Studio (old).app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.0
	3.0.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.7
	2.1.2

=== .NET Core 3.1 SDK ===

SDK: 3.1.406

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Version: 7.4.0.4 (Visual Studio Community)
Hash: 5a05865f6
Branch: xcode12.4
Build date: 2021-01-28 02:30:22-0500

=== Xamarin.iOS ===

Version: 14.10.0.4 (Visual Studio Community)
Hash: 5a05865f6
Branch: xcode12.4
Build date: 2021-01-28 02:30:23-0500

=== Xamarin.Android ===

Version: 11.1.0.26 (Visual Studio Community)
Commit: xamarin-android/d16-8/a36ce73
Android SDK: /Users/jeroenvandenbelt/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/jeroenvandenbelt/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2021-01-14 00:34:58 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2021-01-14 00:35:22 UTC

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Build Information ===

Release ID: 808080012
Git revision: 147eee6fcc43c486d8b79477b6a521322a015604
Build date: 2021-02-04 04:32:34-05
Build branch: release-8.8
Xamarin extensions: 147eee6fcc43c486d8b79477b6a521322a015604

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.2.0 Darwin Kernel Version 20.2.0
    Wed Dec  2 20:39:59 PST 2020
    root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
```

### Example Project (If Possible)

```
Building raytracer (Debug)
Build started 14-2-2021 17:25:42.
__________________________________________________
Project "/Users/jeroenvandenbelt/cj/buildIOSPRAY/raytracer/raytracer.csproj" (Build target(s)):

Target _BeforeCoreCompileImageAssets:
  Skipping target "_BeforeCoreCompileImageAssets" because all output files are up-to-date with respect to the input files.
Target _CoreCompileImageAssets:
  Skipping target "_CoreCompileImageAssets" because all output files are up-to-date with respect to the input files.
Target _CoreCompileInterfaceDefinitions:
      BundleResources Output:
        obj/Debug/ibtool/Main.storyboardc/MainMenu.nib
        obj/Debug/ibtool/Main.storyboardc/XfG-lQ-9wD-view-m2S-Jp-Qdl.nib
        obj/Debug/ibtool/Main.storyboardc/NSWindowController-B8D-0N-5wS.nib
        obj/Debug/ibtool/Main.storyboardc/Info.plist
      OutputManifests Output:
        obj/Debug/ibtool-manifests/Main.storyboardc
Target _CoreCompileColladaAssets:
  Skipping target "_CoreCompileColladaAssets" because it has no inputs.
Target GenerateTargetFrameworkMonikerAttribute:
  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
Target CoreCompile:
    /Applications/Visual Studio (old).app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Roslyn/csc.exe /noconfig /nowarn:1701,1702,2008 /fullpaths /nostdlib+ /errorreport:prompt /warn:4 /define:__UNIFIED__;__MACOS__;DEBUG /errorendlocation /preferreduilang:en-US /reference:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/mscorlib.dll /reference:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/System.Core.dll /reference:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/System.dll /reference:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/Facades/System.Drawing.Common.dll /reference:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/Xamarin.Mac.dll /debug+ /debug:full /nowin32manifest /optimize- /out:obj/Debug/raytracer.exe /target:exe /utf8output /langversion:7.3 Main.cs AppDelegate.cs ViewController.cs ViewController.designer.cs "obj/Debug/Xamarin.Mac,Version=v2.0.AssemblyAttributes.cs"
    Using shared compilation with compiler from directory: /Applications/Visual Studio (old).app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Roslyn
Target CopyFilesToOutputDirectory:
    Copying file from "/Users/jeroenvandenbelt/cj/buildIOSPRAY/raytracer/obj/Debug/raytracer.exe" to "/Users/jeroenvandenbelt/cj/buildIOSPRAY/raytracer/bin/Debug/raytracer.exe".
    raytracer -> /Users/jeroenvandenbelt/cj/buildIOSPRAY/raytracer/bin/Debug/raytracer.exe
    Copying file from "/Users/jeroenvandenbelt/cj/buildIOSPRAY/raytracer/obj/Debug/raytracer.pdb" to "/Users/jeroenvandenbelt/cj/buildIOSPRAY/raytracer/bin/Debug/raytracer.pdb".
Target _DetectSigningIdentity:
    Detected signing identity:
            
      Bundle Id: com.positiongames.raytracer
      App Id: com.positiongames.raytracer
Target _CopyContentToBundle:
  Skipping target "_CopyContentToBundle" because all output files are up-to-date with respect to the input files.
Target _CompileAppManifest:
  Skipping target "_CompileAppManifest" because all output files are up-to-date with respect to the input files.
Target _CompileToNative:
    /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/bin/mmp @/Users/jeroenvandenbelt/cj/buildIOSPRAY/raytracer/obj/Debug/response-file.rsp 
    MMP : warning MM2006: Native library 'librkcommon.1.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libtbb.12.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libtbbmalloc.2.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'librkcommon.1.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libtbb.12.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libtbbmalloc.2.dylib' was referenced but could not be found.
    		
    Dependency libospray.2.5.0.dylib was already at destination, skipping.
    MMP : warning MM2006: Native library 'librkcommon.1.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libtbb.12.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libtbbmalloc.2.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'librkcommon.1.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libtbb.12.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libopenvkl.0.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libtbb.12.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libtbbmalloc.2.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'librkcommon.1.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libopenvkl.0.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libtbb.12.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libtbbmalloc.2.dylib' was referenced but could not be found.
    		
    Dependency libospray_module_ispc.2.5.0.dylib was already at destination, skipping.
    MMP : warning MM2006: Native library 'librkcommon.1.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libopenvkl.0.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libtbb.12.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libtbbmalloc.2.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libopenvkl.0.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'librkcommon.1.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libtbb.12.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libtbbmalloc.2.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libopenvkl.0.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'librkcommon.1.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libtbb.12.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libtbbmalloc.2.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'librkcommon.1.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libtbb.12.dylib' was referenced but could not be found.
    		
    MMP : warning MM2006: Native library 'libtbbmalloc.2.dylib' was referenced but could not be found.
    		
    MMP : error MM0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
    System.IO.IOException: The file '/Users/jeroenvandenbelt/cj/buildIOSPRAY/raytracer/bin/Debug/raytracer.app/Contents/MonoBundle/libembree3.3.dylib' already exists.
      at System.IO.FileSystem.CopyDanglingSymlink (System.String sourceFullPath, System.String destFullPath) [0x0003c] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs:38 
      at System.IO.FileSystem.CopyFile (System.String sourceFullPath, System.String destFullPath, System.Boolean overwrite) [0x0001b] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs:50 
      at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x00056] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/File.cs:74 
      at Xamarin.Bundler.Driver.CopyFileAndRemoveReadOnly (System.String src, System.String dest) [0x00001] in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/mmp/driver.cs:1564 
      at Xamarin.Bundler.Driver.ProcessNativeLibrary (System.Collections.Generic.HashSet`1[T] processed, System.String library, System.Collections.Generic.List`1[T] used_by_methods) [0x00262] in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/mmp/driver.cs:1389 
      at Xamarin.Bundler.Driver.CopyDependencies (System.Collections.Generic.IDictionary`2[TKey,TValue] libraries) [0x00157] in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/mmp/driver.cs:1240 
      at Xamarin.Bundler.Driver.Pack (System.Collections.Generic.IList`1[T] unprocessed) [0x005fc] in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/mmp/driver.cs:597 
      at Xamarin.Bundler.Driver.Main2 (System.String[] args) [0x009a9] in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/mmp/driver.cs:326 
      at Xamarin.Bundler.Driver.Main (System.String[] args) [0x0001b] in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/common/Driver.cs:39 
Done building target "_CompileToNative" in project "raytracer.csproj" -- FAILED.

Done building project "raytracer.csproj" -- FAILED.

Build FAILED.

MMP : warning MM2006: Native library 'librkcommon.1.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libtbb.12.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libtbbmalloc.2.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'librkcommon.1.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libtbb.12.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libtbbmalloc.2.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'librkcommon.1.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libtbb.12.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libtbbmalloc.2.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'librkcommon.1.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libtbb.12.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libopenvkl.0.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libtbb.12.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libtbbmalloc.2.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'librkcommon.1.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libopenvkl.0.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libtbb.12.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libtbbmalloc.2.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'librkcommon.1.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libopenvkl.0.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libtbb.12.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libtbbmalloc.2.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libopenvkl.0.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'librkcommon.1.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libtbb.12.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libtbbmalloc.2.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libopenvkl.0.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'librkcommon.1.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libtbb.12.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libtbbmalloc.2.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'librkcommon.1.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libtbb.12.dylib' was referenced but could not be found.
MMP : warning MM2006: Native library 'libtbbmalloc.2.dylib' was referenced but could not be found.
MMP : error MM0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
    33 Warning(s)
    1 Error(s)

Time Elapsed 00:00:03.07

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Build: 1 error, 33 warnings
```

[raytracer.zip](https://github.com/xamarin/xamarin-macios/files/5978136/raytracer.zip)

**Comment by rolfbjarne** [comment] 2021-02-15 07:39
I can't reproduce this with the test project in question, probably because the test case doesn't have the ospray libraries that you reference:

> <NativeReference Include="..\build\ospray\build\libospray_imgui.2.dylib">

Could you include zip up the entire parent directory and attach it here, so that we're trying the same thing?

**Comment by hieronymusanthonius** [comment] 2021-02-15 11:21
https://www.icloud.com/iclouddrive/0Bs4cEjGLekn9AUYWq2ihYV4g#raytracer

**Comment by rolfbjarne** [comment] 2021-02-15 13:20
It looks like the `./frame/libembree3.3.dylib` file referenced the csproj is a symlink to a file that doesn't exist. Could that be the case?

**Comment by hieronymusanthonius** [comment] 2021-02-15 15:23
Thanks, that was the issue. Now I start to research how to call functions from the  library.

Would this be the right way to do?
  [DllImport("libospray.dylib", EntryPoint = "ospInit",CallingConvention = CallingConvention.Cdecl)]
   public static extern int ospInit(int n, String str);

**Comment by rolfbjarne** [comment] 2021-02-16 07:10
Yes, that looks right (depending on the signature of the `ospInit` function of course, which I don't know).

In any case, I'm closing this issue, since it seems you found the problem.

**Closed by rolfbjarne** 2021-02-16 07:10 UTC
Labels: bug, macOS, need-info
