### ISSUE TITLE
VSfM on Apple Silicon always builds and runs app for osx-x64 instead of osx-arm64

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#16629] opened 2022-11-07 22:22 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VSfM-on-Apple-Silicon-always-builds-and-/10177232)._

---
I’ve got an M1 Macbook and am using dotnet 6 for M1, as well as Visual Studio for Mac Preview 17.4 built for Apple Silicon. When building and running from the dotnet CLI, it correctly selects osx-arm64 for the RuntimeIdentifer by default. VSfM always builds and runs osx-x64 instead.

---
#### Feedback Bot on 10/19/2022, 07:23 PM: 

(private comment, text removed)
#### Theresa Zhang[MSFT] on 10/20/2022, 04:31 AM: 

(private comment, text removed)
#### John Wostenberg on 10/20/2022, 05:57 PM: 

(private comment, text removed)
#### Theresa Zhang[MSFT] on 10/21/2022, 03:22 AM: 

(private comment, text removed)
#### Feedback Bot on 10/21/2022, 03:22 AM: 

(private comment, text removed)
#### John Wostenberg on 10/21/2022, 08:37 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by dalexsoto** [comment] 2022-11-08 00:24
This is a dupe of https://github.com/xamarin/xamarin-macios/issues/15620

**Closed by dalexsoto** 2022-11-08 00:24 UTC
Labels: support
