### ISSUE TITLE
MvxTabBarViewController calls ViewDidDisappear method after ViewWillAppear in Xamarin.iOS 15.0.0.3

### ISSUE THREAD

**Issue by Nishimia** [xamarin/xamarin-macios#12827] opened 2021-09-24 10:36 UTC
### Steps to Reproduce

1. Install app on device with iOS 15.
2. Start app. 

### Expected Behavior
After app start, MvxTabBarViewController calls ViewDidAppear method after ViewWillAppear.

### Actual Behavior
After app start, MvxTabBarViewController calls ViewDidDisappear method after ViewWillAppear.

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.9 (build 3)
Installation UUID: 1bb81de2-3b28-4e18-b0c8-cd7579139901
 GTK+ 2.24.23 (Raleigh theme)
 Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

 Package version: 612000140

=== Mono Framework MDK ===

Runtime:
 Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
 Package version: 612000140

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.401/Sdks
SDK Versions:
 5.0.401
 5.0.400
 5.0.301
 5.0.203
 5.0.202
 5.0.201
 5.0.103
 5.0.102
 3.1.413
 3.1.412
 3.1.410
 3.1.409
 3.1.408
 3.1.407
 3.1.406
 3.1.405
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
 5.0.10
 5.0.9
 5.0.7
 5.0.6
 5.0.5
 5.0.4
 5.0.3
 5.0.2
 3.1.19
 3.1.18
 3.1.16
 3.1.15
 3.1.14
 3.1.13
 3.1.12
 3.1.11

=== .NET Core 3.1 SDK ===

SDK: 3.1.413

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.3.0.4 (Visual Studio Community)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/Oleksandr_Davydov/Library/Developer/Xamarin/android-sdk-macosx
 Supported Android versions:
  8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/Oleksandr_Davydov/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-08-12 20:43:52 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-08-12 20:44:10 UTC

=== Apple Developer Tools ===

Xcode 13.0 (19234)
Build 13A233

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 15.0.0.3 (Visual Studio Community)
Hash: 011ef4317
Branch: xcode13-ios
Build date: 2021-09-22 08:31:50-0400

=== Build Information ===

Release ID: 810090003
Git revision: 156eb53c9c668cb7ff4311ae3d1dab894549848b
Build date: 2021-09-08 07:26:54-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Wed Jun 23 00:26:31 PDT 2021
    root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

NuGet Package Management Extensions 0.27
VsVim 2.8.0.13
```

**Comment by chamons** [comment] 2021-09-27 16:50
Thank you for your feedback!

For us to investigate this further, could you please provide a test case (to reproduce).

We look forward to hearing from you!

**Comment by rachelkang** [comment] 2021-12-20 18:20
We will be closing this issue as it has been over 30 days since we have not received the requested information. If you are still experiencing this issue, please provide all the requested information and then click the Reopen Issue button. Thank you!

**Closed by rachelkang** 2021-12-20 18:20 UTC
Labels: need-info
