### ISSUE TITLE
.NET 6 - macOS app crashes when requesting access to photo library, but is successful with dotnet run

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#16527] opened 2022-10-31 21:09 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-6---macOS-app-crashes-when-requesti/1599551)._

---
When running a new macos app in .NET 6 using `dotnet new macos` the app can successfully run and request permissions to a user’s photolibrary using dotnet run, but crashes when running from Visual Studio and the debugger.<br><br>The attached sample project has code added to the AppDelegate.cs file to request access to a user’s photo library in the DidFinishingLaunching method. Additionally, a NSPhotoLibraryUsageDescription was added to the Info.plist.<br><br>When using dotnet run, the app runs as expected. When using Start Debugging from Visual Studio, the app crashes when the code is executed. After crashing, if the user selects report to apple, a dialog is shown that states, “This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an com.apple.security.personal-information.photos-library key with a string value explaining to the user how the app uses this data.”<br><br>The app is not signed and is running in debug mode in both instances.<br><br>The attached sample app is called “TestPhotosApp.”

---
#### Feedback Bot on 11/30/2021, 10:50 PM: 

(private comment, text removed)
#### YanFang Wang (CSI Interfusion Inc) [MSFT] on 12/2/2021, 03:29 AM: 

(private comment, text removed)
#### John Taubensee on 12/2/2021, 08:09 AM: 

(private comment, text removed)
#### Feedback Bot on 12/6/2021, 04:02 AM: 

(private comment, text removed)
#### Feedback Bot on 6/28/2022, 11:49 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by rolfbjarne** [comment] 2022-11-02 07:48
A wild guess here is that this happens because macOS considers VSMac as the responsible process, and will look for the corresponding privacy keys there (and fail to find them).

See https://gitlab.com/gnachman/iterm2/-/issues/10360 for a more detailed description about "responsible process".

**Comment by tipa** [comment] 2023-01-13 09:41
I think this is a duplicate of this issue: https://github.com/xamarin/xamarin-macios/issues/15614, which was unfortunately closed without a fix. This is still a problem after half a year and is massively slowing down productivity.

**Comment by rolfbjarne** [comment] 2023-01-13 21:35
@tipa I'll try to have a look next week.

Note to self: embedding the Info.plist into the executable like this might work: https://github.com/xamarin/xamarin-macios/issues/13795#issuecomment-1021358936

**Comment by rolfbjarne** [comment] 2023-01-16 09:57
> A wild guess here is that this happens because macOS considers VSMac as the responsible process, and will look for the corresponding privacy keys there (and fail to find them).

This seems to be correct, note the `Responsible:` part of the crash report:

```
Process:               macos7 [74702]
Path:                  /Users/USER/*/macos7.app/Contents/MacOS/macos7
Identifier:            com.companyname.macos7
Version:               1.0 (1)
Code Type:             X86-64 (Native)
Parent Process:        vsdbg-ui [74701]
Responsible:           VisualStudio [73283]
User ID:               501
```

> Note to self: embedding the Info.plist into the executable like this might work: [#13795 (comment)](https://github.com/xamarin/xamarin-macios/issues/13795#issuecomment-1021358936)

It didn't :(

**Comment by rolfbjarne** [comment] 2023-01-17 09:36
@tipa I've opened a bug in dotnet/runtime, since it seems this has to be fixed in the `vsdbg-ui` executable: https://github.com/dotnet/runtime/issues/80727.

**Closed by rolfbjarne** 2023-01-17 09:36 UTC
