### ISSUE TITLE
Document how to add native Watch app

### ISSUE THREAD

**Issue by ivanicin** [xamarin/xamarin-macios#16417] opened 2022-10-24 15:02 UTC
It seems to be possible to add the native Watch app to the Xamarin app but with 0 documentation. According to https://github.com/xamarin/xamarin-macios/issues/16142 this is done using `_ResolvedWatchAppReferences`

Searching for this on the internet returned just that page, so it is not reasonable to think that anyone can do it.

On the other hand as noted here: https://github.com/xamarin/xamarin-macios/issues/16120 , watchOS is not technically supported anymore since one month ago and I think it is reasonable not to ask for that fix from Microsoft as they don't have enough funds to support enough engineers to fix something like that (and you know that this is the fact).

Considering all of this it would be nice if you made some sample on how to do this. I have no expectations and I have Plan B, just it is really yours if you want developers to use Xamarin at all or not...

**Comment by dalexsoto** [comment] 2022-10-24 15:29
Hello!

Agreed, we need to document this better there are some good hints here https://github.com/xamarin/xamarin-macios/issues/10070#issuecomment-950683534 we'll have a look at this in the future

**Comment by beeradmoore** [comment] 2022-10-29 23:40
Hey @ivanicin , this is something I have wanted to do and have some samples but nothing concrete. I have a repo with some notes and working samples [here](https://github.com/beeradmoore/MAUI-Watch-n-Wear). I have wanted to improve this to make the process more clear, but both time and energy have not allowed that to happen.

**Comment by ivanicin** [comment] 2022-12-05 18:57
@dalexsoto you may want to refer to the document by @vouksh https://codebloq.io/2022/12/02/xamarin-ios-with-swiftui-watchos-app/ if you are not to write your own document, it may not be at the level of your documentation (and is not intended to be) but it is very usable.

**Comment by EmilAlipiev** [comment] 2023-07-04 20:00
So using SwiftUi is the only way to build WatchOS apps today? can we not create using Xamarin WatchOS like Objective-C style with Storyboards? I have tried default template but I am unable to deploy on WatchOS simulator through Ios App. Is it now completely broken?  I have created a [SO issue  ](https://stackoverflow.com/questions/76607443/how-to-debug-watchos-app-with-companion-ios-app-using-vs-mac-or-rider)

**Comment by vouksh** [comment] 2023-07-05 02:04
@EmilAlipiev Unfortunately, Microsoft has dropped support for watchOS. There's not enough of us to warrant the amount of work they'd need to keep up with the latest changes. If you're starting a new project, your best bet is to go with MAUI + Native (SwiftUI/Kotlin) Watch apps if you still want to stay in .NET. Otherwise your best bet is to go with a full native app. I'm working on making a demo Maui (Phone) + SwiftUI (Watch) app so that I can write up instructions on pairing those up.

**Comment by EmilAlipiev** [comment] 2023-07-05 21:32
@vouksh thanks for your comment. It is clear for me that Maui is not supporting. I have xamarin app and i want to add watchos extension. I could achieve to use watchos with c# today. project is running on my simulator and watch. From my understanding still until May 2024, Xamarin will get updates. Will that actually makes sense to use it still if i want to get  a quick watchos version and in 2024 convert into SwiftUi.  Or is there anyone obstacles deploying a Xamarin.Ios.WatchOs with the latest Xcode?

**Comment by beeradmoore** [comment] 2023-07-05 22:58
Xamarin will no longer get any Xcode major updates. So the current Xcode in beta will never be supported by Xamarin.

The team have said the number of people using watchOS was very low, so not adding support was acceptable to focus on other things. tvOS may also have a very small user base but it also is very similar to iOS SDKs so there was not much effort required to add it, which can not be said for watchOS.

IMO I wouldn't hold my breath for watchOS support so I think the best way to build watchOS apps today is to build it natively and embed it into your MAUI iOS bundle.

**Comment by EmilAlipiev** [comment] 2023-07-05 23:03
oh ok. "Xamarin will no longer get any Xcode major updates." i thought that they would still update us till next year May. thats of course game changer. too bad.

**Comment by beeradmoore** [comment] 2023-07-05 23:11
See [here](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) for more info, but the main bit is 

> Xamarin support will end on May 1, 2024 for all Xamarin SDKs. Android 13 and Xcode 14 SDKs (iOS and iPadOS 16, macOS 13) will be the final versions Xamarin will target.

Xamarin will still be getting updates/bug fixes for its current things, but it won't ever target Android 14 or use Xcode 15 (iOS 17) SDKs.

**Comment by jerry2007** [comment] 2023-09-11 19:11
> @EmilAlipiev Unfortunately, Microsoft has dropped support for watchOS. There's not enough of us to warrant the amount of work they'd need to keep up with the latest changes. If you're starting a new project, your best bet is to go with MAUI + Native (SwiftUI/Kotlin) Watch apps if you still want to stay in .NET. Otherwise your best bet is to go with a full native app. I'm working on making a demo Maui (Phone) + SwiftUI (Watch) app so that I can write up instructions on pairing those up.

Can you publish working sample pls?

**Comment by vouksh** [comment] 2023-09-11 20:11
I've thrown together a quick example from one of my test projects. [https://github.com/vouksh/MauiWithWatchApps](MauiWithWatchApps)
The Android watch app does not work yet, but this should provide a starting point for someone interested in this until I get through my current backlog enough to tackle any more examples.

**Comment by rolfbjarne** [comment] 2024-09-26 15:57
Closing as a duplicate of #20317.

**Closed by rolfbjarne** 2024-09-26 15:57 UTC
Labels: documentation, watchOS
