### ISSUE TITLE
Unable to build Xamarin iOS project with vs2022 Preview

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#17036] opened 2022-12-13 23:29 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-build-Xamarin-iOS-project-with/10224055)._

---
I can build and debug with vs2022 release but when I try to build the same project under Version 17.5.0 Preview 1.0 I'm getting the following error:

System.IO.DirectoryNotFoundException: Could not find a part of the path "/Users/andrewcope/Library/Caches/Xamarin/mtbs/builds/Lexacom.Alexandria.Client.iOS/a864e9d03004907efee24591b642503c94ca662ba1b08236fe434cba3ffbffab/obj/iPhone/Debug/device-builds/iphone10.4-16.1.1/actool/bundle/AppIcons60x60@2x.png".
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, 
....

This path is incorrect. It should be:
/Users/andrewcope/Library/Caches/Xamarin/mtbs/builds/Lexacom.Alexandria.Client.iOS/a864e9d03004907efee24591b642503c94ca662ba1b08236fe434cba3ffbffab/**obj/Debug/actool**/bundle/AppIcons60x60@2x.png

---
#### Feedback Bot on 12/7/2022, 06:20 PM: 

(private comment, text removed)
#### Roi Chen -MSFT [MSFT] on 12/7/2022, 07:43 PM: 

(private comment, text removed)
#### Andrew Cope on 12/8/2022, 00:53 AM: 

(private comment, text removed)
#### Andrew Cope on 12/8/2022, 03:47 AM: 

(private comment, text removed)
#### Roi Chen -MSFT [MSFT] on 12/8/2022, 02:28 AM: 

(private comment, text removed)
#### Roi Chen -MSFT [MSFT] on 12/13/2022, 01:47 AM: 

(private comment, text removed)

---
#### Roi Chen -MSFT [MSFT] solved on 12/9/2022, 01:07 AM, 0 votes: 

<p>Glad to see that you are no longer blocked now. If you have other questions, please feel free to contact us. Thanks for your contribution to the vs community!</p>

#### Andrew Cope on 12/9/2022, 06:45 AM: 

(private comment, text removed)

**Comment by AndrueCope** [comment] 2022-12-14 14:19
I have some more information. It turns out that if/when this error appears you just have to rebuild (or attempt to run again) and eventually after a couple of attempts the error will 'go away' for while.

**Comment by rolfbjarne** [comment] 2022-12-14 21:12
This is a duplicate of https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1684986 (which is private, I'm working on getting a public link available).

**Closed by rolfbjarne** 2022-12-14 21:12 UTC

**Comment by AndrueCope** [comment] 2023-01-13 08:54
It is a nuisance but I find that for the directory not found error immediately rebuilding again usually works. But there are several other ways that Xamarin iOS builds can spuriously fail. If an immediate rebuild doesn't work try:
* Cleaning the solution.
* Rebuilding rather than just building.
* Unpair/pairing your mac.
* Restarting VS.
For what it's worth apart from pairing to my mac the above are standard fair for those of us on our team that use the Preview these days with any solution. VS has just become an unstable and unreliable build platform for all of us and given the lacklustre responses from MS I just have to hope these issues don't eventually make it into release version.

**Comment by Stensan** [comment] 2023-01-13 09:16
@AndrueCope Thanks for the tips, but this is (sadly) already standard procedure for me while using Xamarin.iOS. I am not using the Preview, I am using the release version 17.4.4. I will install the preview and see if this changes anything.

**Comment by rolfbjarne** [comment] 2023-01-13 12:15
@Stensan a different team is handling this, so I don't have much visibility into what's happening. The right place to ask them is on the original developer community issue (which was reopened): https://developercommunity.visualstudio.com/t/Unable-to-build-Xamarin-iOS-project-with/10224055
