### ISSUE TITLE
NoiOS and NoMac results in NoMacCatalyst

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#12824] opened 2021-09-23 21:24 UTC
In some bindings we have notices that the following:

```csharp
[NoMac, NoiOS, NoTv]
public enum Foo {}
```

results i not including the enum in MacCatalyst, that is, it assumes that if it is not in any of the two platforms, it is not in MacCatalyst, instead of adding it to the min of MacCatalyst. This is quite error prone because the same code will include it in WatchOS min version.

**Comment by rolfbjarne** [comment] 2021-09-24 06:30
IIRC the default is to use the iOS availability if there's no specific Mac Catalyst availability. That was the easiest way to jump-start Mac Catalyst without having to add `[MacCatalyst]` attributes everywhere.

**Comment by mandel-macaque** [comment] 2021-09-27 11:07
@rolfbjarne I wonder if we can do a warning of some type.. I know the issue, other might be caught of guard.

**Comment by filipnavara** [comment] 2021-09-27 19:32
> I know the issue, other might be caught of guard.

For the record, that's how the native Objective C availability attributes work. The `SupportedOSPlatform` / `UnsupportedOSPlatform` attributes in .NET 6 also follow the convention that iOS un/availability implies MacCatalyst un/availability unless explicitly specified.

**Comment by rolfbjarne** [comment] 2022-10-10 15:50
Closing, since this is the expected behavior.

**Closed by rolfbjarne** 2022-10-10 15:50 UTC
Labels: bug
