### ISSUE TITLE
[Bug] AddressBook.ABAddressBook.RequestAccess raises System.ObjectDisposedException

### ISSUE THREAD

**Issue by nbsoftware** [xamarin/xamarin-macios#9580] opened 2020-09-03 10:18 UTC
Please see https://github.com/xamarin/Essentials/issues/1373 originally posted on Xamarin Essentials's github

**Comment by whitneyschmidt** [comment] 2020-09-03 17:19
Posting the original issue info here for easier reference:

Permissions.RequestAsync<Permissions.ContactsRead> was working just fine until iOS 13.6

I have upgraded XCode to 11.7, built my app against latest 13.7 SDK and I got the exception System.ObjectDisposedException below, either on the Simulator or a physical device upgraded to 13.7

Tested again on an iOS 13.6 Simulator, works just fine as expected.

System.ObjectDisposedException: Cannot access a disposed object.
  at AddressBook.ABAddressBook.AssertValid () [0x00012] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.22.1.8/src/Xamarin.iOS/AddressBook/ABAddressBook.cs:171 
  at AddressBook.ABAddressBook.get_Handle () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.22.1.8/src/Xamarin.iOS/AddressBook/ABAddressBook.cs:176 
  at AddressBook.ABAddressBook.RequestAccess (System.Action`2[T1,T2] onCompleted) [0x00027] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.22.1.8/src/Xamarin.iOS/AddressBook/ABAddressBook.cs:204 
  at Xamarin.Essentials.Permissions+ContactsRead.RequestAddressBookPermission () [0x00016] in d:\a\1\s\Xamarin.Essentials\Permissions\Permissions.ios.cs:112 
  at Xamarin.Essentials.Permissions+ContactsRead.RequestAsync () [0x0001d] in d:\a\1\s\Xamarin.Essentials\Permissions\Permissions.ios.cs:91 
  at Xamarin.Essentials.Permissions.RequestAsync[TPermission] () [0x00000] in d:\a\1\s\Xamarin.Essentials\Permissions\Permissions.shared.cs:13 
  at fipacapp.Misc.PermissionsHelpers+<>c.<CheckAddressBookPermissions>b__1_0 () [0x0000f] 
...
Not too sure if this is a Xamarin.Essentials bug or a Xamarin.iOS one... so I'll post it to Xamarin.iOS too

Basic Information

Visual Studio Community 2019 for Mac (Preview)
Version 8.8 Preview (8.8 build 1532)
Installation UUID: be4088b1-069a-44b1-bca1-a8bc61ab68dc
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000090

Mono Framework MDK
Runtime:
	Mono 6.12.0.90 (2020-02/d3daacdaa80) (64-bit)
	Package version: 612000090

...

Apple Developer Tools
Xcode 11.7 (16142)
Build 11E801a

Xamarin.Mac
Version: 6.22.1.8 (Visual Studio Community)
Hash: 6f5adef8e
Branch: d16-8
Build date: 2020-07-29 02:26:57-0400

Xamarin.iOS
Version: 13.22.1.8 (Visual Studio Community)
Hash: 6f5adef8e
Branch: d16-8
Build date: 2020-07-29 02:26:58-0400

Xamarin.Android
Version: 11.0.99.34 (Visual Studio Community)
Commit: xamarin-android/d16-8/49ba90e
Android SDK: /Users/fmeyer/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

**Comment by whitneyschmidt** [comment] 2020-09-03 17:27
@nbsoftware Thank you for your feedback!

This could be one of several things:

- A bug in the Xamarin specific binding or runtime code
- A bug in Apple's implementation itself
- A subtle mis-use of the API in question, which is triggering undefined behavior in Apple's implementation. 

If your project was unchanged between iOS 13.6 and iOS 13.7 and the failure occurred after the upgrade (which seems like the case), then this is probably not due to an API misuse.

If you could share a small sample project that reproduces the issue we might get more information to go on :)

**Comment by nbsoftware** [comment] 2020-09-04 16:55
About the use of a simple sample... ;)

Ok so my initial thoughts were wrong, it is not an issue with the version of iOS.

I can trigger the exception on both iOS 13.7 & 13.6.

The issue arise when I either :
- deny the permissions request the first time and then ask again
- allow the permissions request the first time, go to the app settings and deny the contacts use manually, then go back to the app and ask again

A simple workaround would be to issue the Permissions.RequestAsync within a try / catch block.
But I guess it shouldn't raise that System.ObjectDisposedException, rather return Permissions.Denied so that we know we should ask the user to set the appropriate permissions manually, right?

Sample attached.
[github9580.zip](https://github.com/xamarin/xamarin-macios/files/5176054/github9580.zip)

**Comment by rolfbjarne** [comment] 2020-09-07 16:17
This is a bug in Xamarin.Essentials.

The problem is on this line:

https://github.com/xamarin/Essentials/blob/696928bb76f3debfe2ce75361462646addb81f87/Xamarin.Essentials/Permissions/Permissions.ios.cs#L108

creating an ABAddressBook fails if the user has denied access to the address book. Any subsequent attempt will fail (as far as I can see there's no way to ask again).

Xamarin.Essentials should detect this scenario (possibly by using the static ABAddressBook.Create method, which will return null on failure and an NSError object explaining the problem), and not ask for permission again.

I'm closing this bug since there's already a bug open in Xamarin.Essentials for this.

**Closed by rolfbjarne** 2020-09-07 16:17 UTC
Labels: need-info
