### ISSUE TITLE
Failed to AOT compile Microsoft.Graph.dll, Regression

### ISSUE THREAD

**Issue by jbe2277** [xamarin/xamarin-macios#21013] opened 2024-08-11 11:27 UTC
### Steps to Reproduce

1. Clone https://github.com/jbe2277/waf
2. Open NewsReader.sln
3. Build iOS version in Release Mode

### Expected Behavior

Build should succeed. The GitHub project has an action that builds the iOS version. This takes about 3 minutes. 

Successful build:
- https://github.com/jbe2277/waf/actions/runs/9921990632/job/27410570737
- MAUI workload: 8.0.61

### Actual Behavior

GitHub runner goes for about 3 hours to build the iOS version. Result:

- https://github.com/jbe2277/waf/actions/runs/10333051344/job/28604991509
- MAUI workload: 8.0.71

```
/Users/runner/.dotnet/packs/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8018/targets/Xamarin.Shared.Sdk.targets(1270,3): 
error : Failed to AOT compile Microsoft.Graph.dll, the AOT compiler exited with code 1. 
[/Users/runner/work/waf/waf/src/NewsReader/NewsReader.MauiSystem/NewsReader.MauiSystem.csproj::TargetFramework=net8.0-ios]
```

### Changes from the successful build to the actual one
- Update MAUI workload with latest version (the build always gets the latest one)
- Requires to update Xcode from 15.2 to 15.4
- For that I had to switch the GitHub runner from macos-13 to macos-14

### Related issues
- https://github.com/xamarin/xamarin-macios/issues/18388
- https://github.com/dotnet/runtime/issues/87061

**Comment by rolfbjarne** [comment] 2024-08-13 11:48
I can reproduce the slowness, but not the crash. The crash might be due to excessive memory consumption though, in which case that might not happen on my machine.

However, there's a major difference between the two builds: the working build builds using the RuntimeIdentifier `iossimulator-x64`, while the failing one builds using the RuntimeIdentifier `iossimulator-arm64`. This is probably due to changing the GitHub runner (the default RuntimeIdentifier depends on the architecture of the Mac: on arm64 macs we build for `iossimulator-arm64` by default, otherwise `iossimulator-x64`).

There are a couple of things coming together here:

* When building for arm64, we need to AOT assemblies (we can't JIT due to hardware constraints).
* `Microsoft.Graph.dll` is a rather big assembly, so the AOT compiler has to do a lot of work. This is why the build takes so long. 

There are a couple of potential fixes:

* Enable the interpreter (MAUI only enables it by default for Debug builds), by adding this to your csproj:

```xml
<PropertyGroup>
    <UseInterpreter>true</UseInterpreter>
</PropertyGroup>
```

* Enable the trimmer (it's disabled by default for simulator builds), by adding this to your csproj:

```xml
<PropertyGroup>
    <MtouchLink>SdkOnly</MtouchLink>
</PropertyGroup>
```

Can you try either of these and see if it works?

**Comment by jbe2277** [comment] 2024-08-13 17:04
I have enabled the trimmer - this solved the issue.
- https://github.com/jbe2277/waf/commit/d8295fb855c24af0b94561b5f33fabb587b931e5

**Comment by rolfbjarne** [comment] 2024-08-13 17:22
> I have enabled the trimmer - this solved the issue.
> 
> * [jbe2277/waf@d8295fb](https://github.com/jbe2277/waf/commit/d8295fb855c24af0b94561b5f33fabb587b931e5)

Great, I'll close this then. Thanks for confirming!

**Closed by rolfbjarne** 2024-08-13 17:22 UTC
Labels: need-attention
