### ISSUE TITLE
Cannot build iOS apps with extensions (ditto exited with code 1 at _CopyAppExtensionsToBundle).

### ISSUE THREAD

**Issue by RobTF** [xamarin/xamarin-macios#17878] opened 2023-03-22 10:20 UTC
### Steps to Reproduce

1. Build an iOS app with a widget extension.
2. Observe build fails `ditto exited with code 1` at `_CopyAppExtensionsToBundle` task.

### Expected Behavior
Project builds.

### Actual Behavior
Project does not build - fails `ditto exited with code 1` at `_CopyAppExtensionsToBundle` task.

### Environment
```
Microsoft Visual Studio Professional 2022
Version 17.5.3
VisualStudio.17.Release/17.5.3+33516.290
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Professional

Visual C++ 2022   00476-80000-00000-AA390
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.5.318.41597
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.5.318.41597
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.5.318.41597
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.5.0-6.23128.14+651d32d8017cfcc60fcbd67383601fa9a3deb145
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.4.3 (main@2a4517a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.5.9 (11975e6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.5.2.2316603+9f1b6856460af1e592d387ebef416eadddac453f
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.2.40119.0
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.20105.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.5.0-6.23128.14+651d32d8017cfcc60fcbd67383601fa9a3deb145
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.5.0-beta.23053.5+794b7c259d9646a7eb685dad865aa27da7940a21
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

WiX Toolset Visual Studio Extension   1.0.0.22
WiX Toolset Visual Studio Extension version 1.0.0.22
Copyright (c) .NET Foundation and contributors. All rights reserved.

Xamarin   17.5.0.173 (d17-5@33e727c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.5.3.46 (remotes/origin/d17-5@e4dd80b2bb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.5.41 (ba80d05)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.0.0 (d17-5/797e2e1)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 6dd9def
    Java.Interop: xamarin/java.interop/main@149d70fe
    SQLite: xamarin/sqlite/3.40.0@fdc1e34
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@9f02d77


Xamarin.iOS and Xamarin.Mac SDK   16.2.0.5 (7738c90c9)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Build Logs

[MSBuild_Logs.zip](https://github.com/xamarin/xamarin-macios/files/11038881/MSBuild_Logs.zip)

### Example Project (If Possible)
Please contact if required (Unfortunately I do not have time to build test projects by default but can do a screen share with a known problem project or supply our LoB project in its entirety if required). I'll try and find time and will update if I manage to put something else together.

**Comment by rolfbjarne** [comment] 2023-03-22 10:33
Can you try building your solution directly on the Mac to see if that works?

**Comment by RobTF** [comment] 2023-03-22 10:41
I've tried making a simple blank "hello world" project and that seems to build, so it looks like the most trivial example works OK. It must be my project or some setting in it somewhere. Are there any temporary/working files I could try cleaning out on the mac side of things?

**Comment by RobTF** [comment] 2023-03-22 10:49
Ah no, sorry I wasn't clear I added an extension to the basic hello world project as well and it still worked.

**Comment by RobTF** [comment] 2023-03-22 11:13
OK - I'm playing about whilst I wait and it looks like the problem is when I build the project the extension files do not end up on the Mac at

`/Users/<username>/Library/Caches/Xamarin/mtbs/builds/<Extension Project>`

If I wipe this directory on the Mac and build the hello world project both the app and extension directories appear on the Mac in this location - *most* of the time as I can make it fail occasionally but seemingly randomly.

My actual project however, never produces assets in this directory, even if the build of the Extension seems to work.

Does this give any further clues?

thanks!

**Comment by RobTF** [comment] 2023-03-22 15:03
Yep, works when building on a Mac

**Comment by rolfbjarne** [comment] 2023-03-23 09:02
I believe this might be a duplicate of #17609, where the remote build process gets confused when there are multiple projects involved in the build. We've fixed this partially in the latest VS preview (17.6) - can you try this and see if it still fails for you?

**Closed** 2023-03-30 10:01 UTC
Labels: need-info, windows-only
