### ISSUE TITLE
No debugging with VS Code on physical device (Failed to mount developer tools), How to attach the debugger to running maui app?

### ISSUE THREAD

**Issue by hattmann** [xamarin/xamarin-macios#19341] opened 2023-10-25 12:02 UTC
### Steps to Reproduce

1. VS Code create Example Maui Project
2. Change output to IPhone (Device, no Emulator)
3. Set Breakpoint anywhere
4. Start Debugging, App ist not startet, Message: `Failed to mount developer tools, try to launch app manually`
```
Launching 'com.companyname.mauitestappcode' on the device 'iPhone von User'
warning HE0030: Could not mount developer tools on 'iPhone von Andreas': Could not locate device support files

warning HE0031: Failed to mount developer tools on 'iPhone von Andreas'.
warning HE0030: Could not mount developer tools on 'iPhone von Andreas': Could not locate device support files

warning HE0031: Failed to mount developer tools on 'iPhone von User'.
error MT1007: Failed to launch the application '/Users/andreastuschen/MauiTestappCode/MauiTestappCode/bin/Debug/net7.0-ios/ios-arm64/MauiTestappCode.app' on the device 'iPhone von Andreas': Failed to launch the application 'com.companyname.mauitestappcode' on the device 'iPhone von Andreas': Invalid Service Error (error: 0xe8000022)
. You can still launch the application manually by tapping on it.
```
6. Manual start of app does not connect the .NET Maui or Metor debugger to the app

### Expected Behavior
App debugging should start (With Visual Studio Mac it does)

### Actual Behavior
No debugging on ios device possible

### Environment
OSx VsCode

**Comment by rolfbjarne** [comment] 2023-10-25 14:00
This is due to a breaking change in Xcode 15 + iOS 17, and a duplicate of #19101.

We're fixed this, and we're working on getting the fix released. In the meantime #19101 contains a link to a package for Xamarin.iOS with the fix, and a comment explains how to fix .NET projects too.

**Closed by rolfbjarne** 2023-10-25 14:00 UTC

**Comment by hattmann** [comment] 2023-10-25 17:33
Okay, fine!
I added the path for native developing on mac, in #19101 there is only the windows path. Thank you very much @rolfbjarne!
