### ISSUE TITLE
[xcode12] macOS on Apple Silicon

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#8934] opened 2020-06-22 19:44 UTC
This is a feature released in [Xcode 12](https://github.com/xamarin/xamarin-macios/issues/8931).

Apple is transitioning from x86_64 to an arm based "Apple Silicon".

There are "Developer Transition Kits" that can be ordered.

There appears to be a special Xcode associated with it.

**Comment by rolfbjarne** [comment] 2020-09-07 08:12
A very good point about Apple Silicon was raised here: https://github.com/xamarin/xamarin-macios/issues/6246#issuecomment-685875019 - it's impossible to have a fat binary with arm64 for the simulator on Apple Silicon + arm64 for iOS device (and implementing support for xcframeworks would make this problem go away)

**Comment by chamons** [comment] 2020-09-16 17:35
Quick update the Apple Silicon and Xcode 12:

Xcode 12 shipped yesterday with a removal of all macOS APIs targeting 10.16 and 11.0, so this work isn't time bound to that release.

We are still investigating what is required to support Apple Silicon at both a partial and full level. So far initial testing suggests the x86_64 emulation is pretty good, and lets at least some use cases work today.

We expect that we'll need runtime support targeting the new architecture.

**Comment by tonyarnold** [comment] 2020-11-06 00:46
Xcode 12.2 with Apple Silicon support is being released in the next week or two - are there any updates on this support?

**Comment by chamons** [comment] 2020-11-06 15:33
See https://github.com/xamarin/xamarin-macios/issues/10005 for some details.

**Comment by ivanicin** [comment] 2020-12-19 17:40
I am not sure what this issue tracks:

- native Visual Studio for M1
- support for compiling universal/ARM binaries for Mac

It is not clear if this tracks both or any of that.

It is even less clear what issue #10005 tracks. While it is labeled as Meta it seems that for Xamarin.Mac it track only compatibility on Rosetta. Does that mean that there is no plan for the universal binary support?

To conclude I am interested to know when universal binaries support is released and I would like to subscribe to that issue. But after reading this I am not sure if there is any plan on that feature and if it is how can I track that for my purposes?

**Comment by rolfbjarne** [comment] 2021-01-11 11:20
> While it is labeled as Meta it seems that for Xamarin.Mac it tracks only compatibility on Rosetta.

That's correct, the purpose of that issue is to keep track of what needs to be done to make _existing_ features work.

> Does that mean that there is no plan for the universal binary support?

No, support for Xamarin.Mac apps built for Apple Silicon is in progress here: https://github.com/xamarin/xamarin-macios/pull/10115

**Comment by rolfbjarne** [comment] 2021-01-11 11:21
This looks like pretty much a duplicate of #10005, so I'm closing this.

**Closed by rolfbjarne** 2021-01-11 11:21 UTC
Labels: macOS
