### ISSUE TITLE
Error: ${ProjectDir}: No such file or directory (appName.iOS)

### ISSUE THREAD

**Issue by PinkoAgrawal** [xamarin/xamarin-macios#3939] opened 2018-04-13 14:42 UTC
### Steps to Reproduce

1. Use mac machine macOS high sierra. Update xCode & xamarin to latest version
2.  xCode Version 9.3 (9E145) & xamarin 11.6...
3.  Now run app in simulators with OS 11.3

### Expected Behavior
Application should work

### Actual Behavior
Not working
### Environment

=== Visual Studio Community 2017 for Mac ===

Version 7.4.2 (build 12)
Installation UUID: 3ad16a2d-ba7b-4910-b298-64ae85ff9f88
Runtime:
	Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508010000

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.2.0.16 (Visual Studio Community)
Android SDK: /Users/gsps/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		4.4   (API level 19)
		6.0   (API level 23)
		7.1   (API level 25)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.2.1.28 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.9.1.24 (Visual Studio Community)
Hash: f62de472
Branch: xcode9.3
Build date: 2018-03-29 19:30:53-0400

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704020012
Git revision: 0d8e3f0a4d683771f17959739956fa09c7ba21e3
Build date: 2018-03-30 10:45:17-04
Xamarin addins: 958839ea56ab1e331caf7c92b6ad50fb9e6ee9d2
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

```
```
### Build Logs
For Log find file

[Log.zip](https://github.com/xamarin/xamarin-macios/files/1907821/Log.zip)

**Comment by PinkoAgrawal** [comment] 2018-04-13 14:57
Hi Dalexsoto,
See my updated content in issue. If need further information i will provide. This is very annoying bug.
Thank you

**Comment by dalexsoto** [comment] 2018-04-13 14:58
```
Target _CodesignAppBundle:
    Tool /usr/bin/codesign execution started with arguments: -v --force --sign - --timestamp=none ${ProjectDir} /Users/gsps/Desktop/sisproject/edTheSIS/iOS/bin/iPhoneSimulator/Debug/device-builds/iphone7.2-11.3/edTheSIS.iOS.app
    bin/iPhoneSimulator/Debug/device-builds/iphone7.2-11.3/edTheSIS.iOS.app : error : ${ProjectDir}: No such file or directory
```

Interesting, it looks like `${ProjectDir}` is not expanding and it is just being passed as is to `codesign`, I have tested a file new project and I was unable to reproduce this. Are you able to reproduce in a more self-contained test? If so could you share it with us?

@jstedfast any idea what could be going on?

**Comment by PinkoAgrawal** [comment] 2018-04-13 15:03
Hi,
I am not getting what you mean by, Are you able to reproduce in a more self-contained test?
Still if you need more information about same issue can go here

[(https://stackoverflow.com/questions/49811145/xamarin-ios-projectdirno-such-file-or-directory-appname-ios)]

**Comment by dalexsoto** [comment] 2018-04-13 15:11
@PinkoAgrawal oh, sorry for my poor wording, I mean to ask you if you are able to replicate this issue in a new project since I am not able to replicate it myself.

**Comment by PinkoAgrawal** [comment] 2018-04-13 15:31
Alex,
Unfortunately I am unable to reproduce in new project.
Still if you anything can guess about issue, would be appreciated.

**Comment by jstedfast** [comment] 2018-04-13 17:55
Does the project define ExtraCodesignArgs?

**Comment by PinkoAgrawal** [comment] 2018-04-16 05:25
@jstedfast That issue has been solved. In iOS bundle singning--> I had declared additional argument as `${ProjectDir}`. After removing it, I am able to compile project.
Thank you Jeffery you saved my lots of time.

**Comment by dalexsoto** [comment] 2018-04-16 15:03
Closing per comment above, glad you fixed you issue.

**Closed by dalexsoto** 2018-04-16 15:03 UTC
Labels: iOS, need-info
