### ISSUE TITLE
MacOS bindings projects doesn't treat symlinks correctly (.NET 6)

### ISSUE THREAD

**Issue by hamarb123** [xamarin/xamarin-macios#12630] opened 2021-09-06 10:04 UTC
### Steps to Reproduce

1. Create .NET 6 macos bindings project
2. Add a framework with symbolic links eg. [MetalANGLE 0.0.7](https://github.com/kakashidinho/metalangle/releases/download/gles3-0.0.7/MetalANGLE.framework.mac.zip)
3. Create .NET 6 macos app `dotnet new macos` that references the bindings project
4. Build app with command line `dotnet build` in the macos app folder

### Expected Behavior
Folder structure is the same as in the framework folder with symlinks intact:
![image](https://user-images.githubusercontent.com/25316035/132197838-53428606-23f6-4561-9e71-6363a6ccaf8a.png)
Total framework folder size: 27.1 MB

### Actual Behavior
Folder structure is the same with all symlinks fully expanded:
![image](https://user-images.githubusercontent.com/25316035/132197996-6aa090fd-fbd1-4d4e-b227-a172af629a8e.png)
Total framework folder size: 81.4 MB

### Environment

```
Visual Studio Community 2022 for Mac Preview
Version 17.0 Preview (17.0 build 2706)
Installation UUID: 93d39ea7-8431-4eae-9b2f-0b0bd10e30da
	GTK+ 2.24.23

Mono Framework MDK
Runtime:
	Mono 6.12.0 (2020-02/eb4c3116ebf) (64-bit)
	Package version: 612000147

Roslyn (Language Service)
3.10.0-3.21226.12+c153357eb74f4b5c8fc905b7ae42168b76515531

NuGet
Version: 6.0.0.129

.NET SDK
SDK: /usr/local/share/dotnet/sdk/6.0.100-rc.2.21425.12/Sdks
SDK Versions:
	6.0.100-rc.2.21425.12
	6.0.100-rc.1.21417.3
	6.0.100-rc.1.21403.66
	6.0.100-preview.7.21379.14
	5.0.400
	3.1.412
	3.0.103
	2.2.207
	2.1.817
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.0-rc.2.21423.6
	6.0.0-rc.1.21415.6
	6.0.0-rc.1.21401.3
	5.0.9
	3.1.18
	3.0.3
	2.2.8
	2.1.29

.NET 5.0 SDK
SDK: 5.0.400

.NET Core 3.1 SDK
SDK: 3.1.412

Xamarin.Profiler
Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin Designer
Version: 17.0.0.58
Hash: 927d548a1
Branch: remotes/origin/d17-0
Build date: 2021-08-27 11:27:00 UTC

Apple Developer Tools
Xcode 13.0 (19223.2)
Build 13A5212g

Xamarin.Mac
Version: 7.14.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:00-0400

Xamarin.iOS
Version: 14.20.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:01-0400

Xamarin.Android
Version: 11.3.99.54 (Visual Studio Community)
Commit: xamarin-android/main/0e5e06f
Android SDK: /Users/Hamish/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.2
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/main@a5ed891
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@683f375

Microsoft OpenJDK for Mobile
Java SDK: /Users/Hamish/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.0.0.3
Hash: f06a85b
Branch: remotes/origin/HEAD
Build date: 2021-08-27 11:27:02 UTC

Android Device Manager
Version: 17.0.0.2
Hash: d8af29f
Branch: remotes/origin/main
Build date: 2021-08-27 11:27:02 UTC

Build Information
Release ID: 1700002706
Git revision: ba899d0dec8c3161225334edfcc5569ebfae78cc
Build date: 2021-08-27 07:26:10-04
Build branch: release-17.0

Operating System
Mac OS X 11.5.2
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Wed Jun 23 00:26:31 PDT 2021
    root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
```

### Build Logs

[msbuild.log.zip](https://github.com/xamarin/xamarin-macios/files/7115040/msbuild.log.zip)

### Example Project (If Possible)

[TestBindingsProject.zip](https://github.com/xamarin/xamarin-macios/files/7115035/TestBindingsProject.zip)
Note, before building this project, you need to first extract the zip at `TestBindingsProject/Natives/MetalANGLE.framework.mac.zip` first using Archive Utility (other unarchivers may also work) - it should create a folder called `MetalANGLE.framework` in the Natives folder with the structure shown in the above images.

**Comment by rolfbjarne** [comment] 2021-09-08 08:15
Thanks for the test case!

This is a duplicate of #12369, and I'm closing this in favor of that one.

**Closed by rolfbjarne** 2021-09-08 08:15 UTC
Labels: bug, dotnet, dotnet-pri0
