### ISSUE TITLE
VS 17.5.0 throws error MS B4018: The "ComputeBundleResourceOutputPaths" task failed unexpectedly while creating iOS IPA using MSBuild 

### ISSUE THREAD

**Issue by amarthere** [xamarin/xamarin-macios#17609] opened 2023-02-23 18:33 UTC
### Steps to Reproduce
1.  Create Xamarin iOS cross platform app in VS V. 17.5.0
2. Run MSBuild command from Windows command prompt to generate IPA

### Expected Behavior
Generates IPA
### Actual Behavior
Gives below error:
(_ComputeBundleResourceOutputPaths target) ->
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(1140,3): error MS
B4018: The "ComputeBundleResourceOutputPaths" task failed unexpectedly. [sampleiOS.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(1140,3): error MSB4
018: System.NullReferenceException: Object reference not set to an instance of an object. [sampleiOS.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(1140,3): error MSB4
018:    at Xamarin.MacDev.Tasks.ComputeBundleResourceOutputPaths.RemoveDuplicates() in /Users/builder/azdo/_work/1/s/xa
marin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/ComputeBundleResourceOutputPaths.cs:line 37 [sampleiOS.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(1140,3): error MSB4
018:    at Xamarin.MacDev.Tasks.ComputeBundleResourceOutputPaths.Execute() in /Users/builder/azdo/_work/1/s/xamarin-mac
ios/msbuild/Xamarin.MacDev.Tasks/Tasks/ComputeBundleResourceOutputPaths.cs:line 17 [sampleiOS.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(1140,3): error MSB4
018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [sampleiOS.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(1140,3): error MSB4
018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [sampleiOS.csproj]

### Environment

VS v. 17.5.0

**Note:**

It works when I generate IPA from Visual studio but fails for MSBuild from Windows command prompt.

**Comment by rolfbjarne** [comment] 2023-02-24 09:35
Can you show the complete msbuild command you use?

**Comment by cwall-dev** [comment] 2023-02-24 14:13
I get the same error with 17.5.0 on Windows.
I attached the msbuild log with diagnostics log level.
[msbuild.log](https://github.com/xamarin/xamarin-macios/files/10824999/msbuild.log)

**Comment by amarthere** [comment] 2023-02-24 17:56
Hi @rolfbjarne,

I used below command from Windows command prompt:

"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild" "C:\sample\sampleApp.iOS"  /t:Build /p:Configuration=PROD_Release /p:Platform=iPhone /p:ServerAddress=192.168.1.100 /p:ServerUser="XXXX" /p:ServerPassword=XXXX /p:BuildIpa=true /p:IpaPackageDir="C:\sample\sampleApp.iOS" /p:IpaPackageName="Prod_Release" -fl -flp:logfile="C:\C:\sample\sampleApp.iOS\log1.log";

**Comment by rolfbjarne** [comment] 2023-02-24 19:57
@amarthere can you get the complete version information from here: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#visual-studio-for-windows-1?

**Comment by rolfbjarne** [comment] 2023-02-24 19:58
@cwall-dev if you could post your complete version information as well (https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#visual-studio-for-windows-1)., that would be great

**Comment by amarthere** [comment] 2023-02-24 21:54
@rolfbjarne  Here it is:

Microsoft Visual Studio Enterprise 2022
Version 17.5.0
VisualStudio.17.Release/17.5.0+33414.496
Microsoft .NET Framework
Version 4.8.04084 Installed Version: Enterprise Visual C++ 2022   00476-80000-00000-AA539
Microsoft Visual C++ 2022 ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools ASA Service Provider   1.0 ASP.NET and Web Tools   17.5.317.37931
ASP.NET and Web Tools Azure App Service Tools v3.0.0   17.5.317.37931
Azure App Service Tools v3.0.0 Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio Azure Functions and Web Jobs Tools   17.5.317.37931
Azure Functions and Web Jobs Tools Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio C# Tools   4.5.0-6.23109.5+6a5a63bbc9f4449d9bd1e95a8f9624939c3ccdc3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used. Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools. Extensibility Message Bus   1.4.3 (main@2a4517a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration. Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines Mono Debugging for Visual Studio   17.5.9 (11975e6)
Support for debugging Mono processes with Visual Studio. NuGet Package Manager   6.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/ Razor (ASP.NET Core)   17.5.2.2307502+8b3141d86b738daf2ca3ed9c15b12513071fc676
Provides languages services for ASP.NET Core Razor. SQL Server Data Tools   17.2.40118.0
Microsoft SQL Server Data Tools Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees. ToolWindowHostedEditor   1.0
Hosting json editor into a tool window TypeScript Tools   17.0.20105.2003
TypeScript Tools for Microsoft Visual Studio Visual Basic Tools   4.5.0-6.23109.5+6a5a63bbc9f4449d9bd1e95a8f9624939c3ccdc3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used. Visual F# Tools   17.5.0-beta.23053.5+794b7c259d9646a7eb685dad865aa27da7940a21
Microsoft Visual F# Tools Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio. VisualStudio.DeviceLog   1.0
Information about my package VisualStudio.Mac   1.0
Mac Extension for Visual Studio VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info Xamarin   17.5.0.173 (d17-5@33e727c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android. Xamarin Designer   17.5.3.46 (remotes/origin/d17-5@e4dd80b2bb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio. Xamarin Templates   17.5.41 (ba80d05)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms. Xamarin.Android SDK   13.2.0.0 (d17-5/797e2e1)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 6dd9def
    Java.Interop: xamarin/java.interop/main@149d70fe
    SQLite: xamarin/sqlite/3.40.0@fdc1e34
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@9f02d77 
Xamarin.iOS and Xamarin.Mac SDK   16.2.0.5 (7738c90c9)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by cwall-dev** [comment] 2023-02-25 09:45
@rolfbjarne 
Here the version information:

Microsoft Visual Studio Enterprise 2022
Version 17.5.0
VisualStudio.17.Release/17.5.0+33414.496
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA052
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.5.317.37931
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.5.317.37931
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.5.317.37931
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

BTMDLG Editor Package   1.0
BTMDLG file editor for Visual Studio

C# Tools   4.5.0-6.23109.5+6a5a63bbc9f4449d9bd1e95a8f9624939c3ccdc3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.4.3 (main@2a4517a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.5.9 (11975e6)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.50105.3 Commit Hash:882de61a7c99ae988d4c62029301292a3e0b1d56
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Rainbow Braces   1.0.78
Colorizes matching brace pairs to make it easy to identify them and their scope. Works for curly brackets, parentheses, and square brackets.

Razor (ASP.NET Core)   17.5.2.2307502+8b3141d86b738daf2ca3ed9c15b12513071fc676
Provides languages services for ASP.NET Core Razor.

Resource Localizer   1.0
Collect resources of a sovia project and manage the localization of them.

sovia ProjectConfigurator   1.0
Addin for sovia project configuration

SQL Server Data Tools   17.2.40118.0
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.20105.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.5.0-6.23109.5+6a5a63bbc9f4449d9bd1e95a8f9624939c3ccdc3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.5.0-beta.23053.5+794b7c259d9646a7eb685dad865aa27da7940a21
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.5.0.173 (d17-5@33e727c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.5.3.46 (remotes/origin/d17-5@e4dd80b2bb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.5.41 (ba80d05)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.0.0 (d17-5/797e2e1)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 6dd9def
    Java.Interop: xamarin/java.interop/main@149d70fe
    SQLite: xamarin/sqlite/3.40.0@fdc1e34
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@9f02d77


Xamarin.iOS and Xamarin.Mac SDK   16.2.0.5 (7738c90c9)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by rolfbjarne** [comment] 2023-02-27 13:49
> Hi @rolfbjarne,
> 
> I used below command from Windows command prompt:
> 
> "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild" "C:\sample\sampleApp.iOS" /t:Build /p:Configuration=PROD_Release /p:Platform=iPhone /p:ServerAddress=192.168.1.100 /p:ServerUser="XXXX" /p:ServerPassword=XXXX /p:BuildIpa=true /p:IpaPackageDir="C:\sample\sampleApp.iOS" /p:IpaPackageName="Prod_Release" -fl -flp:logfile="C:\C:\sample\sampleApp.iOS\log1.log";

Can you add `bl:msbuild.binlog` to this command:

> "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild" "C:\sample\sampleApp.iOS" /t:Build /p:Configuration=PROD_Release /p:Platform=iPhone /p:ServerAddress=192.168.1.100 /p:ServerUser="XXXX" /p:ServerPassword=XXXX /p:BuildIpa=true /p:IpaPackageDir="C:\sample\sampleApp.iOS" /p:IpaPackageName="Prod_Release" -fl -flp:logfile="C:\C:\sample\sampleApp.iOS\log1.log" -bl:msbuild.binlog

and attach the resulting `msbuild.binlog` file here?

**Comment by cwall-dev** [comment] 2023-02-27 15:34
Hi @rolfbjarne 
Attached the zipped msbuild.binlog
[msbuild.zip](https://github.com/xamarin/xamarin-macios/files/10841285/msbuild.zip)

**Comment by rolfbjarne** [comment] 2023-02-28 15:55
So a team member told me this should be fixed in the latest VS preview (17.6), so could you try that and see if it works?

If not, please get the updated version info (https://github.com/xamarin/xamarin-macios/issues/17609#issuecomment-1444367902) and a new msbuild.binlog.

**Comment by amarthere** [comment] 2023-02-28 18:40
@rolfbjarne:
Attached msbuild.binlog for 17.5
[msbuild.zip](https://github.com/xamarin/xamarin-macios/files/10853731/msbuild.zip)

**Comment by amarthere** [comment] 2023-02-28 19:34
@rolfbjarne : I tried with 17.6.0 Preview 1 and got same error. Below is the information you requested.
[msbuild.zip](https://github.com/xamarin/xamarin-macios/files/10854094/msbuild.zip)
[17_6_Version_Info.zip](https://github.com/xamarin/xamarin-macios/files/10854104/17_6_Version_Info.zip)

**Comment by cwall-dev** [comment] 2023-03-03 15:01
@rolfbjarne 
One more info: I can build a blank Xamarin iOS App Project with no references successfully. As soon as I add an iOS Class Library Project as a ProjectReference the error occurs.

I created a small [repro repo](https://github.com/cwall-dev/XamarinMsBuildError) with a blank app and an empty iOS Class library project. 

You will hit the error if you are using the following command:
msbuild App2.sln /t:Restore,Build /p:ServerAddress=xxx.xxx.xxx.xxx /p:ServerUser=macuser /p:ServerPassword=macpassword /p:Platform=iPhone /p:BuildIpa=true

**Comment by rolfbjarne** [comment] 2023-03-03 15:09
@cwall-dev yes, there's problem where the remote connection gets confused when there are multiple projects involved. We've supposedly fixed it, and the fix should be in the latest 17.6 preview, but for some reason it seems that it's not there.

**Comment by rolfbjarne** [comment] 2023-03-06 09:58
@cwall-dev yes, my colleague confirmed that the fix for this issue for command-line builds didn't get into the first 17.6 preview, but it will be included in preview 2.

Would building from a Mac work as a workaround for you in the meantime?

**Comment by rolfbjarne** [comment] 2023-03-06 22:35
> Ok, as soon as the next preview is available I will test it and post the results here.

Great, thanks!

**Comment by amarthere** [comment] 2023-03-06 23:15
@rolfbjarne : Do you know the estimated date of preview release? Thanks

**Comment by rolfbjarne** [comment] 2023-03-07 07:11
@amarthere I believe new previews come out on a roughly monthly schedule, so maybe in three weeks or so.

**Comment by cwall-dev** [comment] 2023-03-15 07:25
@rolfbjarne I can confirm that the issue is fixed in VS 2022 17.6 Preview 2.

**Comment by rolfbjarne** [comment] 2023-03-15 07:31
> @rolfbjarne I can confirm that the issue is fixed in VS 2022 17.6 Preview 2.

Thanks for confirming! I'll close this then.

**Comment by cwall-dev** [comment] 2023-03-16 09:45
@rolfbjarne unfortunately it seems that it is not working stable. After the test on my local dev machine I installed the preview 2.0 on our Build Host.
When we build within an azure devops pipeline on our hosted agent the error still occures. 

Attached you'll find the current bin log that was created within the azure devops pipeline.
[Error_iOSBuild.zip](https://github.com/xamarin/xamarin-macios/files/10989139/Error_iOSBuild.zip)

**Visual Studio Version:**

Microsoft Visual Studio Enterprise 2022
Version 17.6.0 Preview 2.0
VisualStudio.17.Preview/17.6.0-pre.2.0+33513.286
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA892
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.6.204.15292
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.6.204.15292
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.6.204.15292
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.6.0-2.23151.17+1314d090671dc1a1500c5303c4b5ae9150f40d98
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.4.3 (main@2a4517a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.6.8 (b2de728)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.5.2.2315304+47a4b09393e3f48a7c47277d13e593bda511dfef
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.2.40306.0
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.20302.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.6.0-2.23151.17+1314d090671dc1a1500c5303c4b5ae9150f40d98
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.6.0-beta.23126.1+4de2393866be1be6fa35af544c6f25a10af5ab3d
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.6.0.96 (main@020b354)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.6.2.2 (remotes/origin/d17-6@dbce9e1ce9)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.6.0 (907c729)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.0.6 (d17-5/a200af1)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 6dd9def
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@9f02d77


Xamarin.iOS and Xamarin.Mac SDK   16.2.0.11 (043a2484c)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by rolfbjarne** [comment] 2023-03-16 12:48
We'll have a look and see what we can find out.

**Comment by wgriep** [comment] 2023-03-20 19:05
@rolfbjarne  Are there any potential workarounds?

**Comment by rolfbjarne** [comment] 2023-03-21 06:33
We're still looking to see what's happening, but it seems our initial fix was not enough.

> @rolfbjarne Are there any potential workarounds?

You can build on the remote Mac directly (instead of building on Windows and have our logic run the build the project remotely on the Mac, you can check out your code on the Mac directly, and build it there yourself).

**Comment by cwall-dev** [comment] 2023-03-21 10:22
Currently we are using a Build Task that cannot run on macos because it has .net 4.8 dependencies.

**Comment by wgriep** [comment] 2023-03-21 10:27
@rolfbjarne Our Xamarin Forms projects have several libraries that require building thru Windows build processes.  Mac builds are not an option.  Last version we were able to use DevOps build process to build iOS (Enterprise and App Store) was 17.3.5.  Each upgrade has broken some form of the build process.  This has become a critical issue.

**Comment by dalexsoto** [comment] 2023-03-21 22:37
Hello! 👋

@rolfbjarne has been serving as a bridge (Thank you!!) between this issue and the Team that is behind the VS Extension, if you need immediate support, I would advice reaching out to the [Microsoft Support](https://support.serviceshub.microsoft.com/supportforbusiness) team so your request can be properly routed directly to the appropriate team that is in charge of the extension.

We will keep this issue open and we'll update as we hear more, than you for your patience!

**Comment by hansoncaleb** [comment] 2023-04-11 15:13
Has there been any updates on this issue?

**Comment by nisewonder** [comment] 2023-04-17 20:10
I reported this issue in the Microsoft Developer Community on February 15th, 2023.  The link is here: https://developercommunity.visualstudio.com/t/cannot-build-iOS-ipa-file-for-store-dis/10280887

The status is "under consideration".  If you have access, please upvote the issue.

**Comment by cwall-dev** [comment] 2023-05-19 08:20
@rolfbjarne today I tested 17.6.0. With this version the issue seemes to be fixed.

**Comment by rolfbjarne** [comment] 2023-05-19 08:35
That's great, thanks for confirming!

**Closed by rolfbjarne** 2023-05-19 08:35 UTC
Labels: bug, windows-only

**Comment by baaaaif** [comment] 2023-06-06 08:21
@rolfbjarne
Unfortunately, I still get the error with 17.6.2 and 17.7p1. (Windows)
Or rather the error from "Cannot build iOS apps with extensions (ditto exited with code 1 at _CopyAppExtensionsToBundle). "[#17878](https://github.com/xamarin/xamarin-macios/issues/17878)
Both are closed, but I can still comment here :)

[audius.dashface.Maui_Release_AnyCPU_net7.0-ios_Build_2023-06-05T18_52_36.9991610+02_00.zip](https://github.com/xamarin/xamarin-macios/files/11662018/audius.dashface.Maui_Release_AnyCPU_net7.0-ios_Build_2023-06-05T18_52_36.9991610%2B02_00.zip)
