### ISSUE TITLE
XCode 16/iOS 18 - Errors on launch and no debugging? 

### ISSUE THREAD

**Issue by PureWeen** [xamarin/xamarin-macios#21479] opened 2024-10-20 14:59 UTC
Moved From:

https://github.com/dotnet/maui/issues/25228

### Description

When starting a debug session the provided errors are spewed out and breakpoints etc. do not work. I am uncertain as to the support story for XCode 16 and iOS 18. Is this a problem we are waiting for a fix on or should this work?

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.91 SR9.1

### Affected platforms

iOS

### Affected platform versions

iOS 18, XCode 16

### Did you find any workaround?

No

### Relevant log output

```
2024-10-12 17:47:27.614 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.IDEDebugger.SpriteKitQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
2024-10-12 17:47:27.614 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.SpriteKit.GKStateMachineQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
2024-10-12 17:47:27.621 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.IDEPlaygroundsKit.PlaygroundBottomBarExecutionAdaptor for extension Xcode.IDEPlaygroundEditor.IDEPlaygroundBottomBarExecutionAdaptor of plug-in com.apple.dt.IDEPlaygroundEditorPlugin
2024-10-12 17:47:27.621 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.WatchOS.Bundle of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-12 17:47:27.622 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.WatchOS.BundleInfo of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-12 17:47:27.622 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEWatchSupportUI:IDEWatchSupportUI.plugindata/plug-in[1]/extension[11] of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-12 17:47:27.622 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-12 17:47:27.622 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOSSimulator.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-12 17:47:27.622 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-12 17:47:27.622 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOS.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-12 17:47:27.622 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.IDEiOSSupportCore.iOSDeviceLocatorMapping for extension Xcode.IDEiOSSupportCore.iOSDeviceLocatorMapping.driverkit of plug-in com.apple.dt.IDEDriverKitSupportCore
2024-10-12 17:47:27.622 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEDriverKitSupportUI:IDEDriverKitSupportUI.plugindata/plug-in[1]/extension[2] of plug-in com.apple.dt.IDEDriverKitSupportUI
2024-10-12 17:47:27.622 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEOSXSupportUI:IDEOSXSupportUI.plugindata/plug-in[1]/extension[5] of plug-in com.apple.dt.IDEOSXSupportUI
2024-10-12 17:47:27.622 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEVisionSupportUI:IDEVisionSupportUI.plugindata/plug-in[1]/extension[5] of plug-in com.apple.dt.IDEVisionSupportUI
2024-10-12 17:47:27.622 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Framework of plug-in com.apple.dt.IDEVisionSupportUI
2024-10-12 17:47:27.622 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Bundle of plug-in com.apple.dt.IDEVisionSupportUI
2024-10-12 17:47:27.622 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Application of plug-in com.apple.dt.IDEVisionSupportUI
2024-10-12 17:47:27.623 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.appletvos.BundleTargetInfo of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-12 17:47:27.623 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATVSimulator.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-12 17:47:27.623 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-12 17:47:27.623 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.appletvos.Bundle of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-12 17:47:27.623 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATV.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-12 17:47:27.623 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEAppleTVSupportUI:IDEAppleTVSupportUI.plugindata/plug-in[1]/extension[11] of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-12 17:47:27.623 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DeviceIconProvider for extension Xcode.DebuggerFoundation.DeviceIconProvider.AppleTV of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-12 17:47:27.623 mlaunch[18123:344604] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-12 17:47:31.361 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.IDEDebugger.SpriteKitQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
2024-10-12 17:47:31.361 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.SpriteKit.GKStateMachineQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
2024-10-12 17:47:31.367 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.IDEPlaygroundsKit.PlaygroundBottomBarExecutionAdaptor for extension Xcode.IDEPlaygroundEditor.IDEPlaygroundBottomBarExecutionAdaptor of plug-in com.apple.dt.IDEPlaygroundEditorPlugin
2024-10-12 17:47:31.367 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.WatchOS.Bundle of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-12 17:47:31.367 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.WatchOS.BundleInfo of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-12 17:47:31.367 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-12 17:47:31.367 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEWatchSupportUI:IDEWatchSupportUI.plugindata/plug-in[1]/extension[11] of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-12 17:47:31.367 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOSSimulator.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-12 17:47:31.367 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-12 17:47:31.367 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOS.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-12 17:47:31.367 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.IDEiOSSupportCore.iOSDeviceLocatorMapping for extension Xcode.IDEiOSSupportCore.iOSDeviceLocatorMapping.driverkit of plug-in com.apple.dt.IDEDriverKitSupportCore
2024-10-12 17:47:31.367 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEDriverKitSupportUI:IDEDriverKitSupportUI.plugindata/plug-in[1]/extension[2] of plug-in com.apple.dt.IDEDriverKitSupportUI
2024-10-12 17:47:31.368 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEOSXSupportUI:IDEOSXSupportUI.plugindata/plug-in[1]/extension[5] of plug-in com.apple.dt.IDEOSXSupportUI
2024-10-12 17:47:31.368 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEVisionSupportUI:IDEVisionSupportUI.plugindata/plug-in[1]/extension[5] of plug-in com.apple.dt.IDEVisionSupportUI
2024-10-12 17:47:31.368 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Framework of plug-in com.apple.dt.IDEVisionSupportUI
2024-10-12 17:47:31.368 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Bundle of plug-in com.apple.dt.IDEVisionSupportUI
2024-10-12 17:47:31.368 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Application of plug-in com.apple.dt.IDEVisionSupportUI
2024-10-12 17:47:31.368 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.appletvos.BundleTargetInfo of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-12 17:47:31.368 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATVSimulator.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-12 17:47:31.368 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-12 17:47:31.368 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.appletvos.Bundle of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-12 17:47:31.368 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATV.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-12 17:47:31.368 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEAppleTVSupportUI:IDEAppleTVSupportUI.plugindata/plug-in[1]/extension[11] of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-12 17:47:31.368 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DeviceIconProvider for extension Xcode.DebuggerFoundation.DeviceIconProvider.AppleTV of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-12 17:47:31.368 mlaunch[18158:344844] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
xcrun devicectl -j /var/folders/5d/bzy7c0354p7f01_x0pf16w680000gn/T/tmpX7MHob.tmp device process launch --terminate-existing --device 00008120-00161D9A0EB9A01E --console com.MyApp
2024-10-12 17:47:31.561 MyApp[1080:118667] Microsoft.iOS: Socket error while connecting to IDE on 127.0.0.1:54383: Connection refused
```

**Comment by rezamohamed** [comment] 2024-10-20 15:04
Just to be clear, these issues only happen when you connect a physical device and debug. No issues debugging on the simulator. Unfortunately things like In App Billing don't work from a simulator, and for proper testing we need to connect a physical device.

![image](https://github.com/user-attachments/assets/3d76e83a-2615-41cd-9449-90ff5ae6f4fe)

**Comment by rolfbjarne** [comment] 2024-10-21 15:15
This looks like the problem:

> Microsoft.iOS: Socket error while connecting to IDE on 127.0.0.1:54383: Connection refused

The app is failing to connect to the debugger.

Which IDE are you using?

**Comment by rezamohamed** [comment] 2024-10-21 15:20
> This looks like the problem:
> 
> > Microsoft.iOS: Socket error while connecting to IDE on 127.0.0.1:54383: Connection refused
> 
> The app is failing to connect to the debugger.
> 
> Which IDE are you using?

I am using Jetbrains Rider 2024.2.5

**Comment by rolfbjarne** [comment] 2024-10-21 15:22
> > This looks like the problem:
> > > Microsoft.iOS: Socket error while connecting to IDE on 127.0.0.1:54383: Connection refused
> > 
> > 
> > The app is failing to connect to the debugger.
> > Which IDE are you using?
> 
> I am using Jetbrains Rider 2024.2.5 on Mac OS Sequoia 15.0.1

Do you get the same behavior if you try with VSCode?

**Comment by rezamohamed** [comment] 2024-10-21 15:26
> > > This looks like the problem:
> > > > Microsoft.iOS: Socket error while connecting to IDE on 127.0.0.1:54383: Connection refused
> > > 
> > > 
> > > The app is failing to connect to the debugger.
> > > Which IDE are you using?
> > 
> > 
> > I am using Jetbrains Rider 2024.2.5 on Mac OS Sequoia 15.0.1
> 
> Do you get the same behavior if you try with VSCode?

I have not set up VSCode, I primarily only use Rider.

**Comment by rolfbjarne** [comment] 2024-10-22 09:19
Does it work if you create a new project from a template?

**Comment by lhughey** [comment] 2024-10-22 14:22
I'm also experiencing the same symptom (I've not confirmed if the cause is the same). I'm able to click on the icon and start debugging, but it does require manually opening the app.

**Comment by rezamohamed** [comment] 2024-10-22 15:02
> Does it work if you create a new project from a template?

it does not work, I am always starting with a empty Maui template

**Comment by rolfbjarne** [comment] 2024-10-23 19:05
Please try creating a new project from a template _in VSCode_ and see if you can debug that on device. This way we can rule out any bugs in the Rider that may cause this.

If it doesn't work in VSCode, please attach any output you're getting.

**Comment by rezamohamed** [comment] 2024-10-26 02:14
A New Maui Project in VS Code can debug, but the same project in Rider cannot. The following is the output from Rider, which is similar to what is above.

```
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_18.0/18.0.8303/tools/bin/mlaunch --devname "XXX’s iPhone" --killdev com.mycompany.vscodemaui --launchdev /Users/myusername/Development/Projects/VsCodeMaui/VsCodeMaui/bin/Debug/net8.0-ios/ios-arm64/VsCodeMaui.app --wait-for-unlock --argument=-connection-mode --argument=wifi -sdk 11.0 --argument=-monodevelop-port --argument=10001 --setenv=__XAMARIN_DEBUG_PORT__=10001 --sdkroot /Applications/Xcode.app/Contents/Developer
2024-10-25 21:11:22.131 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.SpriteKit.GKStateMachineQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
2024-10-25 21:11:22.132 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.IDEDebugger.SpriteKitQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
2024-10-25 21:11:22.137 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.IDEPlaygroundsKit.PlaygroundBottomBarExecutionAdaptor for extension Xcode.IDEPlaygroundEditor.IDEPlaygroundBottomBarExecutionAdaptor of plug-in com.apple.dt.IDEPlaygroundEditorPlugin
2024-10-25 21:11:22.138 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-25 21:11:22.138 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-25 21:11:22.138 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.WatchOS.BundleInfo of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-25 21:11:22.138 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEWatchSupportUI:IDEWatchSupportUI.plugindata/plug-in[1]/extension[11] of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-25 21:11:22.138 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOS.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-25 21:11:22.138 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOSSimulator.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-25 21:11:22.138 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.WatchOS.Bundle of plug-in com.apple.dt.IDEWatchSupportUI
2024-10-25 21:11:22.138 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.IDEiOSSupportCore.iOSDeviceLocatorMapping for extension Xcode.IDEiOSSupportCore.iOSDeviceLocatorMapping.driverkit of plug-in com.apple.dt.IDEDriverKitSupportCore
2024-10-25 21:11:22.138 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEDriverKitSupportUI:IDEDriverKitSupportUI.plugindata/plug-in[1]/extension[2] of plug-in com.apple.dt.IDEDriverKitSupportUI
2024-10-25 21:11:22.138 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEOSXSupportUI:IDEOSXSupportUI.plugindata/plug-in[1]/extension[5] of plug-in com.apple.dt.IDEOSXSupportUI
2024-10-25 21:11:22.138 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEVisionSupportUI:IDEVisionSupportUI.plugindata/plug-in[1]/extension[5] of plug-in com.apple.dt.IDEVisionSupportUI
2024-10-25 21:11:22.138 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Framework of plug-in com.apple.dt.IDEVisionSupportUI
2024-10-25 21:11:22.138 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Application of plug-in com.apple.dt.IDEVisionSupportUI
2024-10-25 21:11:22.138 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Bundle of plug-in com.apple.dt.IDEVisionSupportUI
2024-10-25 21:11:22.139 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.appletvos.BundleTargetInfo of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-25 21:11:22.139 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-25 21:11:22.139 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEAppleTVSupportUI:IDEAppleTVSupportUI.plugindata/plug-in[1]/extension[11] of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-25 21:11:22.139 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DeviceIconProvider for extension Xcode.DebuggerFoundation.DeviceIconProvider.AppleTV of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-25 21:11:22.139 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATVSimulator.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-25 21:11:22.139 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.appletvos.Bundle of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-25 21:11:22.139 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATV.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-10-25 21:11:22.139 mlaunch[42157:10330958] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
```

**Comment by rolfbjarne** [comment] 2024-10-28 08:00
> A New Maui Project in VS Code can debug, but the same project in Rider cannot.

That points towards an issue in Rider, so I'll close this.

Note that all the "Requested but did not find extension point with identifier [...]" lines in your output are just noise, the important part is what comes after those lines, so please make sure to add those to Rider's bug report.

**Closed by rolfbjarne** 2024-10-28 08:00 UTC
Labels: need-attention

**Comment by IsraelSoto-Improving** [comment] 2025-11-13 22:26
@rolfbjarne I know this is an old issue but I started facing this using VSCode with the project I work with and with a new project from the template. Should I open a new issue?

**Comment by rolfbjarne** [comment] 2025-11-14 07:58
> [@rolfbjarne](https://github.com/rolfbjarne) I know this is an old issue but I started facing this using VSCode with the project I work with and with a new project from the template. Should I open a new issue?

Yes, please!
