### ISSUE TITLE
OpenSettings() from CXCallDirectoryManager stopped working in .NET 8.0 for iOS

### ISSUE THREAD

**Issue by thomas-cas** [xamarin/xamarin-macios#21008] opened 2024-08-09 11:26 UTC
We have a iOS app that we recently migrated from Xamarin.iOS to .NET 8.0 for iOS. After this update opening the "Call Blocking & Identification" settings on the iOS device stopped working.

https://developer.apple.com/documentation/callkit/cxcalldirectorymanager/opensettings(completionhandler:)

### Steps to Reproduce

Call OpenSettings() somewhere in the app like this:

`CXCallDirectoryManager.SharedInstance.OpenSettings(_ => { }));`

### Expected Behavior

The phone's "Call Blocking & Identification" settings should be opened.

### Actual Behavior

This fails since the update and nothing happens when calling it. 

For testing I built a blank native Swift app just calling OpenSettings() when pressing a button and here the phone correctly navigates to the caller id settings page.

### Logs
The NSError I get in the .NET version is the follwing:

```
Couldn’t communicate with a helper application.
Error Domain=NSCocoaErrorDomain Code=4097 "connection to service named com.apple.CallKit.CallDirectory" UserInfo={NSDebugDescription=connection to service named com.apple.CallKit.CallDirectory}
```

And the MacOS console logs the follwing information:
```
11:53:06.692184+0200	OpenSettingsTest	[0x1014066c0] activating connection: mach=false listener=false peer=false name=com.apple.CallKit.CallDirectory
11:53:06.692260+0200	OpenSettingsTest	[0x1014066c0] activating connection: mach=false listener=false peer=false name=com.apple.CallKit.CallDirectory
11:53:06.693727+0200	OpenSettingsTest	error Error Domain=NSCocoaErrorDomain Code=4097 UserInfo={NSDebugDescription=<private>}
11:53:06.693664+0200	OpenSettingsTest	error Error Domain=NSCocoaErrorDomain Code=4097 UserInfo={NSDebugDescription=<private>}
11:53:06.699024+0200	OpenSettingsTest	[0x1014066c0] Re-initialization successful; calling out to event handler with XPC_ERROR_CONNECTION_INTERRUPTED
11:53:06.699157+0200	OpenSettingsTest	Default connection interrupted for call directory manager <private>
11:53:06.699317+0200	OpenSettingsTest	[0x1014066c0] invalidated because the current process cancelled the connection by calling xpc_connection_cancel()
11:53:06.699461+0200	OpenSettingsTest	Default connection invalidated for call directory manager <private>
11:53:06.698939+0200	OpenSettingsTest	[0x1014066c0] Re-initialization successful; calling out to event handler with XPC_ERROR_CONNECTION_INTERRUPTED
11:53:06.699095+0200	OpenSettingsTest	Default connection interrupted for call directory manager <private>
11:53:06.699234+0200	OpenSettingsTest	[0x1014066c0] invalidated because the current process cancelled the connection by calling xpc_connection_cancel()
11:53:06.699399+0200	OpenSettingsTest	Default connection invalidated for call directory manager <private>
```

**Comment by rolfbjarne** [comment] 2024-08-09 12:57
I can reproduce, and the device log also shows:

```
com.apple.CallKit.CallDirectory(Foundation)[33060] <Fault>: <NSXPCConnection: 0x115d0c2a0> connection from pid 33189 on anonymousListener or serviceListener received an undecodable message (incompatible reply block signature for launchCallDirectorySettingsWithReply: (wire: <NSMethodSignature: 0x115f06750>
    number of arguments = 3
    frame size = 224
    is special struct return? NO
    return value: -------- -------- -------- --------
        type encoding (v) 'v'
        flags {}
        modifiers {}
        frame {offset = 0, offset adjust = 0, size = 0, size adjust = 0}
        memory {offset = 0, size = 0}
    argument 0: -------- -------- -------- --------
        type encoding (@) '@?'
        flags {isObject, isBlock}
        modifiers {}
        frame {offset = 0, offset adjust = 0, size = 8, size adjust = 0}
        memory {offset = 0, size = 8}
    argument 1: -------- -------- -------- --------
        type encoding (^) '^v'
        flags {}
        modifiers {}
        frame {offset = 8, offset adjust = 0, size = 8, size adjust = 0}
        memory {offset = 0, size = 8}
    argument 2: -------- -------- -------- --------
        type encoding ({) '{NativeHandle=^v}'
        flags {isStruct}
        modifiers {}
        frame {offset = 16, offset adjust = 0, size = 8, size adjust = 0}
        memory {offset = 0, size = 8}
            type encoding (^) '^v'
            flags {}
            modifiers {}
            frame {offset = 16, offset adjust = 0, size = 8, size adjust = 0}
            memory {offset = 0, size = 8}
 vs local: <NSMethodSignature: 0xa911206d62b9baa7>
    number of arguments = 2
    frame size = 224
    is special struct return? NO
    return value: -------- -------- -------- --------
        type encoding (v) 'v'
        flags {}
        modifiers {}
        frame {offset = 0, offset adjust = 0, size = 0, size adjust = 0}
        memory {offset = 0, size = 0}
    argument 0: -------- -------- -------- --------
        type encoding (@) '@?'
        flags {isObject<\M-b\M^@\M-&>)
```

This looks like Apple is validating a bit too much :/ We might have to come up with some sort of workaround here.

I haven't tried this, but I suspect that if you create a tiny Objective-C library that calls this method it'll work.

**Comment by rolfbjarne** [comment] 2024-08-09 18:51
> This looks like Apple is validating a bit too much :/ We might have to come up with some sort of workaround here.

Never mind, this is a bug on our side. Fix is in progress.

**Closed** 2024-08-15 08:02 UTC
Labels: bug

**Comment by AzizBelAbed** [comment] 2024-08-22 12:16
The issue is reproducible on .NET MAUI.

**Comment by AzizBelAbed** [comment] 2024-08-22 12:22
@rolfbjarne Thanks for taking care, I'm facing the same issue on .NET MAUI iOS.
Any idea when this fix will be available ?

**Comment by rolfbjarne** [comment] 2024-08-22 12:37
> @rolfbjarne Thanks for taking care, I'm facing the same issue on .NET MAUI iOS. Any idea when this fix will be available ?

It will be included in our next service release (which should be within a few weeks).
