### ISSUE TITLE
NU1201 - WatchOSApp is not compatible with xamarinios10

### ISSUE THREAD

**Issue by ThumbGen** [xamarin/xamarin-macios#5878] opened 2019-04-09 12:29 UTC
### Steps to Reproduce

1. Migrate a packages.config iOS project to use PackageReferences
2. Keep the WatchOS project reference as it was:

```xml
<ProjectReference Include="..\bla\bla.WatchOSApp\bla.WatchOSApp.csproj">
      <Project>{5e26a76d-a2ef-465d-81e2-9bf3943395d4}</Project>
      <Name>bla.WatchOSApp</Name>
      <IsAppExtension>false</IsAppExtension>
      <IsWatchApp>true</IsWatchApp>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
</ProjectReference>
```

### Expected Behavior

No errors

### Actual Behavior

> NU1201 - Project bla.WatchOSApp is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x86. Project bla.WatchOSApp supports: xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	bla.iOS		

### Environment

```
Microsoft Visual Studio Enterprise 2019 
Version 16.0.0
VisualStudio.16.Release/16.0.0+28729.10
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA861
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

Application Insights Tools for Visual Studio Package   9.0.20307.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.0.12311.10635
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.0.12311.10635
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.0.12311.10635
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.7000.2
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.0.12311.10635
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.7000.2
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.0.0-beta4-19170-01+1deafee3682da88bf07d1c18521a99f47446cee8
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.77 (master@24013d5)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

Microsoft Azure HDInsight Azure Node   2.3.7000.2
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.7000.2
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.5
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.7000.2
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.0.0

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.0.300 (573eda3)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.10301.2 Commit Hash:9c34eb81d73db6babeb71674feb1cb437dba9f2f
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61903.25110
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.10306.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.0.0-beta4-19170-01+1deafee3682da88bf07d1c18521a99f47446cee8
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.0.0.0.  Commit Hash: 809f41207b74a1356208f11b8fa3a15233734050.
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.0.0.513 (d16-0@aebc6bdb5)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.17.4.413 (remotes/origin/d16-0@db42fb8b0)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.1.43 (fe3ade5)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.2.0.5 (HEAD/292d27fa)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2018-08-rc@5ad371dab1b
    Java.Interop: xamarin/java.interop/d16-0@c987483
    LibZipSharp: grendello/LibZipSharp/master@44de300
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    MXE: xamarin/mxe/xamarin@b9cbb535
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.26.0@325e91a
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6


Xamarin.iOS and Xamarin.Mac SDK   12.6.0.23 (ad57f87)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Example Project (If Possible)

> VS bug [#844539](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/844539)

**Comment by rolfbjarne** [comment] 2019-04-09 12:53
I can reproduce by applying this [diff](https://gist.github.com/rolfbjarne/4529352807943b22265c5cea9239094e) to the watchOS/WatchKitCatalog sample in the [ios-samples](https://github.com/xamarin/ios-samples) repository, and then running nuget restore:

```
$ nuget restore -Verbosity detailed
NuGet Version: 4.8.1.5435
Restoring NuGet packages for solution /work/ios-samples/watchOS/WatchKitCatalog/WatchKitCatalog.sln.
MSBuild auto-detection: using msbuild version '15.0' from '/Library/Frameworks/Mono.framework/Versions/5.20.1/lib/mono/msbuild/15.0/bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
MSBuild P2P timeout [ms]: 120000
/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild "/var/folders/43/h027tm1n101cdrq2_b6n9n2m0000gn/T/NuGetScratch/ivr24jq2.oj7.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="/var/folders/43/h027tm1n101cdrq2_b6n9n2m0000gn/T/NuGetScratch/fw6308ny.cpx.nugetrestore.targets" /p:RestoreUseCustomAfterTargets="True" /p:RestoreTaskAssemblyFile="/Library/Frameworks/Mono.framework/Versions/5.20.1/lib/mono/nuget/nuget.exe" /p:RestoreSolutionDirectory="/work/ios-samples/watchOS/WatchKitCatalog/" /p:SolutionDir="/work/ios-samples/watchOS/WatchKitCatalog/" /p:SolutionName="WatchKitCatalog" /p:RestoreBuildInParallel="False" /p:RestoreUseSkipNonexistentTargets="False"

Running non-parallel restore.
Reading project file /work/ios-samples/watchOS/WatchKitCatalog/WatchKit3Extension/WatchKit3Extension.csproj.
The restore inputs for 'Watchkit2Extension' have not changed. No further actions are required to complete the restore.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: /work/ios-samples/watchOS/WatchKitCatalog/WatchKit3Extension/obj/project.assets.json
No-Op restore. The cache will not be updated. Path: /work/ios-samples/watchOS/WatchKitCatalog/WatchKit3Extension/obj/WatchKit3Extension.csproj.nuget.cache
Restore completed in 29.11 ms for /work/ios-samples/watchOS/WatchKitCatalog/WatchKit3Extension/WatchKit3Extension.csproj.
Reading project file /work/ios-samples/watchOS/WatchKitCatalog/WatchKitCatalog/WatchKitCatalog.csproj.
The restore inputs for 'WatchKitCatalog' have changed. Continuing restore.
Restoring packages for /work/ios-samples/watchOS/WatchKitCatalog/WatchKitCatalog/WatchKitCatalog.csproj...
Restoring packages for Xamarin.iOS,Version=v1.0...
Resolving conflicts for Xamarin.iOS,Version=v1.0...
Scanning packages for runtime.json files...
Restoring packages for Xamarin.iOS,Version=v1.0/win...
Resolving conflicts for Xamarin.iOS,Version=v1.0/win...
Restoring packages for Xamarin.iOS,Version=v1.0/win-x64...
Resolving conflicts for Xamarin.iOS,Version=v1.0/win-x64...
Restoring packages for Xamarin.iOS,Version=v1.0/win-x86...
Resolving conflicts for Xamarin.iOS,Version=v1.0/win-x86...
Checking compatibility of packages on Xamarin.iOS,Version=v1.0.
Checking compatibility for WatchKitCatalog 1.0.0 with Xamarin.iOS,Version=v1.0.
Checking compatibility for WatchApp3 1.0.0 with Xamarin.iOS,Version=v1.0.
Checking compatibility for Watchkit2Extension 1.0.0 with Xamarin.iOS,Version=v1.0.
NU1201: Project Watchkit2Extension is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0). Project Watchkit2Extension supports: xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
Incompatible projects: 1
Checking compatibility of packages on Xamarin.iOS,Version=v1.0 (win).
Checking compatibility for WatchKitCatalog 1.0.0 with Xamarin.iOS,Version=v1.0 (win).
Checking compatibility for WatchApp3 1.0.0 with Xamarin.iOS,Version=v1.0 (win).
Checking compatibility for Watchkit2Extension 1.0.0 with Xamarin.iOS,Version=v1.0 (win).
NU1201: Project Watchkit2Extension is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win. Project Watchkit2Extension supports: xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
Incompatible projects: 1
Checking compatibility of packages on Xamarin.iOS,Version=v1.0 (win-x64).
Checking compatibility for WatchKitCatalog 1.0.0 with Xamarin.iOS,Version=v1.0 (win-x64).
Checking compatibility for WatchApp3 1.0.0 with Xamarin.iOS,Version=v1.0 (win-x64).
Checking compatibility for Watchkit2Extension 1.0.0 with Xamarin.iOS,Version=v1.0 (win-x64).
NU1201: Project Watchkit2Extension is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x64. Project Watchkit2Extension supports: xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
Incompatible projects: 1
Checking compatibility of packages on Xamarin.iOS,Version=v1.0 (win-x86).
Checking compatibility for WatchKitCatalog 1.0.0 with Xamarin.iOS,Version=v1.0 (win-x86).
Checking compatibility for WatchApp3 1.0.0 with Xamarin.iOS,Version=v1.0 (win-x86).
Checking compatibility for Watchkit2Extension 1.0.0 with Xamarin.iOS,Version=v1.0 (win-x86).
NU1201: Project Watchkit2Extension is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x86. Project Watchkit2Extension supports: xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
Incompatible projects: 1
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: /work/ios-samples/watchOS/WatchKitCatalog/WatchKitCatalog/obj/project.assets.json
Writing cache file to disk. Path: /work/ios-samples/watchOS/WatchKitCatalog/WatchKitCatalog/obj/WatchKitCatalog.csproj.nuget.cache
Restore failed in 137.77 ms for /work/ios-samples/watchOS/WatchKitCatalog/WatchKitCatalog/WatchKitCatalog.csproj.

Errors in /work/ios-samples/watchOS/WatchKitCatalog/WatchKitCatalog/WatchKitCatalog.csproj
    NU1201: Project Watchkit2Extension is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0). Project Watchkit2Extension supports: xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
    NU1201: Project Watchkit2Extension is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win. Project Watchkit2Extension supports: xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
    NU1201: Project Watchkit2Extension is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x64. Project Watchkit2Extension supports: xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
    NU1201: Project Watchkit2Extension is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x86. Project Watchkit2Extension supports: xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)

NuGet Config files used:
    /Users/rolf/.config/NuGet/NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json
```

**Comment by ThumbGen** [comment] 2019-04-09 13:00
Any workaround for now?

**Comment by rolfbjarne** [comment] 2019-04-09 13:05
@ThumbGen no idea so far (except not using PackageReferences...)

**Comment by rolfbjarne** [comment] 2019-04-10 06:03
@ThumbGen what exactly are your changes to the csprojs to switch to package references? Can you create a diff (`git diff` or the equivalent for your system)?

I'm using this [diff](https://gist.github.com/rolfbjarne/3137302385689966c32dfb66d0d1be77) for the ios-samples/watchOS/WatchKitCatalog sample, and it works fine.

**Comment by ThumbGen** [comment] 2019-04-10 07:34
I have attached a diff between the original csproj (using packages.config) and what the "Right click on packages.config and choose 'Migrate packages.config to PackageReferences" did.

[diff.zip](https://github.com/xamarin/xamarin-macios/files/3062496/diff.zip)

Note: for the shared .NET Standard 2.0, Android, WatchApp, WatchExtension and UWP apps the migration went well; only the iOS project had this small 'glitch'.

**Comment by rolfbjarne** [comment] 2019-04-10 07:50
I tried to replicate something similar with the WatchKitCatalog sample, but no success, it still works (https://gist.github.com/rolfbjarne/33ec887f7d6f91120d33d0cccc5c7176).

Can you attach your three csproj files? Maybe there's something strange in one of them.

**Comment by ThumbGen** [comment] 2019-04-10 08:01
Attached all 3 projects (the iOS in both versions, with and without packages.config)
[project_files.zip](https://github.com/xamarin/xamarin-macios/files/3062636/project_files.zip)

**Comment by rolfbjarne** [comment] 2019-04-10 12:21
I still can't repro any problems with `nuget restore` on those projects 😒, I updated the ProjectReferences to point to the new locations, and everything restored just fine. Then I removed the `<ReferenceOutputAssembly>false</ReferenceOutputAssembly>` from PTMate.iOS_PackageReference.ccsproj, and the problem showed up.

@ThumbGen can you run the following commands on your Mac (remember to fix the path to your solution):

```
nuget restore -Verbosity detailed  /path/to/mysolution.sln
mono --version
which nuget
```

and attach the output here?

**Comment by ThumbGen** [comment] 2019-04-10 13:06
I am not using Visual Studio for Mac, I am using Visual Studio 2019 on a Windows machine (and build using a remote Mac Mini). 

Could it be that this is only a VS2019/Windows problem?

**Comment by rolfbjarne** [comment] 2019-04-10 13:24
Yes, it could be a VS2019/Windows problem (although usually msbuild/nuget problems usually occur on the Mac and not on Windows).

Can you copy your solution to your Mac and check if the `nuget restore` command works there? That would determine if it's a Windows problem or not.

**Comment by ThumbGen** [comment] 2019-04-10 13:48
I can confirm that using the iOS project having PackageReferences, on a Mac machine, using VStudio 2019 for Mac, it builds without problems.

I have attached the "nuget restore -Verbosity detailed" results.
Mono version 5.18.1.3
Nuget: /library/Frameworks/Mono.framework/Versions/Current/Commands/nuget


[file.zip](https://github.com/xamarin/xamarin-macios/files/3064096/file.zip)

**Comment by rolfbjarne** [comment] 2019-04-10 14:58
Great, thanks, I'll move this to my Windows colleagues then.

**Comment by SebastianKruseWago** [comment] 2019-04-25 11:24
I have the same issue and can confirm it is only a problem on Windows and not on macOS but it also affected VS2017. It works on the mac just fine while Windows keeps failing. 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1201	Project MyApp.iOS.Watch.WatchOSExtension is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x86. Project MyApp.iOS.Watch.WatchOSExtension supports: xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	MyApp.iOS	E:\Git\MyApp\MyApp\MyApp\MyApp.iOS\MyApp.iOS.csproj	1	
Error	NU1201	Project MyApp.iOS.Watch.WatchOSExtension is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0). Project MyApp.iOS.Watch.WatchOSExtension supports: xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	MyApp.iOS	E:\Git\MyApp\MyApp\MyApp\MyApp.iOS\MyApp.iOS.csproj	1	
Error	NU1201	Project MyApp.iOS.Watch.WatchOSExtension is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x64. Project MyApp.iOS.Watch.WatchOSExtension supports: xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	MyApp.iOS	E:\Git\MyApp\MyApp\MyApp\MyApp.iOS\MyApp.iOS.csproj	1	
Error	NU1201	Project MyApp.iOS.Watch.WatchOSExtension is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win. Project MyApp.iOS.Watch.WatchOSExtension supports: xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	MyApp.iOS	E:\Git\MyApp\MyApp\MyApp\MyApp.iOS\MyApp.iOS.csproj	1	

```

**Comment by Dids** [comment] 2019-07-31 12:47
I'm seeing this on macOS, where `nuget restore` fails, while Visual Studio for Mac restores and builds just fine.

**Comment by Dids** [comment] 2019-08-14 05:59
@rolfbjarne Any updates on this? Just a gentle reminder that this is happening on macOS as well, not just on Windows.

**Comment by rolfbjarne** [comment] 2019-08-14 09:49
@Dids if you see this only on macOS, it could be a different issue, so could you please file a new issue with all your details + verbose build logs so that we can have a look? If you have a test solution as well that would be even better.

**Comment by Dids** [comment] 2019-08-14 10:17
@rolfbjarne I should be able to create a small repro and a new issue, but before doing so, I'm just wondering if this is indeed the same issue, as I've manually migrated all projects to use PackageReference?

The errors are exactly the same, and this is a large multi-platform Xamarin.Forms projects, with hundreds of dependencies per project, so I'd definitely prefer not having to rollback, for both speed and maintenance reasons. The migration made a huge impact on both.

Just a quick tl;dr version of the issue: VS4Mac builds fine, and it only throws those errors when building from the command line, which breaks Fastlane automation, CI etc.

**Comment by rolfbjarne** [comment] 2019-08-14 13:41
@Dids if the build works fine from the IDE, but not from the command line, you should be able to compare build logs for the two and see where the difference is.

**Comment by Dids** [comment] 2019-09-17 10:18
@rolfbjarne Sorry for the radio silence. Digging in to the detailed logs this week, but figured I'd update on this in the mean time.

So the issue isn't with building, and everything builds fine in VS4Mac as well as with `msbuild`. The issue comes from NuGet, where `nuget restore` is what's causing the errors, and I'm not yet sure if the only reason this works in VS4Mac, is because I have the packages cached locally, and if it would break in case of a fresh install/restore.

**Comment by rolfbjarne** [comment] 2019-11-27 16:45
See also #7477.

**Comment by rolfbjarne** [comment] 2019-11-27 17:51
The fix is to add `<ReferenceOutputAssembly>false</ReferenceOutputAssembly>` to the project reference in the iOS project's csproj, so that it looks like this:

```xml
      <ProjectReference Include="thewatchapp\thewatchapp.WatchOSApp\thewatchapp.WatchOSApp.csproj">
        <IsWatchApp>true</IsWatchApp>
        <Project>{81724650-5BDE-4259-816A-2FA4F2A4E97D}</Project>
        <Name>thewatchapp.WatchOSApp</Name>
        <ReferenceOutputAssembly>false</ReferenceOutputAssembly> <!-- add this line -->
      </ProjectReference>
```

**Comment by SebastianKruseWago** [comment] 2019-11-28 14:21
@rolfbjarne No it's not. It is already in my *.csproj file and still this error pops up all the time. I always have to remove the references to my iOS extension projects before I can update NuGet packages... it's so annoying...

**Comment by rolfbjarne** [comment] 2019-11-28 16:30
@SebastianKruseWago can you show me your csproj files (all of them)?

**Comment by SebastianKruseWago** [comment] 2019-11-28 16:47
@rolfbjarne Sure, here it is: https://pastebin.com/8YswThyg 

The watchOS App already has the flag you mentioned. I also added it temporarly for the Today Extension because both are throwing this error around but it didn't change anything for me.

**Comment by rolfbjarne** [comment] 2019-11-28 17:25
@SebastianKruseWago can you execute the following in your solution's directory:

```
nuget restore -verbosity detailed
```

and attach the output?

**Comment by SebastianKruseWago** [comment] 2019-11-28 17:28
@rolfbjarne The restore is working fine just when updating the packages this causes issues (which than leads to revert of the update). Even with the error listed in the error window, I can compile and run my app just fine. Will your command generates the required output anyway?

**Comment by rolfbjarne** [comment] 2019-11-28 21:06
@SebastianKruseWago I see above that it only happens on VS (on Windows) for you, in that case the VS team will have to look at it (they already know about this bug, and hopefully they'll have time soon to look into it).

**Comment by ThumbGen** [comment] 2019-12-17 19:10
Could you provide a link to the VStudio issue? Soon will be 1 year since the issue was reported, the problem is still not solved and having the old packages.config format prevents me from installing NuGet packages (e.g. ACR.UserDialogs).

TIA

**Comment by chrisstaley** [comment] 2019-12-31 17:45
I had this issue, and the solution for me was to use a newer version of NuGet.

**Comment by AlejandroRuiz** [comment] 2020-01-10 18:27
I confirm by using nuget version 5.4.0 & adding the ReferenceOutputAssembly property the issue is fixed

**Comment by ThumbGen** [comment] 2020-01-13 15:18
I use 5.4.0 and the ReferenceOutputAssembly property and on VStudio 2019 **for Windows** it still does not work.

**Comment by ThumbGen** [comment] 2020-01-27 12:48
@SebastianKruseWago did you find a solution? Does it work for you now?

**Comment by SebastianKruseWago** [comment] 2020-01-27 12:53
@ThumbGen yea, deleting every iOS extension project reference from my iOS project, update the NuGet packages and readd those references... It's so sad that this issue is now here for about a year and Microsoft does not solve this... But hey, the SplitView issue on iPad is there for 4 years now and not solved yet so why the hurry... x)

**Comment by ThumbGen** [comment] 2020-01-28 09:01
@SebastianKruseWago I think I've might have found a simple way to make it work:

0. Install NuGet 5.4.0 and add the ReferenceOutputAssembly key
1. Unload the WatchOSApp project
2. Migrate from packages.config -> PackageReference for App.iOS project
3. Click "Save all" (I feel the csproj files are not automatically saved)
4. Reload WatchOSApp

For updating packages:
1. Unload the WatchOSApp project
2. Update packages in App.iOS project
3. Reload WatchOSApp

I am now finally having PackageReferences in my App.iOS project.

@rolfbjarne  I guess the issue could be closed.

**Comment by rolfbjarne** [comment] 2020-01-28 13:12
@ThumbGen it shouldn't be necessary to go through those hoops, so there's still something for us to fix (i.e. I prefer to keep this issue open).

**Comment by Sebastian1989101** [comment] 2020-04-11 10:41
Issue is still here... is it really so hard to fix such annoying stuff?

**Comment by Shirk** [comment] 2020-05-11 06:51
> Issue is still here... is it really so hard to fix such annoying stuff?

I'd say not hard (especially since WatchOS apps have their own keys in the PackageReference) but probably just not interesting to any of the devs. Why do a small quality of life fix that barely anyone would notice? 

*sigh*

**Comment by Lydecker** [comment] 2020-06-07 23:51
Hi,

Could someone please explain to me how to resolve this:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1201	Project App1.WatchOSApp is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x64. Project App1.WatchOSApp supports: xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	WatchTest.iOS	C:\Users\za\source\repos\WatchTest\WatchTest\WatchTest.iOS\WatchTest.iOS.csproj	1	
Error	NU1201	Project App1.WatchOSApp is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x86. Project App1.WatchOSApp supports: xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	WatchTest.iOS	C:\Users\za\source\repos\WatchTest\WatchTest\WatchTest.iOS\WatchTest.iOS.csproj	1	
Error	NU1201	Project App1.WatchOSApp is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win. Project App1.WatchOSApp supports: xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	WatchTest.iOS	C:\Users\za\source\repos\WatchTest\WatchTest\WatchTest.iOS\WatchTest.iOS.csproj	1	
Error	NU1201	Project App1.WatchOSApp is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0). Project App1.WatchOSApp supports: xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	WatchTest.iOS	C:\Users\za\source\repos\WatchTest\WatchTest\WatchTest.iOS\WatchTest.iOS.csproj	1
```	



I have already manually modified my main iOS Project file to this:

```
    <ProjectReference Include="..\..\App1\App1.WatchOSApp\App1.WatchOSApp.csproj">
      <Project>{99abb3de-9fcf-47da-93a2-ceb9008e6aa2}</Project>
      <Name>App1.WatchOSApp</Name>
	  <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
	  <IsWatchApp>true</IsWatchApp>
    </ProjectReference>
```

But that does not make the above error go away.

I am using VS2019 on Windows 16.6.1


Xamarin   16.6.000.1061 (d16-6@8e68aa8)
Xamarin Designer   16.6.0.318 (remotes/origin/d16-6@66afc5421)
Xamarin Templates   16.6.40 (1f1466f)
Xamarin.iOS and Xamarin.Mac SDK   13.18.2.1 (29c4ea7)

Thank you!

**Comment by Lydecker** [comment] 2020-06-08 00:04
After hours of trying - it's randomly now working.....

**Comment by SethGibson** [comment] 2020-06-24 00:45
Hi all, just wanted to confirm, the issue still persists in Visual Studio 2019 Community for Windows.
I'm using Version 16.6.2 and have added both the ReferenceOutputAssembly and IsWatchApp nodes to my parent iOS App's .csproj file and am still getting the same error on build or trying to refresh the packages.

**Comment by reznor244** [comment] 2020-07-09 23:22
I have this issue on VS 2019 Enterprise (Windows, v16.6.3, Xamarin iOS 13.18.2.1). My iOS csproj already contains `<ReferenceOutputAssembly>false</ReferenceOutputAssembly>`. I have to use PackageReference because without it, I am unable to update to latest version of Xamarin Essentials (System.Drawing.Common.dll not found in GAC error).

Should the WatchExtension project be migrated to PackageReference / would that cause any harm?

**Comment by jandroalvarez** [comment] 2021-12-02 08:05
Hello,

Is this issue dead? I' suffering this problem, too.
It only works on VS for Mac.

I've added the `<ReferenceOutputAssembly>false</ReferenceOutputAssembly>` flag to the iOS csproj file but the problem persists.

My toolkit:
- Visual Studio 2019 16.11.7
- Xamarin iOS 15.2.0.17
- Nuget 5.11.1.5

**Comment by Shirk** [comment] 2022-05-05 13:35
So.. was this fixed or are we just closing it and shoving it under the carpet?

**Comment by rhodesie123** [comment] 2022-05-11 15:26
my iOS app was an old-school csproj project, however, I had a packages.config file in the iOS app directory which was causing the problem. I removed it and it fixed the issue. This was outlined here:

https://stackoverflow.com/questions/51454874/nuget-restore-fails-nu1201-for-net-standard-referencing-net-framework

Hope this helps..

**Comment by Edder** [comment] 2022-05-17 09:35
Still exists with VS Community 2022 17.0.4 and Xamarin iOS 15.4,

**Comment by mariaghiondea** [comment] 2022-05-19 17:44
This item has been open for a while and we weren’t able to prioritize it over other higher impact issues we received, based on the votes and comments from others in the community and our understanding of the issue. 
Based on that, our current and future priorities in this area and others, I’m closing it since the chances of it becoming high enough in priority for a fix in the future are very low. 
I understand that may be disappointing, but I don’t want to create false hopes.

**Comment by mariaghiondea** [comment] 2022-05-19 17:45
This item has been open for a while and we weren’t able to prioritize it over other higher impact issues we received, based on the votes and comments from others in the community and our understanding of the issue. 
Based on that, our current and future priorities in this area and others, I’m closing it since the chances of it becoming high enough in priority for a fix in the future are very low. 
I understand that may be disappointing, but I don’t want to create false hopes.

**Closed by mariaghiondea** 2022-05-19 17:45 UTC
Labels: bug, iOS, external-xamarin-vs
