### ISSUE TITLE
PKIssuerProvisioningExtensionHandler constructor issue

### ISSUE THREAD

**Issue by xtremal** [xamarin/xamarin-macios#19030] opened 2023-09-14 14:10 UTC
**Issue description:**
When the iOS Wallet app tries to initialize the **Issuer Bank App** wallet extension macOS console logs the following exception:
```
Unhandled Exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'System.HashCode' threw an exception. ---> System.EntryPointNotFoundException: SystemNative_GetNonCryptographicallySecureRandomBytes
  at Interop.GetRandomBytes (System.Byte* buffer, System.Int32 length) <0x107e54730 + 0x00018> in <a397f8ddf5cc4340b1b7367e6ca02e39>:0 
  at System.HashCode.GenerateGlobalSeed () <0x107ea9c60 + 0x00017> in <a397f8ddf5cc4340b1b7367e6ca02e39>:0 
  at System.HashCode..cctor () <0x107eaab60 + 0x0000b> in <a397f8ddf5cc4340b1b7367e6ca02e39>:0 
   --- End of inner exception stack trace ---
  at ObjCRuntime.IntPtrTypeValueTuple.GetHashCode () <0x108b85bb0 + 0x00038> in <b6aba114965e42fd86853d6518410032>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) <0x108c16880 + 0x000c7> 10388 in <a397f<…>

Unhandled managed exception: Exception has been thrown by the target of an invocation. (System.Reflection.TargetInvocationException)
The type initializer for 'System.HashCode' threw an exception. (System.TypeInitializationException)
  at ObjCRuntime.IntPtrTypeValueTuple.GetHashCode () <0x108b85bb0 + 0x00038> in <b6aba114965e42fd86853d6518410032>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) <0x108c16880 + 0x000c7> 10388 in <a397f8ddf5cc4340b1b7367e6ca02e39>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].set_Item (TKey key, TValue value) <0x108c0cce0 + 0x0002f> 10102 in <a397f8ddf5cc4340b1b7367e6ca02e39>:0 
  at ObjCRuntime.Runtime.GetDelegateForBlock (System.IntPtr methodPtr, System.Type type) <0x108b7ad60 + 0x0021f> in <b6aba114965e42fd86853d6518410032>:0 
  at ObjCRuntime.BlockLiteral.GetDelegateForBlock[T] () <0x108b7fa60 + 0x0002f> in <b6aba114965e42fd86853d6518410032>:0 
  at Ob<…>
```

`PKIssuerProvisioningExtensionHandler` implementation to reproduce the issue.
```
using Foundation;
using PassKit;
using System;
using System.Collections.Generic;

namespace IssuerBankApp.iOS.WalletExtension
{
  [Register("ProvisioningHandler")]
  public class ProvisioningHandler : PKIssuerProvisioningExtensionHandler
  {
    protected internal ProvisioningHandler(IntPtr handle) : base(handle)
    {
    }
    public override void GetStatus(Action<PKIssuerProvisioningExtensionStatus> completion)
    {
      completion(new PKIssuerProvisioningExtensionStatus()
      {
        RequiresAuthentication = true,
        PassEntriesAvailable = true,
        RemotePassEntriesAvailable = true,
      });
    }
    public override void PassEntries(Action<PKIssuerProvisioningExtensionPassEntry[]> completion)
    {
      var result = new List<PKIssuerProvisioningExtensionPassEntry>();
      completion(result.ToArray());
    }
    public override void RemotePassEntries(Action<PKIssuerProvisioningExtensionPassEntry[]> completion)
    {
      var result = new List<PKIssuerProvisioningExtensionPassEntry>();
      completion(result.ToArray());
    }
    public override void GenerateAddPaymentPassRequest(string identifier, PKAddPaymentPassRequestConfiguration configuration, NSData[] certificates, NSData nonce, NSData nonceSignature, Action<PKAddPaymentPassRequest> completion)
    {
      completion(null);
    }
  }
}
```

As far as I see the issue is in the `PKIssuerProvisioningExtensionHandler.PKIssuerProvisioningExtensionHandler(IntPtr handle)` constructor. 
When i try to implement the class with the other constructor `PKIssuerProvisioningExtensionHandler.PKIssuerProvisioningExtensionHandler(NSObjectFlag t)` macOS console is not logging the exception, nether the iOS Wallet app shows the **Issuer Bank App**.

### Steps to Reproduce
1. Create a sample Xamarin.iOS project (**Issuer Bank App**). 
2. Add iOS Intents Extension to the project. 
3. Implement PKIssuerProvisioningExtensionHandler according to [apple docs](https://developer.apple.com/documentation/passkit/pkissuerprovisioningextensionhandler).
4. Deploy the iOS app (**Issuer Bank App**) to device in sandbox mode.
5. Open iOS wallet app and try to fetch the available cards.

### Expected Behavior
iOS wallet app shows **Issuer Bank App**
![image](https://github.com/xamarin/xamarin-macios/assets/31212256/2e7b4ae8-ec22-4c57-8cca-b58d4d5dc3a9)

### Actual Behavior
iOS wallet app is not showing **Issuer Bank App**

### Environment
Sandbox

<details>
<summary>Version information</summary>

```
Microsoft Visual Studio Community 2022
Version 17.7.3
VisualStudio.17.Release/17.7.3+34024.191
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA942
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.7.273.65229
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.7.273.65229
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.7.273.65229
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.7.0-3.23416.8+43b0b05cc4f492fd5de00f6f6717409091df8daa
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.4.34 (main@d5ab18b)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.7.27 (547ea6f)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.7.3.2333001+0ab18affdf2a37647768d0e25f5f021bee6257a1
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.7.10.1
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.20628.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.7.0-3.23416.8+43b0b05cc4f492fd5de00f6f6717409091df8daa
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.7.0-beta.23314.10+e612cf93b989503c89e3a5830090062b7ab5e143
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.7.0.216 (d17-7@133ddef)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.7.3.9 (remotes/origin/d17-7@796d191def)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.7.21 (150ec9f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.1.2 (d17-5/a8a26c7)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d


Xamarin.iOS and Xamarin.Mac SDK   16.4.0.15 (8c3876d5e)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Build Logs
N/A

**Comment by rolfbjarne** [comment] 2023-09-14 14:15
Could you please zip up and attach the complete test solution you've used to reproduce this? That would greatly speed up any diagnosis on our side, as well as making sure we're testing the same thing.

**Comment by xtremal** [comment] 2023-09-15 11:44
Unfortunately I cannot provide

**Comment by xtremal** [comment] 2023-09-15 11:49
Unfortunately I am not able to upload the solution here. I will try to prepare a demo one. Meanwhile are the any example for a proper PKIssuerProvisioningExtensionHandler implementation?

**Comment by rolfbjarne** [comment] 2023-09-15 12:00
> I will try to prepare a demo one. Meanwhile are the any example for a proper PKIssuerProvisioningExtensionHandler implementation?

Unfortunately no, it's the first time I've heard about anyone trying this, and we don't have any example code (probably because you need a special entitlement from Apple to ship such an extension).

Marking as `need-info` until we have a repro project.

**Comment by N-ihad** [comment] 2023-09-18 18:16
guys anything new? stumbled upon this same issue of my app not showing in the list in apple wallet

**Comment by rolfbjarne** [comment] 2023-09-18 21:44
> guys anything new? stumbled upon this same issue of my app not showing in the list in apple wallet

It would be great if you could provide a test project we could use to reproduce this, then we'll be able to investigate.

**Comment by rolfbjarne** [comment] 2023-09-21 08:16
I see the app has the `com.apple.developer.payment-pass-provisioning` requirement, is this necessary to reproduce the problem? Because that entitlement needs a special permission from Apple to get

**Comment by xtremal** [comment] 2023-09-21 08:46
Yes, it is necessary. My real app has permission for this entitlement. 
I am not sure what the procedure is for obtaining this permission from Apple for development purposes.

**Comment by xtremal** [comment] 2023-09-25 12:51
I am not allowed to upload the app bundle here, however if you want I can send it to you via email or other type of private communication.

**Comment by IharStrekha** [comment] 2023-10-01 21:47
@xtremal  hello. How can I write some message to you? I have some issues with this extension.

**Comment by xtremal** [comment] 2023-10-02 05:39
Hi @IharStrekha. I'm also having issues with the extension. I think it is better to describe the problems here publicly so that we can solve them collaboratively.

**Comment by IharStrekha** [comment] 2023-10-02 07:04
@xtremal I tried to implement with my friend on native code (swift). We spent yesterday 5h. And nothing. I think we have a problem on Issuer side.

I saw your code. first look - good. As we have. But did you add your bundle Ids to associatedApplicationIdentifiers in the PNO metadata?

**Comment by xtremal** [comment] 2023-10-02 08:01
I don't have access to the PNO settings, but as far as I know bundle IDs for the extensions (UI and NonUI) are added to associatedApplicationIdentifiers in PNO metadata.
I want to point that it is absolutely mandatory to follow the pattern "[teamId].[app-bundle-id].[extension]"
eg:
_A1B2C3D4E5.com.issuerbank.app_ - bundle ID of the app
_A1B2C3D4E5.com.issuerbank.app.provisioningExtension_ - bundle ID of the non ui extension (required)
_A1B2C3D4E5.com.issuerbank.app.authExtension_ - bundle ID of the ui extension (non-required)

What was your approach in swift - you have created a swift framework and then a xamarin ios binding library?

**Comment by IharStrekha** [comment] 2023-10-02 09:06
@xtremal  today we will continue work on it  (native app lvl). Why we decide to choose implement  it on native code? Cause many settings (like group, PNO data , three bundle Ids and more) dont related to the code into app. Firsly we wanna  get success on native app. If you want please connect to my skype: spikaa1

**Comment by IharStrekha** [comment] 2023-10-03 10:59
@xtremal we implemented it using native code. But I am trying to do the same on Xamarin side. I think the constructor really does not work.

**Comment by IharStrekha** [comment] 2023-10-04 15:43
@xtremal  I have implemented it on Xamarin.forms

**Comment by xtremal** [comment] 2023-10-04 15:51
Could you please share what was your solution for the problem with the constructor?

**Comment by IharStrekha** [comment] 2023-10-05 07:07
> Could you please share what was your solution for the problem with the constructor?

I can help you via skype.  Cannot write coause some internal problems maybe

**Comment by rolfbjarne** [comment] 2023-10-17 10:09
Were you able to make it work?

If not, you can send private attachment like this (re: https://github.com/xamarin/xamarin-macios/issues/19030#issuecomment-1729571699):

* Create a new feedback ticket here, stating that you're just providing private information to this issue (include the link to this issue): https://developercommunity.visualstudio.com/VisualStudioMac/report
* Once the feedback ticket has been created, you can add private attachments.
* Add a link to the feedback ticket here, so that we can connect them.

**Closed** 2023-10-25 00:11 UTC
Labels: need-info
