### ISSUE TITLE
StoreKit2 (Swift-API) Support

### ISSUE THREAD

**Issue by richaplinvs** [xamarin/xamarin-macios#20807] opened 2024-07-03 09:04 UTC
Now that [StoreKit 1](https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase) has been deprecated. We need official support for [StoreKit 2](https://developer.apple.com/documentation/storekit/in-app_purchase).

I see from [this issue](https://github.com/xamarin/xamarin-macios/issues/6239) that Swift-APIs are planned to be support but there's no timeline or specific mention of StoreKit2.

**Comment by rolfbjarne** [comment] 2024-07-03 12:32
Closing as a duplicate of #16893.

**Closed by rolfbjarne** 2024-07-03 12:32 UTC
