### ISSUE TITLE
Dyn invoked method with too many / too large parameters throw ExecutionEngineException on device

### ISSUE THREAD

**Issue by taikodragon** [xamarin/xamarin-macios#4635] opened 2018-08-16 23:51 UTC
### Steps to Reproduce

1. `git clone https://github.com/taikodragon/AppBug59184`
2. Open AppBug59184.sln in Visual Studio for Mac.
4. Build and run the application in the "Debug|iPhone" configuration.

### Expected Behavior
See this bug for historic details: https://bugzilla.xamarin.com/show_bug.cgi?id=59184
Each test should insert one row into each table.
### Actual Behavior
The first four work properly. Which demonstrates the fix the linked bug, but a mixed database object will cause the same behavior to resurface.

When trying to add a record to the fifth table (BuggedLargerNullableEntities) EFCore will cause an System.ExecutionEngineException while trying to dynamically invoke the constructor of it's Snapshot internal class.

Exception info: https://gist.github.com/taikodragon/ca8888a037bad4369e564b7c5043bcd7

### Environment

```
=== Visual Studio Professional 2017 for Mac ===

Version 7.5.4 (build 7)
Installation UUID: 0e6e8824-59be-4998-8a54-99bf6eb9fa7e
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.193 (master / 64fece5f)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.1
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.301/Sdks
SDK Versions:
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 10.0 (14320.12.2)
Build 10L232m

=== Xamarin.Mac ===

Version: 4.99.2.250 (Visual Studio Professional)

=== Xamarin.iOS ===

Version: 11.99.2.130 (Visual Studio Professional)
Hash: 86e97b10
Branch: HEAD
Build date: 2018-08-04 01:01:50-0400

=== Xamarin.Android ===

Version: 9.0.0.17 (Visual Studio Professional)
Android SDK: /Users/RES/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.4   (API level 19)
		5.0   (API level 21)
		6.0   (API level 23)
		7.1   (API level 25)
		8.1   (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705040007
Git revision: 1fcae95fd5b606f806c3b1d445237f675c395fdd
Build date: 2018-08-02 18:48:50+00
Xamarin addins: 48a82b251ec0ef78cb92223061ea448f967f4ec2

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.5.3
```

### Build Logs

https://gist.github.com/taikodragon/fb6333588f993e34b1b2f0ebd346e34e

### Example Project (If Possible)

https://github.com/taikodragon/AppBug4635
Tested on a iPod Touch (6th generation), iPad (5th generation) using iOS 11.4.1
Tested using VSMac Beta, Alpha, and XCode 10 channels.
Test project requires the use of VS4Mac v7.6 (build 2190) or newer.

**Comment by mandel-macaque** [comment] 2018-08-17 12:18
Thanks for the bug report and the sample, will test and will get back to you ASAP with more information.

**Comment by mandel-macaque** [comment] 2018-08-20 09:47
Hello, 

While trying to confirm the bug I got the following issues when restoring the nuget packages:

> Running non-parallel restore.
> Reading project file /Users/mandel/Xamarin/issue-projects/AppBug59184/AppBug59184/AppBug59184.iOS/AppBug59184.iOS.csproj.
> Restoring packages for /Users/mandel/Xamarin/issue-projects/AppBug59184/AppBug59184/AppBug59184.iOS/AppBug59184.iOS.csproj...
> Restoring packages for .NETFramework,Version=v4.0...
> Resolving conflicts for .NETFramework,Version=v4.0...
> Checking compatibility of packages on .NETFramework,Version=v4.0.
> Checking compatibility for AppBug59184.iOS 1.0.0 with .NETFramework,Version=v4.0.
> Checking compatibility for Xamarin.Forms 3.1.0.697729 with .NETFramework,Version=v4.0.
> Package Xamarin.Forms 3.1.0.697729 is not compatible with net40 (.NETFramework,Version=v4.0). Package Xamarin.Forms 3.1.0.697729 supports:
>   - monoandroid10 (MonoAndroid,Version=v1.0)
>   - netstandard1.0 (.NETStandard,Version=v1.0)
>   - netstandard2.0 (.NETStandard,Version=v2.0)
>   - tizen40 (Tizen,Version=v4.0)
>   - uap10.0 (UAP,Version=v10.0)
>   - xamarinios10 (Xamarin.iOS,Version=v1.0)
>   - xamarinmac (Xamarin.Mac,Version=v0.0)
> Checking compatibility for AppBug59184 1.0.0 with .NETFramework,Version=v4.0.
> Project AppBug59184 is not compatible with net40 (.NETFramework,Version=v4.0). Project AppBug59184 supports: netstandard2.0 (.NETStandard,Version=v2.0)
> Incompatible projects: 1
> Incompatible packages: 1
> Committing restore...
> Generating MSBuild file /Users/mandel/Xamarin/issue-projects/AppBug59184/AppBug59184/AppBug59184.iOS/obj/AppBug59184.iOS.csproj.nuget.g.props.
> Generating MSBuild file /Users/mandel/Xamarin/issue-projects/AppBug59184/AppBug59184/AppBug59184.iOS/obj/AppBug59184.iOS.csproj.nuget.g.targets.
> Writing lock file to disk. Path: /Users/mandel/Xamarin/issue-projects/AppBug59184/AppBug59184/AppBug59184.iOS/obj/project.assets.json
> Writing cache file to disk. Path: /Users/mandel/Xamarin/issue-projects/AppBug59184/AppBug59184/AppBug59184.iOS/obj/AppBug59184.iOS.csproj.nuget.cache
> Restore failed in 25.78 ms for /Users/mandel/Xamarin/issue-projects/AppBug59184/AppBug59184/AppBug59184.iOS/AppBug59184.iOS.csproj.
> 
> NuGet Config files used:
>     /Users/mandel/.config/NuGet/NuGet.Config
> 
> Feeds used:
>     http://nuget.grapecity.com/nuget/
>     https://www.nuget.org/api/v2/
> Restore failed.

 Could you please take a look at the project from the provided github url and confirm that it works. My testing environment is the following [one](https://gist.github.com/mandel-macaque/5aa98347111d2b551d4103d0bec3d125).

**Comment by taikodragon** [comment] 2018-08-21 22:01
I've created a simplified project to ease testing here: https://github.com/taikodragon/AppBug4635
The new repo is using only Xamarin.iOS and EFCore 2.1.1.

I did notice in your logs that Nuget appears to be restoring for `.NETFramework,Version=v4.0` which is not correct for the target project. It should be restoring for `Xamarin.iOS,Version=v1.0`

**Comment by taikodragon** [comment] 2018-08-28 15:13
I'm sorry to bump this issue, but this is a blocking issue for the project I'm working on. I will have to abandon EFCore if a solution cannot be found soon.

**Comment by rolfbjarne** [comment] 2018-09-07 09:00
I can reproduce this with the test project (thanks!), and it seems to be a duplicate of https://github.com/xamarin/xamarin-macios/issues/4749 (which has been moved to https://github.com/mono/mono/issues/10483).

**Closed by rolfbjarne** 2018-09-07 09:00 UTC
Labels: iOS, need-info
