### ISSUE TITLE
Urgent - Error signing AdHoc or AppStore iOS Archive

### ISSUE THREAD

**Issue by DaleMagrath** [xamarin/xamarin-macios#10141] opened 2020-11-23 21:06 UTC
### Steps to Reproduce

1. Build iOS app in Release mode
2. Archive
3. Distribute the Archive and Choose Adhoc
4.  Select the correct Provisioning Profile and Certificate

### Expected Behavior
The Archive is successfully signed for Distribution
### Actual Behavior
An error occurs when signing.  This started happening when upgrading to VS 2019 16.8.2 on Windows and VS 2019 8.8.1 build 37 for Mac.  The Xamrin.iOS.SDK versions are not the same.

Mac - 14.6.0.15
Windows - 14.4.1.3

When pairing to the Mac it gave a compatability warning and I had to downgrade the MAc version to match the Windows version.  After that it paired but would not sign the archive anymore.

This is an urgent issue for us as we need to release to the App Store by 11/27/2020.

Begining distribution, 11/23/2020 4:38:44 PM
Channel: Ad Hoc
App Bundle Id: com.changepoint.mobile2, Version: 3.00.038
Publishing to 'C:\iOS\Archives\signed-ipa\Changepoint.Mobile.ipa'
The underlying client has been disconnected by the remote host
The underlying client has been disconnected by the remote host
An error occurred while registering a handler for 'AgentStatusMessage' messages, so all the content sent to the topic 'xma/agent-status' will not be handled in this active connection
An error occurred while registering a handler for 'ClientStatusMessage' messages, so all the content sent to the topic 'xma/client-status' will not be handled in this active connection
An error occurred while registering a handler for 'PingMessage' messages, so all the content sent to the topic 'xma/ping/{ClientId}' will not be handled in this active connection
Could not create ipa file for distribution of the archive 'Changepoint.Mobile'
No iOS signing identities match the specified provisioning profile 'XC iOS Ad Hoc: com.changepoint.mobile2'.
        

Publishing project 'Changepoint.Mobile' completed with errors.
Could not create ipa file for distribution of the archive 'Changepoint.Mobile'
No iOS signing identities match the specified provisioning profile 'XC iOS Ad Hoc: com.changepoint.mobile2'.
### Environment

Also using XCode 12.2
```
Microsoft Visual Studio Professional 2019
Version 16.8.2
VisualStudio.16.Release/16.8.2+30717.126
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Professional

ASP.NET and Web Tools 2019   16.8.553.28003
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.553.28003
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.553.28003
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.8.553.28003
Azure Functions and Web Jobs Tools

Bundler & Minifier   2.8.396
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

C# Tools   3.8.0-5.20567.16+53c5d7d3cf13d88978744a32a27c5f8350a8400a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Chutzpah Context Menu   4.4.9
Enables you to run JavaScript unit tests via Chutzpah from the context menu

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.8.20241.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

CSS Tools 2019   1.1.4
Provides additional features to the CSS editor in Visual Studio.

EditorConfig Language Service   1.17.284
Language service for .editorconfig files.

EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

File Icons   2.7
Adds icons for files that are not recognized by Solution Explorer

File Nesting   2.6.85
Automatically nest files based on file name and enables developers to nest and unnest any file manually

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper Ultimate 2019.2.2   Build 192.0.20190828.114715
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2020 JetBrains, Inc.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

PowerShell Pro Tools for Visual Studio   1.0
A set of tools for developing and debugging PowerShell scripts and modules in Visual Studio.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.8.20241.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.8.20241.2
Conda support for Python projects.

Python - Django support   16.8.20241.2
Provides templates and integration for the Django web framework.

Python - IronPython support   16.8.20241.2
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.8.20241.2
Profiling support for Python projects.

ReAttach   2.3
Gives you an easy way to ReAttach to prior debugging targets. For more information, see https://marketplace.visualstudio.com/items?itemName=ErlandR.ReAttach.

ResXManager   1.48.3862.0
Manage localization of all ResX-Based resources in one place. Shows all resources of a solution and let's you edit the strings and their localizations in a well-arranged data grid.

SQL Server Data Tools   16.0.62010.06180
Microsoft SQL Server Data Tools

Syncfusion Xamarin Project Templates   13.4.0.53
A multi-project template for building iOS, Android, and Windows apps using Syncfusion Xamarin components.

Syncfusion Xamarin Toolbox   16.2.0.19
Syncfusion Essential Studio for Xamarin Toolbox Visual Studio extension.

SyncfusionMenu Extension   1.0
SyncfusionMenu Visual Studio Extension Detailed Info

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20567.16+53c5d7d3cf13d88978744a32a27c5f8350a8400a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.255 (d16-8@d002176)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.17 (d16-8/c0e2b8e)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: be2226b
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc


Xamarin.iOS and Xamarin.Mac SDK   14.4.1.3 (e30c41de3)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

XamRight   2.22
Program analysis and refactoring tools for Xaml


=== Visual Studio Community 2019 for Mac ===

Version 8.8.1 (build 37)
Installation UUID: 5900d877-168c-4cb2-8fce-f02d6cddbcad
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

=== Roslyn (Language Service) ===

3.8.0-5.20515.7+713efb0e68d34ab75faaf709e071e5c2d8d4ed0e

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.100/Sdks
SDK Versions:
	5.0.100
	3.1.402
	2.1.701
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.0
	3.1.8
	2.1.23
	2.1.12

=== .NET Core 3.1 SDK ===

SDK: 3.1.402

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.2 (17535)
Build 12B45b

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.4.1.3 (Visual Studio Community)
Hash: e30c41de3
Branch: d16-8
Build date: 2020-10-20 22:18:50-0400

=== Xamarin Designer ===

Version: 16.8.0.507
Hash: e87b24884
Branch: remotes/origin/d16-8
Build date: 2020-10-29 00:31:38 UTC

=== Xamarin.Android ===

Not Installed

=== Microsoft OpenJDK for Mobile ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:30 UTC

=== Android Device Manager ===

Version: 16.8.0.45
Hash: fc0af5f
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:54 UTC

=== Build Information ===

Release ID: 808010037
Git revision: acd8ddc086768c701bd641d6ec27316f45813175
Build date: 2020-11-17 12:49:41-05
Build branch: release-8.8
Xamarin extensions: acd8ddc086768c701bd641d6ec27316f45813175

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.1.0 Darwin Kernel Version 20.1.0
    Sat Oct 31 00:07:11 PDT 2020
    root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64


```

### Build Logs

Begining distribution, 11/23/2020 4:38:44 PM
Channel: Ad Hoc
App Bundle Id: com.changepoint.mobile2, Version: 3.00.038
Publishing to 'C:\iOS\Archives\signed-ipa\Changepoint.Mobile.ipa'
The underlying client has been disconnected by the remote host
The underlying client has been disconnected by the remote host
An error occurred while registering a handler for 'AgentStatusMessage' messages, so all the content sent to the topic 'xma/agent-status' will not be handled in this active connection
An error occurred while registering a handler for 'ClientStatusMessage' messages, so all the content sent to the topic 'xma/client-status' will not be handled in this active connection
An error occurred while registering a handler for 'PingMessage' messages, so all the content sent to the topic 'xma/ping/{ClientId}' will not be handled in this active connection
Could not create ipa file for distribution of the archive 'Changepoint.Mobile'
No iOS signing identities match the specified provisioning profile 'XC iOS Ad Hoc: com.changepoint.mobile2'.
        

Publishing project 'Changepoint.Mobile' completed with errors.
Could not create ipa file for distribution of the archive 'Changepoint.Mobile'
No iOS signing identities match the specified provisioning profile 'XC iOS Ad Hoc: com.changepoint.mobile2'.

**Comment by dalexsoto** [comment] 2020-11-23 22:19
Hello @DaleMagrath thanks for reaching out!

The new version of Xamarin.iOS will be available in the next release of Visual Studio for Windows, due to unfortunate circumstances it could not be released at the same time as in VSMac, that said you have two options here

1) Update to stable using VSMac in your Mac host and when Visual Studio for windows asks you to upgrade you can hit cancel to the dialog, IIRC it should connect after that and now you can try to do the release.

2) Update to latest stable on the VSMac build host and open your project on it and do the build and archiving using VSMac.

The second one should unblock you in case 1) does not.

Thank you!

**Comment by DaleMagrath** [comment] 2020-11-24 00:41
unfortunately neither solution worked.
Copied my entire solution folder to the host Mac.  opened it in VS Mac and it fails to build the iOS project in either debug or Release with an unknown MSBuild failure.
I appreciate you not closing a ticket until you get feedback from the person reporting the issue

**Comment by dalexsoto** [comment] 2020-11-24 15:01
Thank you for your response feel free to re-open the issue if it is not resolved for you, as for VSMac for us to investigate this further, could you please provide your full build logs, crash reports (if any), test case (to reproduce) and all your version information.

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

We look forward to hearing from you!

**Comment by dalexsoto** [comment] 2020-11-24 15:02
As for windows, @emaf would you have any suggestions?

**Comment by emaf** [comment] 2020-11-24 19:33
Hi @DaleMagrath, from the information you attached it seems the provisioning information is not found because the build is getting disconnected from your Mac, but we'd need a binary log to confirm this and understand why this is happening.

To get a binary log from that run you should do the following:

1. Install the Project System Tools extension from the Extension Manager (https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools)
2. Open the Build Logging window from `View > Other Windows > Build Logging` and then start logging by clicking on the play button on that window.
3. Reproduce the error your facing when trying to distribute your project
4. Switch back to the Build Logging window 
5. Right-click on the entry with the value `CreateIpa` on the targets column and save the log

Thanks!

**Comment by DaleMagrath** [comment] 2020-11-24 23:01
> Hi @DaleMagrath, from the information you attached it seems the provisioning information is not found because the build is getting disconnected from your Mac, but we'd need a binary log to confirm this and understand why this is happening.
> 
> To get a binary log from that run you should do the following:
> 
> 1. Install the Project System Tools extension from the Extension Manager (https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools)
> 2. Open the Build Logging window from `View > Other Windows > Build Logging` and then start logging by clicking on the play button on that window.
> 3. Reproduce the error your facing when trying to distribute your project
> 4. Switch back to the Build Logging window
> 5. Right-click on the entry with the value `CreateIpa` on the targets column and save the log
> 
> Thanks!

Hi @emaf 
I'll see what I can get.  However wouldn't this mean that I could not build not archive?
I can build, archive, and run the simulator from Windows machine to the Mac host.  I just can't sign it for Distribution
It finds the profile and certificate to build it.
The last time this happened was under the same circumstance I believe.  Mac and Windows versions of Xasmarin.ios.SDK were out of sync.  I'm hoping when VS 2019 16.8.3 release will fix this versioning issue
Would you have any idea when they are releasing?  Usually a weekly cycle

**Comment by emaf** [comment] 2020-11-25 13:14
@DaleMagrath, when distributing VS is essentially running some MSBuild targets but it isn't a regular build. I'm assuming there's a problem with the specific targets for distribution that won't run on a regular build or archive. I've been trying to reproduce it locally but unfortunately it's working for me.

Regarding the SDK mismatch, have you installed a different version of Xamarin.iOS than the one VS installs from Windows? I know VSM is installing a newer version

**Comment by DaleMagrath** [comment] 2020-11-25 18:17
> @DaleMagrath, when distributing VS is essentially running some MSBuild targets but it isn't a regular build. I'm assuming there's a problem with the specific targets for distribution that won't run on a regular build or archive. I've been trying to reproduce it locally but unfortunately it's working for me.
> 
> Regarding the SDK mismatch, have you installed a different version of Xamarin.iOS than the one VS installs from Windows? I know VSM is installing a newer version

@emaf 
I installed Windows VS 2019 16.8.2 and Mac VS 2019 8.8.1  They are currently out of sync with the Mac having a newer version of the SDK which is causing the issues

**Comment by rms81** [comment] 2020-11-29 18:24
Hi. when will be VS versions in sync again?
Thank you

**Comment by emaf** [comment] 2020-11-30 17:23
Closing this issue since it's already being tracked here https://developercommunity2.visualstudio.com/t/Unable-to-Pair-to-Mac-nor-Sign-iOS-Archi/1262512

**Closed by emaf** 2020-11-30 17:23 UTC
Labels: iOS, support
