### ISSUE TITLE
Cannot create an instance of UserNotifications.UNNotificationTrigger on 'get'

### ISSUE THREAD

**Issue by rihadavid** [xamarin/xamarin-macios#3935] opened 2018-04-13 10:01 UTC
### Steps to Reproduce

1. Schedule this UILocalNotification:

       UILocalNotification notification = new UILocalNotification
       {
            FireDate = ((NSDate)DateTime.Now).AddSeconds(30),
            RepeatInterval = NSCalendarUnit.Minute,
            SoundName = "SomeSound.mp3",
            AlertBody = "this is UILocalNotification"
       };
       UIApplication.SharedApplication.ScheduleLocalNotification(notification);

2. Get pending UNNotifications, it contains the scheduled UILocalNotification, now in the form of UNNotificationRequest.

       var pending = await UNUserNotificationCenter.Current.GetPendingNotificationRequestsAsync();

3. Access the .Trigger property

       var trigger = pending[0].Trigger;

4. Error is thrown:
`Cannot create an instance of UserNotifications.UNNotificationTrigger because it is an abstract class`

### Expected Behavior

I should be able to access the property Trigger without an error.

### Actual Behavior

I can't access the property, always throws error.

### Note
It is probably related to the fact, that UNNotifications have no way to set the trigger to "fire after this interval and then repeat in another interval", which UILocalNotifications had. But the UILocalNotification still works in iOS 11, so Apple is probably using some non-public subclass of UNNotificationTrigger that Xamirin is not able to handle.

Also note, that the error is not thrown if in the first step I schedule UNNotification instead of UILocalNotification.

I am not sure, whether this is a Xamarin bug or an iOS bug, but could you guys please look at this?

The reason why I am doing this is because I need exactly that type of UNNotificationTrigger that only UILocalNotification can have, so I was thinking I would create the UILocalNotification and then pass its trigger to a new UNNotification.

### Environment
Microsoft Visual Studio Community 2017 
Version 15.6.5
VisualStudio.15.Release/15.6.5+27428.2027
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

Visual F# Tools 10.1 for F# 4.1   00369-60000-00001-AA614
Microsoft Visual F# Tools 10.1 for F# 4.1

Application Insights Tools for Visual Studio Package   8.11.10212.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40314.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.51214.0
For additional information, visit https://www.asp.net/

AWS Toolkit for Visual Studio 2017   1.14.2.0
AWS Toolkit for Visual Studio 2017.
Copyright 2011-2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Release notes: https://aws-vs-toolkit.s3.amazonaws.com/versioninfo.html

This software includes third party software subject to the following copyrights:
- Logging from log4net, Apache License 
  [http://logging.apache.org/log4net/license.html]
- Putty for PPK to PEM conversion, MIT license 
  [http://www.chiark.greenend.org.uk/~sgtatham/putty/licence.html]
- NGit for AWS Elastic Beanstalk incremental push
  [https://github.com/mono/ngit/blob/master/NGit.license.txt]
- NSch dependency for NGit
  [https://github.com/mono/ngit/blob/master/NSch.license.txt]
- Sharpen dependency for NGit
  [https://github.com/mono/ngit/blob/master/Sharpen/AssemblyInfo.cs]
- ICSharpCode.SharpZipLib dependency for NGit
  [http://www.icsharpcode.net/opensource/sharpziplib/]
- Mono.Posix.dll and Mono.Security.dll dependencies for NGit
  [http://mono-project.com/FAQ:_Licensing#Licensing]
- MPFProj for Visual Studio Project Framework
  [http://mpfproj10.codeplex.com/license]
- JSON Checker for JSON validation
  [http://www.raboof.com/projects/jsonchecker/]
- Newtonsoft Json.NET
  [http://www.newtonsoft.com/json] 
- YamlDotNet
  [http://aaubry.net/pages/yamldotnet.html] 
    

Azure App Service Tools v3.0.0   15.0.40215.0
Azure App Service Tools v3.0.0

C# Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51212.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   4.9.11-pre (71eb098)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.4.11027.3
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61801.210
Microsoft SQL Server Data Tools

TypeScript Tools   15.6.20202.3
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.9.0.753 (f0f46392f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.10.96 (a702a9ceb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.2.0.16 (HEAD/a78295902)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.9.1.24 (f62de47)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by dalexsoto** [comment] 2018-04-13 17:07
Hello @rihadavid thanks for contacting us!

I think this is not a bug and it is an (un?)fortunate situation because of the differences of Objective-C vs C#, let me quote the documentation of [UNNotificationTrigger](https://developer.apple.com/documentation/usernotifications/unnotificationtrigger?language=objc):

> The UNNotificationTrigger class is an abstract class for representing an event that triggers the delivery of a notification. You do not create instances of this class directly. Instead, you instantiate the concrete subclass that defines the trigger condition you want for your notification. You then assign the resulting object to the UNNotificationRequest object that you use to schedule your notification.
> 
> Concrete trigger classes include the following:
> 
> * UNTimeIntervalNotificationTrigger
> * UNCalendarNotificationTrigger
> * UNLocationNotificationTrigger
> * UNPushNotificationTrigger

The most important bit is this one 

> You do not create instances of this class directly. Instead, you instantiate the concrete subclass that defines the trigger condition you want for your notification.

We can enforce such rules outlined in the document in C# because of type safety, in Objective-C there is no such thing as abstract classes, it cannot really be enforced from the language itself. Now because of this you are getting such runtime error, The SDK is using an internal type `UNLegacyNotificationTrigger` which is not exposed in the public API and since the base type is an abstract class you get a recipe to 💣 💥 .

<img width="818" alt="screen shot 2018-04-13 at 11 45 47 am" src="https://user-images.githubusercontent.com/204671/38747370-4d765a26-3f10-11e8-8195-83ece8b7ddcc.png">

To be honest I do not think this is an actual bug, the runtime is somehow protecting you to misuse the API, `UILocalNotification` is now deprecated in favor of `UNNotificationRequest` and ideally you should be using what the later provides, also `UNLegacyNotificationTrigger` is an internal type and Apple might have their reasons to not expose this into the public API.

I am closing this because I consider this is not a bug in Xamarin.iOS.

**Comment by migueldeicaza** [comment] 2018-10-11 14:02
This is really a bug in Xamarin.iOS design, and it needs to be rectified.

**Comment by jigneshbodarya** [comment] 2020-12-11 05:31
How many more years it will take to fix this issue?

**Comment by rolfbjarne** [comment] 2022-09-23 05:53
This is a dup of #4969, which has been fixed, so I'm closing this.

**Closed by rolfbjarne** 2022-09-23 05:53 UTC
Labels: bug, iOS
