### ISSUE TITLE
[.NET 8.0 Preview 1] Permission denied during dotnet build for net8.0-ios and net8.0-maccatalyst

### ISSUE THREAD

**Issue by TimLariviere** [xamarin/xamarin-macios#17616] opened 2023-02-24 11:49 UTC
I'm not sure if it's the right place for it, so please let me know if I need to report this issue elsewhere.

I have been experimenting with the newly released .NET 8.0 Preview 1 and noticed `dotnet build` fails on macOS when targeting `net8.0-ios` or `net8.0-maccatalyst` on macOS (didn't try on Windows).

Building for `net8.0-android` works fine, but targeting either iOS or macOS will  result in a "Permission denied" when calling `tools\mono-aot-cross` during `AOTCompile` MSBuild task.

Running `dotnet build` in sudo mode works though.

### Steps to Reproduce

1. Install dotnet SDK version `8.0.100-preview.1.23115.2`
2. Create a `net7.0-ios` or `net7.0-maccatalyst` project from the official template
3. Change the target frameworks to use net8.0
4. Execute `dotnet build`

### Expected Behavior

Both iOS and Mac Catalyst apps should build without issue.

### Actual Behavior

`dotnet build` fails with a `Permission Denied` error.

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.5 (build 1802)
Installation UUID: 5f290c18-172c-4e9b-9808-1eeb8b2e8202

Runtime
.NET 7.0.1 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 12.3.2372; git-rev-head:754abbf6a3563f6267e5717ae832b4ac25b1f2fb; git-branch:release/7.0.1xx-xcode13.3

Roslyn (Language Service)
4.5.0-3.23056.2+97881342e427ff5cdcba8f12b12ff8e6f3564431

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.200/Sdks
SDK Versions:
	8.0.100-preview.1.23115.2
	7.0.200
	7.0.102
	7.0.101
	7.0.100
	6.0.406
	6.0.405
	6.0.404
	6.0.403
	6.0.112
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	8.0.0-preview.1.23110.8
	7.0.3
	7.0.2
	7.0.1
	7.0.0
	6.0.14
	6.0.13
	6.0.12
	6.0.11

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.2.0.0 (Visual Studio Community)
Commit: xamarin-android/d17-5/797e2e1
Android SDK: /Users/timothelariviere/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		11.0 (API level 30)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.2
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: 6dd9def
Java.Interop: xamarin/java.interop/main@149d70fe
SQLite: xamarin/sqlite/3.40.0@fdc1e34
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@9f02d77

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.5.0.33
Hash: f0c0c52
Branch: remotes/origin/d17-5~2
Build date: 2023-02-14 00:26:05 UTC

Android Device Manager
Version: 0.0.0.1245
Hash: 7f8a990
Branch: 7f8a990
Build date: 2023-02-14 00:26:05 UTC

Apple Developer Tools
Xcode: 14.2 21534
Build: 14C18

Xamarin.Mac
Not Installed

Xamarin.iOS
Version: 16.2.0.5 Visual Studio Community
Hash: 7738c90c9
Branch: xcode14.2
Build date: 2023-01-25 15:56:15-0500

Xamarin Designer
Version: 17.5.3.47
Hash: e8b5d371c3
Branch: remotes/origin/d17-5
Build date: 2023-02-14 00:26:00 UTC

Build Information
Release ID: 1705001802
Git revision: bfdc90915981031f5bdda171c7eebf116a558598
Build date: 2023-02-14 00:24:08+00
Build branch: release-17.5
Build lane: release-17.5

Operating System
Mac OS X 13.1.0
Darwin 22.2.0 Darwin Kernel Version 22.2.0
    Fri Nov 11 02:04:44 PST 2022
    root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 arm64
```

</details>

### Build Logs

<details>
    <summary>dotnet build logs</summary>

    $ dotnet build -f net8.0-ios

    MSBuild version 17.6.0-preview-23108-10+51df47643 for .NET
      Determining projects to restore...
      Restored /Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj (in 462 ms).
    /usr/local/share/dotnet/sdk/8.0.100-preview.1.23115.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(287,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
      Detected signing identity:
              
        Bundle Id: com.companyname.net8maui
        App Id: com.companyname.net8maui
      Net8Maui -> /Users/timothelariviere/Git/Tests/Net8Maui/bin/Debug/net8.0-ios/iossimulator-x64/Net8Maui.dll
      Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018: The "AOTCompile" task failed unexpectedly. [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018: System.AggregateException: One or more errors occurred. (One or more errors occurred. (An error occurred trying to start process '/usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.iossimulator-x64/8.0.0-preview.1.23110.8/Sdk/../tools/mono-aot-cross' with working directory '/Users/timothelariviere/Git/Tests/Net8Maui'. Permission denied)) [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:  ---> System.AggregateException: One or more errors occurred. (An error occurred trying to start process '/usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.iossimulator-x64/8.0.0-preview.1.23110.8/Sdk/../tools/mono-aot-cross' with working directory '/Users/timothelariviere/Git/Tests/Net8Maui'. Permission denied) [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:  ---> System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.iossimulator-x64/8.0.0-preview.1.23110.8/Sdk/../tools/mono-aot-cross' with working directory '/Users/timothelariviere/Git/Tests/Net8Maui'. Permission denied [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:    at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:    at Xamarin.Utils.Execution.<>c__DisplayClass24_1.<RunAsync>b__0() in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/common/Execution.cs:line 103 [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018: --- End of stack trace from previous location --- [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:    at Xamarin.MacDev.Tasks.XamarinTask.ExecuteAsync(String fileName, IList`1 arguments, String sdkDevPath, Dictionary`2 environment, Boolean mergeOutput, Boolean showErrorIfFailure, String workingDirectory) in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinTask.cs:line 120 [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:    --- End of inner exception stack trace --- [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:    at Xamarin.MacDev.Tasks.AOTCompileTaskBase.<>c__DisplayClass36_0.<Execute>b__7(Task`1 v) in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/AOTCompileTaskBase.cs:line 108 [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke() [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018: --- End of stack trace from previous location --- [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:    --- End of inner exception stack trace --- [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:    at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken) [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:    at System.Threading.Tasks.Task.WaitAll(Task[] tasks) [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:    at Xamarin.MacDev.Tasks.AOTCompileTaskBase.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/AOTCompileTaskBase.cs:line 115 [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:    at Xamarin.MacDev.Tasks.AOTCompile.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/AOTCompile.cs:line 14 [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.235-net8-p1/targets/Xamarin.Shared.Sdk.targets(1037,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/Users/timothelariviere/Git/Tests/Net8Maui/Net8Maui.fsproj::TargetFramework=net8.0-ios]
    
    Build FAILED.
</details>

**Comment by rolfbjarne** [comment] 2023-02-24 12:07
This is a known issue: https://github.com/dotnet/runtime/issues/82201

The workaround is simple: you can do `sudo chmod +x path/to/mono-aot-cross` to make the AOT compiler executable.

If you're building for release, you might have to do the same for the `llc` and `opt` binaries: `sudo chmod +x path/to/llc path/to/opt`

**Comment by rolfbjarne** [comment] 2023-02-24 12:07
Closing as duplicate of https://github.com/dotnet/runtime/issues/82201.

**Closed by rolfbjarne** 2023-02-24 12:07 UTC

**Comment by rolfbjarne** [comment] 2023-02-24 12:12
I've added this to the list of known issues: https://github.com/xamarin/xamarin-macios/wiki/Known-issues-in-.NET8#permission-denied-during-dotnet-build-for-net80-ios-and-net80-maccatalyst
