### ISSUE TITLE
Can't resolve the reference 'UIKit.UIViewController Acr.Support.iOS.Extensions::GetTopViewController(UIKit.UIApplication)'

### ISSUE THREAD

**Issue by bhavinjoshi** [xamarin/xamarin-macios#3398] opened 2018-02-06 09:24 UTC
### Expected Behavior
I am using Arc.UserDialog(7.0.1) Library in my Xamarin Project using Xamarin Forms. And when i try to Build & archive application for testflight  or i try to run it in iPhone mobile it shows error as below

Can't resolve the reference 'UIKit.UIViewController Acr.Support.iOS.Extensions::GetTopViewController(UIKit.UIApplication)'
referenced from the method 'UIKit.UIViewController Acr.UserDialogs.UserDialogsImpl/<>c::<.ctor>b__1_0()' in 'Acr.Support.iOS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. (MT2101) 

### Environment
Xamarin Forms

**Comment by mandel-macaque** [comment] 2018-02-06 15:21
Hello,

Can you please add a sample project that reproduces the issue as well as the full enviroment information? 

The easiest way to get exact version information:
- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
Then copy/paste the version information (you can use the "Copy Information" button).

If you cannot provide a sample project, could you provide the full build logs which might help debugging the issue.

To get full build logs just set the log verbosity to diagnostic at the following locations:
- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.
Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

**Comment by mandel-macaque** [comment] 2018-02-27 17:36
@bhavinjoshi  can you please provide the request info? Else I will close the issue as we cannot reproduce it without this information.

**Comment by VincentDondain** [comment] 2018-04-03 21:34
We have not received the requested information. If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button. Thanks!

**Closed by VincentDondain** 2018-04-03 21:34 UTC
Labels: need-info
