### ISSUE TITLE
build breaks if $PATH contains whitespace

### ISSUE THREAD

**Issue by lewurm** [xamarin/xamarin-macios#3400] opened 2018-02-06 13:54 UTC
### Steps to Reproduce

1.
```
$ cat /etc/paths.d/workbooks
/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
$ echo $PATH
/Users/lewurm/Library/Developer/Xamarin/android-sdk-macosx/platform-tools:/Users/lewurm/.fastlane/bin:/Users/lewurm/mate:/Users/lewurm/bin:/Users/lewurm/bin/bin:/Users/lewurm/bin/DESKTOP-7JVC4B3.redmond.corp.microsoft.com:/Users/lewurm/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:"/Applications/VMware Fusion.app/Contents/Public":/Library/TeX/texbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/opt/local/bin:/usr/texbin:/usr/local/bin:/Users/bernhardu/Library/Developer/Xamarin/android-sdk-macosx/platform-tools:/Library/Frameworks/Mono.framework/Versions/Current/bin
```

2. `make all`
```
Making all in builds
/bin/sh: Workbooks.app/Contents/SharedSupport/path-bin:/opt/local/bin:/usr/texbin:/usr/local/bin:/Users/bernhardu/Library/Developer/Xamarin/android-sdk-macosx/platform-tools:/Library/Frameworks/Mono.framework/Versions/Current/bin: No such file or directory
make[1]: *** [.stamp-configure-watchsimulator] Error 127
``` 

### Expected Behavior

Should not break build. For what it's worth, VMware Fusion also adds a path with a whitespace.
### Environment

current master

### Workaround
quote paths with `"`

**Comment by mandel-macaque** [comment] 2018-02-06 15:18
@lewurm is this happening in the xamarin-ios project? Or is it in Workbooks?

**Comment by lewurm** [comment] 2018-02-06 15:26
it's happening on the build of `xamarin-macios`

**Comment by spouliot** [comment] 2018-02-06 16:19
dupe of https://github.com/xamarin/xamarin-macios/issues/3183

**Closed by spouliot** 2018-02-06 16:19 UTC
Labels: duplicate
