### ISSUE TITLE
Cannot deploy Xamarin project to iOS simulator

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#14975] opened 2022-05-10 20:27 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cannot-deploy-Xamarin-project-to-iOS-sim/10028575)._

---
I get “error HE0042: Could not launch the app ‘’ on the device 'iOS 15.4 (19E240) - iPhone 13 Pro Max': Application launch for '' did not return a valid pid nor a launch error.” when attempting to deploy a Xamarin Forms project to the iOS simulator. Another user reported this in the comments under the release post here so possibly it is not working for anyone:

https://devblogs.microsoft.com/visualstudio/visual-studio-2022-for-mac-release-candidate/

---
#### Feedback Bot on 5/4/2022, 10:46 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by rolfbjarne** [comment] 2022-05-11 07:08
This is a duplicate of #14834.

**Closed by rolfbjarne** 2022-05-11 07:08 UTC
