### ISSUE TITLE
iOS regression - crash when parsing JSON

### ISSUE THREAD

**Issue by SamsonCodeHeroes** [xamarin/xamarin-macios#4347] opened 2018-06-27 01:06 UTC
Since the recent Xamarin iOS tooling update, I am seeing a crash that appears to be related to JSON serialization and `ImmutableArray` (see repro attached below).

The following doesn't happen when using the iOS SDK [11.2](https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-vs4mac-previous-stable.log), but does happen using [11.4](https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-vs4mac-stable.log). Strangely, commenting out an unrelated property prevents the error.

### Steps to Reproduce

1. Build and run the app.
2. Press the button. This causes deserialization and re-serializing of a small piece of JSON data.
3. You should get a Null reference exception.
4. Comment out the `Title` property  in `ServiceDto` (other properties should also work).
5. Re-run the app and hit the button.
6. JSON should be output to console, without crashing.

### Expected Behavior
JSON string should be logged to output.

### Actual Behavior
Null reference exception.

### Environment
Error appears to be iPhone-only. Replicated on:
- iPhone5S running iOS version 11.0.3.
- iPhoneX running 11.4.

The crash doesn't seem to happen on all devices. The initial error report wasn't replicated on an old iPad2 running iOS 9.3.5, though I haven't been able to re-test this.

IDE:
```
Microsoft Visual Studio Community 2017 
Version 15.7.2
VisualStudio.15.Release/15.7.2+27703.2018
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

ASP.NET and Web Tools 2017   15.0.40511.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

AWS Toolkit for Visual Studio 2017   1.14.3.3
AWS Toolkit for Visual Studio 2017.
Copyright 2011-2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Release notes: https://aws-vs-toolkit.s3.amazonaws.com/versioninfo.html

This software includes third party software subject to the following copyrights:
- Logging from log4net, Apache License 
  [http://logging.apache.org/log4net/license.html]
- Putty for PPK to PEM conversion, MIT license 
  [http://www.chiark.greenend.org.uk/~sgtatham/putty/licence.html]
- NGit for AWS Elastic Beanstalk incremental push
  [https://github.com/mono/ngit/blob/master/NGit.license.txt]
- NSch dependency for NGit
  [https://github.com/mono/ngit/blob/master/NSch.license.txt]
- Sharpen dependency for NGit
  [https://github.com/mono/ngit/blob/master/Sharpen/AssemblyInfo.cs]
- ICSharpCode.SharpZipLib dependency for NGit
  [http://www.icsharpcode.net/opensource/sharpziplib/]
- Mono.Posix.dll and Mono.Security.dll dependencies for NGit
  [http://mono-project.com/FAQ:_Licensing#Licensing]
- MPFProj for Visual Studio Project Framework
  [http://mpfproj10.codeplex.com/license]
- JSON Checker for JSON validation
  [http://www.raboof.com/projects/jsonchecker/]
- Newtonsoft Json.NET
  [http://www.newtonsoft.com/json] 
- YamlDotNet
  [http://aaubry.net/pages/yamldotnet.html] 
    

Azure App Service Tools v3.0.0   15.0.40424.0
Azure App Service Tools v3.0.0

C# Tools   2.8.2-beta6-62916-08. Commit Hash: 2ad4aabc7a9dada097e54e544ebba48ab1c05074
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Color Theme Designer   1.0
Designer for creating new color themes

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JetBrains ReSharper Ultimate 2017.2    Build 109.0.20170824.131346
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2018 JetBrains, Inc.

Merq   1.1.19-rc (a4ffc1b)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

NCrunch   
Continuous Testing Tool for .NET
Copyright © 2010-2018 Remco Software Ltd

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SettingsWindow Extension   1.0
SettingsWindow Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

Trailing Whitespace Visualizer   2.5.83
Keeps your code files clean by making it easier than ever to identify and remove any trailing whitespace

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.8.2-beta6-62916-08. Commit Hash: 2ad4aabc7a9dada097e54e544ebba48ab1c05074
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 56f97a8dd4353d897336941f3e644423b87c794f.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.10.0.448 (4373404db)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.270 (82d750d12)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.0.19 (HEAD/342b2ce96)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.10.1.178 (408d357)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Example Project
[Repro.zip](https://github.com/xamarin/xamarin-macios/files/2135764/Repro.zip)

**Comment by therealjohn** [comment] 2018-06-28 13:47
I can reproduce this on my iPhone 6s. It works OK in the simulator.

**Comment by therealjohn** [comment] 2018-07-25 13:12
I'm removing the regression label because I can reproduce the issue with Xamarin.iOS 11.10 and Xcode 9.3.1 shown in the build output linked as iOS 11.2. I can also reproduce this with Xamarin.iOS 11.12 and Xcode 9.4.1 which is the versions linked as iOS 11.4.

**Comment by spouliot** [comment] 2018-07-25 13:33
This sounds like a linker _issue_, i.e. it's off by default for the simulator (which works) and enabled by default open device. Serialization (like JSON) is usually done using reflection and types/members must be preserved to work (if they are not directly used by the code).

To test this you can:
- enable the linker on the simulator and run the app; and
- disable the linker on the device;

It the results switch (exception on simulator & working on device) it means the linker needs to be told which extraneous types to preserve,

**Comment by therealjohn** [comment] 2018-07-25 13:39
@spouliot, I should have mentioned that I tested that... The issue reproduces on a device with Don't Link.

**Comment by kentcb** [comment] 2018-07-25 22:21
Yes, I work with @SamsonCodeHeroes. We should have mentioned that we tried disabling the linker first (we've been bitten by that enough before!). We also suspected all sorts of things in terms of what the underlying cause was - immutable collections being the primary candidate. However, changing one thing would change the end result in confounding ways. At one point we even suspected a byte alignment issue with the compiler and tried injecting empty byte arrays to check whether that would cause the issue to go away (it didn't for us).

**Comment by spouliot** [comment] 2018-07-25 22:54
hmm... weird

> at System.Collections.Immutable.ImmutableArray`1+EnumeratorObject[T].Create (T[] array) [0x00000] in <6518d0e60ca84f6b915c07341a031a32>:0 

does hint to some reflection code, e.g. where `T` might not be fully preserved.

I'll investigate this further using the attached sample. Thanks both for replying with extra information - the obvious is not always the culprit :-)

**Comment by bsheen** [comment] 2018-08-10 02:45
@spouliot I work with @kentcb and @SamsonCodeHeroes, I was just wondering if you'd made any progress resolving this issue. It's currently blocking a release for an important client of ours and the app has a significant active user base.

**Comment by WilliamNolanch** [comment] 2018-08-22 04:30
@spouliot @therealjohn, I'm following up on the above. Are we able to get an update? Thanks

**Comment by spouliot** [comment] 2018-08-24 20:36
So, the issue is not related to the (managed) linker.

The issue only shows up on ARM64 (both mono and LLVM AOT backends). It works correctly when AOT'ed on ARMv7 (32bits). Very likely it's not a _real_ `NullReferenceException` but a remapped `SIGSEGV` from the runtime.

Going back in time...
* XI 11.16 (15.9) w/mono `2018-04` fails
* XI 11.14 (15.8) w/mono `2018-02` fails
* XI 11.12 (15.7) w/mono `2017-12` fails
but according to the [original description](url
https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-vs4mac-previous-stable.log)
`mtouch 11.10.1.178 (d15-7: 408d3574)` worked
but installing something just a bit older
`mtouch 11.10.0.1 (d15-7: eadb8376)` failed for me

@vargaz can you have a look at this ? thanks!

**Comment by bsheen** [comment] 2018-09-07 02:28
@vargaz have you been able to make any progress. Our client needs a release out ASAP and this issue is blocking that.

**Comment by vargaz** [comment] 2018-09-08 22:28
As a workaround, try to change the order of the parameters to the ServiceDto constructor:
instead of:
        bool isOpenNow,
        ImmutableArray<RelevantPeriodDto> relevantPeriods)
do:
        ImmutableArray<RelevantPeriodDto> relevantPeriods,
        bool isOpenNow)

**Closed** 2018-09-12 18:01 UTC
Labels: bug, iOS

**Comment by kentcb** [comment] 2018-09-19 01:40
Thanks for fixing this.

Whilst we made some progress by re-ordering parameters, it seems like the crash is manifesting in other ways. For example:
```
2018-09-19 11:36:48.499 QUT[9897:17016688] critical: Stacktrace:
2018-09-19 11:36:48.500 QUT[9897:17016688] critical:   at <unknown> <0xffffffff>
2018-09-19 11:36:48.500 QUT[9897:17016688] critical:   at (wrapper managed-to-native) object.__icall_wrapper_mono_gc_alloc_vector (intptr,intptr,intptr) <0x00007>
2018-09-19 11:36:48.500 QUT[9897:17016688] critical:   at (wrapper alloc) object.AllocVector (intptr,intptr) <0x0016b>
2018-09-19 11:36:48.500 QUT[9897:17016688] critical:   at System.Collections.Generic.Dictionary`2<TKey_REF, TValue_REF>.Initialize (int) [0x0002e] in <3c7b99a36820490fb2cbc5a6fc6b06d8#0955DAA3-D8E5-6EB0-C74C-615A1A72EFF5>:0
2018-09-19 11:36:48.501 QUT[9897:17016688] critical:   at System.Collections.Generic.Dictionary`2<TKey_REF, TValue_REF>..ctor (int,System.Collections.Generic.IEqualityComparer`1<TKey_REF>) [0x00015] in <3c7b99a36820490fb2cbc5a6fc6b06d8#0955DAA3-D8E5-6EB0-C74C-615A1A72EFF5>:0
<snip>
```
Our hope is that these other crashes we're experiencing have the same underlying cause.

Is there an ETA as to when the fix will hit the alpha channel?

**Comment by vargaz** [comment] 2018-09-19 01:44
Can someone answer that ?

**Comment by rolfbjarne** [comment] 2018-09-19 07:51
@kentcb Can you try this package: [xamarin.ios-11.17.0.92.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-4277/ec02eb8f9f27c012e9ac0357793b6ace2c9ec30b/34/package/xamarin.ios-11.17.0.92.pkg) and see if it fixes the problem? It contains the fix for this bug.

You may run into other issues with this package, but if anything shows up we'll help you get through them since it would be nice to at the very least get a confirmation that the fix actually works for your app.

**Comment by kentcb** [comment] 2018-09-19 08:59
Thanks @rolfbjarne! ❤️ 

My preliminary testing indicates that this fixes both issues (I rolled back our workaround to be sure). This is looking positive, but we'll conduct more in-depth testing and get back to you shortly.

**Comment by kentcb** [comment] 2018-09-25 01:26
@rolfbjarne We've done quite extensive testing now and have been unable to reproduce the crash. We're now in discussions around the best path forward with respect to the release. We cognizant of the risk of a compiler-induced bug being caught _after_ the release, after which we would have no recourse (again). One thing that would help us in our decision making is to have a rough understanding of when this fix will hit the alpha channel. Are you able to provide a rough date, or even an indicative "days", "weeks" or "months"?

**Comment by rolfbjarne** [comment] 2018-09-25 06:33
> Are you able to provide a rough date, or even an indicative "days", "weeks" or "months"?

My personal guess would be that it _should_ get into the Alpha channel within a couple of months (in an upcoming (but not the first) preview of our `d16-0` release). The `d16-0` release is scheduled for next Spring, which is when it would reach the Stable channel.

**Comment by cainunable** [comment] 2018-11-27 19:02
@rolfbjarne I see that the fix has been merged a while back, but I don't know how to see which channel it has been released in.  Is this fix out and available yet?

**Comment by rolfbjarne** [comment] 2018-11-28 07:18
@cainunable the first preview release with this fix should come out in a couple of weeks.

**Comment by cainunable** [comment] 2018-11-28 13:16
@rolfbjarne I'm getting a similar error as kentcb's so I am hoping this might be a possible solution.  If I just install the .pkg above to test that theory, how difficult is it to restore my current working environment?

**Comment by rolfbjarne** [comment] 2018-11-28 13:54
@cainunable it should be just a matter of checking for updates in Visual Studio for Mac, and install the offered Xamarin.iOS update. If that doesn't work, you can force the update by switching to a different channel and then switch back again.
