### ISSUE TITLE
[MTOUCH] Native linking fails with Xamarin.iOS v12.14

### ISSUE THREAD

**Issue by parmjitv** [xamarin/xamarin-macios#6765] opened 2019-08-13 21:30 UTC
Xamarin.iOS v12.14 projects do not link correctly via the Mtouch utility.  Is this a known issue with the current release build?

### Steps to Reproduce

1. Install the latest stable development environment with Mac OS X 10.14.6 (Mojave), Xcode 10.3, Visual Studio Community 2019 for Mac v8.2.2, Mono v6.0.0.319, Xamarin.iOS v12.14.0.114

2. Open any Xamarin.iOS project in Visual Studio and set the linker behaviour as 'Link Framework SDKs only' (Release/iPhone)

3. Generate release build

### Expected Behavior

Release build should link correctly.

### Actual Behavior

Variety of MTOUCH/Linker MT5210 errors occur.

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.2.2 (build 21)
Installation UUID: 85a1bc24-a798-4892-9712-4e3b39d02534
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000319

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.319 (2019-02/52203786470) (64-bit)
	Package version: 600000319

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.1.1
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.701/Sdks
SDK Versions:
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.4.1.0 (Visual Studio Community)
Commit: xamarin-android/d16-2/ebd65c9
Android SDK: /Users/xxx/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 25.0.5
SDK Build Tools Version: 25.0.3

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/xxx/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.58
Hash: d03e3ea
Branch: remotes/origin/d16-2~1
Build date: 2019-07-30 21:29:36 UTC

=== Xamarin Designer ===

Version: 16.2.0.379
Hash: 3f0652957
Branch: remotes/origin/d16-2
Build date: 2019-08-01 17:32:50 UTC

=== Apple Developer Tools ===

Xcode 10.3 (14492.2)
Build 10G8

=== Xamarin.Mac ===

Version: 5.14.0.114 (Visual Studio Community)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:06-0400

=== Xamarin.iOS ===

Version: 12.14.0.114 (Visual Studio Community)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:05-0400

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 802020021
Git revision: d2ffd09000c5d24a206b715b63d409e8e965689a
Build date: 2019-08-02 00:25:49+00
Build branch: release-8.2
Xamarin extensions: 4cc9cbbe68baaeb6bc654f36e057b1bd124f3f65

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Thu Jun 20 18:42:21 PDT 2019
    root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
```

### Build Logs

Logs are similar:

```
MTOUCH: Error MT5210: Native linking failed, undefined symbol: _Xamarin_Forms_Core_System_Collections_Generic_EqualityComparer_1_Xamarin_Forms_Size_IndexOf_Xamarin_Forms_Size___Xamarin_Forms_Size_int_int.

MTOUCH: Error MT5210: Native linking failed, undefined symbol: _System_Runtime_Serialization_System_Runtime_Serialization_XmlObjectSerializerWriteContext_IncrementArrayCount_System_Runtime_Serialization_XmlWriterDelegator_System_Array.

MTOUCH: Error MT5210: Native linking failed, undefined symbol: _Xamarin_iOS_WebKit_WKNavigation_get_ClassHandle.
...
```

Please note this was not an occurrence with previous versions of Xamarin.iOS v12.XX.

**Comment by spouliot** [comment] 2019-08-14 01:20
I have seen this in another issue - but it was skipping linking for some BCL assemblies. That created some binaries too large for Apple's native linker to process for on bits architectures (which is limited to about 24bits of addressing).

You can try to build for ARM64 only to see if it works (since Apple's 64bits version of `ld` has no such restriction).

If this happens with only 64 bits (ARM64) builds and without skipping assemblies then please attach your build log. Note that you might have to build from the command-line (with `msbuild`) if it does not fir in the output pane of VSfM.

**Comment by parmjitv** [comment] 2019-08-21 15:45
@spouliot - Thanks for your prompt reply, and please excuse the lateness of my response.  Further to your remarks, please see the following test results.

Using the following options in the Visual Studio iOS Build option pane:

test 1:
Linker behaviour - 'Link Framework SDKs Only'
Supported architecture - 'ARM64'
Use the LLVM optimizing compiler - Disabled
Result: the release build generates as expected.

test 2:
Linker behaviour - 'Link Framework SDKs Only'
Supported architecture - 'ARM64'
Use the LLVM optimizing compiler - Enabled
Result: the release build generates as expected.

test 3:
Linker behaviour - 'Link Framework SDKs Only'
Supported architecture - 'ARMv7 + ARMv7s + ARM64'
Use the LLVM optimizing compiler - Disabled
Result: the release build generates as expected.

test 4:
Linker behaviour - 'Link Framework SDKs Only'
Supported architecture - 'ARMv7 + ARMv7s + ARM64'
Use the LLVM optimizing compiler - Enabled
Use Thumb-2 instruction set for ARMv7 and ARMv7s - Disabled
**Result: the release build generation fails with the aforementioned errors.**

test 5:
Linker behaviour - 'Link Framework SDKs Only'
Supported architecture - 'ARMv7 + ARMv7s + ARM64'
Use the LLVM optimizing compiler - Enabled
Use Thumb-2 instruction set for ARMv7 and ARMv7s - Enabled
**Result: the release build generation fails with the aforementioned errors.**

Apparently there is a collision somewhere when using the LLVM optimizing compiler with the older 32-bit ARMv7 and ARMv7s architectures - is this a known issue?  i.e. #6711

From the Visual Studio notes:

- Use the LLVM optimizing compiler
The LLVM compiler generates code that is faster and smaller, but the compilation takes much longer.  Note this option is not compatible with debug mode.
- Use Thumb-2 instruction set for ARMv7 and ARMv7s
Thumb-2 code is smaller but may be slightly slower in some cases.

**Generally speaking, is it acceptable to use release builds that do not employ the LLVM optimizing compiler for the ARMv7 and ARMv7s architectures?**  If so, this may be the easiest solution for this issue.

I have my updated my development environment to the latest stable stack as outlined below.  Many thanks!

```
=== Visual Studio Community 2019 for Mac ===

Version 8.2.4 (build 17)
Installation UUID: 85a1bc24-a798-4892-9712-4e3b39d02534
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000327

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.327 (2019-02/f8ea05bddcb) (64-bit)
	Package version: 600000327

=== NuGet ===

Version: 5.1.0.6013

=== Xamarin Designer ===

Version: 16.2.0.379
Hash: 3f0652957
Branch: remotes/origin/d16-2
Build date: 2019-08-01 17:32:50 UTC

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.1.1
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.701/Sdks
SDK Versions:
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.4.1.0 (Visual Studio Community)
Commit: xamarin-android/d16-2/ebd65c9
Android SDK: /Users/xxx/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 25.0.5
SDK Build Tools Version: 25.0.3

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/xxx/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.60
Hash: 686c817
Branch: remotes/origin/d16-2
Build date: 2019-08-07 15:49:58 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 10.3 (14492.2)
Build 10G8

=== Xamarin.Mac ===

Version: 5.14.0.114 (Visual Studio Community)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:06-0400

=== Xamarin.iOS ===

Version: 12.14.0.114 (Visual Studio Community)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:05-0400

=== Build Information ===

Release ID: 802040017
Git revision: 9b155edbf23e9fe8b477b3236a342164fabf5f6b
Build date: 2019-08-16 00:21:01+00
Build branch: release-8.2
Xamarin extensions: 9f2598b5f2371ba2903988c2cd87a9759d0255f2

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Thu Jun 20 18:42:21 PDT 2019
    root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
```

**Comment by seanmcleod** [comment] 2019-09-04 19:58
I'm having the same issue. The exact same project/source code that I built 2 months ago for submission to the app store now fails to build a release version after upgrading to Xamarin.iOS 12.14.0.114.

Basically the build takes forever (about 15mins or more) and then fails with 39078 linker errors, basically it doesn't look like a single symbol is resolved, these are the typical examples:

```sh
error MT5210: Native linking failed, undefined symbol: _EasyCockpitIOS_EasyCockpitIOS_ADSBDialog_CreateRootElement. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
error MT5210: Native linking failed, undefined symbol: _EasyCockpitIOS_System_Array_IndexOfImpl_T_DOUBLE_T_DOUBLE___T_DOUBLE_int_int. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
```

I'm also using:

Linker behaviour - 'Link Framework SDKs Only'
Supported architecture - 'ARMv7 + ARMv7s + ARM64'
Use the LLVM optimizing compiler - Enabled

Which hasn't changed from 2 months ago when the same project and code built just fine.

I did notice the following warnings (3 examples of the 15 or so):

```sh
warning : ignoring file /Users/sean/Library/Caches/Xamarin/mtbs/builds/EasyCockpitIOS/179ea3eb79ec43e448b38e32c76c5c88/obj/iPhone/Release/mtouch-cache/armv7s/EasyCockpitIOS.exe-llvm.o, file was built for armv7 which is not the architecture being linked (armv7s): /Users/sean/Library/Caches/Xamarin/mtbs/builds/EasyCockpitIOS/179ea3eb79ec43e448b38e32c76c5c88/obj/iPhone/Release/mtouch-cache/armv7s/EasyCockpitIOS.exe-llvm.o
warning : ignoring file /Users/sean/Library/Caches/Xamarin/mtbs/builds/EasyCockpitIOS/179ea3eb79ec43e448b38e32c76c5c88/obj/iPhone/Release/mtouch-cache/armv7s/mscorlib.dll-llvm.o, file was built for armv7 which is not the architecture being linked (armv7s): /Users/sean/Library/Caches/Xamarin/mtbs/builds/EasyCockpitIOS/179ea3eb79ec43e448b38e32c76c5c88/obj/iPhone/Release/mtouch-cache/armv7s/mscorlib.dll-llvm.o
warning : ignoring file /Users/sean/Library/Caches/Xamarin/mtbs/builds/EasyCockpitIOS/179ea3eb79ec43e448b38e32c76c5c88/obj/iPhone/Release/mtouch-cache/armv7s/Xamarin.iOS.dll-llvm.o, file was built for armv7 which is not the architecture being linked (armv7s): /Users/sean/Library/Caches/Xamarin/mtbs/builds/EasyCockpitIOS/179ea3eb79ec43e448b38e32c76c5c88/obj/iPhone/Release/mtouch-cache/armv7s/Xamarin.iOS.dll-llvm.o
``` 

I tried clearing the build cache, doing a clean-rebuild etc. with no difference.

Then thinking there was some mixup between ARMv7 and ARMv7s I removed ARMv7 and switched to:

Supported architecture - 'ARMv7s + ARM64'

Did a clean rebuild again but no difference.

The only combination that I tried, I didn't try all the combinations that @parmjitv listed above, that worked was to switch to ARM64 only (while keeping LLVM optimizing compiler enabled).

So it does appear as if the combination of the LLVM optimizing compiler for release builds is incompatible with ARMv7 and ARMv7s?

**Comment by seanmcleod** [comment] 2019-09-09 20:28
Any news on this? Should it be possible to use LLVM and ARMv7(s)? Or do we have to give up using LLVM if we want to target ARMv7(s) in addition to ARM64?

**Comment by parmjitv** [comment] 2019-09-10 17:28
@seanmcleod - Hopefully not.  I expect that quite a few Xamarin.iOS apps still run on legacy devices and would benefit from the optimizing compiler.

**Comment by parmjitv** [comment] 2019-09-10 17:28
@spouliot @rolfbjarne - Would this be classified as a bug?  If so, can we expect this to be resolved in the next stable release of Xamarin.iOS?

**Comment by seanmcleod** [comment] 2019-09-10 18:04
@parmjitv I also posted this issue on the Visual Studio community site:

https://developercommunity.visualstudio.com/content/problem/728504/xamarinios-builds-using-llvm-and-armv7-fail-to-lin.html

And received a notification that it is being triaged and with the following comment:

> We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

So hopefully we'll get an answer fairly soon since I need to push an update to our app and a fairly large percentage of our users using iPads in particular are still using iPads with 32bit CPUs.

**Comment by rolfbjarne** [comment] 2019-09-11 06:07
> Generally speaking, is it acceptable to use release builds that do not employ the LLVM optimizing compiler for the ARMv7 and ARMv7s architectures?

Yes, it's perfectly acceptable to ship release builds that were built without the LLVM compiler. There might be two issues: app size or performance; but if your debug builds are fine according your testing, the release builds (without LLVM, and assuming all other build options remain the same too) won't be any worse (neither bigger nor slower than the debug build).

> Would this be classified as a bug?

That depends on exactly what the problem is, which hasn't been fully determined yet.

As Sebastien asked [here](https://github.com/xamarin/xamarin-macios/issues/6765#issuecomment-521066455), please attach the complete verbose build log, that will help us determine the exact cause of what's happening.

**Comment by parmjitv** [comment] 2019-09-11 16:24
@rolfbjarne -  Thank you!  I will try to get the build log to you asap.

**Comment by parmjitv** [comment] 2019-09-11 16:26
@seanmcleod - For now, perhaps you can just build and deploy your app without the LLVM compiler enabled?  I recently did so for my own app, without any issues.  This would at least allow you to push out your update for your users.

**Comment by sergiokoo** [comment] 2019-11-09 22:13
I have the same issue with latest stable builds of Xamarin.iOS. However, for me, the working configuration was to use "ARMv7 + ARM64" and LLVM. Pure ARM64 is also compiled ok. An attempt to include **ARMv7s fails!** So both options "ARMv7s + ARM64" and "ARMv7 + ARMv7s + ARM64" fails with LLVM. I do not see an option to test a pure ARMv7s.
There are thousands of errors similar to what @seanmcleod described.
Something hopefully useful from my logs (sanitized a bit):
`
1>  MTouch: 2019-11-09T22:41:33.7252389+02:00 - Executing
1>  Sending Request Xamarin.Messaging.Build.Contracts.ExecuteTaskMessage to topic xvs/Build/16.3.0.278/execute-task/yyyyyyyyyy.iOS/6f2e17a002fMTouch
1>  Received Response of Xamarin.Messaging.Build.Contracts.ExecuteTaskMessage to topic build22396xxxxxxxxxx/response/xvs/Build/16.3.0.278/execute-task/yyyyyyyyyy.iOS/zzzzMTouch
1>  MTouch: 2019-11-09T22:52:11.5306875+02:00 - Logging messages
1>  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/xxxxxxxxxx/Library/Caches/Xamarin/mtbs/builds/yyyyyyyyyy.iOS/zzzzzzzzzz/obj/iPhone/AppStore/response-file.rsp
1>  Xamarin.iOS 13.6.0.12 (xcode11.2): mmmmmmmmm) using framework: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk
1>  Process exited with code 1, command:
1>  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang  -framework StoreKit -framework Security -framework OpenGLES -framework MediaPlayer -framework GameController -framework CoreGraphics -framework QuartzCore -framework AudioToolbox -framework UIKit -framework Foundation -framework AVFoundation -weak_framework CoreFoundation -weak_framework CFNetwork -weak_framework GSS
/Users/xxxxxxxxxx/Library/Caches/Xamarin/mtbs/builds/yyyyyyyyyy.iOS/zzzzzzzzzz/obj/iPhone/AppStore/mtouch-cache/armv7s/registrar.o 
... some files names, then...
/Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/SDKs/MonoTouch.iphoneos.sdk/usr/lib/libmonosgen-2.0.a /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/SDKs/MonoTouch.iphoneos.sdk/usr/lib/libxamarin.a /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/SDKs/MonoTouch.iphoneos.sdk/usr/lib/libmono-native-compat.a -force_load /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/SDKs/MonoTouch.iphoneos.sdk/usr/lib/libapp.a -Wl,-pie -arch armv7s -miphoneos-version-min=8.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -lz -liconv -o /Users/xxxxxxxxxx/Library/Caches/Xamarin/mtbs/builds/yyyyyyyyyy.iOS/zzzzzzzzzz/obj/iPhone/AppStore/mtouch-cache/armv7s/yyyyyyyyyy.iOS -dead_strip -u _xamarin_find_protocol_wrapper_type -u _xamarin_release_block_on_main_thread -u _xamarin_get_block_descriptor -u _UIApplicationMain
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): warning : ignoring file /Users/xxxxxxxxxx/Library/Caches/Xamarin/mtbs/builds/yyyyyyyyyy.iOS/zzzzzzzzzz/obj/iPhone/AppStore/mtouch-cache/armv7s/yyyyyyyyyy.iOS.exe-llvm.o, building for iOS-armv7s but attempting to link with file built for unknown-armv7
... 60000 similar warnings and then ...
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): error : warning: ignoring file /Users/xxxxxxxxxx/Library/Caches/Xamarin/mtbs/builds/yyyyyyyyyy.iOS/zzzzzzzzzz/obj/iPhone/AppStore/mtouch-cache/armv7s/yyyyyyyyyy.iOS.exe-llvm.o, building for iOS-armv7s but attempting to link with file built for unknown-armv7
... another 60000 similar errors ...
`

**Comment by rolfbjarne** [comment] 2019-11-27 08:36
This is a duplicate of #7471.

**Closed by rolfbjarne** 2019-11-27 08:36 UTC
Labels: iOS, need-info
