### ISSUE TITLE
Binding libraries loads without generated compiled items in DesignTimeBuild mode

### ISSUE THREAD

**Issue by xtmq** [xamarin/xamarin-macios#20814] opened 2024-07-04 07:33 UTC
### Steps to Reproduce

1. Take any iOS binding library project, for example for `net8.0-ios` target framework
2. Load it in `DesignTimeBuild` mode

### Expected Behavior

It is loaded correctly and IDE is able to analyze it content

### Actual Behavior

Files `/obj/Debug/net8.0-ios/iOS/<ProjectName>/<Component>.g.cs` is not added to MSBuild project

### Build Logs and Example Project

Can be found in the Rider Issue Tracker:
https://youtrack.jetbrains.com/issue/RIDER-94830

### Investigation

For some reason these generated files are collected only during `real` build and ignored in design time mode so IDE can not collect and analyze them for some reason:

![image](https://github.com/xamarin/xamarin-macios/assets/1643827/d73aa00c-c736-4cb7-89f3-f2e5b842ea04)

**Comment by rolfbjarne** [comment] 2024-07-04 11:01
This is a known issue, many years ago we disabled the design-time build for binding projects.

It's because building a binding project requires a Mac, and when building remotely from Windows, it would require connecting to the Mac, building there, and getting the result back to the Windows machine. Design time builds are supposed to be fast... so the experience was less than ideal.

The good news is that we're working on building binding projects fully on Windows, and once that's done, we'll also enable design-time builds for binding projects.

That work is tracked here: https://github.com/xamarin/xamarin-macios/issues/10148, so I'm closing this as a duplicate of that issue.

**Closed by rolfbjarne** 2024-07-04 11:01 UTC

**Comment by rolfbjarne** [comment] 2024-07-04 12:20
> If this work will take some time, maybe we add a special property which IDE will be able to set to enable generating in .net 9 SDK?

You can modify your local file with the _CollectGeneratedSources target to see if this would work.
