### ISSUE TITLE
Model attribute with Linker in SdksOnly and compilation Release to Device will cause Error MT0000 - System.NullReferenceException

### ISSUE THREAD

**Issue by juliocabrera1** [xamarin/xamarin-macios#5845] opened 2019-04-03 17:36 UTC
### Steps to Reproduce

1. Open the attached solution
2. Validate that compilation is configured to Release to Device **Important**
3. Validate that project TestApp is configured with Linker to SDKsOnly **Important**
4. Check bundle signing configuration
5. Rebuild the project TestApp

### Expected Behavior
Not throw a NullReferenceException 
### Actual Behavior
It produces an error:
```
MTOUCH : error MT0000: Unexpected error - Please file a bug report at http://bugzilla.xamarin.com
    System.NullReferenceException: Object reference not set to an instance of an object
      at Registrar.StaticRegistrar.GetBlockWrapperCreator (Registrar.Registrar+ObjCMethod obj_method, System.Int32 parameter) [0x0026e] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/StaticRegistrar.cs:4111 
      at Registrar.StaticRegistrar.Specialize (Registrar.AutoIndentStringBuilder sb, Registrar.Registrar+ObjCMethod method, System.Collections.Generic.List`1[T] exceptions) [0x0216b] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/StaticRegistrar.cs:3679 
      at Registrar.StaticRegistrar.Specialize (Registrar.AutoIndentStringBuilder sb) [0x00f3f] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/StaticRegistrar.cs:2959 
    MTOUCH : error MT0000: Unexpected error - Please file a bug report at http://bugzilla.xamarin.com
    System.NullReferenceException: Object reference not set to an instance of an object
      at Registrar.StaticRegistrar.GetBlockWrapperCreator (Registrar.Registrar+ObjCMethod obj_method, System.Int32 parameter) [0x0026e] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/StaticRegistrar.cs:4111 
      at Registrar.StaticRegistrar.Specialize (Registrar.AutoIndentStringBuilder sb, Registrar.Registrar+ObjCMethod method, System.Collections.Generic.List`1[T] exceptions) [0x0216b] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/StaticRegistrar.cs:3679 
      at Registrar.StaticRegistrar.Specialize (Registrar.AutoIndentStringBuilder sb) [0x00f3f] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/StaticRegistrar.cs:2959 
Done building target "_CompileToNative" in project "TestApp.csproj" -- FAILED.
```

### Environment

It happens in two different Mac with different versions of Visual Studio For Mac, also from Visual Studio in Windwos connected to a Mac. 
Below is the information of one of the Mac:

```
=== Visual Studio Community 2019 for Mac ===

Version 8.0 (build 3001)
Installation UUID: 4a8584ef-d91e-4d56-837a-8571e283087e
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

=== NuGet ===

Version: 4.8.2.5835

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.505/Sdks
SDK Versions:
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.9
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.2.0.5 (Visual Studio Community)
Android SDK: /Users/administrator/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: mono/mono/2018-08-rc@5ad371dab1b
Java.Interop: xamarin/java.interop/d16-0@c987483
LibZipSharp: grendello/LibZipSharp/master@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
MXE: xamarin/mxe/xamarin@b9cbb535
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.26.0@325e91a
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/administrator/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-03-27 18:41:02 UTC

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.6.0.25 (Visual Studio Community)
Hash: 50f75273
Branch: d16-0
Build date: 2019-03-05 11:50:33-0800

=== Xamarin.iOS ===

Version: 12.4.0.64 (Visual Studio Community)
Hash: 9c8d8e0a
Branch: xcode10.2
Build date: 2019-03-27 06:24:31-0400

=== Xamarin Designer ===

Version: 4.17.4.414
Hash: 55b8d07ef
Branch: remotes/origin/d16-0
Build date: 2019-03-22 21:44:12 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 800003001
Git revision: 16b11d379aeff65cd1e81d3616c267ad4251ad36
Build date: 2019-03-28 13:14:24+00
Build branch: master
Xamarin extensions: efad41c7f410d8e6d43361236e0e778cf6f9b4a5

=== Operating System ===

Mac OS X 10.14.4
Darwin 18.5.0 Darwin Kernel Version 18.5.0
    Mon Mar 11 20:40:32 PDT 2019
    root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

```

### Build Logs

[BuildLog.txt](https://github.com/xamarin/xamarin-macios/files/3039493/BuildLog.txt)

### Example Project

[TestBindingProject.zip](https://github.com/xamarin/xamarin-macios/files/3039515/TestBindingProject.zip)

The piece of code that produce the error is shown below:
```
//ApiDefinition.cs
namespace TSLBinding.iOS
{
    // typedef void (^TSLCommandResponseLifecycleBlock)();
    delegate void TSLCommandResponseLifecycleBlock();

    // @protocol TSLAsciiCommandResponseNotifying <NSObject>
    [Protocol, Model] //This produce the error.
    //[Protocol] //This works fine.
    [BaseType(typeof(NSObject))]
    interface TSLAsciiCommandResponseNotifying
    {
        // @required @property (copy, nonatomic) TSLCommandResponseLifecycleBlock responseBeganBlock;
        [Export("responseBeganBlock", ArgumentSemantic.Copy)]
        TSLCommandResponseLifecycleBlock ResponseBeganBlock { get; set; }

        // @required @property (copy, nonatomic) TSLCommandResponseLifecycleBlock responseEndedBlock;
        [Export("responseEndedBlock", ArgumentSemantic.Copy)]
        TSLCommandResponseLifecycleBlock ResponseEndedBlock { get; set; }
    }
}
```

**Comment by rolfbjarne** [comment] 2019-04-04 06:26
This is a duplicate of #4102, and fix should already be in the latest stable release from earlier this week.

If you don't want to update, you can add `--optimize=-static-block-to-delegate-lookup` to the additional mtouch arguments in the iOS Build project options as a workaround.

**Closed by rolfbjarne** 2019-04-04 06:26 UTC
