### ISSUE TITLE
Profiling does not start collecting data on Mac Catalyst when the app is a MAUI app

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-macios#20801] opened 2024-07-02 06:23 UTC
### Steps to Reproduce

A Mac Catalyst app works:

```sh
rm -rf ~/Projects/Testing/maccattest
mkdir ~/Projects/Testing/maccattest
cd ~/Projects/Testing/maccattest
dotnet new globaljson --sdk-version 8.0.301
dotnet new maccatalyst
dotnet build -f net8.0-maccatalyst -r maccatalyst-arm64 -c Debug -bl
DOTNET_DiagnosticPorts=~/exciting-trace,suspend ./bin/Debug/net8.0-maccatalyst/maccatalyst-arm64/maccattest.app/Contents/MacOS/maccattest
```

But a .NET MAUI one never starts:

```sh
rm -rf ~/Projects/Testing/maccattest
mkdir ~/Projects/Testing/maccattest
cd ~/Projects/Testing/maccattest 
dotnet new globaljson --sdk-version 8.0.301
dotnet new maui
dotnet build -f net8.0-maccatalyst -r maccatalyst-arm64 -c Debug -bl
DOTNET_DiagnosticPorts=~/exciting-trace,suspend ./bin/Debug/net8.0-maccatalyst/maccatalyst-arm64/maccattest.app/Contents/MacOS/maccattest
```

My trace start is:

```sh
dotnet trace collect --diagnostic-port ~/exciting-trace --format speedscope
```

### Environment

<details>
<summary>Version information</summary>

```
.NET SDK:
 Version:           8.0.301
 Commit:            1a0e9c0300
 Workload version:  8.0.300-manifests.77eacb1b
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.5
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.301/

.NET workloads installed:
 [wasm-tools]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.6/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.workload.mono.toolchain.current/8.0.6/WorkloadManifest.json
   Install Type:        FileBased

 [macos]
   Installation Source: SDK 8.0.300
   Manifest Version:    14.2.8053/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.macos/14.2.8053/WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: SDK 8.0.300
   Manifest Version:    17.2.8053/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.ios/17.2.8053/WorkloadManifest.json
   Install Type:        FileBased

 [aspire]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.2/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.aspire/8.0.2/WorkloadManifest.json
   Install Type:        FileBased

 [maccatalyst]
   Installation Source: SDK 8.0.300
   Manifest Version:    17.2.8053/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maccatalyst/17.2.8053/WorkloadManifest.json
   Install Type:        FileBased

 [maui]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.40/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.40/WorkloadManifest.json
   Install Type:        FileBased

 [tvos]
   Installation Source: SDK 8.0.300
   Manifest Version:    17.2.8053/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.tvos/17.2.8053/WorkloadManifest.json
   Install Type:        FileBased

 [android]
   Installation Source: SDK 8.0.300
   Manifest Version:    34.0.113/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.android/34.0.113/WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      9.0.0-preview.5.24306.7
  Architecture: arm64
  Commit:       a5cc707d97

.NET SDKs installed:
  7.0.407 [/usr/local/share/dotnet/sdk]
  8.0.202 [/usr/local/share/dotnet/sdk]
  8.0.301 [/usr/local/share/dotnet/sdk]
  9.0.100-preview.4.24267.66 [/usr/local/share/dotnet/sdk]
  9.0.100-preview.5.24307.3 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.4.24267.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.5.24306.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.4.24266.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.5.24306.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  /Users/matthew/Projects/Testing/maccattest/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

```

</details>

### Build Logs

[maccat-msbuild.binlog.zip](https://github.com/user-attachments/files/16062645/maccat-msbuild.binlog.zip)

[maui-msbuild.binlog.zip](https://github.com/user-attachments/files/16062683/maui-msbuild.binlog.zip)

**Comment by rolfbjarne** [comment] 2024-07-03 20:33
The problem is that the MAUI app has the sandbox enabled by default, while the plain Mac Catalyst app doesn't.

A sandboxed Mac Catalyst app can't be traced, this is a known issue: https://github.com/dotnet/runtime/issues/94114

The workaround is to disable the sandbox (remove `com.apple.security.app-sandbox` from the Entitlements.plist).

Closing as duplicate of https://github.com/dotnet/runtime/issues/94114.

**Closed by rolfbjarne** 2024-07-03 20:33 UTC
