### ISSUE TITLE
ThreadPoolDispatcher SIGSEGV in background

### ISSUE THREAD

**Issue by praeclarum** [xamarin/xamarin-macios#4113] opened 2018-05-22 21:28 UTC
I have an app that keeps "soft-crashing" in background threads.

The `ThreadPoolDispatcher` triggers it when it pops the `NSAutoreleasePool`. I cannot get the redacted symbols since this isn't a full crash.

It's hard to tell what's going on from the crash but I'm guessing some objects are getting garbage collected and for some reason the pool is still referencing them?

Is there any logging I can enable to get more info?

```
critical:   at <unknown> <0xffffffff>
critical:   at (wrapper managed-to-native) Foundation.NSObject.xamarin_release_managed_ref (intptr,Foundation.NSObject) <0x00007>
critical:   at Foundation.NSObject.ReleaseManagedRef () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.11.0.280/src/Xamarin.iOS/Foundation/NSObject2.cs:221
critical:   at Foundation.NSObject.Dispose (bool) [0x00025] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.11.0.280/src/Xamarin.iOS/Foundation/NSObject2.cs:749
critical:   at Foundation.NSObject.Dispose () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.11.0.280/src/Xamarin.iOS/Foundation/NSObject2.cs:133
critical:   at ObjCRuntime.Runtime.ThreadPoolDispatcher (System.Func`1<bool>) [0x0000f] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.11.0.280/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:280
critical:   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00009] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.11.0.280/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1210
critical:   at (wrapper runtime-invoke) object.runtime_invoke_dynamic (intptr,intptr,intptr,intptr) [0x0001e] in <cf0309ffa9be4853bd91f2dd74762f76#6C99B432-C572-8B9D-08BF-EED3B80DE38D>:0
critical: 
critical: 	0   libmonosgen-2.0.dylib               0x0000000102a6d5cc mono_handle_native_crash + 224
critical: 	1   libmonosgen-2.0.dylib               0x0000000102a7a6fc mono_sigsegv_signal_handler + 316
critical: 	2   libsystem_platform.dylib            0x0000000182a60b58 _sigtramp + 52
critical: 	3   libobjc.A.dylib                     0x000000018201613c <redacted> + 844
critical: 	4   libobjc.A.dylib                     0x000000018201613c <redacted> + 844
critical: 	5   CoreFoundation                      0x0000000182d04aac _CFAutoreleasePoolPop + 28
critical: 	6   Foundation                          0x0000000183784160 <redacted> + 148
critical: 	7   libxamarin-debug.dylib              0x0000000102da48d4 xamarin_release_managed_ref + 212
critical: 	8   libXamarin.iOS.dll.dylib            0x0000000101ba2e68 wrapper_managed_to_native_Foundation_NSObject_xamarin_release_managed_ref_intptr_Foundation_NSObject + 104
critical: 	9   libXamarin.iOS.dll.dylib            0x0000000101ba3248 Foundation_NSObject_ReleaseManagedRef + 24
critical: 	10  libXamarin.iOS.dll.dylib            0x0000000101ba3e3c Foundation_NSObject_Dispose_bool + 108
critical: 	11  libXamarin.iOS.dll.dylib            0x0000000101ba2cf4 Foundation_NSObject_Dispose + 36
critical: 	12  libXamarin.iOS.dll.dylib            0x0000000101b75e84 ObjCRuntime_Runtime_ThreadPoolDispatcher_System_Func_1_bool + 148
critical: 	13  libmscorlib.dll.dylib               0x00000001005c4ce8 System_Threading__ThreadPoolWaitCallback_PerformWaitCallback + 136
critical: 	14  libmscorlib.dll.dylib               0x00000001006e3b18 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 248
critical: 	15  libmonosgen-2.0.dylib               0x0000000102a7d874 mono_jit_runtime_invoke + 904
critical: 	16  libmonosgen-2.0.dylib               0x0000000102b056e4 mono_runtime_try_invoke + 160
critical: 	17  libmonosgen-2.0.dylib               0x0000000102b374b0 worker_callback + 828
critical: 	18  libmonosgen-2.0.dylib               0x0000000102b35374 worker_thread + 1380
critical: 	19  libmonosgen-2.0.dylib               0x0000000102b3f6ec start_wrapper + 732
critical: 	20  libsystem_pthread.dylib             0x0000000182a65220 <redacted> + 272
critical: 	21  libsystem_pthread.dylib             0x0000000182a65110 <redacted> + 0
critical: 	22  libsystem_pthread.dylib             0x0000000182a63b10 thread_start + 4
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
```

### Steps to Reproduce

1. Write an app that does a lot of SceneKit work (creating nodes, moving nodes, creating geometries, etc.) in background threads
2. Note the above error from time to time

### Expected Behavior

I can work on SceneKit elements in background threads without issue.

### Actual Behavior

Occasional crashes in background threads

### Environment

```
=== Visual Studio Enterprise 2017 for Mac (Preview) ===

Version 7.6 Preview (7.6 build 711)
Installation UUID: 4ba352e1-73e8-4dab-a9db-28012ca05af8
Runtime:
	Mono 5.12.0.226 (2018-02/9824e260f56) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

	Package version: 512000226

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.0-preview2-26406-04
	2.0.3
SDK: /usr/local/share/dotnet/sdk/2.1.300-preview2-008530/Sdks
SDK Versions:
	2.1.300-preview2-008530
	2.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.3.1 (14154.1)
Build 9E501

=== Xamarin.Mac ===

Version: 4.5.0.280 (Visual Studio Enterprise)
Hash: e85a7be8
Branch: master
Build date: 2018-05-03 11:35:01-0400

=== Xamarin.Android ===

Version: 8.3.0.19 (Visual Studio Enterprise)
Android SDK: /Users/fak/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.0 (API level 24)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin.iOS ===

Version: 11.11.0.280 (Visual Studio Enterprise)
Hash: e85a7be8
Branch: master
Build date: 2018-05-03 11:35:00-0400

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706000711
Git revision: 634060c6c105fd3ee36678fe547680fd258cbf45
Build date: 2018-05-04 16:11:06-04
Xamarin extensions: c6720450018cb69a3da7c6d0aa0715c013783595
Build lane: monodevelop-lion-master

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Tue Dec 19 10:52:05 PST 2017
    root:xnu-4570.47.16~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

MSBuild Editor 2.0.3
Internet of Things (IoT) development (Preview) 7.5

```

**Comment by spouliot** [comment] 2018-05-23 12:27
Does this happens with 11.10 stable ?

c.c. @rolfbjarne

**Comment by praeclarum** [comment] 2018-05-23 16:02
I just tried with 11.10. A different error bubbles up, but this time ThreadPool isn't on the stack.

Does this look like a memory bug in my app? My code isn't doing anything too crazy. I'm trying to write a repro.

```
2018-05-23 08:59:26.739 Circuit2[3839:910763] critical:   at <unknown> <0xffffffff>
2018-05-23 08:59:26.739 Circuit2[3839:910763] critical:   at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain (int,string[],intptr,intptr) <0x00007>
2018-05-23 08:59:26.739 Circuit2[3839:910763] critical:   at UIKit.UIApplication.Main (string[],intptr,intptr) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/UIKit/UIApplication.cs:79
2018-05-23 08:59:26.739 Circuit2[3839:910763] critical:   at UIKit.UIApplication.Main (string[],string,string) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.178/src/Xamarin.iOS/UIKit/UIApplication.cs:63
2018-05-23 08:59:26.739 Circuit2[3839:910763] critical:   at Circuit2.Program.Main (string[]) [0x00001] in /Users/fak/Dropbox/Projects/Circuit2/Circuit/Program.cs:9
2018-05-23 08:59:26.739 Circuit2[3839:910763] critical:   at (wrapper runtime-invoke) object.runtime_invoke_dynamic (intptr,intptr,intptr,intptr) [0x0001e] in <8a48725212864358a4554e3196f5ca74#5322D0A1-F30D-1517-67BA-4790CBDC5A5C>:0
2018-05-23 08:59:26.739 Circuit2[3839:910763] critical: 
Native stacktrace:

2018-05-23 08:59:26.764 Circuit2[3839:910763] critical: 	0   libmonosgen-2.0.dylib               0x000000010707db24 mono_handle_native_crash + 224
2018-05-23 08:59:26.764 Circuit2[3839:910763] critical: 	1   libmonosgen-2.0.dylib               0x000000010708a680 mono_sigsegv_signal_handler + 316
2018-05-23 08:59:26.764 Circuit2[3839:910763] critical: 	2   libsystem_platform.dylib            0x0000000182a60b58 _sigtramp + 52
2018-05-23 08:59:26.764 Circuit2[3839:910763] critical: 	3   libobjc.A.dylib                     0x0000000181ff6ef4 <redacted> + 148
2018-05-23 08:59:26.764 Circuit2[3839:910763] critical: 	4   libobjc.A.dylib                     0x0000000181ff6ef4 <redacted> + 148
2018-05-23 08:59:26.764 Circuit2[3839:910763] critical: 	5   libobjc.A.dylib                     0x0000000182004990 objc_destructInstance + 68
2018-05-23 08:59:26.764 Circuit2[3839:910763] critical: 	6   libobjc.A.dylib                     0x00000001820049f8 object_dispose + 16
2018-05-23 08:59:26.764 Circuit2[3839:910763] critical: 	7   UIKit                               0x000000018ca1313c <redacted> + 200
2018-05-23 08:59:26.764 Circuit2[3839:910763] critical: 	8   libobjc.A.dylib                     0x000000018201613c <redacted> + 844
2018-05-23 08:59:26.764 Circuit2[3839:910763] critical: 	9   CoreFoundation                      0x0000000182d04aac _CFAutoreleasePoolPop + 28
2018-05-23 08:59:26.764 Circuit2[3839:910763] critical: 	10  UIKit                               0x000000018ccd16c4 <redacted> + 116
2018-05-23 08:59:26.764 Circuit2[3839:910763] critical: 	11  CoreFoundation                      0x0000000182de6910 <redacted> + 32
2018-05-23 08:59:26.764 Circuit2[3839:910763] critical: 	12  CoreFoundation                      0x0000000182de4238 <redacted> + 412
2018-05-23 08:59:26.764 Circuit2[3839:910763] critical: 	13  CoreFoundation                      0x0000000182de4884 <redacted> + 1436
2018-05-23 08:59:26.764 Circuit2[3839:910763] critical: 	14  CoreFoundation                      0x0000000182d04da8 CFRunLoopRunSpecific + 552
2018-05-23 08:59:26.764 Circuit2[3839:910763] critical: 	15  GraphicsServices                    0x0000000184ce7020 GSEventRunModal + 100
2018-05-23 08:59:26.764 Circuit2[3839:910763] critical: 	16  UIKit                               0x000000018cce578c UIApplicationMain + 236
2018-05-23 08:59:26.765 Circuit2[3839:910763] critical: 	17  libXamarin.iOS.dll.dylib            0x0000000106186660 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 368
2018-05-23 08:59:26.765 Circuit2[3839:910763] critical: 	18  libXamarin.iOS.dll.dylib            0x000000010615147c UIKit_UIApplication_Main_string___intptr_intptr + 44
2018-05-23 08:59:26.765 Circuit2[3839:910763] critical: 	19  libXamarin.iOS.dll.dylib            0x000000010615143c UIKit_UIApplication_Main_string___string_string + 172
2018-05-23 08:59:26.765 Circuit2[3839:910763] critical: 	20  libCircuit2.exe.dylib               0x000000010499c700 Circuit2_Program_Main_string__ + 128
2018-05-23 08:59:26.765 Circuit2[3839:910763] critical: 	21  libmscorlib.dll.dylib               0x0000000104e36108 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 248
2018-05-23 08:59:26.765 Circuit2[3839:910763] critical: 	22  libmonosgen-2.0.dylib               0x000000010708d778 mono_jit_runtime_invoke + 904
2018-05-23 08:59:26.765 Circuit2[3839:910763] critical: 	23  libmonosgen-2.0.dylib               0x000000010710c8a4 mono_runtime_invoke_checked + 148
2018-05-23 08:59:26.765 Circuit2[3839:910763] critical: 	24  libmonosgen-2.0.dylib               0x000000010711261c mono_runtime_exec_main_checked + 120
2018-05-23 08:59:26.765 Circuit2[3839:910763] critical: 	25  libmonosgen-2.0.dylib               0x000000010706f608 mono_jit_exec + 268
2018-05-23 08:59:26.765 Circuit2[3839:910763] critical: 	26  libxamarin-debug.dylib              0x00000001073b0cd8 xamarin_main + 2220
2018-05-23 08:59:26.765 Circuit2[3839:910763] critical: 	27  Circuit2                            0x0000000104869478 main + 96
2018-05-23 08:59:26.765 Circuit2[3839:910763] critical: 	28  libdyld.dylib                       0x0000000182795fc0 <redacted> + 4
2018-05-23 08:59:26.765 Circuit2[3839:910763] critical: 
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
```

**Comment by rolfbjarne** [comment] 2018-05-23 16:04
This looks like a memory bug, but it doesn't have to be in your app (it could be in iOS too for instance, and it wouldn't be the first time we've found iOS bugs).

In any case I'll need a way to reproduce it to track it down.

**Comment by praeclarum** [comment] 2018-05-23 17:09
I tried to write a minimal repro but the little bugger works flawlessly. It can give you a sense of what I'm doing though. Here it is:

[Issue4113NoRepro.zip](https://github.com/xamarin/xamarin-macios/files/2032071/Issue4113NoRepro.zip)

The fact that I couldn't get it to repro out of my app makes me realize it's probably not being caused by what I thought. The fact the the repro works also make me think it's less likely a bug in iOS...

So that's the bad news, the good news is it's really easy to repro in my app. I can make the code available if someone wants to repro the hard way.

**Comment by praeclarum** [comment] 2018-05-24 05:46
I am not sure if it's related, but I get some crashes in the wild that seem similar:

<img width="991" alt="screenshot 2018-05-23 22 45 27" src="https://user-images.githubusercontent.com/323548/40466536-062bc1c0-5edb-11e8-8286-ccd823b85e64.png">

**Comment by therealjohn** [comment] 2018-06-28 13:54
> I can make the code available if someone wants to repro the hard way.

@rolfbjarne Is using the app viable for you to reproduce this, per @praeclarum's offer?

**Comment by rolfbjarne** [comment] 2018-06-29 08:00
@therealjohn I've already tried, and I wasn't able to reproduce the crash. @praeclarum was going to modify the test case so that it wouldn't need continuous user interaction, and I'm waiting for this (for self reference it's tracked here (private repo): https://github.com/praeclarum/Circuit2/issues/1)

**Comment by mandel-macaque** [comment] 2018-08-01 09:49
@therealjohn  I will close the issue so that we have a clean backlog, please let us know if the bug was fixed or if we have to keep looking into it. If you have the modified test case it, please attach it an reopen the issue. Thanks in advance.

**Closed by mandel-macaque** 2018-08-01 09:49 UTC
Labels: bug, iOS, need-info
