### ISSUE TITLE
Regression: Hot Restart doesn't deploy native references

### ISSUE THREAD

**Issue by dotMorten** [xamarin/xamarin-macios#19363] opened 2023-10-26 19:07 UTC
When building an application that uses native references and deploying via Hot Restart, the application will crash the moment you make a call to a native library.

### Steps to Reproduce
1. Make sure you're using the .NET 8 RC2 SDK (vs preview, or non-preview with the "use preview sdk" checkbox checked).
2. Create a new .NET 7 application.
3. Add the nuget package `Esri.ArcGISRuntime.Maui` (this'll implicitly include `Esri.ArcGISRuntime.runtimes.iOS` which deploys native references) :
     `<PackageReference Include="Esri.ArcGISRuntime.Maui" Version="200.2.0" />`
4. in `MauiProgram.cs` add `using Esri.ArcGISRuntime.Maui;` and in in the builder add `.UseArcGISRuntime()`
5. Deploy and run the application. Notice the crash.
6. Repeat the operation, but this time use the .NET 7 SDK, and things will launch fine (ie non-preview VS with the "use preview sdk" unchecked). This time the app launches.
(Note: Deploying via remote-host to a mac works fine - only direct deploy on Windows fail)

### Expected Behavior
Application launches with no crash.

### Actual Behavior
Crash in UseArcGISRuntime() which leads to a native call.
```
[0:] An error occurred: '__Internal'. Callstack: '   at RuntimeCoreNet.GeneratedWrappers.CoreArcGISRuntimeEnvironment.SetInstallDirectory(String installPath)
   at Esri.ArcGISRuntime.ArcGISRuntimeEnvironment.InitNative()
   at Esri.ArcGISRuntime.ArcGISRuntimeEnvironment.InitializeRuntimeCore()
   at Esri.ArcGISRuntime.ArcGISRuntimeEnvironment.Initialize(Action`1 configure)
   at Esri.ArcGISRuntime.Maui.AppHostBuilderExtensions.UseArcGISRuntime(MauiAppBuilder builder, Action`1 configure)
   at Esri.ArcGISRuntime.Maui.AppHostBuilderExtensions.UseArcGISRuntime(MauiAppBuilder builder)
   at MauiApp12.MauiProgram.CreateMauiApp() in E:\sources.tmp\MauiApp12\MauiApp12\MauiProgram.cs:line 11
   at MauiApp12.AppDelegate.CreateMauiApp() in E:\sources.tmp\MauiApp12\MauiApp12\Platforms\iOS\AppDelegate.cs:line 8
   at Microsoft.Maui.MauiUIApplicationDelegate.WillFinishLaunching(UIApplication application, NSDictionary launchOptions)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at MauiApp12.Program.Main(String[] args) in E:\sources.tmp\MauiApp12\MauiApp12\Platforms\iOS\Program.cs:line 13
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)'
2023-10-26 11:28:23.399 Xamarin.PreBuilt.iOS[25823:3386266] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
```

If I look in the generated app output `AppData\Local\Temp\1\Xamarin\HotRestart\Signing\MauiApp13.app\out\Payload\MauiApp13.app\` the `Frameworks` subfolder is missing when using the NET 8 SDK.

### Environment

.NET Version: 8.0.100-rc.2.23502.2
VS Version: "VS 17.8.0 Preview 5" or "vs 17.7.5 with preview sdks enabled"

### Example Project (If Possible)

[MauiApp13.zip](https://github.com/xamarin/xamarin-macios/files/13181703/MauiApp13.zip)

**Comment by rolfbjarne** [comment] 2023-10-27 06:37
This is a duplicate of https://github.com/xamarin/xamarin-macios/issues/19278, which we've already fixed for the final .NET 8 release (I confirmed it with your test case too).

**Closed by rolfbjarne** 2023-10-27 06:37 UTC
Labels: windows-only, hotrestart
