### ISSUE TITLE
Getting "Dyld Error Message: Library not loaded: @rpath/Mono.framework/Mono" when attempting to debug Xamarin Forms project (with Notification Service Extension) on iPhone Simulator

### ISSUE THREAD

**Issue by jmelliadis** [xamarin/xamarin-macios#3690] opened 2018-03-07 18:54 UTC
### Steps to Reproduce

1. Downloaded latest Xamarin.iOS and Visual Studio for Mac updates
2. Attempted to run Xamarin Forms project on iPhone Simulator (project has a Notification Service Extension)

### Expected Behavior
App launches on Simulator
### Actual Behavior
App is uploaded to simulator, crashes before launch
### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.4 (build 1033)
Installation UUID: 4255a0d5-48c3-4e98-8894-69902da9081e
Runtime:
	Mono 5.8.0.129 (2017-10/835a98d8559) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000129

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.3
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.3
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.2.0.20 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.8.0.20 (Visual Studio Community)
Hash: 1c6f300e
Branch: d15-6
Build date: 2018-02-07 23:42:40-0500

=== Xamarin.Android ===

Version: 8.2.0.15 (Visual Studio Community)
Android SDK: /Users/jordan/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 23.0.3

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704001033
Git revision: 053991068f3c88497d3e5cc52fe7fdf57c28b62f
Build date: 2018-02-28 05:02:28-05
Xamarin addins: cc3283953e0af0b8bfab1bdfdf847d9e403c4606
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1

```

### Build Logs

[Build Log](https://gist.github.com/jmelliadis/e492f7a62026e03be07c77afb96b52e9)

[Crash Log](https://github.com/xamarin/xamarin-macios/files/1790454/iSurvey.iOS_2018-03-07-132620_Jordans-MacBook-Pro.txt)

**Comment by rolfbjarne** [comment] 2018-03-07 20:35
This is a duplicate of #3289.

Workaround: https://github.com/xamarin/xamarin-macios/issues/3289#issuecomment-363168764

**Closed by rolfbjarne** 2018-03-07 20:35 UTC
