### ISSUE TITLE
[net6] Native framework are not copied or not copied into the correct destination by default

### ISSUE THREAD

**Issue by Redth** [xamarin/xamarin-macios#12450] opened 2021-08-16 20:54 UTC
Originally posted in: https://github.com/dotnet/maui/issues/1916

### Description
An iOS application crashes if you add a binding library based on a custom native iOS framework.

### Steps to Reproduce
1. Create an iOS framework.
2. Create a binding library based on the framework.
3. Create an iOS App with the binding library.
4. Run the App.

### Expected Behavior
The application runs successfully.

### Actual Behavior
The application crashes.
```Termination Reason:    DYLD, [0x1] Library missing```

### Basic Information
Xcode Version: 13.0 beta 3
.NET Core SDK Version: 6.0.100-preview.6.21355.2
Xamarin.iOS Version: 14.20.0.24

### Reproduction Link
https://github.com/AnatolyChugaev/iOS-framework-crash

### Workaround
Put the framework into the application manually.

**Comment by spouliot** [comment] 2021-08-17 15:41
I can duplicate using the repo.
Tagging as `support` for now since we have similar tests that works, so I suspect it's a configuration issue (since a lot of things have changed in the build process).

**Comment by spouliot** [comment] 2021-08-18 19:50
There seems to be a nesting issue

```
$ find ./HelloiOS/bin/Debug/net6.0-ios/iossimulator-x64/HelloiOS.app -name test
./HelloiOS/bin/Debug/net6.0-ios/iossimulator-x64/HelloiOS.app/Frameworks/test.framework/test.framework/test
```

^ double `test.framework/test.framework`, likely caused by

```
/Users/poupou/git/bugs/iOS-framework-crash/Binaries/net6.0-ios/iossimulator-x64/NativeLibrary.resources/test.framework/test
    RelativePath = ../HelloiOS.app/Frameworks/test.framework/test.framework/test
    _FrameworkPath = ../HelloiOS.app/Frameworks/test.framework
    _FrameworkIdentity = /Users/poupou/git/bugs/iOS-framework-crash/Binaries/net6.0-ios/iossimulator-x64/NativeLibrary.resources/
    _FrameworkRelativePath = test.framework/test
    CopyToPublishDirectory = PreserveNewest
```

Our own tests are working but they have quite a few .csproj customizations which might be hiding the issue.

**Comment by spouliot** [comment] 2021-08-18 20:03
It looks like bindings made from dotnet are not embedded, c.c. @rolfbjarne 

IMO that's a good thing (and in sync with `xcframework` support) for build performance.
OTOH we should make `NoBindingEmbedding` default to `true` instead of requiring it inside the dotnet binding projects.

That explains why the `.framework` was not copied into the `.app`. The path issue (from previous comment) is a different issue.

```diff
diff --git a/binding_test/bind_test.csproj b/binding_test/bind_test.csproj
index 1e1a428..cf479a7 100644
--- a/binding_test/bind_test.csproj
+++ b/binding_test/bind_test.csproj
@@ -6,6 +6,7 @@
     <PlatformTarget>AnyCPU</PlatformTarget>
     <RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>
     <IsBindingProject>true</IsBindingProject>
+    <NoBindingEmbedding>true</NoBindingEmbedding>
     <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
     <NativeLibName>ios-fat</NativeLibName>
     <RootNamespace>NativeLibrary</RootNamespace>
diff --git a/build b/build
index eeb5196..54f9f68 100755
--- a/build
+++ b/build
@@ -1,3 +1,4 @@
+git clean . -xfd
 xcodebuild -project test/test.xcodeproj -target test -configuration Debug -arch x86_64 -sdk "iphonesimulator"
-dotnet build binding_test/bind_test.csproj
-dotnet build HelloiOS/HelloiOS.csproj
\ No newline at end of file
+dotnet build binding_test/bind_test.csproj /bl:bindings.binlog
+dotnet build HelloiOS/HelloiOS.csproj /bl:main.binlog
\ No newline at end of file
```

That diff will produce

```
$ tree Binaries/
Binaries/
└── net6.0-ios
    └── iossimulator-x64
        ├── NativeLibrary.dll
        ├── NativeLibrary.pdb
        ├── NativeLibrary.resources
        │   ├── manifest
        │   └── test.framework
        │       ├── Headers
        │       │   ├── CustomClass.h
        │       │   └── test.h
        │       ├── Info.plist
        │       ├── Modules
        │       │   └── module.modulemap
        │       ├── _CodeSignature
        │       │   └── CodeResources
        │       └── test
        └── ref
            └── NativeLibrary.dll

8 directories, 10 files
```

but the `.app` is incorrect

```
./HelloiOS/bin/Debug/net6.0-ios/iossimulator-x64/HelloiOS.app
...
├── Frameworks
│   └── test.framework
│       ├── manifest
│       └── test.framework
│           ├── Headers
│           │   ├── CustomClass.h
│           │   └── test.h
│           ├── Info.plist
│           ├── Modules
│           │   └── module.modulemap
│           ├── _CodeSignature
│           │   └── CodeResources
│           └── test
├── HelloiOS
├── HelloiOS.dll
├── HelloiOS.pdb
├── Info.plist
...
```

**Comment by rolfbjarne** [comment] 2021-08-19 08:03
> OTOH we should make `NoBindingEmbedding` default to `true` instead of requiring it inside the dotnet binding projects.

I would think it should still work though.

**Comment by spouliot** [comment] 2021-08-19 13:36
> I would think it should still work though.

I _think_ it works fine if the bindings are embedded (the default, except for xcframeworks, in legacy). So if you re-use the same bindings/project as legacy then things should work (native code extraction).

**Comment by rolfbjarne** [comment] 2021-09-10 19:18
I've done some work with regards to frameworks recently, and I can't reproduce any problems with the test project anymore, so I'm closing this. RC 2 will have the fixes.

**Closed by rolfbjarne** 2021-09-10 19:18 UTC
Labels: bug, dotnet, dotnet-pri0

**Comment by rolfbjarne** [comment] 2021-09-10 19:57
> It looks like bindings made from dotnet are not embedded, c.c. @rolfbjarne
> 
> IMO that's a good thing (and in sync with `xcframework` support) for build performance.
> OTOH we should make `NoBindingEmbedding` default to `true` instead of requiring it inside the dotnet binding projects.

https://github.com/xamarin/xamarin-macios/pull/12694
