### ISSUE TITLE
Unable to build iOS Binding Library wrapping iOS Framework Native Reference

### ISSUE THREAD

**Issue by jfversluis** [xamarin/xamarin-macios#16191] opened 2022-09-28 18:24 UTC
---
**Issue moved from dotnet/maui#10377**
- Please respond to @MikePendo.

---

_From @MikePendo on Wednesday, September 28, 2022 4:00:35 PM_

### Description

I have the same issue as described here:
[Unable to build iOS Binding Library wrapping iOS Framework Native Reference](https://github.com/dotnet/maui/issues/8000)
Not so sure why it was closed as the issue wasn't resolved at lease for the lates VS.
My binding seems to have the correct build with _.nupkg_ of the few mb (so I assume it does embed the Native SDK)
```
<Project Sdk="Microsoft.NET.Sdk">

 <!-- project definition --> 
  <PropertyGroup>
    <TargetFramework>net6.0-ios</TargetFramework>
    <RootNamespace>p_binding_ios</RootNamespace>
    <UseMaui>true</UseMaui>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <IPhoneResourcePrefix>Resources</IPhoneResourcePrefix>
    <PackageVersion>2.19.2</PackageVersion>
    <PackageId>p-binding-ios</PackageId>
    <IsBindingProject>true</IsBindingProject>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<NoBindingEmbedding>false</NoBindingEmbedding>
    <PackOnBuild>true</PackOnBuild>
  </PropertyGroup>

  <!-- build nuget in visual studio --> 
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
  </PropertyGroup>

  <!-- specifics -->
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <MtouchLink>SdkOnly</MtouchLink>
    <MtouchHttpClientHandler>HttpClientHandler</MtouchHttpClientHandler>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <MtouchLink>SdkOnly</MtouchLink>
    <MtouchHttpClientHandler>HttpClientHandler</MtouchHttpClientHandler>
  </PropertyGroup>
  <ItemGroup>
    <ObjcBindingApiDefinition Include="ApiDefinition.cs" />
    <ObjcBindingCoreSource Include="Structs.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="NativeReferences\" />
  </ItemGroup>

  <ItemGroup>
    <!--<ObjcBindingNativeLibrary Include=".\Native References\P.xcframework"></ObjcBindingNativeLibrary>-->
   <NativeReference Include=".\Native References\P.xcframework">
      <Kind>Framework</Kind>
      <SmartLink>False</SmartLink>
    </NativeReference> 
  </ItemGroup>

</Project>
```

Then I try to embed the binding in Maui test app .
So I have the following warning  which I couldn't follow as for no access error
```
/Users/m/Projects/TestMauiApp/TestMauiApp/ILLINK: Warning MT1302: Could not extract the native library 'P.framework' from '/Users/m/Projects/TestMauiApp/TestMauiApp/obj/Debug/net6.0-ios/iossimulator-x64/linker-cache/P.framework.zip'. Please ensure the native library was properly embedded in the managed assembly (if the assembly was built using a binding project, the native library must be included in the project, and its Build Action must be 'ObjcBindingNativeLibrary'). (MT1302) (TestMauiApp)
```
and the following errors :
```
/Users/m/Projects/TestMauiApp/TestMauiApp/ILLINK: Error MT0140: File '/Users/m/Projects/TestMauiApp/TestMauiApp/obj/Debug/net6.0-ios/iossimulator-x64/linker-cache/P.framework/P' is not a valid framework. (MT0140) (TestMauiApp)
```
The native framework is not in the that location so obviously its not valid 
I am new to Xamarin development.
The Idea is to create shared maui plugin which will embed android and iOS native libs.
Currently I cant force iOS to work. (If I embed the binding to Maui plugin and try to add the plugin in the app I have the same error). So  I am trying to work with binding only for now 

### Steps to Reproduce

basically identical to that issue:
[Unable to build iOS Binding Library wrapping iOS Framework Native Reference](https://github.com/dotnet/maui/issues/8000)

### Link to public reproduction project repository

https://drive.google.com/drive/folders/1E_dtfyK_Ui334X_FOK5hQa-fhY8bDt0-?usp=sharing

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5

### Did you find any workaround?

NO

### Relevant log output

```shell
/Users/m/Projects/TestMauiApp/TestMauiApp/ILLINK: Warning MT1302: Could not extract the native library 'P.framework' from '/Users/m/Projects/TestMauiApp/TestMauiApp/obj/Debug/net6.0-ios/iossimulator-x64/linker-cache/P.framework.zip'. Please ensure the native library was properly embedded in the managed assembly (if the assembly was built using a binding project, the native library must be included in the project, and its Build Action must be 'ObjcBindingNativeLibrary'). (MT1302) (TestMauiApp)

/Users/m/Projects/TestMauiApp/TestMauiApp/ILLink: Error IL7000: An error occured while executing the custom linker steps. Please review the build log for more information. (IL7000) (TestMauiApp) iOS

/Users/m/Projects/TestMauiApp/TestMauiApp/ILLINK: Error MT0140: File '/Users/m/Projects/TestMauiApp/TestMauiApp/obj/Debug/net6.0-ios/iossimulator-x64/linker-cache/P.framework/P' is not a valid framework. (MT0140) (TestMauiApp)

/usr/local/share/dotnet/sdk/6.0.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(5,5): Error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. (NETSDK1144) (TestMauiApp)
```

**Comment by jfversluis** [comment] 2022-09-28 18:24
---
**Issue moved from dotnet/maui#10377**
- Please respond to @mattleibow.

---

_From @mattleibow on Wednesday, September 28, 2022 6:11:32 PM_

May be related to https://github.com/dotnet/maui/issues/10344

**Comment by MikePendo** [comment] 2022-09-28 18:37
@jfversluis 
I dont think its related to [10344](https://github.com/dotnet/maui/issues/10344)
1. its a different types of libs that are used static vs Xcframework  
2. The error is totally  different _undefined sympbols_ which means it cant find the symbols in my case it cant find the SDK.
Please do not close the issue.
I see a lot of issues in this repo are being closed and linked to different issues which are not always has the root cause or the symptoms of the initial issue!

**Comment by MikePendo** [comment] 2022-10-03 19:40
@tj-devel709 
I have provided sample project, wont it be easier to use/try/break that one  and see if u manage to reproduce the issue.... (instead of digging in somebody else logs)

**Comment by rolfbjarne** [comment] 2022-10-04 09:30
Try removing the `<NoBindingEmbedding>false</NoBindingEmbedding>` line from your project file, we don't support embedding xcframeworks in the binding assembly.

**Comment by MikePendo** [comment] 2022-10-04 14:16
@rolfbjarne 
I have removed the line from the _PendoBindingIOS_ cleaned and rebuild as previously it seems like worked (then .nupkg size is few mb which makes sense). BUT when this plugin is embeded into PendoMauiPlugin the size is few kb i.e it doesnt really worked .
I have tried to add the _PendoBindingIOS_ to the sample app but still having the same issue.
Have u tried the sample project I have attached?
So if u dont support Xcframewrok should I try to use only fat framework (although I did see in couple of threads that Xcframewroks are kinda working)?
Can u please share a link reference to the _NoBindingEmbedding_  field and to any other additional fields for the _.csproj_?

**Comment by rolfbjarne** [comment] 2022-10-04 14:23
@MikePendo can you share your main project that consumes the binding project so we can be sure we're testing the same thing?

**Comment by MikePendo** [comment] 2022-10-04 14:37
@rolfbjarne 
Sure [Maui](https://drive.google.com/drive/folders/1Z4-wN_Ib9FSGedVInPG5eRF8fP-cd70A?usp=sharing)
I have included Xcframewrk and Fat framework build in the upper directory (if u want to try).
So basically the bindingIOS will be wrapped MauiPlugin that will ship iOS and Android but unfortunately I cant embed neither of the in the sample app

**Comment by MikePendo** [comment] 2022-10-07 13:25
@rolfbjarne 
Have u manage to look in to it

**Comment by rolfbjarne** [comment] 2022-10-07 16:21
It looks like your framework is a swift framework.

Try adding this NuGet to your executable project:

```xml
 <PackageReference Include="Xamarin.iOS.SwiftRuntimeSupport" Version="0.2.1" />
```

**Comment by MikePendo** [comment] 2022-10-07 17:19
@rolfbjarne 
Thanks will look into it.
Can u please share a reference where can I read about those XML tags? like `PackageReference`

**Comment by MikePendo** [comment] 2022-10-10 21:04
@rolfbjarne 
There r 2 projects in this ticket 
The one u have tried 
1.  [ https://drive.google.com/drive/folders/1E_dtfyK_Ui334X_FOK5hQa-fhY8bDt0-?usp=sharing](https://drive.google.com/drive/folders/1E_dtfyK_Ui334X_FOK5hQa-fhY8bDt0-?usp=sharing)
2. The one u have asked to see which is the full project [https://drive.google.com/drive/folders/1Z4-wN_Ib9FSGedVInPG5eRF8fP-cd70A](https://drive.google.com/drive/folders/1Z4-wN_Ib9FSGedVInPG5eRF8fP-cd70A)

When I build via GUI the project that u r building it get build with correct size of 30M 
The issue starts when I try  to add the binding build in to the app OR in to the Maui plugin (which should include both iOS and Android).
Can u try to add your build in to new maui app? will that work for u?
(I have already tried without `<NoBindingEmbedding>false</NoBindingEmbedding>` and the size is correct one, just did everything in GUI, I will try as suggested to do from command line)

**Comment by MikePendo** [comment] 2022-10-11 20:46
@rolfbjarne 
did u manage too try to add the build in maui app?

**Comment by rolfbjarne** [comment] 2022-10-14 17:09
I added a very simple test app and added the library project as a reference, and added a native linker argument so that ioS can find the swift libraries, and then the app launches for me in the simulator.

This is your code + mine: https://www.dropbox.com/s/1gxb2ibtsg981ex/Maui-134e6f8.zip?dl=0

The test app I added is in PendoMAUIPlugin/PendoTestApp.

**Comment by MikePendo** [comment] 2022-10-19 13:45
@rolfbjarne 
Thanks a lot, looking into it

**Comment by MikePendo** [comment] 2022-10-19 16:29
@rolfbjarne 
I am not sure what exactly u want to achieve in the project
I see in the PendoTestApp
`<ItemGroup>
    <ProjectReference Include="../PendoMAUIPlugin/PendoMAUIPlugin.csproj" />
  </ItemGroup>`
So u r trying to link the project? We supply a nugget package  so we need to link the the product of PendoMauiPlugin not the project.
The PendoBindingIOS is correctly build (the same correct build is happening in my project).
For instance when I try to add the Binding to your test app :
`</ItemGroup>
  <ItemGroup>
    <PackageReference Include="pendo-binding-ios" Version="2.19.2" />
  </ItemGroup>`
  I am receiving the same error  (have u tried to do it)?
  When I try to build the MauiPlugin I cant as it requires Mac catalyst which PendoBinding doesnt support (I am wondering how u manage to build it).<br> If I remove that target dependency I obviously can build the MauiPlugin but the size is couple of KB i.e it doesn't includes the binding.

**Comment by rolfbjarne** [comment] 2022-10-20 08:49
> I am receiving the same error (have u tried to do it)?

No, but that's why we request a _complete_ way to reproduce the problem, so that we're testing the same thing.

In any case, I've changed the test project to use a package reference, and it still works: https://www.dropbox.com/s/ztsg7wyxtmt51hj/Maui-34ea05f.zip?dl=0

There's also a script (`PendoMAUIPlugin/repro.sh`) that I used to build and run the sample project, and it works fine for me (the test app launches successfully in the simulator).

**Comment by jingliancui** [comment] 2022-10-20 09:04
Hey everyone, Here's the solution:
Please refer to this learning video:
https://learn.microsoft.com/en-us/events/dotnetconf-focus-on-maui/binding-native-libraries-for-dotnet-maui

The key is add this node:
`<NoBindingEmbedding>False</NoBindingEmbedding>`

Let us go to see the different before add this node:
<img width="438" alt="image" src="https://user-images.githubusercontent.com/16309962/196905019-34e6009a-648c-436e-82e5-e698926f8bb1.png">

After added this node:
<img width="437" alt="image" src="https://user-images.githubusercontent.com/16309962/196904534-9adff280-ab5c-42a3-a7d8-703e76920662.png">

I don't know why the default binding project remove this node. 

Any way, I hope the docs about binding for MAUI can be publish asap. 
Another addition thing like `<NoBindingEmbedding>False</NoBindingEmbedding>` , I hope these nodes can be written into docs too.

**Comment by MikePendo** [comment] 2022-10-25 12:52
Sorry people couldnt find time to look into it (please dont close) I want to verify the solution during the week

**Comment by rolfbjarne** [comment] 2022-11-03 21:04
@jingliancui that doesn't sound related to this issue, so please file a new issue and we can discuss it there (this avoids confusion in this issue when different comments talk about different things).

**Comment by jingliancui** [comment] 2022-11-04 07:06
@rolfbjarne sure, thanks
https://github.com/xamarin/xamarin-macios/issues/16580

**Comment by jingliancui** [comment] 2022-12-02 16:46
https://github.com/xamarin/xamarin-macios/issues/16953

hope this will help you

**Comment by rolfbjarne** [comment] 2022-12-20 08:09
@MikePendo were you able to make it work?

**Closed** 2022-12-27 09:01 UTC
Labels: need-info, binding-projects
