### ISSUE TITLE
[Bug] iOS API call made using HttpClient call gets cancelled when we swipe to open Control center

### ISSUE THREAD

**Issue by muffadal53** [xamarin/xamarin-macios#9176] opened 2020-07-23 14:25 UTC
### Description

We we making an API call using **HttpClient** and while the call is in progress meanwhile if we open iOS control center on iphone using bottom swipe the API call fails.

### Steps to Reproduce

1. Make an API call using **HttpClient** on iOS.
2. While the API call is progress try to open iOS control center using swipe.
3. The API call gets cancelled.

### Expected Behavior

The API call should continue and complete even if we just open iOS Control Center.

### Actual Behavior

The API call gets currently in progress cancelled.

### Basic Information

XF version: 4.3.0.991221

- IDE: Visual Studio 2019 16.5.3
- Platform Target Frameworks:
  - iOS:  13.6
- Affected Devices: iOS (iPhone, iPad)

**Comment by chamons** [comment] 2020-07-24 15:57
Are you setting the session background? Else I believe iOS will by default cancel you once you leave the foreground.

Please post an example of your API usage here, else we will not be able to intelligently comment on your issue.

**Comment by muffadal53** [comment] 2020-07-24 17:02
> Are you setting the session background? Else I believe iOS will by default cancel you once you leave the foreground.
> 
> Please post an example of your API usage here, else we will not be able to intelligently comment on your issue.

Hi @chamons 

I don't set session background in Xamarin forms Application. I just use the HttpClient to call respective API and then dispose the same as mentioned below.

- Usage:

`this.getHttpClient = new HttpClient
{	
	Timeout = TimeSpan.FromSeconds(30)
};

this.getHttpClient.DefaultRequestHeaders.Add(ACCEPT, ACCEPT_TYPE_JSON);
HttpResponseMessage response = await this.getHttpClient.GetAsync(requestUri);`

- Dispose:

`this.getHttpClient.Dispose();`

Can you kindly help me how to I set the background session in Xamarin forms application so that the API call doesn't get cancelled.

Thanks.

**Comment by chamons** [comment] 2020-07-24 17:29
Ok, I did some research, and if you are using HttpClient directly, and not NSUrlSessionHandler this is expected behavior. 

My fellow engineer wrote it up in great detail [here](https://github.com/xamarin/xamarin-macios/issues/6443#issuecomment-509585929) but in short:

"Once your application leaves the forground, we have to kill outstanding network requests because the threadpool that runs them could be stopped at iOS's whims and that would cause your application to freeze.

You can catch this in a try catch and re-try later.

However, we have a candidate improvement/fix for this, which is described in detail here:

https://github.com/xamarin/xamarin-macios/issues/7080#issuecomment-609945804

**Closed by chamons** 2020-07-24 17:29 UTC
Labels: iOS, need-info

**Comment by muffadal53** [comment] 2020-07-24 19:12
> Ok, I did some research, and if you are using HttpClient directly, and not NSUrlSessionHandler this is expected behavior.
> 
> My fellow engineer wrote it up in great detail [here](https://github.com/xamarin/xamarin-macios/issues/6443#issuecomment-509585929) but in short:
> 
> "Once your application leaves the forground, we have to kill outstanding network requests because the threadpool that runs them could be stopped at iOS's whims and that would cause your application to freeze.
> 
> You can catch this in a try catch and re-try later.
> 
> However, we have a candidate improvement/fix for this, which is described in detail here:
> 
> [#7080 (comment)](https://github.com/xamarin/xamarin-macios/issues/7080#issuecomment-609945804)

Hi @chamons,

So if I understand correctly you mean that If I use "NSUrlSessionHandler" in my xamarin forms application only for iOS then the HttClient API call won't get cancelled when the application leaves foreground?

Thanks.

**Comment by mandel-macaque** [comment] 2020-07-27 16:00
Hello,

If you httpclient is not going to be making long lasting requests, that is, you are not performing any download, approach 2 is the preferred one, otherwise use a background session.

The approach 2 will be the default in the future, but it is needed due to an old issue on the mono side that was fixed.
