### ISSUE TITLE
Environment-specific info plist files no longer show after Xamarin iOS 13.14.1.39 update

### ISSUE THREAD

**Issue by justintoth** [xamarin/xamarin-macios#8181] opened 2020-03-24 14:31 UTC
### Steps to Reproduce

1. Create environment-specific info.plist files in a Xamarin iOS app like so:

```
<None Include="Info.dev.plist" Condition="'$(Configuration)' == 'iOS-Dev-Debug' OR '$(Configuration)' == 'iOS-Dev-Release'">
      <LogicalName>Info.plist</LogicalName>
      <SubType>Designer</SubType>
    </None>
    <None Include="Info.test.plist" Condition="'$(Configuration)' == 'iOS-Test-Debug' OR '$(Configuration)' == 'iOS-Test-Release'">
      <LogicalName>Info.plist</LogicalName>
      <SubType>Designer</SubType>
    </None>
    <None Include="Info.prod.plist" Condition="'$(Configuration)' == 'iOS-Prod-Debug' OR '$(Configuration)' == 'iOS-Prod-Release'">
      <LogicalName>Info.plist</LogicalName>
      <SubType>Designer</SubType>
    </None>
```

2. Upgrade to Xamarin iOS 13.14.1.39.
3. Notice in Solution Explorer that ONLY Info.dev.plist is displayed, Info.test.plist and Info.prod.plist are missing even though they are still included in the project file.

### Expected Behavior

Info.test.plist and Info.prod.plist should be displayed in Solution Explorer.

### Actual Behavior

Info.test.plist and Info.prod.plist are not displayed in Solution Explorer.

<img width="267" alt="Screen Shot 2020-03-24 at 10 30 47 AM" src="https://user-images.githubusercontent.com/1443831/77437041-94710180-6dba-11ea-81e0-1d6e529cbb67.png">

### Environment

=== Visual Studio Community 2019 for Mac ===

Version 8.5 (build 3183)
Installation UUID: a5cb7345-33b8-43d1-ad0a-06c1922a4877
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.14.1.39 (d16-5 / 30e8706b4)

	Package version: 608000123

=== Mono Framework MDK ===

Runtime:
	Mono 6.8.0.123 (2019-10/1d0d939dc30) (64-bit)
	Package version: 608000123

=== Roslyn (Language Service) ===

3.5.0-beta4-20125-04+1baa0b3063238ed752ad1f0368b1df6b6901373e

=== NuGet ===

Version: 5.4.0.6315

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.102/Sdks
SDK Versions:
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.2.203
	2.1.505
	2.1.504
	2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.2.4
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.9
	2.1.8
	2.1.2

=== Xamarin Designer ===

Version: 16.5.0.471
Hash: 35aa4889d
Branch: remotes/origin/d16-5
Build date: 2020-02-25 00:52:08 UTC

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.3.1 (15715)
Build 11C504

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 13.14.1.39 (Visual Studio Community)
Hash: 30e8706b4
Branch: d16-5
Build date: 2020-02-20 16:41:48-0500

=== Xamarin.Android ===

Version: 10.2.0.100 (Visual Studio Community)
Commit: xamarin-android/d16-5/988c811
Android SDK: /Users/justintoth/Library/Android/sdk
	Supported Android versions:
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.6
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: c0c5c78
Java.Interop: xamarin/java.interop/d16-5@fc18c54
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/justintoth/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.5.0.39
Hash: 6fb4c79
Branch: remotes/origin/d16-5
Build date: 2020-02-20 23:25:56 UTC

=== Android Device Manager ===

Version: 16.5.0.71
Hash: 49194e8
Branch: remotes/origin/d16-5
Build date: 2020-02-20 23:26:18 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 805003183
Git revision: 60e06e010baa677204535600661dda3fb4677c2f
Build date: 2020-03-20 06:18:03-04
Build branch: release-8.5
Xamarin extensions: 60e06e010baa677204535600661dda3fb4677c2f

=== Operating System ===

Mac OS X 10.15.3
Darwin 19.3.0 Darwin Kernel Version 19.3.0
    Thu Jan  9 20:58:23 PST 2020
    root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

**Comment by chamons** [comment] 2020-03-24 20:09
Thanks for the report. This appears to be an IDE specific issue, so I've used a tag to create an internal bug for review.

You are also welcome to file an issue at https://developercommunity.visualstudio.com/ if you'd like.

**Comment by mrward** [comment] 2020-03-24 20:32
To support .NET Core 3 there was a change made to VS Mac to consider conditions in the project file (at least on initial load - currently it does not update when the configuration changes in the main status bar) .NET Core has files conditionally included and was causing duplicate files in the IDE.

VS on Windows should also not show all these files in its Solution window since not all the configurations are active at the same time.

**Comment by chamons** [comment] 2020-03-24 20:36
@mrward - So is this a bug that should move to VSfM or expected new behavior?

**Comment by mrward** [comment] 2020-03-24 20:40
It is expected behaviour in VS Mac now.

**Comment by chamons** [comment] 2020-03-24 20:40
Closing due to ^.

**Closed by chamons** 2020-03-24 20:40 UTC
Labels: external-visual-studio-for-mac

**Comment by justintoth** [comment] 2020-04-03 17:02
@mrward @chamons I would contend that this is not expected behavior, it's a regression on how VS for Mac and Xamarin Studio have worked for years. As you said, "currently it does not update when the configuration changes in the main status bar". To edit all three of my environment plist files, I would have to go through this process:

1. Open VS for Mac with environment A configuration set.
2. Edit the environment A plist file.
3. Change to environment B configuration.
4. Close and reopen VS for Mac.
5. Edit the environment B plist file.
6. Change to environment C configuration.
7. Close and reopen VS for Mac.
8. Edit the environment C plist file.

That is hardly a good UX for simply editing 3 files.

**Comment by mrward** [comment] 2020-04-03 18:02
Agreed it is not good UX. VS Mac should update the list of files based on the active configuration which it does not. There is an internal bug tracking this problem in VS Mac.

**Comment by justintoth** [comment] 2020-04-03 18:13
@mrward Can you put a note on that internal ticket to update this thread when that is resolved, so I can retest it?

**Comment by mrward** [comment] 2020-04-03 18:14
I have added a link to this github issue on the internal ticket.

**Comment by jthegeman** [comment] 2021-02-05 16:19
Any updates on this? 

Having to unload the iOS project and reload it, or close the project and re-open it is somewhat of a pain.

Currently I switch to having the stage and release info.plist in a different folder and then in the Azure Build pipeline I copy the correct one into the iOS root project, replacing the Dev one.
