### ISSUE TITLE
productbuild crashes on Monterey with os key set in plist

### ISSUE THREAD

**Issue by ivanicin** [xamarin/xamarin-macios#13197] opened 2021-11-01 16:33 UTC
### Steps to Reproduce

1. Create a new Mac project with the latest versions of VS, Xcode and **macOS Monterey** (the last one is likely causing the problem). 
2. Switch to Release mode and build with installer enabled
3. Build crashes

### Workaround

https://github.com/xamarin/xamarin-macios/issues/13197#issuecomment-958745845

### Expected Behavior
The app is built successfully.

### Actual Behavior

https://gist.github.com/chamons/261accfaee570a33e1f715a18d2a4d73

### Environment

https://gist.github.com/chamons/270981b17de48861dc900219d3d481c3

### Example Project (If Possible)

[Test.zip](https://github.com/xamarin/xamarin-macios/files/7454726/Test.zip)

**Comment by ivanicin** [comment] 2021-11-01 16:40
@chamons  @dalexsoto as far as I can tell this means that at the moment Xamarin.Mac is useless for major use cases as it can't output anything with installer. While this is likely limited only to macOS Monterey (I would guess I don't have other devices to test)  I hope you will take it as a priority over other bugs.

**Comment by cybnz** [comment] 2021-11-02 03:53
Also on macOS Monterey, also get "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.Common.targets(3,3): Error MSB6006: "productbuild" exited with code 134. (MSB6006) (HelloWorld.MacOS)".  Will try testing with an older version to see if issue persists.

**Comment by ivanicin** [comment] 2021-11-02 12:22
@cybnz after checking few more threads on the internet about this, I can pretty sure conclude this:

- this issue affects all M1 devices and it has started to affect Intel devices since Monterey update
- it was reported to Microsoft already two months ago but it was ignored: https://developercommunity.visualstudio.com/t/visual-studio-2019-mac-m1-xamarin-forms-macos-buil/1540290 (also Microsoft support has confirmed to read it here: https://stackoverflow.com/questions/69206855/cannot-build-an-installer-for-a-cocoaapp-xamarin-forms-on-visual-studio-for-ma/69810175#69810175)
- it is not clear why it was ignored because I am quite sure that the person that has answered (@chamons ) knows that his answer there was wrong in the context of the report, but possibly he did something in a hurry. But it is quite clear that no one tried to reproduce the problem though it takes just few minutes to do that. 

And this is not isolated incident, the quality of Xamarin.Mac is in constant decline with some things being released that would be unacceptable even for Alpha testing and being ignored and not fixed (just as an example share extension is not working for almost a year and it is shipped and no one cares https://github.com/xamarin/xamarin-macios/issues/10911). Let's see what happens here, but if this doesn't get any attention the project is definitely at the trash quality level.

**Comment by chamons** [comment] 2021-11-02 15:45
I was just able to build a Hello world application on my `MacBook Pro (13-inch, M1, 2020)` with Xamarin.Mac and install it without a crash.

I am going to look into your sample and will report back, but this does not seem to be an unconditional issue as it works for at least me on an M1.

**Comment by cristiandolf** [comment] 2021-11-02 16:16
I confirm the bug. I have updated my Macbook (intel) to Monterey and now my Xamarin.Mac app doesn't build in Release mode.

**Comment by ivanicin** [comment] 2021-11-02 16:29
> 
> 
> I was just able to build a Hello world application on my `MacBook Pro (13-inch, M1, 2020)` with Xamarin.Mac and install it without a crash.
> 
> I am going to look into your sample and will report back, but this does not seem to be an unconditional issue as it works for at least me on an M1.

I don't have M1 device so I have believed that the report by that user was correct that M1 is affected on Big Sur too.

I cannot see if you have tested on Big Sur or Monterey. There are four confirmed cases for Monterey and most of them appear to be Monterey only. If you have tested on Big Sur then you need to test on Monterey.

There is no need to test my sample in particular, if it doesn't work it doesn't work on any project, I have just added that to ensure that someone doesn't skip for the reason 'there is no sample' - unfortunately I have seen that too.

**Comment by chamons** [comment] 2021-11-02 16:36
We are looking into the Monterey angle now, to see if it reproduces there for us.

Please note that in all of the logs currently sent we are crashing inside of productbuild:

```
Error MSB6006: "productbuild" exited with code 134. (MSB6006) (HelloWorld.MacOS)". Will try testing with an older version to see if issue persists.
```

```
 /usr/bin/productbuild --product /Users/ivanicin/Projects/Test/Test/obj/Release/Product.plist --component /Users/ivanicin/Projects/Test/Test/bin/Release/Test.app /Applications /Users/ivanicin/Projects/Test/Test/bin/Release/Test-1.0.pkg
2021-11-01 17:25:26.081 productbuild[10168:110746] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSMutableOrderedSet unionOrderedSet:]: ordered set argument is not an NSOrderedSet'
*** First throw call stack:
(
0 CoreFoundation 0x00007ff81789de5b __exceptionPreprocess + 242
```

 /usr/bin/productbuild is a component of Xcode, not something contained within Xamarin.Mac. So this may very likely turn out to be an issue that needs to be reported to Apple.

**Comment by chamons** [comment] 2021-11-02 16:37
@ivanicin @cristiandolf - If you want to help us pin this down more quickly, consider testing this:

- Open Xcode 13.1
- Create a new Mac project
- Build it in release and create an installer
- See if it crashes. If not, attach a build log.

**Comment by ivanicin** [comment] 2021-11-02 17:52
@chamons  Sure I am happy to help anytime. I’ll send as soon as I am by my Mac which is tomorrow.

**Comment by cybnz** [comment] 2021-11-02 18:20
@chamons Sorry if this is wrong, I'm new to this.  Just built a new Mac app in Xcode for release, no problems.  Below is the output.

`2021-11-03 07:18:58.323507+1300 Test123[63968:2412217] Checked for defaults IMKUseDistributedObjects.  result is 0
2021-11-03 07:18:58.323617+1300 Test123[63968:2412217] IMK will use XPC for App = com.benj.Test123, euid=501
2021-11-03 07:18:58.326864+1300 Test123[63968:2412217] IMKInputSession [0x6000023ce0a0 activate] Invoking activateServerWithReply:, from Main thread = 1, bundleID=com.apple.PressAndHold
2021-11-03 07:18:58.327015+1300 Test123[63968:2412217] IMKInputSession (activate) CFRunLoopAddObserver( 0x6000020c1a40 ) on IMKInputSessionXPCInvocation (0x6000004f0fc0), runLoopMode(s) = com.apple.run-loop-mode.view-bridge.blocks + CommonModes
2021-11-03 07:18:58.327089+1300 Test123[63968:2412217] IMKInputSession (activate) CFRunLoopObserver on IMKInputSessionXPCInvocation (0x6000004f0fc0) runLoop fired on IMK _replyObserver, (kCFRunLoopEntry)
2021-11-03 07:18:58.327133+1300 Test123[63968:2412217] IMKInputSession (activate) CFRunLoopObserver kCFRunLoopEntry - innerRunLoopCount=1, otherInnerRunLoopDetected=0
2021-11-03 07:18:58.327741+1300 Test123[63968:2412664] IMKInputSession -imkxpc_bundleIdentifierWithReply: delivered on IMK Client side!!
2021-11-03 07:18:58.327808+1300 Test123[63968:2412664] IMKInputSession -imkxpc_bundleIdentifierWithReply: waitCount = 1, Will Perform block on main thread in Mode='com.apple.run-loop-mode.view-bridge.blocks' + CFRunLoopWakeUp
2021-11-03 07:18:58.435369+1300 Test123[63968:2412217] [IMKInputSession imkxpc_bundleIdentifierWithReply:] ^() Perform block invoked
2021-11-03 07:18:58.435799+1300 Test123[63968:2412664] IMKInputSession -imkxpc_windowLevelWithReply: delivered on IMK Client side!!
2021-11-03 07:18:58.435869+1300 Test123[63968:2412664] IMKInputSession -imkxpc_windowLevelWithReply: waitCount = 1, Will Perform block on main thread in Mode='com.apple.run-loop-mode.view-bridge.blocks' + CFRunLoopWakeUp
2021-11-03 07:18:58.435957+1300 Test123[63968:2412217] [IMKInputSession imkxpc_windowLevelWithReply] ^() Perform block invoked
2021-11-03 07:18:58.436172+1300 Test123[63968:2412664] IMKInputSession [0x6000023ce0a0 activate] ^() ReplyBlock invoked -> IMKInvocationInterrupt, bundleID=com.apple.PressAndHold
2021-11-03 07:18:58.436246+1300 Test123[63968:2412217] IMKClientInvocationInterruptCurrentXPCReply for SEL=activate - Perform Block (Main thread)
2021-11-03 07:18:58.436288+1300 Test123[63968:2412217] IMKClientInvocationInterruptCurrentXPCReply for SEL=activate - CFRunLoopTimerInvalidate( 0x6000024c6100 )
2021-11-03 07:18:58.436336+1300 Test123[63968:2412217] IMKClientInvocationInterruptCurrentXPCReply for SEL=activate - CFRunLoopStop( 0x600002dccd00 )
2021-11-03 07:18:58.437862+1300 Test123[63968:2412217] IMKInputSession (activate) CFRunLoopObserver on IMKInputSessionXPCInvocation (0x6000004f0fc0) runLoop fired on IMK _replyObserver, (kCFRunLoopExit)
2021-11-03 07:18:58.437924+1300 Test123[63968:2412217] IMKInputSession (activate) CFRunLoopObserver kCFRunLoopExit (State change BEGIN) - innerRunLoopCount=1, otherInnerRunLoopDetected=0
2021-11-03 07:18:58.437965+1300 Test123[63968:2412217] IMKInputSession (activate) CFRunLoopObserver kCFRunLoopExit (State change END) - innerRunLoopCount=0, otherInnerRunLoopDetected=0
2021-11-03 07:18:58.438010+1300 Test123[63968:2412217] IMKInputSession (activate) CFRunLoopRunInMode exited, (kCFRunLoopRunStopped)
2021-11-03 07:18:58.438050+1300 Test123[63968:2412217] IMKInputSession (activate) CFRunLoopRunInMode (kIMKXPCPrivateRunLoopMode) ] RunLoopFinished(1)/Stopped(2) - Run result = 2, (Invocation already done = 1) (Sentinel IsZombie = 0)
2021-11-03 07:18:58.438088+1300 Test123[63968:2412217] IMKInputSession (activate) CFRunLoopRunInMode() LOOP DONE!
2021-11-03 07:18:58.438139+1300 Test123[63968:2412217] IMKInputSession [0x6000023ce0a0 activate] activateServerWithReply : Call completed = 1 (noError=1), bundleID=com.apple.PressAndHold
`

**Comment by mathieubourgeois** [comment] 2021-11-03 04:38
I did some checks with `productbuild` with macOS Monterey (I was curious, since I made the original `CompileProductDefinitionTaskBase` that creates the `Product.plist` file used to create the pkg). The `Product.plist` file usually resembles something like

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>arch</key>
    <array>
      <string>x86_64</string>
      <string>arm64</string>
    </array>
    <key>os</key>
    <array>
      <string>10.15</string>
    </array>
  </dict>
</plist>
```

Trying to invoke `productbuild` with this plist, it indeed causes this crash on Monterey. I isolated that the problem is the `os` key; if I comment it out, it passes. It seems like it automatically finds the minimum version from the .app now, which didn't happen before. I've tried multiple ways to make the array pass, none worked. The man page also hasn't changed in that regard :

>     os                            Minimum allowable OS versions (array of strings)

So, it looks like this is a bug in macOS Monterey's implementation of productbuild. I guess that they create a set of strings from what they find from the .app, then try to create an union with the content of the plist's `os` property directly, but there is no way to create a set in a plist as far as I am aware, so if you provide an os version, it just crashes instead because it tries to create an union between a set and an array. This should definitely be reported to Apple, since the issue is on their end.

Sadly, on Xamarin's end, the way I wrote it initially means that, even if you pass your own custom plist, we ensure that the os key is set. So I don't see a way of circumventing the issue until Apple fixes it or Xamarin circumvents the issue by not setting the key on Monterey forward even though they are supposed to be able to.

**Comment by mathieubourgeois** [comment] 2021-11-03 04:59
> I did some checks with `productbuild` with macOS Monterey (I was curious, since I made the original `CompileProductDefinitionTaskBase` that creates the `Product.plist` file used to create the pkg). The `Product.plist` file usually resembles something like
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
>   <dict>
>     <key>arch</key>
>     <array>
>       <string>x86_64</string>
>       <string>arm64</string>
>     </array>
>     <key>os</key>
>     <array>
>       <string>10.15</string>
>     </array>
>   </dict>
> </plist>
> ```
> 
> Trying to invoke `productbuild` with this plist, it indeed causes this crash on Monterey. I isolated that the problem is the `os` key; if I comment it out, it passes. It seems like it automatically finds the minimum version from the .app now, which didn't happen before. I've tried multiple ways to make the array pass, none worked. The man page also hasn't changed in that regard :
> 
> > ```
> > os                            Minimum allowable OS versions (array of strings)
> > ```
> 
> So, it looks like this is a bug in macOS Monterey's implementation of productbuild. I guess that they create a set of strings from what they find from the .app, then try to create an union with the content of the plist's `os` property directly, but there is no way to create a set in a plist as far as I am aware, so if you provide an os version, it just crashes instead because it tries to create an union between a set and an array. This should definitely be reported to Apple, since the issue is on their end.
> 
> Sadly, on Xamarin's end, the way I wrote it initially means that, even if you pass your own custom plist, we ensure that the os key is set. So I don't see a way of circumventing the issue until Apple fixes it or Xamarin circumvents the issue by not setting the key on Monterey forward even though they are supposed to be able to.

Small addendum : from what I'm reading now, it is possible to create a set in a plist file. However,

- It only applies to the binary format, the xml/json format don't support it
- From what I can see, Xamarin's plist handling classes don't know how to handle a set in the binary format, so even if we provided a binary xml with the set instead of the array, pretty sure it would crash the build.

Anyway, it's a moot point, since the doc mentions (as it has always mentionned) that it takes an array of strings, so that's what it should do and Apple should fix it.

**Comment by cristiandolf** [comment] 2021-11-03 08:40
The error is: Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSMutableOrderedSet unionOrderedSet:]: ordered set argument is not an NSOrderedSet'

A workaround for now can be:
- open the Product.plist file built by Visual Studio for Mac (under obj/Release folder, you see the path from "build output" in VS)
- delete os key and save
- run the productbuild command from the Terminal. Es:
` /usr/bin/productbuild --product /Users/cgmac/Desktop/DEV/Projects/Karmatech/KTWizardTestMac10/KTWizardTestMac10/obj/Release/Product.plist --component /Users/cgmac/Desktop/DEV/Projects/Karmatech/KTWizardTestMac10/KTWizardTestMac10/bin/Release/KTWizardTest.app /Applications /Users/cgmac/Desktop/DEV/Projects/Karmatech/KTWizardTestMac10/KTWizardTestMac10/bin/Release/KTWizardTest-1.0.pkg`
- You will find the .pkg file under bin/Release folder

**Comment by ivanicin** [comment] 2021-11-03 11:55
> The error is: Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSMutableOrderedSet unionOrderedSet:]: ordered set argument is not an NSOrderedSet'
> 
> A workaround for now can be:
> 
>     * open the Product.plist file built by Visual Studio for Mac (under obj/Release folder, you see the path from "build output" in VS)
> ....

This looks like a very good workaround if this is true:
> It seems like it automatically finds the minimum version from the .app now, which didn't happen before.

However that word 'seems' doesn't sound too reassuring. Can someone confirm that removing the os key won't have any negative effect on the declared min version?

**Comment by cristiandolf** [comment] 2021-11-03 13:22
I ran my app and it works.
I think this field is for showing a warning when the user tries to run the app on a lower OS version.
In this case I think the app simply crashes without any warning.

**Comment by ivanicin** [comment] 2021-11-03 13:23
As far as I can tell it 

> This looks like a very good workaround if this is true:
> 
> > It seems like it automatically finds the minimum version from the .app now, which didn't happen before.

As far as I can tell this does work. I created a new app that requires Mojave, used the trick above and tried to install it on High Sierra and I've got a warning in the installation that the app requires Mojave.

**Comment by ivanicin** [comment] 2021-11-03 13:25
> 
> 
> I ran my app and it works. I think this field is for showing a warning when the user tries to run the app on a lower OS version. In this case I think the app simply crashes without any warning.

@cristiandolf working without that would be in acceptable in some cases, but in some cases it wouldn't. For example if you use App Store it is expected that the user can't download the app if it is not supported.

But the good news is that it works properly as far as I can tell.

**Comment by mathieubourgeois** [comment] 2021-11-03 14:21
I've reported the issue on my end to Apple through Feedback Assistant. I hope others do the same.

@cristiandolf While invoking productbuild directly might work for your use case, please be mindful that the pkg creation can pass other information to productbuild (for example, codesigning information for the installer, check https://github.com/xamarin/xamarin-macios/blob/main/msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CreateInstallerPackageTaskBase.cs for a general idea).

**Comment by chamons** [comment] 2021-11-03 14:29
Amazing detective work folks!

That absolutely sounds like a bug from Apple, and I would strongly suggest everyone file a issue through Feedback Assistant.

We could remove that key from our generated plist, but that would break some valid use cases. 

Despite the fact that we can't fix this bug in Xamarin, I'm going to leave this open for awhile to make it easier for others to find. 

Thanks again!

**Comment by ivanicin** [comment] 2021-11-03 15:02
> Despite the fact that we can't fix this bug in Xamarin, I'm going to leave this open for awhile to make it easier for others to find.

This is just my educated guess, so it may be completely wrong. But from what I have noted thus far this should be fixable in Xamarin. If you don't generate the os key on Monterey I expect everything to work OK. As noted by @mathieubourgeois that information is retrieved from .app file on Monterey so the deletion of key won't lead to side effects. And again as far as I can tell this is the only thing that stops from build to be completed.

As you can see in the comment above I did make a test and I can confirm that even if the os key is removed the information is pulled from somewhere else on Monterey and everything works as expected regarding the min os version.

So while this needs to be more broadly tested to be confirmed with 100% probability I don't see why the issue wouldn't be fixable from the Xamarin side if this is true.

**Comment by chamons** [comment] 2021-11-03 15:15
Maybe I'm missing something, but I believe the os key here is telling the installer "don't allow this to be installed if the OS is < 10.15".

If we remove generating this key, then your installer will run on older OSs and then crash on launch (assuming you make 10.15+ API calls).

I believe we harvest this version from your Info.plist.

Please correct me if I'm wrong here though.

**Comment by ivanicin** [comment] 2021-11-03 15:18
@chamons according to my tests you are wrong on Monterey.

I have created the installer with workaround suggested above and I couldn't use it to install on unsupported OS.

The information is pulled from somewhere else, @mathieubourgeois suggests that it is pulled from .app file which is probably true as I don't have any better idea.

**Comment by ivanicin** [comment] 2021-11-03 17:59
Also taking into account that it seems that Apple has removed redundant information and is now pulling information from another source I would rather consider this as yet undocumented improvement in Monterey and not the bug. Again assuming that what I perceive is correct.

**Comment by mathieubourgeois** [comment] 2021-11-03 19:23
While I do agree that it may be feasible for Xamarin to stop providing the `os` key from Monterey forward (supposing that `productbuild` indeed extracts it from the app now) I most definitely wouldn't consider that Xamarin's usage of the key is the bug here. Apple may have made an improvement by automatically grabbing this info if it's available in the .app, but they still broke support for their own public api which is still entirely reasonable to want to use in the process.

If Xamarin removes the `os` key from Monterey forward, they're only circumventing Apple's bug. Personally, I would prefer Apple fix their bug, and having as many people report the issue to Apple would probably help in that regards.

**Comment by ivanicin** [comment] 2021-11-03 20:02
I think we all agree that behavior doesn’t match the documentation. Calling that a bug is overstretching as the situation that the documentation hasn’t been updated is also perfectly legitimate. 

Considering that currently observed behavior is technically superior to previous behavior (please correct me if I miss out something that can’t be done now) and that updating this sort of documentation isn’t something that Apple does well, I would say that 99% this is not a bug. 

Please take into account that if you don’t have a real good argument to claim that this is a bug your suggestion is reckless as it may be wasting indefinite amount of time in waiting for something that won’t happen and that could be easily handled immediately.

**Comment by chamons** [comment] 2021-11-03 20:07
So a couple of things:

- Updating Visual Studio for Mac or the SDK is not a instant operation. Changes usually take at least a few weeks if not longer to go live.
- I'm not convinced that this behavior from Apple (of digging out the version from info.plist and not provided plist) is correct or even universal. We see it on one OS right now, and one that has a reputation for being a buggy initial release. 
- Do remember that Xamarin.Mac right now supports macOS 10.9+, so we'd have to test and confirm installers built with the changed plist correctly don't work that far back.

The OS key is absolutely documented behavior from Apple:

From man productbuild:
```
PRE-INSTALL REQUIREMENTS PROPERTY LIST
     When you use productbuild to synthesize a distribution (e.g. with the --component option), you can specify pre-install requirements in a separate property list file, specified
     with the --product option. (When you use Xcode to create a package for the Mac App Store, you can specify this file using the "Pre-install Requirements Property List" build set-
     ting.)

     At the top level, this property list is a dictionary, with the following keys:

     Key                       Description
     os                        Minimum allowable OS versions (array of strings)
```

**Comment by ivanicin** [comment] 2021-11-03 20:23
Ok, I’ll end up my comments here, hopefully they were constructive. 

My personal opinion is that the fact that Apple has implemented the alternative mechanism to pull the version info and stopped to support the old obsolete mechanism from working at the same time is very hard to be a coincidence and bug. 

At this point you will have to place a high profile bet, and decision to keep the things the same is also a bet that may or may not pay off. 

I fully understand that those few weeks might be necessary. But if you start the process in two months those few weeks will come on top of that. 

As you are responsible for the project I fully understand that you want to make the decision on your own, that is perfectly legitimate and may not fit my consideration.

**Comment by jaredjones** [comment] 2021-11-10 09:26
@mathieubourgeois I received your bug report today through Feedback Assistant.
There is no need to trouble Xamarin with this issue, we'll get it fixed soon in Monterey.

**Comment by jaredjones** [comment] 2021-11-10 09:41
@mathieubourgeois I received your bug report today through Feedback Assistant.
Thanks for using Feedback Assistant, that really is the only way to let us know that something is not working properly. It can also take a while for a bug report to land at the right person's desk, and for that bug-fix to be placed into the proper release vehicle.

There is no need to trouble Xamarin with this issue, we'll get it fixed soon in Monterey.

**Comment by jaredjones** [comment] 2021-11-10 09:48
> I've reported the issue on my end to Apple through Feedback Assistant. I hope others do the same.
> 
> @cristiandolf While invoking productbuild directly might work for your use case, please be mindful that the pkg creation can pass other information to productbuild (for example, codesigning information for the installer, check https://github.com/xamarin/xamarin-macios/blob/main/msbuild/Xamarin.MacDev.Tasks.Core/Tasks/CreateInstallerPackageTaskBase.cs for a general idea).

@mathieubourgeois Thanks for using Feedback Assistant! Your bug report just landed on my desk today.
There is no need to trouble Xamarin with this issue, we'll get it fixed soon in Monterey.

**Comment by ivanicin** [comment] 2021-11-11 11:59
In the meantime I can confirm that the workaround mentioned above works without any issues. I was able to submit the new version to the App Store and it displays the minimal required OS correctly: https://apps.apple.com/us/app/speech-central-text-to-speech/id1223093645 . As the App Store displays this number correctly everything will work properly on any version of macOS.

**Comment by zshameel** [comment] 2021-11-11 17:51
I am encountering the same error now. It worked earlier, but after upgrading to Monterey, I am facing this error. However, the workaround given above worked.

**Comment by macshome** [comment] 2021-11-17 15:25
If you are using non-appstore distribution packages you can use `allowed-os-versions` in your distribution.xml file like normal as well.

For example we require 10.14.4 and use this key without issue on macOS 12:
```
<allowed-os-versions>
    	<os-version min="10.14.4"/>
</allowed-os-versions>
```
https://developer.apple.com/library/archive/documentation/DeveloperTools/Reference/DistributionDefinitionRef/Chapters/Distribution_XML_Ref.html#//apple_ref/doc/uid/TP40005370-CH100-SW33

**Comment by jaredjones** [comment] 2021-11-17 19:28
That's completely correct.
The entire purpose of the `Requirements.plist` is to make it easy to construct a `Distribution` for your installer package. If you're willing to dive deeper and learn more about the format then you can use the `--synthesize` option of `productbuild` to create a template distribution and fill in whatever you want for the eligibility checks.

**Comment by mathieubourgeois** [comment] 2021-11-18 15:53
On my end, after receiving infos from Feedback Assistant, I can confirm that the issue is fixed on my end when updating to macOS Monterey 12.1 Beta 3.

**Comment by ttrias** [comment] 2021-11-19 00:21
I can confirm that the issue also does not arise when using Xcode 13 Beta instead of Xcode 13.1.  In my case I am building and packaging a Xamarin Mac (Cocoa) application.

**Comment by ttrias** [comment] 2021-11-19 00:32
A bit more research shows that the OS version information is now an ordered set and not an array.  Unfortunately, the XML Property List format doesn't support an NSOrderedSet instead of an NSArray.  Xamarin would have to produce a binary plist instead.

**Comment by chamons** [comment] 2021-12-22 20:57
Given that 12.1 has been released to stable awhile ago and it has been fixed on Apple's end I'm going to close this issue.

**Closed by chamons** 2021-12-22 20:57 UTC
Labels: bug
