### ISSUE TITLE
[iOS] Cannot set breakpoint on the specified IL offset.

### ISSUE THREAD

**Issue by MartinZikmund** [xamarin/xamarin-macios#21758] opened 2024-12-04 14:39 UTC
### Apple platform

iOS

### Framework version

net8.0-*, net9.0-*

### Affected platform version

VS 2022 17.12.x

### Description

I am hitting `Cannot set breakpoint on the specified IL offset.` error trying to launch the Uno Platform Sample application on iOS via Remote Mac connection from VS. The app deploys correctly to the device/Simulator, but on launch it immediately crashes when the debugger is attached with:

```
2024-12-04 15:27:46.530862+0100 SamplesApp[15085:147760] warning: Unable to insert breakpoint at SamplesApp.iOS.Application:<Main> (string[]):0
Cannot set breakpoint on the specified IL offset.
System.ArgumentException: Cannot set breakpoint on the specified IL offset.
   at Mono.Debugger.Soft.VirtualMachine.ErrorHandler(Object sender, ErrorHandlerEventArgs args) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugger.Soft\Mono.Debugger.Soft\VirtualMachine.cs:line 373
   at Mono.Debugger.Soft.Connection.SendReceive(CommandSet command_set, Int32 command, PacketWriter packet) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugger.Soft\Mono.Debugger.Soft\Connection.cs:line 1903
   at Mono.Debugger.Soft.Connection.EnableEvent(EventType etype, SuspendPolicy suspend_policy, List`1 mods) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugger.Soft\Mono.Debugger.Soft\Connection.cs:line 2851
   at Mono.Debugger.Soft.EventRequest.SendReq(List`1 mods) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugger.Soft\Mono.Debugger.Soft\EventRequest.cs:line 106
   at Mono.Debugging.Soft.SoftDebuggerSession.InsertBreakpoint(Breakpoint bp, BreakInfo bi, MethodMirror method, Int32 ilOffset) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 1403
   at Mono.Debugging.Soft.SoftDebuggerSession.ResolveFunctionBreakpoint(BreakInfo bi, FunctionBreakpoint bp, MethodMirror method) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2968
   at Mono.Debugging.Soft.SoftDebuggerSession.ResolveBreakpoints(TypeMirror type) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2911
   at Mono.Debugging.Soft.SoftDebuggerSession.HandleTypeLoadEvents(TypeLoadEvent[] events) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 2420
   at Mono.Debugging.Soft.SoftDebuggerSession.HandleEventSet(EventSet es) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 1879
   at Mono.Debugging.Soft.SoftDebuggerSession.EventHandler() in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:line 1801
```

This is odd because I actually have **no breakpoints set** (I confirmed this by both deleting all breakpoints and then doing a full `git clean -xfd` on the repository). I started observing this issue in VS 17.12 Preview 2.0, but it remained ever since (originally reported at [VS feedback](https://developercommunity.visualstudio.com/t/iOS---Cannot-set-breakpoint-on-the-speci/10745954?ref=native&refTime=1733322703806&refUserId=2017dd32-d242-4d44-bc7d-d0eefb216f79), but I believe this is a more appropriate location for this report).

Tested with two different PCs and two different Macs.

### Steps to Reproduce

1. Clone https://github.com/unoplatform/uno
2. In src folder rename crosstargeting_override.props.sample to crosstargeting_override.props
3. In the crosstargeting_override.props file uncomment <UnoTargetFrameworkOverride> prop and set it to net8.0-ios
4. Open Uno.UI-netcoremobile-only.slnf and try to run SamplesApp.netcoremobile on iOS Simulator or a device
5. **You should see a crash immediately after deploy is done**

### Did you find any workaround?

No

**Comment by rolfbjarne** [comment] 2024-12-06 09:02
> originally reported at [VS feedback](https://developercommunity.visualstudio.com/t/iOS---Cannot-set-breakpoint-on-the-speci/10745954?ref=native&refTime=1733322703806&refUserId=2017dd32-d242-4d44-bc7d-d0eefb216f79), but I believe this is a more appropriate location for this report

I pinged the team responsible for that feedback ticket, and they'll look at it.

I'll close this issue as a duplicate of the feedback ticket for now, but feel free to contact us again if you don't hear anything on the feedback ticket after a while.

**Closed by rolfbjarne** 2024-12-06 09:02 UTC

**Comment by MartinZikmund** [comment] 2024-12-12 18:09
@rolfbjarne Please reopen it here, I now see the same is happening also when trying to run from Rider on macOS, so this is not a VS specific issue

**Comment by rolfbjarne** [comment] 2024-12-13 08:08
> @rolfbjarne Please reopen it here, I now see the same is happening also when trying to run from Rider on macOS, so this is not a VS specific issue

That probably means it's a runtime issue - I've looped the runtime people in on the VS feedback ticket, so please continue updating any new info there.

**Comment by MartinZikmund** [comment] 2024-12-14 19:58
@rolfbjarne after very long debugging and trial and error I think I found the culprit. We were using `async Task Main` in the application, and that seems to cause the problem. Should be reproducible with a blank iOS app and the following:

```csharp
public class Application
{
    public static async Task Main(string[] args)
    {
        await Test(args);
    }

    public static Task Test(string[] args)
    {
        UIApplication.Main(args, null, typeof(AppDelegate));

        return Task.CompletedTask;
    }
}
```

I will include this in the VS feedback as well

**Comment by rolfbjarne** [comment] 2024-12-16 12:01
@MartinZikmund I would never have guessed that, I don't think I've ever seen anyone use `async Task Main` in an iOS project. I'll pass the info along to the approproate people. Great debugging!
