### ISSUE TITLE
Build fails when using EFCore 3.0 and SQLite on iOS

### ISSUE THREAD

**Issue by Kistelekig98** [xamarin/xamarin-macios#7232] opened 2019-10-15 08:27 UTC
### Steps to Reproduce
1. Open the solution
2. Build it

### Expected Behavior
The application builds.

### Actual Behavior
Build fails.
Errors:
> Error		Native linking failed. Please review the build log.	EFCoreIOSTeszt.iOSClient
			
> Error		Native linking failed, undefined symbol: _sqlite3_rekey_v2. This symbol was referenced by the managed member SQLitePCL.SQLite3Provider_internal/NativeMethods.sqlite3_rekey_v2. Please verify that all the necessary frameworks have been referenced and native libraries linked.	EFCoreIOSTeszt.iOSClient	
		
> Error		linker command failed with exit code 1 (use -v to see invocation)	EFCoreIOSTeszt.iOSClient
			
> Error		Native linking failed, undefined symbol: _sqlite3_key_v2. This symbol was referenced by the managed member SQLitePCL.SQLite3Provider_internal/NativeMethods.sqlite3_key_v2. Please verify that all the necessary frameworks have been referenced and native libraries linked.	EFCoreIOSTeszt.iOSClient			

### Environment
```
Microsoft Visual Studio Community 2019
Version 16.3.4
VisualStudio.16.Release/16.3.4+29409.12
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

Application Insights Tools for Visual Studio Package   9.1.00913.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.3.285.24939
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.3.285.24939
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.3.285.24939
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.9000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.3.285.24939
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.9000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.3.9000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.9000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.9000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20816.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.83+gbc8a4b23ec
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.3.7 (9d260c5)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61908.27190
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.10821.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19455.1+0422ff293bb2cc722fe5021b85ef50378a9af823
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.3.0.277 (d16-3@c0fcab7)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.3.0.246 (remotes/origin/d16-3@bd2f86892)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.565 (27e9746)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.0.3.0 (d16-3/4d45b41)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-06@5608fe0abb3
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333


Xamarin.iOS and Xamarin.Mac SDK   13.4.0.2 (e37549b)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

Xcode 11.1
```

### Build Logs
[minimal](https://gist.github.com/Kistelekig98/39eb3df058ccf06cad22cea33732ecfa)
[diagnostic](https://gist.github.com/Kistelekig98/fde25e38d8a269e89e40a9292adc7242)

### Example Project
[EFCoreIOSTeszt.zip](https://github.com/xamarin/xamarin-macios/files/3728116/EFCoreIOSTeszt.zip)

### Other
In my opinion the line that causes the bug is the SQLite initialization (*SQLitePCL.Batteries_V2.Init()* in *EFCoreIOSTest.Connect.Model.OnConfiguring*), because without that line the problem doesn't occur (I get other errors, but it doesn't really matter)

**Comment by whitneyschmidt** [comment] 2019-10-15 19:27
```
'C:\Users\kisteleki.gergely\source\repos\EFCoreIOSTeszt\EFCoreIOSTeszt.Core\..\EFCoreIOSTeszt.Osszekoto\Model.cs' conflicts with the imported type 'BloggingContext' in 'EFCoreIOSTeszt.Connect, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\Users\kisteleki.gergely\source\repos\EFCoreIOSTeszt\EFCoreIOSTeszt.Core\..\EFCoreIOSTeszt.Osszekoto\Model.cs'.
2>Migrations\20191014102219_Initialize.Designer.cs(10,23,10,38): warning CS0436: The type 'BloggingContext' in 'C:\Users\kisteleki.gergely\source\repos\EFCoreIOSTeszt\EFCoreIOSTeszt.Core\..\EFCoreIOSTeszt.Osszekoto\Model.cs' conflicts with the imported type 'BloggingContext' in 'EFCoreIOSTeszt.Connect, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\Users\kisteleki.gergely\source\repos\EFCoreIOSTeszt\EFCoreIOSTeszt.Core\..\EFCoreIOSTeszt.Osszekoto\Model.cs'.
2>C:\Users\kisteleki.gergely\source\repos\EFCoreIOSTeszt\EFCoreIOSTeszt.Osszekoto\Model.cs(26,17,26,21): warning CS0436: The type 'Post' in 'C:\Users\kisteleki.gergely\source\repos\EFCoreIOSTeszt\EFCoreIOSTeszt.Core\..\EFCoreIOSTeszt.Osszekoto\Model.cs' conflicts with the imported type 'Post' in 'EFCoreIOSTeszt.Connect, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\Users\kisteleki.gergely\source\repos\EFCoreIOSTeszt\EFCoreIOSTeszt.Core\..\EFCoreIOSTeszt.Osszekoto\Model.cs'.
2>C:\Users\kisteleki.gergely\source\repos\EFCoreIOSTeszt\EFCoreIOSTeszt.Osszekoto\Model.cs(9,18,9,22): warning CS0436: The type 'Blog' in 'C:\Users\kisteleki.gergely\source\repos\EFCoreIOSTeszt\EFCoreIOSTeszt.Core\..\EFCoreIOSTeszt.Osszekoto\Model.cs' conflicts with the imported type 'Blog' in 'EFCoreIOSTeszt.Connect, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\Users\kisteleki.gergely\source\repos\EFCoreIOSTeszt\EFCoreIOSTeszt.Core\..\EFCoreIOSTeszt.Osszekoto\Model.cs'.
2>C:\Users\kisteleki.gergely\source\repos\EFCoreIOSTeszt\EFCoreIOSTeszt.Osszekoto\Model.cs(36,12,36,16): warning CS0436: The type 'Blog' in 'C:\Users\kisteleki.gergely\source\repos\EFCoreIOSTeszt\EFCoreIOSTeszt.Core\..\EFCoreIOSTeszt.Osszekoto\Model.cs' conflicts with the imported type 'Blog' in 'EFCoreIOSTeszt.Connect, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\Users\kisteleki.gergely\source\repos\EFCoreIOSTeszt\EFCoreIOSTeszt.Core\..\EFCoreIOSTeszt.Osszekoto\Model.cs'.
2>C:\Users\kisteleki.gergely\source\repos\EFCoreIOSTeszt\EFCoreIOSTeszt.Osszekoto\Model.cs(10,18,10,22): warning CS0436: The type 'Post' in 'C:\Users\kisteleki.gergely\source\repos\EFCoreIOSTeszt\EFCoreIOSTeszt.Core\..\EFCoreIOSTeszt.Osszekoto\Model.cs' conflicts with the imported type 'Post' in 'EFCoreIOSTeszt.Connect, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\Users\kisteleki.gergely\source\repos\EFCoreIOSTeszt\EFCoreIOSTeszt.Core\..\EFCoreIOSTeszt.Osszekoto\Model.cs'.
2>C:\Users\kisteleki.gergely\source\repos\EFCoreIOSTeszt\EFCoreIOSTeszt.Osszekoto\Model.cs(26,49,26,53): warning CS0436: The type 'Post' in 'C:\Users\kisteleki.gergely\source\repos\EFCoreIOSTeszt\EFCoreIOSTeszt.Core\..\EFCoreIOSTeszt.Osszekoto\Model.cs' conflicts with the imported type 'Post' in 'EFCoreIOSTeszt.Connect, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\Users\kisteleki.gergely\source\repos\EFCoreIOSTeszt\EFCoreIOSTeszt.Core\..\EFCoreIOSTeszt.Osszekoto\Model.cs'.
```

**Comment by whitneyschmidt** [comment] 2019-10-15 19:53
@Kistelekig98 Thank you for your feedback!

This issue appears to be a SQLitePCL problem. The best course of action is to file an issue with https://github.com/ericsink/SQLitePCL.raw

It looks like it could be similar to https://github.com/ericsink/SQLitePCL.raw/issues/266

Closing for now - if you find that this only reproduces with Xcode11 please reopen this bug for investigation :)

**Closed by whitneyschmidt** 2019-10-15 19:53 UTC
Labels: support

**Comment by spouliot** [comment] 2019-10-15 21:06
Some additional context might help. The issue is that the native symbols do **not** exist in the 3rd party library you are (natively) linking with. See the last (linker) invocation to `clang`

```
   /Applications/Xcode112-beta1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang  -framework Security -framework UIKit -framework Foundation -weak_framework CoreFoundation -weak_framework CFNetwork -weak_framework GSS /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/registrar.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/main.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/EFCoreIOSTeszt.iOSKliens.exe.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/mscorlib.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/Xamarin.iOS.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/System.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/Mono.Security.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/System.Xml.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/System.Numerics.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/System.Core.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/System.Net.Http.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/EFCoreIOSTeszt.Connect.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/System.Data.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/System.Transactions.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/System.Web.Services.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/System.Xml.Linq.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/Microsoft.EntityFrameworkCore.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/Microsoft.Extensions.DependencyInjection.Abstractions.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/Microsoft.Extensions.Logging.Abstractions.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/Microsoft.Extensions.Caching.Abstractions.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/Microsoft.Extensions.Primitives.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/System.Runtime.CompilerServices.Unsafe.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/Microsoft.EntityFrameworkCore.Abstractions.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/System.ComponentModel.DataAnnotations.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/System.Collections.Immutable.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/System.Diagnostics.DiagnosticSource.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/Microsoft.Extensions.DependencyInjection.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/Microsoft.Extensions.Logging.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/Microsoft.Extensions.Options.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/Microsoft.Extensions.Caching.Memory.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/Microsoft.EntityFrameworkCore.Relational.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/Microsoft.Extensions.Configuration.Abstractions.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/SQLitePCLRaw.batteries_v2.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/SQLitePCLRaw.lib.e_sqlite3.ios.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/SQLitePCLRaw.provider.internal.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/SQLitePCLRaw.core.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/Microsoft.EntityFrameworkCore.Sqlite.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/Microsoft.DotNet.PlatformAbstractions.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/Microsoft.Data.Sqlite.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/Microsoft.Extensions.DependencyModel.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/System.Text.Json.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/System.Text.Encodings.Web.dll.o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/Microsoft.Bcl.AsyncInterfaces.dll.o /Users/poupou/git/xcode11.2/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/SDKs/MonoTouch.iphoneos.sdk/usr/lib/libmonosgen-2.0.a /Users/poupou/git/xcode11.2/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/SDKs/MonoTouch.iphoneos.sdk/usr/lib/libxamarin-debug.a /Users/poupou/git/xcode11.2/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/SDKs/MonoTouch.iphoneos.sdk/usr/lib/libmono-native-unified.a -force_load /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/e_sqlite3.a -force_load /Users/poupou/git/xcode11.2/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/SDKs/MonoTouch.iphoneos.sdk/usr/lib/libapp.a -Wl,-pie -arch arm64 -miphoneos-version-min=11.4 -isysroot /Applications/Xcode112-beta1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -lz -liconv -o /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/arm64/EFCoreIOSTeszt.iOSKliens -u _xamarin_find_protocol_wrapper_type -u _xamarin_release_block_on_main_thread -u _xamarin_get_block_descriptor -u _UIApplicationMain -u _sqlite3_close -u _sqlite3_close_v2 -u _sqlite3_enable_shared_cache -u _sqlite3_interrupt -u _sqlite3_finalize -u _sqlite3_reset -u _sqlite3_clear_bindings -u _sqlite3_stmt_status -u _sqlite3_bind_parameter_name -u _sqlite3_column_database_name -u _sqlite3_column_decltype -u _sqlite3_column_name -u _sqlite3_column_origin_name -u _sqlite3_column_table_name -u _sqlite3_column_text -u _sqlite3_errmsg -u _sqlite3_db_readonly -u _sqlite3_db_filename -u _sqlite3_prepare_v2 -u _sqlite3_prepare_v3 -u _sqlite3_db_status -u _sqlite3_complete -u _sqlite3_compileoption_used -u _sqlite3_compileoption_get -u _sqlite3_table_column_metadata -u _sqlite3_value_text -u _sqlite3_enable_load_extension -u _sqlite3_load_extension -u _sqlite3_initialize -u _sqlite3_shutdown -u _sqlite3_libversion -u _sqlite3_libversion_number -u _sqlite3_threadsafe -u _sqlite3_sourceid -u _sqlite3_malloc -u _sqlite3_realloc -u _sqlite3_free -u _sqlite3_stricmp -u _sqlite3_strnicmp -u _sqlite3_open -u _sqlite3_open_v2 -u _sqlite3_vfs_find -u _sqlite3_last_insert_rowid -u _sqlite3_changes -u _sqlite3_total_changes -u _sqlite3_memory_used -u _sqlite3_memory_highwater -u _sqlite3_status -u _sqlite3_busy_timeout -u _sqlite3_bind_blob -u _sqlite3_bind_zeroblob -u _sqlite3_bind_double -u _sqlite3_bind_int -u _sqlite3_bind_int64 -u _sqlite3_bind_null -u _sqlite3_bind_text -u _sqlite3_bind_parameter_count -u _sqlite3_bind_parameter_index -u _sqlite3_column_count -u _sqlite3_data_count -u _sqlite3_step -u _sqlite3_sql -u _sqlite3_column_double -u _sqlite3_column_int -u _sqlite3_column_int64 -u _sqlite3_column_blob -u _sqlite3_column_bytes -u _sqlite3_column_type -u _sqlite3_aggregate_count -u _sqlite3_value_blob -u _sqlite3_value_bytes -u _sqlite3_value_double -u _sqlite3_value_int -u _sqlite3_value_int64 -u _sqlite3_value_type -u _sqlite3_user_data -u _sqlite3_result_blob -u _sqlite3_result_double -u _sqlite3_result_error -u _sqlite3_result_int -u _sqlite3_result_int64 -u _sqlite3_result_null -u _sqlite3_result_text -u _sqlite3_result_zeroblob -u _sqlite3_result_error_toobig -u _sqlite3_result_error_nomem -u _sqlite3_result_error_code -u _sqlite3_aggregate_context -u _sqlite3_key -u _sqlite3_key_v2 -u _sqlite3_rekey -u _sqlite3_rekey_v2 -u _sqlite3_config -u _sqlite3_create_collation -u _sqlite3_update_hook -u _sqlite3_commit_hook -u _sqlite3_profile -u _sqlite3_progress_handler -u _sqlite3_trace -u _sqlite3_rollback_hook -u _sqlite3_db_handle -u _sqlite3_next_stmt -u _sqlite3_stmt_busy -u _sqlite3_stmt_readonly -u _sqlite3_exec -u _sqlite3_get_autocommit -u _sqlite3_extended_result_codes -u _sqlite3_errcode -u _sqlite3_extended_errcode -u _sqlite3_errstr -u _sqlite3_log -u _sqlite3_file_control -u _sqlite3_backup_init -u _sqlite3_backup_step -u _sqlite3_backup_remaining -u _sqlite3_backup_pagecount -u _sqlite3_backup_finish -u _sqlite3_blob_open -u _sqlite3_blob_write -u _sqlite3_blob_read -u _sqlite3_blob_bytes -u _sqlite3_blob_reopen -u _sqlite3_blob_close -u _sqlite3_wal_autocheckpoint -u _sqlite3_wal_checkpoint -u _sqlite3_wal_checkpoint_v2 -u _sqlite3_set_authorizer -u _sqlite3_create_function_v2 -u _mono_pmip
```

Iin particular
```
-force_load /Users/poupou/Downloads/EFCoreIOSTeszt/EFCoreIOSTeszt.iOSKliens/obj/iPhone/Debug/device-builds/iphone11.6-13.1.2/mtouch-cache/e_sqlite3.a
```

which is not the _default_ (OS provided) version of `sqlite3`. The version above does not include the symbols 
```
Undefined symbols for architecture arm64:
      "_sqlite3_key_v2", referenced from:
         -u command line option
      "_sqlite3_rekey_v2", referenced from:
         -u command line option
    ld: symbol(s) not found for architecture arm64
```
even if the managed code has p/invoke referencing the symbols.

As a **workaround** you can add ` --dynamic-symbol-mode=ignore` to your **Additional touch arguments**. This is **not** ideal since it removes build time checks and might eventually hides useful warnings (from this or other native libraries your project is using). IOW things could fail at runtime.

Also note that this won't work with some build options or platforms (e.g. tvOS and watchOS requires bitcode, which itself require symbols to be present).
