### ISSUE TITLE
In the scene:willConnectToSession:options:, accessing connectionOptions.UserActivities throws

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-macios#16378] opened 2022-10-18 15:50 UTC
### Steps to Reproduce

1. Add some Info.plist xml
```xml
<key>UIApplicationSceneManifest</key>
<dict>
	<key>UIApplicationSupportsMultipleScenes</key>
	<true/>
	<key>UISceneConfigurations</key>
	<dict>
		<key>UIWindowSceneSessionRoleApplication</key>
		<array>
			<dict>
				<key>UISceneConfigurationName</key>
				<string>__MAUI_DEFAULT_SCENE_CONFIGURATION__</string>
				<key>UISceneDelegateClassName</key>
				<string>SceneDelegate</string>
			</dict>
		</array>
	</dict>
</dict>
```
2. Override the Scene Delegate method:
```cs
[Export("scene:willConnectToSession:options:")]
[System.Runtime.Versioning.SupportedOSPlatform("ios13.0")]
[System.Runtime.Versioning.SupportedOSPlatform("tvos13.0")]
public virtual void WillConnect(UIScene scene, UISceneSession session, UISceneConnectionOptions connectionOptions)
{
    var activities = connectionOptions.UserActivities;
}
```
3. Observe an exception:
```
Unable to cast object of type 'Foundation.NSSet`1[[UIKit.UIScene, Microsoft.iOS, Version=16.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]]' to type 'Foundation.NSSet`1[[Foundation.NSUserActivity, Microsoft.iOS, Version=16.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]]'.

   at ObjCRuntime.Runtime.GetNSObject[NSSet`1](IntPtr ptr)
   at UIKit.UISceneConnectionOptions.get_UserActivities()
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IUIWindowSceneDelegate sceneDelegate, IApplication application, UIScene scene, UISceneSession session, UISceneConnectionOptions connectionOptions) in /Users/matthew/Projects/maui/src/Core/src/Platform/iOS/ApplicationExtensions.cs:line 60
   at Microsoft.Maui.MauiUISceneDelegate.WillConnect(UIScene scene, UISceneSession session, UISceneConnectionOptions connectionOptions) in /Users/matthew/Projects/maui/src/Core/src/Platform/iOS/MauiUISceneDelegate.cs:line 23
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at Maui.Controls.Sample.Platform.Application.Main(String[] args) in /Users/matthew/Projects/maui/src/Controls/samples/Controls.Sample.Sandbox/Platforms/iOS/Main.cs:line 8
```

### Expected Behavior

No exception

### Actual Behavior

Exception

### Environment

<details>
<summary>Version information</summary>

```
```

</details>

**Comment by mattleibow** [comment] 2022-10-26 21:45
I was also able to repro this now with a small sample project: https://github.com/mattleibow/MauiMultiWindowSample

Just download and run mac catalyst.

```
 % dotnet --info 
.NET SDK:
 Version:   7.0.100
 Commit:    4e41c41027

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.5
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.402 [/usr/local/share/dotnet/sdk]
  7.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

```
% dotnet workload list

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
macos                      12.3.2366/7.0.100      SDK 7.0.100        
ios                        16.0.1470/7.0.100      SDK 7.0.100        
maccatalyst                15.4.2366/7.0.100      SDK 7.0.100        
maui                       7.0.1/7.0.100          SDK 7.0.100        
tvos                       16.0.1470/7.0.100      SDK 7.0.100        
android                    33.0.4/7.0.100         SDK 7.0.100        
```

**Comment by rolfbjarne** [comment] 2022-10-27 08:21
I can reproduce.

It looks like it's a duplicate of https://github.com/xamarin/xamarin-macios/issues/13704.

**Closed** 2022-10-28 09:05 UTC
Labels: bug, dotnet
