### ISSUE TITLE
[NET8] Bound external constants on static libraries are being linked as non-external on the final app.

### ISSUE THREAD

**Issue by Flash3001** [xamarin/xamarin-macios#20301] opened 2024-03-13 15:45 UTC
### Steps to Reproduce

Using NET 8

1.  dotnet new ios
2.  dotnet add package Xamarin.Google.iOS.MobileAds --version 8.13.0.3
3.  add `var adType = Google.MobileAds.AdLoaderAdType.GamBanner.GetConstant()` anywhere in code and run.

### Expected Behavior

`Google.MobileAds.AdLoaderAdType.GamBanner.GetConstant()` should return a valid string.

### Actual Behavior

`null` is returned

### Environment

dotnet --version 8.0.201
running on macOS 14.3.1 (23D60)
Xcode Version 15.3 (15E204a)

### The Cause

`external` constants in the static library (contained in a xcframework) are being imported as `non-external` on the final app.

GoogleMobileAds.xcframework
<img width="1171" alt="Screenshot 2024-03-13 at 12 35 40" src="https://github.com/xamarin/xamarin-macios/assets/7071748/dbc173c4-ef9d-4f71-ac76-1f11f0e745f8">

My App
![Screenshot 2024-03-12 at 17 51 12](https://github.com/xamarin/xamarin-macios/assets/7071748/8c0620e8-5e33-43ed-95d6-909157d848fc)

This is the relevant binding: https://github.com/xamarin/GoogleApisForiOSComponents/blob/c7ae591364f73a4e61d47d765a1e537bb509422e/source/Google/MobileAds/Enums.cs#L28

### Last Version it was Working?

I don't know for certain. I jumped from Xamarin.iOS straight to NET8

### Example Project

[linking_error.zip](https://github.com/xamarin/xamarin-macios/files/14590033/linking_error.zip)

### Workaround 

1. Manually create a list of symbols that should be external, but aren't.
2. Add the list to the list _CustomLinkFlags using `-exported_symbols_list my_list.list`

```
  <ItemGroup>
    <_CustomLinkFlags Include="-exported_symbols_list" />
    <_CustomLinkFlags Include="google_ads_symbols.list" />
  </ItemGroup>
```

My App with workaround
<img width="924" alt="Screenshot 2024-03-13 at 12 36 37" src="https://github.com/xamarin/xamarin-macios/assets/7071748/84a6a9ac-e0da-4839-ac0f-6e58cac9bed1">

### Sample project with workaround implemented

[linking_error_workaround.zip](https://github.com/xamarin/xamarin-macios/files/14590010/linking_error_workaround.zip)

**Comment by Flash3001** [comment] 2024-03-13 16:00
Just in case someone else sees the same issue and is googling about it, these are signs it is happening:

```<Google> Delegate does not conform to the required protocol, nil. Add nil to Loader's protocol list.```

or an exception is thrown when accessing ```AdSizeCons.Banner```

**Comment by Flash3001** [comment] 2024-03-14 15:24
Update to this, the workaround works fine for `debug` builds, but on `release` builds the constants are completely missing. 

Add this extra workaround made the trick for my release builds: 

```        <_ReferencesLinkerFlags Include="-u_GADAdSizeBanner" Visible="false" />
        <_ReferencesLinkerFlags Include="-u_GADAdSizeFluid"  Visible="false" />
        <_ReferencesLinkerFlags Include="-u_GADAdSizeFullBanner"  Visible="false" />
        <_ReferencesLinkerFlags Include="-u_GADAdSizeInvalid"  Visible="false" />
        <_ReferencesLinkerFlags Include="-u_GADAdSizeLargeBanner"  Visible="false" />
        <_ReferencesLinkerFlags Include="-u_GADAdSizeLeaderboard"  Visible="false" />
        <_ReferencesLinkerFlags Include="-u_GADAdSizeMediumRectangle"  Visible="false" />
        <_ReferencesLinkerFlags Include="-u_GADAdSizeFromCGSize" Visible="false" />
        <_ReferencesLinkerFlags Include="-u_GADAdSizeSkyscraper"  Visible="false" />
        <_ReferencesLinkerFlags Include="-u_kGADAdSizeSmartBannerLandscape" Visible="false" />
        <_ReferencesLinkerFlags Include="-u_kGADAdSizeSmartBannerPortrait"  Visible="false" />
        <_ReferencesLinkerFlags Include="-u_GADAdLoaderAdTypeCustomNative"  Visible="false" />
        <_ReferencesLinkerFlags Include="-u_GADAdLoaderAdTypeGAMBanner"  Visible="false" />
        <_ReferencesLinkerFlags Include="-u_GADAdLoaderAdTypeNative" Visible="false" />```

**Comment by rolfbjarne** [comment] 2024-03-14 17:01
This is a duplicate of #20061, which we've already fixed.

The fix should be included in the next .NET service release.

**Comment by rolfbjarne** [comment] 2024-03-14 17:01
Great analysis of the issue btw!

**Closed by rolfbjarne** 2024-03-14 17:01 UTC
