### ISSUE TITLE
Error HE0004 Could Not Load Framework ContentDeliveryServices

### ISSUE THREAD

**Issue by sisaacks** [xamarin/xamarin-macios#18094] opened 2023-04-19 00:08 UTC
### Steps to Reproduce
Upgrade to the Following:

- Xamarin Forms: 5.0.0.2578
- Windows Visual Studio: 17.5.4
- MAC Visual Studio: 17.5.4
- XCODE: 14.3

When I try to debug the iOS application I am getting the following error: HE0004: Could not load the framework ‘ContentDeliveryServices’ (path: /Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/ContentDeliveryServices):

### Expected Behavior
I would expect that the application starts and debugs

### Actual Behavior
I get the error noted above

### Environment
Notes above

<details>
<summary>Version information</summary>

```
```

</details>

**Comment by rolfbjarne** [comment] 2023-04-19 05:33
This is a duplicate of #17561.

**Closed by rolfbjarne** 2023-04-19 05:33 UTC
