### ISSUE TITLE
Clang++ exited with code 1

### ISSUE THREAD

**Issue by nchrisr** [xamarin/xamarin-macios#19229] opened 2023-10-17 11:51 UTC
### Steps to Reproduce

1. Create a new MAUI project on a **Windows Machine** with Visual Studio
2. Install the Branch-Xamarin-Linking-SDK NuGet package.
3. Pair the Windows device to an M1 Mac and try to run on a simulator or a device.

### Expected Behavior
App should build successfully 

### Actual Behavior

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_BNCCommerceEvent", referenced from:
     -u command line option
  "_OBJC_CLASS_$_BNCLinkCache", referenced from:
     -u command line option
  "_OBJC_CLASS_$_BNCLinkData", referenced from:
     -u command line option
  "_OBJC_CLASS_$_BNCPreferenceHelper", referenced from:
     -u command line option
  "_OBJC_CLASS_$_BNCProduct", referenced from:
     -u command line option
  "_OBJC_CLASS_$_BNCServerInterface", referenced from:
     -u command line option
  "_OBJC_CLASS_$_BNCServerRequest", referenced from:
     -u command line option
  "_OBJC_CLASS_$_BNCServerRequestQueue", referenced from:
     -u command line option
  "_OBJC_CLASS_$_BNCServerResponse", referenced from:
     -u command line option
  "_OBJC_CLASS_$_Branch", referenced from:
     -u command line option
  "_OBJC_CLASS_$_BranchActivityItemProvider", referenced from:
     -u command line option
  "_OBJC_CLASS_$_BranchCSSearchableItemAttributeSet", referenced from:
     -u command line opt		
```

### Environment

<details>
<summary>Version information</summary>

```
Microsoft Visual Studio Enterprise 2022
Version 17.7.5
VisualStudio.17.Release/17.7.5+34202.233
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Enterprise

ASP.NET and Web Tools   17.7.273.65229
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.7.273.65229
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.7.273.65229
Azure Functions and Web Jobs Tools

C# Tools   4.7.0-3.23469.2+a3b9f0c274649870015cfe508cacde8fdc15df55
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.4.34 (main@d5ab18b)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.7.27 (547ea6f)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.7.3.2333001+0ab18affdf2a37647768d0e25f5f021bee6257a1
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.7.10.1
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.20829.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.7.0-3.23469.2+a3b9f0c274649870015cfe508cacde8fdc15df55
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.7.0-beta.23314.10+e612cf93b989503c89e3a5830090062b7ab5e143
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.7.0.223 (d17-7@c374b3e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.7.3.9 (remotes/origin/d17-7@796d191def)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.7.21 (150ec9f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.1.2 (d17-5/a8a26c7)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d


Xamarin.iOS and Xamarin.Mac SDK   16.4.0.18 (9d266025e)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Build Logs
[msbuild.zip](https://github.com/xamarin/xamarin-macios/files/12928453/msbuild.zip)

**Comment by rolfbjarne** [comment] 2023-10-17 12:04
This worked fine for me:

```shell
$ dotnet new ios
The template "iOS Application" was created successfully.

$ dotnet add package Branch-Xamarin-Linking-SDK
[...]

$ dotnet build /bl /p:RuntimeIdentifier=ios-arm64
[...]
Build succeeded.
```

Please attach a binlog that shows the error: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs

**Comment by nchrisr** [comment] 2023-10-17 12:07
> This worked fine for me:
> 
> ```shell
> $ dotnet new ios
> The template "iOS Application" was created successfully.
> 
> $ dotnet add package Branch-Xamarin-Linking-SDK
> [...]
> 
> $ dotnet build /bl /p:RuntimeIdentifier=ios-arm64
> [...]
> Build succeeded.
> ```
> 
> Please attach a binlog that shows the error: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs

Did you do this from a Windows machine? It has to be done from a Windows Machine paired to an M1 Mac

**Comment by rolfbjarne** [comment] 2023-10-17 12:40
> I have added the build logs as requested

The binlog shows a successful build - if you built from the command line, you'll have to pass a few properties to the build for it to be built remotely (https://learn.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/#build-ios-apps-from-the-windows-command-line)


> Did you do this from a Windows machine? It has to be done from a Windows Machine paired to an M1 Mac.

If it only happens on Windows, it might be a duplicate of #19173.

**Comment by rolfbjarne** [comment] 2023-10-20 09:08
OK, I can reproduce this, sorry about the late reply.

Potential workaround:

1. Find the file Xamarin.Shared.targets for your system (for me it's something like `C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.8968-net8-rc2\tools\msbuild\iOS\Xamarin.Shared.targets`, but the exact location depends on which version of .NET and the workload you have installed).
2. Locate the `_ExpandNativeReferences` target (around line 140):

```xml
	<Target Name="_ExpandNativeReferences" Condition="'$(DesignTimeBuild)' != 'true'" DependsOnTargets="_DetectSdkLocations;_ComputeTargetArchitectures;_GenerateBundleName">
		<ItemGroup>
			<_XCFrameworkNativeReference Include="@(NativeReference -> '%(Identity)/.')" Condition="'%(Extension)' == '.xcframework'" />
			<_FrameworkNativeReference Include="@(NativeReference -> '%(Identity)/%(Filename)')" Condition="'%(Extension)' == '.framework'" />
			<_FileNativeReference Include="@(NativeReference)" Condition="'%(Extension)' != '.framework' And '%(Extension)' != '.xcframework'" />
		</ItemGroup>
		<ResolveNativeReferences
			SessionId="$(BuildSessionId)"
			Condition="('$(IsMacEnabled)' == 'true' Or '$(IsHotRestartBuild)' == 'true') And '$(IsBindingProject)' != 'true'"
			Architectures="$(TargetArchitectures)"
			FrameworksDirectory="$(_AppFrameworksRelativePath)"
			IntermediateOutputPath="$(DeviceSpecificIntermediateOutputPath)"
			NativeReferences="@(_XCFrameworkNativeReference);@(_FrameworkNativeReference)"
			References="@(ReferencePath)"
			SdkIsSimulator="$(_SdkIsSimulator)"
			TargetFrameworkMoniker="$(_ComputedTargetFrameworkMoniker)"
			>
			<Output TaskParameter="NativeFrameworks" ItemName="_ResolvedNativeReference" />
		</ResolveNativeReferences>

		<ItemGroup>
			<_FrameworkNativeReference Include="@(_ResolvedNativeReference)" Condition="'%(Kind)' == 'Framework'" />
			<_FileNativeReference Include="@(_ResolvedNativeReference)" Condition="'%(Kind)' == 'Static' Or '%(Kind)' == 'Dynamic'" />
		</ItemGroup>
	</Target>
```

3. Remove the line `SessionId="$(BuildSessionId)"` in the `ResolveNativeReferences` task, so that it looks like this:

```xml
	<Target Name="_ExpandNativeReferences" Condition="'$(DesignTimeBuild)' != 'true'" DependsOnTargets="_DetectSdkLocations;_ComputeTargetArchitectures;_GenerateBundleName">
		<ItemGroup>
			<_XCFrameworkNativeReference Include="@(NativeReference -> '%(Identity)/.')" Condition="'%(Extension)' == '.xcframework'" />
			<_FrameworkNativeReference Include="@(NativeReference -> '%(Identity)/%(Filename)')" Condition="'%(Extension)' == '.framework'" />
			<_FileNativeReference Include="@(NativeReference)" Condition="'%(Extension)' != '.framework' And '%(Extension)' != '.xcframework'" />
		</ItemGroup>
		<ResolveNativeReferences
			Condition="('$(IsMacEnabled)' == 'true' Or '$(IsHotRestartBuild)' == 'true') And '$(IsBindingProject)' != 'true'"
			Architectures="$(TargetArchitectures)"
			FrameworksDirectory="$(_AppFrameworksRelativePath)"
			IntermediateOutputPath="$(DeviceSpecificIntermediateOutputPath)"
			NativeReferences="@(_XCFrameworkNativeReference);@(_FrameworkNativeReference)"
			References="@(ReferencePath)"
			SdkIsSimulator="$(_SdkIsSimulator)"
			TargetFrameworkMoniker="$(_ComputedTargetFrameworkMoniker)"
			>
			<Output TaskParameter="NativeFrameworks" ItemName="_ResolvedNativeReference" />
		</ResolveNativeReferences>

		<ItemGroup>
			<_FrameworkNativeReference Include="@(_ResolvedNativeReference)" Condition="'%(Kind)' == 'Framework'" />
			<_FileNativeReference Include="@(_ResolvedNativeReference)" Condition="'%(Kind)' == 'Static' Or '%(Kind)' == 'Dynamic'" />
		</ItemGroup>
	</Target>
``` 

4. Close VS and try again.

**Comment by nchrisr** [comment] 2023-10-20 10:35
@rolfbjarne I tried your work around and its now a different error:

```
MSB4018	The "ResolveNativeReferences" task failed unexpectedly.
System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Xamarin.Utils.Execution.<>c__DisplayClass24_1.<RunAsync>b__0() in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/common/Execution.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Xamarin.MacDev.Tasks.XamarinTask.<ExecuteAsync>d__24.MoveNext() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinTask.cs:line 120
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Xamarin.MacDev.Tasks.ResolveNativeReferences.ProcessSidecar(ITaskItem r, String resources, List`1 native_frameworks) in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs:line 143
   at Xamarin.MacDev.Tasks.ResolveNativeReferences.ExecuteLocally() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs:line 114
   at Xamarin.MacDev.Tasks.ResolveNativeReferences.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs:line 66
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Xamarin.Utils.Execution.<>c__DisplayClass24_1.<RunAsync>b__0() in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/common/Execution.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Xamarin.MacDev.Tasks.XamarinTask.<ExecuteAsync>d__24.MoveNext() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinTask.cs:line 120<---
	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7107\tools\msbuild\iOS\Xamarin.Shared.targets	137
```

Any thoughts on what I could try to fix this one?

**Comment by rolfbjarne** [comment] 2023-10-23 14:59
> * Do you think an update to a VS service release would fix it?

Yes, I'm working on a fix.

I'm still looking into a workaround in the meantime.

**Comment by rolfbjarne** [comment] 2023-10-24 15:01
I have another potential workaround:

1. Remove the first workaround (add back the `SessionId="$(BuildSessionId)"` line)
2. Add the following just before the `ResolveNativeReferences` task in the `_ExpandNativeReferences` target:

```xml
		<ItemGroup>
			<_FilesToCopyToMac Include="@(ReferencePath->'%(RootDir)%(Directory)%(Filename).resources.zip')" Condition="Exists('%(RootDir)%(Directory)%(Filename).resources.zip')">
				<TargetPath>%(ReferencePath.RootDir)%(ReferencePath.Directory)%(ReferencePath.Filename).resources.zip</TargetPath>
			</_FilesToCopyToMac>
		</ItemGroup>

		<CopyFilesToBuildServer 
			Condition="'$(IsMacEnabled)' == 'true'" 
			SessionId="$(BuildSessionId)" 
			Files="@(_FilesToCopyToMac)" />
```

So that the `_ExpandNativeReferences` target looks like this:

```xml
	<Target Name="_ExpandNativeReferences" Condition="'$(DesignTimeBuild)' != 'true'" DependsOnTargets="_DetectSdkLocations;_ComputeTargetArchitectures">
		<ItemGroup>
			<_XCFrameworkNativeReference Include="@(NativeReference -> '%(Identity)/.')" Condition="'%(Extension)' == '.xcframework'" />
			<_FrameworkNativeReference Include="@(NativeReference -> '%(Identity)/%(Filename)')" Condition="'%(Extension)' == '.framework'" />
			<_FileNativeReference Include="@(NativeReference)" Condition="'%(Extension)' != '.framework' And '%(Extension)' != '.xcframework'" />
		</ItemGroup>

		<ItemGroup>
			<_FilesToCopyToMac Include="@(ReferencePath->'%(RootDir)%(Directory)%(Filename).resources.zip')" Condition="Exists('%(RootDir)%(Directory)%(Filename).resources.zip')">
				<TargetPath>%(ReferencePath.RootDir)%(ReferencePath.Directory)%(ReferencePath.Filename).resources.zip</TargetPath>
			</_FilesToCopyToMac>
		</ItemGroup>

		<CopyFilesToBuildServer 
			Condition="'$(IsMacEnabled)' == 'true'" 
			SessionId="$(BuildSessionId)" 
			Files="@(_FilesToCopyToMac)" />

		<ResolveNativeReferences
			SessionId="$(BuildSessionId)"
			Condition="'$(IsMacEnabled)' == 'true' And '$(IsBindingProject)' != 'true'"
			Architectures="$(TargetArchitectures)"
			IntermediateOutputPath="$(DeviceSpecificIntermediateOutputPath)"
			NativeReferences="@(_XCFrameworkNativeReference);@(_FrameworkNativeReference)"
			References="@(ReferencePath)"
			SdkIsSimulator="$(_SdkIsSimulator)"
			TargetFrameworkMoniker="$(_ComputedTargetFrameworkMoniker)"
			>
			<Output TaskParameter="NativeFrameworks" ItemName="_ResolvedNativeReference" />
		</ResolveNativeReferences>
```

Can you try that and see if it works for you?

**Comment by nchrisr** [comment] 2023-10-24 15:28
@rolfbjarne Your work around works, thanks!

**Closed** 2023-10-25 06:44 UTC
Labels: bug, regression, windows-only
