### ISSUE TITLE
XI and XM bindings projects use MCS not CSC

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#3654] opened 2018-03-02 22:12 UTC
### Steps to Reproduce

1. Create New XI or XM Binding Project
2. Look at build log for mcs or csc
3. Notice mcs 

### Environment

Latest master

### Build Logs

https://gist.github.com/chamons/23397ab1935469d9ebda6bf89c1532ba

> VS bug [#580959](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/580959), VS bug [#580960](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/580960)

**Comment by spouliot** [comment] 2018-03-05 22:42
Let's complete the kill in 15.7 :)

**Comment by chamons** [comment] 2018-03-09 16:24
Work done here https://github.com/chamons/xamarin-macios/commit/7c39a00bc7d146dba798034fbab2feccf302470c waiting on https://github.com/xamarin/xamarin-macios/pull/3672  to land first.

**Comment by spouliot** [comment] 2018-03-14 20:59
@slluis this bug was synced 3 times into VSTS, 2 times on XI and one time on XM. Closing a duplicate also close the GitHub issue :(

The description was updated to mention 2 issues. I guess I close the wrong one since it was mentioned there ?

**Comment by spouliot** [comment] 2018-03-14 21:02
It's a fight I'll lose :(

**Comment by slluis** [comment] 2018-03-15 12:30
I'm not sure why it synced twice for XI. I'll try to reproduce. The dup is now closed, so I guess it is all ok now.

**Comment by spouliot** [comment] 2018-04-20 17:33
https://github.com/xamarin/xamarin-macios/pull/3672 has landed, closing

**Closed by spouliot** 2018-04-20 17:33 UTC
Labels: enhancement, iOS, macOS, vs-sync
