### ISSUE TITLE
Asset catalogs in sub assemblies replace main assembly cataglos

### ISSUE THREAD

**Issue by J-Swift** [xamarin/xamarin-macios#15801] opened 2022-08-30 02:14 UTC
### Steps to Reproduce

1. Create a net6-ios app with an asset catalog. Run the app and notice `UIImage.FromBundle` works fine
<img width="250" alt="Screen Shot 2022-08-29 at 9 49 48 PM" src="https://user-images.githubusercontent.com/734158/187332186-4cac0433-a18b-4023-816b-9872b332163f.png">

2. Create a net6-ios lib with an asset cataglog. Reference the lib from the app.
3. Run the app and notice `UIImage.FromBundle` doesnt work.
<img width="250" alt="Screen Shot 2022-08-29 at 9 51 14 PM" src="https://user-images.githubusercontent.com/734158/187332208-9eee1944-4426-4f04-acef-c8f0acd384ba.png">

### Expected Behavior

Sub assemblies should create their own bundle so that assets play nicely together. I should then be able to load the appropriate image at runtime using `UIImage.FromBundle` and pass in the main bundle for the app assets or the sub assembly bundle for the lib assets.

### Actual Behavior

The sub assembly Assets.car replaces the app assembly Assets.car entirely. This is also now the `MainBundle`, as you don't pass anything for the bundle param in `UIImage.FromBundle`.

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac Preview
Version 17.4 Preview (17.4 build 715)
Installation UUID: 427a2609-4a78-421c-a5a1-ada78abd9f2f

Runtime
.NET 6.0.5 (64-bit)
Architecture: X64

Roslyn (Language Service)
4.4.0-1.22371.1+c07f2571612b471671c809b5b0db59b0c37aab57

NuGet
Version: 6.2.1.2

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.400/Sdks
SDK Versions:
	6.0.400
	6.0.300-preview.22168.1
	6.0.201
	3.1.422
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.8
	6.0.3
	6.0.2
	3.1.28

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 13.4.1 (20504)
Build 13F100

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 15.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:55-0400

Xamarin.Android
Not Installed

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.4.0.24
Hash: b3b6672
Branch: remotes/origin/HEAD~1
Build date: 2022-08-04 16:27:22 UTC

Android Device Manager
Version: 0.0.0.1179
Hash: 0f220c0
Branch: main
Build date: 2022-08-04 16:27:22 UTC

Xamarin Designer
Version: 17.4.0.32
Hash: 439b92ed7b
Branch: remotes/origin/d17-4
Build date: 2022-08-04 16:27:17 UTC

Build Information
Release ID: 1704000715
Git revision: 09071dadfc1b81e4f0e2c9505cd8a5ef0b41d312
Build date: 2022-08-04 16:24:56+00
Build branch: release-17.4
Build lane: release-17.4

Operating System
Mac OS X 12.5.1
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Wed Aug 10 14:25:27 PDT 2022
    root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64


```

</details>

### Build Logs

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/9449016/msbuild.binlog.zip)

### Example Project (If Possible)

https://github.com/J-Swift/net6-assets-repro

**Comment by chamons** [comment] 2022-09-01 15:46
This looks like it is worth looking into during the NET7 timeframe.

**Comment by rolfbjarne** [comment] 2022-09-01 15:56
This has been reported before (#5755), so I'm closing as a duplicate of that issue.

**Closed by rolfbjarne** 2022-09-01 15:56 UTC
Labels: bug, msbuild

**Comment by J-Swift** [comment] 2022-09-01 16:00
Is there any plan on addressing this? It looks like that other issue hasnt even been acknowledge

**Comment by rolfbjarne** [comment] 2022-09-01 16:21
> Is there any plan on addressing this? It looks like that other issue hasnt even been acknowledged

No immediate plans unfortunately (as always we're bound by limited manpower). But we certainly know about it.
