### ISSUE TITLE
Build fails with forms app

### ISSUE THREAD

**Issue by nodoid** [xamarin/xamarin-macios#7724] opened 2020-01-19 23:07 UTC
### Steps to Reproduce

1. Create forms app 
2. Build app using Xamarin iOS (preview)
3. 

### Expected Behavior
App should build

### Actual Behavior
/Users/pfj/Developer/hand/hand.iOS/obj/iPhone/Debug/mtouch-cache/registrar.m(6872,17): warning G3E9910A3: auto property synthesis will not synthesize property 'inputImage' declared in protocol 'CILanczosScaleTransform' [-Wobjc-protocol-property-synthesis]
/Users/pfj/Developer/hand/hand.iOS/obj/iPhone/Debug/mtouch-cache/registrar.m(6872,17): warning G3E9910A3: auto property synthesis will not synthesize property 'scale' declared in protocol 'CILanczosScaleTransform' [-Wobjc-protocol-property-synthesis]
/Users/pfj/Developer/hand/hand.iOS/obj/iPhone/Debug/mtouch-cache/registrar.m(6872,17): warning G3E9910A3: auto property synthesis will not synthesize property 'aspectRatio' declared in protocol 'CILanczosScaleTransform' [-Wobjc-protocol-property-synthesis]
/Users/pfj/Developer/hand/hand.iOS/obj/iPhone/Debug/mtouch-cache/registrar.h(1724,82): error GF247FC6C: interface type 'NSString' cannot be passed by value; did you forget * in 'NSString'?
/Users/pfj/Developer/hand/hand.iOS/obj/iPhone/Debug/mtouch-cache/registrar.h(1800,45): error GF247FC6C: interface type 'NSString' cannot be passed by value; did you forget * in 'NSString'?
/Users/pfj/Developer/hand/hand.iOS/obj/iPhone/Debug/mtouch-cache/registrar.h(1802,125): error GF247FC6C: interface type 'NSString' cannot be passed by value; did you forget * in 'NSString'?
MTOUCH : error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
### Environment

```
=== Visual Studio Community 2019 for Mac (Preview) ===

Version 8.5 Preview (8.5 build 1543)
Installation UUID: 933163e9-dca5-472b-b2ed-29d7aab111ab
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.14.1.17 (d16-5 / d30880059)

	Package version: 608000087

=== Mono Framework MDK ===

Runtime:
	Mono 6.8.0.87 (2019-10/df42020fe6f) (64-bit)
	Package version: 608000087

=== Roslyn (Language Service) ===

3.4.0-beta4-19568-04+82f2e2541478e239dc4b04f231e90dc2b3dcb422

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.100/Sdks
SDK Versions:
	3.1.100
	3.1.100-preview3-014645
	3.1.100-preview2-014569
	3.0.100
	3.0.100-rc1-014190
	3.0.100-preview9-014004
	3.0.100-preview5-011568
	2.2.203
	2.1.701
	2.1.505
	2.1.504
	2.1.500
	2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.0
	3.1.0-preview3.19553.2
	3.1.0-preview2.19525.6
	3.0.0
	3.0.0-rc1-19456-20
	3.0.0-preview9-19423-09
	3.0.0-preview5-27626-15
	2.2.4
	2.2.3
	2.1.14
	2.1.13
	2.1.12
	2.1.9
	2.1.8
	2.1.6
	2.1.2

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.3.1 (15715)
Build 11C504

=== Xamarin.Android ===

Version: 10.2.0.84 (Visual Studio Community)
Commit: xamarin-android/d16-5/ac3f71f
Android SDK: /Users/pfj/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: df42020
Java.Interop: xamarin/java.interop/d16-5@c0cc770
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/pfj/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.5.0.28
Hash: 2697505
Branch: remotes/origin/d16-5
Build date: 2019-12-18 17:36:18 UTC

=== Android Device Manager ===

Version: 16.5.0.36
Hash: 1ea9748
Branch: remotes/origin/d16-5
Build date: 2019-12-18 17:36:40 UTC

=== Xamarin Designer ===

Version: 16.5.0.382
Hash: c3bbd0524
Branch: remotes/origin/d16-5
Build date: 2019-12-30 21:46:42 UTC

=== Xamarin.Mac ===

Version: 6.14.1.17 (Visual Studio Community)
Hash: d30880059
Branch: d16-5
Build date: 2020-01-07 18:20:41-0500

=== Xamarin.iOS ===

Version: 13.14.1.17 (Visual Studio Community)
Hash: d30880059
Branch: d16-5
Build date: 2020-01-07 18:20:41-0500

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 805001543
Git revision: c91d9639b1c8c8dff574f5c4fd46bca48dbfd21f
Build date: 2020-01-09 16:05:44-05
Build branch: release-8.5
Xamarin extensions: e97f3dddaff6b0ffa19fc7e2c512f70ac79226a4

=== Operating System ===

Mac OS X 10.15.2
Darwin 19.2.0 Darwin Kernel Version 19.2.0
    Sat Nov  9 03:47:04 PST 2019
    root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64


```

### Build Logs

https://gist.github.com/nodoid/57508470f27afdb846fa0bcf40c6615a

**Comment by chamons** [comment] 2020-01-21 20:50
```
/Users/pfj/Developer/hand/hand.iOS/obj/iPhone/Debug/mtouch-cache/registrar.m(6872,17): warning G3E9910A3: auto property synthesis will not synthesize property 'inputImage' declared in protocol 'CILanczosScaleTransform' [-Wobjc-protocol-property-synthesis]
/Users/pfj/Developer/hand/hand.iOS/obj/iPhone/Debug/mtouch-cache/registrar.m(6872,17): warning G3E9910A3: auto property synthesis will not synthesize property 'scale' declared in protocol 'CILanczosScaleTransform' [-Wobjc-protocol-property-synthesis]
/Users/pfj/Developer/hand/hand.iOS/obj/iPhone/Debug/mtouch-cache/registrar.m(6872,17): warning G3E9910A3: auto property synthesis will not synthesize property 'aspectRatio' declared in protocol 'CILanczosScaleTransform' [-Wobjc-protocol-property-synthesis]
/Users/pfj/Developer/hand/hand.iOS/obj/iPhone/Debug/mtouch-cache/registrar.h(1724,82): error GF247FC6C: interface type 'NSString' cannot be passed by value; did you forget * in 'NSString'?
/Users/pfj/Developer/hand/hand.iOS/obj/iPhone/Debug/mtouch-cache/registrar.h(1800,45): error GF247FC6C: interface type 'NSString' cannot be passed by value; did you forget * in 'NSString'?
/Users/pfj/Developer/hand/hand.iOS/obj/iPhone/Debug/mtouch-cache/registrar.h(1802,125): error GF247FC6C: interface type 'NSString' cannot be passed by value; did you forget * in 'NSString'?
MTOUCH : error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
```

```
    Using Xcode 11.3.1 (11C504) found in /Applications/Xcode.app/Contents/Developer
    Xamarin.iOS 13.14.1.17 (d16-5): d30880059) using framework: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk
```

This appears to be a duplicate of https://github.com/xamarin/xamarin-macios/issues/7733

**Comment by dalexsoto** [comment] 2020-01-22 00:57
Yes, this is a dupe of #7733 and should be fixed once https://github.com/xamarin/xamarin-macios/pull/7735 is merged

**Closed** 2020-01-22 15:28 UTC
Labels: bug, regression
