### ISSUE TITLE
Failed to marshal the Objective-C object (type: __NSTaggedDate), type 'Foundation.NSDate&' does not have a constructor that takes one IntPtr argument

### ISSUE THREAD

**Issue by AlinNereid** [xamarin/xamarin-macios#4824] opened 2018-09-16 16:15 UTC
### Steps to Reproduce
1. Create and add a NSDatePickerCell object to a View
2. Subscribe to ValidateProposedDateValue event
3. Compile the solution in Release mode (with Debug information to None)
4. Open the application and change the date
5. The application crash

### Expected Behavior
Change the value of date picker
### Actual Behavior
Crash application with the following error:
Unhandled Exception:
System.Exception: Failed to marshal the Objective-C object 0xc1c1b0200000000d (type: __NSTaggedDate). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'Foundation.NSDate&' does not have a constructor that takes one IntPtr argument).
  at ObjCRuntime.Runtime.MissingCtor (System.IntPtr ptr, System.IntPtr klass, System.Type type, ObjCRuntime.Runtime+MissingCtorResolution resolution) [0x00063] in <d60f531997154f158d706441a369e1c6>:0 
  at ObjCRuntime.Runtime.ConstructNSObject[T] (System.IntPtr ptr, System.Type type, ObjCRuntime.Runtime+MissingCtorResolution missingCtorResolution) [0x0002a] in <d60f531997154f158d706441a369e1c6>:0 
  at ObjCRuntime.Runtime.GetNSObject (System.IntPtr ptr, System.Type target_type, ObjCRuntime.Runtime+MissingCtorResolution missingCtorResolution, System.Boolean evenInFinalizerQueue, System.Boolean& created) [0x000c1] in <d60f531997154f158d706441a369e1c6>:0 
  at ObjCRuntime.Runtime.GetNSObjectWithType (System.IntPtr ptr, System.IntPtr type_ptr, System.Boolean& created) [0x0000d] in <d60f531997154f158d706441a369e1c6>:0 
  at ObjCRuntime.Runtime.get_nsobject_with_type (System.IntPtr obj, System.IntPtr type, System.Boolean& created, System.Int32& exception_gchandle) [0x00005] in <d60f531997154f158d706441a369e1c6>:0 
--- End of stack trace from previous location where exception was thrown ---
  at (wrapper managed-to-native) AppKit.NSApplication.NSApplicationMain(int,string[])
  at AppKit.NSApplication.Main (System.String[] args) [0x00040] in <d60f531997154f158d706441a369e1c6>:0 
  at TestDatePicker.MainClass.Main (System.String[] args) [0x00005] in <1d407f9acd1f41ec9c8b92e646a0235a>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: Failed to marshal the Objective-C object 0xc1c1b0200000000d (type: __NSTaggedDate). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'Foundation.NSDate&' does not have a constructor that takes one IntPtr argument).
  at ObjCRuntime.Runtime.MissingCtor (System.IntPtr ptr, System.IntPtr klass, System.Type type, ObjCRuntime.Runtime+MissingCtorResolution resolution) [0x00063] in <d60f531997154f158d706441a369e1c6>:0 
  at ObjCRuntime.Runtime.ConstructNSObject[T] (System.IntPtr ptr, System.Type type, ObjCRuntime.Runtime+MissingCtorResolution missingCtorResolution) [0x0002a] in <d60f531997154f158d706441a369e1c6>:0 
  at ObjCRuntime.Runtime.GetNSObject (System.IntPtr ptr, System.Type target_type, ObjCRuntime.Runtime+MissingCtorResolution missingCtorResolution, System.Boolean evenInFinalizerQueue, System.Boolean& created) [0x000c1] in <d60f531997154f158d706441a369e1c6>:0 
  at ObjCRuntime.Runtime.GetNSObjectWithType (System.IntPtr ptr, System.IntPtr type_ptr, System.Boolean& created) [0x0000d] in <d60f531997154f158d706441a369e1c6>:0 
  at ObjCRuntime.Runtime.get_nsobject_with_type (System.IntPtr obj, System.IntPtr type, System.Boolean& created, System.Int32& exception_gchandle) [0x00005] in <d60f531997154f158d706441a369e1c6>:0 
--- End of stack trace from previous location where exception was thrown ---
  at (wrapper managed-to-native) AppKit.NSApplication.NSApplicationMain(int,string[])
  at AppKit.NSApplication.Main (System.String[] args) [0x00040] in <d60f531997154f158d706441a369e1c6>:0 
  at TestDatePicker.MainClass.Main (System.String[] args) [0x00005] in <1d407f9acd1f41ec9c8b92e646a0235a>:0 
### Environment
=== Visual Studio Community 2017 for Mac ===

Version 7.6.5 (build 20)
Installation UUID: 007f3429-0791-4e56-bc19-3e23ad66a801
Runtime:
	Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000301

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.6.0.14 (Visual Studio Community)
Hash: 1a6e2786
Branch: 
Build date: 2018-08-28 00:12:06-0400

=== Xamarin.iOS ===

Version: 11.14.0.14 (Visual Studio Community)
Hash: 1a6e2786
Branch: HEAD
Build date: 2018-08-28 00:12:06-0400

=== Xamarin.Android ===

Not Installed

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706050020
Git revision: f6a29a810eb4b81ceb9a4ea4ba411da98b6e25cf
Build date: 2018-09-11 21:34:07+00
Build branch: release-7.6
Xamarin extensions: 097e18c3e104c652bde3a02799dcba13eaad6f7b

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Internet of Things (IoT) development (Preview) 7.1

```
```

### Build Logs

https://gist.github.com/AlinNereid/7298dc749c9f1db8e228053de8467ed0

### Example Project (If Possible)

[TestDatePicker.zip](https://github.com/xamarin/xamarin-macios/files/2386753/TestDatePicker.zip)

**Comment by rolfbjarne** [comment] 2018-09-17 05:47
This is a duplicate of #4254, and already fixed (but not released to stable yet).

As a workaround, you can either try the Beta channel, or:

* Add `--registrar:partial` to the additional mmp arguments in the project's Mac Build options.
* Set `Linker behavior` to `Don't Link` in the same place.

**Closed by rolfbjarne** 2018-09-17 05:47 UTC
