### ISSUE TITLE
Proxy authentication required(407) is returned only for https connection on Mac application with VS for Mac 7.6.11.

### ISSUE THREAD

**Issue by MizuhoYASOSHIMA** [xamarin/xamarin-macios#5151] opened 2018-11-20 10:47 UTC
### Steps to Reproduce

1. Prepare network which has proxy with authentication.
2. Run sample application.
3. Input a URL starts with "https://" into URL field, fill other proxy information filed and click "GET".

### Expected Behavior
success to get the specified page and "OK" appears in the text box.

### Actual Behavior
Proxy authentication required(407) occurs.

Input a URL start with "http://" works properly.
And attached sample program works with "https" on Visual Studio for Mac 7.4.1 properly too.

### Environment

```
=== Visual Studio Professional 2017 for Mac ===

Version 7.6.11 (build 9)
Installation UUID: 728400ae-5136-42be-bfcb-415fc593041f
Runtime:
	Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000309

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime version:
	2.1.2
	2.1.1
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK version:
	2.1.302
	2.1.301
	2.1.4
	2.0.0
MSBuild SDK: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version:1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version:9.0.0.20 (Visual Studio Professional)
Android SDK: /Users/yasoshimamizuho/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android Version:
		6.0 (API Level 23)
		8.1 (API Level 27)

SDK Tools Version: 25.2.3
SDK Platform Tool Version: 25.0.1
SDK Build Tool Version: 25.0.1

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL のコードは以下から入手できます。
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.0.0.0 (Visual Studio Professional)
Hash: b40230c0
Branch: 
Build date: 2018-09-27 11:41:37-0400

=== Xamarin.iOS ===

Version: 12.2.1.10 (Visual Studio Professional)
Hash: f2a05edd
Branch: d15-9
Build date: 2018-10-31 18:55:57-0400

=== Build Information ===

Release ID: 706110009
Git revision: d7cd66f5e3acd3d46ba0b94a0c935378f828bde0
Build date: 2018-10-31 17:17:12+00
Build branch: release-7.6
Xamarin extensions: bc9b985bfcb480b04a208a6d4045adc443a07857

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Wed Oct 10 23:06:14 PDT 2018
    root:xnu-4570.71.13~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Team Foundation Version Control for TFS and Azure DevOps 0.4.3.1

```

### Example Project (If Possible)

[MacProxyTest.zip](https://github.com/xamarin/xamarin-macios/files/2599290/MacProxyTest.zip)

**Comment by dalexsoto** [comment] 2018-11-21 15:45
@mandel-macaque could you have a look at this one? Thanks!

**Comment by nhattruong061** [comment] 2018-12-03 06:45
I have same issues. Any one? :(

**Comment by mandel-macaque** [comment] 2018-12-07 12:31
@nhattruong061 @MizuhoYASOSHIMA I'm going to take a look at this. Are there any special settings you are using for the proxy? Or can I simply set up a proxy with auth?

**Comment by MizuhoYASOSHIMA** [comment] 2018-12-10 02:02
Thank you for having looking at.
I used proxy with NTLM authentication  and got the error.
(This proxy is my company', so I don't know detailed setting of the proxy.)
I also used proxy with Basic authentication (using Squid) and had no error.
So it seems that the issue is related to NTLM authentication.

**Comment by mandel-macaque** [comment] 2018-12-10 11:51
@MizuhoYASOSHIMA thanks for the info! I was using squid with basic auth and could not reproduce the issue. I'll set up a proxy with NTLM auth and will try to reproduce and debug the issue.

**Comment by mandel-macaque** [comment] 2019-01-11 12:06
Hello, sorry for the late reply but we have been closely looking at reproducing the issue and we have noticed that, with the information we have so far, we are not able to create an environment that is like yours. I have requested some help from our sysadmins and their feedback is the only product from Microsoft that will match a similar setup (proxy + NTLM) is Microsoft Forefront TMG 2010  which is a discontinued product.

Can you please request more information about the environment, if possible the product used to set the proxy so that we can mimic the setup and move fwd with a fix.

Thanks for your help :)

**Comment by MizuhoYASOSHIMA** [comment] 2019-01-15 02:41
Hello, thank you for keeping having look at this issue!
I requested detailed information to our IT department. When I get it, I'll let you know.

**Comment by mandel-macaque** [comment] 2019-01-23 16:24
Let me ask our sysadmin and I'll get back to you.

**Comment by mandel-macaque** [comment] 2019-01-30 12:07
Hello, the information I got from the sysadmins is that we tried several open source proxies that support NTLM but we do not believe that the setup is the one you are using. Unfortunately without the information of your setup we cannot follow up the issue since we will probably will not be working in the same environment. 

I am closing the issue until we can have further information about your setup. Please let you IT department know about this fact. Maybe we could use a private issue for this.

**Closed by mandel-macaque** 2019-01-30 12:07 UTC
Labels: macOS, need-info

**Comment by MizuhoYASOSHIMA** [comment] 2019-01-30 23:46
Thank you so much for your cooperation.
I'll ask our IT department again.
If I get new information about this, I'll make a new private issue.
