### ISSUE TITLE
New iOS 13 UINavigationBarAppearance including standardAppearance, scrollEdgeAppearance not available

### ISSUE THREAD

**Issue by jmlumpkin** [xamarin/xamarin-macios#6834] opened 2019-08-22 19:48 UTC
In iOS 13, it appears that a new class is available called UINavigationBarAppearance. This has a few new properties like standardAppearance and scrollEdgeAppearance. I don't know if this fixes my issue, but I have tried so many things (see https://forums.xamarin.com/discussion/166561/bartintcolor-does-not-work-with-preferslargetitles-in-ios-13/). Images available on SO post at https://stackoverflow.com/questions/57615878/bartintcolor-does-not-work-with-preferslargetitles-in-ios-13-in-xamarin

### Steps to Reproduce

1. Create an app, and use the following code to maintain navbars
```this.NavigationController.NavigationBar.BarTintColor = UIColor.FromRGB(3, 117, 178);
            this.NavigationController.NavigationBar.TintColor = UIColor.White;
            this.NavigationController.NavigationBar.Translucent = false;
            this.NavigationController.NavigationBar.TitleTextAttributes = new UIStringAttributes
            {
                ForegroundColor = UIColor.White

            };

            this.NavigationController.NavigationBar.PrefersLargeTitles = true;
            this.NavigationController.NavigationBar.LargeTitleTextAttributes = new UIStringAttributes
            {
                ForegroundColor = UIColor.White
            };
```

2. Compile and run against 12.99, notice that BarTintColor is not working. Everything else does. 
3. Target iOS 12, compile and run, and works. 

### Expected Behavior
Without many changes, should work just like iOS 12. Everything appears to work except setting BarTintColor, when using PrefersLargeTitles. 

### Actual Behavior
PrefersLargeTitles works, and when scrolling, it looks correct. But on first load or at the top of the list, bartintcolor appears white. 

### Environment

```
Visual Studio Enterprise 2019 for Mac
Version 8.2.4 (build 17)
Installation UUID: 5d3cd6ad-14fd-4029-bbe9-514ca3118b6b
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000327

Mono Framework MDK
Runtime:
	Mono 6.0.0.327 (2019-02/f8ea05bddcb) (64-bit)
	Package version: 600000327

NuGet
Version: 5.1.0.6013

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.5
	2.1.9
	2.1.8
	2.1.7
	2.1.6
	2.1.2
SDK: /usr/local/share/dotnet/sdk/2.2.300/Sdks
SDK Versions:
	2.2.300
	2.2.107
	2.2.105
	2.1.505
	2.1.504
	2.1.503
	2.1.500
	2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

Xamarin.Profiler
Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 9.4.1.0 (Visual Studio Enterprise)
Commit: xamarin-android/d16-2/ebd65c9
Android SDK: /Users/jmlumpkin/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

Microsoft Mobile OpenJDK
Java SDK: /Users/jmlumpkin/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 1.2.0.60
Hash: 686c817
Branch: remotes/origin/d16-2
Build date: 2019-08-07 15:49:58 UTC

Apple Developer Tools
Xcode 11.0 (14921.5)
Build 11M392q

Xamarin.Mac
Version: 5.14.0.114 (Visual Studio Enterprise)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:06-0400

Xamarin.iOS
Version: 12.14.0.114 (Visual Studio Enterprise)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:05-0400

Xamarin Designer
Version: 16.2.0.379
Hash: 3f0652957
Branch: remotes/origin/d16-2
Build date: 2019-08-01 17:32:50 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 802040017
Git revision: 9b155edbf23e9fe8b477b3236a342164fabf5f6b
Build date: 2019-08-16 00:21:01+00
Build branch: release-8.2
Xamarin extensions: 9f2598b5f2371ba2903988c2cd87a9759d0255f2

Operating System
Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

Enabled user installed extensions
Team Foundation Version Control for TFS and Azure DevOps 0.4.4.5

```

**Comment by rolfbjarne** [comment] 2019-08-23 09:55
I don't think this is a bug in Xamarin.iOS since we're just a layer on top of iOS (except that we might be missing some bindings you'd need, but it doesn't look like that's the case here).

Have you seen this: https://forums.developer.apple.com/thread/117505? It looks like somebody else ran into a very similar problem.

Here's the video from WWDC 2019 that forum post talks about, which also seems to explain a few things: https://developer.apple.com/videos/play/wwdc2019/224/

If you still can't make it work, my suggestion would be to try to make it work with an Xcode project. If that doesn't work either, you can ask in Apple's forums or StackOverflow (and it's more likely you'll found someone to help, because the Xamarin users are a minority compared to the total of the Apple users). If the Xcode project works, but the Xamarin.iOS one doesn't, then attach both here, reopen the issue and we'll be happy to have a second look at the problem.

**Comment by jmlumpkin** [comment] 2019-08-23 12:05
I did not come across that (the forums were not working there yesterday for me). This is nearly the exact same problem. But if you look at their solution (navigationItem.scrollEdgeAppearance = navigationController.navigationBar.standardAppearance), scrollEdgeAppearance and standardAppearance are something that Xamarin isn't exposing. 

I actually did try this in a sample app using the default new project in VS for Mac. That actually is not showing this behavior, so something there is working. I do not see though how that default app is setting these settings. I am assuming its in the LaunchScreen.storyboard, which we are not using. 

I just saw Xamarin.iOS 12.99.3.5 was posted, will update and see what happens.

**Comment by jmlumpkin** [comment] 2019-08-23 12:28
12.99.3.5 includes standard and scrolledgeapperance, so I am getting somewhere! I have some to do (actually set standard appearance), but applying update from last night made a change.

**Comment by jmlumpkin** [comment] 2019-08-23 15:39
Ok, I have determined what I think is going on here, and was able to get it to work in Xcode, but not in Xamarin. It did take some work, as several times I ran into the exact same issue in Xcode. I think its because the appearance must be instanced, and when I get it to work in Swift, but not in C#, it appears a type missmatch. 

In Swift:
`
let appearance = UINavigationBarAppearance()
`
`
appearance.backgroundColor = .purple
self.navigationController?.navigationBar.scrollEdgeAppearance = appearance
self.navigationController?.navigationBar.standardAppearance = appearance
`

In C#
`
var appearance = this.NavigationController.NavigationBar.StandardAppearance; // should just be bale to do UINavigationBarAppearance
`
`
 //var appearance = new UINavigationBarAppearance();
appearance.BackgroundColor = UIColor.Purple;
`
`
this.NavigationController.NavigationBar.ScrollEdgeAppearance = appearance;
this.NavigationController.NavigationBar.StandardAppearance = appearance;
`

If I try to just use UINavigationBarAppearance, I get a `Cannot implicitly convert type 'UIKit.UINavigationBarAppearance' to 'UIKit.UINavigationBar.UINavigationBarAppearance'` error. If I do it the way uncommented, it crashes at runtime
`
{System.InvalidCastException: Specified cast is not valid.
  at (wrapper castclass) System.Object.__castclass_with_cache(object,intptr,intptr)
  at ObjCRuntime.Runtime.ConstructNSObject[T] (System.IntPtr ptr, System.Type type, ObjCRuntime.Runtime+MissingCtorResolution missingCtorResolution) [0x0003b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.99.3.5/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:1133 
  at ObjCRuntime.Runtime.GetNSObject[T] (System.IntPtr ptr) [0x000d1] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.99.3.5/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:1274 
  at UIKit.UINavigationBar.get_StandardAppearance () [0x0000d] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.99.3.5/src/Xamarin.iOS/UINavigationBar.g.cs:692 
  at navbartest.iOS.BrowseViewController.ViewDidLoad () [0x00072] in /Users/jmlumpkin/Projects/navbartest/iOS/ViewControllers/BrowseViewController.cs:32 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.99.3.5/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.99.3.5/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at navbartest.iOS.Application.Main (System.String[] args) [0x00001] in /Users/jmlumpkin/Projects/navbartest/iOS/Main.cs:12 }`

This functionality did change in 12.99.3.5, as standard/scroll were not available before. 

I am trying to use the example that @rolfbjarne included. This twitter thread (from David Duncan, the gentleman presenting in the video) explains as well - https://twitter.com/rincewindsama/status/1143917018397102080. 

This SO answer specifically got it working for me on Xcode - https://stackoverflow.com/questions/56556254/in-ios13-the-status-bar-background-colour-is-different-from-the-navigation-bar-i/56941896#56941896 . Previously, many were referencing the class directly not the objects. 

Attached are an Xcode example and Xamarin. Xcode based off default master/detail project. Xamarin based off default iOS project. 
[navbartesting-xcode.zip](https://github.com/xamarin/xamarin-macios/files/3535196/navbartesting-xcode.zip)
[navbartest-xamarin.zip](https://github.com/xamarin/xamarin-macios/files/3535197/navbartest-xamarin.zip)

**Comment by jmlumpkin** [comment] 2019-08-23 15:41
@rolfbjarne I can not reopen this issue due to permissions.

**Comment by rolfbjarne** [comment] 2019-08-23 16:10
Thanks! I can reproduce something strange now, I'll have a look next week.

**Comment by rolfbjarne** [comment] 2019-08-28 08:21
This is now fixed (https://github.com/xamarin/xamarin-macios/commit/37e710c44b0cdd60535ffc0b6fed17e582c43ba9), and this works:

```csharp
var appearance = new UINavigationBarAppearance();
```

I can provide a package in a couple of hours if you want to try out the fix.

**Closed by rolfbjarne** 2019-08-28 08:21 UTC
Labels: bug, iOS

**Comment by rolfbjarne** [comment] 2019-08-28 12:18
@jmlumpkin you can download and install this package to try it out: [xamarin.ios-12.99.4.1.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode11/37e710c44b0cdd60535ffc0b6fed17e582c43ba9/250/package/xamarin.ios-12.99.4.1.pkg)

**Comment by rolfbjarne** [comment] 2019-08-28 12:19
Yes, the fix would be included in the next preview, but if the fix is incomplete it will take longer to get a complete fix.
