### ISSUE TITLE
[net6][iOS] `Ran out of trampolines of type 1` running on x64 simulator

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-macios#14855] opened 2022-04-29 15:13 UTC
### Steps to Reproduce

1. Build and run a large app with the x64 iOS simulator

### Expected Behavior
The app runs without failing.

### Actual Behavior

```
Ran out of trampolines of type 1 in '7B5B7D87-1D1E-43DB-9BB1-12062FA2B779/data/Containers/Bundle/Application/7599D867-453F-4D78-99CA-4EDBDB515629/My.app/System.Private.CoreLib.dll' (limit 4096)
```

### Environment

.NET 6 Mobile RC2

### Build Logs

On demand.

### Other details

Note that this does not reproduce on a physical device.

It tried changing this:
```
<MonoAOTCompilerDefaultAotArguments Include="nimt-trampolines=4000" />
<MonoAOTCompilerDefaultAotArguments Include="ntrampolines=10000" />
<MonoAOTCompilerDefaultAotArguments Include="nrgctx-fetch-trampolines=256" />
<MonoAOTCompilerDefaultAotArguments Include="ngsharedvt-trampolines=8192" />
<MonoAOTCompilerDefaultAotArguments Include="nftnptr-arg-trampolines=8000" />
<MonoAOTCompilerDefaultAotArguments Include="nrgctx-trampolines=31000" />		
```

But since the AOT compiler does not seem to run in this context, it's likely not using these parameters.

Related: https://github.com/dotnet/runtime/issues/53033

**Comment by jeromelaban** [comment] 2022-04-29 15:22
Yes, it's this one, from this commit:  https://github.com/unoplatform/Uno.Gallery/commit/233b06d1f8065c86c51d68ad3be45ec3741b1cf7.

You'll need to build `Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj` for `net6.0-ios`. I'm doing this on windows, if that matters.

**Comment by jeromelaban** [comment] 2022-04-29 15:26
One additional information I discovered, if I disable the interpreter, the application runs properly. The hint was in the stack trace:

```
	  at <unknown> <0xffffffff>
	  at System.Object:__icall_wrapper_ves_icall_mono_delegate_ctor_interp <0xffffffff>
	  at <>c__DisplayClass0_0:<Build>b__0 <0x003c2>
	  at Uno.Material.__Resources._mergedpages_c69cbc6d79c924ed978294ad194451a9_mergedpagesRDSC61:Build <0x005b8>
	  at <>c:<Get_3_289>b__126_2 <0x0001e>
```

**Comment by rolfbjarne** [comment] 2022-05-03 11:52
I can reproduce, here's a crash report: https://gist.github.com/rolfbjarne/8038c203eec8a33fc580bee41866d75b

I believe this is because:

* We enable the AOT compiler when using the interpreter, because we need to AOT-compile `System.Private.CoreLib.dll`.
* We're not in FullAOT mode (we're interpreting), so this block isn't executed:

https://github.com/dotnet/runtime/blob/c73386ba4da885010f3126d5e841d1ab51edfce5/src/mono/mono/mini/aot-runtime.c#L2278-L2283

* Which means we'll never get here, because USE_PAGE_TRAMPOLINES will be false:

https://github.com/dotnet/runtime/blob/c73386ba4da885010f3126d5e841d1ab51edfce5/src/mono/mono/mini/aot-runtime.c#L5858

* And instead we'll go here:

https://github.com/dotnet/runtime/blob/c73386ba4da885010f3126d5e841d1ab51edfce5/src/mono/mono/mini/aot-runtime.c#L5860

* And eventually end up here:

https://github.com/dotnet/runtime/blob/c73386ba4da885010f3126d5e841d1ab51edfce5/src/mono/mono/mini/aot-runtime.c#L5770-L5771

The current workaround is to disable the interpreter.

I'm moving to dotnet/runtime, since I believe that's where the issue is.

**Comment by rolfbjarne** [comment] 2022-05-03 11:52
This issue was moved to dotnet/runtime#68808

**Closed by rolfbjarne** 2022-05-03 11:52 UTC
Labels: dotnet, need-attention
