### ISSUE TITLE
[XI]  ProtocolTest failure on device with Release with linkall enabled with d15-7 builds

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#3812] opened 2018-03-23 21:35 UTC
### Steps to Reproduce

1. Build and execute  monotouch-test on device with Release, linkall  and no llvm enabled

### Expected Behavior
Tests should execute successfully on device
### Actual Behavior
Protocol test in binding project is failing
[FAIL] ProtocolTest.OnlyProtocol :   [Protocol] IP1
[FAIL] ProtocolTest.ProtocolWithBaseType :   [Protocol] IP2
[FAIL] ProtocolTest.ProtocolWithBaseTypeAndModel :   [Protocol] IP3

This issue didn't occur in d15-6, seems to be a regression with d15-7.

### Environment

"
=== Visual Studio Community 2017 for Mac ===

Version 7.4 (build 1033)
Installation UUID: 74c37335-5878-4fa7-8f71-09bc48b661c5
Runtime:
	Mono 5.8.0.129 (2017-10/835a98d8559) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000129

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.2.0.15 (Visual Studio Community)
Android SDK: /Users/gourikumari/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)

SDK Tools Version: 25.2.3
SDK Platform Tools Version: 25.0.1
SDK Build Tools Version: 25.0.1

Java SDK: /usr
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.2.0.20 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.10.0.43 (Visual Studio Community)
Hash: 3627e873
Branch: d15-7
Build date: 2018-03-21 22:33:57-0400

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704001033
Git revision: 053991068f3c88497d3e5cc52fe7fdf57c28b62f
Build date: 2018-02-28 05:02:28-05
Xamarin addins: cc3283953e0af0b8bfab1bdfdf847d9e403c4606
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Thu Jun 15 17:36:27 PDT 2017
    root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Gist Ide Information 1.1.0
Internet of Things (IoT) development (Preview) 7.1

"
### Build Logs
Results from bot:
Build Log: http://xqa.blob.core.windows.net/gist/report-fc1d6d0389194f8ca1a5afccfd4e21f8.txt
Test and Device Log: http://xqa.blob.core.windows.net/gist/monotouchtest-ios04-26-2883f2d0ba153dbdfb07cfbe77e7221d97200ca11e04-26-28-7db01a4e963a49959f44898cfea4166b.zip

Can reproduce with , Version: 11.10.0.43 (Visual Studio Community)
Hash: 3627e873

> VS bug [#591134](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/591134)

**Comment by mandel-macaque** [comment] 2018-03-26 14:30
Can you please give me a pointer to the test case that fails?

**Comment by mandel-macaque** [comment] 2018-03-26 14:31
No need found it.

**Comment by mandel-macaque** [comment] 2018-03-26 16:29
Tested it with master https://gist.github.com/mandel-macaque/997cea906e0f9dff0f34fe26cdef79ff

And does fail. Will get back here with results for d15-6 and d15-7.

**Comment by mandel-macaque** [comment] 2018-03-27 23:28
Confirming this as a regression, the tests do work on d15-6.

**Comment by spouliot** [comment] 2018-03-28 15:58
@rolfbjarne let's figure out why the device bot did not report that case

**Comment by spouliot** [comment] 2018-03-28 20:57
So I misread _Build and execute monotouch-test on device with Release, linkall and no llvm enabled_ for being a linkall.app test. That explains why the device bot did not hit this.

The failures are due to changes in the tests in 15.7, so not a regression from 15.6.

We don't generally use "Link all" on monotouch-test (matrix is too huge) but since it works (or it did) maybe it should become our default on devices (i.e. replace the default "Link SDL" for this app).

Keeping open for @rolfbjarne to confirm it's fine since `Runtime.DynamicRegistrationSupported` is `true` and the `[Protocol]` attribute is not present.

**Comment by rolfbjarne** [comment] 2018-04-03 11:22
The ProtocolTests require the LINKALL conditional compilation symbol when linkall is enabled: https://github.com/xamarin/xamarin-macios/blob/1dee418501fc1416aa175f083f2a7df1fb611f8e/tests/bindings-test/ProtocolTest.cs#L24-L27

This symbol must be set in the bindings-test project (which monotouch-test references).

@spouliot I can easily add this scenario (monotouch-test on device with linkall enabled) to the device tests if we wish (it's a one-line addition in xharness). It might be more complicated for Gouri to adjust her tests (since it would require modifying a referenced project, not monotouch-test.csproj itself).

Taking it off the d15-7 milestone, since this is a testing problem.

**Comment by spouliot** [comment] 2018-04-03 17:12
@rolfbjarne instead of more (and nearly identical) configuration could we only test link all in monotouch-test ? it's not like it differs a lot since there's about no user code (tests) that is not preserved.

Also due to how vsts/github sync work the milestone must exists in both (and we don't control vsts) so I'm moving it to 15.8. In any case triaged issues should all have a milestone.

**Comment by rolfbjarne** [comment] 2018-04-04 10:56
@spouliot yes, I can change monotouch-test to be linkall, that's simple enough.

**Comment by rolfbjarne** [comment] 2018-04-26 21:06
@spouliot so I found a better fix for this particular problem (in PR #4004), but I can still change monotouch-test to be linkall if you wish.

**Comment by spouliot** [comment] 2018-04-26 21:39
I like the approach but it won't _entirely_ solve the problem, i.e. as long as we build and test with "Link SDK" it remains too easy to add tests that will fail under "Link all", leading to other, similar bug reports.

However if we build/test with "Link All" then tests won't fail if someone builds/test it with "Link SDK". Of course it _could_ fail - but it's much harder or requires some kind of premeditation ;-)

**Closed** 2018-04-27 11:11 UTC
Labels: bug, iOS, vs-sync
