### ISSUE TITLE
MAUI/net6 - could not compile IOS native binding project - Access to the path is denied.

### ISSUE THREAD

**Issue by LukasKuchta** [xamarin/xamarin-macios#15981] opened 2022-09-16 08:56 UTC
### Steps to Reproduce

1. Create ios binding project to native libs
2. Try to complie
3. 

### Expected Behavior
dll as output

### Actual Behavior
```
CSC : error CS1566: Error reading resource 'AppConnect.framework' -- 'Access to the path 'C:\_projects\AppConnectBinding_net6\AppConne
ctBinding\AppConnectBinding\frameworks\AppConnect.xcframework\ios-arm64_armv7\AppConnect.framework' is denied.' [C:\_projects\AppConne
ctBinding_net6\AppConnectBinding\AppConnectBinding\AppConnectBinding.csproj]

Build FAILED.
```

### Environment
Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.4.0 Preview 1.0

**csproj** here
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-ios</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <IsBindingProject>true</IsBindingProject>
  </PropertyGroup>

  <ItemGroup>
    <ObjcBindingApiDefinition Include="ApiDefinition.cs" />
    <ObjcBindingCoreSource Include="StructsAndEnums.cs" />
    <ObjcBindingNativeLibrary Include="frameworks/AppConnect.xcframework/ios-arm64_armv7/AppConnect.framework"/>
  </ItemGroup>

    <ItemGroup>
    <NativeReference Include="frameworks/AppConnect.xcframework/ios-arm64_armv7/AppConnect.framework">
        <Kind>Framework</Kind>
        <Frameworks></Frameworks>
    </NativeReference>
    </ItemGroup>
    <ItemGroup>
    <Compile Remove="frameworks\sharpie_output\*" />
    </ItemGroup>
</Project>
```

<details>
<summary>
Path is valid but access deniend is reason of build
</summary>

```
c:\>cd C:\_projects\AppConnectBinding_net6\AppConnectBinding\AppConnectBinding\frameworks\AppConnect.xcframework\ios-arm64_armv7\AppConnect.framework

C:\_projects\AppConnectBinding_net6\AppConnectBinding\AppConnectBinding\frameworks\AppConnect.xcframework\ios-arm64_armv7\AppConnect.framework>dir
 Volume in drive C is Data
 Volume Serial Number is DE9D-E901

 Directory of C:\_projects\AppConnectBinding_net6\AppConnectBinding\AppConnectBinding\frameworks\AppConnect.xcframework\ios-arm64_armv7\AppConnect.framework

05/09/2022  10:39    <DIR>          .
05/09/2022  10:39    <DIR>          ..
05/09/2022  10:39             6,148 .DS_Store
31/03/2021  13:13         6,361,928 AppConnect
31/03/2021  13:13    <DIR>          Headers
05/09/2022  10:26               720 Info.plist
31/03/2021  13:15    <DIR>          Modules
               3 File(s)      6,368,796 bytes
               4 Dir(s)  157,660,282,880 bytes free

</details>
```

### Build Logs
```
PS C:\_projects\AppConnectBinding_net6\AppConnectBinding\AppConnectBinding> dotnet **build AppConnectBinding.csproj /bl:msbuild.binlog**
MSBuild version 17.3.0+92e077650 for .NET
C:\Program Files\dotnet\sdk\6.0.400\MSBuild.dll -consoleloggerparameters:Summary -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\6.0.400\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\6.0.400\dotnet.dll -maxcpucount -restore -verbosity:m /bl:msbuild.binlog AppConnectBinding.csproj
  Determining projects to restore...
  All projects are up-to-date for restore.
CSC : error CS1566: Error reading resource 'AppConnect.framework' -- 'Access to the path 'C:\_projects\AppConnectBinding_net6\AppConne
ctBinding\AppConnectBinding\frameworks\AppConnect.xcframework\ios-arm64_armv7\AppConnect.framework' is denied.' [C:\_projects\AppConne
ctBinding_net6\AppConnectBinding\AppConnectBinding\AppConnectBinding.csproj]

Build FAILED.

CSC : error CS1566: Error reading resource 'AppConnect.framework' -- 'Access to the path 'C:\_projects\AppConnectBinding_net6\AppConne
ctBinding\AppConnectBinding\frameworks\AppConnect.xcframework\ios-arm64_armv7\AppConnect.framework' is denied.' [C:\_projects\AppConne
ctBinding_net6\AppConnectBinding\AppConnectBinding\AppConnectBinding.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:12.31
```

**Comment by tj-devel709** [comment] 2022-09-16 17:24
Thank you for your feedback @LukasKuchta. Could you provide the binlogs so we can have a closer look?

**Comment by LukasKuchta** [comment] 2022-09-19 04:25
Hello, binlog file is attached here
[msbuild.zip](https://github.com/xamarin/xamarin-macios/files/9596137/msbuild.zip)

**Comment by LukasKuchta** [comment] 2022-09-22 11:44
@tj-devel709 second attemt here 
[log_folder.zip](https://github.com/xamarin/xamarin-macios/files/9625310/log_folder.zip)

**Comment by rolfbjarne** [comment] 2022-09-26 09:39
Try removing this line from the csproj:

```xml
<ObjcBindingNativeLibrary Include="frameworks/AppConnect.xcframework/ios-arm64_armv7/AppConnect.framework"/>
```

and let us know if that helps.

**Comment by LukasKuchta** [comment] 2022-09-29 09:22
@rolfbjarne it helps to removed error. But output dll has only 7kb. When i used it into project everythinks looks fine. But when i run project undefined symbols errors happens. 

Do you need another binlog from this build ?

**Comment by rolfbjarne** [comment] 2022-09-30 13:10
@LukasKuchta are there any other files next to the output dll? Can you list them? And yes, also get a binlog, please!

**Comment by LukasKuchta** [comment] 2022-10-03 07:52
Content of output folder is attached as image here (two files here .dll and .pdb) 
<img width="441" alt="list" src="https://user-images.githubusercontent.com/105702630/193526761-d338bc88-97a7-4cc2-a848-6242868586cd.PNG">

Log from my next attempt here: 
[log_folder02.zip](https://github.com/xamarin/xamarin-macios/files/9695611/log_folder02.zip)

**Comment by rolfbjarne** [comment] 2022-10-03 10:39
The problem is that your Windows isn't connected to a Mac:

> Task "CreateBindingResourcePackage" skipped, due to false condition; ('$(IsMacEnabled)' == 'true') was evaluated as ('false' == 'true').

Can you [connect to a Mac](https://learn.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/) and try again?

**Comment by LukasKuchta** [comment] 2022-10-05 06:28
@rolfbjarne It was point of evil in my trouble. Thanks for your time.  It is working now.

**Comment by rolfbjarne** [comment] 2022-10-05 07:13
Great thanks for letting us know!

I'm closing this in favor of #16244, which is clearer about the actual problem.

**Closed by rolfbjarne** 2022-10-05 07:13 UTC
Labels: need-attention
