### ISSUE TITLE
iOS depends on private symbols which prevents builds with no linking from submission (Xamarin.Forms and others)

### ISSUE THREAD

**Issue by amirvenus** [xamarin/xamarin-macios#5913] opened 2019-04-16 20:48 UTC
### Steps to Reproduce

1. Use latest XF nuget 3.6.0.293080
2. Archive for publishing in release mode
3. Upload using Application Loader

### Expected Behaviour

It should work fine as before

### Actual Behavior

Apple complains that the app makes reference to non-public APIs:

We identified one or more issues with a recent delivery for your app. Please correct the following issues, then upload again.

Non-public API usage:

The app references non-public selectors in App.iOS: addTemporaryAttribute:value:forCharacterRange:, addTemporaryAttributes:forCharacterRange:, behaviorWithType:, defaultBaselineOffsetForFont:, defaultLineHeightForFont:, finished, greekingThreshold, horizontalCornerRadius, initWithSource:convolutionState:weights:, initWithType:, postSession:didAddPlayer:, postSession:didReceiveData:fromPlayer:, postSession:didReceiveMessage:withData:fromPlayer:, postSession:didRemovePlayer:, postSession:player:didChangeConnectionState:, postSession:player:didSaveData:, preferredMetalContext, removeData:, removeTemporaryAttribute:forCharacterRange:, setGreekingThreshold:, setHorizontalCornerRadius:, setIsPrimary:, setShouldAntiAlias:, setUUID:, setVerticalCornerRadius:, shouldAntiAlias, temporaryAttribute:atCharacterIndex:effectiveRange:, temporaryAttribute:atCharacterIndex:longestEffectiveRange:inRange:, temporaryAttributesAtCharacterIndex:effectiveRange:, temporaryAttributesAtCharacterIndex:longestEffectiveRange:inRange:, textContainerChangedTextView:, toolTip, usesBackgroundSession, verticalCornerRadius
If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

> VS bug [#855982](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/855982)

**Comment by engmsaleh** [comment] 2019-04-17 21:50
@spouliot This is the first thing that I have checked on the beginning and this is the selected option actually and I got rejected with it
Please advise if there are anything I miss
![Screen Shot 2019-04-17 at 11 47 53 PM](https://user-images.githubusercontent.com/462150/56323210-7000b400-616b-11e9-8aae-a9b8014b1ee2.png)

**Comment by amirvenus** [comment] 2019-04-17 22:19
> For some reason (template?) you are not linking your application (i.e. `--nolink` is i the build logs). While _not_ linking should work (for submission) you're strongly encouraged to enable the managed linker. This produce a (much) smaller application and has extraneous performance (including startup) enhancements.
> 
> Can you try changing your "Linker behavior" from "Don't link" (current) to the _normal_ default of "Link Framework SDKs only" and try to submit again ? Thanks!

The issue exists in all 3 Linker modes. 
[Building (Release).txt](https://github.com/xamarin/xamarin-macios/files/3091765/Building.Release.txt)

**Comment by spouliot** [comment] 2019-04-17 22:27
Right now I can only duplicate this issue when using "Don't Link". Please attach the full build log (with `-v -v -v -v` **and** msbuild set to diagnostic level) and Apple's rejection email (the details could be different from the ones above). Thanks!

**Comment by amirvenus** [comment] 2019-04-17 22:31
How do I msbuild set to diagnostic level?

**Comment by engmsaleh** [comment] 2019-04-17 22:47
@amirvenus follow [these steps](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#Diagnostic_MSBuild_Output) for diagnostic level

**Comment by engmsaleh** [comment] 2019-04-17 23:09
@spouliot I have make diagnostic level build report for the iOS device as the last one I have sent was for iOS simulator
[diagnostic_build_output_device.txt](https://github.com/xamarin/xamarin-macios/files/3091878/diagnostic_build_output_device.txt)

I have noticed a thing and I think it might be the problem, I have made sure that **Link Framework SDKs only** is selected as per the screenshot here, but for some reason on the build output **--nolink**  is still selected  
![Screen Shot 2019-04-17 at 11 47 53 PM](https://user-images.githubusercontent.com/462150/56326461-63ce2400-6176-11e9-83b9-d1c2b3ec075c.png)

Could this be the issue?

**Comment by engmsaleh** [comment] 2019-04-18 01:32
After filling an internal issue with the Xamarin team, they advised doing the following 
> adding **--linksdkonly** to the Additional mtouch arguments on the iOS Build settings page  
As it seems that **Visual Studio** ignores the settings in GUI as a screenshot above

I have tested it and now get my build accepted by Apple without the above error
Please @amirvenus try the above suggestion and confirm if it solved yours also

**Comment by engmsaleh** [comment] 2019-04-18 01:44
Also, one another notice that I’m getting the following warning, although I’m not using location or any other modules that use it and it started also to appear randomly one week ago, 
Please advise if you have any suggestion for that.

> Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).
> 
> Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).
> 
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

**Comment by jgold6** [comment] 2019-04-18 02:13
I have had two reports in support cases where despite the setting for the linker options being "Link Framework SDKs only" and the <MtouchLink>SdkOnly</MtouchLink> elemnet being present in the appropriate property group in the .csproj file, that the build occurred as if "DOn't Link" was set. This is shown in the build output with --nolink being passed as an argument to Mtouch task. 

So there is a bug here in that the Linker setting in the GUI iOS BUild settings page, and the MtouchLink element in the .csproj file, are being ignored and the build is done with "Don't Link" option. 

I have not been able to reproduce this on my end though.

**Comment by spouliot** [comment] 2019-04-18 02:27
@jgold6 the GUI issue is a different issue then :(

@engmsaleh do not worry about the `Info,plist` warnings - they should disappear when linking properly.

What happens is that Apple sees extra API and warn you that using them requires some (privacy) entries in the `Info.plist`. Enabling the linker will remove those API (in most cases) and the warnings will disappear too.

**Comment by amirvenus** [comment] 2019-04-18 03:07
I will test it then 

What’s the mtouch argument for link all?

**Comment by EpicDrakkar** [comment] 2019-04-18 07:33
If I add --linksdkonly to the Additional mtouch arguments on the iOS Build settings page, Im having a crash in Debug whenever I open a WebKitView

The runtime function get_block_wrapper_creator has been linked away.

[error.txt](https://github.com/xamarin/xamarin-macios/files/3093211/error.txt)

**Comment by EpicDrakkar** [comment] 2019-04-18 10:22
Using --linksdkonly it worked for me. Nevertheless I had a crash using WKwebView with DecidePolicy which I didnt had before, but I did a work around to fix this, and now its published. Thanks!

**Comment by amirvenus** [comment] 2019-04-18 10:29
I tried --linksdkonly but it is still the same issue.

**Comment by EpicDrakkar** [comment] 2019-04-18 12:21
> --linksdkonly

Are you sure that you put the --linksdkonly with Release selection?

![Screenshot 2019-04-18 at 14 20 22](https://user-images.githubusercontent.com/7905478/56360506-23f25580-61e5-11e9-912e-7868033b6020.png)

**Comment by spouliot** [comment] 2019-04-18 12:49
@amirvenus "link all" is `mtouch` default, i.e. if `--nolink` or `linksdkonly` is not used (and not seen in your build logs). However using this option means you're responsible to preserve anything required by 3rd party code (e.g. things used thru reflection).

**Comment by amirvenus** [comment] 2019-04-18 14:01
This is my latest build using --linksdkonly switch again


[Building iOS (Release).txt](https://github.com/xamarin/xamarin-macios/files/3094696/Building.iOS.Release.txt)

**Comment by engmsaleh** [comment] 2019-04-18 14:09
@EpicDrakkar  This is the configurations that worked for me
![Screen Shot 2019-04-18 at 4 08 30 PM](https://user-images.githubusercontent.com/462150/56366849-522b6180-61f4-11e9-8c40-429a2fa57672.png)

**Comment by amirvenus** [comment] 2019-04-18 14:11
> @EpicDrakkar This is the configurations that worked for me
> ![Screen Shot 2019-04-18 at 4 08 30 PM](https://user-images.githubusercontent.com/462150/56366849-522b6180-61f4-11e9-8c40-429a2fa57672.png)

So you don't have LLVM enabled? I should try that too

**Comment by engmsaleh** [comment] 2019-04-18 14:13
@amirvenus Yes

**Comment by spouliot** [comment] 2019-04-18 14:22
I have some local fixes (so the following list is partial) but here are the mentioned selected and who/where git blames.

## addTemporaryAttribute:value:forCharacterRange:
Found in:
* `xkit.cs`
```
788b63d96f (Rolf Bjarne Kvinge 2018-10-01 14:17:28 +0200  800) 		[Export ("addTemporaryAttribute:value:forCharacterRange:")]
788b63d96f (Rolf Bjarne Kvinge 2018-10-01 14:17:28 +0200  806) 		[Export ("addTemporaryAttribute:value:forCharacterRange:")]

```
## addTemporaryAttributes:forCharacterRange:
Found in:
* `xkit.cs`
```
788b63d96f (Rolf Bjarne Kvinge 2018-10-01 14:17:28 +0200  730) 		[Export ("addTemporaryAttributes:forCharacterRange:")]

```
## behaviorWithType:
Found in:
* `coreanimation.cs`
```
5830166c63 (Rolf Bjarne Kvinge 2016-04-21 14:30:02 +0200 1783) 		[Static][Export ("behaviorWithType:")]

```
## defaultBaselineOffsetForFont:
Found in:
* `xkit.cs`
```
788b63d96f (Rolf Bjarne Kvinge 2018-10-01 14:17:28 +0200  827) 		[Export ("defaultBaselineOffsetForFont:")]

```
## defaultLineHeightForFont:
Found in:
* `xkit.cs`
```
788b63d96f (Rolf Bjarne Kvinge 2018-10-01 14:17:28 +0200  820) 		[Export ("defaultLineHeightForFont:")]

```
## finished
Found in:
* `avfoundation.cs`
```
5830166c63 (Rolf Bjarne Kvinge 2016-04-21 14:30:02 +0200  3819) 		[Export ("finished")]

```
* `foundation.cs`
```
bcc05aa5ff (Timothy Risi       2017-08-15 04:32:51 -0800 11803) 		[Export ("finished")]

```
## greekingThreshold
Found in:
* `pdfkit.cs`
```
5830166c63 (Rolf Bjarne Kvinge 2016-04-21 14:30:02 +0200 1775) 		[Export ("greekingThreshold")]

```
## initWithSource:convolutionState:weights:
Found in:
* `metalperformanceshaders.cs`
```
87f9e23989 (Timothy Risi       2017-11-28 11:29:05 -0900 3678) 		[Export ("initWithSource:convolutionState:weights:")]

```
## initWithType:
Found in:
* `coreanimation.cs`
```
5830166c63 (Rolf Bjarne Kvinge 2016-04-21 14:30:02 +0200 1767) 		[Export ("initWithType:")]

```
## postSession:didAddPlayer:
Found in:
* `gamekit.cs`
```
832db98110 (Alex Soto          2018-02-14 09:38:49 -0600 2447) 		[Export ("postSession:didAddPlayer:")]

```
## postSession:didReceiveData:fromPlayer:
Found in:
* `gamekit.cs`
```
832db98110 (Alex Soto          2018-02-14 09:38:49 -0600 2467) 		[Export ("postSession:didReceiveData:fromPlayer:")]

```
## postSession:didReceiveMessage:withData:fromPlayer:
Found in:
* `gamekit.cs`
```
832db98110 (Alex Soto          2018-02-14 09:38:49 -0600 2472) 		[Export ("postSession:didReceiveMessage:withData:fromPlayer:")]

```
## postSession:didRemovePlayer:
Found in:
* `gamekit.cs`
```
832db98110 (Alex Soto          2018-02-14 09:38:49 -0600 2452) 		[Export ("postSession:didRemovePlayer:")]

```
## postSession:player:didChangeConnectionState:
Found in:
* `gamekit.cs`
```
832db98110 (Alex Soto          2018-02-14 09:38:49 -0600 2457) 		[Export ("postSession:player:didChangeConnectionState:")]

```
## postSession:player:didSaveData:
Found in:
* `gamekit.cs`
```
832db98110 (Alex Soto          2018-02-14 09:38:49 -0600 2462) 		[Export ("postSession:player:didSaveData:")]

```
## preferredMetalContext
Found in:
* `vision.cs`
```
89071bc19d (Alex Soto          2017-07-18 11:12:10 -0500 1342) 		[NullAllowed, Export ("preferredMetalContext", ArgumentSemantic.Retain)]

```
## removeData:
Found in:
* `gameplaykit.cs`
```
5830166c63 (Rolf Bjarne Kvinge 2016-04-21 14:30:02 +0200 1991) 		[Export ("removeData:")]

```
## removeTemporaryAttribute:forCharacterRange:
Found in:
* `xkit.cs`
```
788b63d96f (Rolf Bjarne Kvinge 2018-10-01 14:17:28 +0200  743) 		[Export ("removeTemporaryAttribute:forCharacterRange:")]
788b63d96f (Rolf Bjarne Kvinge 2018-10-01 14:17:28 +0200  749) 		[Export ("removeTemporaryAttribute:forCharacterRange:")]

```
## setGreekingThreshold:
* Not found - try without `set` prefix.

Found in:
## setIsPrimary:
* Not found - try without `set` prefix.

Found in:
## setShouldAntiAlias:
* Not found - try without `set` prefix.

Found in:
## setUUID:
* Not found - try without `set` prefix.

Found in:
## shouldAntiAlias
Found in:
* `pdfkit.cs`
```
5830166c63 (Rolf Bjarne Kvinge 2016-04-21 14:30:02 +0200 1770) 		[Export ("shouldAntiAlias")]

```
## temporaryAttribute:atCharacterIndex:effectiveRange:
Found in:
* `xkit.cs`
```
788b63d96f (Rolf Bjarne Kvinge 2018-10-01 14:17:28 +0200  758) 		[Export ("temporaryAttribute:atCharacterIndex:effectiveRange:")]
788b63d96f (Rolf Bjarne Kvinge 2018-10-01 14:17:28 +0200  765) 		[Export ("temporaryAttribute:atCharacterIndex:effectiveRange:")]

```
## temporaryAttribute:atCharacterIndex:longestEffectiveRange:inRange:
Found in:
* `xkit.cs`
```
788b63d96f (Rolf Bjarne Kvinge 2018-10-01 14:17:28 +0200  771) 		[Export ("temporaryAttribute:atCharacterIndex:longestEffectiveRange:inRange:")]
788b63d96f (Rolf Bjarne Kvinge 2018-10-01 14:17:28 +0200  778) 		[Export ("temporaryAttribute:atCharacterIndex:longestEffectiveRange:inRange:")]

```
## temporaryAttributesAtCharacterIndex:effectiveRange:
Found in:
* `xkit.cs`
```
788b63d96f (Rolf Bjarne Kvinge 2018-10-01 14:17:28 +0200  713) 		[Export ("temporaryAttributesAtCharacterIndex:effectiveRange:")]
788b63d96f (Rolf Bjarne Kvinge 2018-10-01 14:17:28 +0200  720) 		[Export ("temporaryAttributesAtCharacterIndex:effectiveRange:")]

```
## temporaryAttributesAtCharacterIndex:longestEffectiveRange:inRange:
Found in:
* `xkit.cs`
```
788b63d96f (Rolf Bjarne Kvinge 2018-10-01 14:17:28 +0200  784) 		[Export ("temporaryAttributesAtCharacterIndex:longestEffectiveRange:inRange:")]
788b63d96f (Rolf Bjarne Kvinge 2018-10-01 14:17:28 +0200  791) 		[Export ("temporaryAttributesAtCharacterIndex:longestEffectiveRange:inRange:")]

```
## textContainerChangedTextView:
Found in:
* `xkit.cs`
```
788b63d96f (Rolf Bjarne Kvinge 2018-10-01 14:17:28 +0200   85) 		[Export ("textContainerChangedTextView:")]

```
## toolTip
Found in:
* `appkit.cs`
```
5830166c63 (Rolf Bjarne Kvinge 2016-04-21 14:30:02 +0200  8213) 		[Export ("toolTip")]
5830166c63 (Rolf Bjarne Kvinge 2016-04-21 14:30:02 +0200 14842) 		[Export ("toolTip")]
5830166c63 (Rolf Bjarne Kvinge 2016-04-21 14:30:02 +0200 15755) 		[Export ("toolTip")]
5830166c63 (Rolf Bjarne Kvinge 2016-04-21 14:30:02 +0200 17618) 		[Export ("toolTip")]
5830166c63 (Rolf Bjarne Kvinge 2016-04-21 14:30:02 +0200 19633) 		[Export ("toolTip")]
b59a82e6db (Chris Hamons       2017-07-19 09:00:13 -0500 26618) 		[Export ("toolTip")]

```
* `pdfkit.cs`
```
5830166c63 (Rolf Bjarne Kvinge 2016-04-21 14:30:02 +0200  606) 		[Export ("toolTip")]

```
## usesBackgroundSession
Found in:
* `cloudkit.cs`
```
5830166c63 (Rolf Bjarne Kvinge 2016-04-21 14:30:02 +0200 1251) 		[Export ("usesBackgroundSession", ArgumentSemantic.UnsafeUnretained)]

```

**Comment by EpicDrakkar** [comment] 2019-04-18 14:36
> @EpicDrakkar This is the configurations that worked for me
> ![Screen Shot 2019-04-18 at 4 08 30 PM](https://user-images.githubusercontent.com/462150/56366849-522b6180-61f4-11e9-8c40-429a2fa57672.png)

I was able to fix this issue this morning. linksdkonly did the trick for me.

**Comment by amirvenus** [comment] 2019-04-18 14:39
Removing the LLVM, setting Linker behvaiour to Link Framework SDKs and adding --linksdkonly did the job. 

Thanks

**Comment by Jak893** [comment] 2019-04-26 09:27
Hi, we've been blocked by this issue for the past week or so now. I appreciate from all the activity above there is work being done to address this but unfortunately, we think, due to us being dependant on an SQLite package, we cannot use the `--linksdkonly` fix as the build then fails with `MT2002: Failed to resolve "System.Diagnostics.CounterCreationDataCollection"`. Once this has all be merged in, is there any ETA on when an update version of the package will be available? I know that can sometimes be like asking how long a piece of string is, but any additional timeframes would be greatly appreciated :)

**Comment by spouliot** [comment] 2019-04-26 12:47
@Jak893 it's already merged in `master` so it should [1] be part of `d16-2` (not yet branched) and we're seeking approval to back port it into the [next stable release](https://github.com/xamarin/xamarin-macios/pull/5949) ([d16-1](https://docs.microsoft.com/en-us/xamarin/ios/release-notes/12/12.10)).

Specific dates are harder... but you can get a _good_ guess by reading https://docs.microsoft.com/en-us/visualstudio/productinfo/release-rhythm

[1] unless something cause us to revert it (not a common situation)

There's several assemblies that provide SQLite support. It looks like the one you're using is not built against .NET Standard (or against the XI BCL SDK) and that can create a few problems (like the one you mention). If possible see if there's a different build against **.NET Standard** as this will reduce future pain in addition to fixing this - e.g. by disabling the managed linker you are making your application much larger, disabling optimizations (so slower) and you get longer build times...

**Comment by Jak893** [comment] 2019-04-26 16:21
@spouliot That's perfect, definitely gives us something to work with in the meantime, thanks for the advice! Have a great weekend :)

**Comment by chamons** [comment] 2019-04-29 20:43
This is landed now in d16-1, the next major release, and master for future releases.

Thanks for the report everyone 👋

**Closed by chamons** 2019-04-29 20:43 UTC
Labels: bug, iOS, regression, vs-sync

**Comment by svrooij** [comment] 2019-06-14 13:59
This issue is back....
I've got
- Xamarin.iOS version 12.10.0.153
- Xamarin.Forms 4.0.0.497661

And when I build my application to publish to the app store, I get a nice message from Apple:
> You application has one or more issues.
> ITMS-90338: Non-public API usage - The app references non-public selectors in MyApp.iOS: applicationWillTerminate, ddSetLogLevel:, donothingatall:, localTarget, newSocketQueueForConnectionFromAddress:onSocket:, setOrientation:animated:, socket:didConnectToHost:port:, socket:didReadPartialDataOfLength:tag:, socket:didReceiveTrust:completionHandler:, socket:didWritePartialDataOfLength:tag:, socket:shouldTimeoutReadWithTag:elapsed:bytesDone:, socket:shouldTimeoutWriteWithTag:elapsed:bytesDone:, socketDidCloseReadStream:, socketDidSecure:, terminateWithSuccess, webSocket:didReceiveMessage:, webSocketDidClose:, webSocketDidOpen:. 

Anyone know how to solve this?

**Comment by rolfbjarne** [comment] 2019-06-14 14:07
@svrooij are you using any third-party libraries? I couldn't find any of those selectors in Xamarin.iOS, so my guess is that they're coming from somewhere else.

**Comment by svrooij** [comment] 2019-06-15 11:36
@rolfbjarne You're right it was a project created for the `Xamarin.Forms MasterDetail` template a few weeks ago, this includes a reference to `Xamarin.TextCloud.Agent` which is now unsupported. So maybe the template should be adjusted.

**Comment by rolfbjarne** [comment] 2019-06-17 07:29
> @rolfbjarne You're right it was a project created for the `Xamarin.Forms MasterDetail` template a few weeks ago, this includes a reference to `Xamarin.TextCloud.Agent` which is now unsupported. So maybe the template should be adjusted.

Great, thanks for letting us know. I've filed this internally ([#923024](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/923024)) so hopefully we'll get around to fix it .

**Comment by amirvenus** [comment] 2019-06-18 09:48
by the way, I realised using link all option results in a bigger binary than using linksdkonly option (almost double in size)

**Comment by joehanna** [comment] 2019-09-03 07:47
I am getting the same rejection from Apple - but the Linker setting was not the problem for me. Turning off LLVM solved it.

I am still getting this warning though:
```
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that 
use UIWebView APIs. See https://developer.apple.com/documentation/uikit/uiwebview for
more information
```

despite having added the appropriate attribute to `Assembly.cs`

`[assembly: ExportRenderer(typeof(WebView), typeof(Xamarin.Forms.Platform.iOS.WkWebViewRenderer))]`

**Comment by PureWeen** [comment] 2019-09-03 15:34
@joehanna Forms discussion about that issue going on here https://github.com/xamarin/Xamarin.Forms/issues/7323

**Comment by swapnil591** [comment] 2019-10-22 13:31
How to add --linksdkonly and where to add

**Comment by chamons** [comment] 2019-10-22 14:49
@swapnil591 - In your iOS project options, look for iOS Build -> Additional mtouch arguments.

![image](https://user-images.githubusercontent.com/6392201/67298726-45443f00-f4b1-11e9-97bb-9a0b299e8bd5.png)

**Comment by Dintwe** [comment] 2020-04-20 21:45
getting same issue

ITMS-90338: Non-public API usage

VS 2019 Mac 8.5.3 build 16

Xamarin Forms 4.5.0.617

<img width="967" alt="ios_build" src="https://user-images.githubusercontent.com/56117627/79802664-a82f6980-8360-11ea-87d0-fec42d0f95a3.png">

**Comment by Dintwe** [comment] 2020-04-20 21:58
getting same issue

ITMS-90338: Non-public API usage

VS 2019 Mac 8.5.3 build 16

Xamarin Forms 4.5.0.617

<img width="962" alt="ios_build" src="https://user-images.githubusercontent.com/56117627/79803618-9b137a00-8362-11ea-9f72-1045cbd97e30.png">
