### ISSUE TITLE
Xamarin.Mac Widget is not displayed in macOS Big Sur

### ISSUE THREAD

**Issue by schovan** [xamarin/xamarin-macios#10137] opened 2020-11-23 15:01 UTC
### Steps to Reproduce

1. Open Visual Studio for Mac and create a new Cocoa App solution from templates
2. Add a new project with a Widget implementation
3. Run the application

### Expected Behavior
Application starts and the Widget is displayed

### Actual Behavior
Application starts and works correctly, but the Widget is not displayed
(probably because of improved widgets in macOS Big Sur)

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.8.1 (build 37)
Installation UUID: bd9009c4-bee4-4e4a-9632-058d71ea6f3f
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

=== Roslyn (Language Service) ===

3.8.0-5.20515.7+713efb0e68d34ab75faaf709e071e5c2d8d4ed0e

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.100/Sdks
SDK Versions:
	5.0.100
	3.1.403
	3.1.402
	3.1.401
	3.1.302
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.0
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	2.1.23
	2.1.22
	2.1.21
	2.1.20

=== .NET Core 3.1 SDK ===

SDK: 3.1.403

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Not Installed

=== Microsoft OpenJDK for Mobile ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:30 UTC

=== Android Device Manager ===

Version: 16.8.0.45
Hash: fc0af5f
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:54 UTC

=== Apple Developer Tools ===

Xcode 12.2 (17535)
Build 12B45b

=== Xamarin.Mac ===

Version: 7.0.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:40-0500

=== Xamarin.iOS ===

Version: 14.6.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:41-0500

=== Xamarin Designer ===

Version: 16.8.0.507
Hash: e87b24884
Branch: remotes/origin/d16-8
Build date: 2020-10-29 00:31:38 UTC

=== Build Information ===

Release ID: 808010037
Git revision: acd8ddc086768c701bd641d6ec27316f45813175
Build date: 2020-11-17 12:49:41-05
Build branch: release-8.8
Xamarin extensions: acd8ddc086768c701bd641d6ec27316f45813175

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.1.0 Darwin Kernel Version 20.1.0
    Sat Oct 31 00:07:11 PDT 2020
    root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
```

**Comment by tj-devel709** [comment] 2020-11-23 17:43
Hello,
Thank you for your feedback! Unfortunately widgets are not supported in Xamarin.Mac.

**Comment by schovan** [comment] 2020-11-23 18:08
@tj-devel709 Widgets are supported in Xamarin.Mac and they were working for years, but they stopped working in Big Sur update. Can you please look at this issue? Do you need some additional information how to reproduce this issue? We need to solve this, because our customers may have already updated to Big Sur.

**Comment by schovan** [comment] 2020-11-25 15:42
@tj-devel709 this is `Info.pllist` of our widget project

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>Smart Job Manager Widget</string>
	<key>CFBundleIdentifier</key>
	<string>com.myq.smart-job-manager.widget</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Smart Job Manager Widget</string>
	<key>CFBundlePackageType</key>
	<string>XPC!</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0.2</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSMinimumSystemVersion</key>
	<string>10.12</string>
	<key>NSExtension</key>
	<dict>
		<key>NSExtensionPointIdentifier</key>
		<string>com.apple.widget-extension</string>
		<key>NSExtensionPrincipalClass</key>
		<string>TodayViewController</string>
		<key>com.apple.notificationcenter.widget.description</key>
		<string>Smart Job Manager Status Widget</string>
		<key>NSExtensionAttributes</key>
		<dict>
			<key>NSExtensionPointVersion</key>
			<string>2.0</string>
		</dict>
	</dict>
</dict>
</plist>
```
Implementation of a widget in c# code is normal view controller, but implements `INCWidgetProviding` interface.
Also
```
[Export("widgetPerformUpdateWithCompletionHandler:")]
public void WidgetPerformUpdate(Action<NCUpdateResult> completionHandler)
```
needs to be implemented.

**Comment by dalexsoto** [comment] 2020-11-25 16:39
Hello @schovan could you upload a small test case that reproduces the issue you are seeing? This will help us to diagnose it. I hope that apple did not unify their widgets with the way the iOS ones work because as @tj-devel709 pointed out we currently do not support those.

Thanks.

**Comment by schovan** [comment] 2020-11-26 09:31
Hello @dalexsoto @tj-devel709,

I created a simple Visual Studio project, that contains a widget:

[TestApp.zip](https://github.com/xamarin/xamarin-macios/files/5601774/TestApp.zip)

It is nothing special, I just used templates from Visual Studio - Cocoa App and Today Extension Project.
This project displays the widget in macOS Mojave, but in macOS Big Sur, the widget is not displayed.
This is how it looks in macOS Mojave:
 
![Screenshot 2020-11-26 at 09 50 39](https://user-images.githubusercontent.com/16373322/100333108-7c4d2400-2fd2-11eb-9b32-a12a84407a58.png)

**Comment by JeroenBer** [comment] 2021-01-03 16:39
Hi, we have the same problem you are talking about Widgets but what you actually mean is Today Extensions. This is something different. Today extensions have been there for a long time in macOS. The newest macOS big sur now also supports widgets. 

So what you are saying is that today extensions are no longer working and that's a duplicate of our bug: https://github.com/xamarin/xamarin-macios/issues/10324

Please it's important to solve since this existing functionality has gone for our customers.

**Comment by spouliot** [comment] 2021-01-11 16:15
> Version: 7.0.0.15 (Visual Studio Community)

Closing as dupe of #10324 since that XM version is known not to include the `PlugIns` directory inside the `.app`

**Closed by spouliot** 2021-01-11 16:15 UTC
Labels: bug, macOS
