### ISSUE TITLE
Native iOS Debugging not working

### ISSUE THREAD

**Issue by arivoir** [xamarin/xamarin-macios#20813] opened 2024-07-03 21:18 UTC
I'm trying to run a native iOS application in VSCode, where the .Net Maui extension is installed.

I can open the project correctly and see the "Solution Explorer" and build the solution, but when I try to debug it I get the following error

> /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1215,3): error : Failed to AOT compile Microsoft.Maui.Controls.HotReload.Forms.dll, the AOT compiler exited with code 139. [/Users/alvarorivoir/C1/c1-netcore/iOS/Samples/Grid/FlexGridExplorer/FlexGridExplorer.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1215,3): error : Failed to AOT compile aot-instances.dll, the AOT compiler exited with code 139. [/Users/alvarorivoir/C1/c1-netcore/iOS/Samples/Grid/FlexGridExplorer/FlexGridExplorer.csproj]
    192 Warning(s)
    2 Error(s)

I don't have a repro sample

### Environment

The executed command is

`dotnet build -t:Build -p:Configuration=Debug -r iossimulator-arm64 -p:CustomAfterMicrosoftCSharpTargets="/Users/alvarorivoir/.vscode/extensions/ms-dotnettools.dotnet-maui-1.0.6-darwin-arm64/dist/resources/Custom.After.Microsoft.CSharp.targets" -p:MauiVSCodeBuildOutputFile="/var/folders/3f/vk4zy7vd6xz0ldvm5mygs22c0000gn/T/dotnet-maui/maui-vsc-1b98e481-c196-4a24-a55f-4261dd7a8a58.json" -p:XamlTools="/Users/alvarorivoir/.vscode/extensions/ms-dotnettools.csharp-2.34.12-darwin-arm64/.xamlTools" /Users/alvarorivoir/C1/c1-netcore/iOS/Samples/Grid/FlexGridExplorer/FlexGridExplorer.csproj`

`dotnet --version  8.0.302`

**Comment by rolfbjarne** [comment] 2024-07-04 11:04
This is a duplicate of https://github.com/microsoft/vscode-dotnettools/issues/1237.

The workaround is to enable the interpreter:

```xml
<PropertyGroup>
    <UseInterpreter>true</UseInterpreter>
</PropertyGroup>
```

Alternatively you can disable Hot Reload in VSCode.

**Closed by rolfbjarne** 2024-07-04 11:04 UTC
