### ISSUE TITLE
Deadlock in Xamarin.Mac

### ISSUE THREAD

**Issue by rrrado** [xamarin/xamarin-macios#5120] opened 2018-11-12 19:23 UTC
### Steps to Reproduce

problem occurs when my application (Xamarin.Mac) runs for a longer time. It is just periodically connecting to local HTTP server and updates the UI if needed. I start it from VS in debugger and I keep it running. When I check it after half day the debugger is disconnected with no message and application window is frozen. VS cannot attach to the application anymore, but I can attach in Xcode.

### Expected Behavior

application should stay responsive

### Actual Behavior

application halts in deadlock.
Sample callstacks:
[https://justpaste.it/2srvx](https://justpaste.it/2srvx)
[https://justpaste.it/6nuv3](https://justpaste.it/6nuv3)

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.6.9 (build 22)
Installation UUID: 1a82bda2-8f63-4499-be55-ab2d64a54dcc
Runtime:
	Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000309

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
	2.0.3
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
	2.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Not Installed

=== Apple Developer Tools ===

Xcode 10.0 (14320.25)
Build 10A255

=== Xamarin.Mac ===

Version: 5.0.0.0 (Visual Studio Community)
Hash: b40230c0
Branch: 
Build date: 2018-09-27 11:41:37-0400

=== Xamarin.iOS ===

Xamarin.iOS not installed.
Can't find mtouch or the Version file at /Library/Frameworks/Xamarin.iOS.framework/Versions/Current.

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706090022
Git revision: 0a0ba3c4593e9adb1c6ff6324e641036146af376
Build date: 2018-10-05 16:38:51+00
Build branch: release-7.6
Xamarin extensions: f7856b13f2c03a58e08381d3a5970bba18f5c7d7

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Team Foundation Version Control for TFS and Azure DevOps 0.4.3.1
```

### Example Project (If Possible)
Unfortunately I don't have simple project

**Comment by lewurm** [comment] 2018-11-12 22:37
looks like a deadlock in the runtime debugger. could you do `bt all` in lldb and post the output here?

**Comment by rrrado** [comment] 2018-11-13 16:05
I've started the application yesterday and it still works so I'll do it when it will hang again.

**Comment by VincentDondain** [comment] 2018-12-13 18:34
Hi,

I'll close this issue given that it seems you couldn't reproduce it and provide the information requested by Bernhard but feel free to reopen this issue once you're able to and we'll take a look.

Thanks.

**Closed by VincentDondain** 2018-12-13 18:34 UTC
Labels: macOS, need-info
