### ISSUE TITLE
[watchOS]WatchOS app fails to deploy on device

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#5020] opened 2018-10-19 21:15 UTC
### Steps to Reproduce

1. Update System to Xamarin.iOS, Version: 12.2.1.9 (Visual Studio Enterprise)
Hash: 6284095 or Xcode10.1 Version: 12.1.0.14 (Visual Studio Community)
Hash: 3cf004f
2. Build and deploy a watchOS app on device
3. Tested on an iPhone6Plus (12.1) + watch series 4 (5.0) device

### Expected Behavior
App deploys and launches successfully

### Actual Behavior
App fails to deploy on device with an error, IncorrectArchitecture: Failed to find matching arch for 32-bit Mach-O input file /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.917qLz/extracted/testioswatchtestwatchkit.app/PlugIns/testioswatchtestwatchkitExtension.appex/testioswatchtestwatchkitExtension

I tested with Xcode10.1 Version: 12.1.0.14 (Visual Studio Community)
Hash: 3cf004f8 and d15-9 (Version: 12.2.1.9 (Visual Studio Enterprise)
Hash: 62840955) builds and both gave the same result. I checked with  a watchOS app from Xcode10.1 beta 3 on the same device combination and app got deployed without any issues and launched

### Environment

```
Gouri Kumari [5:10 PM]
=== Visual Studio Community 2017 for Mac ===

Version 7.6.10 (build 21)
Installation UUID: 519fc1da-445a-45d9-9748-27fa26180fd4
Runtime:
    Mono 5.12.0.311 (2018-02/d01276bb36f) (64-bit)
    GTK+ 2.24.23 (Raleigh theme)
    Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

    Package version: 512000311

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
    2.1.2
    2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
    2.1.302
    2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 10.1 (14460.43.1)
Build 10O45e

=== Xamarin.Mac ===

Version: 5.1.0.11 (Visual Studio Community)
Hash: 3cf004f8
Branch:
Build date: 2018-10-17 16:06:20-0400

=== Xamarin.iOS ===

Version: 12.1.0.14 (Visual Studio Community)
Hash: 3cf004f8
Branch: xcode10.1
Build date: 2018-10-17 16:06:19-0400

=== Xamarin.Android ===

Not Installed

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706100021
Git revision: 803d947529b9ae3169543d7049b4114bce1dbe38
Build date: 2018-10-18 18:17:05+00
Build branch: release-7.6-xcode10.1
Xamarin extensions: 3a9afc960ba73e5862829e8a0cd9369bcca43d70

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
   Thu Jun 21 22:53:14 PDT 2018
   root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Android Designer 4.15.1.1
Xamarin Designer 4.15.1.1
Forms Previewer 4.15.1.1
iOS Designer 4.15.1.1
```

### Build Logs

Build Log: https://gist.github.com/GouriKumari/3e6941a08c849678dfd5f5e00393683d
Application Output: https://gist.github.com/GouriKumari/e10de771690e484e3e6afe99f35cc859

### Example Project (If Possible)

Tested with a new watchOS template project.

**Comment by rolfbjarne** [comment] 2018-10-22 05:56
This is a duplicate of #4864.

**Closed by rolfbjarne** 2018-10-22 05:56 UTC
