### ISSUE TITLE
error signing Entitlements.xcent when publishing app on physical iphone

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#14698] opened 2022-04-07 16:19 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/error-signing-Entitlementsxcent-when-pu/10003141)._

---
[severity:It's more difficult to complete my work]
After doing the whole process of generating a free profile in Xcode and testing it on the physical device. When doing the process through Visual Studio 2022 Preview it is giving the following error when signing: "Entitlements.xcent: cannot read entitlement data intlog.iOS"

The file he is trying to sign:

```




application-identifier
3ND3HSYPB5.intlog.intlog
get-task-allow

com.apple.developer.team-identifier
3ND3HSYPB5
keychain-access-groups

3ND3HSYPB5.intlog.intlog



```

Error by log:

```
1>  intlog.iOS -> E:\Documentos\Visual Studio 2022\Projects\intlog\intlog\intlog.iOS\bin\iPhone\Debug\intlog.iOS.exe
1>  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/lucas/Library/Caches/Xamarin/mtbs/builds/intlog.iOS/d3a261e106c6bab65946eef8af07909b534271aaf5acc5ec5020552e78deecc2/obj/iPhone/Debug/device-builds/iphone11.8-15.4/response-file.rsp 
1>F:\Visual Studio 2021\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(238,3): warning : warning: '/Users/lucas/Library/Caches/Xamarin/mtbs/builds/intlog.iOS/d3a261e106c6bab65946eef8af07909b534271aaf5acc5ec5020552e78deecc2/obj/iPhone/Debug/device-builds/iphone11.8-15.4/mtouch-cache/arm64/Xamarin.iOS.dll.o' was built with class_ro_t pointer signing enabled, but previous .o files were not
1>  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -num-threads 4 -z -o bin/iPhone/Debug/device-builds/iphone11.8-15.4/intlog.iOS.app.dSYM bin/iPhone/Debug/device-builds/iphone11.8-15.4/intlog.iOS.app/intlog.iOS 
1>F:\Visual Studio 2021\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(2419,3): warning : warning: ignoring unknown option: -z
1>  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -i -s obj/iPhone/Debug/device-builds/iphone11.8-15.4/mtouch-symbols.list bin/iPhone/Debug/device-builds/iphone11.8-15.4/intlog.iOS.app/intlog.iOS 
1>  /usr/bin/mdimport bin/iPhone/Debug/device-builds/iphone11.8-15.4/intlog.iOS.app/../ 
1>  Tool /usr/bin/codesign execution finished (exit code = 1).
1>          
1>  /Users/lucas/Library/Caches/Xamarin/mtbs/builds/intlog.iOS/d3a261e106c6bab65946eef8af07909b534271aaf5acc5ec5020552e78deecc2/obj\iPhone\Debug\device-builds\iphone11.8-15.4\Entitlements.xcent: cannot read entitlement data
1>  
1>F:\Visual Studio 2021\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(2068,3): error : /usr/bin/codesign exited with code 1
1>F:\Visual Studio 2021\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(2068,3): error :         
1>F:\Visual Studio 2021\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(2068,3): error : Failed to codesign '/Users/lucas/Library/Caches/Xamarin/mtbs/builds/intlog.iOS/d3a261e106c6bab65946eef8af07909b534271aaf5acc5ec5020552e78deecc2/bin/iPhone/Debug/device-builds/iphone11.8-15.4/intlog.iOS.app': /Users/lucas/Library/Caches/Xamarin/mtbs/builds/intlog.iOS/d3a261e106c6bab65946eef8af07909b534271aaf5acc5ec5020552e78deecc2/obj\iPhone\Debug\device-builds\iphone11.8-15.4\Entitlements.xcent: cannot read entitlement data
1>F:\Visual Studio 2021\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(2068,3): error : 
1>F:\Visual Studio 2021\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(2068,3): error :
```
     
**This same process works normally in Visual Studio 2019**

---
#### Feedback Bot on 4/2/2022, 04:33 AM: 

(private comment, text removed)
#### Feedback Bot on 4/2/2022, 08:48 AM: 

(private comment, text removed)
#### lucas Vor on 4/2/2022, 09:02 PM: 

(private comment, text removed)
#### Roi Chen -MSFT [MSFT] on 4/7/2022, 08:37 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by chamons** [comment] 2022-04-28 21:00
Does the file `Users/lucas/Library/Caches/Xamarin/mtbs/builds/intlog.iOS/d3a261e106c6bab65946eef8af07909b534271aaf5acc5ec5020552e78deecc2/obj\iPhone\Debug\device-builds\iphone11.8-15.4\Entitlements.xcent` exist on your build agent?

**Comment by rolfbjarne** [comment] 2022-04-29 07:23
This is probably a duplicate of https://github.com/xamarin/xamarin-macios/pull/14365, which has been fixed (and released) already.

**Closed** 2022-05-06 08:00 UTC
Labels: need-info
