### ISSUE TITLE
[Mac] With .net 8 RC1 VS builds the app, but won't start it

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#19189] opened 2023-10-12 16:26 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Mac-With-net-8-RC1-VS-builds-the-app/10481368)._

---
**Context:**  
OSX Ventura  
Mac with M2 Processor  
VS 2022 for Mac  
.Net 8 RC1

**What happend:**  
When starting debugging an app the app will be builded, but a popup stated it isn’t builded and stops the process.

**How To:**  
Generate a new Maui app using .Net 8  
and simply try to debug it.

---
#### Feedback Bot on 10/1/2023, 08:18 PM: 

(private comment, text removed)
#### Samantha Houts [MSFT] on 10/9/2023, 08:47 AM: 

(private comment, text removed)
#### Michael Engelmann on 10/9/2023, 00:09 PM: 

(private comment, text removed)
#### Michael Engelmann on 10/11/2023, 04:10 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ZeProgFactory** [comment] 2023-10-12 17:19
Same issue with Maui .Net 8 RC2

**Comment by cburns-pw** [comment] 2023-10-12 17:29
Might have something to do with this: https://github.com/xamarin/xamarin-macios/pull/19159

**Comment by ZeProgFactory** [comment] 2023-10-13 14:01
The issue is on Mac with `Apple M2` chip.

**Does this happen in the simulator or on device (or both)?**
Device --> we are on physical Macs

**If on device, which iOS version does the device have?**
macOS Venture 13.6

**Can you screenshot the exact error?**
<img width="1582" alt="image" src="https://github.com/xamarin/xamarin-macios/assets/17034030/7db420c4-2f22-41d2-85a9-0b01b1d4f555">

[Build.log](https://github.com/xamarin/xamarin-macios/files/12894296/Build.log)

**Comment by rolfbjarne** [comment] 2023-10-13 16:50
* Do any of the other platforms (iOS, Android) work as expected?
* Can you change/set the runtime identifier in the csproj and see if that makes a difference?

```xml
<PropertyGroup>
     <RuntimeIdentifier>maccatalyst-x64</RuntimeIdentifier>
</PropertyGroup>
```

**Comment by ZeProgFactory** [comment] 2023-10-13 21:04
> * Do any of the other platforms (iOS, Android) work as expected?
> * Can you change/set the runtime identifier in the csproj and see if that makes a difference?
> 
> ```
> <PropertyGroup>
>      <RuntimeIdentifier>maccatalyst-x64</RuntimeIdentifier>
> </PropertyGroup>
> ```

The were no issues building on PC for PC, nor for Android on Mac.

Setting the RuntimeIdentifier solves the issue on Mac, but on the other side, now there where build errors on PC.

**Comment by rolfbjarne** [comment] 2023-10-16 06:47
Ok, that means this is likely a problem in the IDE, so I've reopened the feedback ticket (and I'm closing this one).

Note that it may take a while to get this fixed in the IDE (if ever): https://devblogs.microsoft.com/visualstudio/visual-studio-for-mac-retirement-announcement/

> > * Do any of the other platforms (iOS, Android) work as expected?
> > * Can you change/set the runtime identifier in the csproj and see if that makes a difference?
> > 
> > ```
> > <PropertyGroup>
> >      <RuntimeIdentifier>maccatalyst-x64</RuntimeIdentifier>
> > </PropertyGroup>
> > ```
> 
> The were no issues building on PC for PC, nor for Android on Mac.
> 
> Setting the RuntimeIdentifier solves the issue on Mac, but on the other side, now there where build errors on PC.

This was only meant as a diagnostic idea, not as a workaround.

However, something like this should work on Windows too:

```xml
<PropertyGroup Condition="$(TargetFramework.EndsWith('-maccatalyst'))">
    <RuntimeIdentifier>maccatalyst-x64</RuntimeIdentifier>
</PropertyGroup>
```

and if you still want universal release builds, you can limit to Debug only:

```xml
<PropertyGroup Condition="$(TargetFramework.EndsWith('-maccatalyst')) And '$(Configuration)' == 'Debug'">
    <RuntimeIdentifier>maccatalyst-x64</RuntimeIdentifier>
</PropertyGroup>
```

**Closed by rolfbjarne** 2023-10-16 06:47 UTC
Labels: need-attention

**Comment by ZeProgFactory** [comment] 2023-10-17 01:49
> Ok, that means this is likely a problem in the IDE, so I've reopened the feedback ticket (and I'm closing this one).

@rolfbjarne could you please give the link. 
Thanks

**Comment by rolfbjarne** [comment] 2023-10-17 07:22
> > Ok, that means this is likely a problem in the IDE, so I've reopened the feedback ticket (and I'm closing this one).
> 
> @rolfbjarne could you please give the link. Thanks

https://developercommunity.visualstudio.com/t/Mac-With-net-8-RC1-VS-builds-the-app/10481368
