### ISSUE TITLE
App Crash on starting - iOS Binding library - DYLD: Symbol not found

### ISSUE THREAD

**Issue by rmarinho** [xamarin/xamarin-macios#18761] opened 2023-08-17 18:25 UTC
---
**Issue moved from dotnet/maui#16811**
- Please respond to @kapilntt.

---

_From @kapilntt on Thursday, August 17, 2023 6:58:00 AM_

### Description

I'm migrating an app from Xamarin.Form to .NET MAUI.  The Xamarin Forms app successfully uses a native iOS library (xcframework) with the help of bindings project.

With .net 7,
* The binding project compiles successfully
* The Maui iOS App compiles successfully

However upon launching the app on iPhone or in simulator, the app throws following error and Visual Studio shows the crash screen.
`xcrun simctl launch --stdout=/dev/ttys001 --stderr=/dev/ttys002 --terminate-running-process 6FB7B74B-4AE5-43C4-A1F4-67BA87255B9B com.companyname.appname.iOS2 -monodevelop-port 10000
com.companyname.appname.iOS2: 7307
dyld[7307]: Symbol not found: _$s21MobileAccess0B10CredentialP10sessionUrl10Foundation3URLVvgTj
Referenced from: <E9568E49-115C-3F9A-99A4-23446C80E534> /Library/Developer/CoreSimulator/Devices/6FB7B74B-4AE5-43C4-A1F4-67BA87255B9B/data/Containers/Bundle/Application/9BFB0F68-20E4-4176-BC7B-60DA6752F4FB/appname.iOS2.app/Frameworks/SdkProxy.framework/SdkProxy`

A similar issue was reported in the following ticket but it has been put into backlog with no timeframe for fixing.
 https://github.com/dotnet/maui/issues/13464 

### Steps to Reproduce

1. Create iOS binding library in Visual Studio for Mac 17.6.3 (build 421)
2. Add native references to xcframework files. Make sure Smark Link is ticked.
3. Add ApiDefinition and StructsAndEnums from old Xamarin project. 
4. Observe successful compilation
5. Go to the iOS app project and refer the binding DLL
6. Observe successful compilation
7. Run the app
8. Observe the crash

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

no

**Comment by rolfbjarne** [comment] 2023-08-18 14:22
@kapilntt could you please attach a test solution we can use to reproduce this in order to figure out what's going on?

**Comment by kapilntt** [comment] 2023-08-22 00:29
Hi @rolfbjarne , 
I have created a stripped version of the app that demonstrates reproduction of the issue. 
Is there a way to privately share the sample? 
Thanks,

**Comment by rolfbjarne** [comment] 2023-08-22 10:52
@kapilntt 

> Hi @rolfbjarne , I have created a stripped version of the app that demonstrates reproduction of the issue. Is there a way to privately share the sample? Thanks,

Yes, you can open a feedback ticket here:

* https://developercommunity.visualstudio.com/VisualStudioMac/report

and once the ticket is open, you can add private attachments.

Make sure to state that you're just adding private information to this issue in the feedback ticket (and post a link to the feedback ticket here), that way we can route it efficiently.

**Comment by kapilntt** [comment] 2023-08-24 01:12
Awesome. Here is the ticket: https://developercommunity.visualstudio.com/t/App-Crash-on-starting---iOS-Binding-libr/10448478

**Comment by rolfbjarne** [comment] 2023-08-24 17:56
I get a different error:

```
dyld[46580]: Symbol not found: _$s21GallagherMobileAccess0B10CredentialP10sessionUrl10Foundation3URLVvgTj
  Referenced from: <E9568E49-115C-3F9A-99A4-23446C80E534> /Users/rolf/Library/Developer/CoreSimulator/Devices/9B99FC8C-690B-4D6F-B223-F9E1ABC07362/data/Containers/Bundle/Application/D1F184A4-FE12-443A-8F01-C015240F5256/BugReportApp.iOS2.app/Frameworks/MobileConnectSdkProxy.framework/MobileConnectSdkProxy
  Expected in:     <C900AC28-F6D8-3379-8E1A-2A895B67EF05> /Users/rolf/Library/Developer/CoreSimulator/Devices/9B99FC8C-690B-4D6F-B223-F9E1ABC07362/data/Containers/Bundle/Application/D1F184A4-FE12-443A-8F01-C015240F5256/BugReportApp.iOS2.app/Frameworks/GallagherMobileAccess.framework/GallagherMobileAccess
```

and that's true enough, the MobileConnectSdkProxy library references the symbol `_$s21GallagherMobileAccess0B10CredentialP10sessionUrl10Foundation3URLVvgTj` from `GallagherMobileAccess`:

```
$ nm -m MobileConnectSdkProxy.xcframework/ios-arm64/MobileConnectSdkProxy.framework/MobileConnectSdkProxy
[...]
         (undefined) external _$s21GallagherMobileAccess0B10CredentialP10sessionUrl10Foundation3URLVvgTj (from GallagherMobileAccess)
```

and it's not there:

```
$ nm -m GallagherMobileAccess.xcframework/ios-arm64/GallagherMobileAccess.framework/GallagherMobileAccess | grep s21GallagherMobileAccess0B10CredentialP10sessionUrl10Foundation3URLVvgTj
[no output]
```

Could these libraries be out of sync somehow? Maybe a specific version of one library only works with a specific version of the other library?

**Comment by kapilntt** [comment] 2023-08-25 00:10
I am glad that you are able to observe the issue. 

The exact same xcframework binaries with the exact same versions built with older Xamarin binding project is compiling and running as expected. 

The difference I observe is, that the binary produced by the Xamarin binding project is 12MB vs the newer .net ones are 44kb only. To me, this indicates that it's not linked properly. 

In one of the other posts here, I read that earlier binding projects used to embed frameworks which are now not embedded for some architectural reasons.

**Comment by rolfbjarne** [comment] 2023-08-25 12:17
Can you attach a working test project for Xamarin.iOS so that I can compare? I can't see how this can work in the first place.

**Comment by kapilntt** [comment] 2023-09-03 23:22
Hi @rolfbjarne, I will create a sample using Xamarin.iOS and older binding library.

**Comment by rolfbjarne** [comment] 2023-09-05 06:23
> Hi @rolfbjarne, I will create a sample using Xamarin.iOS and older binding library.

Ok, I'll mark as need-info until then

**Comment by kapilntt** [comment] 2023-09-05 07:50
I have attached the working Xamarin binding project and the working Xamarin app project in the ticket here:
https://developercommunity.visualstudio.com/t/App-Crash-on-starting---iOS-Binding-libr/10448478?viewtype=all 

So far following has been provided:
* Nonworking Maui and binding project. It was possible to observe and reproduce the issue
* Working Xamarin app and binding project so a comparison can be made.

**Comment by rolfbjarne** [comment] 2023-09-05 09:21
If I try to build this project:

> BugReportXamarinWorking/BugReportXamarinWorking/BugReportXamarinWorking.iOS/BugReportXamarinWorking.iOS.csproj

it fails to build with:

```
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: AccessResult. The symbol '_OBJC_CLASS_$_AccessResult' could not be found in any of the libraries or frameworks linked with your application.
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: GallagherMobileAccessError. The symbol '_OBJC_CLASS_$_GallagherMobileAccessError' could not be found in any of the libraries or frameworks linked with your application.
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: MobileAccess. The symbol '_OBJC_CLASS_$_MobileAccess' could not be found in any of the libraries or frameworks linked with your application.
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: MobileAccessLocalization. The symbol '_OBJC_CLASS_$_MobileAccessLocalization' could not be found in any of the libraries or frameworks linked with your application.
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: MobileAccessProvider. The symbol '_OBJC_CLASS_$_MobileAccessProvider' could not be found in any of the libraries or frameworks linked with your application.
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: MobileCredential. The symbol '_OBJC_CLASS_$_MobileCredential' could not be found in any of the libraries or frameworks linked with your application.
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: Reader. The symbol '_OBJC_CLASS_$_Reader' could not be found in any of the libraries or frameworks linked with your application.
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: ReaderAttributes. The symbol '_OBJC_CLASS_$_ReaderAttributes' could not be found in any of the libraries or frameworks linked with your application.
  MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: TitleAndBody. The symbol '_OBJC_CLASS_$_TitleAndBody' could not be found in any of the libraries or frameworks linked with your application.
  MTOUCH : error MT5202: Native linking failed. Please review the build log.
  clang : error : linker command failed with exit code 1 (use -v to see invocation) 
```

This is because the xcframeworks are embedded in `MobileConnectSdk.iOS.Bindings.dll`, and we don't support embedded xcframeworks.

Building the binding project with `<NoBindingEmbedding>true</NoBindingEmbedding>`, and using the resulting `MobileConnectSdk.iOS.Bindings.dll` and `MobileConnectSdk.iOS.Bindings.resources` binding output in the project above results in the same runtime error as for the .NET project.

Can you provide a [binlog](https://aka.ms/binlog) from your successful Xamarin build?

**Comment by kapilntt** [comment] 2023-09-13 00:34
Hi,

While I get the logs, can you please suggest how it supposed to be? 
If the new way is not to embed, are we meant to copy files and frameworks in the iOS project? So instead of binding project doing the linking, iOS project would do. Is that how it supposed to be?

**Comment by rolfbjarne** [comment] 2023-09-13 10:20
> Hi,
> 
> While I get the logs, can you please suggest how it supposed to be? If the new way is not to embed, are we meant to copy files and frameworks in the iOS project?

There are three main ways:

* Create a NuGet from the binding project and reference that (`dotnet pack` can be used to create a NuGet).
* Reference the binding project from your main project. In this case we'll pick up the framework from the binding project automatically.
* Reference the binding project's assembly from the main project. In this case, if you've copied the binding assembly from the bin directory to some other place, you must also copy the *.resources directory from the bin directory so that it stays together with the binding assembly.

> So instead of binding project doing the linking, iOS project would do. Is that how it supposed to be?

It's always been the iOS project who does the linking. What's changed is where the native libraries/frameworks are (before: inside the binding assembly as a resource, now: next to the binding assembly inside a separate *.resources directory)

**Comment by kapilntt** [comment] 2023-10-10 06:49
Hi @rolfbjarne , 

On Mac, the command line "dotnet build -bl" is failing on Xamarin project as it is trying to build against .net 7. Is there a way to capture Visual Studio for Mac build output as a binary buildlog? 

While investigating this further, I noticed that the Xamarin project where bindings are working as expected, the Xamarin iOS project also has Native references to both the frameworks. After observing that, I tried adding native references to Maui iOS project but those references do not appear in the project tree and "Symbol not found" error still causes the app to crash on starting.

**Comment by rolfbjarne** [comment] 2023-10-12 12:46
> On Mac, the command line "dotnet build -bl" is failing on Xamarin project as it is trying to build against .net 7.

I'm confused, isn't .NET 7 what you're trying to use?

> Is there a way to capture Visual Studio for Mac build output as a binary buildlog?

Yes: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs

**Comment by kapilntt** [comment] 2023-10-13 01:25
Thanks for reopening...

Here is a quick summary 
- Maui Forms app created with .net 7 is crashing with "DYLD: Symbol not found" while using the binding library created with .net 7
- The sample of Maui Forms app and the latest binding library has been provided [here] (https://developercommunity.visualstudio.com/t/App-Crash-on-starting---iOS-Binding-libr/10448478) to observe the issue.
- The exact same native libraries used with the Xamarin binding project and Xamarin Forms app do work in the current production release.
- A sample of working Xamarin Forms and Xamarin binding library was provided but the Xamarin app encountered the same "Symbol not found" [here](https://github.com/xamarin/xamarin-macios/issues/18761#issuecomment-1706254633) even after adding <NoBindingEmbedding>true</NoBindingEmbedding>.
- The last request was to provide a binary build log from the Xamarin working project from my machine and that is the one I couldn't provide because the command line "dotnet build -bl" on the mac machine is trying to use .net 7 against the Xamarin project and not respecting the .net standard 2.1 as per project/solution configuration. 

The issue is pretty clear that the .net 7 builds are not able to link the external libraries (xcframework). 
So far I have tried the following two things:
1. Adding DLL as a reference and keeping *.resources folders next to it
2. Referencing binding project in the Maui Forms app.

One observation I made in the [last post ](https://github.com/xamarin/xamarin-macios/issues/18761#issuecomment-1754519824) that Xamarin Forms project (working production app) also has "Native References" to those two xcframewroks. In MAUI project, I was not able to add the same references by editing the csproj file.

Since the Maui app and binding projects are provided [here] (https://developercommunity.visualstudio.com/t/App-Crash-on-starting---iOS-Binding-libr/10448478), would you be able to suggest how can I reference native frameworks to get them linked?

**Comment by rolfbjarne** [comment] 2023-10-17 12:42
> * The last request was to provide a binary build log from the Xamarin working project from my machine and that is the one I couldn't provide because the command line "dotnet build -bl" on the mac machine is trying to use .net 7

Ah, my bad, you have to use "msbuild" instead of "dotnet build" to build a Xamarin project. Can you try that and see if you can get that to work?

**Comment by kapilntt** [comment] 2023-10-18 05:32
Hi @rolfbjarne ,

I have attached the biglog here:https://developercommunity.visualstudio.com/t/App-Crash-on-starting---iOS-Binding-libr/10494191 

Thanks,

**Comment by rolfbjarne** [comment] 2023-10-18 07:05
OK, I see how your legacy Xamarin.iOS project compiles, you have two NativeReference items to the xcframeworks in the executable project, that works around the fact that the embedded xcframeworks in the binding project don't work.

However, it doesn't explain why the Xamarin.iOS project works for you, because I get this error at runtime with the Xamarin.iOS project:

```
dyld[46580]: Symbol not found: _$s21GallagherMobileAccess0B10CredentialP10sessionUrl10Foundation3URLVvgTj
  Referenced from: <E9568E49-115C-3F9A-99A4-23446C80E534> /Users/rolf/Library/Developer/CoreSimulator/Devices/9B99FC8C-690B-4D6F-B223-F9E1ABC07362/data/Containers/Bundle/Application/D1F184A4-FE12-443A-8F01-C015240F5256/BugReportApp.iOS2.app/Frameworks/MobileConnectSdkProxy.framework/MobileConnectSdkProxy
  Expected in:     <C900AC28-F6D8-3379-8E1A-2A895B67EF05> /Users/rolf/Library/Developer/CoreSimulator/Devices/9B99FC8C-690B-4D6F-B223-F9E1ABC07362/data/Containers/Bundle/Application/D1F184A4-FE12-443A-8F01-C015240F5256/BugReportApp.iOS2.app/Frameworks/GallagherMobileAccess.framework/GallagherMobileAccess
```

Can you attach the .ipa you uploaded to Apple so that I can inspect it and compare it to what I get when I build locally?

**Comment by kapilntt** [comment] 2023-10-18 07:29
HI @rolfbjarne ,
Thanks for a quick response. I have uploaded the ipa to following ticket. 
https://developercommunity.visualstudio.com/t/App-Crash-on-starting---iOS-Binding-libr/10494191#TPIN-N10494245
To download the file you would need to click "Show Reaction" and find it in the attachment. 

Thanks,

**Comment by rolfbjarne** [comment] 2023-10-18 07:51
The difference is that the GallagherMobileAccess framework in the ipa has a different version.

The IPA: 

```
$  /usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' Frameworks/GallagherMobileAccess.framework/Info.plist
15.04.033
```

The test projects:

```
$ /usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' GallagherMobileAccess.xcframework/ios-arm64/GallagherMobileAccess.framework/Info.plist
15.05.026
```

Please try the .NET project again with the same version of the GallagherMobileAccess framework and see if that works. If not, please update the test project and attach the updated version.

**Comment by kapilntt** [comment] 2023-10-23 05:08
To leave any doubts out, I will create another set of test projects and upload them.

**Comment by rolfbjarne** [comment] 2023-10-23 07:38
OK, marking as need-info until then.

**Closed** 2023-10-31 00:40 UTC
Labels: need-info

**Comment by kapilntt** [comment] 2023-10-31 00:45
.

**Comment by kapilntt** [comment] 2023-10-31 00:51
Hi,

The requested *Working* Xamarin project has been uploaded on the following location:
https://developercommunity.visualstudio.com/t/App-Crash-on-starting---iOS-Binding-libr/10494191

The Xamarin.iOS app project setup is as follows:
* The binding library is referenced as DLL
* The frameworks referenced in Binding project are also referenced in Xamarin.iOS project as Native Reference

**Comment by kapilntt** [comment] 2023-10-31 02:06
After updating Visual Studio for Mac and updating the .net workloads, the MAUI app not crashing anymore. Magic!

Sorry community, I don't have any learnings on what caused the crash and how it is now fixed!

**Comment by kapilntt** [comment] 2023-10-31 02:51
Too early to post the above comment. The issue is fixed in .net 7 ios app but Maui Forms app is still crashing. Need to create another bug report app.
