### ISSUE TITLE
SignalR on ios - missing method exceptions

### ISSUE THREAD

**Issue by BrennanConroy** [xamarin/xamarin-macios#10592] opened 2021-02-08 22:51 UTC
---
**Issue moved from dotnet/aspnetcore#29762**
- Please respond to @freever.

---

_From @freever on Friday, January 29, 2021 1:47:17 PM_

Hi,

I am battling to get SignalR client v5 working on iOS. 

* First off, I get the following exception when trying to connect:

> Method not found: Microsoft.AspNetCore.Http.Connections.NegotiationResponse Microsoft.AspNetCore.Http.Connections.NegotiateProtocol.ParseResponse(System.ReadOnlySpan`1<byte>)

>  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471 
  at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync (System.Uri url, System.Net.Http.HttpClient httpClient, Microsoft.Extensions.Logging.ILogger logger, System.Threading.CancellationToken cancellationToken) [0x0003d] in <bb806567921d4ab0bec56c94fba28201>:0 
  at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync (System.Uri uri, System.Threading.CancellationToken cancellationToken) [0x00011] in <bb806567921d4ab0bec56c94fba28201>:0 
  at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport (Microsoft.AspNetCore.Connections.TransferFormat transferFormat, System.Threading.CancellationToken cancellationToken) [0x00180] in <bb806567921d4ab0bec56c94fba28201>:0 
  at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore (Microsoft.AspNetCore.Connections.TransferFormat transferFormat, System.Threading.CancellationToken cancellationToken) [0x00127] in <bb806567921d4ab0bec56c94fba28201>:0 
  at System.Threading.Tasks.ForceAsyncAwaiter.GetResult () [0x0000c] in <bb806567921d4ab0bec56c94fba28201>:0 
  at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync (Microsoft.AspNetCore.Connections.TransferFormat transferFormat, System.Threading.CancellationToken cancellationToken) [0x00091] in <bb806567921d4ab0bec56c94fba28201>:0 
  at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync (System.Net.EndPoint endPoint, System.Threading.CancellationToken cancellationToken) [0x00114] in <bb806567921d4ab0bec56c94fba28201>:0 
  at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync (System.Net.EndPoint endPoint, System.Threading.CancellationToken cancellationToken) [0x001bf] in <bb806567921d4ab0bec56c94fba28201>:0 
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () [0x0001b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs:813 
  at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore (System.Threading.CancellationToken cancellationToken) [0x000a5] in <6aa45f4976694480a4c916587efde4db>:0 
  at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner (System.Threading.CancellationToken cancellationToken) [0x001a4] in <6aa45f4976694480a4c916587efde4db>:0 
  at System.Threading.Tasks.ForceAsyncAwaiter.GetResult () [0x0000c] in <6aa45f4976694480a4c916587efde4db>:0 
  at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync (System.Threading.CancellationToken cancellationToken) [0x00091] in <6aa45f4976694480a4c916587efde4db>:0 
  at Blauhaus.SignalR.Client.SignalRConnectionProxy.ConnectAsync () [0x0002e] in C:\Code\Blauhaus\Blauhaus.SignalR\src\Blauhaus.SignalR.Client\SignalRConnectionProxy.cs:57 
  at Blauhaus.SignalR.Client.SignalRConnectionProxy.InvokeAsync[TDto] (System.String methodName, System.Object parameter1, System.Object parameter2) [0x00087] in C:\Code\Blauhaus\Blauhaus.SignalR\src\Blauhaus.SignalR.Client\SignalRConnectionProxy.cs:75 
  at Blauhaus.SignalR.Client.SignalRClient`1[TDto].HandleCommandAsync[TCommand] (TCommand command) [0x0014a] in C:\Code\Blauhaus\Blauhaus.SignalR\src\Blauhaus.SignalR.Client\SignalRClient.cs:52 

* Secondly, if I add System.Text.Json directly to the iOS project as suggested elsewhere on the interwebs, I get a new problem:

> {System.TypeInitializationException: The type initializer for 'Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol' threw an exception. ---> System.MissingMethodException: Method not found: int System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<byte>)
  at System.Text.Json.JsonEncodedText.EncodeHelper (System.ReadOnlySpan`1[T] utf8Value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00000] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
  at System.Text.Json.JsonEncodedText.TranscodeAndEncode (System.ReadOnlySpan`1[T] value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00033] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
  at System.Text.Json.JsonEncodedText.Encode (System.ReadOnlySpan`1[T] value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00014] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
  at System.Text.Json.JsonEncodedText.Encode (System.String value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00014] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
  at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol..cctor () [0x00000] in <1c8fd512c0974021b9b175f863d5c3ce>:0 
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:936 
--- End of stack trace from previous location where exception was thrown ---

* Finally if I try to bypass System.Text.Json by using AddNewtonsoftJsonProtocol() instead of System.Text.Json I get the following

> Method not found: Microsoft.AspNetCore.Http.Connections.NegotiationResponse Microsoft.AspNetCore.Http.Connections.NegotiateProtocol.ParseResponse(System.ReadOnlySpan`1<byte>)
>  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471 
  at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync (System.Uri url, System.Net.Http.HttpClient httpClient, Microsoft.Extensions.Logging.ILogger logger, System.Threading.CancellationToken cancellationToken) [0x0003d] in <bb806567921d4ab0bec56c94fba28201>:0 
  at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync (System.Uri uri, System.Threading.CancellationToken cancellationToken) [0x00011] in <bb806567921d4ab0bec56c94fba28201>:0 
  at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport (Microsoft.AspNetCore.Connections.TransferFormat transferFormat, System.Threading.CancellationToken cancellationToken) [0x00180] in <bb806567921d4ab0bec56c94fba28201>:0 
  at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore (Microsoft.AspNetCore.Connections.TransferFormat transferFormat, System.Threading.CancellationToken cancellationToken) [0x00127] in <bb806567921d4ab0bec56c94fba28201>:0 
  at System.Threading.Tasks.ForceAsyncAwaiter.GetResult () [0x0000c] in <bb806567921d4ab0bec56c94fba28201>:0 
  at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync (Microsoft.AspNetCore.Connections.TransferFormat transferFormat, System.Threading.CancellationToken cancellationToken) [0x00091] in <bb806567921d4ab0bec56c94fba28201>:0 
  at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync (System.Net.EndPoint endPoint, System.Threading.CancellationToken cancellationToken) [0x00114] in <bb806567921d4ab0bec56c94fba28201>:0 
  at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync (System.Net.EndPoint endPoint, System.Threading.CancellationToken cancellationToken) [0x001bf] in <bb806567921d4ab0bec56c94fba28201>:0 
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () [0x0001b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs:813 
  at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore (System.Threading.CancellationToken cancellationToken) [0x000a5] in <6aa45f4976694480a4c916587efde4db>:0 
  at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner (System.Threading.CancellationToken cancellationToken) [0x001a4] in <6aa45f4976694480a4c916587efde4db>:0 
  at System.Threading.Tasks.ForceAsyncAwaiter.GetResult () [0x0000c] in <6aa45f4976694480a4c916587efde4db>:0 
  at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync (System.Threading.CancellationToken cancellationToken) [0x00091] in <6aa45f4976694480a4c916587efde4db>:0 
  at MineGame.App.ViewModels.ViewModels.Account.StartupViewModel+<>c.<.ctor>b__0_0 () [0x00062] in C:\Code\MineGame Code\MineGame.Client\src\MineGame.Client.App\MineGame.App.ViewModels\ViewModels\Account\StartupViewModel.cs:43 

Are there any other options I can try, or can anyone suggest a remedy?

**Comment by BrennanConroy** [comment] 2021-02-08 22:51
---
**Issue moved from dotnet/aspnetcore#29762**
- Please respond to @BrennanConroy.

---

_From @BrennanConroy on Friday, January 29, 2021 5:48:09 PM_

Have you looked into using an rd.xml file to make sure methods aren't trimmed? https://docs.microsoft.com/dotnet/framework/net-native/runtime-directives-rd-xml-configuration-file-reference

A quick test would be to try disabling the linker when building and seeing if the app works. https://docs.microsoft.com/xamarin/ios/deploy-test/linker?tabs=windows

**Comment by BrennanConroy** [comment] 2021-02-08 22:51
---
**Issue moved from dotnet/aspnetcore#29762**
- Please respond to @freever.

---

_From @freever on Saturday, January 30, 2021 7:15:00 AM_

Hi @BrennanConroy thanks for your response. That was my first thought too, but my linker is still set to "Don't Link". 

![image](https://user-images.githubusercontent.com/2269624/106350041-88f43e00-62db-11eb-8355-2abed63eaf51.png)

**Comment by BrennanConroy** [comment] 2021-02-08 22:51
---
**Issue moved from dotnet/aspnetcore#29762**
- Please respond to @freever.

---

_From @freever on Sunday, January 31, 2021 7:22:08 AM_

I have been using Version 16.9.0 Preview 3.0 on Windows. When I switch back to Version 16.8.4, the problem disappears, so it appears to be a Xamarin.iOS version issue perhaps? 

Here is the config that works:
[works.txt](https://github.com/dotnet/aspnetcore/files/5899316/works.txt)

And the config that doesn't:
[works_no.txt](https://github.com/dotnet/aspnetcore/files/5899317/works_no.txt)

**Comment by BrennanConroy** [comment] 2021-02-08 22:51
---
**Issue moved from dotnet/aspnetcore#29762**
- Please respond to @BrennanConroy.

---

_From @BrennanConroy on Monday, February 1, 2021 10:08:43 PM_

@Clancey is there any known changes with linking between Xamarin iOS in VS 16.8.4 and 16.9.0 that could causes the above issues?

**Comment by BrennanConroy** [comment] 2021-02-08 22:51
---
**Issue moved from dotnet/aspnetcore#29762**
- Please respond to @Clancey.

---

_From @Clancey on Monday, February 1, 2021 11:24:35 PM_

@dalexsoto Do you have any thoughts?

**Comment by BrennanConroy** [comment] 2021-02-08 22:51
---
**Issue moved from dotnet/aspnetcore#29762**
- Please respond to @BrennanConroy.

---

_From @BrennanConroy on Wednesday, February 3, 2021 9:02:29 PM_

Is there a repo we can move this issue to?

**Comment by dalexsoto** [comment] 2021-02-09 02:11
This is a dupe of #10548

**Closed by dalexsoto** 2021-02-09 02:11 UTC

**Comment by ssbssb-cmd** [comment] 2021-03-10 11:57
Hi what was the resolution / fix? I'm linking through the duple issues but its not clear to me how this has been fixed. I'm currently blocked on releases so would really appreciate some help / guidance on how this can be fixed. I've tried setting the System.Memory (4.5.4) and System.Buffers (4.5.1) in the package references as described in one of the other threads but still getting the same problem.

I've tried switching to Newtonsoft provider and then on connect get a different error (System.MissingMethodException: Method not found: Microsoft.AspNetCore.Http.Connections.NegotiationResponse) which again I can't find how to resolve

**Comment by freever** [comment] 2021-03-10 12:05
@ssbssb-cmd I ended up removing all traces of System.Text.Json references from all my projects and then it started working.

**Comment by ssbssb-cmd** [comment] 2021-03-10 12:16
> @ssbssb-cmd I ended up removing all traces of System.Text.Json references from all my projects and then it started working.

I've just done a search in files for System.Text.Json and nothing has come back. Where I do have references to Json, it is using the Newtonsoft Json packages

**Comment by RodSanford** [comment] 2021-03-17 11:50
This is still an issue with VS 16.9.2.  Windows and Android are fine. iOS fails when trying to .Build a new HubConnectionBuilder().

**Comment by chetus** [comment] 2021-04-17 17:04
Hello, I get this error on VS2019 16.9.4 on HubConnection.StartAsync only in iOS. Are there any fix?

**Comment by peppy** [comment] 2021-04-17 17:38
@chetus you can find a workaround here: https://github.com/mono/mono/issues/20805#issuecomment-791440473

**Comment by chetus** [comment] 2021-04-17 18:20
@peppy Thanks it works :)
