### ISSUE TITLE
Potential Incorrect ToLocalTime for historical dates prior to 1972

### ISSUE THREAD

**Issue by rsDevelopment1987** [xamarin/xamarin-macios#9054] opened 2020-07-10 11:11 UTC
### Steps to Reproduce

1. Create UTC date and time of 2020-07-07 12:07
2. Using the ToLocalTime() to convert to local time  (uk) 
3. The resulting date is  2020-07-07 13:07
4. Create UTC date and time of 1971-07-07 12:07
5. Using the ToLocalTime() to convert to local time  (uk) 
6. The resulting date is  1971-07-07 12:07

### Expected Behaviour
The resulting date should be 1971-07-07 13:07.  It appears that there are no TimeZone rules prior to 1972 being loaded/used in the ToLocalTime method.

### Actual Behaviour
Comparing results of step 3 and 6 the result of 1971 is an hour out.   This also has an impact when looking up the offset and daylight savings time information.

### Notes
I have debugged as much as possible down in the DateTime and it appears that the dotNet loads a set of TimezoneAdjustment Rules which is smaller than the  the rule set from a dotnet core application.  

I have attached a sample app with output in the console window for information (ignore the ui).  

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.6.1 (build 26)
Installation UUID: f42089e3-3c2d-4d8a-86bd-d37533c78c52
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 610000104

=== Mono Framework MDK ===

Runtime:
	Mono 6.10.0.104 (2019-12/5d03a6fe116) (64-bit)
	Package version: 610000104

=== Roslyn (Language Service) ===

3.6.0-3.20210.9+4eafdcb1bcbd8d3573f2ba6065e56d9b9ce4f8a3

=== NuGet ===

Version: 5.6.0.6591

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.301/Sdks
SDK Versions:
	3.1.301
	3.1.100
	3.0.102
	2.2.401
	2.1.700
	2.1.402
	2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.5
	3.1.0
	3.0.2
	2.2.6
	2.1.14
	2.1.11
	2.1.4
	2.1.2

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.5 (16139)
Build 11E608c

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 13.18.1.31 (Visual Studio Community)
Hash: b3eedfed9
Branch: d16-6
Build date: 2020-04-09 10:22:36-0400

=== Xamarin Designer ===

Version: 16.6.0.329
Hash: d4f8bcd13
Branch: remotes/origin/d16-6
Build date: 2020-04-24 02:16:02 UTC

=== Xamarin.Android ===

Not Installed

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/robert.sayers/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.6.0.50
Hash: 5901879
Branch: remotes/origin/d16-6
Build date: 2020-04-30 04:01:22 UTC

=== Android Device Manager ===

Version: 16.6.0.95
Hash: 45d17b5
Branch: remotes/origin/d16-6
Build date: 2020-04-30 04:01:42 UTC

=== Build Information ===

Release ID: 806010026
Git revision: 9c7c371ce0eefcbfe3a406b6471abc91da319fdb
Build date: 2020-05-25 07:00:13-04
Build branch: release-8.6
Xamarin extensions: 9c7c371ce0eefcbfe3a406b6471abc91da319fdb

=== Operating System ===

Mac OS X 10.15.4
Darwin 19.4.0 Darwin Kernel Version 19.4.0
    Wed Mar  4 22:28:40 PST 2020
    root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

```

### Example Project (If Possible)

[iOSDateTime copy.zip](https://github.com/xamarin/xamarin-macios/files/4902380/iOSDateTime.copy.zip)

**Comment by chamons** [comment] 2020-07-10 15:51
I'm having trouble following the example project and when I tried to reproduce the steps given I'm not seeing your results:

```csharp
		static void Main(string[] args)
		{
			CultureInfo.CurrentCulture = new CultureInfo("en-GB");

			var date1 = DateTime.SpecifyKind(DateTime.Parse("2020-07-07 12:07"), DateTimeKind.Utc);
			Console.WriteLine(date1);
			Console.WriteLine(date1.ToLocalTime());
			var date2 = DateTime.SpecifyKind(DateTime.Parse("1971-07-07 12:07"), DateTimeKind.Utc);
			Console.WriteLine(date2);
			Console.WriteLine(date2.ToLocalTime());
		}
```
```
07/07/2020 12:07:00
07/07/2020 07:07:00
07/07/1971 12:07:00
07/07/1971 07:07:00
```

I'm sure I'm doing something wrong, can you provide code that shows the exact problem you are running into?

**Comment by rsDevelopment1987** [comment] 2020-07-12 20:58
This has evolved and into the other mentioned issue.  

Missing information was have your device in London timezone - from the debugging i've done there appears to have a limited set of timezone adjustments loaded and these adjustments start at 1972 - so the dotNet side of things doesn't know that 1971 is +1 hour of daylight savings time.

**Comment by whitneyschmidt** [comment] 2020-07-22 18:45
@rsDevelopment1987 I'm closing this issue since it's become a duplicate of the https://github.com/xamarin/xamarin-macios/issues/9064. If there's any additional info on this that doesn't apply to the other, feel free to reopen.

**Closed by whitneyschmidt** 2020-07-22 18:45 UTC
Labels: iOS, need-info
