### ISSUE TITLE
WebKit randomly crashing after WKWebView is initialized on Xamarin.iOS 11.10.1.177

### ISSUE THREAD

**Issue by rgbedin** [xamarin/xamarin-macios#4100] opened 2018-05-17 13:28 UTC
### Overview

My solution, which is essentially a WKWebView wrapper, randomly crashes after the WebView is initialized when compiled with Xamarin.iOS 11.10.1.177. The build log and crash log is attached below. It seems that the WKWebView is being deallocated prematurely. It seems to crash at 

> WebKit::WebCookieManagerProxy::processPoolDestroyed()

As you can note in the logs. I've attached the Environment information. The very same project, with no other changes at all, when compiled using Xamarin.iOS 11.9.1.24, works fine.

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.5.1 (build 22)
Installation UUID: 114f7622-c81a-4d00-a1e9-60fffe4ccc76
Runtime:
	Mono 5.10.1.47 (2017-12/8eb8f7d5e74) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010047

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.3.1 (14154.1)
Build 9E501

=== Xamarin.Mac ===

Version: 4.4.1.178 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.10.1.178 (Visual Studio Community)
Hash: 408d3574
Branch: d15-7
Build date: 2018-05-08 18:56:30-0400

=== Xamarin.Android ===

Version: 8.3.0.19 (Visual Studio Community)
Android SDK: /Users/rgbedin/Library/Android/sdk
	Supported Android versions:
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 26.0.2
SDK Platform Tools Version: 25.0.6
SDK Build Tools Version: 26.0.2

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705010022
Git revision: 60442dd643a20c7a4ae1f8705b8d1de8972eee78
Build date: 2018-05-15 01:43:39+00
Xamarin addins: 4194ffe4868321e4c3477bd56aed579bda4c6fbb

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
```

### Build Log

Please note I have one .NET Standard 2.0 Core project (ZebuEnterprise.Core -- shared with Android and iOS), two iOS extension projects (ZebuEnterprise.iOS.NotificationExtension and ZebuEnterprise.iOS.ShareExtension) and the main iOS project (ZebuEnterprise.iOS).

[build.txt](https://github.com/xamarin/xamarin-macios/files/2013309/build.txt)

### Crash Log

[log.txt](https://github.com/xamarin/xamarin-macios/files/2013244/log.txt)

**Comment by spouliot** [comment] 2018-05-17 14:16
The crash log does not show anything that points out directly to the Xamarin runtime. Could you share your solution with us (or a smaller test case) so we can duplicate this on our side ? thanks!

**Comment by markusian** [comment] 2018-05-22 14:07
I am seeing the same thing in my project. Unfortunately I cannot manage to reproduce it myself, but quite a number of users are seeing the app crash, and to be sincere I am not sure what to do at the moment

**Comment by pineapple216** [comment] 2018-06-19 12:21
I'm experiencing the same issue on Xamarin.iOS 11.12.0.4. Please fix this issue ASAP.

**Comment by rolfbjarne** [comment] 2018-06-19 12:32
This looks like a duplicate of #4130.

**Closed** 2018-06-19 12:41 UTC
Labels: duplicate, iOS, need-info
