### ISSUE TITLE
Error: No valid iOS code signing keys found in keychain

### ISSUE THREAD

**Issue by hedgehed** [xamarin/xamarin-macios#7171] opened 2019-10-04 07:26 UTC
### Steps to Reproduce
1. in Xcode Version 11.0 I successfully compiled application and launched on the iPhone 

2. In Visual studio 2019 version 16.3.2  for Windows i have an error 
 "No valid iOS code signing keys found in keychain"
With same name of application, same bundle id

### Environment
```
Microsoft Visual Studio Professional 2019
Version 16.3.2
VisualStudio.16.Release/16.3.2+29326.143
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

Visual C++ 2019   00435-20000-00004-AA591
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.3.283.64955
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.3.283.64955
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.3.283.64955
Azure App Service Tools v3.0.0

C# Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Debugging Tools for Windows   10.0.18346.1000
Integrates the Windows Debugger functionality (http://go.microsoft.com/fwlink/?linkid=223405) in Visual Studio.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.83+gbc8a4b23ec
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.3.7 (9d260c5)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

PHP Tools for Visual Studio   1.32.11556.2019
PHP Tools extend Visual Studio with a set of features to build PHP applications more efficiently. It makes code more readable, easier to navigate, and clean.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61908.27190
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.10821.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19455.1+0422ff293bb2cc722fe5021b85ef50378a9af823
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Windows Driver Kit   10.0.18346.1000
Headers, libraries, and tools needed to develop, debug, and test Windows drivers (msdn.microsoft.com/en-us/windows/hardware/gg487428.aspx)

Xamarin   16.3.0.274 (d16-3@06531f8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.3.0.246 (remotes/origin/d16-3@bd2f86892)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.565 (27e9746)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.0.0.43 (d16-3/8af1ca8)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-06@7af64d1ebe9
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333


Xamarin.iOS and Xamarin.Mac SDK   13.2.0.42 (5e8a208)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

XCode Version 11.0 (11A420a)

### Build Logs

`https://gist.github.com/hedgehed/1166aa3a14607fd31c31460f089dac4c`

### Example Project (If Possible)
(no example)
**I think what root of problem is:
Xcode places in keystore the certificate 'Apple Development: blah@blah.com (********)'
But visual studio searches in keystore the prefixes 'iPhone Developer', 'iOS Development'**

> VS bug [#994126](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/994126)

**Comment by kolliganesh** [comment] 2019-10-04 11:31
same here

**Comment by FlxGen** [comment] 2019-10-04 16:21
Same

**Comment by FlxGen** [comment] 2019-10-04 16:39
Found a work around.  In Mac VS create a dummy iOS project then go to preferences > publishing > select your Apple ID > View Details... >  Create certificate.  Create an iOS Development and iOS Distribution certificate.  I don't think VS and VS Mac work with Apples new Xcode 11 certs.

**Comment by hedgehed** [comment] 2019-10-04 17:16
> 
> 
> Found a work around. In Mac VS create a dummy iOS project then go to preferences > publishing > Apple Developer Accounts > select your Apple ID > View Details... > Create certificate. Create an iOS Development and iOS Distribution certificate. I don't think VS and VS Mac works with Apples new Xcode 11 certs.

https://clip2net.com/clip/m590560/67a87-clip-127kb.png

I am not member of Apple Development, i just use the "Free provisioning" for testing on my iphone.

https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/free-provisioning?tabs=macos

**Comment by hedgehed** [comment] 2019-10-04 17:44
I also tried to install older Xcode (10.3), but it threw an error when trying to connect to apple server to obtaining the free provisioning like here:

https://stackoverflow.com/questions/52490574/a-non-http-200-response-was-received-400-for-url-https-developerservices2-ap

**Comment by FlxGen** [comment] 2019-10-04 19:05
I don't use that development path so I'm not sure.  You tried what I would have tried with the older version of Xcode.  I believe your assertion above is correct regarding searching for specific names in the Keystore.  Apple changed the cert names in Xcode 11.  A cert I had in my store was called "iOS Development" but when I create new certs they are called "Development".  I'm not sure this is how VS is searching the store since it seems kind of rudimentary but it makes sense.  This definitively seems like a bug.

**Comment by chamons** [comment] 2019-10-04 22:09
Are you using the Automatic or Manual provisioning option in Visual Studio?

https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/automatic-provisioning?tabs=windows

**Comment by FlxGen** [comment] 2019-10-04 22:12
I tested with both.  Neither work.  

For what it's worth, automatic has never worked in VS19 for me.

**Comment by chamons** [comment] 2019-10-04 22:24
I'm not honestly sure if this is a bug in the IDE, or user error. Getting signing working is rather non-trivial.

Can someone please try enabling automatic and posting logs when things go wrong?

**Comment by FlxGen** [comment] 2019-10-04 22:37
Just want to be clear.  Automatic under Bundle Signing or under Manual Provisioning > Provision Profile > Automatic? 

If you clear all of the certs out of your Keystore and install only the Xcode11 certs, the profiles don't appear in the manual provisioning lists.  If you create a developer profile with both an Xcode11 cert and pre-Xcode11 cert it shows up.  You can't have two certs with a distro profile so no distro profile never appears.  90% sure this is a bug unless there is some new procedure I'm not aware of.

**Comment by FlxGen** [comment] 2019-10-04 22:40
Also, VS Mac still creates old certs and those work.

It probably hasn't come up yet because most users probably have their pre-Xcode11 certs in their profiles still.

**Comment by hedgehed** [comment] 2019-10-05 07:03
This is Xcode 10.3 list of certificates
https://clip2net.com/clip/m590560/ef4b3-clip-169kb.jpg

This is error if i click "IOS Development"
https://clip2net.com/clip/m590560/33b5e-clip-128kb.png

This is Xcode 11 list of certificates
https://clip2net.com/clip/m590560/679d6-clip-142kb.jpg

Maybe you know a quick and dirty hack about comparing names of certificates 
it looks like i can patch the 
Xamarin.iOS.Common.targets file, but not sure
(about this
The certificate 'Apple Development: blah@blah.com (********)' does not match any of the prefixes 'iPhone Developer', 'iOS Development'.
)

**Comment by rolfbjarne** [comment] 2019-10-07 05:45
This looks like a duplicate of #6486.

**Comment by hedgehed** [comment] 2019-10-07 11:47
yes, thanks, 
I edited the project file, added the full name of my certificate from the key holder and it worked!
(I apologize for not finding #6486 by keywords of error)

**Comment by chamons** [comment] 2019-10-07 15:05
#6486 is not super clear in this case, so don't feel bad for missing it. 

I'm going to close this issue and update #6486 with text to hopefully make the connection more obvious.

**Closed by chamons** 2019-10-07 15:05 UTC
Labels: external-xamarin-vs, support

**Comment by clintonrocksmith** [comment] 2019-10-10 01:40
For other people

We got it working by editing the .csproj file and manually specifying the name of the certificate as seen in the KeyChain

<CodesignKey>Apple Distribution: Company Pty Ltd (5W******)</CodesignKey>

Visual Studio Mac 2019 (latest) still didn't recognise it, but it built in release mode.
