### ISSUE TITLE
[XI]mscorlib test failure with release config  on  new iOS device

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#4901] opened 2018-10-01 20:47 UTC
### Steps to Reproduce

1. Update System to Xamarin.iOS stable build, Version: 12.0.0.15 (Visual Studio Enterprise)
Hash: 84552a4
2. Execute mscorlib tests on device with release config

### Expected Behavior
All tests pass
### Actual Behavior
Observed that TestGetFileLineNumber, TestGetFileName, TestFileName2 in StackFrameTest2 and StackFrameTest3 are failing. 
### Environment

```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.6.7 (build 49)
Installation UUID: 74c37335-5878-4fa7-8f71-09bc48b661c5
Runtime:
	Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000301

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 10.0 (14320.24)
Build 10A254a

=== Xamarin.Mac ===

Version: 4.6.0.14 (Visual Studio Enterprise)
Hash: 1a6e2786
Branch: 
Build date: 2018-08-28 00:12:06-0400

=== Xamarin.iOS ===

Version: 12.0.0.15 (Visual Studio Enterprise)
Hash: 84552a46
Branch: xcode10
Build date: 2018-09-17 21:54:33-0400

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Enterprise)
Android SDK: /Users/gourikumari/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)

SDK Tools Version: 25.2.3
SDK Platform Tools Version: 25.0.1
SDK Build Tools Version: 25.0.1

Java SDK: /usr
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706070049
Git revision: 0b48ccfb376397678b3bc3653da2c6603d35357d
Build date: 2018-09-20 21:14:23+00
Build branch: release-7.6
Xamarin extensions: b25fd1e2b9a7859aff9536924e8edb6cbfb78637

=== Operating System ===

Mac OS X 10.14.0
Darwin 18.0.0 Darwin Kernel Version 18.0.0
    Wed Aug 22 20:59:21 PDT 2018
    root:xnu-4903.201.2~4/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Gist Ide Information 1.1.0


```

### Build Logs

Build Log: https://gist.github.com/GouriKumari/f3127b85dff84c212e9452ce0d9d62d6
test Log from console: https://gist.github.com/GouriKumari/bd4bfb9ec5d07d8de3103c74f8199b6c

### Example Project (If Possible)
xamarin-macios/bcl-tests/mscorlib

## Additional Info:
This issue is not occurring with Debug config.

**Comment by VincentDondain** [comment] 2018-10-02 15:15
Need to borrow and iPhone X[s] to confirm that (:

**Comment by VincentDondain** [comment] 2018-10-02 21:04
I could not reproduce this issue with XI master: https://gist.github.com/VincentDondain/a38d0fd064129efb11ec0cf4e6eb16a0.

I tried running the mscorlib tests on device with release config.

This might not have been device specific and might already have been fixed. @GouriKumari I'll close the issue for now but feel free to reopen if you have more evidence of it being a X[s] issue that's not fixed on master.

**Closed by VincentDondain** 2018-10-02 21:04 UTC
