### ISSUE TITLE
error MT3001: Could not AOT the assembly

### ISSUE THREAD

**Issue by Ludovic192** [xamarin/xamarin-macios#11442] opened 2021-05-05 09:27 UTC
### Steps to Reproduce

1. Try to compile a iOS project referencing the Abp.dll > 6.0 with 14.3 or 14.5 SDK and don't link assemblies option

[logs.txt](https://github.com/xamarin/xamarin-macios/files/6425930/logs.txt)

### Expected Behavior
The project build successfully 
### Actual Behavior
Build failure
### Environment

=== Visual Studio Community 2019 for Mac ===

Version 8.9.8 (build 7)
Installation UUID: 731501dc-0f02-4e5c-8057-d2a5ecf48d83
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000125

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.125 (2020-02/8c552e98bd6) (64-bit)
	Package version: 612000125

=== Roslyn (Language Service) ===

3.9.0-6.21152.10+c10f884b30737542ddd84ca889a4aad9281ce210

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.202/Sdks
SDK Versions:
	5.0.202
	5.0.103
	5.0.102
	5.0.100
	3.1.408
	3.1.406
	3.1.405
	3.1.404
	3.1.402
	3.1.401
	3.1.301
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.5
	5.0.3
	5.0.2
	5.0.0
	3.1.14
	3.1.12
	3.1.11
	3.1.10
	3.1.8
	3.1.7
	3.1.5
	2.1.23
	2.1.22
	2.1.21
	2.1.19

=== .NET Core 3.1 SDK ===

SDK: 3.1.408

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.5 (18205)
Build 12E262

=== Xamarin.Mac ===

Version: 7.10.0.5 (Visual Studio Community)
Hash: ab40b131d
Branch: xcode12.5
Build date: 2021-04-22 08:56:41-0400

=== Xamarin.iOS ===

Version: 14.16.0.5 (Visual Studio Community)
Hash: ab40b131d
Branch: xcode12.5
Build date: 2021-04-22 08:56:42-0400

=== Xamarin Designer ===

Version: 16.9.0.324
Hash: b1e216c75
Branch: remotes/origin/d16-9
Build date: 2021-04-16 00:02:50 UTC

=== Xamarin.Android ===

Version: 11.2.2.1 (Visual Studio Community)
Commit: xamarin-android/d16-9/877f572
Android SDK: Not found

=== Microsoft OpenJDK for Mobile ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/dev/bretjohn/readme-tweak~3
Build date: 2021-04-21 21:23:40 UTC

=== Android Device Manager ===

Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/dev/jmt/d16-9bump~1
Build date: 2021-04-21 21:23:58 UTC

=== Build Information ===

Release ID: 809080007
Git revision: 85b793ce322599fe423c2d233c346b13824ca4d8
Build date: 2021-04-28 12:54:34-04
Build branch: release-8.9
Xamarin extensions: 85b793ce322599fe423c2d233c346b13824ca4d8

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.1.0 Darwin Kernel Version 20.1.0
    Sat Oct 31 00:07:11 PDT 2020
    root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64

### Build Logs

.txt file attached. 

### Example Project (If Possible)

I cannot share the project and my schedule doesn't allow me to spare time on creating a sample reproducing. 
I will however share as much details as possible:
It appears that the issue is comes from the Abp.dll version 6 and up not being compatible with the compiler. 
The issue only occurs when I try to compile in release | iPhone configuration. In this configuration, the supported architecture is locked on ARM64. 
When I try to compile using linking I get a different error: 

MTOUCH : error MT2102: Error processing the method 'System.Void Abp.Auditing.AuditingInterceptor/<InternalInterceptAsynchronous>d__6`1::MoveNext()' in the assembly 'Abp.dll': Value cannot be null.

If I try to compile in release | iPhonesimulator  which allows x86|x64 architecture, it works fine. 

As a workaround I had to compile using an older version of Abp.dll (5.14) since we had to get a release out but we would appreciate being able to use the latest version soon. 

I tried with both 14.3 & 14.5 SDK versions, exact same output.

**Comment by spouliot** [comment] 2021-05-05 13:05
It looks like your project does not provide all the required dependencies to build correctly. E.g. your logs contains several (33) warnings like:

>     Dependency "System.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
>        Could not resolve this reference. Could not locate the assembly "System.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.

>     Dependency "System.Reflection.TypeExtensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
>        Could not resolve this reference. Could not locate the assembly "System.Reflection.TypeExtensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.

>     Dependency "System.AppContext, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
>        Could not resolve this reference. Could not locate the assembly "System.AppContext, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.

This is either an issue in your project or (more likely) in the one/many of the (sub)dependencies you're using. However this is **not** a bug in the SDK itself. We're simply are not given a correct/complete input to generate a valid application.

> When I try to compile using linking I get a different error:

That's quite likely why the managed linker complains... it cannot find types it requires, so it cannot rewrite a smaller version of the assembly. If the code was **not** reachable then the linker would not complain (the error would not be seen and discard along unused code).

> The issue only occurs when I try to compile in release | iPhone configuration. In this configuration, the supported architecture is locked on ARM64.

Turning off the managed linker means you're giving the (incomplete) set of assemblies to the AOT compiler (which is what must be used for device builds). The AOT compiler face the same problem (as the managed linker) as it can't AOT or call code it cannot find.

> If I try to compile in release | iPhonesimulator which allows x86|x64 architecture, it works fine.

Maybe. When you do so it's being JITed. That means those errors are found at runtime (not build time) and depending on your code it's possible that the error are never reached (or it would just crash after more exhaustive testing).

**Comment by Ludovic192** [comment] 2021-05-05 13:43
Great, thanks for the answer. 
I will look into these warnings about the missing assemblies. 
If the issue still persists I will try to create a sample project reproducing the issue.

**Comment by LeoJHarris** [comment] 2021-05-06 02:21
I just started getting exactly the same issue.

**Comment by spouliot** [comment] 2021-05-31 15:20
No test cases were supplied, closing.

If you have this (or a similar issue) please file an new issue and make sure to include a test case so we can reproduce it. Thanks!

**Closed by spouliot** 2021-05-31 15:20 UTC
Labels: iOS, need-info, support
