### ISSUE TITLE
NSDate to DateTime conversion issue in iOS platform

### ISSUE THREAD

**Issue by Sasikumar3595** [xamarin/xamarin-macios#11814] opened 2021-06-04 09:48 UTC
I'm working in custom Date and TimePicker and i was tried to convert the NSDate value to DateTime value makes exception(System.ArgumentOutOfRangeException - Specified argument was out of the range of valid values. Parameter name: Value is outside the range of NSDate).

**Convert to NSDate from DateTime**
```
public NSDate ToNsDate(DateTime dateTime)
{
       if (dateTime.Kind == DateTimeKind.Unspecified)
       {
            dateTime = DateTime.SpecifyKind(dateTime, DateTimeKind.Local);
       }
       return (NSDate)dateTime;
}
```
**Convert to DateTime from NSDate**
```
public DateTime ToDateTime(NSDate date)
 {
       double offsetValue = calendar.TimeZone.SecondsFromGMT(date);
        return (DateTime)date.AddSeconds(offsetValue);
 }
```
### Steps to Reproduce

1. Run the sample
2. In the sample, convert to DateTime from NSDate makes crash 
3. NSDate value(1/1/0001) convert to DateTime makes crash

### Expected Behavior

- Conversion does not makes crash

### Actual Behavior

- Conversion makes crash

### Screenshots

![Code](https://user-images.githubusercontent.com/44917578/120782538-bbdb6680-c547-11eb-8d51-cf454a2f33c4.png)
![Value](https://user-images.githubusercontent.com/44917578/120782548-bf6eed80-c547-11eb-907d-35719e52c332.png)

### Example Project (If Possible)

[PickerRenderer.zip](https://github.com/xamarin/xamarin-macios/files/6597449/PickerRenderer.zip)

**Comment by spouliot** [comment] 2021-06-04 14:43
Duplicate of https://github.com/xamarin/xamarin-macios/issues/6993

**Closed by spouliot** 2021-06-04 14:43 UTC

**Comment by Sasikumar3595** [comment] 2021-06-07 05:03
Hi @spouliot ,

Above specified issue shows DateTime to NSDate conversion makes wrong value. But i was logged the issue report for NSDate to DateTime conversion makes crash 

```
//// Create minimum NSDate value
NSDateComponents dateComponents = new NSDateComponents { Year = 1, Month = 1, Day = 1 };
NSDate date = calendar.DateFromComponents(dateComponents);

//// Convert the minimum NSDate value to date time value.
DateTime convertedDateTime = ToDateTime(date);
```

The above specified code makes exception NSDate to DateTime conversion
