### ISSUE TITLE
Flexibility app UI differences found with iOS 12 Simulator

### ISSUE THREAD

**Issue by bholmes** [xamarin/xamarin-macios#4659] opened 2018-08-20 21:02 UTC
### Steps to Reproduce
 
1. Clone the following repo https://github.com/davidortinau/flexibility
2. Using the Xcode 10 Xamarin Preview open and build Flexibility.sln for iPhone 8 iOS 12 Simulator
3. Run the app

### Expected Behavior

![image](https://user-images.githubusercontent.com/310715/44366209-02946a80-a49a-11e8-86d0-f38b6b19e325.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/310715/44365970-2dca8a00-a499-11e8-8980-ad586bc1cf1f.png)

On device with iOS 12 we do not observe a difference and the app renders as we expect.

### Environment

https://gist.github.com/bholmes/4c7f31244d117b0adfb9525f38919d52

### Build Logs

https://gist.github.com/bholmes/4f4c00b74017620b3191ccac40a558c0

### Example Project (If Possible)

https://github.com/davidortinau/flexibility

**Comment by VincentDondain** [comment] 2018-08-20 21:24
@bholmes what is the version of you `/Applications/Xcode.app`? If it's Xcode 10 beta 6 did you open it to install the command line tools.

Then what is you `xcode-select -p`?

**Comment by VincentDondain** [comment] 2018-08-20 21:27
Looks like you're still running into https://github.com/xamarin/xamarin-macios/issues/4577 and friends but I cannot reproduce that with Xcode 10 beta 6 anymore.

**Comment by bholmes** [comment] 2018-08-20 21:28
Xcode 10 Beta 6

Yes I opened Xcode and let it finish the installation.  

`xcode-select -p` is `/Applicatations/Xcode.app/Contents/Developer` AND I expect that.  This is how and where I installed the beta.

**Comment by VincentDondain** [comment] 2018-08-21 13:33
@bholmes can you do a `xcode-select --install` and re-try?

**Comment by bholmes** [comment] 2018-08-21 13:43
@VincentDondain Same result.  Just so we are on the same page, have you tried this repo with your system and Xcode beta 6?

**Comment by VincentDondain** [comment] 2018-08-21 15:09
Yes and it works for me. @mandel-macaque can you double check too please?

**Comment by VincentDondain** [comment] 2018-08-21 15:14
And it's not the fact that my VSMac is *using* beta 6 because even with the previous betas it now works. That's why I'm thinking the fix is in Apple's installed tools (maybe ibtool).

**Comment by VincentDondain** [comment] 2018-08-21 17:46
^ yea that's it. I could reproduce the issue again with XI `11.99.2.130` (Preview 5). The latest XI from the Xcode 10 branch, built with beta 6 should work.

Closing (feel free to reopen if you're still experiencing the issue).

**Closed by VincentDondain** 2018-08-21 17:46 UTC
Labels: need-info

**Comment by bholmes** [comment] 2018-08-21 18:07
Confirmed that xamarin.ios-11.99.3.243.pkg  looks correct.  Mysteries like these concern me.  What is the diff?

**Comment by VincentDondain** [comment] 2018-08-21 18:08
So it's an XI that was built after the Xcode 10 beta 6 bump.
