### ISSUE TITLE
Support CGColorCreateCopyByMatchingToColorSpace

### ISSUE THREAD

**Issue by sparkie108** [xamarin/xamarin-macios#10270] opened 2020-12-12 15:47 UTC
Converting colors between the sRGB and Display P3 color spaces is not currently possible using Xamarin.iOS.  It is possible in Swift and Objective-C.

My requirement to convert colors comes from UIColorPickerViewController by default returning Display P3 colors but SkiaSharp only supporting screen drawing using sRGB. 

### Expected Behavior

The C# equivalent of the following Swift code should be possible:
`let color = UIColor.blue.cgColor.converted(to: CGColorSpace.displayP3, intent: .relative, options: nil)`

### Actual Behavior

The CGColor converted method (CGColorCreateCopyByMatchingToColorSpace in obj-C) is unavailable as it's set to internal.  Making it public should resolve this issue.

The Display P3 color space can be created just fine:

`CGColorSpace.CreateWithName(CGColorSpaceNames.DisplayP3)`

### Environment

=== Visual Studio Community 2019 for Mac ===

Version 8.8.3 (build 16)
Installation UUID: e5faad52-1fe9-422a-b2d2-e8ec7f1407ad
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000107

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.107 (2020-02/a22ed3f094e) (64-bit)
	Package version: 612000107

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.2 (17535)
Build 12B45b

=== Xamarin.iOS ===

Version: 14.6.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:41-0500

=== Build Information ===

Release ID: 808030016
Git revision: cc6375d2fdcc1b42532e551e24ce650eaca1ae45
Build date: 2020-11-25 13:16:20-05
Build branch: release-8.8
Xamarin extensions: cc6375d2fdcc1b42532e551e24ce650eaca1ae45

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Thu Oct 29 22:56:45 PDT 2020
    root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

DeepClean 1.2.5
FileNesting 0.1.2

**Comment by rolfbjarne** [comment] 2020-12-14 07:09
This is a duplicate of #10212, which has already been fixed and will be released when we release support for Xcode 12.3.

**Closed by rolfbjarne** 2020-12-14 07:09 UTC
