### ISSUE TITLE
Internal consistency error, please file a bug (http://bugzilla.xamarin.com). Additional data: found managed object 0x126028ea8=0x7fb3f9052880 (Linker.Sealer.Unsealable) in native object 0x60c000223540 (AppDelegate).

### ISSUE THREAD

**Issue by marek-safar** [xamarin/xamarin-macios#4175] opened 2018-06-03 07:30 UTC
### Steps to Reproduce

1. apply patch https://gist.github.com/marek-safar/e564ad5efdbe66387ae53b17ddea86a6
2. make run-ios-sim64-linkall
3. 

### Expected Behavior

No crash

### Actual Behavior

```
2018-06-03 09:24:06.089 link all[65308:6402124] Xamarin.iOS: Internal consistency error, please file a bug (http://bugzilla.xamarin.com). Additional data: found managed object 0x126028ea8=0x7fb3f9052880 (Linker.Sealer.Unsealable) in native object 0x60c000223540 (AppDelegate).
2018-06-03 09:24:06.091 link all[65308:6402124] critical: Stacktrace:

2018-06-03 09:24:06.091 link all[65308:6402124] critical:   at <unknown> <0xffffffff>
2018-06-03 09:24:06.091 link all[65308:6402124] critical:   at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain (int,string[],intptr,intptr) [0x0005c] in <fada7c48e0ed4641aa34baffb2274fed>:0
2018-06-03 09:24:06.092 link all[65308:6402124] critical:   at UIKit.UIApplication.Main (string[],intptr,intptr) [0x00005] in /Users/marek/git/xamarin/xamarin-macios/src/UIKit/UIApplication.cs:79
2018-06-03 09:24:06.092 link all[65308:6402124] critical:   at UIKit.UIApplication.Main (string[],string,string) [0x0002c] in /Users/marek/git/xamarin/xamarin-macios/src/UIKit/UIApplication.cs:63
2018-06-03 09:24:06.092 link all[65308:6402124] critical:   at LinkAll.Application.Main (string[]) [0x00001] in /Users/marek/git/xamarin/xamarin-macios/tests/linker/ios/link all/Main.cs:19
2018-06-03 09:24:06.093 link all[65308:6402124] critical:   at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) [0x00051] in <dec08c9bb76c4510a20ddda25bf09b70>:0
2018-06-03 09:24:06.093 link all[65308:6402124] critical:
Native stacktrace:

2018-06-03 09:24:06.149 link all[65308:6402124] critical: 	0   link all                            0x000000010c577394 mono_handle_native_crash + 244
2018-06-03 09:24:06.149 link all[65308:6402124] critical: 	1   libsystem_platform.dylib            0x000000011448ff5a _sigtramp + 26
2018-06-03 09:24:06.149 link all[65308:6402124] critical: 	2   ???                                 0x000000000000ffff 0x0 + 65535
2018-06-03 09:24:06.150 link all[65308:6402124] critical: 	3   libsystem_c.dylib                   0x00000001140c5c97 abort + 127
2018-06-03 09:24:06.150 link all[65308:6402124] critical: 	4   link all                            0x000000010c74e5c9 xamarin_assertion_message + 425
2018-06-03 09:24:06.150 link all[65308:6402124] critical: 	5   link all                            0x000000010c74e405 xamarin_get_managed_object_for_ptr_fast + 213
2018-06-03 09:24:06.150 link all[65308:6402124] critical: 	6   link all                            0x000000010c49ce43 _ZL30native_to_managed_trampoline_5P11objc_objectP13objc_selectorPP11_MonoMethodP13UIApplicationP12NSDictionaryj + 291
2018-06-03 09:24:06.150 link all[65308:6402124] critical: 	7   link all                            0x000000010c49cd08 -[AppDelegate application:didFinishLaunchingWithOptions:] + 72
2018-06-03 09:24:06.150 link all[65308:6402124] critical: 	8   UIKit                               0x000000010e0f775b -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 278
2018-06-03 09:24:06.150 link all[65308:6402124] critical: 	9   UIKit                               0x000000010e0f91d2 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4123
2018-06-03 09:24:06.150 link all[65308:6402124] critical: 	10  UIKit                               0x000000010e0fe62b -[UIApplication _runWithMainScene:transitionContext:completion:] + 1677
2018-06-03 09:24:06.150 link all[65308:6402124] critical: 	11  UIKit                               0x000000010e4c0e4a __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 866
2018-06-03 09:24:06.151 link all[65308:6402124] critical: 	12  UIKit                               0x000000010e893909 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
2018-06-03 09:24:06.151 link all[65308:6402124] critical: 	13  UIKit                               0x000000010e4c0a86 -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 236
2018-06-03 09:24:06.151 link all[65308:6402124] critical: 	14  UIKit                               0x000000010e4c12a7 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 675
2018-06-03 09:24:06.151 link all[65308:6402124] critical: 	15  UIKit                               0x000000010ee324d4 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 299
2018-06-03 09:24:06.152 link all[65308:6402124] critical: 	16  UIKit                               0x000000010ee3236e -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 433
2018-06-03 09:24:06.152 link all[65308:6402124] critical: 	17  UIKit                               0x000000010eb1662d __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 221
2018-06-03 09:24:06.152 link all[65308:6402124] critical: 	18  UIKit                               0x000000010ed11387 _performActionsWithDelayForTransitionContext + 100
2018-06-03 09:24:06.152 link all[65308:6402124] critical: 	19  UIKit                               0x000000010eb164f7 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 223
2018-06-03 09:24:06.153 link all[65308:6402124] critical: 	20  UIKit                               0x000000010e892fb0 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
2018-06-03 09:24:06.153 link all[65308:6402124] critical: 	21  UIKit                               0x000000010e0fcf0c -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 515
2018-06-03 09:24:06.153 link all[65308:6402124] critical: 	22  UIKit                               0x000000010e6cfa97 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
2018-06-03 09:24:06.153 link all[65308:6402124] critical: 	23  FrontBoardServices                  0x00000001178042f3 -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 331
2018-06-03 09:24:06.153 link all[65308:6402124] critical: 	24  FrontBoardServices                  0x000000011780ccfa __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 225
2018-06-03 09:24:06.154 link all[65308:6402124] critical: 	25  libdispatch.dylib                   0x0000000113f85779 _dispatch_client_callout + 8
2018-06-03 09:24:06.154 link all[65308:6402124] critical: 	26  libdispatch.dylib                   0x0000000113f8a931 _dispatch_block_invoke_direct + 317
2018-06-03 09:24:06.154 link all[65308:6402124] critical: 	27  FrontBoardServices                  0x0000000117838470 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
2018-06-03 09:24:06.154 link all[65308:6402124] critical: 	28  FrontBoardServices                  0x000000011783812e -[FBSSerialQueue _performNext] + 439
2018-06-03 09:24:06.155 link all[65308:6402124] critical: 	29  FrontBoardServices                  0x000000011783868e -[FBSSerialQueue _performNextFromRunLoopSource] + 45
2018-06-03 09:24:06.155 link all[65308:6402124] critical: 	30  CoreFoundation                      0x0000000110f70bb1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
2018-06-03 09:24:06.155 link all[65308:6402124] critical: 	31  CoreFoundation                      0x0000000110f554af __CFRunLoopDoSources0 + 271
2018-06-03 09:24:06.155 link all[65308:6402124] critical: 	32  CoreFoundation                      0x0000000110f54a6f __CFRunLoopRun + 1263
2018-06-03 09:24:06.155 link all[65308:6402124] critical: 	33  CoreFoundation                      0x0000000110f5430b CFRunLoopRunSpecific + 635
2018-06-03 09:24:06.155 link all[65308:6402124] critical: 	34  GraphicsServices                    0x000000011648aa73 GSEventRunModal + 62
2018-06-03 09:24:06.156 link all[65308:6402124] critical: 	35  UIKit                               0x000000010e1000b7 UIApplicationMain + 159
2018-06-03 09:24:06.156 link all[65308:6402124] critical: 	36  ???                                 0x00000001273975e9 0x0 + 4953044457
2018-06-03 09:24:06.156 link all[65308:6402124] critical: 	37  ???                                 0x0000000127397483 0x0 + 4953044099
2018-06-03 09:24:06.156 link all[65308:6402124] critical: 	38  link all                            0x000000010c589654 mono_jit_runtime_invoke + 1428
2018-06-03 09:24:06.156 link all[65308:6402124] critical: 	39  link all                            0x000000010c66f0df mono_runtime_invoke_checked + 127
2018-06-03 09:24:06.157 link all[65308:6402124] critical: 	40  link all                            0x000000010c6746fe mono_runtime_exec_main_checked + 110
2018-06-03 09:24:06.157 link all[65308:6402124] critical: 	41  link all                            0x000000010c4f6439 mono_jit_exec + 297
2018-06-03 09:24:06.157 link all[65308:6402124] critical: 	42  link all                            0x000000010c75e4e6 xamarin_main + 2726
2018-06-03 09:24:06.157 link all[65308:6402124] critical: 	43  link all                            0x000000010c4aed70 main + 80
2018-06-03 09:24:06.157 link all[65308:6402124] critical: 	44  libdyld.dylib                       0x0000000113ffa955 start + 1
2018-06-03 09:24:06.157 link all[65308:6402124] critical: 	45  ???                                 0x0000000000000009 0x0 + 9
2018-06-03 09:24:06.158 link all[65308:6402124] critical:
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================
```

### Environment

```
```

**Comment by dalexsoto** [comment] 2018-06-05 17:38
@marek-safar I tried reproducing the issue with the steps you mentioned and I am unable to do so using latest master[1]. Could you tell me in what version you were able to reproduce this?

[1]:
```
Test run started
2018-06-05 10:35:27.674 link all[74418:3144139] PBItemCollectionServicer connection disconnected.
Tests have finished executing
Xamarin.Hosting: Simulated process has exited.
Test run completed
launchctl remove com.apple.CoreSimulator.CoreSimulatorService
killall -9 'iPhone Simulator' 'iOS Simulator' Simulator 'Simulator (Watch)' com.apple.CoreSimulator.CoreSimulatorService ibtoold
Tests run: 29 Passed: 29 Inconclusive: 0 Failed: 0 Ignored: 1
```

**Comment by rolfbjarne** [comment] 2018-06-08 17:27
If you built XI yourself, this is probably because something was only partially rebuild in the XI assemblies / mtouch.

**Comment by mandel-macaque** [comment] 2018-07-12 19:19
@marek-safar should we close this bug?

**Closed** 2018-07-13 21:14 UTC
Labels: iOS, need-info
