### ISSUE TITLE
Directory Not Found Exception - iPhone XR 12.4 + Xcode 12.2

### ISSUE THREAD

**Issue by Axemasta** [xamarin/xamarin-macios#10097] opened 2020-11-16 14:44 UTC
I noticed this issue after upgrading to the latest version of Xcode, when it decided to set my default simulator to the iPhone XR.

### Steps to Reproduce

1. Ensure latest Xcode 12.2 (12B45b) is installed (VSMac version is not important)
2. Load any Xamarin iOS / Forms project
3. Build and Run on **iPhone XR 12.4**

### Expected Behavior

The code builds and runs successfully

### Actual Behavior

1 Error in build:

**Error**
`Error: System.IO.DirectoryNotFoundException: Could not find a part of the path "/Users/user/Documents/POC/Xamarin/PathNotFoundTest/PathNotFoundTest.iOS/obj/iPhoneSimulator/Debug/device-builds/iphone x??-12.4/actool/bundle/AppIcon20x20@2x.png"`

Pay close attention to the device path: `/iphone x??-12.4/`. If I go to that directory via finder I can confirm it does exist

![missing path](https://user-images.githubusercontent.com/33064621/99265520-adcb3000-2819-11eb-8e46-53267ba1494c.png)

The path exists but the path string used in the build is wrong, the directory is created with a special character `ʀ` and the build is expecting `R`

**Stack Trace**
```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(3,3): Error: System.IO.DirectoryNotFoundException: Could not find a part of the path "/Users/user/Documents/POC/Xamarin/PathNotFoundTest/PathNotFoundTest.iOS/obj/iPhoneSimulator/Debug/device-builds/iphone x??-12.4/actool/bundle/AppIcon20x20@2x.png".
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0015e] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/FileStream.cs:223 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/FileStream.cs:106 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions)
  at System.IO.FileSystem.CopyFile (System.String sourceFullPath, System.String destFullPath, System.Boolean overwrite) [0x00025] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs:54 
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x00056] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/File.cs:74 
  at Xamarin.MacDev.Tasks.SmartCopyTaskBase.CopyFile (System.String source, System.String target, System.String targetItemSpec) [0x00030] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/msbuild/Xamarin.MacDev.Tasks.Core/Tasks/SmartCopyTaskBase.cs:66 
  at Xamarin.MacDev.Tasks.SmartCopyTaskBase.Execute () [0x000d2] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/msbuild/Xamarin.MacDev.Tasks.Core/Tasks/SmartCopyTaskBase.cs:99  (PathNotFoundTest.iOS)
```

### Environment

```
=== Visual Studio Professional 2019 for Mac ===

Version 8.8 (build 2913)
Installation UUID: d0e71568-6b05-4a41-b8fa-320993c585d4
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

=== Roslyn (Language Service) ===

3.8.0-5.20515.7+713efb0e68d34ab75faaf709e071e5c2d8d4ed0e

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.100/Sdks
SDK Versions:
	5.0.100
	3.1.403
	3.1.402
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.0
	3.1.9
	3.1.8
	2.1.23
	2.1.22

=== .NET Core 3.1 SDK ===

SDK: 3.1.403

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.2 (17535)
Build 12B45b

=== Xamarin.Mac ===

Version: 6.22.1.26 (Visual Studio Professional)
Hash: 1dc78db1a
Branch: d16-8-xm
Build date: 2020-09-18 17:30:35-0400

=== Xamarin.iOS ===

Version: 14.4.1.3 (Visual Studio Professional)
Hash: e30c41de3
Branch: d16-8
Build date: 2020-10-20 22:18:50-0400

=== Xamarin Designer ===

Version: 16.8.0.495
Hash: 1a7425b8f
Branch: remotes/origin/d16-8
Build date: 2020-10-20 10:51:14 UTC

=== Xamarin.Android ===

Version: 11.1.0.17 (Visual Studio Professional)
Commit: xamarin-android/d16-8/c0e2b8e
Android SDK: /Users/alex.duffell/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/alex.duffell/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:30 UTC

=== Android Device Manager ===

Version: 16.8.0.45
Hash: fc0af5f
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:54 UTC

=== Build Information ===

Release ID: 808002913
Git revision: c6189b3851aed1e1aadbef5807d54bd5bb505e5e
Build date: 2020-11-05 07:07:20-05
Build branch: release-8.8
Xamarin extensions: c6189b3851aed1e1aadbef5807d54bd5bb505e5e

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Mon Aug 31 22:12:52 PDT 2020
    root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

DeepClean 1.2.5
FileNesting 0.1.2
MFractor 4.3.3
Code Coverage 1.0


```

### Example Project (If Possible)

[Path Not Found Test.zip](https://github.com/xamarin/xamarin-macios/files/5546985/PathNotFoudnTest.zip)

This is just a hello world xamarin forms app

**Comment by rolfbjarne** [comment] 2020-11-16 14:57
This looks like a duplicate of #9839, so I'm closing this.

**Closed by rolfbjarne** 2020-11-16 14:57 UTC
