### ISSUE TITLE
Inconsistency between UIDeviceOrientation and UIInterfaceOrientation

### ISSUE THREAD

**Issue by BaseCrusher** [xamarin/xamarin-macios#10314] opened 2020-12-17 22:58 UTC
Hello everyone,

I was jsut working on device orientation in my app when I noticed a small inconsistency between UIDeviceOrientation and UIInterfaceOrientation.

They should both have the same values for each enum but UIInterfaceOrientation does deliver the wrong value. This results in havin code like this:

```
NSNumber nextOrientation;
var deviceOrientation = UIDevice.CurrentDevice.Orientation;
// Picture1
if (deviceOrientation == UIDeviceOrientation.LandscapeLeft || deviceOrientation == UIDeviceOrientation.Portrait)
{
    // Picture2
    nextOrientation = new NSNumber((int)UIInterfaceOrientation.LandscapeRight);
}
else
{
    // Picture3
    nextOrientation = new NSNumber((int)UIInterfaceOrientation.LandscapeLeft);
}
```
Picture1:
![Untitled2](https://user-images.githubusercontent.com/12885003/102553436-21838580-40c3-11eb-9765-d3f98e9dbfaa.png)
Picture2:
![Untitled](https://user-images.githubusercontent.com/12885003/102553435-20eaef00-40c3-11eb-997e-327ae09a185f.png)
Picture3:
![Untitled3](https://user-images.githubusercontent.com/12885003/102553437-21838580-40c3-11eb-9ec2-bc4094035350.png)

### Steps to Reproduce

1.  Well there is not much to reproduce. Just copy paste the code into cs file and see what values UIDeviceOrientation and UIInterfaceOrientation delivers.

### Expected Behavior
UIInterfaceOrientation.Landscape to have the right values.

### Actual Behavior
UIInterfaceOrientation.Landscape has wrong values.

**Comment by BaseCrusher** [comment] 2020-12-17 23:08
Provided a fix in PR.
#10315

**Comment by rolfbjarne** [comment] 2020-12-18 07:27
We're just mirroring what Apple does, this is how it's defined in Apple's headers:

```objective-c
// Note that UIInterfaceOrientationLandscapeLeft is equal to UIDeviceOrientationLandscapeRight (and vice versa).
// This is because rotating the device to the left requires rotating the content to the right.
typedef NS_ENUM(NSInteger, UIInterfaceOrientation) {
    UIInterfaceOrientationUnknown            = UIDeviceOrientationUnknown,
    UIInterfaceOrientationPortrait           = UIDeviceOrientationPortrait,
    UIInterfaceOrientationPortraitUpsideDown = UIDeviceOrientationPortraitUpsideDown,
    UIInterfaceOrientationLandscapeLeft      = UIDeviceOrientationLandscapeRight,
    UIInterfaceOrientationLandscapeRight     = UIDeviceOrientationLandscapeLeft
} API_UNAVAILABLE(tvos);
```

So I'm closing this, since as far as I can tell this is not a bug in our code.

**Closed by rolfbjarne** 2020-12-18 07:27 UTC
