### ISSUE TITLE
Xamarin.Mac not compiling in TFS build server

### ISSUE THREAD

**Issue by arivoir** [xamarin/xamarin-macios#3758] opened 2018-03-15 18:37 UTC
You can find all the details here [323760](https://forums.xamarin.com/discussion/comment/323760).

When the build starts it deletes the output folder content of a referenced project incorrectly, then it fails because it want to get what deleted.

**Comment by dalexsoto** [comment] 2018-03-15 18:54
Closing as a duplicate of issue #3746 

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Mac\Xamarin.Mac.Windows.After.targets(57,3): Warning VSX1000: No Address and User has been specified in order to establish a connection to a Mac Server, so only the main assembly was compiled for project 'C1.Mac.CollectionView'. Connect to a Mac Server and try again to build the full application.

**Closed by dalexsoto** 2018-03-15 18:54 UTC
Labels: macOS
