### ISSUE TITLE
NSURLConnection HttpClient implementation seems to cancel running requests when app moves to background

### ISSUE THREAD

**Issue by leonluc-dev** [xamarin/xamarin-macios#9370] opened 2020-08-13 15:29 UTC
### Steps to Reproduce

1. Set up a HttpClient (with `NSUrlConnection (iOS 7+)` set as the HttpClient implementation in the project settings)
2. Send a post or get request using the http client (preferrably a slow loading url to have time to do step 3)
3. While the request is running, move the app to the background (home button or swipe)

### Expected Behavior
The http request finishes properly in the background

As is the case with the `Managed (default)` and `CFNetwork (iOS 6+)` HttpClient handlers

### Actual Behavior
The http request throws a TaskCanceledException just after the app moves to the background.

```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
  at System.Net.Http.NSUrlSessionHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x001d4] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.20.2.2/src/Xamarin.iOS/Foundation/NSUrlSessionHandler.cs:527 
  at System.Net.Http.HttpClient.FinishSendAsyncBuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x0017e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:506 
  at SessionTestApp.ViewController+<TestHttpBtn_TouchUpInside>d__7.MoveNext () [0x0003b] in C:\Users\appdev\source\repos\SessionTestApp\SessionTestApp\ViewController.cs:29 
```
### Environment

```
Microsoft Visual Studio Professional 2019
Version 16.7.1
VisualStudio.16.Release/16.7.1+30406.217
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

ASP.NET and Web Tools 2019   16.7.532.28833
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2035807+72d099b977d3a85e65fa3b0614ca8cfc803fef02
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.7.532.28833
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.7.532.28833
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.7.532.28833
Azure Functions and Web Jobs Tools

C# Tools   3.7.0-6.20375.2+34202cc2f3e869fd70a26d8237f4552cf9e192cf
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30701.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.79+ge3567815aa.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.7.5 (112c7bc)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62008.03130
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.20702.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.7.0-6.20375.2+34202cc2f3e869fd70a26d8237f4552cf9e192cf
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20361.3+3ef6f0b514198c0bfa6c2c09fefe41a740b024d5
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.7.000.440 (d16-7@358f3c6)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.7.0.495 (remotes/origin/d16-7@79c0c522c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.7.85 (1bcbbdf)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.0.0.3 (d16-7/aca845b)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-7@1f3388a
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f


Xamarin.iOS and Xamarin.Mac SDK   13.20.2.2 (817b6f72a)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```
### Example Project (If Possible)

The example project contains a simple call to `http://slowwly.robertomurray.co.uk/delay/7000/url/{url}` , which delays the response for testing purposes. But the issue occurs with all urls, both HTTP and HTTPS.

[NSUrlSessionTestApp.zip](https://github.com/xamarin/xamarin-macios/files/5069876/NSUrlSessionTestApp.zip)

**Comment by mandel-macaque** [comment] 2020-08-13 21:07
Hello,

This is not an issue but a 'feature' that was added to workaround an issue that was present in the mono runtime. This workaround will be remove as soon as we have a good way to reproduce the fact that it was fixed as per issue https://github.com/xamarin/xamarin-macios/issues/7080

What you are describing is a duplicate of issue https://github.com/xamarin/xamarin-macios/issues/6443 In that issue, please read the following [comment](https://github.com/xamarin/xamarin-macios/issues/6443#issuecomment-509585929).  If you do not want to have this in your requests and you do know that the time of the request will be sort and won't be affected by the OS reclaiming resources I added the following [fix](https://github.com/xamarin/xamarin-macios/issues/6443#issuecomment-509585929).

To workaround it, simply create a NSUrlSessionHandler that set the property BypassBackgroundSessionCheck to true. For example:

```csharp
/ create your own handler instance rather than using the one provided by default.
var handler = new NSUrlSessionHandler() {
  BypassBackgroundSessionCheck = false, // readd the hack
};
var httpClient = new HttpClient (handler); // use the handler with the hack
```

This won't be needed in the next preview of the next stable version of Xamarin.iOS but it is needed in the current stable one as per https://github.com/xamarin/xamarin-macios/pull/8296

**Closed by mandel-macaque** 2020-08-13 21:07 UTC

**Comment by leonluc-dev** [comment] 2020-08-13 21:52
I see. Ill look into the workaround.

The reason this came up is because we had a massive failure of Testflight tests recently. The initialization code of our app does some http requests after startup to check status etc.
But after starting a Testflight app buid for the first time it shows a test info screen to the user (this happens for all tesflight apps distributed through external user. groups). This info screen moves the actual app to the background at the same time its running startup code causing all requests during initialization to fail for every single user.

For the workaround, Is there a way to set a custom handler for iOS (inherited from NSUrlSessionHandler)  at project level like you can for Xamarin.Android? Since the requests in our app are mostly in shared code it would be tedious to pass the httpclient platform specific handler on code level

**Comment by mandel-macaque** [comment] 2020-08-13 22:58
@leonluc-dev use the property and everything should be fine. AFAIK the threadpool was fixed already. New release will have it disabled by default, and we will leave the 'feature' just in case we have issues.
