### ISSUE TITLE
Cannot implicitly convert type 'CoreNFC.INFCIso15693Tag' to 'CoreNFC.INFCNdefTag'. An explicit conversion exists (are you missing a cast?)

### ISSUE THREAD

**Issue by sujeetulli** [xamarin/xamarin-macios#9386] opened 2020-08-17 11:34 UTC
Swift code.
if case let NFCTag.iso15693(tag) = tags.first! {
            session.connect(to: tags.first!) { (error: Error?) in
   
                    tag.readSingleBlock(requestFlags: [.highDataRate, .address], blockNumber:0) { (response:
                        Data, error: Error?) in
                        
                }
            }
        }

How to migrate to Xamarin C#

Here, What I'm trying to do...  
I have NFCTagReaderSessionDelegate and NFC tag type is iso15693...
Now I'm trying to get the payload of this tag... I'm unable to get it...
 How can I get the payload of this tag? 

### Steps to Reproduce

1. 
2. 
3. 

### Environment

```
```

**Comment by whitneyschmidt** [comment] 2020-08-17 15:40
@sujeetulli Thank you for your feedback!

For us to investigate this further, could you please provide your full build logs, a test case showing how you are getting the payload of the tag in C#, and all your version information.

**The most useful information you can provide at this point is a sample project demonstrating your use case.**

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

We look forward to hearing from you!

**Comment by spouliot** [comment] 2020-08-17 18:39
Sounds like a dupe of https://github.com/xamarin/xamarin-macios/issues/9159

**Comment by whitneyschmidt** [comment] 2020-08-17 18:51
@sujeetulli It's likely that this is a dupe of the issue @spouliot linked. If that is the case, then there is a fix available in our [first preview](https://docs.microsoft.com/en-us/xamarin/ios/release-notes/13/13.99) of Xcode 12.

**Comment by whitneyschmidt** [comment] 2020-08-27 19:37
@sujeetulli Have you been able try out the conversion with the Xcode 12 preview?

If you're still running into this, we will need a small sample project that reproduces the issue to begin investigating.

**Comment by rolfbjarne** [comment] 2020-09-15 10:57
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!

**Closed by rolfbjarne** 2020-09-15 10:57 UTC
Labels: need-info, support

**Comment by sujeetulli** [comment] 2020-09-16 21:15
@whitneyschmidt  @rolfbjarne, The Xcode 12 is in beta version, So I haven't tested. I'll get back you with the result once it will be an official public release.
