### ISSUE TITLE
VS paired to MAC cant build ios project

### ISSUE THREAD

**Issue by scriptBoris** [xamarin/xamarin-macios#18432] opened 2023-06-10 08:17 UTC
### Steps to Reproduce

1. download sample [MauiSampleErrorMac.zip](https://github.com/xamarin/xamarin-macios/files/11711942/MauiSampleErrorMac.zip)
2. open project in VS2022 windows
3. pair VS2022 with mac
4. try build or debug

### Expected Behavior
For iOS Build successful

### Actual Behavior
For iOS Build Error ❌
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7060\targets\Xamarin.Shared.Sdk.targets(2021,3): error : MessagingRemoteException: An error occurred on client Build1647060 while executing a reply for topic xvs/build/16.4.7060/execute-task/MauiSampleErrorMac/154ea72002fGetFileSystemEntries
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7060\targets\Xamarin.Shared.Sdk.targets(2021,3): error : DirectoryNotFoundException: Could not find a part of the path '/Users/dev/Library/Caches/Xamarin/mtbs/builds/MauiSampleErrorMac/154ea727715ad8d3a420b9195f49158d6e636d2c5ae56fce23c394fc5633cc5e/C:/Ngt/xamarin.firebase.ios.core/8.10.0.3/lib/net6.0-ios15.4/Firebase.Core.resources'.
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7060\targets\Xamarin.Shared.Sdk.targets(2021,3): error :

For Android Build success 👍

### Environment
VS2022 windows 17.6.2
VS2022 mac 17.5.6 (build3)
Xcode 14.3 (14E222b)
MacOS 13.3.1
Windows 11 22H2 (22621.1778)

### Build Logs
[MauiSampleErrorMac_Debug_AnyCPU_Build_2023-06-10T14_12_34.6108937+06_00.zip](https://github.com/xamarin/xamarin-macios/files/11711960/MauiSampleErrorMac_Debug_AnyCPU_Build_2023-06-10T14_12_34.6108937%2B06_00.zip)

### Example Project (If Possible)
sample [MauiSampleErrorMac.zip](https://github.com/xamarin/xamarin-macios/files/11711942/MauiSampleErrorMac.zip)

P.S. Deleting the XML SessionId="$(BuildSessionId)", in Xamarin.Shared.Sdk.targets, parameter does not help

**Comment by scriptBoris** [comment] 2023-06-12 17:57
@rolfbjarne I want to ask a counter question: have you tried to reproduce the error yourself? In this issue, I described the error playback instruction.

I don't want to sound rude, but this critical error is more than a month old. I have already tried many ways to solve this error, and no, restarting the sun did NOT solve the error

😒

**Comment by rolfbjarne** [comment] 2023-06-13 12:52
> have you tried to reproduce the error yourself? In this issue, I described the error playback instruction.

Yes, I've tried, and I can reproduce the error before changing `Xamarin.Shared.Sdk.targets`, but not after.

Can you try editing `Xamarin.Shared.Sdk.targets` again, completely removing the `_CopyLocalBindingResources` target, and see if that works?

Also please make sure to edit the correct file, you may have multiple versions of the file on your system. The correct one to edit is the one that's listed in your error message:

> C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7060\targets\Xamarin.Shared.Sdk.targets

**Comment by scriptBoris** [comment] 2023-06-14 10:52
@rolfbjarne I updated visual studio windows to version 17.6.3 and now the error looks like this:
```
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018: непредвиденная ошибка при выполнении задачи "ResolveNativeReferences".
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018: System.AggregateException: Произошла одна или несколько ошибок. ---> System.ComponentModel.Win32Exception: Не удается найти указанный файл
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    в System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    в Xamarin.Utils.Execution.<>c__DisplayClass24_1.<RunAsync>b__0() в /Users/builder/azdo/_work/1/s/xamarin-macios/tools/common/Execution.cs:строка 103
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018: --- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    в Xamarin.MacDev.Tasks.XamarinTask.<ExecuteAsync>d__24.MoveNext() в /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinTask.cs:строка 120
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    --- Конец трассировки внутреннего стека исключений ---
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    в System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    в System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    в System.Threading.Tasks.Task.Wait()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    в Xamarin.MacDev.Tasks.ResolveNativeReferencesBase.ProcessSidecar(ITaskItem r, String resources, List`1 native_frameworks) в /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs:строка 133
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    в Xamarin.MacDev.Tasks.ResolveNativeReferencesBase.Execute() в /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/ResolveNativeReferencesBase.cs:строка 104
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    в Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    в Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018: ---> (Внутреннее исключение #0) System.ComponentModel.Win32Exception (0x80004005): Не удается найти указанный файл
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    в System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    в Xamarin.Utils.Execution.<>c__DisplayClass24_1.<RunAsync>b__0() в /Users/builder/azdo/_work/1/s/xamarin-macios/tools/common/Execution.cs:строка 103
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018: --- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:    в Xamarin.MacDev.Tasks.XamarinTask.<ExecuteAsync>d__24.MoveNext() в /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks/Tasks/XamarinTask.cs:строка 120<---
1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error MSB4018:
```
If I open the file Xamarin.Shared.targets, I can't find the block:
```
<GetFileSystemEntries
        SessionId="$(BuildSessionId)"
	DirectoryPath="@(_BindingPackagesFromReferencedAssembliesDirectoriesExists)"
	Pattern="*"
	Recursive="true"
	IncludeDirectories="false"
	>
	<Output TaskParameter="Entries" ItemName="_BindingPackagesFromReferencedAssemblies" />
</GetFileSystemEntries>
```

**Comment by rolfbjarne** [comment] 2023-06-14 11:09
@scriptBoris could you get a binlog for that error?

**Comment by Kebechet** [comment] 2023-06-21 11:04
I can reproduce the error from his MAUI sample and after running:
logs:
[MSBuildReproLogs.zip](https://github.com/xamarin/xamarin-macios/files/11816748/MSBuildReproLogs.zip)

**Comment by scriptBoris** [comment] 2023-06-21 15:30
The Visual Studio Windows 17.6.4 update came out, I downloaded the update. The error has not disappeared 😒

**Comment by rolfbjarne** [comment] 2023-06-21 16:04
> The Visual Studio Windows 17.6.4 update came out, I downloaded the update. The error has not disappeared 😒

That makes sense: if the workaround for #18308 didn't work for you, then you're running into something else, which hasn't been fixed, because we haven't figured out what's going on yet.

**Comment by rolfbjarne** [comment] 2023-06-21 16:11
@Kebechet 

> I can reproduce the error from his MAUI sample. logs: [MSBuildReproLogs.zip](https://github.com/xamarin/xamarin-macios/files/11816748/MSBuildReproLogs.zip)

That's a different issue (the error occurs in the DetectSdkLocations task and not GetFileSystemEntries task, which is what this issue is about) - could you please file a new issue here (like this: https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022), and we'll have a look (feel free to post the link here so that we can make sure it reaches the right people).

**Comment by rolfbjarne** [comment] 2023-06-21 16:13
Marked as `need-info` since we're still waiting for the binlogs from the previous comment (https://github.com/xamarin/xamarin-macios/issues/18432#issuecomment-1590984922).

**Closed** 2023-06-28 17:01 UTC
Labels: need-info
