### ISSUE TITLE
Live Run fails with PackageReference

### ISSUE THREAD

**Issue by breyed** [xamarin/xamarin-macios#3178] opened 2018-01-08 14:39 UTC
### Description

When a Xamarin iOS project uses `PackageReference` to reference an assembly, a normal build works, but Live Run does not. The ability to use `PackageReference` is important because it is needed to avoid bugs with referencing .NET Standard libraries. It also makes NuGet dependency management much easier.

### Steps to Reproduce

1.  Create a new Xamarin.Forms project.
2.  In the iOS project, convert it from the old NuGet style to using a single `PackageReference` element in the iOS .csproj:

```` xml
    <PackageReference Include="Xamarin.Forms" Version="2.5.0.121934" />
````
3. Add this line to AppDelegate.cs:
```` cs
    [assembly: Preserve(AllMembers = true), XamlCompilation(XamlCompilationOptions.Compile)]
````
4. Attempt to debug the project using Live Run.

### Expected Behavior
You can run the app with Live Run.

### Actual Behavior
The Live Run fails with "The type or namespace name 'XamlCompilationAttribute' could not be found".

### Environment

[Visual studio installed products](https://gist.github.com/breyed/f66145df3af9588a3c55dd0af7b939e0)

**Comment by jamesmontemagno** [comment] 2018-01-08 19:07
Can you let me know what version of the live player you are running (in the app under about).

The latest TestFlight version of the live player support this scenario: https://developer.xamarin.com/guides/cross-platform/live/install/#Xamarin_Live_Player_for_iOS

**Comment by mandel-macaque** [comment] 2018-01-09 12:24
Setting the lables to need-info until @breyed checks the version provided by @jamesmontemagno

**Comment by breyed** [comment] 2018-01-09 14:24
I was on the latest App Store version of Live Player. After updating to TestFlight version 1.4.129 (629), the build seemed to get further. Now the build fails with these errors:

1. The type or namespace name 'BigInteger' could not be found. [This is from System.Numerics.BigInteger in .nuget\packages\netstandard.library\2.0.1\build\netstandard2.0\ref\netstandard.dll.]

2. System.IO.DirectoryNotFoundException: Could not find a part of the path "/var/mobile/Containers/Data/Application/8CD57878-838F-4004-87F9-2FF838CDE126/Documents/.nuget/packages/sqlitepclraw.provider.sqlite3.ios_unified/1.1.8/lib/Xamarin.iOS10/SQLitePCLRaw.provider.sqlite3.dll".

**Comment by jamesmontemagno** [comment] 2018-01-10 04:15
I think we may have fixed this today actually. Is there another project that has the nuget in it?

Do you have a small repro that we can test out?

**Comment by breyed** [comment] 2018-01-10 14:02
> Is there another project that has the nuget in it?

In my production project, the Xamarin iOS references a .NET Standard class library, which references another .NET Standard class library. So yes, there are two projects referencing the netstandard NuGet.

> Do you have a small repro that we can test out?

I created a [branch](https://github.com/breyed/xamarin-macios-netstandard-build-crash/tree/live-player) from a previous repro I had put together. It has an IOS project, which references a .NET Standard lib, which references another .NET Standard lib. One of the class libraries references Protocol buffers. The IOS projects instantiates objects in the class libraries from `FinishedLaunching`.

I couldn't get the branch to cause the build error. However, it fails at runtime, so it may be a clue:
````
NInterpret.NInterpretException: Assembly `Google.Protobuf` is not loaded
````

Also of note is that most of the time the except message isn't displayed. Instead, I see:
````
NInterpret.NInterpretException: <Timeout exceeded getting exception details>
````

**Comment by mandel-macaque** [comment] 2018-01-15 11:35
@jamesmontemagno any comments? This does not look like a XI bug, so we should close the issue and track it in the right project.

**Comment by jamesmontemagno** [comment] 2018-01-16 22:02
We can no longer reproduce the issue with XAMLCompilation, so I assume one is already fixed. Going to test out the other project now.

**Comment by jamesmontemagno** [comment] 2018-01-16 22:24
@breyed are you doing this in VS for Mac or VS 2017?

When I run your project I get a build issue:

/Users/jamesmontemagno/Downloads/xamarin-macios-netstandard-build-crash-live-player/ClassLibrary1/ClassLibrary1.csproj(5,5): Error MSB3073: The command "/Users/jamesmontemagno/.nuget/packages/Google.Protobuf.Tools/3.5.1/tools/windows_x64/protoc --proto_path=. --csharp_out=obj Test.proto" exited with code 127. (MSB3073) (ClassLibrary1)

**Comment by jamesmontemagno** [comment] 2018-01-17 00:02
We validated the BigInteger issue and have it fixed pending a new release of the app

**Comment by breyed** [comment] 2018-01-17 12:54
The build issue you're seeing is because the Protobuf code generation MSBuild target is Windows-specific, and you're running the build on the Mac. In my production workflow, all the projects (including database, web, and mobile projects) are built on Windows, except for iOS which uses the Mac agent. In intended the repro to be similar, where the .NET Standard DLL is built on Windows and the iOS project build using the Mac agent.

**Comment by jamesmontemagno** [comment] 2018-01-17 16:42
Thanks for the additional information.

Seems like we are tracking multiple things here.

1. XAMLCompilation flag causes issues -> Verified Fixed
2. Issue with BigInteger in .NET Standard Library -> Fixed (pending release)
3. SQLite-NET PCL Issue -> Being tracked and worked on
4. Issue with protobuf NuGet -> Being tracked

**Comment by darharel** [comment] 2018-06-20 09:49
Hey @jamesmontemagno ,

is there any news about the SQLite-net-pcl Issue with the xamarin live? 
if still not, how long do you think it will take for it to work properly? 

by the way, you are all doing great job on developing our platforms! 
Thanks alot!

**Comment by hsnsalhi** [comment] 2018-07-16 22:05
+1

**Comment by rolfbjarne** [comment] 2022-09-22 19:46
Closing since Live Run no longer exists.

**Closed by rolfbjarne** 2022-09-22 19:46 UTC
Labels: bug, iOS, external-live-run
