### ISSUE TITLE
File provider UI Extension for Mac: Unable to trigger prepare method for authentication or custom action

### ISSUE THREAD

**Issue by harshitgindra** [xamarin/xamarin-macios#15493] opened 2022-07-13 21:56 UTC
### Steps to Reproduce

1. Build the project and run the app. It should register a domain `XamarinMacFileProviderExample`
2. Go to the `XamarinMacFileProviderExample` cloud storage domain in Finder. There should  be a sign in button on the top right of `Finder` window
3.  Upon clicking on the sign in button, the UI or the alert is not prompted. Console shows the logs attached to the issue
4. Right click in the `XamarinMacFileProviderExample` folder, a `Custom Action` button should appear in menu. On clicking the button, nothing happens the `prepare` method in the view controller is not triggered. Logs attached below in the ticket

### Expected Behavior
On clicking the `sign in` or `Custom action` button, a prompt should be displayed on the screen and `DocumentActionViewController` class `prepare` method should be invoked

### Actual Behavior
No prompts and the prepare method is not invoked.

When I look at the console for logs, I see the following logs from `Finder` process
```
FP Custom action sheet finished with error Error Domain=com.apple.ViewBridge Code=14 "(null)" UserInfo={com.apple.ViewBridge.error.hint={
    callStackSymbols =     (
        "0   CoreFoundation                      __exceptionPreprocess + 242",
        "1   libobjc.A.dylib                     objc_exception_throw + 48",
        "2   Foundation                          -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 267",
        "3   FileProviderUI                      -[FPUIActionExtensionContainerViewController _configureWithDomainIdentifier:] + 170",
        "4   FileProviderUI                      -[FPUIActionExtensionContainerViewController awakeFromRemoteView] + 851",
        "5   ViewBridge                          -[NSViewServiceMarshal _bootstrap:replyData:completion:] + 2235",
        "6   ViewBridge                          -[NSViewServiceMarshal bootstrap:withReply:] + 245",
        "7   CoreFoundation                      __invoking___ + 140",
        "8   CoreFoundation                      -[NSInvocation invoke] + 305",
        "9   CoreFoundation                      -[NSInvocation invokeWithTarget:] + 70",
        "10  ViewBridge                          -[NSVB_ViewServiceImplicitAnimationDecodingProxy forwardInvocation:] + 85",
        "11  CoreFoundation                      ___forwarding___ + 751",
        "12  CoreFoundation                      _CF_forwarding_prep_0 + 120",
        "13  CoreFoundation                      __invoking___ + 140",
        "14  CoreFoundation                      -[NSInvocation invoke] + 305",
        "15  CoreFoundation                      -[NSInvocation invokeWithTarget:] + 70",
        "16  ViewBridge                          -[NSVB_QueueingProxy forwardInvocation:] + 321",
        "17  CoreFoundation                      ___forwarding___ + 751",
        "18  CoreFoundation                      _CF_forwarding_prep_0 + 120",
        "19  CoreFoundation                      __invoking___ + 140",
        "20  CoreFoundation                      -[NSInvocation invoke] + 305",
        "21  CoreFoundation                      -[NSInvocation invokeWithTarget:] + 70",
        "22  CoreFoundation                      ___forwarding___ + 751",
        "23  CoreFoundation                      _CF_forwarding_prep_0 + 120",
        "24  CoreFoundation                      __invoking___ + 140",
        "25  CoreFoundation                      -[NSInvocation invoke] + 305",
        "26  ViewBridge                          __deferNSXPCInvocationOntoMainThread_block_invoke + 228",
        "27  ViewBridge                          __wrapBlockWithVoucher_block_invoke + 37",
        "28  ViewBridge                          __deferBlockOntoMainThread_block_invoke_2 + 274",
        "29  CoreFoundation                      __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12",
        "30  CoreFoundation                      __CFRunLoopDoBlocks + 445",
        "31  CoreFoundation                      __CFRunLoopRun + 2609",
        "32  CoreFoundation                      CFRunLoopRunSpecific + 562",
        "33  HIToolbox                           RunCurrentEventLoopInMode + 292",
        "34  HIToolbox                           ReceiveNextEventCommon + 594",
        "35  HIToolbox                           _BlockUntilNextEventMatchingListInModeWithFilter + 70",
        "36  AppKit                              _DPSNextEvent + 927",
        "37  AppKit                              -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394",
        "38  ViewBridge                          __75-[NSViewServiceApplication nextEventMatchingMask:untilDate:inMode:dequeue:]_block_invoke + 111",
        "39  ViewBridge                          -[NSViewServiceApplication _withToxicEventMonitorPerform:] + 114",
        "40  ViewBridge                          -[NSViewServiceApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 151",
        "41  AppKit                              -[NSApplication run] + 586",
        "42  AppKit                              NSApplicationMain + 817",
        "43  libxpc.dylib                        _xpc_objc_main + 867",
        "44  libxpc.dylib                        xpc_main + 99",
        "45  Foundation                          +[NSXPCListener serviceListener] + 0",
        "46  PlugInKit                           __PLUGINKIT_CALLING_OUT_TO_CLIENT_SUBSYSTEM_FOR_BEGINUSING__ + 38962",
        "47  PlugInKit                           __PLUGINKIT_CALLING_OUT_TO_CLIENT_SUBSYSTEM_FOR_BEGINUSING__ + 38072",
        "48  PlugInKit                           __PLUGINKIT_CALLING_OUT_TO_CLIENT_SUBSYSTEM_FOR_BEGINUSING__ + 39937",
        "49  ExtensionFoundation                 EXExtensionMain + 284",
        "50  Foundation                          NSExtensionMain + 240",
        "51  MyFileProviderUiExtension           xamarin_main + 1107",
        "52  MyFileProviderUiExtension           xamarin_mac_extension_main + 32",
        "53  dyld                                start + 462"
    );
    name = NSInternalInconsistencyException;
    reason = "attempting to send message to non-existent action extension view controller";
}, com.apple.ViewBridge.error.description=NSViewBridgeServiceBootstrapError}



FP Custom action sheet failed to load with error Error Domain=com.apple.ViewBridge Code=14 "(null)" UserInfo={com.apple.ViewBridge.error.hint={
    callStackSymbols =     (
        "0   CoreFoundation                      __exceptionPreprocess + 242",
        "1   libobjc.A.dylib                     objc_exception_throw + 48",
        "2   Foundation                          -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 267",
        "3   FileProviderUI                      -[FPUIActionExtensionContainerViewController _configureWithDomainIdentifier:] + 170",
        "4   FileProviderUI                      -[FPUIActionExtensionContainerViewController awakeFromRemoteView] + 851",
        "5   ViewBridge                          -[NSViewServiceMarshal _bootstrap:replyData:completion:] + 2235",
        "6   ViewBridge                          -[NSViewServiceMarshal bootstrap:withReply:] + 245",
        "7   CoreFoundation                      __invoking___ + 140",
        "8   CoreFoundation                      -[NSInvocation invoke] + 305",
        "9   CoreFoundation                      -[NSInvocation invokeWithTarget:] + 70",
        "10  ViewBridge                          -[NSVB_ViewServiceImplicitAnimationDecodingProxy forwardInvocation:] + 85",
        "11  CoreFoundation                      ___forwarding___ + 751",
        "12  CoreFoundation                      _CF_forwarding_prep_0 + 120",
        "13  CoreFoundation                      __invoking___ + 140",
        "14  CoreFoundation                      -[NSInvocation invoke] + 305",
        "15  CoreFoundation                      -[NSInvocation invokeWithTarget:] + 70",
        "16  ViewBridge                          -[NSVB_QueueingProxy forwardInvocation:] + 321",
        "17  CoreFoundation                      ___forwarding___ + 751",
        "18  CoreFoundation                      _CF_forwarding_prep_0 + 120",
        "19  CoreFoundation                      __invoking___ + 140",
        "20  CoreFoundation                      -[NSInvocation invoke] + 305",
        "21  CoreFoundation                      -[NSInvocation invokeWithTarget:] + 70",
        "22  CoreFoundation                      ___forwarding___ + 751",
        "23  CoreFoundation                      _CF_forwarding_prep_0 + 120",
        "24  CoreFoundation                      __invoking___ + 140",
        "25  CoreFoundation                      -[NSInvocation invoke] + 305",
        "26  ViewBridge                          __deferNSXPCInvocationOntoMainThread_block_invoke + 228",
        "27  ViewBridge                          __wrapBlockWithVoucher_block_invoke + 37",
        "28  ViewBridge                          __deferBlockOntoMainThread_block_invoke_2 + 274",
        "29  CoreFoundation                      __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12",
        "30  CoreFoundation                      __CFRunLoopDoBlocks + 445",
        "31  CoreFoundation                      __CFRunLoopRun + 2609",
        "32  CoreFoundation                      CFRunLoopRunSpecific + 562",
        "33  HIToolbox                           RunCurrentEventLoopInMode + 292",
        "34  HIToolbox                           ReceiveNextEventCommon + 594",
        "35  HIToolbox                           _BlockUntilNextEventMatchingListInModeWithFilter + 70",
        "36  AppKit                              _DPSNextEvent + 927",
        "37  AppKit                              -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394",
        "38  ViewBridge                          __75-[NSViewServiceApplication nextEventMatchingMask:untilDate:inMode:dequeue:]_block_invoke + 111",
        "39  ViewBridge                          -[NSViewServiceApplication _withToxicEventMonitorPerform:] + 114",
        "40  ViewBridge                          -[NSViewServiceApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 151",
        "41  AppKit                              -[NSApplication run] + 586",
        "42  AppKit                              NSApplicationMain + 817",
        "43  libxpc.dylib                        _xpc_objc_main + 867",
        "44  libxpc.dylib                        xpc_main + 99",
        "45  Foundation                          +[NSXPCListener serviceListener] + 0",
        "46  PlugInKit                           __PLUGINKIT_CALLING_OUT_TO_CLIENT_SUBSYSTEM_FOR_BEGINUSING__ + 38962",
        "47  PlugInKit                           __PLUGINKIT_CALLING_OUT_TO_CLIENT_SUBSYSTEM_FOR_BEGINUSING__ + 38072",
        "48  PlugInKit                           __PLUGINKIT_CALLING_OUT_TO_CLIENT_SUBSYSTEM_FOR_BEGINUSING__ + 39937",
        "49  ExtensionFoundation                 EXExtensionMain + 284",
        "50  Foundation                          NSExtensionMain + 240",
        "51  MyFileProviderUiExtension           xamarin_main + 1107",
        "52  MyFileProviderUiExtension           xamarin_mac_extension_main + 32",
        "53  dyld                                start + 462"
    );
    name = NSInternalInconsistencyException;
    reason = "attempting to send message to non-existent action extension view controller";
}, com.apple.ViewBridge.error.description=NSViewBridgeServiceBootstrapError}

```
### Environment

<details>
<summary>Version information</summary>

```
Building XamarinMacFileProviderExample (Debug)
Build started 7/13/2022 3:16:34 PM.
Environment at start of build:
MSBUILDPROJECTROOTELEMENTCACHESIZE = 200
ServiceHubLogSessionKey        = BED975C4
DOTNET_MSBUILD_SDK_RESOLVER_CLI_DIR = /usr/local/share/dotnet
__CF_USER_TEXT_ENCODING        = 0x1F5:0x0:0x0
USER                           = chief
PKG_CONFIG_PATH                = /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/pkgconfig
XPC_FLAGS                      = 0x0
MONO_GC_PARAMS                 = nursery-size=64m
LD_LIBRARY_PATH                = /Library/Frameworks/Mono.framework/Versions/6.12.0/lib:
TMPDIR                         = /var/folders/7m/933f7cx94sz9r1xkprsgt1f00000gn/T/
COMPlus_EnableCrashReport      = 1
COMPlus_DbgEnableMiniDump      = 0
LaunchInstanceID               = 34C2528D-583B-4D74-8350-19AB803CCF55
COMPlus_DbgEnableFastHeapDumps = 1
XPC_SERVICE_NAME               = application.com.microsoft.visual-studio.25988313.25988891
HOME                           = /Users/chief
ServiceHubUniqueLogDir         = vsmac
COMMAND_MODE                   = unix2003
__CFBundleIdentifier           = com.microsoft.visual-studio
PATH                           = /Library/Frameworks/Mono.framework/Commands:/Applications/Visual Studio.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/usr/local/bin:~/.dotnet/tools:/usr/local/share/dotnet
MSBUILD_EXE_PATH               = /Users/chief/Library/Caches/VisualStudio/17.0/MSBuild/2210_3/MonoDevelop.MSBuildBuilder.exe
DYLD_BIND_AT_LAUNCH            = 1
SECURITYSESSIONID              = 186a7
SSH_AUTH_SOCK                  = /private/tmp/com.apple.launchd.1Rr2itz6Wl/Listeners
SHELL                          = /bin/zsh
COMPlus_EnableDumpOnSigTerm    = 1
GTKSHARP_SLIM_STARTUP          = yes
LOGNAME                        = chief

```
[build-logs.txt](https://github.com/xamarin/xamarin-macios/files/9106465/build-logs.txt)

</details>

### Build Logs
[console-logs.txt](https://github.com/xamarin/xamarin-macios/files/9106470/console-logs.txt)
### Example Project (If Possible)

1. Code available [here](https://github.com/harshitgindra/XamarinMacFileProviderExample) to reproduce the issue

**Comment by chamons** [comment] 2022-07-18 20:45
I took a look at the sample, and ran the following steps:

- Launch XamarinMacFileProviderExample
- 
![image](https://user-images.githubusercontent.com/6392201/179614104-8eeb1f02-9465-42f9-9c8b-b86ca0d2f188.png)
- Open Finder
- Enter
- 
![image](https://user-images.githubusercontent.com/6392201/179614124-aaf73c47-34ec-46ec-9805-8a3e8cbc7130.png)
- Enable Plugin
- I then get Loading... for a long period of time:
- 
![image](https://user-images.githubusercontent.com/6392201/179614177-e25db3a7-4833-451a-9c39-5cc87eadc2a3.png)

Given the description of the bug, it sounds like I should have gotten a UI that should then fail with interacted with, is that correct?

**Comment by harshitgindra** [comment] 2022-07-18 20:57
Hi Chris, I haven't implemented the flow to fetch the contents. When you run the app, a sign in button appears on the top right of the Finder window
<img width="970" alt="Screenshot 2022-07-18 at 1 51 29 PM" src="https://user-images.githubusercontent.com/9598218/179615626-a30b8d10-80ad-41aa-8834-2ecb130583b1.png">

Another way to verify the behavior is by right clicking in the finder(screenshot below)
<img width="981" alt="Screenshot 2022-07-18 at 1 51 37 PM" src="https://user-images.githubusercontent.com/9598218/179615761-71c99f96-df82-4d35-b4bf-f3661d4ea69c.png">

Clicking on either of the two buttons gives same result. 
I hope this helps.

**Comment by harshitgindra** [comment] 2022-07-18 21:42
Yeah, I plan to implement the feature once I can figure out why the app is unable to trigger and communicate with file provider ui extension.

**Comment by chamons** [comment] 2022-07-19 14:42
After some investigation I believe the problem is that your sample does not call any of the completion handlers passed to it, as the API expects.

See https://github.com/harshitgindra/XamarinMacFileProviderExample/pull/1 for a partial solution that moves the error further. As it became clear that this was currently a "using the API wrong" not necessarily a "the binding is buggy", it became out of scope for an issue. But between that PR and the [sample project](https://github.com/peterthomashorn/macosfileproviderexample) linked you should be able to hash things out.

In the event that you have a fully ported sample and after significant debugging believe that it is now an SDK bug, please open a new issue with the corrected sample project.

**Closed by chamons** 2022-07-19 14:42 UTC
Labels: need-attention
