### ISSUE TITLE
[dotnet] LinkSdk.LinkSdkRegressionTest.SpecialFolder fails on tvOS

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#12640] opened 2021-09-07 10:22 UTC
Failure:

    LinkSdk.LinkSdkRegressionTest
        [FAIL] SpecialFolder :   /Users/builder/Library/Developer/CoreSimulator/Devices/76C018EB-3C82-46A5-BC38-B374E8ECABC6/data/Containers/Data/Application/57C91DB9-18F2-4B24-B112-B9BB7DC530ED/Library/Caches/Documents/.fonts
            Expected: True
            But was:  False
                at LinkSdk.LinkSdkRegressionTest.TestFolder (System.Environment+SpecialFolder folder, System.Boolean supported, System.Nullable`1[T] exists, System.Boolean readOnly) [0x00058] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/linker/ios/link sdk/LinkSdkRegressionTest.cs:851 
                at LinkSdk.LinkSdkRegressionTest.SpecialFolder () [0x0027c] in /Users/builder/azdo/_work/1/s/xamarin-macios/tests/linker/ios/link sdk/LinkSdkRegressionTest.cs:952 

Ref: https://github.com/xamarin/xamarin-macios/pull/12571#commitcomment-56023692

This was caused by: https://github.com/dotnet/runtime/commit/8da82f23adea445dd9d75a0ee5575fdae3cd8b8d

**Comment by rolfbjarne** [comment] 2021-09-07 10:29
This happens in the RC 1 branch as well: https://github.com/xamarin/xamarin-macios/pull/12633#issuecomment-914188584

**Comment by filipnavara** [comment] 2021-09-07 11:00
I would have expected it to be related to https://github.com/dotnet/runtime/commit/8da82f23adea445dd9d75a0ee5575fdae3cd8b8d (and other tvOS fixes made there). I will look into it.

**Comment by rolfbjarne** [comment] 2021-09-07 11:39
> I would have expected it to be related to [dotnet/runtime@8da82f2](https://github.com/dotnet/runtime/commit/8da82f23adea445dd9d75a0ee5575fdae3cd8b8d) (and other tvOS fixes made there). I will look into it.

It was a copy-paste mistake on my part, I meant to paste the commit you mention.

**Comment by spouliot** [comment] 2021-09-07 13:21
The _latest_ (after the committed fixes) failures did not happen locally, even after I reseted the simulator (and a `git clean`). Some state on the bot's simulator might have _permanently_ changed :(

**Comment by rolfbjarne** [comment] 2021-09-07 13:25
Yes, I'm having trouble reproducing this locally as well 😒

**Comment by filipnavara** [comment] 2021-09-07 15:11
I was not able to reproduce it locally either (on clean tvOS 15 Simulator).

**Comment by rolfbjarne** [comment] 2021-09-07 15:23
Doesn't fail in the RC 1 branch either.

**Comment by spouliot** [comment] 2021-09-07 15:24
hmm... pretty sure one of the rc.1 builds did (after my fix)
but I need to check if I backported the last fix on `main` or if I waited for rc1 to confirm it was fine

**Comment by filipnavara** [comment] 2021-09-08 05:04
I can actually reproduce it now. The failing tests are the non-dotnet ones and it fails only if the dotnet ones were not run first. The dotnet ones create all the necessary directories and then the legacy ones already see them as existing.

**Comment by filipnavara** [comment] 2021-09-08 07:45
Would it make sense to relax the test to change `exist` to imply that the folder MUST exists but not the opposite? (Or, alternatively, do it only for tvOS)

**Comment by rolfbjarne** [comment] 2021-09-08 10:20
> I can actually reproduce it now. The failing tests are the non-dotnet ones and it fails only if the dotnet ones were not run first.
> 
> The order of running the tests is important:
> 
> * If dotnet ones run first they create all the necessary directories and then the legacy ones already see them as existing.
> * If non-dotnet ones run first they assert the existence of `.fonts` directory that does not exist.

That explains a lot! Thanks for looking into this.

> Would it make sense to relax the test to change `exist` to imply that the folder MUST exists but not the opposite? (Or, alternatively, do it only for tvOS)

I think your PR works fine, basically not specify whether the folder must exist or not for tvOS, so it works either way.

**Comment by spouliot** [comment] 2021-09-14 13:09
Failure still happens on bots :(

**Comment by spouliot** [comment] 2021-09-15 13:35
This issue is not (totally?) solved and still occurs on bot's PR

**Closed** 2021-09-16 13:36 UTC
Labels: dotnet, tests
