### ISSUE TITLE
[net7-rc2] `Unable to find package Microsoft.NETCore.App.Runtime.linux-bionic-x64 with version (= 6.0.10)`

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-macios#16401] opened 2022-10-20 16:05 UTC
### Steps to Reproduce

I'm opening this issue in this repository because it seems related to the restore graph generation in `net6.0-macos`.

I'm also not sure about the repro steps, but here we go:

1. Install net7.0-rc2 with all workloads (including macos)
1. `dotnet new install Uno.ProjectTemplates.Dotnet`
1. `dotnet new unoapp -o testapp`
1. `cd testapp\testapp.Mobile`
1. `dotnet build -f net6.0-android -c Release -p:RuntimeIdentifier=android-x64`

(Android is on purpose here, because that's how the issue seems to happen, but it may not be the trigger)

### Expected Behavior

Compilation succeeds.

### Actual Behavior

```
/Users/runner/work/1/s/src/SamplesApp/SamplesApp.netcoremobile/SamplesApp.netcoremobile.csproj error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.linux-bionic-x64 with version (= 6.0.10)
  - Found 5 version(s) in NuGet official package source [ Nearest version: 7.0.0-preview.5.22301.12 ]
  - Found 0 version(s) in Solution Packages
  - Found 0 version(s) in platform.uno dev [/Users/runner/work/1/s/src/SamplesApp/SamplesApp.netcoremobile/SamplesApp.netcoremobile.csproj]
```

### Environment

```
dotnet --version
7.0.100-rc.2.22477.23
dotnet workload list
```

```
Installed Workload Id      Manifest Version                         Installation Source
---------------------------------------------------------------------------------------
macos                      12.3.1186-rc.2/7.0.100-rc.2              SDK 7.0.100-rc.2
ios                        16.0.1271-rc.2-xcode14/7.0.100-rc.2      VS 17.4.33015.44
maui-android               7.0.0-rc.2.6866/7.0.100-rc.2             VS 17.4.33015.44
maui-windows               7.0.0-rc.2.6866/7.0.100-rc.2             VS 17.4.33015.44
maui-maccatalyst           7.0.0-rc.2.6866/7.0.100-rc.2             VS 17.4.33015.44
android                    33.0.0-rc.2.202/7.0.100-rc.2             VS 17.4.33015.44
maccatalyst                15.4.1186-rc.2/7.0.100-rc.2              VS 17.4.33015.44
maui-ios                   7.0.0-rc.2.6866/7.0.100-rc.2             VS 17.4.33015.44
```

### Build Logs
[android-netcoremobile-sampleapp.zip](https://github.com/xamarin/xamarin-macios/files/9831855/android-netcoremobile-sampleapp.zip)

**Comment by rolfbjarne** [comment] 2022-10-20 16:07
Did you get a binlog for this issue?

**Comment by jeromelaban** [comment] 2022-10-20 16:59
Heh ;) Yes it's Uno's sample app build logs.

As an update, if I remove `net6.0-macos` from the `TargetFramework` list, the nuget restore graph is generated properly.

**Comment by rolfbjarne** [comment] 2022-10-24 09:53
@jeromelaban I believe this issue will "fix" itself once the package it's complaining about is released.

That doesn't mean there's an issue here (it's certainly weird - and kind of amusing... - that it's complaining about a linux package when building for android, but only when macOS is among the target frameworks).

**Comment by rolfbjarne** [comment] 2022-10-25 20:21
Minimal repro project:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0-android;net6.0-macos</TargetFrameworks>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
</Project>
```

Fails like this:

```
$ dotnet build -f net6.0-android -c Release -p:RuntimeIdentifier=android-x64
+ test -f /usr/local/share/dotnet/arm64/dotnet
+ test -f /usr/local/share/dotnet/dotnet
+ exec /usr/local/share/dotnet/dotnet build -f net6.0-macos -c Release -p:RuntimeIdentifier=android-x64
MSBuild version 17.4.0-preview-22465-02+02b334e3a for .NET
  Determining projects to restore...
/Users/rolf/test/dotnet/issue-16401-a/testapp/testapp.Mobile/testapp.Mobile.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.linux-bionic-x64 with version (= 6.0.10)
/Users/rolf/test/dotnet/issue-16401-a/testapp/testapp.Mobile/testapp.Mobile.csproj : error NU1102:   - Found 5 version(s) in nuget.org [ Nearest version: 7.0.0-preview.5.22301.12 ]
/Users/rolf/test/dotnet/issue-16401-a/testapp/testapp.Mobile/testapp.Mobile.csproj : error NU1102:   - Found 0 version(s) in /usr/local/share/dotnet/library-packs
  Failed to restore /Users/rolf/test/dotnet/issue-16401-a/testapp/testapp.Mobile/testapp.Mobile.csproj (in 109 ms).
```

Note that specifying the RuntimeIdentifier on the command line is required.

In fact you get the same error if you try to build the net6.0-macos framework with the android RuntimeIdentifier:

```
$ dotnet build -f net6.0-macos -c Release -p:RuntimeIdentifier=android-x64
+ test -f /usr/local/share/dotnet/arm64/dotnet
+ test -f /usr/local/share/dotnet/dotnet
+ exec /usr/local/share/dotnet/dotnet build -f net6.0-macos -c Release -p:RuntimeIdentifier=android-x64
MSBuild version 17.4.0-preview-22465-02+02b334e3a for .NET
  Determining projects to restore...
/Users/rolf/test/dotnet/issue-16401-a/testapp/testapp.Mobile/testapp.Mobile.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.linux-bionic-x64 with version (= 6.0.10)
/Users/rolf/test/dotnet/issue-16401-a/testapp/testapp.Mobile/testapp.Mobile.csproj : error NU1102:   - Found 5 version(s) in nuget.org [ Nearest version: 7.0.0-preview.5.22301.12 ]
/Users/rolf/test/dotnet/issue-16401-a/testapp/testapp.Mobile/testapp.Mobile.csproj : error NU1102:   - Found 0 version(s) in /usr/local/share/dotnet/library-packs
  Failed to restore /Users/rolf/test/dotnet/issue-16401-a/testapp/testapp.Mobile/testapp.Mobile.csproj (in 109 ms).
```

Which makes me think this is a variation of https://github.com/dotnet/sdk/issues/21877, where the RuntimeIdentifier specified on the command line is used for all target frameworks during the restore operation.

This also means there's a workaround: don't specify the RuntimeIdentifier on the command line, but in the project file instead:

```xml
<RuntimeIdentifier Condition="'$(TargetFramework)' == 'net6.0-android'">android-x64</RuntimeIdentifier>
```

**Comment by rolfbjarne** [comment] 2022-10-25 20:27
Closing as duplicate of https://github.com/dotnet/sdk/issues/21877.

**Closed by rolfbjarne** 2022-10-25 20:27 UTC
Labels: question, macOS
