### ISSUE TITLE
Missing app icons and assets.car while building IPA on jenkins using msbuild

### ISSUE THREAD

**Issue by awattar** [xamarin/xamarin-macios#7759] opened 2020-01-27 11:08 UTC
### Steps to Reproduce

There are no steps to reproduce - the same zip archive with app code when build locally and on jenkins on the very similar environment - Xcode 11.0 + VS19 for Mac 8.4.2 (build 59) gives different IPA file. The one on the local machine works but the other from jenkins doesn't have app icon and Assets.car.

Also reported on stack - https://stackoverflow.com/questions/59907615/missing-assets-in-ipa-when-building-xamarin-ios-app-using-msbuild-on-jenkins

This is a very similar case also without resolution - https://stackoverflow.com/questions/48681956/asset-car-and-app-icons-missing-in-ipa-that-was-built-with-msbuild?noredirect=1#comment105976081_48681956

### Expected Behavior

App icons and Assets.car present in IPA.

### Actual Behavior

No app icon and Assets.car in IPA.

### Environment

```
Visual Studio Community 2019 for Mac
Version 8.4.2 (build 59)
Installation UUID: b9f366d0-b4bf-4f50-8a61-ba68496c6b2e
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)

	Package version: 606000155

Mono Framework MDK
Runtime:
	Mono 6.6.0.155 (2019-08/296a9afdb24) (64-bit)
	Package version: 606000155

Roslyn (Language Service)
3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d

NuGet
Version: 5.3.0.6192

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/3.1.101/Sdks
SDK Versions:
	3.1.101
	3.1.100
	3.1.100-preview3-014645
	3.0.100
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.1
	3.1.0
	3.1.0-preview3.19553.2
	3.0.0
	2.1.15
	2.1.14
	2.1.13

Xamarin.Profiler
Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 11.0 (14936)
Build 11A420a

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 13.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

Xamarin Designer
Version: 16.4.0.478
Hash: 95f0ab363
Branch: remotes/origin/d16-4
Build date: 2020-01-08 23:59:46 UTC

Xamarin.Android
Version: 10.1.3.7 (Visual Studio Community)
Commit: xamarin-android/d16-4/d66aed0
Android SDK: /Users/mwesolowski/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: fd9f379
Java.Interop: xamarin/java.interop/d16-4@c4e569f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

Microsoft Mobile OpenJDK
Java SDK: /Users/mwesolowski/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.4.0.9
Hash: 3f7256f
Branch: remotes/origin/d16-4
Build date: 2020-01-14 22:19:04 UTC

Android Device Manager
Version: 16.4.0.30
Hash: f9172e2
Branch: remotes/origin/d16-4
Build date: 2020-01-14 22:19:24 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 804020059
Git revision: eb6fcdd83a227678e487aa733df3c8745f54fafc
Build date: 2020-01-17 12:12:02+00
Build branch: release-8.4
Xamarin extensions: ec32c90978c94f03d72f507b01f5aee70952ce87

Operating System
Mac OS X 10.15.2
Darwin 19.2.0 Darwin Kernel Version 19.2.0
    Sat Nov  9 03:47:04 PST 2019
    root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

```

### Build Logs

jenkins builds _CopyResourcesToBundle partially and does not copy all the files:
```
09:05:00 Building target "_CopyResourcesToBundle" partially, because some output files are out of date with respect to their input files.
```

Local build builds _CopyResourcesToBundle completely and it does copy all the files:
```
 Building target "_CopyResourcesToBundle" completely.
...
  Output file "bin/iPhoneSimulator/Release/RssReader.app/AppIcon60x60@2x.png" does not exist.
  Output file "bin/iPhoneSimulator/Release/RssReader.app/AppIcon76x76@2x~ipad.png" does not exist.
  Output file "bin/iPhoneSimulator/Release/RssReader.app/Assets.car" does not exist.
...
  Using "SmartCopy" task from assembly "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Tasks.dll".
  Task "SmartCopy"
...
Copying file from '/Users/mwesolowski/git/wm_xamarin/iOS/Examples/RssReader/obj/iPhoneSimulator/Debug/device-builds/iphone 8 plus-13.0/actool/bundle/AppIcon60x60@2x.png' to '/Users/mwesolowski/git/wm_xamarin/iOS/Examples/RssReader/bin/iPhoneSimulator/Debug/device-builds/iphone 8 plus-13.0/RssReader.app/AppIcon60x60@2x.png'
    Copying file from '/Users/mwesolowski/git/wm_xamarin/iOS/Examples/RssReader/obj/iPhoneSimulator/Debug/device-builds/iphone 8 plus-13.0/actool/bundle/AppIcon76x76@2x~ipad.png' to '/Users/mwesolowski/git/wm_xamarin/iOS/Examples/RssReader/bin/iPhoneSimulator/Debug/device-builds/iphone 8 plus-13.0/RssReader.app/AppIcon76x76@2x~ipad.png'
    Copying file from '/Users/mwesolowski/git/wm_xamarin/iOS/Examples/RssReader/obj/iPhoneSimulator/Release/actool/bundle/Assets.car' to '/Users/mwesolowski/git/wm_xamarin/iOS/Examples/RssReader/bin/iPhoneSimulator/Release/RssReader.app/Assets.car'
...
  Done executing task "SmartCopy".
Done building target "_CopyResourcesToBundle" in project "RssReader.csproj".
```

### Example Project (If Possible)

N/A

**Comment by chamons** [comment] 2020-01-28 17:44
Thank you for your feedback!

For us to investigate this further, could you please provide your **full build logs**, test case (to reproduce) and all your version information.

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

We look forward to hearing from you!

**Comment by awattar** [comment] 2020-01-28 21:16
I had to remove nonrelevant info and anonymize some data as this is from our production server.

Simply added new Test app (Single View App - Xamarin iOS "native" type) from creator to the solution.
Switched Link behaviour to Link Framework SDKs Only.
Used correct Signing identity to create IPA.

Build log in the attachment.

Both machines have the same Xcode 11.0 and VS19 8.4.2 (build 59), Mono and Xamarin.iOS versions are also the same and already attached in the ticket.
[buildlog.txt](https://github.com/xamarin/xamarin-macios/files/4124628/buildlog.txt)

**Comment by jonathanpeppers** [comment] 2020-01-30 18:03
@awattar do you know why your log from jenkins would have paths like this:
```
22:03:42       _ACTool_BundleResources=
22:03:42           obj/iPhone/Release/actool/bundle/AppIcon60x60@2x.png
22:03:42                   LogicalName=../../../../../../../../../../../../../../../../../../../var/lib/Jenkins/workspace/tmp/Examples/Test/obj/iPhone/Release/actool/bundle/AppIcon60x60@2x.png
22:03:42                   Optimize=false
22:03:42           obj/iPhone/Release/actool/bundle/AppIcon76x76@2x~ipad.png
22:03:42                   LogicalName=../../../../../../../../../../../../../../../../../../../var/lib/Jenkins/workspace/tmp/Examples/Test/obj/iPhone/Release/actool/bundle/AppIcon76x76@2x~ipad.png
22:03:42                   Optimize=false
22:03:42           obj/iPhone/Release/actool/bundle/Assets.car
22:03:42                   LogicalName=../../../../../../../../../../../../../../../../../../../var/lib/Jenkins/workspace/tmp/Examples/Test/obj/iPhone/Release/actool/bundle/Assets.car
22:03:42                   Optimize=false (TaskId:16)
```
I'm guessing you don't see this locally?

When you tested locally did you use a similar command:
```
msbuild /flp:logfile=BuildTest.err;errorsonly /p:StopOnFirstFailure=true /p:Configuration=Release /p:Platform=iPhone /p:BuildIpa=true /p:IpaPackageDir=/private/var/lib/Jenkins/workspace/tmp/iOS/IPAFiles /p:CodesignKey=key /p:CodesignProvision=prov /t:Test /verbosity:diag ./Examples.sln
```
Setting `IpaPackageDir` seems like it might be causing it?

**Comment by awattar** [comment] 2020-02-03 13:40
@jonathanpeppers 

I'll try to check those long paths with someone - they look a little odd.

Yes, when testing locally using similar msbuild command it works as expected. IpaPackageDir was working for a long time.

**Comment by jonathanpeppers** [comment] 2020-02-03 14:17
`/p:IpPackageDir` seems to work for me, but I was just using this app:

https://github.com/xamarin/xamarin-macios/tree/master/msbuild/tests/MyXamarinFormsApp

Could the current directory of your build running on Jenkins affect it? Is it different than the project's directory?

**Comment by awattar** [comment] 2020-02-04 09:28
@jonathanpeppers 

I'm building in the current dir - "./Examples.sln" so perhaps I'll try to remove IpaPackageDir for a while and test.

**Comment by awattar** [comment] 2020-02-04 12:55
Seems to be similar to https://xamarin.github.io/bugzilla-archives/32/32935/bug.html same odd paths and missing assets.

**Comment by jonathanpeppers** [comment] 2020-02-04 16:12
@awattar reading through the old bugs, it seems like the issue might be related to symlinks? But this has probably been happening for a long time. 👀 

It looks like your Jenkins build machine is checking out code into a symlink:

    /var/lib/Jenkins/workspace/tmp/

On my mac `/var/` is a link to:
```
$ ls -la /
t...
lrwxr-xr-x@   1 root  wheel     11 Nov 20  2018 var -> private/var
```

Can you change the location where Jenkins is checking out your project? And see if that solves the issue, thanks!

**Comment by awattar** [comment] 2020-02-04 20:36
I'll check this with my build and release team. Thanks!

**Comment by awattar** [comment] 2020-02-05 11:52
It works after the jenkins home dir change. Thanks for the catch.

So it seems that we still have symlink issue in msbuild.

**Comment by jonathanpeppers** [comment] 2020-03-05 14:48
@awattar I've not been able to repro this issue with a test, so it must be something specific about using `/var/lib/`?

Anyone else, please comment if you are running into this, thanks!

**Comment by jonathanpeppers** [comment] 2020-05-06 14:10
Closing this for now, unless some has a reason to use projects inside `/var/`, thanks!

**Closed by jonathanpeppers** 2020-05-06 14:10 UTC
Labels: external-xsdk, iOS

**Comment by pravincarvalho** [comment] 2020-05-14 09:10
I've struggled to debug this issue for days and also had the projects inside of /var/ on MacOS.
It is is not possible to fix, can we have an error to indicate to the user that need to move the project to another directory?
