### ISSUE TITLE
[iOS] [.NET 8 & .NET 7] Memory leak in GetSemanticSegmentationMatte() - 2.98 MB per image!

### ISSUE THREAD

**Issue by MLB-BIOMETRIC** [xamarin/xamarin-macios#19518] opened 2023-11-24 13:27 UTC
### Bug description

There is a memory leak when using ``GetSemanticSegmentationMatte`` method to get segmentation mattes such as Hair, Teeth and so on. This leak is 2,98 MB per image.

Furthermore, there seems to be an issue where it only allows for four hair masks for four consecutive images.

### Steps to Reproduce

1. Clone my repo that reproduces this memory leak: https://github.com/MLB-BIOMETRIC/Microsoft.iOS.AVSemanticSegmentationMatte-memoryleak
2. Run the iOS app with either .NET 8 or .NET 7 in Release mode. 
- Use the configured ``[RELEASE] App`` task from ``.vscode/launch.json``
- Use the build command below generated from the ``[RELEASE] App`` vscode launch task.
```
dotnet build -t:Build -p:Configuration=Release -r ios-arm64 -p:CustomAfterMicrosoftCSharpTargets="/Users/mlb/.vscode/extensions/ms-dotnettools.dotnet-maui-0.6.19-darwin-arm64/dist/resources/Custom.After.Microsoft.CSharp.targets" -p:MauiVSCodeBuildOutputFile=/var/folders/j2/npl2x6_9245_rkxlk3gpykx80000gp/T/dotnet-maui/maui-vsc-fcb77205-3126-4a8e-baaa-8bdf548d930d.json App
```
3. Track the memory allocations using Apple Instruments. (``Allocations`` profiling template)
4. Watch the hair mask working for the first 4 images, and then being null for following image (for no reason).
5. Watch the 2,98 MB memory leak stack up for each of the images taken with a hair mask that isn't null.

### Expected Behavior

The expected behavior is that there should be no memory leak when getting the segmentation mattes for images. Furthermore, it should be able to capture as many photos with hair masks without giving null on the hair mask.

### Actual Behavior

Each time a segmentation matte (hair mask) is generated a memory leak is introduced of 2,98 MB. Furthermore, it only allows for 4 consectuive images with hair masks before hair masks starts to become null.

Below is an example of Apple Instruments that shows the 2,98 MB memory leak for each of the 4 images that i took requesting a hair mask.

![InstrumentsMemoryLeakHairMask](https://github.com/xamarin/xamarin-macios/assets/130459814/cd5144a8-b19e-4bb0-9b8c-61e8cfd3adae)

**Apple Instruments file (Allocations profiling template**

Below is a copy of an Allocations profiling i ran, where 6 images were taken. 4 hair masks were generated. 
[Microsoft.iOS.AVSemanticSegmentationMatte-memoryleak - 6 images taken - 4 hair masks.trace.zip](https://github.com/MLB-BIOMETRIC/Microsoft.iOS.AVSemanticSegmentationMatte-memoryleak/raw/main/Microsoft.iOS.AVSemanticSegmentationMatte-memoryleak%20-%206%20images%20taken%20-%204%20hair%20masks.trace.zip)

### Environment

```
Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------
maui                       8.0.3/8.0.100         SDK 8.0.100        
```

### Build Logs

No special build logs.

### Example Project

https://github.com/MLB-BIOMETRIC/Microsoft.iOS.AVSemanticSegmentationMatte-memoryleak

**Comment by MLB-BIOMETRIC** [comment] 2023-11-27 09:31
I reported it on Microsoft Developer Community as well: https://developercommunity.visualstudio.com/t/NET-8--NET-7-Xamarin-iOS-Memory-l/10526276

**Comment by rolfbjarne** [comment] 2023-11-27 14:31
I can reproduce the problem, but I can't get Instruments to show anything (Instruments hangs soon after I try to profile).

Could you save your Instruments trace and attach it here?

**Comment by MLB-BIOMETRIC** [comment] 2023-11-28 09:00
@rolfbjarne You have to build the iOS app in Release mode (``-c Release``). I just used the ``[RELEASE] App`` task configured in the ``.vscode/launch.json``. For some reason the ``-c Debug`` doesn't work with Instruments... I think thats another bug :)

Below is the command generated and used from the ``[RELEASE] App`` vscode task.

**Build command**
```
dotnet build -t:Build -p:Configuration=Release -r ios-arm64 -p:CustomAfterMicrosoftCSharpTargets="/Users/mlb/.vscode/extensions/ms-dotnettools.dotnet-maui-0.6.19-darwin-arm64/dist/resources/Custom.After.Microsoft.CSharp.targets" -p:MauiVSCodeBuildOutputFile=/var/folders/j2/npl2x6_9245_rkxlk3gpykx80000gp/T/dotnet-maui/maui-vsc-fcb77205-3126-4a8e-baaa-8bdf548d930d.json App
```


**Instruments**
[Microsoft.iOS.AVSemanticSegmentationMatte-memoryleak - 6 images taken - 4 hair masks.trace.zip](https://github.com/MLB-BIOMETRIC/Microsoft.iOS.AVSemanticSegmentationMatte-memoryleak/raw/main/Microsoft.iOS.AVSemanticSegmentationMatte-memoryleak%20-%206%20images%20taken%20-%204%20hair%20masks.trace.zip)


Furthermore, I uploaded my instruments file. To find the ``CMCapture - 2,98 MiB`` leak you have to go into ``All Heap & Anonymous VM`` and then sort by ``Size``. The file above shows 6 pictures taken, where 4 of them has hairmasks with the leak.

![image](https://github.com/xamarin/xamarin-macios/assets/130459814/7ebab1cf-c9d0-48df-8ca5-cb6d1df198c2)




I updated the original with info as well.

**Comment by MLB-BIOMETRIC** [comment] 2023-11-30 08:33
If @rolfbjarne or anyone else can point me in a direction to where this ``GetSemanticSegmentationMatte`` method is located. Then I will see if I possibly can contribute a fix myself. :)

**Comment by rolfbjarne** [comment] 2023-11-30 10:21
It's just a binding to the native method, so it's a bit more complicated than that.

At least I can reproduce it myself now and profile with Instruments with a release build, so I'll have a look.

**Comment by rolfbjarne** [comment] 2023-12-05 09:24
This actually seems like an issue with iOS itself, and not our bindings.

The leak only occurs when creating a CIImage from the `AVSemanticSegmentationMatte` instance.

In other words, _not_ doing this:

```cs
var cihairmask = new CIImage(hairmaskraw)
```

fixes the leak.

The CIImage uses an internal type, `CI:SurfaceImage`, which stores (and retains) the `AVSemanticSegmentationMatte` instance:

```
-[NSObject retain]	
CI::SurfaceImage::set_ssmatte(void const*)	
-[CIImage _initWithIOSurface:options:owner:]	
-[CIImage initWithCVPixelBuffer:options:]	
[...]
```

but this `AVSemanticSegmentationMatte` reference is never released, even when the `CI:SurfaceImage` instance is freed.

Note that I made a few changes to the DidFinishProcessingPhoto: https://gist.github.com/rolfbjarne/7a60c2697e3d0b613e95b4638f939af2

* Dispose of all images (using the `using ...` clause). Waiting on the GC to do its job might take too long in this case (in particular because image processing results in memory pressure that's not visible to the GC).
* Add an NSAutoreleasePool - this ensures any internal temporary objects created by iOS are freed in a timely manner.
* Call GC.Collect: this is only while profiling, it makes profiling results more predictable, since you don't have to wait for the GC to run to see if there's a leak or not.

Going forward, my recommendation would be to create a test project in Xcode, and use it to submit an issue to Apple (Apple  doesn't accept Xamarin projects as test projects).

I'm going to close this issue, since it doesn't look like a problem in our product. If you determine otherwise with an Xcode project, please reopen, and attach the Xcode project, and we'll have a look again.

**Closed by rolfbjarne** 2023-12-05 09:24 UTC
Labels: need-attention

**Comment by MLB-BIOMETRIC** [comment] 2023-12-07 14:51
@rolfbjarne Thank you very much for your investegation.

I managed to "fix" the memory leak, by instead of using the raw
```csharp
using var cihairmask = new CIImage(hairmaskraw)
```

then use the mattingImage CVPixelBuffer
```csharp
using var cihairmask = new CIImage(hairmaskraw.MattingImage);
```

This even resolves the problem of only being able to take 4 hairmasks consecutively. 

I am not sure if this still is an Apple iOS problem directly, or this leads us further to the cause. :)
