### ISSUE TITLE
[Bug] "[xma]: Failed to execute 'which mono64': ExitStatus = 1"

### ISSUE THREAD

**Issue by commcad** [xamarin/xamarin-macios#9756] opened 2020-09-26 11:07 UTC
### Description
When compiling, and/or deploying, and/or pairing to a mac we are getting this error.

### Steps to Reproduce

1. Pairing to mac from VS2019, install mono and xamarin packages from the pairing tool, establish a successful conn
2. Build solution; getting error "[xma]: Failed to execute 'which mono64': ExitStatus = 1"
3. Deploy over to mac for simulation; getting error "[xma]: Failed to execute 'which mono64': ExitStatus = 1"

Specs:
Win: Clean Win10 install
Win: New VS2019 install with Mobile/Xamarin packages & SDKs
Mac: Clean 10.15.7 Catalina install
MaC: New Xcode 12.0 install

Workaround: No workaround required. All seems to work well regardless, apart from this annoyance/error. Thanks

> VS bug [#1224277](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1224277)

**Comment by glat** [comment] 2020-10-02 14:56
+1

**Comment by mauroa** [comment] 2020-10-05 19:57
Hi,
Thanks for your feedback. This is not an error but a warning. Even if it doesn't affect the behavior, I agree it's annoying and confusing for many users, so we are already tracking this and we will be removing it soon. This issue is already been tracked in this other ticket: https://developercommunity.visualstudio.com/content/problem/1206100/warning-vsx1000-the-connection-to-the-mac-server-w.html
I'm closing this as a duplicate, so please follow up on the linked item. We are likely to release the fix on the next 16.8 Preview.
Thanks.

**Closed by mauroa** 2020-10-05 19:57 UTC
Labels: external-xamarin-vs

**Comment by theBoringCoder** [comment] 2020-10-15 01:30
Reconsider closing this. The moderators of the developer community ticket you linked to have a differing perspective.

https://developercommunity.visualstudio.com/content/problem/1206100/warning-vsx1000-the-connection-to-the-mac-server-w.html

**Comment by YYZRichard** [comment] 2020-10-21 04:40
I encountered the same issue on **Visual Studio 2019 on Windows 10**, followed by the message: 

**An error occurred while executing MTouch**. 

This issue started after upgrading to **Xamarin.IOS 14** and **XCode 12** on 20-Oct-2020. It's happening on 5 computers, 2 of them have a brand new install of Visual Studio 2019. 

To reproduce, just create a brand new Xamarin iOS project, and deploy it to an iPhone.

**Comment by mclillill** [comment] 2020-11-17 12:30
@samhouts I have the same issue after upgrading to VisualStudio 16.8. i can't build via command line anymore. Please consider reopening.

**Comment by Auto72** [comment] 2020-12-15 08:44
I have the same issue in VisualStudio 16.8.3 😔

**Comment by vmsJenni** [comment] 2020-12-18 06:54
Throwing in my 2-cents here as well - as I am also receiving the same warning since updating VS2019 to 16.8.3
Warning		[xma]: Failed to execute 'which mono64': ExitStatus = 1	

Also, unable to debug via simulator (simulator does not even try to startup anymore).  Build is successful(?)

VS2019:  16.8.3
MAC:  Catalina 10.15.7
XCode: 12.3 (12C33)

**Comment by mclillill** [comment] 2020-12-18 08:09
@samhouts @XamarinQA @xamarin-release-manager I also still have the same issue. Please reopen the issue.

**Comment by taublast** [comment] 2021-03-15 10:35
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.Messaging.targets(83,3): warning : [xma]: Failed to execute 'which mono64': ExitStatus = 1

Still up..
