### ISSUE TITLE
Seems like icons are broken again with the Visual Studio for Mac 8.10.10 release...

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/xamarin-macios#12917] opened 2021-10-03 23:34 UTC
Seems like issue #11786 is back this time on VS for Mac 8.10.10...
![Bildschirmfoto 2021-10-04 um 01 29 13](https://user-images.githubusercontent.com/25636075/135775622-b723b704-5db1-43c7-b884-07684deb2c41.png)

**Comment by chamons** [comment] 2021-10-04 11:07
Thanks of for the feedback.

Unfortunately the team responsible for VS for Mac can not get feedback from github. 

Please file this [here](https://developercommunity.visualstudio.com/report?space=41&entry=problem).

**Comment by chamons** [comment] 2021-10-05 14:29
After research it appears that dialog is populated from an [SDK step](https://github.com/xamarin/xamarin-macios/blob/main/msbuild/Xamarin.MacDev.Tasks/Tasks/ALToolValidate.cs). However, our submission tests are not failing, so there must be something unique in your build.

Please attach a [binary build log](https://docs.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2019#save-a-binary-log) or sample project showing the issue.

**Comment by chamons** [comment] 2021-10-11 16:50
I tried to reproduce this with a new project (and our submission test) and I've been unable to. 

Could you please attach a [binary build log](https://docs.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2019#save-a-binary-log) or sample project showing the issue.

**Comment by Sebastian1989101** [comment] 2021-10-11 16:55
Don‘t know if @sisaacks has the same problem, in my case it was only if the bundle included alternate app icons. I could build new TestFlight builds by removing them from the app for now.. which is kinda a bad solution but at least I could continue testing on my other stuff for now…

**Comment by rachelkang** [comment] 2021-12-20 18:17
We will be closing this issue as it has been over 30 days since we have not received the requested information. If you are still experiencing this issue, please provide all the requested information (i.e. the full binary build logs and/or sample project) and then click the Reopen Issue button. Thank you!

**Comment by sisaacks** [comment] 2021-12-20 18:28
@rachelkang someone from Microsoft ended up helping me solve the issue.  My project is about 3 years old.  When I created it, there was not a LaunchScreen.StoryBoard in the resources folder.  I followed a MS tutorial to add the storyboard to the root of my project.  Somehow, during updates, an additional storyboard was added to my project and the file was hidden.  I renamed my storyboard and added it to the resources folder and like magic everything started working.  Every now and then I still get the error when switching from Android to IOS project.  But usually if I clean and rebuild then I can upload to transporter.

**Comment by rachelkang** [comment] 2021-12-20 19:46
That's awesome! I'm glad you were able to get it working. If you run into the error and get blocked because of it, feel free to share your sample project, full build logs, and reopen this issue. Thanks!

**Comment by sisaacks** [comment] 2021-12-21 02:42
@rachelkang I honestly think, it the file was added when I upgraded and because I had a file with the same name, the file became hidden.  It seems strange to me, simply renaming the file to something other than LaunchScreen.Storyboard and it started working.....then the hidden file appeared.  I deleted that one, renamed mine to LaunchScreen.Storyboard and it started working.  I can't be the only person that his this issue

**Comment by rachelkang** [comment] 2021-12-21 16:01
If you or other folks report that you run into this issue again in the future, and can share an updated sample that reproduces it, we will be sure to reopen this issue then. Without the requested information, we unfortunately cannot investigate further.

**Comment by jgold6** [comment] 2022-01-11 20:17
Not sure if the same issue, but I found an issue when building either from Windows with Mac or directrly in VS for Mac.

If the Deployment Target >= 11.0, then only two of the AppIcons are compiled into the app bundle. 
If the Deployment Target < 11.0 then all of the AppIcons are compiled into the app bundle. 

I can reproduce this simply by creating a new template Xam.iOS Master-Detail project and setting the Deployment target to >= 11.0. If I then build for Release | iPhone and inspect the app bundle, I will only see two AppIcons, the 60x60@2x and the 76x76@2x-ipad. If I instead set the deployment target to < 11.0, then all of hte AppIcons end up in the app bundle.


Steps to reproduce:
1. Open Visual Studio for Mac 8.10.16 (current stable as of this writing)
2. Create a new Xamarin.iOS Master Detail app project (did not try other templates) with deployment Target >= 11.0
3. Build for Release | iPhone
4. Open the App bundle and look for the AppIcons

Expected result:
Will see 17 AppIcons

Actual Result
Only see 2 AppIcons


If you clean and rebuild after changing the deployment Target to <= 10.3, then all of the AppIcons are in the app bundle.

**Comment by jgold6** [comment] 2022-01-12 20:28
Closing again because in the end my last comment did not reveal an instance of this issue.

**Closed by jgold6** 2022-01-12 20:28 UTC
Labels: need-info
