### ISSUE TITLE
Xamarin fails to compile and link project using Deedle and Fsharp.core libs

### ISSUE THREAD

**Issue by rhy-ama** [xamarin/xamarin-macios#7361] opened 2019-11-04 18:03 UTC
### Steps to Reproduce

1.  Unpack the provided Xamarin template project.
2.  The only XAML and class modified is the AboutViewModel xaml and cs.
3.  Set target to iPhone and try to compile

### Expected Behavior

Compilation without issues.

### Actual Behavior

Compilation fails and "Compile to native" stage. If Deedle and FSharp.core nugets are removed from the solution and relevant lines inside AboutViewModel.cs are commented/uncommented, code compiles and runs without issues.

### Environment

Visual studio on dev PC:

```
Microsoft Visual Studio 2019
Version 16.3.7
VisualStudio.16.Release/16.3.7+29424.173
Microsoft .NET Framework
Version 4.8.03752

Mono Debugging for Visual Studio   16.3.7 (9d260c5)
Support for debugging Mono processes with Visual Studio.

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19455.1+0422ff293bb2cc722fe5021b85ef50378a9af823
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.3.0.277 (d16-3@c0fcab7)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.3.0.246 (remotes/origin/d16-3@bd2f86892)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.565 (27e9746)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.0.3.0 (d16-3/4d45b41)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-06@5608fe0abb3
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333


Xamarin.iOS and Xamarin.Mac SDK   13.4.0.2 (e37549b)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```
Mac Catalina, XCode 11.2:
```
Version 8.3.6 (build 4)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)
	Package version: 604000208

=== Mono Framework MDK ===
Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

=== .NET Core SDK ===
SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	2.1.701
	2.1.700
	2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.1.13
	2.1.12
	2.1.11
	2.1.9

=== Xamarin.Profiler ===
Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===
Xcode 11.2 (15526)
Build 11B52

=== Xamarin.Mac ===
Version: 6.4.0.2 (Visual Studio Community)

=== Xamarin.iOS ===
Version: 13.4.0.2 (Visual Studio Community)
Hash: e37549bc
Branch: xcode11.1
Build date: 2019-10-07 22:43:23-0400

=== Xamarin.Android ===
Version: 10.0.3.0 (Visual Studio Community)
Commit: xamarin-android/d16-3/4d45b41
Android SDK: /Users/rhy-dev-mac02/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-06@5608fe0abb3
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Operating System ===

Mac OS X 10.15.1
Darwin 19.0.0 Darwin Kernel Version 19.0.0
    Thu Oct 17 16:17:15 PDT 2019
```

### Build Logs

[Build.txt](https://github.com/xamarin/xamarin-macios/files/3805388/Build.txt)

### Example Project (If Possible)

[DependencyTest.zip](https://github.com/xamarin/xamarin-macios/files/3805395/DependencyTest.zip)

**Comment by chamons** [comment] 2019-11-04 21:37
FYI @rolfbjarne 

Once I correctly swap it to 64-bit I hang on

```
  778   ??  R     11:20.60 /Library/Frameworks/Xamarin.iOS.framework/Versions/13.4.0.2/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32 --aot=mtriple=arm64-ios,data-outfile=/Users/donblas/Downloads/DependencyTest/DependencyTest/DependencyTest.iOS/obj/iPhone/Debug/mtouch-cache/arm64/Deedle.aotdata.arm64,static,asmonly,direct-icalls,full,soft-debug,dwarfdebug,no-direct-calls,outfile=/Users/donblas/Downloads/DependencyTest/DependencyTest/DependencyTest.iOS/obj/iPhone/Debug/mtouch-cache/arm64/Deedle.dll.s /Users/donblas/Downloads/DependencyTest/DependencyTest/DependencyTest.iOS/obj/iPhone/Debug/mtouch-cache/3-Build/Deedle.dll
```
For a _long_ time.

**Comment by rhy-ama** [comment] 2019-11-04 21:42
@chamons ....no worries. takes around an hour to drop and pop the error :)

**Comment by rolfbjarne** [comment] 2019-11-05 11:46
The problem is that the 2.3MB Deedle.dll turns into a 11GB Deedle.dll.s when AOT-compiled, then a 3.5GB Deedle.dll.o when the native code is compiled, and finally the native linker just gives up with a SIGBUS.

I think this is due to a generic explosion in the AOT compiler, but of a magnitude I've never seen before.

Moving to the mono repo, since if this is a bug, it's a bug in the AOT compiler.

**Comment by rolfbjarne** [comment] 2019-11-05 11:47
This issue was moved to mono/mono#17709

**Closed by rolfbjarne** 2019-11-05 11:47 UTC
Labels: bug, iOS
