### ISSUE TITLE
Build from Visual Studio 2022 17.7.5 paired to Mac failing if using a xcframework inside the project

### ISSUE THREAD

**Issue by cwall-dev** [xamarin/xamarin-macios#19152] opened 2023-10-11 13:59 UTC
### Steps to Reproduce

1. Create new Blank Maui App from Template
2. Add Nuget Package References to a package containig a xcframework. (For Example to "Scandit.DataCapture.Core" Version 6.19.1)
3. Connect to Mac
4. Hit Run on connected RemoteDevice

### Expected Behavior
The app should build and start on the device

### Actual Behavior
The Build fails with the following Error:
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7107\tools\msbuild\iOS\Xamarin.Shared.targets(137,3): error : C:/Projekte/Investigation/VS2022MAUIiOSBuildError/MauiApp1/MauiApp1/bin/Debug/net7.0-ios/ios-arm64/ScanditCaptureCoreiOS.resources/ScanditCaptureCore.xcframework has an incorrect or unknown format and cannot be processed.

### Environment

<details>
<summary>Version information</summary>

```
Microsoft Visual Studio Enterprise 2022
Version 17.7.5
VisualStudio.17.Release/17.7.5+34202.233
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA272
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.7.273.65229
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.7.273.65229
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.7.273.65229
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

BTMDLG Editor Package   1.0
BTMDLG file editor for Visual Studio

C# Tools   4.7.0-3.23469.2+a3b9f0c274649870015cfe508cacde8fdc15df55
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.4.34 (main@d5ab18b)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

FireGiant HeatWave   1.0.1.1
Visual Studio tooling for WiX projects.  For more information about HeatWave, visit http://www.firegiant.com.

GitHub Copilot   1.116.0.0 (v1.116.0.0@5a26aa711)
GitHub Copilot is an AI pair programmer that helps you write code faster and with less work.

GitHub Copilot Agent   1.116.440 (v1.116.0)

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.7.27 (547ea6f)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.50628.1 Commit Hash:f9e713b25f69afd3ced63d934e0722003b73c121
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.7.3.2333001+0ab18affdf2a37647768d0e25f5f021bee6257a1
Provides languages services for ASP.NET Core Razor.

Resource Localizer   1.0
Collect resources of a sovia project and manage the localization of them.

sovia ProjectConfigurator   1.0
Addin for sovia project configuration

SQL Server Data Tools   17.7.10.1
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.20829.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.7.0-3.23469.2+a3b9f0c274649870015cfe508cacde8fdc15df55
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.7.0-beta.23314.10+e612cf93b989503c89e3a5830090062b7ab5e143
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.7.0.223 (d17-7@c374b3e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.7.3.9 (remotes/origin/d17-7@796d191def)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.7.21 (150ec9f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.1.2 (d17-5/a8a26c7)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d


Xamarin.iOS and Xamarin.Mac SDK   16.4.0.18 (9d266025e)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```
On Mac: 
MacOS 14
XCode 15

</details>

### Build Logs

[CentralNode_devenv_PID=4088_x64_BuildManager_Default.zip](https://github.com/xamarin/xamarin-macios/files/12870693/CentralNode_devenv_PID.4088_x64_BuildManager_Default.zip)

### Example Project (If Possible)

You can find a repro repo here: https://github.com/cwall-dev/VS2022MAUIiOSBuildError

**Comment by philipag** [comment] 2023-10-12 07:45
I have a related issue here I posted as a VS issue but perhaps it belongs here:

https://developercommunity.visualstudio.com/t/MAUI-iOS-NativeReference-broken-in-lates/10489411#T-ND10490116

MAUI iOS NativeReference broken in latest VS 17.8 Preview 3 (worked in Preview 2)
[severity:I’m unable to use this version] [regression] [worked-in:17.8 Preview 2]

I have the following in an app csproj file:

`		<NativeReference Include="$(ProjectDir)Platforms\iOS\lib\bass_fx.xcframework">
			<Kind>Dynamic</Kind>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</NativeReference>`

In preview 2 this worked and copied the framework lib into the app bundle. In preview 3, this gives the following build warning and does not add the files into the bundle:

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.8968-net8-rc2\tools\msbuild\iOS\Xamarin.Shared.targets(138,3): warning : The directory ‘C:/z/recorder/apps/Phone/PTDSP/Platforms/iOS/lib’ does not exist.

Nothing has changed in the project other than the VS RC2 upgrade and the ‘lib’ folder definitely exists, so this is a regression in RC2. For me this is a show stopper and RC2 cannot be used to develop iOS project with framework dependencies.

**Comment by rolfbjarne** [comment] 2023-10-17 07:39
> I have a related issue here I posted as a VS issue but perhaps it belongs here:
> 
> [developercommunity.visualstudio.com/t/MAUI-iOS-NativeReference-broken-in-lates/10489411#T-ND10490116](https://developercommunity.visualstudio.com/t/MAUI-iOS-NativeReference-broken-in-lates/10489411#T-ND10490116)
> 
> MAUI iOS NativeReference broken in latest VS 17.8 Preview 3 (worked in Preview 2) [severity:I’m unable to use this version] [regression] [worked-in:17.8 Preview 2]
> 
> I have the following in an app csproj file:
> 
> ```
> 		<NativeReference Include="$(ProjectDir)Platforms\iOS\lib\bass_fx.xcframework">
> 			<Kind>Dynamic</Kind>
> 			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
> 		</NativeReference>
> ```
> 
> In preview 2 this worked and copied the framework lib into the app bundle. In preview 3, this gives the following build warning and does not add the files into the bundle:
> 
> 1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.8968-net8-rc2\tools\msbuild\iOS\Xamarin.Shared.targets(138,3): warning : The directory ‘C:/z/recorder/apps/Phone/PTDSP/Platforms/iOS/lib’ does not exist.
> 
> Nothing has changed in the project other than the VS RC2 upgrade and the ‘lib’ folder definitely exists, so this is a regression in RC2. For me this is a show stopper and RC2 cannot be used to develop iOS project with framework dependencies.

This is the same as https://github.com/xamarin/xamarin-macios/issues/19173.

**Comment by rolfbjarne** [comment] 2023-10-17 07:40
@cwall-dev did this work for you in earlier versions of .NET 7?

**Comment by cwall-dev** [comment] 2023-10-17 07:43
@rolfbjarne yes of course. I can successfully build the Repro repo using Visual Studio **17.7.4**.

**Comment by rolfbjarne** [comment] 2023-10-17 12:31
Looks like this bug is a duplicate of https://github.com/xamarin/xamarin-macios/issues/19173 as well, so I'm closing as such.

**Closed by rolfbjarne** 2023-10-17 12:31 UTC
Labels: bug, regression
