### ISSUE TITLE
Xamarin ios re-generate a tons of files at the storyboard folder level.

### ISSUE THREAD

**Issue by unamed000** [xamarin/xamarin-macios#9508] opened 2020-08-26 07:27 UTC
I have a pretty big project written by xamarin ios and xamarin android. When i update to latest version of Visual Studio, it starts behaving weird when i tried to open .storyboard file via xcode and edit something. It will generate a lots of .cs and .designer.cs file from the Custom class and File owners in the .storyboard files which are not in the same folder of the .storyboard file (Because i putted them elsewhere which make more sense)

### Steps to Reproduce

1. Have a xamarin ios project
2. Create a storyboard file and make a custom class link to a control in the storyboard
3. Copy the .cs and .designer.cs project from a different folder
4. Reopen the storyboard and edit again. It will try to generate that class again.

### Expected Behavior
It shouldn't generate a new class when it's not in the same folder

### Actual Behavior
It will try to generate that class again.

### Environment
```
=== Visual Studio Community 2019 for Mac ===

Version 8.7.4 (build 38)
Installation UUID: f282c7f1-c9b9-4d6a-ba9b-96763593280d
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000090

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.90 (2020-02/d3daacdaa80) (64-bit)
	Package version: 612000090

=== Roslyn (Language Service) ===

3.7.0-6.20412.3+d3c3a44a4e7ad31cc75c59be0d3df4a19ff33878

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.401/Sdks
SDK Versions:
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.701
	2.1.700
	2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.6 (16141)
Build 11E708

=== Xamarin.Mac ===

Version: 6.20.2.2 (Visual Studio Community)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:44:59-0400

=== Xamarin.iOS ===

Version: 13.20.2.2 (Visual Studio Community)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:45:00-0400

=== Xamarin Designer ===

Version: 16.7.0.492
Hash: f5afe667d
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-07-10 18:42:54 UTC

=== Xamarin.Android ===

Version: 11.0.2.0 (Visual Studio Community)
Commit: xamarin-android/d16-7/025fde9
Android SDK: /Users/netcompany/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.0
SDK Build Tools Version: 29.0.3

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/netcompany/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-08-19 22:18:28 UTC

=== Android Device Manager ===

Version: 16.7.0.24
Hash: bb090a3
Branch: remotes/origin/d16-7
Build date: 2020-08-19 22:18:52 UTC

=== Build Information ===

Release ID: 807040038
Git revision: 7f322926a2e0a5fa0c1e3833215a191883f7514a
Build date: 2020-08-20 10:10:20-04
Build branch: release-8.7
Xamarin extensions: 7f322926a2e0a5fa0c1e3833215a191883f7514a

=== Operating System ===

Mac OS X 10.15.5
Darwin 19.5.0 Darwin Kernel Version 19.5.0
    Tue May 26 20:41:44 PDT 2020
    root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64


```

> VS bug [#1180517](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1180517)

**Comment by jkapsouras** [comment] 2020-08-26 08:20
Happens to vs for mac 8.7.3 and to 8.7.4. It also happens for the versions in the preview channel

**Comment by unamed000** [comment] 2020-08-28 03:02
For now, it's almost impossible to work with xamarin.ios for now because of this issue. Any suggestions that i can downgrade my VS version to previous one?

**Comment by jkapsouras** [comment] 2020-08-28 06:15
@unamed000 check this from Xamarin: https://download.visualstudio.microsoft.com/download/pr/68ffa29a-6a5b-41f7-af7b-506ddcf4bbfc/6f601f3b5ff4d19ecd2c258517acc562/visualstudioformac-8.6.2.6.dmg You can work with 8.6, it's fine (I already switched yesterday). We will be notified when the issue is going to be fixed in 8.7. Check also here -> https://github.com/xamarin/xamarin-macios/issues/9372

**Comment by unamed000** [comment] 2020-08-28 09:05
Thanks !!

**Comment by jkapsouras** [comment] 2020-09-09 10:28
As I mentioned in https://github.com/xamarin/xamarin-macios/issues/9372 a new version has been just released and the problem is now fixed (tested in XCode 11.7 and Visual Studio for Mac 8.7.5.19)

**Comment by unamed000** [comment] 2020-09-22 09:58
This is somehow happening again with latest VS for Mac with Xcode 12.0

**Comment by whitneyschmidt** [comment] 2020-12-14 17:57
@unamed000 Thanks for your feedback! Closing this issue as it appears it has been fixed. Feel free to reopen if you are still encountering it after upgrading to Xcode 11.7 and VSMac 8.7.5.19 :)

**Closed by whitneyschmidt** 2020-12-14 17:57 UTC
Labels: external-visual-studio-for-mac
