### ISSUE TITLE
MT3001: Could not AOT the assembly when private enum in generic class

### ISSUE THREAD

**Issue by arendigossweiler** [xamarin/xamarin-macios#5979] opened 2019-05-02 14:45 UTC
### Steps to Reproduce

1. Create a .net standard library
2. Create a generic class
3. Add a private enum into the generic class
4. Create a variable from this enum type in the constructor
5. Use string interpolation to convert the enum value to a string
6. Use the .net standard library in a Xamarin.iOS project

Please find a reduced solution to reproduce the issue below.
The code which causes the error can be found in the libtest.Aot class line 19.

### Expected Behavior
The iOS project can be compiled without error.

### Actual Behavior
The build failed with error:
MTOUCH : error MT3001: Could not AOT the assembly '/Users/a.gossweiler/Projects/libtest/libtest.iOS/obj/iPhone/Debug/mtouch-cache/3-Build/libtest.dll'

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.0.5 (build 9)
Installation UUID: a1c7ad7a-babc-43b7-af7c-bdca8460cb99
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

=== NuGet ===

Version: 4.8.2.5835

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.1.9
SDK: /usr/local/share/dotnet/sdk/2.1.505/Sdks
SDK Version: 2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.9
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.2.3.0 (Visual Studio Community)
Android SDK: /Users/Shared/Library/Developer/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: mono/mono/2018-08-rc@5ac37ccd385
Java.Interop: xamarin/java.interop/d16-0@c987483
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
MXE: xamarin/mxe/xamarin@b9cbb535
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.26.0@325e91a
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/a.gossweiler/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-04-05 16:58:56 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Xamarin Designer ===

Version: 4.17.4.418
Hash: 3d086e814
Branch: remotes/origin/d16-0
Build date: 2019-04-01 09:20:10 UTC

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 12.8.0.0 (Visual Studio Community)
Hash: 0aa84521
Branch: d16-0
Build date: 2019-04-02 16:01:19-0400

=== Build Information ===

Release ID: 800050009
Git revision: d9d7eed60cb59740ba55c04bfe9c39ac57014c12
Build date: 2019-04-26 10:08:19+00
Build branch: master
Xamarin extensions: 5efedb990d786142d3b54351c01ce867af7b7680

=== Operating System ===

Mac OS X 10.14.4
Darwin 18.5.0 Darwin Kernel Version 18.5.0
    Mon Mar 11 20:40:32 PDT 2019
    root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
```

### Build Logs

Target _CompileToNative:
    /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/a.gossweiler/Projects/libtest/libtest.iOS/obj/iPhone/Debug/response-file.rsp 
    AOT Compilation exited with code 134, command:
    MONO_PATH=/Users/a.gossweiler/Projects/libtest/libtest.iOS/obj/iPhone/Debug/mtouch-cache/3-Build /Library/Frameworks/Xamarin.iOS.framework/Versions/12.8.0.0/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32  --aot=mtriple=arm64-ios,data-outfile=/Users/a.gossweiler/Projects/libtest/libtest.iOS/obj/iPhone/Debug/mtouch-cache/arm64/libtest.aotdata.arm64,static,asmonly,direct-icalls,full,soft-debug,dwarfdebug,no-direct-calls,outfile=/Users/a.gossweiler/Projects/libtest/libtest.iOS/obj/iPhone/Debug/mtouch-cache/arm64/libtest.dll.s "/Users/a.gossweiler/Projects/libtest/libtest.iOS/obj/iPhone/Debug/mtouch-cache/3-Build/libtest.dll"
    Mono Ahead of Time compiler - compiling assembly /Users/a.gossweiler/Projects/libtest/libtest.iOS/obj/iPhone/Debug/mtouch-cache/3-Build/libtest.dll
    AOTID 83789DAF-67CF-F8DC-35CB-14BCAF2FE32E
    * Assertion at /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mono/mini/decompose.c:1469, condition `cfg->cbb == first_bb' not met
    
    
    MTOUCH : error MT3001: Could not AOT the assembly '/Users/a.gossweiler/Projects/libtest/libtest.iOS/obj/iPhone/Debug/mtouch-cache/3-Build/libtest.dll'
Done building target "_CompileToNative" in project "libtest.iOS.csproj" -- FAILED.
### Example Project (If Possible)

[libtest.zip](https://github.com/xamarin/xamarin-macios/files/3138486/libtest.zip)

**Comment by rolfbjarne** [comment] 2019-05-03 06:59
This looks like a duplicate of https://github.com/mono/mono/issues/13297 and/or https://github.com/mono/mono/issues/14066.

The workaround seems to be to not use enums in generic classes (https://github.com/mono/mono/issues/14066#issuecomment-485142851)

**Closed by rolfbjarne** 2019-05-03 06:59 UTC
