### ISSUE TITLE
[Generator] If a class uses the Sealed attribute it should not have protected methods.

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#9505] opened 2020-08-25 21:49 UTC
As CS0628 states: 

> A sealed class cannot introduce a protected member because no other class will be able to inherit from the sealed class and use the protected member.

Yet the generator is creating the costructors as protected, for example we get the following warning:

```
build/mac/full/ReplayKit/RPScreenRecorder.g.cs(113,22): warning CS0628: ‘RPScreenRecorder.RPScreenRecorder(IntPtr)’: new protected member declared in sealed class
```

When generating sealed classes this should not be protected.

**Comment by spouliot** [comment] 2020-08-26 00:07
dupe of https://github.com/xamarin/xamarin-macios/issues/9065

**Closed by spouliot** 2020-08-26 00:07 UTC
Labels: enhancement, generator
