### ISSUE TITLE
[XM]NSCustomView sample fails to build in Release mode with"error MM5109: Native linking failed with error code 1" when Target Framework is set to "Unsupported Framework"

### ISSUE THREAD

**Issue by p-lad** [xamarin/xamarin-macios#4874] opened 2018-09-25 08:00 UTC
### Steps to Reproduce

1. Download NSCustomView Sample from https://github.com/xamarin/mac-samples
2. Open NSCustomView Sample in VSFM
3. Change Config to Release Mode
4. Open Project properties >>General >> Select Unsupported framework
5. Build the application

### Expected Behavior
NSCustomView Sample should build and run successfully.

### Actual Behavior
[XM]NSCustomView sample fails to build in Release mode with"error MM5109: Native linking failed with error code 1" when Target Framework is set to "Unsupported Framework"

### Environment
https://gist.github.com/p-lad/e9e7ecd0cf27caf6e292d0e2693c8adb

```
```

### Build Logs
https://gist.github.com/p-lad/0f9cec282a8773fc8ded4081961473a8

### Example Project (If Possible)
mac samples/NSCustomView

**Comment by VincentDondain** [comment] 2018-09-25 19:53
Hi,

This is because your current version of Xamarin.Mac (4.6.0.14) doesn't support Xcode 10.

This should be fixed with Xamarin.Mac from our Xcode 10 Preview Channel (currently version 4.99.3.741).

I'll close the issue for now but feel free to reopen if the problem is still not solved.

**Closed by VincentDondain** 2018-09-25 19:53 UTC

**Comment by p-lad** [comment] 2018-10-01 11:34
Hello,
This issue is not reproducible when tested with:-
Version 7.6.8 (build 38)
Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
Xamarin.Mac Version: 5.0.0.0
Xamarin.iOS Version: 12.0.0.15
Xamarin.Android Version: 9.0.0.20

Build Info: https://gist.github.com/mohakbarokar/6f7cb0a0834ecc8ad21bc054aaa2f3ea

Screen cast link :- https://www.screencast.com/t/t3g8a0XhP

Thanks.
